### ISSUE TITLE
branchs dos desafios anteriores indo junto com as novas

### ISSUE THREAD

**Issue by Cleysonlb** [da2k/curso-javascript-ninja#100]
Fala @fdaciuk, rapaz to com um "problema" ao editar o arquivo, fazer o commit e dar push ele envia branchs dos desafios anteriores juntos.
Exemplo: Enviei a branch do challenge 02 e na mesma branch esta indo do challenge 01

**Comment by fdaciuk** [comment]
É que quando você está criando a branch do challenge-02, por exemplo, você está fazendo isso dentro da branch challenge-01. 

Pra criar uma branch nova, ela precisa ser baseada na master. Pra isso, você precisa dar um `git checkout master`, e então dar o `git checkout -b challenge-02`, por exemplo ;)

**Comment by Cleysonlb** [comment]
Ahhh, então ai esta o problema!! Vlw mesmo @fdaciuk, to com tudo pronto aqui para reenviar os challengers! ;)

**Comment by fdaciuk** [comment]
Show :dancer:
