### ISSUE TITLE
[Aula 01] - Sobre o GitHub

### ISSUE THREAD

**Issue by fnaomiwamizu** [da2k/curso-javascript-ninja#10037]
Olá, Fernando. boa tarde! 

Sou bem novata no uso do GitHub e estou tendo dificuldade para submeter meus exercícios no GitHub.
 No vídeo 7 da Seção 01 - Desafio da semana você comenta no minuto 6:27 que após resolver o exercício (no meu caso, a challenge 01), deveria aparecer a linha verde com o botão "Compare & pull request", mas não aparece nada para mim, e a partir daí o uso do site foi ficando cada vez mais difícil.

Quando eu fui realizar o exercício, criei a branch "challenge-01" no local do "master", mas agora sumiu e não encontro o meu exercício resolvido.

Por favor, poderia me ajudar a entender o uso do sistema e onde estou errando? 

Obrigada! 

Abs.

**Comment by fdaciuk** [comment]
Oi @fnaomiwamizu! Desculpe pela demora na resposta!

Sempre que for abrir uma issue aqui no GitHub, por favor, deixe o meu `@` marcado pra eu receber a notificação, senão eu não vejo sua dúvida, ok? =)

Sobre o GitHub: esse botão de "Compare & pull request" aparece nos primeiros 30 minutos que você fez o "push" do código para uma nova branch. Passados esses 30 minutos, é preciso abrir o pull request de forma manual.

Mas assim, não se preocupe com isso: usar o GitHub é importante, mas se isso estiver travando os seus estudos, não precisa enviar os Pull Requests.

O importante é você tentar resolver os desafios, ainda que só na sua máquina mesmo.

Depois você pode voltar e estudar como usar Git e GitHub, ok? =)

**Comment by fdaciuk** [comment]
Oi @fnaomiwamizu! Conseguiu resolver? Vou fechar a issue, mas fique super à vontade para abrir uma nova se precisar de qualquer ajuda, ok?

**Comment by fnaomiwamizu** [comment]
feito Daciuk =)

Consegui sim. Na verdade tenho usado e feito os exercícios e corrigido na
própria página do exercício, por meio do acompanhamento dos vídeos de
resolução.

Obrigada!

Att.
*Fernanda Naomi Iwamizu*
*+55 **(11) 96767-1267 *


Em qui., 1 de dez. de 2022 às 13:46, Fernando Daciuk <
***@***.***> escreveu:

**Comment by fdaciuk** [comment]
Perfeito! Qualquer dúvida, fique à vontade para perguntar :D
