### ISSUE TITLE
Desafio semana 2 

### ISSUE THREAD

**Issue by pabloh25** [da2k/curso-javascript-ninja#10042]
@fdaciuk estou com dificuldades em verificar se o valor do parâmetro está sendo passado ou não, quando coloco 1 ou 2 valores ele retorna NaN e não sei identificar onde está o problema.

```js
function tresArgumentos(a,b,c){
... if(a === 0 || b === 0 || c === 0){ "Preencha todos os 3 valores"} else ( a >= 1 && b >= 1 && c >= 1)
... return a * b * c + 2
... }
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pabloh25! Você está testando se os valores são iguais a zero. Zero é um número que precisa, obrigatoriamente, ser passado.

Para saber se o valor não foi passado, você precisa testar se ele está **indefinido**. Lembra quando falamos sobre isso? =)

**Comment by pabloh25** [comment]
Entendi @fdaciuk , eu estava tentando a condicional sem o return no if 
![image](https://user-images.githubusercontent.com/50158934/200177459-c354120e-1eab-4cf5-9e97-726b4b9ef452.png)

E ai quando realizava o teste ele retornava NaN
Estava assim antes 
![image](https://user-images.githubusercontent.com/50158934/200177510-5b5e5e3f-1e4c-4b62-8a37-cae77a0a714d.png)

Por isso tentei com um valor zero, mas ficou mais claro agora que quando faço o uso do zero, ele precisa de um valor sendo informado.

Obrigado pelo retorno.

**Comment by fdaciuk** [comment]
Boa @pabloh25! Qualquer dúvida, só avisar :D
