### ISSUE TITLE
Aula 08 - Programação funcional

### ISSUE THREAD

**Issue by leandrofsp** [da2k/curso-javascript-ninja#1004]
Fala. 
Acho que não entendi muito bem a essência da programação funcional. Fico perdido quando se fala nela, será que mais pra frente conforme vamos aplicando vou entendendo?

vlw

**Comment by fdaciuk** [comment]
Opa @leandrofsp, tudo certo? =)

Então, nessa aula começamos uma introdução à programação funcional, e como você pode se aproveitar desse paradigma usando JavaScript.

Mas programação funcional é um assunto bastante extenso. É uma forma diferente de pensar, um "estilo" de se programar =)

Durante o curso vamos falar com mais detalhes sobre alguns outros pontos de programação funcional sim, mas teremos alguns meetups em breve pra falar de alguns assuntos mais específicos que não são o foco direto do curso. 

Programação funcional é um deles =)

**Comment by leandrofsp** [comment]
Opa tudo certo, tentando virar ninja haha.

É verdade é um assunto gigante ja fui em alguns eventos e programação funcional sempre está em pauta.

Legal, será um meetup para os alunos ou no geral?

Obrigado pelo esclarecimento.

**Comment by fdaciuk** [comment]
Isso mesmo @leandrofsp! Nós já fizemos dois desses =)

Em breve vamos marcar o próximo =)
