### ISSUE TITLE
Configurar o Git para abrir o Sublime text por comando. 

### ISSUE THREAD

**Issue by gabs-vieira** [da2k/curso-javascript-ninja#10073]
Fernando, tu poderia me ajudar a configurar o git para a partir dele conseguir abrir o editor de texto usando o comando "subl" ou o vscode pelo comando "code"?

Ja configurei o git (`user.name, user.email` `e core editor (``git config --global core.editor "'C:\Program Files\Sublime Text\sublime_text.exe' -n -w"`)). 
Além disso, coloquei no _vim .bashrc_ o comando " `alias subl="C:\Program Files\Sublime Text\sublime_text.exe"` "

Entretanto, não está rodando rs. 

@fdaciuk

**Comment by fdaciuk** [comment]
Opa! Eae @gandwizz :D 

Vamos lá: como você está no Windows, eu não consigo testar o que vou te passar, mas vou tentar te ajudar, ok? =) 

Primeiro é preciso definir qual editor você vai usar: Sublime ou VSCode?

**Comment by gabs-vieira** [comment]
Certo! Muito obrigado.

Vou usar o VSCode.

**Comment by fdaciuk** [comment]
Certo! Você consegue abrir seu projeto no vscode pelo terminal, com o comando `code .`?

**Comment by gabs-vieira** [comment]
Daiuk, não sei porque motivos, mas consegui fazer ele abrir usando esse comando tanto no Shell, tanto no git. xD

**Comment by gabs-vieira** [comment]
Daciuk* rsr Muito obrigado mestre. Mas logo logo vou trocar do windows pra um linux... sem burocracia. Inclusive, estou gostando muito do curso. JS puro. Obrigado pelo material e pela tua atenção

**Comment by fdaciuk** [comment]
Deu certo? Show! Você chegou a definir o `core.editor` certinho, pra abrir o VSCode quando você for fazer algum commit, por exemplo?

> Mas logo logo vou trocar do windows pra um linux... sem burocracia. 

Boa!

> Inclusive, estou gostando muito do curso. JS puro. Obrigado pelo material e pela tua atenção

Que massa que está curtindo mano! Qualquer dúvida, fique super à vontade pra mandar aqui :D

**Comment by gabs-vieira** [comment]
>Bem lembrado! Eu creio que esteja certo.  Usei o comando anterior para configurar o `core.editor` " `git config --global core.editor "'C:\Users\thugs\AppData\Local\Programs\Microsoft VS Code\Code.exe' -n -w"` " . 

Seria isso? 

![core editor](https://user-images.githubusercontent.com/69372836/210796236-c36626f7-065e-4a0e-9441-ba9fbf3d6d56.png)

**Comment by fdaciuk** [comment]
É pra ser isso mesmo. Pra testar, na hora de comitar, não use o `-m` que ele vai abrir o editor, aí você consegue ver se deu certo =)

**Comment by gabs-vieira** [comment]
Funcionou! Muito obrigado =)

**Comment by fdaciuk** [comment]
Boa! Qualquer coisa, grita ae :D
