### ISSUE TITLE
Erro na hora de clonar o repositório no terminal.

### ISSUE THREAD

**Issue by MFlor3ncio** [da2k/curso-javascript-ninja#10116]
Olá Fernando, estou fazendo o seu curso e estou com uma dúvida na hora de clonar o repositório no meu terminal,  aparece a seguinte mensagem no terminal:

git clone git@github.com:MFlor3ncio/curso-javascript-ninja.gitCloning into 'curso-javascript-ninja'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Gostaria de uma ajuda nisso, muito obrigado e aguardo o retorno.

Att,
Matheus Florencio

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MFlor3ncio! Provavelmente você não configurou sua chave SSH no GitHub.

Tem duas formas de resolver esse problema: a mais fácil é clonar usando "HTTPS" ao invés de "SSH".

A segunda é um pouco mais chatinha, que é fazer a configuração do SSH. Você não precisa fazer especificamente pra esse projeto, mas vai ser importante para outros projetos seus, onde você vai precisar enviar coisas para o GitHub. Aqui tem as instruções de como fazer, com base no sistema operacional que você está usando:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh
