### ISSUE TITLE
[Aula 1] Dúvida sobre pull resquest

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10147]
Olá, Fernando!

Sei que não está mais corrigindo os pull requests, mas fiquei procurando como fazer caso precisasse e não consegui entender. Tirei um print da tela. Você poderia me dizer como fazer o pull request? Nessa tela onde deveria clicar para fazer o pull request?

![image](https://user-images.githubusercontent.com/54543420/236463946-bba9c568-58d8-496b-804c-1bee9be5315b.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! É bem simples: pelo seu repositório mesmo, é só clicar ali na aba "Pull Requests":

![image](https://user-images.githubusercontent.com/487669/236472492-cedb6d22-303b-418d-bf89-d60aaf889be2.png)

---

Na tela que carregar, clique no botão "New pull request":

![image](https://user-images.githubusercontent.com/487669/236472830-b7e5da2b-7f56-4f7c-8153-ccb1a671a18a.png)

---

Na tela que carregar, você vai ver 4 selects:
- O primeiro é referente ao repositório principal, que vai receber o Pull Request;
- O segundo é a branch do repositório principal que você vai enviar o Pull Request. Não precisa mexer em nenhuma dessas duas opções.
- O terceiro é o seu repositório, onde tem as novas alterações;
- E o quarto é a branch do seu repositório que contém as alterações. É aqui que você seleciona a branch que tem as alterações, e que você quer enviar o Pull Request:

![image](https://user-images.githubusercontent.com/487669/236473730-b718efb3-2987-4cda-9e38-aff585361b8f.png)

---

Ao selecionar a branch, se houverem alterações, você vai ver um botão "Create pull request", e logo abaixo você vai conseguir ver as alterações que foram feitas, em comparação com o que está na branch do repositório principal.

Se estiver tudo certo, clique no botão "Create pull request" e pronto! =)

Qualquer dúvida, só avisar :D
