### ISSUE TITLE
[Aula 2] Desafio #02 dificuldade no Git

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10148]
Olá, Fernando! Estou com dificuldade no Git.

Primeiro o que foi digitado em "curso-js-ninja"? Foi dois "l" (de laranja)? Não consigo exibir essas informações que aparecem no seu? Isso é o tamanho do arquivo?

![image](https://user-images.githubusercontent.com/54543420/236557821-87f65583-e121-4f49-965b-101d6dd1fa16.png)

No meu não aparece como no seu entre parênteses (master) será que fiz algo errado?

![image](https://user-images.githubusercontent.com/54543420/236558391-e37d5b6d-b252-4787-9913-6be69a67bc54.png)

Segue print do meu Git:

![image](https://user-images.githubusercontent.com/54543420/236558482-fa05342d-31a1-405d-a4d8-180bd062dc1b.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Esse é o comando para listar arquivos (no meu caso, são dois L minúsculos).
No windows provavelmente é `dir`.

Para usar terminal no windows, recomendo instalar o WSL2, que é um terminal Linux dentro do windows. Dessa forma você vai conseguir usar praticamente os mesmos comandos que eu usei no curso =)

**Comment by anarsantos** [comment]
Valeu! Desculpa incomodar, mas só mais uma pergunta. Tô tentando descobrir o comando que limpa o terminal, já digitei de um tudo, mas nenhum comando limpa o terminal. Qual seria o comando que limpa o terminal no Windows?

**Comment by fdaciuk** [comment]
Sem problemas, pode perguntar sim =)
Se não estou enganado, no windows é `cls`. No linux (ou no WSL2) é `clear` ou `Ctrl + L`.

**Comment by anarsantos** [comment]
Obrigada pela disponibilidade, Fernando :)
Tô tendando subir a resolução do Challenge 02 e apareceu uma mensagem de erro. Você poderia me ajudar?

![image](https://user-images.githubusercontent.com/54543420/236863342-95ee5158-3956-4b7b-b90a-b64bf07bfaff.png)

**Comment by anarsantos** [comment]
Eu de novo rs. Acho que fiz uma pequena confusão, fui tentar criar uma branch pelo terminal enviando para o meu repositório daí  acho que criei no repositório original e estou confusa agora.

Abriu uma página com Regras de proteção da branch e tem um bando de opções para clicar não sei o que fazer e não achei a branch challenge-02 no meu repositório. Segue o print da página:

![image](https://user-images.githubusercontent.com/54543420/236890911-7e3eb7f8-82d7-4e4d-81c1-25da0410859f.png)

E parece que meu Pull request foi para o seu repositório?! Não tenho muita habilidade com o GitHub, desculpe-me.

![image](https://user-images.githubusercontent.com/54543420/236891416-87bd8fae-47e1-4339-aaf0-64f790f337cc.png)

**Comment by fdaciuk** [comment]
Oi @anarsantos! Você conseguiu resolver o erro do primeiro print? Olhei aqui o seu repositório e a branch `challenge-02` está lá, então acho que deu certo né? xD

Sobre as regras de proteção de branch, pode ignorar, não precisa mexer em nada disso aí.

E sobre o pull request ser enviado para o meu repositório, é isso mesmo: sempre que você abre um pull request, você está enviando alterações do seu repositório (no caso, o `anarsantos/curso-javascript-ninja`) para o repositório principal, que irá receber as alterações (`da2k/curso-javascript-ninja`). 

Pra você saber se está enviando do seu repo para o repo correto, é só olhar ali os selects que aparecem: o da esquerda é o repo e branch principais. Os da direita é o seu repo e a sua branch =)

**Comment by anarsantos** [comment]
Oi, Fernando! Então, depois de muito sofrimento, lágrima e suor consegui rs Sou um pouco perdida com o GitHub e seus comandos, espero que um dia isso melhore. Depois atualizei a página e daí vi a branch chanllenge-02 no meu repositório.

Sobre as alterações do meu repositório enviar para o principal eu não sabia, eu achava que tinha feito o fork e daí vai sempre para o meu. Tenho muito que aprender sobre GitHub rs.

Obrigada mais uma vez pela atenção ;)

**Comment by anarsantos** [comment]
Esqueci de perguntar mais uma coisa.

Sempre que eu for subir as alterações de um novo desafio para que não apareça aquela mensagem de erro preciso digitar os comandos: 
git checkout -b "o nome da branch"
git push origin "o nome da branch"
É isso mesmo?

**Comment by fdaciuk** [comment]
Vou deixar aqui um guiazinho rápido de git pra te ajudar:

O `git checkout -b nome_da_branch` é para criar uma nova branch e já mudar pra ela. Aí você pode começar a fazer as alterações que precisa. Lembrando que, antes de executar esse comando, é preciso estar na branch principal `main` ou `master`, dependendo de como está seu repositório.

Para garantir que você está nessa branch, é só executar:

```
git checkout master
```

ou

```
git checkout main
```

Para ver a branch em que você está, pode rodar `git branch`, que o nome da branch selecionada será exibida com um asterisco do lado.

Quando você terminar de alterar, você executa: 

```
git add nome_do_arquivo
```

para adicionar as alterações que você acabou de fazer. Se quiser adicionar todos os arquivos alterados, não precisa passar os nomes deles um a um, pode usar o ponto para representar todos os arquivos alterados naquele diretório. Então o comando ficaria: 

```
git add .
```

Depois de adicionar, você faz o commit das alterações. O `commit` é a confirmação daquela alteração: ao realizar o `commit`, você nomeia uma entrada na árvore do Git, pra que você consiga navegar pelas alterações que fez em todo o projeto. O comando é: 

```
git commit -m "Aqui a mensagem de commit detalhando as alterações feitas"
```

Com tudo adicionado e comitado, é hora de "empurrar" as alterações para o seu repositório com `git push origin nome_da_branch`.

A qualquer momento você pode executar `git status` para verificar o status atual das suas alterações =)

Acho que é isso. Qualquer dúvida, fique à vontade para perguntar :D

**Comment by anarsantos** [comment]
Valeu mesmo pelo guia rápido, espero não passar muito sufoco das próximas vezes, mas sou um pouco atrapalhada é muito provável que me confunda em algum momento rs. Novamente muito obrigada :)

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer dúvida pode perguntar =)
Se estiver com muita dificuldade com git, não se preocupe com isso no início do curso: foque no curso primeiro, e depois você pode começar a estudar git mais a fundo, ok? =)

**Comment by anarsantos** [comment]
Vou seguir seu conselho. Tenho outra dúvida, ontem quando fui subir o desafio 02, vi que havia digitado errado o 01. É possível renomear a branch?

**Comment by fdaciuk** [comment]
É sim! Só acessar a branch que vc quer renomear (`git checkout sua_branch`) e então usar o comando 

```
git branch -m novo_nome
``` 

=)

**Comment by anarsantos** [comment]
Espero que essa seja a última pergunta do dia, que já tô cansada de perguntar. Acabei de baixar o Node, mas não consigo digitar os códigos. Ele tem a aparência do Git, quando vou criar uma variável aparece mensagem de erro. Só consigo criar as variáveis e objetos no console do Chrome. Como faço para poder criar os códigos no Node como você ensina nas aulas?

**Comment by fdaciuk** [comment]
Sem problemas, pergunte à vontade =)

Tem duas formas de você executar o código JavaScript usando o Node:

1) Você pode só digitar o comando `node`, e ele vai abrir um REPL no seu terminal (REPL é um ambiente parecido com o Console do navegador, onde você pode digitar comandos JavaScript, um por linha).

2) Uma outra forma mais simples de executar código JavaScript é criar um `arquivo.js` com o código que você quer executar, e então digitar no terminal `node caminho_do_seu/arquivo.js`. Esse comando vai executar o código que está no `arquivo.js`.

Usando o REPL, todo comando que você digitar vai já mostrar o resultado dele ali no terminal. 

Por exemplo: digite `node` e você verá um prompt no terminal assim:

![image](https://github.com/da2k/curso-javascript-ninja/assets/487669/934ca86e-a89e-4b4b-b478-2eed15a06c7f)

Se você digitar qualquer código JavaScript válido, você vai receber o resultado da expressão digitada. Por exemplo: ao digitar `2 + 2` e dar enter, você vai ver o resultado `4`:

![image](https://github.com/da2k/curso-javascript-ninja/assets/487669/334933da-8065-41b8-a87e-f22e14252145)

Para sair do REPL e voltar para o terminal, digite `Ctrl + C` duas vezes, ou `Ctrl + D`.

Agora, se você criar um `arquivo.js` e usar o comando `node arquivo.js` para executar o conteúdo do arquivo, o conteúdo dele será avaliado normalmente, mas o resultado só será exibido se você usar o `console.log` (vou mostrar isso na aula 4 ou 5).

Aqui um exemplo: crie um arquivo `teste.js`, e coloque o seguinte conteúdo nele:

```js
console.log(2 + 2);
```

Então execute com `node teste.js`. Você verá o resultado `4` no terminal =)

Ficou claro?

**Comment by anarsantos** [comment]
Ficou claro sim. Muito obrigada. Mas agora acho que chega de perguntas pelo menos por hoje rs. Preciso avançar nos estudos aqui :)

**Comment by fdaciuk** [comment]
haha! Bons estudos, e pergunte sempre que precisar! :D
