### ISSUE TITLE
[Aula 06] Operador vírgula

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10157]
Oi, Fernando! Na aula 06 tem o retorno abaixo e fiquei confusa, não entendi muito bem. A parte "x += 1" eu entendo como funciona, coloquei abaixo. Mas e depois da vírgula? O segundo "x" é a repetição do primeiro?

return (x += 1, x);
x = x + 1
x = 0 + 1
x = 1

No exemplo que você passou de ternário também não entendi. O null não é false? Como foi passado na aula de Falsy?
A resposta não seria 1?

> var x = null === false ? 1 : 2;
undefined
> x
2

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Quando você usa o operador vírgula, as expressões à esquerda são avaliadas, mas o resultado retornado é sempre a última expressão, mais à direita.

No caso, o que acontece aqui é:

```js
return (x += 1, x);
```

A expressão `x += 1` será avaliada, mas o interpretador do JS não faz nada com ela, ele simplesmente passa para a próxima expressão, que é `x` (no caso, `x` vai ser avaliado e o valor dele vai ser retornado).

Então, como apenas a expressão da direita é retornada, o `return` vai ser avaliado com a última expressão, retornando apenas o valor final de `x`.

Seria o mesmo que fazer:

```js
x += 1;
return x;
```

A primeira expressão é avaliada, mas somente a última é retornada =)

Sobre o `null` ser `false`, na verdade isso não é verdade. `null` é _falsy_, ou seja: **se convertido para booleano**, o resultado de `null` será `false`.

Mas a expressão do ternário está testando o valor exato de `null` contra o valor exato de `false`. O resultado é `2` pois `null` e `false` são valores diferentes.

Se você fizesse:

```js
var x = !null ? 1 : 2
```

Aí sim o resultado seria `1`, pois o operador `!` **converte o valor para booleano** e então **inverte o resultado**. `null` convertido para booleano `false`. E invertendo o valor booleano `false`, temos `true`. Então nesse caso o resultado seria `1`, não `2`.

Ficou mais claro?

**Comment by anarsantos** [comment]
Acho que esse é um conhecimento muito avançado para os meu dois neurônios rsrs.

No caso do retorno, entendi que o JS não fará nada com a primeira expressão, vai retornar o "x" após a vírgula. Mas, contudo entretanto, todavia ele retorna o valor 1. De onde vem isso?

> function myFunc() {
... var x = 0;
... return (x +=1, x);
... }
undefined
> myFunc();
1

**Comment by fdaciuk** [comment]
> Acho que esse é um conhecimento muito avançado para os meu dois neurônios rsrs.

É nada! Talvez o que não ficou claro é que, apesar de ignorado o resultado da expressão `x += 1`, ela ainda assim é avaliada, e `x` recebe o novo valor, ou seja:

```js
x += 1;
```

É o mesmo que:

```js
x = x + 1;
```

Logo, o valor da variável `x` que era zero antes dessa expressão ser executada, agora vai ser `1`, pois:

```js
function myFunc () {
  // a próxima linha define o valor inicial de `x` como zero
  var x = 0;

  // a próxima linha faz uma reatribuição na variável `x`. 
  // O novo valor é `x + 1`, ou `0 + 1`, que é igual a `1`. 
  // Logo, à partir daqui, o valor de `x` não é mais zero, e sim `1`.
  x += 1;

  // e aqui a expressão `x += 1` já foi executada. 
  // Como o novo valor de `x` é `1`, é esse valor que a função vai retornar =)
  return x; 
}
```

Ficou melhor pra entender agora? =)

**Comment by anarsantos** [comment]
Entendi agora. E reli a explicação do null que tinha ficado um pouco perdida e agora fiz o download do entendimento rs. Valeu!

**Comment by fdaciuk** [comment]
Boa, perfeito! Qualquer dúvida, só avisar :D
