### ISSUE TITLE
[Aula 3] Retorno da última função

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10154]
Oi, Fernando!

Não entendi por que precisa ser: 
' ' + pessoa.nome + ' ' + pessoa.sobrenome + ', tenho '
e não pode ser:
' ' + pessoa.nomeCompleto + ', tenho '

Coloquei a segunda opção "nomeCompleto" e óbvio que deu ruim, mas não entendi o porquê.

Mais dúvidas, eu posso criar a nova branch do desafio sem ter feito nenhuma alteração ou é melhor criar no final após ter resolvido os exercícios?

Última dúvida, como faço para encontrar as issues que você fechou? Fui dar uma olhada para pegar alguns comandos nas minhas dúvidas anteriores e não encontrei aqui no site.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Se você quiser usar a função `pessoa.nomeCompleto`, você precisa executar ela, usando os parênteses, para que você consiga usar o conteúdo de retorno da função: 

```js
pessoa.nomeCompleto()`

```

Nesse exemplo eu não usei essa função porque ela retorna uma frase, não apenas o nome completo. Aí a frase usada na função `pessoa.apresentacao` iria ficar estranha =)

> Mais dúvidas, eu posso criar a nova branch do desafio sem ter feito nenhuma alteração ou é melhor criar no final após ter resolvido os exercícios?

Pode criar antes sim, sem problemas. Desde que você não faça um `git add` ou `git commit` antes de criar a branch, você pode criar ela antes ou depois de resolver o desafio, não vai fazer diferença =)

> Última dúvida, como faço para encontrar as issues que você fechou?

Na lista de Issues você vai ver uma link "Closed". Ele fica meio escondido mesmo, vou mandar um print pra você ver:

![image](https://github.com/da2k/curso-javascript-ninja/assets/487669/84fa870f-f413-4ddb-8a17-1193435957f7)

Só clicar ali que você vai ver todas as issues fechadas.

Se quiser, você ainda pode filtrar somente pelas issues que você criou, pra facilitar encontrar se ela estiver perdida em meio a várias outras issues fechadas. É só clicar ali no select "Author" e escrever seu nome de usuário `anarsantos` e dar enter =)

**Comment by anarsantos** [comment]
Esqueci que a função nomeCompleto tem uma frase, ficaria estranho mesmo.

Se você não mostra o "Closed" não acharia nunca. Valeu pelas respostas :)

**Comment by fdaciuk** [comment]
Nada! Qualquer dúvida, só avisar :D
