### ISSUE TITLE
[Aula 07] Desafio

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10158]
Oi, Fernando! Tem mais de meia hora que tento saber porque aparece NaN e não sei onde está o erro. O código está igual ao seu.
![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/8f8c131a-9f1b-4f8a-8481-9000f5913b96)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! `NaN` significa `Not a Number`. Não sei se você já chegou nessa parte do curso, mas você vai receber como resultado `NaN` sempre que tentar fazer uma operação numérica com algum dado que não seja número, ou não seja possível converter para número.

O problema está acontecendo por causa da linha `12`, onde você está tentando usar o operador de pós-incremento em um array =)

Não precisa desse operador aí, pode remover ele :D

**Comment by anarsantos** [comment]
Obrigada, isso é o cérebro pedindo descanso.

**Comment by fdaciuk** [comment]
Bom descanso, e bons estudos :D
