### ISSUE TITLE
[Aula 05] Parâmetros de Funções como arrays e objetos

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10156]
Olá, novamente! rs
Estou aqui tentando reproduzir os argumentos que você está passando na aula, mas deu bug no meu Node porque não fica igual ao seu.
Em "myFunction(['fernando', 1, true, 34]);" retorna 1 e não o array como no vídeo. Não entendi?

> function myFunction2(arg) {
... return arg[1];
... }
undefined
> myFunction2(arr);
2
> myFunction2([1, 5, 7, 8]);
5
> myFunction(['fernando', 1, true, 34]);
1
> myFunction
[Function: myFunction]
> myFunction(['fernando', 1, true, 34]);
1
> myFunction(['fernando', 1, true, 34]);
1

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Veja que a sua função `myFunction2` está retornando o elemento que está no índice `1` do array (ou seja, o segundo elemento). Por isso ele retorna `1` quando você passa o array `['fernando', 1, true, 34]` =)

**Comment by anarsantos** [comment]
Mas eu mudei para myFunction (myFunction(['fernando', 1, true, 34]);) não teria que mostrar o array?

**Comment by fdaciuk** [comment]
Como você criou a `myFunction`? Não aparece ali no seu código a definição dela =)

**Comment by anarsantos** [comment]
Sorry rs, Acho que estou um pouco cansada de código.

function myFunction(arg) {
... return arg;
... };

**Comment by fdaciuk** [comment]
Sem problemas, estudar muito cansa mesmo :D

Esse código deveria retornar o array sim! Tenta fechar o REPL do Node e abrir de novo, e colocar essa função novamente, só pra ter certeza que você usou a função correta =)

**Comment by anarsantos** [comment]
Fechei e deu bom, acho que estou cansada rs

**Comment by fdaciuk** [comment]
É hora de parar um pouco! Bom descanso aí :D

**Comment by anarsantos** [comment]
Obrigada, pra vc também :)
