### ISSUE TITLE
[Aula 05] Revisão do desafio da semana #04 - Parte 3

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10155]
Oi, Fernando! Estou tendo problema no método adicionarPessoas, fiz igual ao que você mostra no vídeo, mas aparece "NaN", não entendi onde está o erro? Já apaguei e refiz várias vezes. Copiei o código todo do console para você ver.

carro.obterModelo = function() {
    return carro.modelo;
};
ƒ () {
    return carro.modelo;
}
carro.obterMarca = function() {
    return carro.marca;
};
ƒ () {
    return carro.marca;
}
carro.obterMarcaModelo = function() {
    return 'Esse carro é um ' + carro.obterMarca() + ' ' + carro.obterModelo();
};
ƒ () {
    return 'Esse carro é um ' + carro.obterMarca() + ' ' + carro.obterModelo();
}
carro.adicionarPessoas = function(numeroPessoas) {
    return 'Já temos ' + carro.quantidadePessoas + ' pessoas no carro!';      
};
ƒ (numeroPessoas) {
    return 'Já temos ' + carro.quantidadePessoas + ' pessoas no carro!';      
}
carro.adicionarPessoas(2);
'Já temos 0 pessoas no carro!'
carro.adicionarPessoas = function(numeroPessoas) {
    var totalPessoas = carro.quantidadePesoas + numeroPessoas; 
    return 'Já temos ' + totalPessoas + ' pessoas no carro!';      
};
ƒ (numeroPessoas) {
    var totalPessoas = carro.quantidadePesoas + numeroPessoas; 
    return 'Já temos ' + totalPessoas + ' pessoas no carro!';      
}
carro.adicionarPessoas(2);
'Já temos NaN pessoas no carro!'

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Na criação do objeto carro, você chegou a criar a propriedade `quantidadePessoas`?

**Comment by anarsantos** [comment]
Sim, agora que vi que quando fui chamar "quantidadePessoas" faltou um "s" na digitação :(. 
"var totalPessoas = carro.quantidadePesoas + numeroPessoas;"

**Comment by fdaciuk** [comment]
Perfeito! Infelizmente isso acontece muito com JavaScript, por isso é bom prestar atenção =)
Mais para o final do curso eu vou mostrar algumas ferramentas que ajudam a pegar esse tipo de problema, mas é bom acostumar desde já a tentar encontrar esse tipo de erro "só no olho", já que é bem comum isso acontecer xD

**Comment by anarsantos** [comment]
Pois é, eu só atenta, mas a digitação, às vezes, não é. Ainda chamaram minha atenção quando comentei isso da falta de "s". E vc é formada em letras, aff ainda preciso ouvir desaforo. rs Como você falou, é algo comum então preciso treinar meu olho para pegar esse tipo de erro e outros. É a vida! rs

**Comment by fdaciuk** [comment]
Nem faz sentido chamar a atenção por esse tipo de erro, isso é muito comum mesmo, todo mundo erra digitando xD

Com o tempo você vai começar a ver alguns erros, e quando for "voltar" no código pra tentar entender o que está errado, vai perceber que a maioria deles é por conta  de _typo_ mesmo =)

Mas ainda que existam ferramentas que podem ser usadas para pegar esses problemas mais facilmente, eu recomendo você aprender desse modo, sem ferramentas. Isso vai deixar seu olho muito mais treinado para erros de digitação xD

**Comment by anarsantos** [comment]
rs o erro que mais cometo é o de digitação, o corretor altera as palavras no whats e nem vejo rs, mas é a vida.

Por enquanto vamos seguir sem ferramentas rs Valeu pelas dicas!

**Comment by fdaciuk** [comment]
Boa! Siga os estudos aí, e qualquer dúvida, pode perguntar :D
