### ISSUE TITLE
[Aula 10] Dúvina no desafio, erro no invalid

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10168]
Olá, senhor Daciuk! 

A operação "invalid" deu erro: is not a function. Preciso colocar o "invalid" na var operation?

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/380b05ee-15ba-45b3-81ce-854068a5747a)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Essa mensagem significa que `invalid` recebeu algum valor retornado da chamada da função `calculator`, mas esse valor retornado não é uma função.

Tem que ver a implementação da função `calculator`, ela deveria sempre retornar uma nova função que espera os dois números, já que você está executando a função na linha 204 =)

**Comment by anarsantos** [comment]
Muito obrigada! Um dia serei assim que nem você rs, olharei e já saberei onde está o erro. Fui olhar a função calculator e de fato estava defeituosa, tinha aspas onde não deveria. Os erros quase sempre são coisas "mínimas" acentos, pontos etc coisas que não deveriam estar ali.

**Comment by fdaciuk** [comment]
Com certeza você chega sim, isso é só tempo e costume com a linguagem! Com os tempo, os problemas que hoje são novos começam a se tornar "comuns", aí fica fácil saber o que é =)

> Os erros quase sempre são coisas "mínimas" acentos, pontos etc coisas que não deveriam estar ali.

Quando estamos começando é assim mesmo! Siga em frente, e conte comigo para o que precisar =)

**Comment by anarsantos** [comment]
Espero que seja assim como você está falando, todos os dias penso em desistir. Acho que nunca vou aprender, fazer um exercício sozinha. Mas bora tentar acreditar que vai melhorar e vai ficar menos difícil. Obrigada :)

**Comment by fdaciuk** [comment]
Esse processo leva alguns meses, às vezes alguns anos. Então não desista! O começo nunca é fácil pra qualquer coisa nova que você esteja aprendendo, mas ser resiliente vale a pena =)
