### ISSUE TITLE
[Aula 9] Desafio dúvida no ternário

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10166]
Olá, Fernando! Quero dizer que gostei bastante da parte onde tínhamos que alterar a ordem do código para que funcione. Embora ainda seja um nível bem básico e iniciante é bacana esse tipo de exercício.

Minha dúvida sobre o o ternário que está em myFunction2 é: o primeiro "sum" que aparece antes da interrogação é o nome da variável ou o nome da função?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! O `sum`, nesse caso, é o nome da variável que recebeu a função com o mesmo nome. Se você mudar o nome da função ali vai conseguir ver isso melhor. A função pelo nome só pode ser acessada no escopo interno dela, nunca de fora. Do lado de fora, a função só é acessível pelo nome da variável =)

**Comment by anarsantos** [comment]
E daí você só acessa o nome da função "sum()" porque você colocou o nome da variável da função certo?

**Comment by fdaciuk** [comment]
Isso mesmo! Não é obrigatório usar um nome na hora de definir uma função como expressão (atribuindo para uma variável, por exemplo). Na época que o curso foi gravado, era muito comum dar para a função o mesmo nome da variável para facilitar o debug, mas hoje em dia os navegadores já conseguem identificar o nome da função pelo nome da variável usada =)
