### ISSUE TITLE
[Aula 12] Problemas para subir o desafio

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10172]
Boa tarde, Fernando!

Me atrapalhei toda, não subi a aula 11 e daí criei a aula12 e quando foi subir tinha que subir os dois. Deu uma confusão e não sai do lugar. Não sei como resolver. Você poderia me ajudar? Não consigo ir para a branch do challenge 12.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/f5004c47-2228-4406-a585-433039ff2064)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! A primeira coisa a fazer é reverter o commit que você acabou de fazer. Se já tivesse feito o `push` seria mais chatinho de resolver, mas como está local ainda, vai ser tranquilo.

A primeira coisa a fazer é ter certeza que você está na branch do `challenge-11`, que é onde vc comitou o arquivo do `challenge-12`. Se você executar:

```
git branch
```

E a branch do `challenge-11` estiver selecionada, está tudo certo até aqui. Senão, use o comando:

```
git checkout challenge-11
```

Agora você deve estar com a branch `challenge-11` selecionada. Confirme com:

```
git branch
```

Feito isso, confirme se o commit do challenge 12 está nessa branch mesmo, com o comando:

```
git log
```

Se o último log mostrado for o commit que você fez para o arquivo do challenge 12, é aqui que vamos começar a mexer! :D  

Me confirme se está tudo certo até aqui antes de prosseguirmos =)

**Comment by anarsantos** [comment]
Então, depois que mandei a mensagem pra vc, tentei novamente, mas sem esperança, o git checkout e por acaso deu certo rs. Fiz todo o desafio, vamos ver se vai subir certinho.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/0156e76a-ecea-4e32-8e72-1df5b11340de)

**Comment by fdaciuk** [comment]
Deu certo? Então perfeito! Qualquer coisa avisa aí :D

**Comment by anarsantos** [comment]
Parece que deu, vamos ver na hora de subir rs. 

Deixa eu aproveitar e te perguntar outra coisa. Sei que não passei nem da metade do curso, mas mesmo assim estou muito ansiosa. Sinto dificuldade de interpretar e colocar os execícios em código. Você teria alguma dica, algum material para fazer mais exercícios e ir aperfeiçoando a capacidade de interpretação?

**Comment by fdaciuk** [comment]
Olha, isso vem com a prática mesmo. As vezes é um termo que você ainda não pegou que fica difícil interpretar ou algo do tipo. O que você pode fazer é: depois de resolver um desafio, tente voltar ao mesmo depois de algum tempo (umas duas semanas), pra ver se você lembra do que foi feito ali e se está mais claro de entender o que você já viu.

Essa é uma forma de tentar evoluir com isso.

Posso te passar também alguns outros sites onde você pode tentar resolver algoritmos com JS, mas recomendo primeiro você focar no curso, pois pode ter algumas coisas que você vai ver ali nesses sites que ainda não viu no curso.

Nesse vídeo aqui eu mostrei vários sites que você pode usar pra estudar algoritmos em JS (ou qualquer outra linguagem):

https://www.twitch.tv/fdaciuk/clip/ImpossibleBillowingOstrichCurseLit-d4IJ6QnhtP3Ers_G

**Comment by anarsantos** [comment]
De fato esse lance de voltar é uma coisa que ajuda mesmo. Já tinha visto JS antes algumas coisas que vi até aqui no curso fizeram um pouco mais de sentido. O lance da repetição dá resultado. Vou seguir seu conselho depois vou para as plataformas com exercícios.

Valeu pelas dicas! :)

**Comment by fdaciuk** [comment]
Perfeito! Qualquer dúvida, estou sempre à disposição para ajudar =)
