### ISSUE TITLE
[Aula 14] Problemas no terminal

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10208]
Olá. Fernando! Retomei o curso de JS depois de muito tempo me atrapalhei na hora de criar a branch e não coloquei o "-b" e daí estou com dificuldade de rodar o código no termnal. Você conseguiria me ajudar?

Digito o comando "node challenge..." e não exibe os consoles.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/9c1d1a5b-ad92-4186-882c-c42a9cf11af0)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Você chegou a executar a IIFE? Não dá pra ver todo o código pelo print, mas pode ser esse o problema =)

Qualquer coisa, faz um push pro seu repo aqui no GitHub e manda o link que eu dou uma olhada no código =)

**Comment by anarsantos** [comment]
Se por acaso o senhor chama de executar a IIFE os "()" no final antes do ponto e vígula não executei não rsrs

Após executar como num passe de mágica apareceu, cê vê como são as coisas rsrs. Tô a mais de 1h nisso afff

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/2e1551d8-aa2c-4577-aae4-df8778aa4206)

**Comment by fdaciuk** [comment]
É isso mesmo hehe! É que a ideia da IIFE é ser uma função auto-executável: você cria a função e já executa ela, sem atribuir para uma variável ou nomear pra chamar depois =)

Como funções são _lazy_ em JS, o conteúdo de uma função só é executado quando a função é executada (usando o operador `()`).

Mas que bom que era isso! Bons estudos, e qualquer dúvida, pode mandar que eu te ajudo :D

**Comment by anarsantos** [comment]
Talvez esse conceito de autoexecutável ainda não tenha ficado claro na minha mente de dois neurônios rs. Mas até a seção 33 tem que ficar rs. Valeu pela ajuda!

**Comment by fdaciuk** [comment]
Vai ficar sim! Se não ficar, só perguntar que eu explico quantas vezes for preciso :D
