### ISSUE TITLE
[Aula 15] Abrir o browser

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10209]
Olá, Fernando!

Você abriu o arquivo HTML pelo terminal com o Python, não consegui entender muito bem. Eu abri pela pasta do arquivo mesmo. Pelo terminal do VSCode também é possível abrir? Seria somente com o Phyton?

Abaixo segue o print da minha pasta, cliquei no ícone do Chrome e abriu.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/47f79d73-19bf-4999-bce0-3caeb9a8181b)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! O que eu mostrei na aula, na verdade, foi como subir um servidor local com Python, que seria uma simulação de como o seu projeto apareceria se estivesse hospedado em um servidor na web =)

Abrir o arquivo HTML clicando duas vezes vai funcionar para algumas coisas mais simples, mas quando você chegar na aula sobre como fazer requisições HTTP para conversar com um servidor, esse recurso ficará bloqueado se você abrir o arquivo dessa forma.

Por isso simulamos um servidor web, mas rodando localmente, no seu computador.

Hoje existem algumas bibliotecas que facilitam esse trabalho sem precisar do Python: o VSCode tem uma extensão chamada "Live Server" que serve exatamente para isso: ele cria um servidor local pra você e tê dá um endereço para você acessar o conteúdo do seu `index.html`:
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

Uma outra forma de fazer pelo terminal, é executando o comando abaixo no diretório onde está o seu arquivo `index.html`:

```
npx http-server -c-1 .
```

Você vai ver, no terminal onde executou esse comando, um endereço para acessar o conteúdo do seu HTML. É a mesma ideia de criar o servidor usando o Python, mas usando uma ferramenta diferente =)

**Comment by anarsantos** [comment]
Quantos conceitos professor, às vezes, dá desespero, mas 1% de mim diz que vai dar certo no final rsrs Obrigada viu! rs

**Comment by fdaciuk** [comment]
Relaxa, quando chegar nessa aula você vai ver que não tem nada demais =)
Mas isso é basicamente estudo complementar de web, vale a pena separar um tempo para estudar um pouco mais sobre o protocolo HTTP assim que você terminar o curso :D

**Comment by anarsantos** [comment]
Pode deixar, mais um tópico para estudar no final desse curso. Estou feliz que cheguei na aula 15, achei que nunca chegaria rs. Até o fim desse mês termino.

**Comment by fdaciuk** [comment]
Boa! Pode ir mandando suas dúvidas aqui! Bons estudos :D
