### ISSUE TITLE
[Aula 21] Problema ao preencher os campos "Nome" e "Email"

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10217]
Fernando, a coisa travou e não consegui decifrar o porquê. Pra mim está igual o seu.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/b889661d-8764-4f26-8bf9-66ab0c70682d)

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/131bfc9c-40fb-4c24-855e-ac906782b1ea)

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/a4230d06-7bd1-4922-b5f5-e74cb625fbb2)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Consegue subir aqui no GitHub o projeto e mandar o link pra eu ver o código todo? Normalmente esse erro acontece quando o HTML não tem a tag que você está tentando selecionar com `querySelector`, por exemplo. Aí a variável recebe `null` ao invés de receber um objeto =)

**Comment by anarsantos** [comment]
https://github.com/da2k/curso-javascript-ninja/compare/master...anarsantos:curso-javascript-ninja:challenge-20?expand=1

Espero que seja o link certo rs, sou meio atrapalhada no GitHub.

**Comment by fdaciuk** [comment]
Dá pra ver por esse link sim =)

Provavelmente o problema é nessa linha [aqui](https://github.com/anarsantos/curso-javascript-ninja/commit/3e9669a53bebdeac662a957035906a6cb35be6a2#diff-8a96bb82f11337c5b530780a975deae42f8dd07309b2eafd3a27358f2117170bR34). Veja que falta o fechamento das aspas duplas ali depois de `type="text` =)

**Comment by anarsantos** [comment]
Tô rindo, mas é de nervoso. Fiquei mais de 1h tantando achar o problema. O lado positivo é que vou prestar mais atenção aos fechamentos das coisas. rs
![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/84321520-86f1-493d-9520-1d810bd1e0c3)

**Comment by fdaciuk** [comment]
Isso acontece, e muito no começo, então não se preocupe! Aprenda com os erros. JavaScript é muito por pra isso, já que a linguagem não tem nenhum mecanismo que te avisa desse tipo de problema, a não ser os erros em runtime (quando você executa seu código).

O importante é sempre tentar entender o erro pra saber onde procurar. Com o tempo e prática você vai pegando tudo isso :D

**Comment by anarsantos** [comment]
Essa é a grande questão "tentar entender o erro pra saber onde procurar." Mas chego lá :)

**Comment by fdaciuk** [comment]
É que é a primeira vez que você está vendo esse erro. Não se preocupe que você vai ver ele muito ainda haha!

Mas vou tentar te explicar a lógica, que aí fica mais fácil pra você entender nas próximas vezes. A mensagem de erro é:

```
Uncaught TypeError: Cannot set properties of null (setting 'value')
```

No início da mensagem você sempre vai ver o tipo do erro. Nesse caso, é um `TypeError`: significa que é um erro relacionado do **tipo** do dado que você está tentando manipular.

`Uncaught` significa "não capturado", ou seja: aconteceu um erro que não foi tratado (com `try/catch`, por exemplo). Não sei se você já chegou na aula onde eu falo do `try/catch`, mas isso não é o mais importante agora, é só pra vc entender essa parte mesmo =)

A mensagem de erro vem logo após o tipo: `Cannot set properties of null (setting 'value')`. Essa mensagem diz que não foi possível definir uma propriedade em cima de um valor que é `null` (já que `null` não é um objeto, logo você não consegue manipular propriedades em um valor que é `null`).

A parte `setting 'value'` mostra que você tentou definir uma propriedade `value` de um dado que deveria ser objeto (pois é em objetos que vc usa propriedades), mas na verdade o dado era `null`.

Essa é a explicação do erro. Agora, como faz para chegar até o problema real?

Tá vendo que, do lado direito da linha do erro aparece o nome de um arquivo seguido de um número?

```
challenge-20.js:58
```

Isso significa que esse erro foi encontrado no arquivo `challenge-20.js`, na linha 58!

E se você reparar no print que você mandou do seu editor, vai ver que erro acontece exatamente nessa linha. Tem até uma linha vermelha indicando o problema =)

Agora você sabe onde está o erro e, voltando à mensagem, você sabe que está tentando definir a propriedade `value` de um valor que é `null`.

A linha 58 é isso aqui:

```js
$inputUsername.value = username;
```

Com isso a gente pode perceber que `$inputUsername` é `null`. Aí você vai ver o que o `$inputUsername` recebe (por isso eu pedi seu código completo).

```js
var $inputUsername = document.querySelector('input[type="text]');
```

O `querySelector` só retorna `null` quando ele não encontra o elemento que casa com o seletor passado. Então a primeira coisa a fazer é olhar se no seu HTML tem um `input` com `type=text`.

O HTML estava correto, então não é ali o problema.

A próxima coisa que eu analiso nesse código é: o que o `querySelector` está tentando selecionar que retornou `null`? Se existe o `input` com `type=text`, então a probabilidade de ter digitado o seletor errado é grande. Como o seletor é apenas uma string, é mais difícil de ver o erro mesmo.

Mas analisando com calma só essa parte, fica mais fácil chegar no problema =)

Erros de digitação são os mais comuns que você vai encontrar, então sempre que tiver algum erro, siga esses passos que eu mostrei, e tente prestar atenção em como o código foi escrito =)

Essa explicação não é pra você achar que a partir de agora eu vou deixar de te ajudar, é só pra facilitar um pouco mais quando você encontrar um erro, mas pode ter casos onde vai ser difícil encontrar sozinha o problema.

Nesses momentos, eu estarei aqui pra te ajudar =)

**Comment by anarsantos** [comment]
Ainda não cheguei na aula de try/catch não sinhô. rs Eu aqui pensando "nossa como irei desvendar essas mensagens de erro" e você me vem com uma super explicação detalhada do erro. rs Ainda estou me recuperando das 2hs que perdi tentando devendar. Vou só terminar todos os vídeos da aula 22 e leio com atenção. Você está empatado com Guanabara como meus professores favoritos :)

**Comment by fdaciuk** [comment]
hahah! Massa, qualquer coisa manda aí :D

**Comment by anarsantos** [comment]
Acabei de ler a explicação com calma e ficou bem claro. É legal entender o que a mensagem de erro diz. Eu consigui entender a linha onde estava problema, mas não estava enxergando que era as aspas que não tinha fechado :(. Mas com a compreensão de como analisar a mensagem fica um pouco melhor. Vamos ver se não vou ficar tão perdida da próxima rs.

**Comment by fdaciuk** [comment]
Perfeito! Entender que o problema ali era as aspas vem com o tempo mesmo. Eu bati o olho e vi porque já passei muito por isso =)
