### ISSUE TITLE
[Aula 17] Sobre o for

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10211]
Olá, Fernando!

Não entendi muito bem a função da outra variável que você colocou no for: len = name.length? Tanto no primeiro quanto no último exercício.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Você está falando do desafio 17, ou do desafio 16, resolvido na aula 17?

**Comment by anarsantos** [comment]
Ah é, desculpa, deveria ter colocado no título [Aula 16], desculpa rs. É sobre o desafio 16 resolvido na aula 17. Ando cansada.

**Comment by fdaciuk** [comment]
Sem problemas! Agora entendi e já vi aqui qual foi o exercício =)
Bom, o uso da variável `len` não é estritamente necessário nesse caso. Provavelmente eu usei pra mostrar que o primeiro "parâmetro" passado para o `for` serve para inicializar variáveis, e vai executar apenas uma vez, então você pode inicializar quantas variáveis você achar necessário ali, se elas forem usadas para criar o seu loop.

Mas você pode criar a variável também fora do `for` que vai ter o mesmo resultado =)

**Comment by anarsantos** [comment]
Esse "for" poderia estar sem essa "variável len" então? O len vai executar os outros loops? Já que você disse que o "var i = 0" será executado apenas uma vez.

**Comment by fdaciuk** [comment]
Cada argumento do `for` é separado por um ponto-e-vírgula, então, nesse `for` aqui:

```js
  var name = 'Fernando';
  for (var i = 0, len = name.length; i < len; i++) {
    console.log(name[i] + ' é a ' + (i + 1) + 'ª letra do meu nome.');
  }
```

A expressão `var i = 0, len = name.length` é uma só, e faz parte do primeiro argumento do `for`, então as duas variáveis `i` e `len` serão criadas apenas uma vez.

Mas você poderia fazer apenas assim:

```js
  var name = 'Fernando';
  for (var i = 0; i < name.length; i++) {
    console.log(name[i] + ' é a ' + (i + 1) + 'ª letra do meu nome.');
  }
```

ou ainda:

```js
  var name = 'Fernando';
  var len = name.length;
  for (var i = 0; i < len; i++) {
    console.log(name[i] + ' é a ' + (i + 1) + 'ª letra do meu nome.');
  }
```

As 3 formas são similares, e terão o mesmo resultado no final das contas =)

**Comment by anarsantos** [comment]
Tá acho que estou entendendo rs, a "variável len" é traz o comprimento da "variável name"?

**Comment by fdaciuk** [comment]
Isso, nós usamos o tamanho / comprimento da variável `name` pois nós precisamos passar por cada uma das letras que estão nessa string. Então, enquanto a variável contadora `i` for menor que o tamanho total da string, o código do corpo do `for` será executado. Quando `i` for maior ou igual a `len`, aí esse código não será mais executado, e o código que está abaixo do `for` é que será lido e executado =)

**Comment by anarsantos** [comment]
Tá senhor, acho que entendi. Agora tô sofrendo com regex. Se tiver alguma dúvida envio. Valeu pelas explicações ;)

**Comment by fdaciuk** [comment]
Boa! Regex é complicadinho mesmo, mas assim que você pega a base dela, fica mais fácil :D 
Bons estudos, e mande dúvidas sempre que tiver :D

**Comment by anarsantos** [comment]
Espero pegar a base logo rs.
