### ISSUE TITLE
[Aula 24] A soma está indefinida

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10225]
Olá, seu Fernando! Meu olho não está achando o erro. Essa calculadora está me tirando o pouco de paz que tenho rs.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/2e8abc7c-4fa6-4780-b98c-f7971c6de71c)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Não entendi qual é o problema xD
Não está mostrando o resultado no console, é isso?

Se for isso, consegue compartilhar seu código pra eu ver como você fez?

**Comment by anarsantos** [comment]
Isso mesmo, senhor! Achei que fosse conseguir ficar uma aula sem mandar mensagem, mas não foi possível rs. Sorry.

https://github.com/anarsantos/curso-javascript-ninja

**Comment by fdaciuk** [comment]
Sem problemas :D 

Perfeito, já vi o problema, mas antes de te mostrar qual é, vou te mostrar como debugar pra chegar nele, ok? Vai levar um tempinho mas vai valer a pena. Vamos por partes:

Temos que trabalhar com as informações que temos. E o que temos de informação até agora é que, ao clicar no botão com o sinal de igual, é exibido `undefined` no console, então vamos começar por aí.

Se está mostrando `undefined`, significa que a função `reduce` está retornando `undefined`, concorda?

O seu desafio agora é tentar descobrir por que essa função está retornando `undefined`.

Dica: use o `console.log` para ver o valor das variáveis dentro dessa função, pra ver se alguma tem o valor diferente do esperado =)

Tente sozinha e, se depois de tentar por um tempo você não conseguir descobrir, comenta aqui com o passo-a-passo do que você fez que eu te ajudo a entender o processo de como chegar no resultado, pode ser? :D

**Comment by anarsantos** [comment]
Oie, eu tentei, mas não consegui. Tenho dificuldade ainda com o console, dá undefined e eu não entendo o porquê.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/0f40b646-ff7e-42d2-b50d-1e4246dab107)

**Comment by fdaciuk** [comment]
Ah, você está usando o debugger do browser já, muito bom! Bom, a dica é olhar os valores das variáveis **dentro** do `reduce`. Pelo debugger você já consegue ver que o `allValues` tem o valor correto, então até ali está tudo ok =)

Use o `console.log` para verificar o valor das variáveis dentro do `reduce`, por exemplo: ali na linha 76 você definiu a variável `firstValue`, correto? Então, logo abaixo dessa linha, adicione um `console.log("firstValue:", firstValue)` pra você ver o que tem nessa variável.

Faça isso para todas e veja, uma por uma, qual o valor das variáveis. O objetivo é verificar se o valor delas é o que você realmente esperava que estivesse atribuído a elas.

**Comment by anarsantos** [comment]
Antes de testar com o console vi que estava faltando os parênteses depois do "pop". :(

**Comment by fdaciuk** [comment]
Perfeito, era isso =)

**Comment by anarsantos** [comment]
Pois é. vivendo e aprendendo. Estava eu tentando achar onde errei daí entrei na pasta de "desafios-resolvidos" e vi que você colocou uma nota, que não precisa mais usar o `Array.prototype.forEach`. Em que outro caso ele seria necessário?

**Comment by fdaciuk** [comment]
Sobre o `Array.prototype.forEach`, você pode usar sempre que quiser usar esse método de array em um _array like_ que não tenha esse método. Isso vale para qualquer método de array =)

A nota dizendo que não precisa mais é porque essa feature entrou na especificação da DOM API, então agora uma `NodeList` contém o método `forEach`, mas continua não tendo os outros métodos que são específicos de array (`map`, `reduce`, `filter`, etc).

Então, se você precisar usar qualquer desses métodos em uma `NodeList`, por exemplo, pode continuar usando a técnica mostrada no curso =)

**Comment by anarsantos** [comment]
Legal, senhor Fernando! Acho que hoje não teremos mais dúvidas, espero rs

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, manda aí :D

**Comment by FeFernando** [comment]
Cara existe um jeito de tu calcular uma expressão matematica com um comando que se chama "eval" no javascript, basicamente ele vai ler a expressão matematica e resolve-la se na hora de declarar o resultado ela tiver o valor como  da conta como parametro.

Olhe esse exemplo:

var conta = "2 + 3"
var resultado = eval(conta)
console.log(resultado)

Isso funciona tambem se a expressão estiver em uma div

**Comment by fdaciuk** [comment]
Oi @FeFernando! Sim, existe, mas eu nem mostrei essa função no curso pois ela é **muito perigosa**, e pode abrir muitas brechas de segurança se usada de maneira errada.

Outro ponto importante é que a ideia dessa aula é evoluir a parte lógica: entender como seria o funcionamento real de uma simples calculadora vai ajudar a resolver muitos outros problemas similares no dia a dia de um projeto real =)
