### ISSUE TITLE
[Aula 22] Dúvida no "this"

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10222]
Oi Fernando! No vídeo 132 você diz que o "this" é global, daí quando não está declarado, como no código abaixo, ele retorna "undefined"?

```js
(function() {
    'use strict';

    function myFunction(a, b, c, d) {
        console.log(this.lastname);
    }
       
    console.log(myFunction.call());
})();
```
Lá por volta dos 10 minutos você diz que o "this" representa o window e ele não tem a propriedade "lastname". O window eu não preciso colocar nos parenteses?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! A forma como o `this` se apresenta quando você não usa `new` depende se você está no modo estrito ou não: fora do modo estrito, ele vai apontar para a global `window`, ou seja: `window` e `this` serão referência para o mesmo objeto global.

Quando você usa o modo estrito (com `"use strict"`), aí o `this` se torna `undefined` =)

**Comment by anarsantos** [comment]
Beleza, entendi! Vou aproveitar que vou iniciar o desafio 22 e apareceu no browser de forma diferente. Por que está aparecendo assim?

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/7f3a1cc1-e8a2-4465-8323-fb90ddc70c60)

**Comment by fdaciuk** [comment]
É que você subiu o servidor estático no diretório principal do repositório, aí não tem um arquivo `index.html` para renderizar no browser =)

Para abrir direto o `index.html`, você precisa subir o server no diretório do challenge que tem o `index.html` =)

**Comment by anarsantos** [comment]
Misericórdia senhor! Você falou português? Falou. Mas não entendi nada kkkkkkkkkkkk

Socorro!!!! Poderia por gentileza traduzir a primeira frase e a segunda? kkkk Tô me sentindo um jegue kkk Como sobe "servidor estático no diretório principal"? E como faz para "subir o server no diretório do challenge"?

**Comment by fdaciuk** [comment]
hahah! Calma, vamos por partes =)
Primeiro: como você chegou nessa tela do print?

**Comment by anarsantos** [comment]
Então vamos por partes senhor rs.

Foi clicando no "Go Live".
![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/45e29313-1079-4151-b040-0d471cb8eeb8)

**Comment by fdaciuk** [comment]
Ah, você está usando direto do VSCode, entendido. Nesse caso, o que acontece é o seguinte: ao clicar em "Go Live", o VSCode vai subir um servidor local no seu computador (como se fosse um servidor de internet, mas apenas para acesso local) no diretório que está definido como workspace do seu VSCode.

Como seu workspace é o diretório do repositório do curso, quando você clicar em "Go Live" ele vai mostrar aquela lista de diretórios que você mandou no primeiro print pois não tem nenhum arquivo `index.html` para ser renderizado nesse diretório.

Para resolver, após clicar em "Go Live" para subir o servidor, é só você clicar com o botão direito em cima do HTML que você quer abrir e escolher a opção "Open with Live Server".

Essa informação eu encontrei na documentação do [Live Server do VSCode](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).

Como eu não uso VSCode, me deixe saber se isso funcionou, ou se ficou alguma dúvida sobre alguma coisa que eu escrevi acima que eu tento detalhar melhor :D

**Comment by anarsantos** [comment]
Não, tá perfeito. Entendi tudo :). Você é fantástico mesmo não usando a IDE conseguiu achar a informação, coisas de quem tem uma senioridade maior. Espero chegar nesse nível. rs

**Comment by fdaciuk** [comment]
Chega com certeza! Tudo é questão de tempo e prática :D

**Comment by anarsantos** [comment]
Obrigada pelo apoio, hoje foi um dia complicado, tanto do conteúdo que fiquei meio perdida e fiz uma entrevista horrível. O entrevistador colocando palavras na minha boca. Dizendo que não gosto de matemática, que todo mundo que faz letras não gosta, sou formada em letras. Em nenhum momento disse isso, mas enfim... dias melhores virão!

**Comment by fdaciuk** [comment]
É complicado mesmo, mas pense que foi um livramento: se o entrevistador te tratou assim, imagina como é o dia a dia da empresa =)

Siga firme estudando e praticando que logo vai aparecer uma oportunidade legal :D

**Comment by anarsantos** [comment]
Então seu Fernando, não sei se foi livramento, espero que sim, porque ficaram de dar retorno até sexta ou segunda, mas não tem lógica ele me chamar. Uma amiga falou pra ir, mesmo que pra ficar 3 meses, porque pego esse salário. Vamos ver.

Mas obrigada pelas explicações e apoio :)

**Comment by fdaciuk** [comment]
Entendi! Bom, aguarde a resposta então, mas não desanime! Estou torcendo pra ser uma boa oportunidade :D

**Comment by anarsantos** [comment]
Obrigada, querido professor. rs
