### ISSUE TITLE
[Aula 23] EditorConfig VSCode

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10224]
Seu Fernando, depois de instalar o EditorConfig como faço para criar o arquivo no VSCode? Pesquisei aqui, mas não achei. Vi que você fez pelo terminal.

Achei uma instrução e consegui achar o EditorConfig. Se eu clicar no último link ele gera para todos os arquivos?
![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/4a1dc114-72a1-410b-916b-89dff3861bfa)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi! Provavelmente, ao clicar na última opção, ele vai gerar um arquivo `.editorconfig` já preenchido com algumas opções padrão, mas você pode modificar para ficar como mostrado no curso =)

E para gerar um arquivo novo vazio, é só clicar ali em "New File..." e dar o nome de `.editorconfig` (com ponto na frente) =)

**Comment by anarsantos** [comment]
Obrigada seu Fernando! :)

**Comment by fdaciuk** [comment]
Nada! Qualquer dúvida, manda aí :D
