### ISSUE TITLE
[Aula 28] Métodos estáticos

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10231]
Oi, Fernando! No "vídeo"/texto 168 você diz que **fez o exercício usando protoype**, mas era para **fazer com métodos estáticos**. Não ficou muito claro pra mim. Porque esse foi o desafio mais difícil no meu caso. Ainda não tenho muita habilidade com os conceitos desse desafio.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! Sim, na verdade você entendeu certo, eu que gravei a resolução desse desafio na emoção 😅 
Mas eu deixei a solução correta na branch `desafios-resolvidos`:
https://github.com/da2k/curso-javascript-ninja/blob/desafios-resolvidos/challenge-27/challenge-27.js 

=)

**Comment by anarsantos** [comment]
Ok, senhor. Já dei uma olhada no repositório do resolvido. Muito obrigada! ;)

**Comment by fdaciuk** [comment]
Nada! Qualquer coisa, só avisar :D
