### ISSUE TITLE
[Aula 30] Erro no ajax.send

### ISSUE THREAD

**Issue by anarsantos** [da2k/curso-javascript-ninja#10235]
Já assisti o início da aula algmas vezes para tentar encontrar o erro espero que não seja parênteses de novo. Na metade do companyInfo o código já começa a dar problema.

![image](https://github.com/da2k/curso-javascript-ninja/assets/54543420/360a17a6-9882-4815-953a-c82b4754a08b)

Segue o link: https://github.com/anarsantos/curso-javascript-ninja/tree/challenge-29/challenge-29

Você fica falando que pode incomodar dá nisso rs, não sei choro se dou risada. Estou em crise existencial.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @anarsantos! É que você iniciou o servidor na raiz do repositório, aí o caminho público para acessar o arquivo `company.json` ficaria `/challenge-29/company.json` =)

Se você iniciar o servidor no diretório `challenge-29`, vai funcionar como esperado =)

E a dica aqui para esse desafio e para os próximos: inicie o servidor sempre no diretório do desafio, onde tem o arquivo `index.html`, já considerando que, quando você quiser subir um app desse tipo na internet, esse será o caminho inicial da sua aplicação :D

**Comment by anarsantos** [comment]
Seu Fernando, não entendi muito bem o que o senhor escrevinhou rs. Socorro!

Precisamos traduzir do seu português para o meu rs.

Meu filho, quem é "o servidor raiz"? Como vive? O que come? Eu nem sabia que ele existia kkkkkkkkkk

Esse caminho `/challenge-29/company.json` tem que ir no `index.html`?

**Comment by fdaciuk** [comment]
hahah! Tranquilo, vamos lá: você está usando a extensão "Live Server" do VSCode para subir o servidor, certo? Qual o processo você faz para subir o servidor?

**Comment by anarsantos** [comment]
Eu clico no arquivo `index.html` com o botão direito do mouse.

**Comment by fdaciuk** [comment]
Beleza! O "raiz" que eu comentei ali significa o caminho inicial. Por exemplo: se você usa windows, a "raiz" dos seus arquivos fica em um HD que é chamado de "C:" pelo windows.

No caso do diretório com os arquivos do curso, quando você abre esse diretório no VSCode, e lá no VSCode você vê a lista com todos os challenges, o diretório "raiz" é o diretório onde tem todos os diretórios dos challenges.

E o Live Server sempre inicia o servidor com base nesse diretório raiz, ou seja: se você clicou com o botão direito para abrir o arquivo que está em `challenge-29/index.html`, quando você acessar o endereço do Live Server (`http://localhost:5500`), você vai ver toda a lista de challenges.

O que você precisa fazer é abrir só o diretório do `challenge-29` no VSCode, para esse diretório ser o diretório "raiz". Dessa forma, ao iniciar o Live Server, o `index.html` que está dentro do `challenge-29` será automaticamente renderizado quando você acessar `http://localhost:5500`, pois agora o diretório `challenge-29` é o diretório "raiz".

Tenta aí e me deixe saber se você tiver alguma dificuldade =)

**Comment by anarsantos** [comment]
Seu Fernando o erro não aparece mais, mas o nome e o telefone também não. rs

**Comment by fdaciuk** [comment]
Essa foi difícil até pra eu descobrir 😅 
Tive que redigitar pra encontrar o problema, e só vi porque dei um `git diff` pra ver o que estava diferente: você escreveu [`textContext`](https://github.com/anarsantos/curso-javascript-ninja/blob/challenge-29/challenge-29/challenge-29.js#L58-L59) (com x) ao invés de `textContent` (com n) 🙈 

A culpa não é sua, tá? Como eu disse lá no começo, isso é bastante comum de acontecer, mas existem ferramentas que te ajudam a pegar esse tipo de erro. Vou mostrar isso nas aulas finais do curso =)

Por enquanto, é bom continuar assim pra entender que esse é um problema comum, e quanto tudo parece que está funcionando, menos por um detalhe, é bom tentar olhar com calma o que foi digitado =)

**Comment by anarsantos** [comment]
Tenho trabalhado duro para me aprimorar nos erros, já que nos acertos tá difícil kkkkkkkkk. Isso é para contribuir com sua evolução na programação, eu não só pertubo, mas também contribuo para a evolução do coleguinha rs. Quer dizer isso vai depender do ponto de vista. kkkk

O duro é olhar com calma o que foi digitado quando você já está cansado(a) rs. Às vezes, precisa de outro abençoado para olhar mesmo. Mas veja pelo lado bom, não há. kkkk Falando sério, tem muito tempo que não cometo erro de digitação 😊

**Comment by fdaciuk** [comment]
hahah! Justissimo! E também tem essa de você estar em cima do código por muito tempo, acabar passando essas coisas. Um olhar de fora sempre ajuda =)

**Comment by anarsantos** [comment]
Com certeza senhor o olhar de fora sempre ajuda rs. Valeu :)
