### ISSUE TITLE
FATAL: COULD NOT CREAT WORK TREE DIR 'Hello-May': Permission Denied

### ISSUE THREAD

**Issue by Lopesmay** [da2k/curso-javascript-ninja#10269]
Boa Tarde galera, to tentando fazer um teste para clonar um repositório e está dando esse erro do título, alguém saberia me dar uma luz?

``` https://github.com/Lopesmay/Hello-May.git``` Essa é a URL 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Lopesmay! Você precisa criar uma chave SSH para se conectar com o GitHub e ter acesso aos seus repositórios privados =)

É bem tranquilo de fazer, só seguir esses passos do tutorial do próprio GitHub:
1. [Criar](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh) uma chave SSH no seu sistema operacional
2. [Adicionar](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) a chave SSH **pública** na sua conta do GitHub
3. [Testar](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection) a conexão com GitHub.

Após isso, você vai conseguir facilmente clonar seus repositórios privados e dar pull/push sem problemas :D
