### ISSUE TITLE
Desafio da semana 5 [condicional ternário]

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-javascript-ninja#1028]
Na função book(), tentei utilizar o condicional ternário dessa maneira:

**!bookName ? return allBooks : return allBooks[bookName];**

Pq não funciona dessa maneira?

Valeu!

**Comment by fdaciuk** [comment]
Fala @pedromuraki! =)

O condicional ternário é diferente do `if`. O `if` é uma estrutura condicional. Ele simplesmente gera um bloco de código para que, se a expressão passada dentro dos parênteses for verdadeira, ele executa esse bloco.

Já o ternário **é uma expressão**, que sempre te retorna um valor. Ele precisa sempre dos dois lados do teste que você faz: se a expressão inicial for verdadeira, ele executa o que vem logo após o sinal de interrogação, senão, ele executa o que vem após os dois pontos.

Ou seja: o ternário é uma expressão completa, por isso você não pode usar o `return` _dentro_ dele.

O correto seria fazer:

```js
return !bookName ? allBooks : allBooks[bookName];
```

O que significa que, o ternário será executado e, o valor que o ternário retornar será passado para o return =)

Ficou mais claro?

**Comment by fdaciuk** [comment]
Fala @pedromuraki! Se tiver alguma dúvida ainda com relação a isso, me avisa que eu abro a issue novamente, ok? =)
