### ISSUE TITLE
Comunidade dos Alunos JS Ninja

### ISSUE THREAD

**Issue by mariocfsalles** [da2k/curso-javascript-ninja#10282]
Bom dia Fernando tudo joia?
Não é bem uma dúvida relacionado ao curso do JS Ninja, o que gostaria mesmo de saber é se há alguma forma de nós alunos interagirmos?
Em uma das mensagens do curso na Udemy encontrei um link para o discord, mas o mesmo se encontra expirado. Ainda há esse canal no Discord? Se sim agradeceria se pudesse facultar por favor
Até mais!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mariocfsalles! Tudo certo, e contigo? :D 
Não temos um discord específico dos alunos (até tínhamos, mas tinha zero movimentação), mas tem um de comunidade que eu abri e convidei os alunos a participarem de lá! 

Se quiser entrar, você encontra o link de invite no meu [canal da Twitch](https://twitch.tv/fdaciuk)

Só ir lá e clicar em "Chat", e digitar `!discord` que lá tem o link atualizado =)

Não precisa estar ao vivo, pode digitar a qualquer momento no chat, ok?

**Comment by mariocfsalles** [comment]
Thanks @fdaciuk !
