### ISSUE TITLE
Operador de pré e pós incremento

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-javascript-ninja#1030]
Na prática, qual a diferença entre o operador de pré e de pós incremento? (++x / x++).

Abs.

**Comment by fdaciuk** [comment]
A diferença principal acontece quando vocẽ atribui o valor de `x` à uma outra variável.

Esses operadores causam o que chamamos de _efeito colateral_, pois além de somar 1 ao valor da variável, eles **mudam** o valor da variável para o novo valor, somado 1.

O que você normalmente vê é:

```js
var x = 1;
x++;
console.log(x); // 2

var y = 1;
++y;
console.log(y); // 2
```

Usando qualquer um dos dois, o resultado é o mesmo. A diferença acontece aqui:

```js
var x = 1;
var xx = x++;
console.log(x); // 2
console.log(xx); // 1

var y = 1;
var yy = ++y;
console.log(y); // 2
console.log(yy); // 2
```

Perceba que, com o operador de pós-incremento, quando você o usa, e ao mesmo tempo atribui o valor a uma variável, acontece o seguinte:
1) Primeiro o valor de `x` é atribuído à `xx`;
2) O valor de `x` é incrementado.

Por isso `xx === 1` enquanto `x === 2`.

No caso do pré-incremento, a incrementação tem prioridade sobre a operação de atribuição. Então acontece o seguinte:

Ao atribuir o valor de `y` para `yy`, antes da atribuição, `y` é somado 1 e alterado o valor dessa variável. Logo, `y` será igual a `2`. Então a atribuição é feita, e o valor de `yy` passa a ser `2` também.

Deu pra entender? =)

**Comment by fdaciuk** [comment]
Se tiver alguma dúvida ainda com relação a isso, só avisar que eu abro a issue novamente, ok? =)
