### ISSUE TITLE
Aula 10 - Calculator

### ISSUE THREAD

**Issue by leandrofsp** [da2k/curso-javascript-ninja#1033]
_Voltando ao exemplo da calculadora, vamos utilizar mais uma abordagem
	funcional, mas dessa vez, separando algumas responsabilidades.
	- Primeiro, crie um objeto chamado `operation` que terá as propriedades:
	'+', '-', '*', '/' e '%'.
	- Cada propriedade vai receber uma função (logo, elas serão métodos), e essa
	função receberá dois parâmetros e retornará a operação referente à sua
	propriedade, usando os valores passados por parâmetro._

estou com duvida no enunciado acima. é possível criar uma propriedade com os caracteres descritos(+,-,/,%,*)? Se é que é isso pra fazer rs.

vlw

**Comment by fdaciuk** [comment]
Fala @leandrofsp!

Exatamente, é possível =)

Lembra que vimos que podemos criar _chaves_ em objetos como string? E que podemos usar qualquer caractere dentro de strings? Então ;)

PS.: Sempre que criar uma issue, me marque com "@fdaciuk", senão eu posso demorar pra ver xD

**Comment by leandrofsp** [comment]
Opa blz @fdaciuk. 
Acho que não lembro rs, vou procurar qual foi a aula, pra tentar novamente. Ta complicado esse desafio haha.

Vlw.

**Comment by leandrofsp** [comment]
Então @fdaciuk  eu tinha feito algo assim, seria isso?
var operation = {
		'+' : function(value1, value2){
			return ( value1 + value2 );
		},
		'-' : function(value1, value2){
			return ( value1 - value2 );
		},
		'*' : function(value1, value2){
			return ( value1 * value2 );
		},
		'/' : function(value1, value2){
			return ( value1 / value );
		},
		'%' : function(value1, value2){
			return ( value1 % value2 );
		}
	};

**Comment by fdaciuk** [comment]
Isso ae \o/

**Comment by fdaciuk** [comment]
PS.: Só precisa marcar quando criar a issue.. os outros comentários eu já recebo normalmente :grin:

**Comment by leandrofsp** [comment]
Então eu tinha criado desse jeito mas dai pra recuperar os dados desse objeto em ' ' não consegui, por isso perguntei se estava correto, mas sabendo que é isso vou tentar.

Obrigado.

PS. É só pra garantir que recebeu haha.

**Comment by fdaciuk** [comment]
Entendi, sem crise sobre a marcação, só pra avisar mesmo xD

Sobre usar strings como chaves de objetos, nós fizemos isso no desafio da lista de livros =)

**Comment by leandrofsp** [comment]
Bacana vou rever a aula e bora pro desafio quebra a cabeça.

Obrigado pela ajuda.

**Comment by fdaciuk** [comment]
Nada! Precisar de algo é só gritar \o/

**Comment by theandersonn** [comment]
@fdaciuk Fiquei com dúvida neste mesmo ponto. Aproveitando essa issue :)

Pensei em declarar esse objeto como o leandro fez, no entanto fiquei travado porque não consigo acessar o método do objeto.

Assim, eu não consigo acessar o método.

`var operation = {
 '+': function (x,y){return x+y;}
 }
operation.+;`

Desta forma eu já consigo. O que ocorre?

`var operation = {
 'sum': function (x,y){return x+y;}
 }
operation.sum;`

**Comment by fdaciuk** [comment]
Fala @theandersonn =)
Quando você usa strings para nomear chaves de um objeto (tanto propriedades como métodos), você só consegue acessar essa chave com a notação de array, usando colchetes =)

Para acessar chaves de objetos com a notação de ponto, a regra é a mesma para nomes de funções e variáveis: você só pode usar letras de `A` a `Z`, `a` a `z`, números `0` a `9`, e os caracteres `_` e `$`, e ainda não podem começar com números.

Acho que nós vimos isso nas primeiras aulas, quando falávamos sobre nomear variáveis =)

Qualquer outro tipo de caractere precisa ser passado como `string` na chave do objeto, e só pode ser acessado com notação de colchetes =)

Deu pra sacar?

**Comment by theandersonn** [comment]
Deu sim, valeu!
No próximo intervalo vou prosseguir com o exercício.

**Comment by fdaciuk** [comment]
Qualquer dúvida só avisar =)
