### ISSUE TITLE
Aula 09 - Hoisting

### ISSUE THREAD

**Issue by willianribeiro** [da2k/curso-javascript-ninja#1045]
Grande Daciuk! 

Pelo que eu tava analisando na aula 9, o passo a passo que o JavaScript faz é:

1. Procura no escopo da função por declarações de variáveis, iça elas para o topo da função e as atribui `undefined`.
2. Procura no escopo da função por funções literais e iça elas para o topo.
3. Após isso ele segue linha a linha. Consequentemente, caso exista alguma inicialização de variável ele a faz.

Sendo assim, o que o JavaScript faria com o código abaixo:
```
function myFunction() {
  var number1 = 1;
  var number2 = 2;
  
  return sum();
  
  var sum = function() {
    return number1 + number2;
  };
```

Seria isso?

```
function myFunction() {
  var number1 = undefined;
  var number2 = undefined;
  var sum = undefined;
  
  number1 = 1;
  number2 = 2;

  return sum();

  sum = function() {
    return number1 + number2;
  };
}
```

@fdaciuk

**Comment by willianribeiro** [comment]
Eu fiquei curioso quanto aos passos que o interpretador segue, quanto a ordem que ele faz as coisas, saca?
Você fala disso no curso ou tem algum material que você indicaria? (Pode ser em inglês)

**Comment by fdaciuk** [comment]
Isso mesmo! Só as variáveis `number1` e `number2` que não se alteram, mas com a variável `sum`, é exatamente esse o comportamento :)

Com coisas síncronas, que é o que você está vendo nesse momento, esse é o único comportamento diferente que ele faz.

Em aulas mais pra frente, eu falo mais sobre outras coisas que acontecem quando temos código assíncrono :)

Fique tranquilo que o curso vai te dar toda a base que você precisa pra entender bem o funcionamento da linguagem :)

E, dúvidas, pode gritar :)

**Comment by willianribeiro** [comment]
Hmmm certo

Mas péra, então `number1` e `number2` **não** são inicializadas com `undefined` antes de receberem seus respectivos valores? (`1` e `2`)

Por que `sum` é tratado de forma diferente de `number1` e `number2`? 
O `sum` de fato é inicializado com `undefined`, certo? Os 3 são variáveis, não deveriam se comportar do mesmo jeito?

**Comment by fdaciuk** [comment]
Não necessariamente.. `number1` e `number2` já estão no início do seu escopo, que é a topo da função, por isso elas são inicializadas com os valores corretos =)

No caso do `sum`, como ela é criada com `var` depois do início da função, então é feito `hoisting` com ela, definindo seu valor como `undefined` antes de atribuir a função à essa variável =)

**Comment by willianribeiro** [comment]
hmmmm agora saquei! show de bola! valeu @fdaciuk ! 

🎉🎉🎉🎉

**Comment by fdaciuk** [comment]
Valeu! Qualquer dúvida, só avisar =)
