### ISSUE TITLE
Aula 10 - Como funciona a expressão: {} + []

### ISSUE THREAD

**Issue by willianribeiro** [da2k/curso-javascript-ninja#1064]
Postei essa dúvida no grupo, mas to passando pra cá pra ficar mais fácil de acompanhar:

Boa tarde, povo!

To assistindo a Aula 10 e pintou uma dúvida aqui. Na aula o @fdaciuk faz o seguinte:

```
function sum (a, b) {
    return a + b;
}

console.log( sum( {}, [] ) );   // —> isso retorna [object Object]
```

Eu fui testar aqui e somei direto no console node, sem criar uma função e o resultado foi `0`! Alguém sabe porque diabos isso acontece?

![image](https://cloud.githubusercontent.com/assets/3102551/19579818/5d66d9e6-9701-11e6-8286-cba78bc0833c.png)

@fdaciuk

**Comment by willianribeiro** [comment]
Resposta do Daciuk:


@willianribeiro eu fiquei de falar sobre isso depois e acabei não falando.. o que acontece nesse caso é o seguinte:

JavaScript tem tipagem fraca e tipagem dinâmica.. isso significa que você não precisa dizer que um valor é de um tipo específico para fazer algum tipo de operação.. por ter tipagem dinâmica, o JS faz inferência de tipos, e ele mesmo converte os valores para o tipo ideal, dependendo da operação que você está tentando fazer xD

Nesse caso, o que acontece é o seguinte:

Ao tentar somar dois números (10 + 2), o resultado é 12
Ao tentar somar um número com uma string, acontece o seguinte: (10 + 'abc') = "10abc"
Ele concatena! Por que?

Porque, quando você usa o sinal de + com uma string, o JS entende que você quer concatenar, não somar. Então o que ele faz é converter o outro valor também para string e faz a concatenação. Acontece mais ou menos isso:
10 + 'abc'
'10' + 'abc'
'10abc'

No caso do `{} + []` ser igual a `0`, o que acontece é que o JS usa o operador `+` como unário, e converte (ou tenta converter) o array para número.. como não há valores dentro do array, ele assume o valor zero, e converte o array para zero. O objeto convertido em número é NaN, que é ignorado e o resultado acaba sendo zero.

Se você faz a "soma" ao contrário: `[] + {}`, o JS vê que o objeto não é possível converter para número, então ele tenta concatenar o array com o objeto.. para isso, ele precisa transformar os dois em strings.. se vc pegar um array e usar o `toString()`, vai ver a representação `[object Object]`, pois é a representação em string de qualquer objeto, por isso ele retorna esse valor xD

Por ser uma linguagem dinâmica, o JS tem muito disso (como outras linguagens dinâmicas). Conhecendo o que acontece, você sabe o que deve evitar, e como tratar para não deixar acontecer esses problemas :smiley:

Recomendo assistir a esse vídeo: https://www.destroyallsoftware.com/talks/wat

É uma sátira com Ruby e JS, mostrando exatamente esses pontos xD

**Comment by willianribeiro** [comment]
Caraca, que doidera Daciuk kkkk

Bom, vamos lá, eu entendi até a parte em que você explica sobre a soma do `{} + []`. Que o JS entende o `+` como operador unário, tenta fazer a conversão de ambos (para number) que resulta em `NaN` para o objeto e `0` para o array. Ele ignora o `NaN` e retorna `0`. 

Mas por que afinal ele entende o `+` como operador unário e no outro caso, quando você inverte a soma ( `[] + {}` ) ele entende como operador binário ? 😳

Isso me confundiu um pouco!

**Comment by fdaciuk** [comment]
haha! :D

Então, a explicação que eu dei foi bem rasa.. na verdade, muitas coisas acontecem quando é necessário fazer conversão de valores, principalmente quando algum desses valores é um objeto.

Se quiser ir mais a fundo nesse assunto [a documentação da ECMAScript](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-type-conversion) detalha exatamente o que acontece com cada tipo quando convertido =)
