### ISSUE TITLE
Aula 22 - Array-like e prototypes

### ISSUE THREAD

**Issue by meche** [da2k/curso-javascript-ninja#1071]
Fala Mestre!

Estou com uma dúvida quanto a utilização do this nesta matéria. no seguinte exemplo:

```js
    function myFunction () {
        Array.prototype.forEach.call(arguments, function (item, index) {
            console.log('usando forEach em um array-like, o arguments: ', item )
            console.log(this)
        }) 
```

Eu passei arguments, e funcionou quase tudo, mas o this apresentou como `undefined`

se eu faço isso:

```js
    function myFunction () {
        Array.prototype.forEach.call(arguments, function (item, index) {
            console.log('usando forEach em um array-like, o arguments: ', item )
            console.log(this)
        }, arguments) // parametro é o this
``` 
ai ele apresenta o this, por que? Em .call() seu primeiro parametro não é o this?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @meche! Boa pergunta =)

Como você está fazendo a chamada da função? Se possível, mostre o código todo que assim fica mais fácil explicar o que pode ter acontecido :)

**Comment by meche** [comment]
```js
myFunction('a', 'b', 'c')
```
Fiz assim @fdaciuk

**Comment by fdaciuk** [comment]
Entendi.. provavelmente você estava usando o `'use strict'`, certo?

O método `forEach` aceita que se passe um `this` para a função de callback usando o segundo parâmetro, como você fez no segundo exemplo.

No primeiro exemplo, o `this` é o objeto global. Por causa do `'use strict'`, quando você usa o `this` sem criar um novo objeto com `new`, o `this` se torna `undefined` =)

Deu pra entender o que aconteceu?

**Comment by meche** [comment]
Sim, estou usando `use strict` e com a `IIFE` padrão do curso que você passou :) 

Entendi, o .call() neste caso não consegue passar o arguments como this, só o segundo parâmetro do forEach.. beleza Mestre! valeu!

**Comment by fdaciuk** [comment]
Não é nem o caso de não conseguir.. isso é a implementação do `forEach` na real.. o `this` que você passa para o método `call` (`arguments`) é usado como o `array` a ser iterado. Mas dentro da função de callback do método `forEach`, ele faz o `bind` do objeto que você passar como segundo parâmetro, para ser chamado como `this` dentro da função =)

**Comment by meche** [comment]
sucesso então.. entendido! Pode fechar a issue ! valeu mesmo!

**Comment by fdaciuk** [comment]
\o/
