### ISSUE TITLE
Aula 12 - Criar objetos com conteúdo igual mas com referência diferente

### ISSUE THREAD

**Issue by soutomario** [da2k/curso-javascript-ninja#1075]
Fala Daciuk Sensei beleza? \õ

Cara eu estou na aula 12 e me pairou uma dúvida:
Se eu criar uma variavel

`
var obj = {number: 1};
var obj2 = obj;
console.log(obj2 === obj); // true
`

Eu sei que a referência do obj é atribuida a variável, agora e se eu quiser passar somente o conteúdo da variavel e não a referência, é possível?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @soutomario! É possível sim =)
Você precisa iterar pelas chaves desse objeto, e criar um novo baseado nos valores que não são objetos.

Pode parecer um pouco complicado, mas não, olha só:

Pense que, cada objeto criado ocupa um espaço diferente de memória. Lembre-se também que, a cada vez que você usa `{}` para criar um objeto, é como se você estivesse usando `new Object()`, ou seja: `{}` vai sempre criar um novo objeto =)

Se você fizer:

```js
var obj = { number: 1 };
var obj2 = { number: 2 };
```

Você acaba de criar dois objetos, com o mesmo conteúdo "visualmente falando", mas que são diferentes pois estão ocupando espaços diferentes na memória.

Para copiar um objetos, você pode usar o `Object.keys`, que pega todas as chaves do objeto e as coloca em um array, e então você itera por esse array e vai atribuindo as chaves e os valores para criar um novo objeto:

```js
var obj = { key1: 'value1', key2: 'value2' };
var keys = Object.keys(obj);
var newObj = {};

for (var i = 0; i < keys.length; i++) {
  var key = keys[i];
  var value = obj[keys[i]];
  newObj[key] = value;
}

console.log(obj); // { key1: 'value1', key2: 'value2' };
console.log(newObj); // { key1: 'value1', key2: 'value2' };
console.log(obj === newObj); // false
```

Pronto! Agora você criou um novo objeto com o mesmo conteúdo! Mas tem um outro porém: lembre-se que, sem contar os tipos primitivos - string, number, boolean, null e undefined - qualquer outro tipo de valor em JS é um objeto: object, array, function, etc.

Então, sempre que você criar qualquer um desses tipos que sejam objetos, eles terão o seu espacinho lá na memória =)

Isso inclui também objetos criados dentro de objetos:

```js
var obj = {
  key1: 'value1',
  key2: {
    key2_1: 'value2_1',
    key2_2: 'value2_2'
  }
};

var keys = Object.keys(obj);
var newObj = {};

for (var i = 0; i < keys.length; i++) {
  var key = keys[i];
  var value = obj[keys[i]];
  newObj[key] = value;
}

console.log(obj === newObj); // false
console.log(obj.key2 === newObj.key2); // true <-- olha isso!
```

O que aconteceu acima? Você iterou pelo objeto principal, copiando as propriedades para `newObj`, mas `obj.key2` também é um objeto, e também tem seu espaço em memória. Como você simplesmente atribuiu o `obj.key2` para `newObj.key2`, então eles conterão a referência para o mesmo objeto, ou seja, vão apontar exatamente para o mesmo local na memória.

Então, para criar um novo objeto a partir de um outro, você sempre precisa verificar se o valor da chave que está sendo iterada não é um objeto. Porque se for, você precisa iterar por ele também xD

Mas a ideia de objetos ficarem em memória é boa, pois no uso comum, você dificilmente vai precisar criar um novo objeto se for somente usar referência. Se for fazer alguma modificação, para não alterar o objeto anterior, ae sim você cria um novo e altera o valor necessário.

Mas os valores que não precisam ser alterados, podem continuar sendo somente reatribuídos, para aproveitar o valor já existente =)

Deu pra entender?

PS.: Usei `for` para iterar pois até a aula 12 é o que tinhamos visto para fazer iteração. Na aula 13 você vai conhecer umas novas formas mais "bonitas" de iterar arrays :D

**Comment by fdaciuk** [comment]
Fala @soutomario! Ficou clara a explicação? Qualquer coisa me avise que eu abro de novo a issue, ok? =)
