### ISSUE TITLE
[Aula 28] Dúvida sobre o Método POST

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#1079]
Como fazer requisições via POST para uma API?}

@fdaciuk

Salve! Queria uma dica sua se possível. Como posso realizar uma pesquisa em uma API, usando o método GET do xhr. 

O lha o que eu tenho tentado fazer.

<pre>
var xhttp = new XMLHttpRequest();
  xhttp.open("POST", "http://pokeapi.co/api/v2/pokemon/", true);
  xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  xhttp.send("name=pikachu");
  console.log(xhttp); 
</pre>

**Comment by fdaciuk** [comment]
Fala @DaniloAgostinho! A ideia é basicamente essa mesmo =)
Só vai precisar de um listener para o event `onreadystatechange`, para saber quando o request foi feito :D

Na aula 32 tem 3 vídeos falando sobre o método POST :D 

Qualquer dúvida só avisar! :D

**Comment by DaniloAgostinho** [comment]
@fdaciuk vlw mano!

👍
