### ISSUE TITLE
Desafio 13 - forEach

### ISSUE THREAD

**Issue by leandrofsp** [da2k/curso-javascript-ninja#1085]
Fala, tudo blz.

então estou tentando fazer o desafio mas dei uma travada no forEach não estou conseguindo fazer teria uma luz?

`/*
	usando forEach, percorra o array `brasil` e gere um novo array chamado
	`newBrasil`. Esse array deve ter cada item como um objeto, com as
	propriedades:
	- `id`: que será o índice do array `brasil`,
	- `estado`: que será o estado do array `brasil`.
	*/

//o que eu tentei fazer
	brasil.forEach(function(item, index) {
		newBrasil = [ { id: index, estado: item } ];
	});
console.log( newBrasil );`

@fdaciuk

**Comment by fdaciuk** [comment]
É quase isso @leandrofsp! =)

Mas veja o que você está fazendo: a função passada para o `forEach` é executada uma vez para cada item do array.

No caso, dentro da função, você sobrescreve tudo o que tem no `newBrasil`. Logo, ao final da iteração, o `newBrasil` vai ter os dados somente do último item.

O que você precisa fazer é criar um novo array (que será o `newBrasil`) e **empurrar** pra dentro dele esse objeto que você vai criar dentro do `forEach`, sacou? xD

**Comment by leandrofsp** [comment]
Compreendi um pouco, vou tentar fazer novamente pra vê se sai rs.

vlw @fdaciuk

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida posta aqui =)

**Comment by leandrofsp** [comment]
Acho que agora deu certo.

valeu pela ajuda  @fdaciuk

**Comment by fdaciuk** [comment]
Show :dancer: :dancer:

**Comment by leandrofsp** [comment]
Olha eu de novo rs. 
Na hora que eu mando imprimi no console ele imprimi assim `[Object, Object, Object, Object]` está correto? deveria imprimir aberto como na aula que vc apresentou né?

o que fiz:
`var newBrasil = [];
	nordeste.forEach(function(item, index, array) {
		newBrasil.push( { id: index, estado: item } );
	});
console.log( newBrasil );`

@fdaciuk

**Comment by fdaciuk** [comment]
Você está testando no console do browser ou no console do node?

**Comment by leandrofsp** [comment]
Do browser.

**Comment by fdaciuk** [comment]
Então está correto xD
Aparece uma setinha do lado esquerdo, não?
Clica na setinha que ele vai abrir o array =)

**Comment by leandrofsp** [comment]
Isso, ah ta no browser aparece diferente, pensei que estava fazendo algo errado. 
valeu de novo rs

**Comment by fdaciuk** [comment]
Show! Deu certo então né? =)
