### ISSUE TITLE
Desafio 14

### ISSUE THREAD

**Issue by leandrofsp** [da2k/curso-javascript-ninja#1101]
O desafio 14 é pra resolver somente com o que foi passado na aula 14? 

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @leandrofsp! Todos os desafios você pode resolver com tudo o que foi visto nas aulas anteriores, até a aula em que você está. 

A maior parte dos exercícios vão pedir para serem resolvidos com o que foi visto naquela aula, mas conforme você avança, você pode usar todo o conhecimento adquirido até então =)

**Comment by leandrofsp** [comment]
Vlw pelo esclarecimento @fdaciuk.

Bora quebra a cabeça rs :grimacing:

**Comment by fdaciuk** [comment]
:D

Qualquer dúvida grita ae =)
