### ISSUE TITLE
Duvida Challenge 03

### ISSUE THREAD

**Issue by luanasallles** [da2k/curso-javascript-ninja#1103]
Terminando o desafio 3 fiquei em dúvida se posso ou não criar um método dentro da variável dessa forma:

pessoa.apresentacao = function(){
 var eleela = function(){
  if(pessoa.sexo === 'Feminino'){
   return 'a';
  } else {
   return 'o';
  }
 };
 var anoanos = function(){
  if(pessoa.idade > 1){
   return 'anos';
  } else {
   return 'ano';
  }
 };
 var metrometros = function(){
  if(pessoa.caminhouQuantosMetros > 1){
   return 'metros';
  } else {
   return 'metro';
  }
 };
 return 'Olá, eu sou ' + eleela(); + pessoa.nomeCompleto + ', tenho '+ pessoa.idade + anoanos(); + ', ' + pessoa.altura + ', meu peso é ' + pessoa.peso + ' e, só hoje, eu já caminhei '+ pessoa.caminhouQuantosMetros + metrometros(); + '!';
}

Pelo erro no console, tá errado mesmo, mas como faria para colocar uma função dentro de um método?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @luanasallles =)
Você consegue fazer dessa forma sim :D

Como você fez funciona. O erro está no `return` do método `pessoa.apresentacao`: ao executar as funções `eleela`, `anoanos`, etc., você está colocando `;` após a execução dessas funções =)

Como você está concatenando o retorno dessas funções com a frase final, o sinal de `+` logo após o ponto-e-vírgula vai gerar o erro =)

**Comment by luanasallles** [comment]
Ahhhh entendi, debuguei várias vezes aqui e realmente não entendia o porque do erro.

Agora deu certo =D

Obrigada!!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :D
