### ISSUE TITLE
Challenge 04 dúvida com retorno do Método

### ISSUE THREAD

**Issue by luanasallles** [da2k/curso-javascript-ninja#1108]
Não sei o que está dando errado na função do exercício 4, pois se eu adiciono 2 + 3 ele retorna //carro está lotado  mas se eu tento adicionar (6) ele retorna // so cabem mais 3 lugares.

Pode me ajudar? vou colocar o método e as chamadas aqui embaixo.

carro.adicionarPessoas = function(recebePessoas){
  var dentroCarro = carro.quantidadePessoas + recebePessoas;
  var pessoaPessoas = carro.quantidadePessoas === 1 ? 'pessoas' : 'pessoa'; 

  if (dentroCarro === carro.assentos && dentroCarro >= carro.assentos){
   return 'O carro já está lotado!';
  }
  if (dentroCarro > carro.assentos) {
   return 'Só cabem mais ' + (carro.assentos - carro.quantidadePessoas) + ' ' + pessoaPessoas +'!';
  }
   carro.quantidadePessoas += recebePessoas;
   return 'Já temos ' + carro.quantidadePessoas + ' pessoas no carro!';
};

carro.adicionarPessoas(2)
"Já temos 2 pessoas no carro!"
carro.adicionarPessoas(3)
"O carro já está lotado!"
carro.adicionarPessoas(6)
"Só cabem mais 3 pessoa!"

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @luanasallles  =)
O problema, provavelmente, está no seu primeiro if:

```js
if (dentroCarro === carro.assentos && dentroCarro >= carro.assentos)
```

Nesse caso, para que a verificação retorne `true` e ele entre nesse `if`, é necessário duas coisas:
1) Que `dentroCarro` seja igual a `carro.assentos`;
2) Que `dentroCarro` seja maior ou igual a `carro.assentos`.

Olhando para essa expressão, a única forma dela ser verdadeira seria se `dentroCarro` for exatamente igual a `carro.assentos`, pois somente assim é que as duas expressões serão verdadeiras. Caso contrário, ele vai ignorar esse `if` e seguir para o restante do código =)

Nesse `if`, vc pode usar somente a segunda expressão, que deverá funcionar como você precisa =)

**Comment by luanasallles** [comment]
Ahhh não conseguia identificar o erro de maneira nenhuma, o cérebro pifou fortemente nesse exercício hihi.

Oremos para conseguir terminar o curso hahaha.

Obrigada pelo help!

**Comment by fdaciuk** [comment]
haha! Relaxa =)

Os desafios são pra quebrar a cabeça mesmo :D

Qualquer dúvida, só avisar =)
