### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by gabrielazevedo** [da2k/curso-javascript-ninja#1118]
Dei um fork no projeto, criei a branch "challenge-01" e fiz o exercício, quando terminei o exercício no meu repositório, eu dei um "commit" e quando cliquei no repositório do da2k, não apareceu para dar o Pull Request e nem clicando em "New Pull Request" eu consegui enviar.

OBS: Eu já tinha feito este exercício "challenge-01" a um tempo atrás, mas quis começar tudo do 0, e exclui o repositório antigo e clonei tudo novamente.

Obrigado.

@fdaciuk

**Comment by gabrielazevedo** [comment]
Consegui, estava tantando dar PR, enquanto estava dentro do arquivo "reademe", voltei na raiz onde tem todas as pastas dos challenges, e consegui dar o PR.

**Comment by fdaciuk** [comment]
Que bom que deu certo @gabrielazevedo =)
Qualquer coisa só avisar :D
