### ISSUE TITLE
[Aula 2] Penúltimo exercício 

### ISSUE THREAD

**Issue by gabrielazevedo** [da2k/curso-javascript-ninja#1126]
Tem o seguinte exercício:
/*
Crie uma função com as seguintes características:
1. A função deve receber 3 argumentos.
2. Se somente um argumento for passado, retorne o valor do argumento.
3. Se dois argumentos forem passados, retorne a soma dos dois argumentos.
4. Se todos os argumentos forem passados, retorne a soma do primeiro com o segundo, e o resultado, dividido pelo terceiro.
5. Se nenhum argumento for passado, retorne o valor booleano `false`.
6. E ainda, se nenhuma das condições acima forem atendidas, retorne `null`.
*/

Quero que me ajude, pois não estou conseguindo finalizar. Estou fazendo da seguinte form:

function teste(x, y, z){
   if(x){
      return x;
    } else if(x, y){
      return x + y;
    } else if( x, y, z){
      return x + y / z;
    } else if( x === undefined && y === undefined && z === undefined)
      return false;
    } else{
      return null;
    }
}

Me ajude pois não estou conseguindo finalizar :(

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @gabrielazevedo! =)

Vamos ver os passos que o exercício pede, e tentar fazer aos poucos, ok?

> A função deve receber 3 argumentos.

Até aqui ok, você fez certo =)

> Se somente um argumento for passado, retorne o valor do argumento.

Como você garante que somente o primeiro argumento foi passado? Se você testar só por ele, não dá pra saber, o segundo e o terceiro também podem ter sido passados, correto?

Então, para garantir que somente o primeiro foi passado, você precisa testar se ele é diferente de `undefined` (lembra que vimos isso?), e também testar se os outros dois são iguais a `undefined` =)

Seguindo essa lógica, já fica mais fácil de seguir =)

Tente fazer, e qualquer dúvida me avise :D

**Comment by gabrielazevedo** [comment]
Pooow lembro sim, me ajudou bastante. Mais tarde vou fazer e mando o PR.
Obrigado @fdaciuk :)

**Comment by fdaciuk** [comment]
\o/
qualquer coisa só avisar :D
