### ISSUE TITLE
[Aula 2]

### ISSUE THREAD

**Issue by gabrielazevedo** [da2k/curso-javascript-ninja#1129]
Terminei o exercício como você me explicou na ultima issue.

1° Gostaria que verificasse por favor, se fiz correto desta vez, como a dica que me deu na ultima issue.

2° Uma dúvida, Já tinha dado o PR do challenge-02, quando entrei pelo Github, eu somente dei um commit e ele já apareceu no PR que tinha dado da ultima vez. Então quando dou 1 PR, não preciso faze-lo novamente? Somente dar o commit?

3° Mais uma dúvida, no penultimo exercicio do Challenge 2, tem uma parte que tem o seguinte pedido:
"5. Se nenhum argumento for passado, retorne o valor booleano `false`."

Eu fiz da seguinte form.
else if(x === undefined && y === undefined && z === undefined){
	return false;
}

Mas gostaria de saber se eu poderia ter usado este outro operador lógico, o "||" e ficar assim:
else if(x === undefined || y === undefined || z === undefined){
	return false;
}

Obrigado pela ajuda.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @gabrielazevedo =)

1. Vou dar uma olhada, mas você pode sempre conferir com a solução do desafio na próxima aula =)

2. Isso mesmo! Com o PR aberto, só precisa comitar *na mesma branch*, que o GitHub entende que você está só alterando o PR =)

3. Me explica o que você entendeu sobre a diferença entre `&&` e `||`.

**Comment by fdaciuk** [comment]
@gabrielazevedo conseguiu entender sobre o `&&` e `||` ?

**Comment by gabrielazevedo** [comment]
Entendi sim, veja se estou correto:

else if(x === undefined && y === undefined && z === undefined)
se dois valores forem preenchidos e um não for preenchido, ele vai retornar verdadeiro, porque ele verifica todos os três e ver se um está preenchido.

Já desta forma:

**Comment by fdaciuk** [comment]
É isso mesmo =)
E isso responde a sua pergunta inicial, correto? Não é possível simplesmente substituir o `&&` por `||` =)

Normalmente, quando trocamos o `&&` por `||`, temos que inverter a comparação: se era verdadeiro, vira falso e vice-versa.

Exemplo do que seria similar usando `&&` ou `||`:

```js
x === undefined && y === undefined && z === undefined
x !== undefined || y !== undefined || z !== undefined
```

Essas duas expressões acima são similares. Veja que, quando trocamos de `&&` para `||`, temos que inverter a verificação também, de `===` para `!==`, **nesse caso**.

É importante sempre pensar no seguinte, quando se usa um `if`:

O bloco dentro do `if` só será executado se a expressão testada retornar `true`. Caso contrário, o bloco do `if` será ignorado.

Acho que assim fica mais fácil de entender =)

Bom, ficou claro a sua dúvida então? Tem algo mais que não tenha ficado claro?

**Comment by fdaciuk** [comment]
@gabrielazevedo vou fechar a issue, mas se ainda tiver dúvidas com relação à esse assunto, só avisar que eu reabro, ok? =)
