### ISSUE TITLE
Regex para caracteres alfanuméricos acentuados

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-javascript-ninja#1146]
Fala Fernando, beleza? Como faço para dar match com caracteres acentuados, visto que o \w não pega os mesmos. Valeu, abs!

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @pedromuraki! Não sei em qual aula sobre Regex você está, mas a base de caracteres permitidos pelo JavaScript vêm da tabela unicode, que você pode ver aqui: http://unicode-table.com/en/

A regex funciona da mesma forma, segundo a ordem dessa tabela. Então, para pegar os caracteres acentuados, você pode criar um grupo de caracteres que vai da primeira letra acentuada até a última, ou montar o grupo da forma que você precisar =)

Ficou claro?

**Comment by pedromuraki** [comment]
@fdaciuk já vi todas as aulas sobre regex, mas achei que houvesse algo mais simplificado pra selecionar os alfanuméricos já incluindo os acentuados. Valeu pela referência, abs!

**Comment by fdaciuk** [comment]
Show! É que a forma de usar caracteres acentuados são diferentes nos vários idiomas existentes, por isso não existe uma regra específica para eles =)

Mas usando a tabela unicode acima você consegue fazer o agrupamento que precisa =)

Qualquer dúvida só avisar :D
