### ISSUE TITLE
addEventListener

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-javascript-ninja#1148]
Duas dúvidas sobre addEventListener:

1. É possível atribuir um mesmo evento pra dois ou mais elementos sem ter que duplicar o código? Ex:
**($el1 ou $el2).addEventListener('click', func, false);**

2. É possível atribuir mais de uma função no evento? Ex:
**$el.addEventListenter('click', func1 e func2, false);**

Abs!

@fdaciuk

**Comment by fdaciuk** [comment]
Olá @pedromuraki! Não é possível fazer dessa forma, em nenhum dos casos, pelo motivo de que o método `addEventListener` tem uma assinatura (ou contrato, como alguns chamam), que é o seguinte:

1. Ele é um método de um objeto referente a um nó do DOM;
2. Ele recebe 3 parâmetros: 
  2.1. O primeiro é o evento que será criado um listener;
  2.2. O segundo é a função de callback que será executada quando o evento for disparado;
  2.3. O terceiro é para saber se é preciso "usar captura" ou não. 

[Aqui](https://developer.mozilla.org/pt-BR/docs/Web/API/Element/addEventListener) você consegue ver a documentação do `addEventListener`.

Mas, como sabemos, esse método não passa de uma simples função JavaScript, e pode ser tratada como tal.

Você mesmo pode criar uma implementação que, por exemplo, receba um array de elementos e atribua o mesmo evento a cada um desses elementos do array.

E, no segundo exemplo, você pode fazer o mesmo: criar uma implementação de uma função que receba o evento e duas ou mais funções, que serão atreladas ao evento de um elemento. Um exemplo bem claro disso é quando você usa o `querySelectorAll` para selecionar vários elementos do DOM. Ele retorna uma `NodeList`, que é um conjunto de nós HTML do DOM, onde você pode atrelar eventos. Mas você não consegue atrelar eventos na `NodeList`, precisa atrelar a cada elemento separadamente. 

Então você pode fazer como mostramos em aula:

```js
var $divs = document.querySelectorAll('div');

Array.prototype.forEach.call($divs, function ($element) {
  $element.addEventListener('click', callback, false);
});
```

Assim você consegue atrelar eventos a todos os elementos dentro da `NodeList`. O `Array.prototype.forEach.call`, passando a variável `$divs` que é a `NodeList` como `this`, faz com que o JS entenda que o `$divs` deve ser tratado como um array, mas isso eu expliquei em aula =)

Deu pra entender? Qualquer dúvida, só avisar!

**Comment by fdaciuk** [comment]
Fala @pedromuraki! Vou fechar a issue, mas se ainda ficou alguma dúvida, me avisa que eu reabro, ok? :D
