### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-javascript-ninja#1149]
Posso utilizar a IIFE desta maneira:
**(function func(){
  console.log('ok');
})();**

ao invés dessa:
**function func(){
  console.log('ok');
}
func();**

?

Valeu, abs.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @pedromuraki! No primeiro exemplo, você simplesmente nomeou a IIFE. E sim, isso é válido. Mas só será útil se você estiver fazendo algum código recursivo, onde você precise invocar essa função após a sua execução. Fora isso, não vai ter muita necessidade =)

O segundo exemplo não é uma IIFE. A ideia da IIFE é que a função seja **auto-executável**. No segundo exemplo você simplesmente cria a função literal, e depois invoca ela manualmente.

Deu pra entender a diferença? =)

**Comment by fdaciuk** [comment]
@pedromuraki vou fechar a issue, mas se ainda restaram dúvidas, me avisa que eu reabro, ok?

 :D
