### ISSUE TITLE
Return de múltiplos valores

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-javascript-ninja#1150]
É possível retornar múltiplos valores na execução de uma função? Ex:

var x;
var y;
function func() {
    var x = 10;
    var y = 20;
    **return x e y;**
}

Valeu, abs.

@fdaciuk

**Comment by hevertoncastro** [comment]
Você pode retornar um array ou objeto com estes valores @pedromuraki.

**Array**

```javascript
var x;
var y;

function func() {
  x = 10;
  y = 20;
  return [x, y];
}
console.log(func()[0], func()[1])
```

 **Objeto**

```javascript
var x;
var y;

function func() {
  x = 10;
  y = 20;
  var values = {
    x: x,
    y: y
  }
  return values;
}
console.log(func().x, func().y)
```

**Comment by fdaciuk** [comment]
Obrigado @hevertoncastro! =)

É isso mesmo @pedromuraki! Cada função só pode retornar um único valor. Mas para retornar mais valores, você pode usar arrays ou objetos =)

**Comment by fdaciuk** [comment]
@pedromuraki, vou fechar a issue, mas se ainda ficou alguma dúvida, só avisar que eu reabro :D

**Comment by pedromuraki** [comment]
@hevertoncastro @fdaciuk valeu pessoal, tinha esquecido de responder! abs.

**Comment by fdaciuk** [comment]
Qualquer coisa só avisar =)
