### ISSUE TITLE
Nunca mais foi corrigido um exercício meu.

### ISSUE THREAD

**Issue by nono21** [da2k/curso-javascript-ninja#116]
Fernando, acho que não estou enviando de forma correta meus exercícios para você porque nunca mais recebi nenhuma notificação de correção.
Tenho todas as branchs criadas com todos os exercícios feitos... Devo dar um push ou merge para algum outro repositorio? Desculpe as perguntas mas sou iniciante nesse git.
Abraço

**Comment by fdaciuk** [comment]
Fala cara! Olha só seus Pull Requests:

![selection_117](https://cloud.githubusercontent.com/assets/487669/7761883/18b3ead8-0002-11e5-9107-c2cf5de9c6af.png)

Os desafios 01, 02 e 03 estão ok! Esses eu marco com a tag `revised`.

O exercício 04 ainda está aguardo a sua correção. Você pode acessar [nesse link](https://github.com/da2k/curso-javascript-ninja/pull/82) para ver os comentários.

Os outros desafios provavelmente você não enviou o _pull request_. Você tem dúvidas de como fazer isso? Me avisa que eu tento te ajudar, ok? xD

Nos últimos vídeos de cada aula, eu explico como fazer o pull request. No primeiro é o que deve estar mais detalhado.

Para você verificar se o seu pull request foi enviado corretamente, você pode acessar o repositório do curso, e clicar em **Pull Requests**:

![selection_118](https://cloud.githubusercontent.com/assets/487669/7761942/0945d506-0003-11e5-9f7c-41571ce620b8.png)

Você também consegue ver pela home do Github. Acessando o Github, após logar, você verá um link **Pull Requests** no canto superior direito:

![selection_119](https://cloud.githubusercontent.com/assets/487669/7761950/20237eea-0003-11e5-9c9c-8bf5cf0f3fc4.png)

Clicando ali você vai ver todos os pull requests que você fez :)

Ah, sempre que você corrigir um desafio, você faz um comentário lá me marcando (com @fdaciuk) que eu recebo uma notificação para corrigir, blz?

Qualquer dúvida, me avise! Pode comentar aqui mesmo que vou te ajudando a enviar se não conseguir, ok? :smile:

**Comment by nono21** [comment]
Vou precisar de uma ajuda sim... No challenge 04 preciso fazer esse pull
request ou só dar o push?

2015-05-21 21:49 GMT-03:00 Fernando Daciuk <notifications@github.com>:

**Comment by fdaciuk** [comment]
Fala @nono21! O challenge 04 já tem pull request aberto, então é só fazer push para essa branch no seu repositório mesmo, que as alterações já irão aparecer lá no PR aberto ;)

Para os outros desafios, é só fazer o pull request da seguinte forma (vou mostrar do 5, os outros só seguir igual):

No seu repositório, acesse a branch `challenge-05`:

![selection_120](https://cloud.githubusercontent.com/assets/487669/7762147/7d55a130-0006-11e5-826d-528cc5ce0bfd.png)

Depois clique no botão verde, para criar o pull request:

![selection_121](https://cloud.githubusercontent.com/assets/487669/7762151/851af6d6-0006-11e5-9ab0-1116f3ac5b48.png)

Vai aparecer essa tela, já com as opções corretas selecionadas:

![selection_122](https://cloud.githubusercontent.com/assets/487669/7762160/b4349350-0006-11e5-8d75-648a0092ee88.png)

Em **base fork** deve estar marcado **da2k/curso-javascript-ninja**, e a branch, em **base**, deve ser a **master**.

Em **head fork**, deve ser o seu repositório: **nono21/curso-javascript-ninja**, e a branch, em **compare**, deve ser a do desafio que você está enviando. Nesse caso, o **challenge-05**.

Aí você só confere se só o arquivo de desafio 05 foi alterado, na mesma tela, só rolando um pouco pra baixo:

![selection_123](https://cloud.githubusercontent.com/assets/487669/7762190/227bbe2e-0007-11e5-9c2f-3694e13c0acf.png)

Fazendo isso, você garante que está sendo enviado só o desafio 5 mesmo :)

Agora pode clicar no botão verde **Create pull request** :smile: 

Depois é só fazer isso com cada desafio que falta! :)

Se ainda tiver dúvidas, me avise!! :D

**Comment by nono21** [comment]
Obrigado Fernando! Será que deu certo agora? Mandei bala ai nos pulls... Me confirma se está ok por favor.

**Comment by fdaciuk** [comment]
Agora sim @nono21! o/

![selection_124](https://cloud.githubusercontent.com/assets/487669/7762323/3d7bb9f2-0009-11e5-9a8a-ef41ca8952b4.png)

Vou fazer as correções ;)
