### ISSUE TITLE
[Aula 1] Parâmetros de Funções e Operadores abreviados

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-javascript-ninja#12]
Oi Daciuk!
Fiquei em dúvida de quais são os parâmetros válidos que podemos passar na função, quais são as restrições ou parâmetros inválidos?

Você pode por favor explicar sobre os operadores abreviados de multiplicação e divisão?

**Comment by fdaciuk** [comment]
Opa Anderson! Sobre os parâmetros das funções, vamos falar nas próximas aulas! Essa foi somente uma pequena introdução :)

Os operadores abreviados de multiplicação e divisão funcionam exatamente igual os de adição e subtração.

Só que os operadores de adição e subtração tem duas formas abreviadas:

```js
var soma = 0;
soma++;
```

Os operadores `++` e `--` causam efeito colateral, alterando o valor original da variável `soma` para `1` (no exemplo acima), sem precisar usar o operador de atribuição `=`.

A segunda forma abreviada é assim:

```js
var soma = 0;
soma += 1;
```

Que é o mesmo que fazer isso:

```js
var soma = 0;
soma = soma + 1;
```

No caso, eu pego todo o valor da variável `soma` (zero), adiciono `1` e atribuo novamente à variável `soma`. Assim ela fica com o valor atualizado: `1`.

Para multiplicação e divisão, funciona igual o segundo exemplo que mostrei:

```js
var mult = 3;
mult *= 3;
```

Nesse caso, da multiplicação, a variável `mult` vou declarada com o valor `3`. Depois eu peguei todo o valor dela, e multipliquei por `3`, atribuindo o resultado à ela novamente.

Seria o mesmo que fazer:

```
var mult = 3;
mult = mult * 3;
```

O resultado disso é `9`. Se você pegar esse código e colocar no console do seu navegador ou no console do node, vai poder ver os resultados mais facilmente.

Ficou claro?

:)

**Comment by theandersonn** [comment]
Ficou Claro sim!
obrigado.
