### ISSUE TITLE
[challenge 10]

### ISSUE THREAD

**Issue by kalyanelordao** [da2k/curso-javascript-ninja#1212]
Olá Fernando, 
tive duas dúvidas no desafio 10.

1. Na hora de criar o objeto  _operation_, cada propriedade (que agora é uma função) recebe dois parâmetros, na resolução do desafio tu define os parâmetros como (x,y), por exemplo:

           operation = {
              '+': function(x, y) {
                  return x + y;
          },
já quando tu vais criar a função _showOperationMessage_ tu pede para passar o operator, o primeiro e o segundo número, nessa hora, tu passa:

          function showOperationMessage(operator, number1, number2)

Existe algum motivo para tu nomear os dois parâmetros da **_showOperationMessage_** diferente dos parâmetros do objeto **operation**?

Obs: Testei com parâmetros iguais, tanto no objeto como na função e **funfou**.
         E, testei com parâmetros diferentes, no objeto e na função e também **funfou**.

2. A segunda dúvida é no uso do **_return_** que tu utiliza no retorno de todas as funções criadas, exceto na função:

        _if(sum){
             num1 = 10;
             num2 = 10;

           console.log( showOperationMessage(operationSignal, num1, num2), sum(num1, num2));
        }_ ...

Agradeço desde já,
Kalyane.

@fdaciuk

**Comment by fdaciuk** [comment]
Olá @kalyanelordao! Vamos lá =)

## Dúvida 1

Sobre os nomes dos parâmetros passados para as funções: na verdade, não importa o nome dado. O que você precisa saber com relação a isso é que, o nome dos parâmetros serão usados da mesma forma que se você estivesse criando variáveis locais, internas à função. O escopo do nome dos parâmetros é a função onde eles estão sendo criados.

Se houver alguma variável com o mesmo nome dos parâmetros passados, em algum escopo acima em que essa função tenha acesso, os nomes que estão mais adentro, prevalecerão. Exemplo:

```js
var number = 1;
function whichNumber () {
  var number = 2;
  return number;
}

console.log(number) // 1
console.log(whichNumber()) // 2
```

Veja que o valor da variável `number`, fora da função, é igual a `1`. Já o valor de `number` dentro da função é `2`, pois variáveis locais têm precedência sobre variáveis globais (ou fora da escopo da função). 

## Dúvida 2

Nesse ponto do código que você mostrou, o código não está dentro de uma função específica (somente dentro da IIFE). Como a IIFE é uma função auto-executável, o retorno dela não é importante, pois não atribuímos esse retorno a nenhuma variável, nem fazemos nada que realmente necessite desse valor para alguma coisa. Por isso não é necessário o uso do `return`.

Mas para todas as outras funções, nós precisamos dos valores retornados, por isso o uso do `return`.

Para esses exemplos, pode não ter ficado muito claro a diferença do `return` e do `console.log`, pois nós estamos sempre vendo o resultado no `console` do Node, ou no `console` do browser.

Mas a diferença básica é a seguinte: `console.log` vai simplesmente **exibir** uma mensagem no `console`, seja ele no Node ou no browser. Já o `return`, usado dentro de uma função, vai retornar um valor, que pode ser manipulado da forma como você precisar: você pode atribuir esse valor à uma variável, pode passar como parâmetro para uma função, ou ainda pode exibir esse valor no console.

Vou exemplificar para tentar deixar mais claro: se uma função não tiver o `return`, dizendo que a função **devolve** algum valor quando ela é executado, então o retorno da função será `undefined`:

```js
// vamos criar uma função que retorne a string `alguma coisa`:
function myFunction () {
  return 'alguma coisa';
}

// agora vamos atribuir esse valor à uma variável:
var something = myFunction();

// E agora, vamos exibir o valor de `something`, que é o resultado da função `myFunction`, no console:
console.log(something);
```

Nesse primeiro exemplo, você pode ver que a função `myFunction` **retorna** um valor (`alguma coisa`).

Agora, e se usássemos o `console.log` no lugar, o que aconteceria?

```js
function myFunction () {
  console.log('alguma coisa');
}

var something = myFunction(); // nesse momento, como a função é executada, é mostrado no console o valor `alguma coisa`, resultado do `console.log` dentro da função myFunction

// E ao tentar exibir o valor de `something` no console, olha o que acontece:
console.log(something); // undefined 
```

Veja que, nesse segundo exemplo, o valor de `something` é `undefined`, porque a função não retorna nada, simplesmente chama o `console.log`, que só serve única e exclusivamente para exibir mensagens no console =)

Ficou mais claro?

**Comment by kalyanelordao** [comment]
Ótima explicação @fdaciuk.

Agradeço mais uma vez.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
