### ISSUE TITLE
Dúvida extra 

### ISSUE THREAD

**Issue by lucasalbuquerque** [da2k/curso-javascript-ninja#1220]
Fala professor, blz?

Primeiramente estou muito grato, 3 módulos assistidos e já sei fazer mais do que nunca imaginei.

Estou tentando fazer uma função que exibe quantos meses e dias faltam para o aniversario de uma determinada pessoa.

Em minha mente desenhei o algoritmo de que devo pegar o dia e mes atual, depois o dia e mes que a pessoa faz aniversario, antes de mais nada.

Até ai blz.. 

	var d = new Date,
	ano_atual = d.getFullYear();
	mes_atual = d.getMonth();
	dia_atual = d.getDate();

	mes_aniver = 4;
	dia_niver = 5;

Para descobrir quantos meses faltam fica simples, é só fazer o mes_atual - mes_aniver.

Agora para descobrir quantos dias faltam não faço ideia, vc consegue me dar uma luz?

Tks!

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @lucasalbuquerque =)

Que bom que está curtindo :grin: 

Em aulas futuras, vamos falar sobre o objeto `Date`, mas vou adiantar aqui alguns pontos xD

Esse seu cálculo pode dar errado, por alguns motivos, vou listar eles:

1) o método `getMonth()` tem como base `0`. Ou seja: os meses vão de `0` a `11`, não de `1` a `12`. Então, para pegar o mês correto, você deveria fazer `d.getMonth() + 1`.

2) Para calcular qualquer tipo de data, você precisa levar em consideração a data completa, não somente os meses. 

Exemplo:

Estamos no mês de Janeiro de 2017, e você faz aniversário no mês de março. Então você teria:

```js
var mesAtual = 1;
var mesAniversario = 3;
mesAniversario - mesAtual; // 2 -> ou seja: faltam 2 meses para o seu aniversário!
```

Isso funcionaria. Mas e se nós estivéssemos em Dezembro de 2016? Aí esse cálculo daria errado:

```js
var mesAtual = 12;
var mesAniversario = 3;
mesAniversario - mesAtual; // -9 -> O valor correto deveria ser 3
```

Então não vai funcionar simplesmente tentando calcular os meses =)

O que você precisa fazer é o seguinte: pegar um tipo de valor que seja usado como base, e que esse número contenha a data completa (dia, mês e ano). Preferencialmente o menor valor para calcular tempo que você pode ter: milissegundos.

O objeto `Date` tem um método chamado `getTime()`, que traz o tempo em milissegundos entre `1 de Janeiro de 1970 00:00:00 UTC` até a data atual (inclusive com horas, minutos, segundos e milissegundos):

```js
var hoje = new Date();
hoje.getTime(); // 1484395643831 // se você testar, vai dar um número maior que esse, pois o tempo não para xD
```

Até aí tudo bem! Agora você tem o valor em milissegundos do tempo que passou desde 01/01/1970 até hoje (14/01/2017).

Para saber quantos dias se passaram, você precisa saber o valor de UM DIA em milissegundos.

Para isso, você precisa fazer a conversão de tempo, transformando-o em milissegundos. Vamos criar algumas variáveis pra facilitar o entendimento:

```js
var UM_SEGUNDO = 1000; // tomando como base os milissegundos, 1 segundo é igual a 1000 milissegundos
var UM_MINUTO = 60 * UM_SEGUNDO; // um minuto são 60 segundos
var UMA_HORA = 60 * UM_MINUTO; // uma hora são 60 minutos
var UM_DIA = 24 * UMA_HORA; // um dia são 24 horas
```

Agora, sabendo qual o valor de `1 dia` em milissegundos, já conseguimos fazer nossos cálculos =)

Para saber quantos dias passaram desde o 15 do dezembro de 2016 até agora, por exemplo, é só fazer:

```js
var quinzeDeDezembroDe2016 = new Date(2016, 11, 15); // o construtor de data aceita alguns parâmetros.. os 3 primeiros são: ano, mês (começando em zero para janeiro) e o dia
var hoje = new Date();
var milissegundosPassados = hoje.getTime() - quinzeDeDezembroDe2016.getTime(); // usamos o `getTime` para saber quantos milissegundos passaram desde o dia 15/12/2016 até agora
var diasPassados = quinzeDeDezembroDe2016 / UM_DIA; // e para saber quantos dias passaram, só precisamos dividir o valor em milissegundos pelo valor de UM DIA, em milissegundos =)
```

Pronto, assim você pode calcular quantos dias faltam de uma data até outra!

---

Agora, para calcular quantos meses faltam, a fórmula é a seguinte:

```
mesAniversario - mesAPartir + (12 * (anoAniversario - anoAPartir)) // multiplicamos 12 para o resultado da diferença dos anos, pois temos 12 meses em um ano. Assim vemos a diferença de meses e somamos com a quantidade de diferença de anos VEZES 12.
```

Aí é só aplicar a fórmula:

```js
var dataAniversario = new Date(2017, 9, 14); // 14/10/2017
var dataAPartir = new Date(2016, 8, 1); // 01/09/2016

var mesAniversario = dataAniversario.getMonth(); // não precisa normalizar com +1 aqui, pois usamos o getMonth() das duas datas para o cálculo
var mesAPartir = dataAPartir.getMonth();

var anoAniversario = dataAniversario.getFullYear(); // pega o ano com 4 dígitos
var anoAPartir = dataAPartir.getFullYear();

mesAniversario - mesAPartir + (12 * (anoAniversario - anoAPartir)) // 13 meses =)
```

Deu pra entender?

Se alguma coisa não ficou clara, não se preocupe! Tem muita coisa ainda de JS pra ver no curso, e, até chegar no objeto `Date`, tudo isso deve estar mais claro na sua mente =)

Qualquer dúvida, só avisar :D

**Comment by fdaciuk** [comment]
@lucasalbuquerque ficou alguma dúvida com relação a esse assunto? Vou fechar a issue, mas se ainda não ficou claro, só avisar que eu reabro e debatemos novamente, até que fique claro, ok? =)
