### ISSUE TITLE
[Aula 2]

### ISSUE THREAD

**Issue by JoaoPauloDev** [da2k/curso-javascript-ninja#1263]
Boa tarde, estou tendo problema para clonar o diretório para o meu computador, estou dando o git clone usando o ssh, mas recebo a mensagem 
Cloning into 'curso-javascript-ninja'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Como posso resolver esse problema?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @JoaoPauloDev, tudo certo? =)

Você seguiu os passos da primeira aula, onde eu mostro como clonar o repositório (forkar, clonar, etc)?

Se fez isso, o problema é com sua chave SSH. Se você ainda não tem uma chave SSH no seu computador, você precisa criar ela e adicionar no GitHub, para que possa ter permissão de clonar usando SSH.

[Aqui](https://help.github.com/articles/connecting-to-github-with-ssh/) você encontra um passo a passo de como fazer. Me avise se deu certo ou não!

**Comment by JoaoPauloDev** [comment]
Opa Fernando, me desculpe, eu esqueci de responder hahaha.
Deu certo sim, valeu ;)

**Comment by fdaciuk** [comment]
Show @JoaoPauloDev! =)
Qualquer dúvida me avise xD
