### ISSUE TITLE
Challenge-09

### ISSUE THREAD

**Issue by joselialcosta** [da2k/curso-javascript-ninja#1268]
Boa tarde!
Estou um pouco travada no exercício dessa aula, não sei bem se consegui compreender o enunciado, mas vou colocar abaixo até onde eu consegui avançar. (Não quero ver o vídeo da resolução antes de conseguir resolver esse problema, entende?)

```

/*
  No desafio anterior criamos uma calculadora, usando uma estrutura funcional.
  Agora vamos criar uma outra calculadora, usando uma outra abordagem :D
  - Crie uma função `calculator` que recebe dois valores (números)
  por parâmetro. -ok
  - Essa função deve retornar uma outra função, que recebe um parâmetro
  chamado `callback`. -ok
  - Esse `callback` será uma função, que passaremos por parâmetro ao invocar
  o retorno de `calculator`.
  - O retorno dessa segunda função deve ser a função de `callback` passada
  por parâmetro, INVOCADA, e passando a ela por parâmetro os dois valores
  que foram passadas para a primeira função `calculator`.
  */

  function calculator(val1,val2) {
    return function(callback){
      return callback(val1,val2);
    };
  }



  /*
  Declare uma variável chamada `sum`, e atribua a ela a função `calculator`,
  passando dois números por parâmetro.
  */

  var sum = calculator(1,2);

  /*
  Sabemos que `sum` agora tem uma função atribuída a ela, que é o retorno de
  `calculator`. E essa função espera um parâmetro `callback`. O `callback`
  tem dois parãmetros disponíveis, que são os números que você acabou de passar
  para a chamada à `calculator` acima.
  - Mostre no console o retorno da invocação de `sum`, passando por parâmetro
  uma função anônima que irá retornar a soma dos dois números que essa função
  anônima tem como seus argumentos.
  */
  console.log( 'O resultado da soma é:'+ sum(function(){return 100 + 200 }) );
  // ?

```
A minha principal dúvida é: vc pede pra eu passar 2 números de parâmetro para a função `calculator`, atribuída a variável `sum`. Ok, fiz isso. Porém quando eu tento mostrar no console a invocação de `sum` eu me perdi 😢 

```
- Mostre no console o retorno da invocação de `sum`, passando por parâmetro
  uma função anônima que irá retornar a soma dos dois números que essa função
  anônima tem como seus argumentos.

```

Pode me ajudar a encontrar o que estou fazendo de errado?

Muito obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @joselialcosta! A ideia é essa mesmo :D

Só precisa ajustar essa linha: 

```js
 console.log( 'O resultado da soma é:'+ sum(function(){return 100 + 200 }) );
```

Se você reparar como a função `sum` funciona, vai ficar mais claro entender o que precisa ajustar. Vamos lá:

```js
  function calculator(val1,val2) {
    return function(callback){
      return callback(val1,val2);
    };
  }

  var sum = calculator(1,2);
```

Veja só: você criou a função `calculator` que recebe dois parâmetros, correto? O retorno dessa função é uma outra função que recebe um `callback` como parâmetro. Vamos tentar entender isso aqui:

- Ao executar `calculator`, passando os dois parâmetros, ela vai retornar uma função. Isso significa que, ao fazer isso aqui:

```js
var sum = calculator(1,2);
```

Você estará atribuindo para a variável `sum` o retorno da função `calculator`, correto?

O retorno da `calculator` é uma função que recebe uma função por parâmetro. Então você pode usar `sum` assim:

```js
sum(function () {...})
```

Até aqui está claro? Certo, vamos seguir =)

Agora, repare nessa linha da função `calculator`:

```diff
  function calculator(val1,val2) {
    return function(callback){
+     return callback(val1,val2);
    };
  }
```

Essa linha marcada acima é o que acontece com a função passada por parâmetro para `sum`.

Veja que, ao executar `sum`, você cria uma função que é passada por parâmetro pra ela, mas não faz nada com essa função, só passa ela por parâmetro.

Olhando para o último código de exemplo, você vê que, essa função passada é executada, e os parâmetros que você passou lá em cima, em `calculator` são passados para ela.

Logo, ao criar a função que você passa para `sum`, vc tem esses parâmetros disponíveis:

```js
sum(function (val1, val2) {...})
```

Deu pra entender? O `val1` e o `val2` acima são aqueles mesmos valores que você passou quando declarou a variável `sum`:

```js
var sum = calculator(1, 2);
```

Então, se você fizer:

```js
sum(function (val1, val2) { return val1 + val2 });
```

Você estará somando `1` e `2` =)

É um pouco complicado de entender de primeira mesmo, tente fazer e refazer o exercício várias vezes, pois programação funcional é um paradigma diferente do que você está acostumada.

Não se preocupe que, com o tempo, isso se torna mais natural. O importante é fazer e refazer várias vezes, até que fique claro, ok?

Se tiver dúvidas ainda quanto a isso, só avisar =)

**Comment by joselialcosta** [comment]
Acho que eu entendi, @fdaciuk .
Neste caso a função `calculator` servirá apenas para guardar os valores, quem vai executar a operação será `sum`. Por isso vc precisa passar os parâmetros via função anônima e finalmente somá-los?

**Comment by fdaciuk** [comment]
Isso! A função `calculator` vai funcionar como uma _closure_, guardando valores para serem acessados no futuro. Ela será a base da **calculadora**. Então, você poderá utilizar essa base para criar todas as operações matemáticas que quiser =)

**Comment by joselialcosta** [comment]
Beleza, vou tentar refaze-lo então. Muito obrigada!

**Comment by fdaciuk** [comment]
Nada =)
Qualquer dúvida, só avisar xD
