### ISSUE TITLE
Challenge 21

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-javascript-ninja#1274]
Boa noite Fernando, tudo bem?

Cara, eu fiz o challenge 21, e percebi que se clicar mais vezes no botao Start, a velocidade do cronometro aumenta, talvez pq ele execute mais vezes, em intervalos de tempo diferente a função timer.

Tem alguma maneira de isso não  acontecer?

https://github.com/da2k/curso-javascript-ninja/pull/1272

Valeu!

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @gustavom! Tem como resolver sim =)

Lembra que eu comentei que o `setTimeout` é assíncrono? Ou seja: ele coloca a função passada para ele por parâmetro no _event loop_ até que o tempo setado passe, e então a função seja executada.

Isso acontece para que a _thread_ principal da sua aplicação não fique bloqueada. O problema é que, a cada vez que você clica no botão, ele adiciona mais um evento ao _event loop_.

O que você precisa fazer é: ao clicar no botão para iniciar o timer, antes de criar o timer com o `setTimeout`, você precisa limpar esse timer, sacou? Assim sempre vai ficar somente um timer executando =)

Deu pra entender?

**Comment by gustavom** [comment]
Boa!!!
Na função do timer, começei ela limpando o setTimeOut:

```
function timer(){
        clearTimeout(temporizer);
        $timer.value = counter++;
        temporizer = setTimeout( timer, 1000 );
    }
```
Clicando no start varias vezes, mas ao clicar no stop, ele para tudo, legal!

Valeu!!

**Comment by fdaciuk** [comment]
Isso ae =)
