### ISSUE TITLE
[m02][A37]

### ISSUE THREAD

**Issue by RodrigoWP** [da2k/curso-javascript-ninja#1277]
Sobre o cssmodules, eu vi que ele resolve o "problema" do efeito global do css, até ai tudo bem.
Mas em produção tudo em apenas um arquivo, como ficaria? Funciona da mesma forma?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @RodrigoWP! Fica da mesma forma na verdade =)

Não entendi é a sua dúvida xD

**Comment by RodrigoWP** [comment]
Pensando o seguinte, 2 componentes com 1 botão em cada, se nos dois componentes eu tiver uma classe com o mesmo nome, cada um carrega com o seu estilo?

**Comment by fdaciuk** [comment]
Sim, na verdade a ideia do css modules é que você não fique se preocupando com colisão de nomes de classes mesmo. Ainda que você tenha dois componentes diferentes, com classes iguais, mas CSSs diferentes, as classes geradas serão diferentes para cada componente =)

Você ainda consegue configurar o nome da classe, para que ela contenha, além da hash gerada pelo css modules, outras informações, como o caminho para o seu componente. Assim fica fácil saber qual componente é quando você está inspecionando pelo dev tools =)

Dá uma olhada nesse link: https://github.com/webpack-contrib/css-loader#css-scope

**Comment by RodrigoWP** [comment]
Entendi! Então, em desenvolvimento foi de boa. Mas fiz um teste com o build de produção servindo no pushstate-server, e não rolou, não carregou os estilos. Posso ter esquecido de algo?

**Comment by fdaciuk** [comment]
Provavelmente faltou allguma configuração. Conseguiu resolver? =)
