### ISSUE TITLE
[Challenge 19] Possível problema na implementação da hasClass

### ISSUE THREAD

**Issue by pauloregis** [da2k/curso-javascript-ninja#1359]
Daciuk, no **challenge-19**, acredito ter encontrado um erro na implementação da função **hasClass**, porque ao testar se a classe _"conta"_ está presente na markup, a função está retornando true, quando deveria retornar false.

Veja nesse link, que criei no regex101
https://regex101.com/r/mAx3PJ/1

Isso deve ocorrer, porque a palavra _"conta"_ está contida em _"container"_, aí qlqr substring das classes que colocar para verificar se tem na markup vai retornar true.. sei que a implementação que está na aula resolve os casos do desafio, mas parece não deixar a função genérica.

Minha dúvida é saber se estou correto e, se sim, se essa minha implementação tá legal?

https://gist.github.com/pauloregis/37249f3df41d146060e3d2040d601dac

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @pauloregis!

Esse é o objetivo dos desafios: fazer você pensar fora da caixa! Realmente as soluções que eu mostro em aula nem sempre são as melhores. Fico feliz em você ter percebido esse caso, faz todo sentido. Faltaram alguns detalhes na regex para não permitir casar **pedaços** de uma classe existente =)

A sua solução funciona muito bem, e foi muito bem pensada: resolver a solução em pequenas etapas =) Parabéns :clap: :clap: 

**Nota:** fica como desafio tentar resolver com uma única regex. Topa? :sunglasses:

**Comment by pauloregis** [comment]
Fala @fdaciuk!

Fui atrás de mais conteúdo sobre expressões regulares e me deparei com o **\b** e, com ele, acredito ter chegado a uma solução utilizando apenas regex. Além de não permitir casar mais com **pedaços**, também permite que a markup venha somente em **uma linha**.

**Segue a solução para avaliação:**

https://regex101.com/r/QCh8tS/2
https://gist.github.com/pauloregis/37249f3df41d146060e3d2040d601dac

**Comment by fdaciuk** [comment]
Muito bom @pauloregis! O `\b` não foi mostrado no curso, mas ele resolve muito bem o problema, pra deixar a regex mais genérica, parabéns :dancer: :sparkles:
