### ISSUE TITLE
Challenge 25

### ISSUE THREAD

**Issue by JoaoPauloDev** [da2k/curso-javascript-ninja#1387]
Fala Fernando, beleza?

Sobre as possíveis duvidas até aqui, eu ainda não compreendi exatamente a função do prototype no js.

Eu uso o Array.prototype para usar os métodos de array, mas a unica diferença entre usar métodos com o prototype é que eu posso passar o contexto de execução para eles? ou existe outra diferença nos métodos de prototype e os comuns?

Além disso quando estendemos uma função construtora com o prototype, não podemos simplesmente adicionar a 'extensão' diretamente na declaração da função construtora?

Enfim, qual a principal razão da prototype?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @JoaoPauloDev! Bom, vamos lá: a ideia do `prototype`, é que você consiga manter referências de métodos entre vários objetos criados, ao invés de criar cópias desses métodos.

Voltando algumas aulas atrás, nós vimos que objetos, quando são criados e reatribuídos, eles são passados por referência. Lembra disso?

```js
var obj1 = { prop1: 1, prop2: 2 };
var obj2 = { prop1: 1, prop2: 2 };
console.log(obj1 === obj2); // false
```
O resultado acima é falso porque o `{}` é um atalho para `new Object()`, ou seja, cada vez que você usa `{}` para criar um objeto, ainda que ele tenha as mesmas propriedades de outro objeto já criado (exemplo acima), são dois objetos diferentes, criados em espaços de memória diferentes.

Agora, se você reatribui o mesmo objeto à outra variável, aí sim as duas variáveis irão apontar para o mesmo espaço de memória, logo o objeto das duas variáveis será o mesmo. Qualquer alteração em um irá refletir no outro:

```js
var obj1 = { prop1: 1, prop2: 2 };
var obj2 = obj1;
console.log(obj1 === obj2); // true

obj1.prop2 = 2
console.log(obj2.prop2); 2
```

Até aqui tudo bem? Então segue =)

Lembrando que, tudo o que não é `string`, `number`, `boolean`, `null` e `undefined`, é tratado como um **objeto** em JavaScript.

Então `object`, `array`, `function`, etc., são objetos. Se funções são objetos, então eles também são passados por referência!

Quando você cria uma função construtora, e atribui algum método ao `prototype` dessa função, a referência para aquele método fica atrelado à esse objeto `prototype`, criado na função.

Então, sempre que você cria um novo objeto usando essa função construtora, o JavaScript "aproveita" o mesmo método pendurado no `prototype` para esse novo objeto criado, ao invés de criar um novo objeto, e ocupar um outro espaço de memória, entendeu?

Por exemplo:

```js
function Test () {}
Test.prototype.method1 = function () { return 'method1' }

var test = new Test()
console.log(test.method1 === Test.prototype.method1); // true
```

Veja que o objeto criado tem o mesmo método pendurado no prototype de `Test`, e não só isso: são o mesmo objeto, ocupando o mesmo espaço de memória =)

Se você tentar dar um `console.log` em `test`, verá que ele não tem métodos e propriedades próprios. Esses métodos e propriedades estão no `prototype` de `Test`. Mas o `test` herdou do construtor `Test` por causa do `prototype` =)

---

Sobre usar `Array.prototype` para métodos de array:

Os colchetes - `[ ]` - são um atalho para `new Array()`. Então sempre que você cria um novo array usando essa notação, você está criando objetos diferentes em memória.

```js
console.log([1, 2, 3] === [1, 2, 3]); // false
```

Em alguns exemplos do curso, eu mostrei que você pode usar métodos de array para objetos que **não são arrays**, mas funcionam de forma parecida: no caso de `NodeLists`, por exemplo, que são elementos do DOM que são um outro tipo de objeto, mas o comportamento deles é parecido com o de um array.

Como eles não são arrays, eles não têm os métodos que usamos para array (map, filter, reduce, etc)., mas você pode fazer um _workaround_ e usar o `Array.prototype.map.call(nodeList)`, para passar o `nodeList` para o método `map` como `this`, e assim utilizar o método `map` em NodeLists, já que ele só existe nos objetos do tipo `array`.

_E por que não usar `[].map`, que é bem mais curto que `Array.prototype.map`?_

Exatamente pelo motivo citado acima! `[]` vai criar um novo `array` vazio em memória só para usar o método `map` dele. Porque fazer isso se eu posso utilizar uma referência ao método `map` que já existem em `Array.prototype`?

Deu pra entender?

Se ficou alguma dúvida ainda, só avisar :D

**Comment by JoaoPauloDev** [comment]
![prototype](https://cloud.githubusercontent.com/assets/25267642/25535202/a0c48f6c-2c0c-11e7-99ab-4d0832e15437.PNG)

Agora eu peguei melhor o propósito da coisa hahahahaha.
Então ao invez de alocar na memoria para cara objeto criado uma função nova, nós simplesmente usamos a que foi declarada no prototype da função?

Upei uma imagem para tentar explicar melhor o que eu quis dizer.

Muito obrigado Fernando :D

**Comment by fdaciuk** [comment]
> Então ao invez de alocar na memoria para cara objeto criado uma função nova, nós simplesmente usamos a que foi declarada no prototype da função?

Exatamente isso =)

O que você precisa ter em mente, e tomar cuidado, é com a mutabilidade dos valores. Se você atribuir um valor ao prototype de uma função construtora, mas modificar a atribuição no objeto criado à partir dessa função, o valor utilizado será sempre o último:

```js
function Test () {};
Test.prototype.prop1 = 1;

var test = new Test()
test.prop1 = 2
console.log(test.prop1 === Test.prototype.prop1); // false
```

Se você reatribuir alguma propriedade, ela será alterada, e o valor será diferente do apresentado no `prototype` do construtor.

Tem também a questão de que objetos em JavaScript são mutáveis, então, se você tiver alguma propriedade que seja um tipo de objeto no construtor, e modificar esse objeto no objeto criado, o objeto no prototype também será modificado, por causa da referência:

```js
function Test () {};
Test.prototype.prop1 = [1, 2, 3];

var test = new Test();
test.prop1.push(4);
console.log(test.prop1); // [1, 2, 3, 4]
console.log(Test.prototype.prop1); // [1, 2, 3, 4]
console.log(test.prop1 === Test.prototype.prop1); // true
```

Veja que, se você não reatribuir o valor, mas modificar o objeto (no caso do array, usando o método `push`, que ao invés de retornar um novo array, modifica o array original), o objeto no `prototype` também será modificado, pois a referência vale também para o `prototype`.

E um outro ponto que é importante saber é que, mesmo que um objeto já tenha sido criado (usando `new`), e em um ponto mais pra frente da sua aplicação você modificar o prototype do objeto construtor, adicionando mais métodos, esses novos métodos vão estar disponíveis também no objeto que já tinha sido criado:

```js
function Test () {};
Test.prototype.prop1 = 1;

var test = new Test()
console.log(test.prop2); // undefined

Test.prototype.prop2 = 2;
console.log(test.prop2); // 2
```

Acho que é isso que você precisa saber sobre `prototype` =)

Temos exercícios no curso para o uso do `prototype`, para que você entenda como ele funciona, mas minha dica é: evite usar qualquer coisa que precise do `this`. Prefira sempre funções simples, que são previsíveis, e tente sempre trabalhar com imutabilidade, substituindo métodos como `push`, `pop`, `shift`, `unshift`, por `concat`, `map`, `filter`, `reduce`, etc., que sempre irão retornar um novo array ou um novo objeto qualquer =)

Qualquer dúvida, só avisar :D

**Comment by JoaoPauloDev** [comment]
Perfeito Fernando, entendi tudo certinho.
Muito obrigado mesmo pela ajuda :smile: 
Um forte abraço.
