### ISSUE TITLE
Challenge 28

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-javascript-ninja#1403]
@fdaciuk eu tinha feito uma solução minha e depois fiz a sua, que esta na correção aqui, mas tanto na minha e na sua, quando testo com um CEP que não existe, não passa pelo tratamento de erro.

Realmente não percebi o que fiz de errado.

E quando o status volta como 400?

Valeu!!!

Link para o meu arquivo

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @gustavom! É referente ao código [desse PR](https://github.com/da2k/curso-javascript-ninja/pull/1402), certo?

Vou analisar aqui e já te digo o que aconteceu =)

**Comment by gustavom** [comment]
Isso mesmo @fdaciuk .
Valeu!!!

**Comment by fdaciuk** [comment]
Pronto @gustavom, comentei lá no seu PR =)
Era só um erro de _typo_ mesmo :D

**Comment by gustavom** [comment]
Boa tarde @fdaciuk . Eu vi o comentário, valeu! Não tinha visto o "s".

Mas, ainda assim, quando busco por um CEP que não existe, por exemplo "5" e o endereço "https://viacep.com.br/ws/5/json/" retorna o status 400, no console da um erro na função "`handleSubmitFormCEP `" no "`ajax.send();`".

Como eu poderia tratar esse erro?

**Comment by fdaciuk** [comment]
Show! Bom, pra tratar o status, você pode checar como está fazendo na função `isRequestOk`. No caso, `readyState === 4` significa que a requisição terminou. Ae você checa se o `status` é maior ou igual a `400`, que seriam status de erro. Se for esse status, a resposta é a mensagem de erro =)

**Comment by gustavom** [comment]
Valeu @fdaciuk .
Testei outras coisas, e inseri um "else" na função "handleReadyStateChange" e também funcionou.

**Comment by fdaciuk** [comment]
Também dá =)
Só pra garantir que foi erro mesmo, você pode testar se:
- Requisição com sucesso: status >= 200 && status <= 300
- Requisição com erro: status >=400

**Comment by gustavom** [comment]
Valeu!!!

**Comment by gustavom** [comment]
Vou rever as aulas novamente para fixar melhor o conteúdo.
Com essas duas verificações que passou, ficou confuso novamente, acho que deixei passar algum conteúdo. Pois o erro do console, ele aponto 4 erros de 'get bad request 400', então ainda tenho dúvida, em qual momento da aplicação, devo verificar o status da conexão quando deu erro, pois parece que em um momento ela ocorre com sucesso, e depois de ver que o cep indicado na url não existe, ele devolve o erro.

**Comment by fdaciuk** [comment]
Legal! Assim.. a função de callback do evento `readystatechange` é executada a cada vez que o `readyState` muda. O valor dele pode ser de 1 a 4. Quando chega a 4, significa que a requisição terminou. Então você só precisa checar dentro dessa função se o `readyState` é 4, e então verificar o status que retornou, pra ver se foi com erro ou sucesso =)

**Comment by gustavom** [comment]
Ah, por isso que ele passa pelo if e else durante a requisição.

Eu estava achando que ele verificava apenas uma vez.

Valeu!!!!!

**Comment by fdaciuk** [comment]
isso =)

Vou fechar a issue aqui então, se tiver mais alguma dúvida com relação a esse assunto, só avisar que eu reabro, ok? =)
