### ISSUE TITLE
Challenge 29

### ISSUE THREAD

**Issue by JoaoPauloDev** [da2k/curso-javascript-ninja#1418]
Fala Fernando, beleza?

Estou tendo problemas de : Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Tentei criar um servidor node que respondesse com o arquivo company.json mas mesmo assim ele continuou dando o mesmo erro.

O que eu poderia fazer para contornar esse problema?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @JoaoPauloDev =)
Não é pra ter problemas de CORS nesse momento, porque os dois aquivos (index.html e company.json) estão no mesmo ambiente =)

O que você precisa fazer é, ao requisitar o `company.json`, usar uma URL relativa ao caminho que você está, sem passar o caminho completo. Provavelmente é por isso que você está tendo esse erro :)

**Comment by JoaoPauloDev** [comment]
Estou fazendo desta forma:

`  var ajax = new XMLHttpRequest();
  ajax.open('get', 'company.json');
  ajax.send();`

O que pode estar errado?

**Comment by fdaciuk** [comment]
O problema pode estar em como você está subindo o server. Como você está fazendo isso?

**Comment by JoaoPauloDev** [comment]
No momento não estou subindo nenhum server, só estou tentando fazer a requisição mesmo.

Quando eu estava usando o nodejs era assim:

var http = require('http');
var fs = require('fs');

function onRequest(req, res){
  res.writeHead(200, {'Content-Type': 'application/json'});
  fs.readFile('./company.json', null, function(error, data){
    if(error){
      res.writeHead(404);
      res.end('File not Found');
    }else{
      res.end(data);
    }
    res.end('Unkown');
  });
}

http.createServer(onRequest).listen(3000);

**Comment by fdaciuk** [comment]
Saquei! Tentar fazer a requisição usando `file:///` provavelmente vai dar problema mesmo =)
Mas não precisa se preocupar com server nesse momento. Use um servidor estático (em python, PHP, ou em node mesmo, com o `http-server` por exemplo) que já vai funcionar corretamente =)

**Comment by JoaoPauloDev** [comment]
Estou tentando com o nodejs, mas mesmo assim não funciona.

No meu challenge-29.js : 

  var ajax = new XMLHttpRequest();
  ajax.open('get', 'http://localhost:8080');
  ajax.send();
  ajax.addEventListener('readystatechange', function(){
    if(ajax.readyState === 4)
       console.log(ajax.responseText);
  });

No meu server.js: 

var http = require('http');
var fs = require('fs');

http.createServer(function (req, res) {
  fs.readFile('company.json', function(error, data){
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.write(data);
    res.end();
  });
}).listen(8080);

Todos os arquivos estão na mesma pasta (challenge-29.js, index.html, company.json, server.js).
Quando eu acesso 'localhost:8080' ele retorna na pagina o json, mas quando tento acessar pelo index.html ele me retorna o seguinte erro: 

XMLHttpRequest cannot load http://localhost:8080/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Esse erro é apontado para a linha onde eu dou um console.log no responseText do server.

**Comment by JoaoPauloDev** [comment]
Mesmo mudando o Header no node para 'apllication/json', o erro prevalece, porem na aba de debug network eu consigo ver o json.

**Comment by fdaciuk** [comment]
Opa @JoaoPauloDev! Você tentou usar o [`http-server`](https://www.npmjs.com/package/http-server)?

**Comment by fdaciuk** [comment]
@JoaoPauloDev conseguiu seguir com o `http-server`? 
Qualquer coisa avisa ae que nós vamos destrinchando até encontrar o problema, ok? =)

**Comment by JoaoPauloDev** [comment]
@fdaciuk Me desculpe, esqueci de fechar aqui e avisar, deu certo sim, eu fiz e funcionou com o http-server, ai eu já fui fazendo os outros exercícios.
Me desculpe, vou fechar a issue.
Muito obrigado e um abraço ;)

**Comment by fdaciuk** [comment]
Sem problemas meu caro =)

Que bom que deu certo o/

Se precisar de algo, só avisar :D
