### ISSUE TITLE
Challenge 14 - dúvida

### ISSUE THREAD

**Issue by virginiarcruz** [da2k/curso-javascript-ninja#1538]
Fernando, 
não entendi 2 itens do challenge-14.
No desafio

> Verifique se existem em algum índice de numberObjects um objeto ìgual a
>     { number: 2 }. Se houver, mostre no console:
>     - "Existe um objeto { number: 2 } em numberObjects!"
>     Senão, mostre a frase:
>     - "Não existe um objeto { number: 2 } em numberObjects :("
>     Consegue prever o resultado? Deixe uma mensagem no console tentando explicar
>     o que acontece ;)

    Eu tinha feito desta forma:

```
console.log( '\nExiste um { number: 2 } em numberObjects?' );
console.log( numberObjects.indexOf({number: 2} ) ? 
                 'Existe um objeto { number: 2 } em numberObjects!' : 
                 'Não existe um objeto { number: 2 } em numberObjects :(' );
```

Não entendi o porque de não estar correto, e na solução que você indicou na solução, no meu código cai sempre na opção de não existe.
 

@fdaciuk

**Comment by virginiarcruz** [comment]
só uma correção no código que eu tinha feito:
```
console.log( numberObjects.indexOf({number: 2} ) ? 
                 'Existe um objeto { number: 2 } em numberObjects!' : 
                 'Não existe um objeto { number: 2 } em numberObjects :(' );
```

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! O que acontece é o seguinte: Lembra que comentamos em algumas aulas atrás que `{}` é apenas um atalho para `new Object()` ?

Então, sempre que você cria um novo objeto usando `{}`, um novo espaço de memória é reservado para esse objeto. 

Quando você tenta usar o `indexOf` para buscar um valor em um array de objetos, cada objeto desse array ocupa um espaço na memória.

Ao testar dessa forma:

```js
numberObjects.indexOf({ number: 2 })
``` 

você estará criando um novo objeto `{ number: 2 }`, em outro espaço de memória, entende? =)

Agora, quando você atribui o objeto que já existe em `numberObjects` para uma variável, então você está dizendo que aquela variável vai apontar para o mesmo espaço de memória onde aquele objeto foi criado. Por exemplo:

```js
var numberObjects = [
  { number: 1 },
  { number: 2 }
]
```

Veja que esse array `numberObjects` contém 2 objetos. Como são objetos, cada um vai ocupar um espaço diferente na memória. Se você atribui exatamente esse valor à uma variável, a variável não **recebe** o valor, ela se torna um ponteiro, e **aponta** para aquele espaço de memória onde está aquele objeto:

```js
var objNumber2 = numberObjects[1]
```

Agora o objeto que está no índice `1` do array `numberObjects` foi passado como referência para a variável `objNumber2`. Ou seja: tanto a variável quanto o índice 1 do `numberObjects` apontam para o mesmo lugar, logo eles são o mesmo objeto =)

Agora, se você testar:

```
numberObjects.indexOf(objNumber2) > -1
```

Isso vai retornar `true`, pois o índice é maior que `-1`. Nesse caso, o índice é o `1`.

Ficou claro? =)

**Comment by virginiarcruz** [comment]
Mas quando faço 

`var objNumber2 = numberObjects[1]`

Eu não estaria atribuindo manualmente o índice que eu quero buscar no objeto?
eu sei que o indice 1 de numberObjects é` {number : 2}`

No exercício eu não teria que fazer esta busca dentro de numberObjects ?

**Comment by fdaciuk** [comment]
Isso mesmo! A ideia desse exercício é só pra ver se você conseguiu entender como funciona as referências de objetos na linguagem. O resultado é para dar sempre `false` mesmo =)

**Comment by virginiarcruz** [comment]
Entendi então.
Pensei que fosse pra fazer uma busca no Array entre os objetos dele e encontrar o number: 2

**Comment by fdaciuk** [comment]
Era pra ser meio "pegadinha" xD

Mas apenas pra mostrar que, ao menos usando dessa forma, você não consegue comparar um índice de um array que é um objeto, criando um novo objeto =)

Por isso pedi para deixar um `console.log` com o que você tinha entendido do resultado retornado =)

**Comment by fdaciuk** [comment]
Se tiver qualquer dúvida, só avisar =)
