### ISSUE TITLE
Commits - github

### ISSUE THREAD

**Issue by virginiarcruz** [da2k/curso-javascript-ninja#1539]
Estou fazendo minhas alterações no repositório que clonei no meu perfil do git. Separando as branchs etc.
https://github.com/virginiarcruz/curso-javascript-ninja

Preciso após fazer o git push ba branch que estou trabalhando fazer mais alguma coisa? Merge com a master? Ou para este repositório?
Estou no challenge-14 mas agora que percebi que posso estar com meu git desatualizado dos demais. =(

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! A ideia é que cada desafio resolvido fique somente na branch que você usou para resolver. Quando você volta para a master, os desafios devem ficar sem solução mesmo =)

Se você quiser centralizar todos os desafios resolvidos em uma branch só, você pode criar uma nova branch `desafios-resolvidos` ou algo assim, e fazer merge para essa branch.

Mas é importante deixar a `master` limpa para que você tenha a referência de todos os desafios sem a solução, se precisar voltar em algum, ok? =)

**Comment by virginiarcruz** [comment]
Ok =)

**Comment by fdaciuk** [comment]
Qualquer coisa só avisar =)

**Comment by virginiarcruz** [comment]
Fernando, só mais uma dúvida, faço os pull requests? 
Da branch atual do meu repositório para a branch equivalente do challenge ou para a master?

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! Chegou sua mensagem no email, mas vi que você apagou. Conseguiu resolver? =)

**Comment by virginiarcruz** [comment]
consegui resolver @fdaciuk .
Vi que na aula 01 você fala como fazer. =)

**Comment by fdaciuk** [comment]
Legal =)
Qualquer dúvida pode perguntar =)
