### ISSUE TITLE
Dúvida Challenge-10 - Colocando o new na conversão

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1547]
Olá

Por quê você não colocou o new na frente dos construtores para fazer a conversão ?

`var five = Number('5');` Ele passa e acusa true enquanto `var five = new Number('5');` acusa false.

Isso acontece por quê ao colocar o operado new ele cria um objeto ?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @lucianobarauna! Exatamente isso =)

Lembra que na aula 10 nós vimos sobre _Wrapper Objects_? É isso que usamos ali! Eles convertem o valor, ao invés de criar um novo objeto =)

**Comment by lucianobarauna** [comment]
Vlw !!!!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar! =)
