### ISSUE TITLE
Puxei coisas demais pro challenge 10

### ISSUE THREAD

**Issue by nono21** [da2k/curso-javascript-ninja#158]
Fernando, eu dei um git fetch upstream seguido de git merge upstream/master de dentro da branch master... e depois dei um git push origin master.
Só que acabou puxando o challenge 11 e 12 pra dentro da branch master e agora se eu criar uma branch nova pro challenge10 ele vai colocar o 11 e 12 também né?
Como resolvo isso?
Obrigado

**Comment by fdaciuk** [comment]
Opa! Quanto a isso não tem problema, esse é o comportamento esperado mesmo :)
O importante é: ao criar a branch para o desafio 10, resolver somente ele e fazer o commit, que na hora de fazer o pull request vai ficar tudo certo :D

**Comment by fdaciuk** [comment]
@nono21 Opa! Quanto a isso não tem problema, esse é o comportamento esperado mesmo :)
O importante é: ao criar a branch para o desafio 10, resolver somente ele e fazer o commit, que na hora de fazer o pull request vai ficar tudo certo :D
