### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by cristianopacheco** [da2k/curso-javascript-ninja#1592]
Olá Fernando, conforme sua sugestão, faço contato por aqui.

Cara, parabéns pelo treinamento!

Estou bem na metade e estou gostando muito, de longe é o melhor treinamento javascript que eu ja participei. 

Demorei muito para encontrar estes treinamentos! eu procrastinando, olhando o feed do Twitter, abri um tweet de pessoa que sigo que postou que tinha comprado o seu treinamento de React, abri o link e PIMBA! comprei os dois treinamentos de javascript e estou muito feliz.

Você tem planos para criar um treinamento de Node?

Eu trabalho como dev backend com php e java, gostaria de ver algo sobre node. Gosto muito de javascript, mas nunca encontrei um material  bacana.

Você pode me indicar algo sobre isso? pode ser em ingles, livro ou treinamento. 
por favor.

E por ultimo, você gostaria de participar do poadcast DEVNAESTRADA?
contando um pouco da sua história e divulgar seus treinamentos.

Com certeza tem vários como eu que não o conhecia e que acompanha o poadcast, tenho certeza que seria um cast muito legal.

Um abraço!

 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @cristianopacheco! Esse tipo de feedback me deixa bastante feliz, e me mantém motivado para continuar compartilhando conhecimento. Obrigado :heart: 

Pretendo sim fazer um curso de Node em breve, mas existem alguns legais que você pode tomar como base:
- O Rodrigo Branas dá uma base muito boa no seu [canal do Youtube](https://www.youtube.com/playlist?list=PLQCmSnNFVYnTFo60Bt972f8HA4Td7WKwq);
- No canal da webschool (do Suissa) tem uma parte de um curso dele também [falando sobre Node](https://www.youtube.com/playlist?list=PL77JVjKTJT2hP_lxL88oDo2rJvOskpGfJ);
- Tem um curso gringo - muito bom por sinal - [do WesBos sobre Node](https://learnnode.com/).

Fora esses materiais, a documentação ajuda bastante quando se tem alguma dúvida específica =)

Sobre o DEVNAESTRADA, com certeza eu ficaria muito feliz de participar! Não consigo acompanhar todos os episódios, mas sempre que possível eu escuto, acho bem interessante a proposta :D 

Obrigado mais uma vez pelas palavras, e no que precisar conte comigo =)

**Comment by cristianopacheco** [comment]
Opa legal @fdaciuk!

vou te indicar lá pro pessoal, com certeza eles ja devem te conhecer.

um grande abraço e muito sucesso!
