### ISSUE TITLE
Evitar o this

### ISSUE THREAD

**Issue by paulo70** [da2k/curso-javascript-ninja#1627]
Fernando, blz?
Da maneira que você colocou nas aulas pra usar as IIFE com o this é possível fazer apenas com o revealing pattern sem o uso do this? e posso manter essa técnica do revealing  dentro de um projeto?

Nas aulas:
```
(function() {
  var app = (function() {
    return {
      init: function() {
        this.handleTest();
      },

      handleTest: function() {
        console.log('hi');
      }
    }
  })()
  app.init();
})();
```
-------------------------------------------------
Revealing:

```
(function() {
  var app = (function() {
    function addGreeting() {
      return 'hi'
    }

    function addAwnser() {
      return 'hi';
    }

    function addQuestionName() {
      return 'whats is your name'
    }

    function addAwnserName() {
      return 'my name is jimmiy'
    }

    return {
      addGreeting,
      addAwnser,
      addQuestionName,
      addAwnserName
    };
  })();

  console.log(app.addGreeting());
  console.log(app.addAwnser());
  console.log(app.addQuestionName());
  console.log(app.addAwnserName());

})();)
```

@fdaciuk

**Comment by fdaciuk** [comment]
Pode, com certeza @paulo70 =)
O ideal é evitar o `this` mesmo :D 

A maneira mostrada na aula foi um dos vários patterns que podemos utilizar, mas evitando o `this`, você evita muitos problemas ;D 

Qualquer dúvida, só avisar!

**Comment by paulo70** [comment]
@fdaciuk Obrigado!

**Comment by fdaciuk** [comment]
Nada @paulo70! Qualquer dúvida, só avisar :D
