### ISSUE TITLE
For para Objetos

### ISSUE THREAD

**Issue by edpedroso** [da2k/curso-javascript-ninja#1647]
Olá Fernando,

Na aula "Revisão desafio semana #11 - Parte 1" aos 7:28min você diz que nós vamos usar o loop "for in" quando não sabemos a quantidade de propriedades de um objeto, mas se sabemos a quantidade de propriedades podemos usar o "for" normal.

Essa afirmação está correta? Pois testei aqui e não consigo chamar uma propriedade de um objeto usando objeto[0], apenas objeto[propriedade] ou objeto.propriedade.

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edpedroso! :D 

Realmente não ficou muito clara a explicação, desculpe =) 

O que eu estava tentando explicar era especificamente sobre o contador. Como nós não sabemos a quantidade de propriedades que aquele objeto pode ter, nós precisamos iniciar o contador fora do `for` e ir incrementando ele do lado de dentro.

Mas para percorrer objetos e pegar suas propriedades, é com o `for in` mesmo =)

**Comment by edpedroso** [comment]
Perfeito @fdaciuk , obrigado!

**Comment by fdaciuk** [comment]
Qualquer dúvida, avisa ae :D
