### ISSUE TITLE
Correção

### ISSUE THREAD

**Issue by Danilosas86** [da2k/curso-javascript-ninja#1648]
Oi Fernando. Como saberei se meu Challenge-01 foi corrigido ou não? 
Você coloca algum comentário se estiver tudo ok? 
Eu já fiz o 01, mas não sei se está certo ou se tem alguma coisa errada.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Danilosas86! A correção você pode acompanhar sempre na próxima aula! Infelizmente não tem como eu olhar os desafios um a um, mas eu dou sempre prioridade para dúvidas. Então, se você resolver algum desafio e, ao assistir a correção, ficar qualquer dúvida, você pode abrir uma issue que eu te ajudando, beleza? =)

Os desafios eu vou sempre marcar com a tag `REVIEW: Waiting` para contar na hora de gerar o certificado =)

**Comment by Danilosas86** [comment]
Beleza.. Valeu.

**Comment by fdaciuk** [comment]
E qualquer dúvida mesmo @Danilosas86, não hesite em perguntar, ok? O objetivo é que você possa entender de fato como o JavaScript funciona, e conseguir se virar sozinho com a linguagem :D
