### ISSUE TITLE
Grupo de Alunos

### ISSUE THREAD

**Issue by WilliamRoger** [da2k/curso-javascript-ninja#1652]
Bom dia Fernando!
gostaria de saber se existe um grupo com todos os alunos no Slack (para interação e ajuda) caso não tenha, se existe a possibilidade ser criado um grupo para esse fim?

@fdaciuk

**Comment by ldrbraga** [comment]
queroserninja.slack.com

**Comment by WilliamRoger** [comment]
Valeu mano!

**Comment by ldrbraga** [comment]
Valeu! :)

**Comment by WilliamRoger** [comment]
Mano acho que alguém precisa me mandar um convite se puder manda pra mim!
williamroger.frontend@gmail.com
Thanks!

**Comment by fdaciuk** [comment]
Oi @WilliamRoger! Acabei de te mandar o invite ;)

**Comment by wallacecosta** [comment]
Sei que a issue foi finalizada mas poderia mandar convite para wallacedacosta@gmail.com.
@fdaciuk

**Comment by fdaciuk** [comment]
Foi @wallacecosta :D

**Comment by Danilosas86** [comment]
manda para mim tb contato@danilosouza.com

**Comment by fdaciuk** [comment]
Foi @Danilosas86 =)
