### ISSUE TITLE
[Challenge-02] Git clone 

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1662]
Olá professor. 
Instalei o Git mas quando dou o enter na linha de comando que deveria clonar o repositório, é retornado o erro "SyntaxError: Unexpected identifier". 

Imagem do erro:

[![clone.jpg](https://s24.postimg.org/hhbyon3bp/clone.jpg)](https://postimg.org/image/vb0bdovwx/)

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @Roger-Melo! É que você está rodando o `git clone` dentro da interface do node :)
Você precisa rodar o comando direto no terminal. Saia da interface do node com `Ctrl + C` :)

**Comment by Roger-Melo** [comment]
Consegui! Obrigado, professor. 
Vou continuando aqui e qualquer coisa te aviso ;)

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
