### ISSUE TITLE
[Aula 1] Desafio

### ISSUE THREAD

**Issue by wdgraphael** [da2k/curso-javascript-ninja#1684]
Opa, não estou encontrando o "Compare & pull request" que mostrou no vídeo, mudou algo?

Abs.

@fdaciuk

**Comment by fdaciuk** [comment]
Olá @wdgraphael! Pode acontecer do GitHub não mostrar em alguns momentos, mas você pode enviar dessa forma:

1) Acesse o seu repositório, e troque pela branch que você quer enviar o pull request:

![selection_019](https://user-images.githubusercontent.com/487669/29363247-9a2740e6-8265-11e7-8d7d-e09b30ceed73.png)

2) Depois de selecionada a branch que você vai enviar, clique no botão "New pull request":

![selection_020](https://user-images.githubusercontent.com/487669/29363279-bb107610-8265-11e7-957c-9d81b429d3f8.png)

Depois disso, os passos são os mesmos :D 

Qualquer dúvida avisa ae! :D

**Comment by ribeiroevandro** [comment]
Eu também demorei, acho que o github mudou a interface... Após o commit ele não identifica como mostrado no vídeo...

**Comment by wdgraphael** [comment]
Consegui. Obrigado!

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
