### ISSUE TITLE
[AULA 01] DUVIDA SOBRE VARIAVEIS

### ISSUE THREAD

**Issue by ruanvalente** [da2k/curso-javascript-ninja#1686]
Olá, professor, minha duvida é a seguinte. Qual é a diferença entre se usar **var** ou invés de **let** e quando usar **const**  ?? Desde já agradeço muito, estou aprendendo bastante !!

@fdaciuk

**Comment by fdaciuk** [comment]
Olá @ruanvalente, tudo bem? =)
Desculpe, mas não consegui encontrar seu cadastro no curso pela Udemy. Poderia, por favor, me passar como está seu nome de usuário lá? :)

**Comment by ruanvalente** [comment]
Olá professor é **ruantux**, porém estou tentando entrar diz que meu usuário é inválido. Vou entrar em contato com a plataforma para vê se conseguem resolver o problema. Não é a primeira vez que isso acontece !

**Comment by fdaciuk** [comment]
Isso, veja certinho com eles lá, porque apesar dos desafios ficarem abertos, o suporte é especificamente pra quem está fazendo o curso, e eu só consigo validar essa informação por lá, ok? =)

**Comment by ruanvalente** [comment]
Ok, desde já agradeço a atenção !

**Comment by fdaciuk** [comment]
Sem problemas =)
Vou fechar a issue, mas assim que você conseguir confirmar com eles, comenta aqui que eu reabro e a gente segue, ok? =)
