### ISSUE TITLE
Feedback / Correções

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1689]
Professor, os alunos que se matricularam no curso recentemente também terão os exercícios corrigidos?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Infelizmente eu não consigo acompanhar as correções dos desafios um a um, mas eu deixei a correção sempre no início da próxima aula, detalhando todas as decisões tomadas para a solução.

Mas o suporte é a base do acompanhamento: qualquer dúvida que você tenha, inclusive de algum desafio que não ficou muito clara a solução, pode perguntar que eu vou dando prioridade pra isso, ok? 

O importante é que você não fique com nenhuma dúvida, e consiga entender de fato a linguagem, e eu estou aqui pra te ajudar no que precisar =)

**Comment by Roger-Melo** [comment]
Combinado professor. Obrigado =)

**Comment by fdaciuk** [comment]
Nada! Precisando de algo, só avisar! :D
