### ISSUE TITLE
[Aula01] Desafio

### ISSUE THREAD

**Issue by michaelsnogueira** [da2k/curso-javascript-ninja#1716]
Fernando, fiz o desafio, mas não sei se chegou até você, poderia confirmar por gentileza? Grato!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @michaelsnogueira! Chegou certinho sim! A solução você pode conferir sempre nos primeiros vídeos da próxima aula, ok?

E se tiver qualquer dúvida, seja do conteúdo passado, seja da solução do desafio, pode abrir issue que eu vou te ajudando. O importante é você entender todo o conteúdo passado :D

**Comment by juliafealves** [comment]
Olá @fdaciuk tudo bem!?
Gostaria de saber se é necessário ficar te enviando as soluções dos desafios das aulas, ou se só basta praticar e ir conferindo os vídeos.

Obrigada! Estou gostando muito do curso.

Valeu.

**Comment by ffabiorj** [comment]
@juliafealves O ideal é você manda para ele corrigir. A gente sempre erra algumas coisas.

**Comment by fdaciuk** [comment]
Boa @ffabiorj! É isso mesmo @juliafealves! Pode continuar enviando os desafios, pois pode surgir alguma dúvida enquanto você está resolvendo, ou até mesmo após ver a solução, no início da próxima aula =)

Se isso acontecer, me marque no PR, ou abra uma issue com a sua dúvida, que eu vou repassando contigo pra tirar a dúvida, ok? =)

**Comment by fdaciuk** [comment]
Bom, vou fechar a issue, mas se tiverem qualquer outra dúvida sobre isso, só avisar que a gente reabre, ok? :D
