### ISSUE TITLE
[AULA 26 - 155] Elemento __proto__

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1728]
Professor quando é mostrado o elemento no console ele aparece nas suas propriedades uma em específico chamado __proto__ . Seria ele o prototype do elemento ?
Escrever dessa forma __proto__ é alguma convenção ou isso é coisa do navegador ?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @lucianobarauna! O `prototype` só existe em funções :)
O `__proto__` é um objeto interno da linguagem, que basicamente expõe quem é o `Prototype` daquele objeto, mas você normalmente não precisa se preocupar com ele =)

Se quiser saber mais sobre, pode ver aqui: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

**Comment by lucianobarauna** [comment]
Entendi professor. Foi só uma curiosidade mesmo ;-)

**Comment by fdaciuk** [comment]
Show! Qualquer coisa avisa ae :D
