### ISSUE TITLE
Revisão dos Exercícos

### ISSUE THREAD

**Issue by michaelsnogueira** [da2k/curso-javascript-ninja#1747]
Bom dia Fernando, tudo bem? Estou começando a Seção 6, e até o momento eu não assisti nenhuma revisão de cada seção pois estava pensando em assistir as revisões conforme você for validando o exercício. Ex: Você deu o OK nos exercícios da Seção 1, após o OK, assisto a revisão da seção 1, ou você acha melhor eu ir assistindo a revisão logo após eu terminar o exercício? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @michaelsnogueira! Sim, pode assistir as revisões, pois além da solução do desafio, eu dou várias dicas nessas aulas :D 

Hoje não tem como eu validar os desafios um a um, então eu estou focando em dar suporte para as dúvidas.

Qualquer dúvida que você tenha, seja sobre a aula ou sobre a revisão do desafio, você pode perguntar que eu vou te acompanhando até que fique claro! O importante é que você não tenha dúvidas e aprenda a linguagem de verdade :D 

Qualquer coisa, só avisar!
