### ISSUE TITLE
Dúvida Aula 27 

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1751]
Professor só para ver se entendi direito.

Aqui no código nos entramos dentro do Object através do prototype e convertemos em uma string.
Com isso o javascript dentro dele nos retorna o valor a partir do elemento que instanciamos no call.
```
function is(element) {
  return Object.prototype.toString.call(element);
}

console.log( is( [1, 2, 3] ) );
console.log( is( function(){} ) );
console.log( is( 1 ) );
console.log( is( true ) );
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucianobarauna! Todo objeto em JS - e também construtores de tipos primitivos - têm um método `toString`, que retorna a representação daquele objeto no formato _string_.

No caso do objeto `Object`, o `toString` retorna sempre `[object Object]`, em outras palavras: um objeto do tipo `Object` (que é o construtor para um novo objeto).

Lembra que vimos que, ao criar um novo objeto literal, com `{}`, na verdade é o mesmo que fazer `new Object()`?

Esse `Object` é o construtor do objeto. Como `Array` é o construtor para um array; `String` para criar uma nova string, etc.

Nesse caso, quando você passa um `this` diferente para o `toString` de `Object`, ele vai retornar na string o construtor daquele objeto =)

Ficou claro?

**Comment by fdaciuk** [comment]
Essa informação você tem também na própria documentação do método `toString`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString#Using_toString()_to_detect_object_class

**Comment by lucianobarauna** [comment]
Então no caso isso é um comportamento do método `toString` em `Object` ?

**Comment by fdaciuk** [comment]
Isso! Você pode usar `toString` em qualquer tipo de dado pra ver a representação em string que ele retorna.

Exemplo:

```js
var number = 1
console.log(number.toString()) // "1"

var regex = /\d+/
console.log(regex.toString()) // "/\d+/"

var array = [1, 2, 3]
console.log(array.toString()) // "1,2,3"
```

E por aí vai :D

**Comment by lucianobarauna** [comment]
Sim to ligado.
Agora quando usamos ele no `Object` ele recebe um powerUp rs 
Maneiro e vlw professor. To perdendo a vergonha com dúvidas rs

**Comment by fdaciuk** [comment]
É isso mesmo! Como funções permitem injetar um `this`, e o `toString` do `Object` usa esse `this` pra exibir o construtor, então dá pra fazer essas magias com ele :D 

Se quiser ver um exemplo claro disso, só olhar [essa lib que eu criei](https://github.com/fdaciuk/is) com base nessa técnica =)

**Comment by lucianobarauna** [comment]
Que maneiro professor.
E que bom que entendi, confesso que estava com medo de não ter intendido.
Obrigado mais uma vez

**Comment by fdaciuk** [comment]
Show de bola!

Qualquer dúvida, abre issue ae :D
