### ISSUE TITLE
Repositório branchs

### ISSUE THREAD

**Issue by virginiarcruz** [da2k/curso-javascript-ninja#1754]
Fernando,

Estou tentando baixar novamente meu repositório com os desafios que ja resolvi pra dar continuidade ao curso.
No entanto, quando faço um clone ele só baixa a branch master, e não consigo fazer checkout para as demais branches.

Estou baixando o meu repositório que fiz o fork com o seu. 
Será que estou fazendo algo errado? 
=/

@fdaciuk

**Comment by virginiarcruz** [comment]
Por exemplo: 
Se faço: git checkout challenge-26, ele permanece na master.

Mas se faço: git checkout origin/challenge-26
Ele vai pra branch só que exibe "HEAD detached at origin/challenge-26"

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! Como cada desafio está em uma branch diferente, se você precisar de todas elas você pode fazer assim:

```sh
# Atualiza com seu repositório
$ git fetch origin

# Aqui você cria uma branch local, chamada `challenge-01`, com base nessa mesma branch do seu repositório (`origin/challenge-01`)
$ git checkout origin/challenge-01 -b challenge-01
```

**Comment by fdaciuk** [comment]
Se quiser trazer todas as branches de uma só vez, e estiver usando Linux, você pode rodar um shell script que vai fazer isso pra você. Dá uma olhada [nesse tópico](https://github.com/da2k/curso-javascript-ninja/issues/79#issuecomment-96659980) que tem a dica de como fazer ;)

**Comment by virginiarcruz** [comment]
Eu estou usando mac =/,
Vou tentar a primeira dica que você deu pra ver de dar certo.

**Comment by fdaciuk** [comment]
Entendi! Vai pela primeira que dá certo! Mas só faça para as branchs que vc precisar mesmo, não tem necessidade de baixar todas, a menos que vc realmente queira fazer isso =)

Porque as branches continuam no seu repositório no GitHub =)

**Comment by virginiarcruz** [comment]
Deu certo Fernando.

Utilizei o código que estava no artigo que você indicou:

`for remote in `git branch -r | grep -v master `; do git checkout --track $remote ; done`

Obrigada =)

**Comment by fdaciuk** [comment]
Show de bola :D 

Qualquer coisa, só avisar! =)
