### ISSUE TITLE
Dúvida this para aula 27 - Refatorando código

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1761]
Professor estou tentando refatorar o código da aula27 mais não estou conseguindo fazer por conta do this.

Sabe me dizer onde estou errando ?

  ```
  (function (win, doc) {
    'use strict';
    function createProtoObjAndvalue(stringNameObject, objectTarget) {
      this.teste = function teste() {
        return 'teste';
      }
    }
    console.log(createProtoObjAndvalue.teste());
  })(window, document)
  ```

Segue o print
![image](https://user-images.githubusercontent.com/1054454/29977401-967aa95a-8f13-11e7-9d99-d84cb80584e0.png)

@fdaciuk

**Comment by lucianobarauna** [comment]
Eu instanciei o new e acho que era por conta disso, certo professor ?

**Comment by fdaciuk** [comment]
Fala @lucianobarauna! É isso mesmo!

Quando você utiliza o `new` com uma função, ele te retorna sempre um novo objeto. Esse objeto recebe todas as propriedades e métodos que você pendurou no `this` dentro da função, ou no `.prototype` da referência da função.

Por isso que não funciona se você não usar o `new`.

Se quiser não usar o `new`, a função deveria retornar um objeto, e o método `teste` deve ser passado como método desse objeto. O efeito é basicamente o mesmo =)

**Comment by lucianobarauna** [comment]
Vlw professor !!!!
é isso mesmo

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida grita ae :D
