### ISSUE TITLE
[Aula 08] - Functional programming

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1763]
Olá, professor. 

Vc poderia recomendar alguns materiais de estudo sobre introdução à programação funcional?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Roger-Melo, tudo bem? =)

Acho que o melhor lugar pra se aprender programação funcional, é utilizar uma linguagem que funciona com esse paradigma.

JavaScript é multiparadigma: você pode aplicar OO, funcional, código imperativo. Então **começar** a estudar à partir de JS, sem ter uma base da linguagem, pode ficar um pouco complicado.

Recomendo você começar a estudar Haskell. É uma linguagem puramente funcional, e os conceitos funcionais que você aprender nessa linguagem - após aprender como as coisas funcionam no JS - podem ser facilmente aplicados em JS =)

Eu criei [um repositório onde eu faço alguns testes com Haskell](https://github.com/playgd/haskell-playground). Lá tem algumas instruções de como instalar as dependências necessárias e algumas fontes legais de estudo (em EN e PT-BR).

Dá uma olhada lá que pode ajudar =)

**Comment by Roger-Melo** [comment]
Entendi. Melhor terminar este curso primeiro, né?

Os códigos dos seus projetos geralmente são um mix de cada paradigma?

**Comment by fdaciuk** [comment]
Sim! No curso nós vemos vários paradigmas até conhecer toda a linguagem. Depois nós começamos a ver alguns padrões que podemos utilizar em nossos projetos =)

**Comment by Roger-Melo** [comment]
Valeu professor!

**Comment by fdaciuk** [comment]
Valeu! Qualquer coisa grita ae :D
