### ISSUE TITLE
Canal no Slack para os participantes do Curso 

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-javascript-ninja#177]
@fdaciuk Acha válido um canal no Slack para interação e networking entre os participantes do Curso?
Aqui no GitHub fica com as dúvidas através de issues e no slack ficaria o networking e conversas sobre JavaScript.

**Comment by alvesnatan** [comment]
+1

**Comment by fdaciuk** [comment]
Acho bem válido @theandersonn! Inclusive estava pensando exatamente isso na semana passada xD
Vou criar o canal e mando e-mail pra cada um depois :)

**Comment by theandersonn** [comment]
10, show @fdaciuk !

**Comment by fdaciuk** [comment]
Done! :dancer: :dancer:

**Comment by daviccardoso** [comment]
Olá, @fdaciuk!
Tudo bem?
Esse canal ainda existe? Caso sim, gostaria de fazer parte dele também. :^)

**Comment by fdaciuk** [comment]
Existe sim @daviccardoso! Me manda seu e-mail inbox (pode ser pela Udemy) que eu te convido para o grupo :D
