### ISSUE TITLE
Challenge 28 - CORS Gulp

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1777]
Professor eu coloquei o gulp para emular o servidor e parar o erro do CORS mais ele continua 

Segue o código do gulp:
```
var gulp = require('gulp');
var browserSync = require('browser-sync').create();


gulp.task('server', function(){
  browserSync.init({
    server: {
      baseDir:'./',
      middleware: function(req, res, next){
        res.setHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
        res.setHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT");
        next();
      }
    }
  })
  gulp.watch('./*').on('change', browserSync.reload);
})

```

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @lucianobarauna! Tenho que dar uma olhada na doc do `browserSync` pra ver qual o problema. Chegou a olhar lá se é assim mesmo que seta o cors? Qualquer coisa, tente usar o módulo `cors` ao invés de setar manualmente, pode funcionar =)

```js
var cors = require('cors') // instale com "npm install --save cors"
// ... restante do código
middleware: cors() // use o `cors` aqui em `middleware`
```

Testa ae e veja se funciona :)

**Comment by lucianobarauna** [comment]
não conhecia esse.
Eu só usei o gulp. Agora com o curso to começando a ficar menos tímido com js rs
Vou testar sim.

**Comment by fdaciuk** [comment]
Massa! Falei dele pq no curso eu mostro o uso do `cors` =)

**Comment by lucianobarauna** [comment]
É mais eu não quis avançar muito no para ver isso rs.
Nas revisões você explica mais eu só vejo elas depois que tento pelo menos fazer alguma coisa sozinh. Faço isso para tentar desenvolver o que aprendi e por conta disso ainda não vi sobre o cors e to demorando um pouco para terminar ;-)

**Comment by fdaciuk** [comment]
Entendi! Bom, quando realmente precisamos do cors, eu mostro antes do desafio, e deixo a parte do backend meio pronta para usar, então pode ser que você tenha pulado alguma parte =)

**Comment by lucianobarauna** [comment]
Nada eu que ainda não cheguei mesmo na parte de Rest e do cors rs
Eu ainda to no 28 mais como tem exemplo de request e o gulp não tá com cors aparece o erro

**Comment by fdaciuk** [comment]
Saquei =)
Conseguiu resolver?

**Comment by lucianobarauna** [comment]
Então a configuração ficou assim. Mais o erro persiste. 
Vou rever a video aula e ir montando conforme você vai mostrando lá, talvez eu tenha esquecido de algo.
```
var gulp = require('gulp');
var browserSync = require('browser-sync').create();
var cors = require('cors');

gulp.task('server', function(){
  browserSync.init({
    server: {
      baseDir:'./',
      middleware: cors()
    }
  })
  gulp.watch('./*').on('change', browserSync.reload);
})
```

O print do erro é esse.
![screen shot 2017-09-09 at 12 16 02 am](https://user-images.githubusercontent.com/1054454/30236649-9d98e13e-94f4-11e7-9298-7901917535a6.png)

**Comment by lucianobarauna** [comment]
Professor
O erro ainda está rolando e talvez por conta dele eu não estou conseguindo visualizar a mensagem de erro.
O código está aqui https://github.com/da2k/curso-javascript-ninja/pull/1783/commits/2d7dc055799f219df36ce9b0c34904f8d9df045f

**Comment by fdaciuk** [comment]
Fala @lucianobarauna! Cara, eu testei aqui seu código e está funcionando normalmente =)
Testa novamente ae pra ver se o problema persiste =)

**Comment by lucianobarauna** [comment]
@fdaciuk 
Mai esse log acima do XMLHttpRequest não é um erro então ?

**Comment by fdaciuk** [comment]
Sim, é um erro =)
Mas tem que ver com que versão do arquivo você rodou pra dar esse erro =)
Eu usei a versão que você passou ali em cima e funcionou: https://github.com/da2k/curso-javascript-ninja/tree/2d7dc055799f219df36ce9b0c34904f8d9df045f/challenge-28

**Comment by fdaciuk** [comment]
Rodei o `gulp server` e foi de boa =)

**Comment by lucianobarauna** [comment]
Que doido. Vou desistir :-( esse erro só rola quando eu digito um cep errado ou nenhum cep.

**Comment by fdaciuk** [comment]
Ah, entendi! Então está certo! Nesse caso você só precisa validar pra não deixar entrar um CEP em branco =)

**Comment by lucianobarauna** [comment]
A tá entendi. Vlw então professor aheuae

**Comment by fdaciuk** [comment]
haha! Beleza =)
Vou fechar a issue então, mas se der qualquer problema, avisa ae :D
