### ISSUE TITLE
Challenge 27 - Avaliação do código

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1778]
Professor o que achou da refatoração ?

[Link código refatorado](https://github.com/da2k/curso-javascript-ninja/pull/1765/files#diff-2e551756c356e98769c03813e2d5843a)

Vlw!!

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @lucianobarauna! Vou dar uma olhada e te dou um feedback :D
