### ISSUE TITLE
Challenge-12 - [for in]

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1780]
Olá professor. 

Já vi o vídeo da correção do exercício 12 várias vezes, já até decorei a resposta, mas não estou conseguindo entender como um trecho específico do código funciona: 

Esta é a questão completa: 

```js
/*
    Mostre no console todas as propriedades e valores de todos os livros,
    no formato abaixo:
        "[PROPRIEDADE]: [VALOR]"
    */
```

A resolução foi: 

```js
for(var i = 0; i < books.length; i++) {

        for(var prop in books[i]) {

            console.log(prop + ': ' + books[i][prop]);
        }
    }
```

O pedaço de código que está fritando minha mente é o: 
`books[i][prop]);`

Realmente não consegui compreender como ele funciona. 
Vc poderia explicar novamente?

P.S.: Não sei pq o markdown do GitHub não está reconhecendo o primeiro for.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Roger-Melo! Para blocos de código, você precisa usar 3 crases! Já ajustei =)

Vamos à dúvida: o que acontece é o seguinte:

O `for` normal itera por arrays através dos índices. No caso do exemplo, o `for` vai iterar o array em `books`, certo? Vai começar a iterar no índice zero até o índice final.

Como books é um array de objetos, com esse primeiro `for` você pega o objeto completo a cada iteração:

```js
var books = [
  { name: 'Livro 1', pages: 100 },
  { name: 'Livro 2', pages: 200 }
];

for (var i = 0; i < books.length; i++) {
  console.log(books[i]);
}
```

O resultado dessa iteração será:

|                 | valor de `i` | valor de `books[i]`|
|-------------- | :------------: | ------------------------|
1ª iteração: | 0              | `{ name: 'Livro 1', pages: 100 }`|
2ª iteração: | 1              | `{ name: 'Livro 2', pages: 200 }`|

Veja que o valor de `books[i]` é sempre um objeto inteiro. Para obter as **propriedades** de um objeto, nós precisamos usar o `for in`. Como dentro do `for` nós temos o objeto inteiro, só precisamos usar o `for in` ali dentro para obter as propriedades de cada objeto.

Pense em cada iteração de `books[i]` de forma isolada. A primeira iteração retorna o objeto `{ name: 'Livro 1', pages: 100 }`, que você pega com `books[i]`, certo? Então, para pegar a propriedade `name` desse objeto, você faria `books[i].name`, que te retornaria o nome do livro, e com `books[i].page`, você teria a quantidade de páginas.

Se você fosse pegar essas duas propriedades manualmente, você poderia fazer algo como:

```js
for (var i = 0; i < books.length; i++) {
  console.log('name: ' + books[i].name);
  console.log('pages: ' + books[i].pages);
}
```

E isso te retornaria o que você espera:

```
name: Livro 1
pages: 100
name: Livro 2
pages: 200
```

Só que você pode ter outras propriedades. Para pegar uma propriedade de um objeto de forma dinâmica, você utiliza a sintaxe de colchetes:

```js
var propName = 'name' // veja que `name` aqui é uma string
console.log(books[0][propName]) // "Livro 1"
```

Se você perceber, `propName` é uma variável que tem como valor a string `"name"`. Usando a sintaxe de ponto em um objeto, você precisa passar exatamente o **nome da propriedade**:

```js
var propName = 'name';
console.log(books[0].name) // "Livro 1"
console.log(books[0][propName]) // "Livro 1"
console.log(books[0].propName) // undefined, pois não existe uma propriedade com nome `propName`
```

Perceba a diferença nos exemplos acima: a propriedade `name` existe no objeto `books[0]`, por isso ele retorna o nome do livro. Mas `propName` não existe, ele é uma variável que contém o nome de uma propriedade válida como string. Para usar esse formato, precisamos usar a sintaxe de colchetes =)

Sabendo disso, dentro do primeiro `for`, você pode usar o `for in`, onde você cria uma variável qualquer que vai representar cada propriedade do objeto (no caso do exemplo, a variável é `prop`):

```js
for (var i = 0; i < books.length; i++) {
  for (var prop in books[i]) {
    console.log(prop + ': ' + books[i][prop])
  }
}
```

Ao executar o primeiro `for`, temos o objeto completo. Então, dentro desse `for` iteramos o objeto para pegar todas as propriedades dele, usando o `for in`. Olha como fica a iteração do `for in`:

**1ª iteração do primeiro `for`:**

O valor de `books[i]` é `{ name: 'Livro 1', pages: 100 }`.

| iterações do `for in` | valor de `prop` | valor de `books[i][prop]` |
| -------------------------- | -------------------- | ------------------------------ |
| 1ª iteração               | `"name"`           | `"Livro 1"`                     |
| 2ª iteração               | `"pages"`          | `100`                             |

---

**2ª iteração do primeiro `for`:**

O valor de `books[i]` é `{ name: 'Livro 2', pages: 200 }`.

| iterações do `for in` | valor de `prop` | valor de `books[i][prop]` |
| -------------------------- | -------------------- | ------------------------------ |
| 1ª iteração               | `"name"`           | `"Livro 2"`                     |
| 2ª iteração               | `"pages"`          | `200`                             |

Acho que é isso. Ficou claro? =)

**Comment by Roger-Melo** [comment]
Ótima explicação professor. 

Me esclareceu bastante sobre os usos dos for e for in. 

Muito obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Que bom que ficou claro! Qualquer dúvida, só avisar!
