### ISSUE TITLE
Problema ao clonar Repositorio

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#1782]
estou tentando clonar o repositorio e esta dando o seguinte erro'

`D:\Codigos\JavaScript-Ninja
λ git clone git@github.com:jhonesgoncalves/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Você chegou a configurar a chave SSH no seu sistema? Se não fez isso, só seguir [esses passos](https://help.github.com/articles/connecting-to-github-with-ssh/) antes de tentar clonar =)

Depois me diga se funcionou :D

**Comment by jhonesgoncal** [comment]
Eu tentei fazer isso ai , mais nao consegui

**Comment by fdaciuk** [comment]
Mas deu algum erro, qual foi o problema?

**Comment by jhonesgoncal** [comment]
![rtertret](https://user-images.githubusercontent.com/23177787/30111699-0f60e45e-92e5-11e7-8336-e3f032000361.PNG)

**Comment by jhonesgoncal** [comment]
o problema foi que não entendi os passos que eles descreve no post

**Comment by jhonesgoncal** [comment]
$ clip < ~/.ssh/id_rsa.pub

esse clip não funciona

**Comment by jhonesgoncal** [comment]
Key is invalid. It must begin with 'ssh-ed25519', 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'. Check that you're copying the public half of the key


da esse erro qdo coloco a sha que tem no codigo 
que aparece no meu terminal.
SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8



``C:\Users\SQZ69\Documents\Jhones\Codigos\JavaScriptNinja
λ git clone git@github.com:jhonesgoncalves/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting `(yes/no)?`

**Comment by jhonesgoncal** [comment]
`C:\Users\SQZ69\Documents\Jhones\Codigos\JavaScriptNinja
λ git clone git@github.com:jhonesgoncalves/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?`

**Comment by fdaciuk** [comment]
Acho que deu certo xD

Tente rodar "ssh -T git@github.com".

Se você receber uma mensagem de boas vindas com seu nome de usuário no GitHub, então deu certo =)

Só nessa última pergunta, responda "yes", que ele vai já te conectar com o GitHub, adicionando esse domínio como seguro no seu sistema =)

**Comment by jhonesgoncal** [comment]
`C:\Users\SQZ69\Documents\Jhones\Codigos\JavaScriptNinja
λ ssh -T git@github.com
Permission denied (publickey).`

apareceu isso

**Comment by fdaciuk** [comment]
Boa! Então não deu certo ainda =)

Dá uma olhada no seu diretório de usuário, na pasta `.ssh`, deve ter um arquivo `id_rsa.pub`. Abra esse arquivo com o bloco de notas mesmo e adicione nas configurações de SSH da sua conta do GitHub.

Depois tente rodar novamente o `ssh -T git@github.com` =)

**Comment by jhonesgoncal** [comment]
procurei esse arquivo e não acho. na pasta ssh nao tem ele. coloquei pra visualizar os ocultos e mesmo assim nao aparece

**Comment by fdaciuk** [comment]
Então provavelmente você não chegou a criar ele. Para criar, só seguir [esses passos](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-windows).

Depois, para verificar se o arquivo foi criado, só rodar [esses comados](https://help.github.com/articles/checking-for-existing-ssh-keys/#platform-windows) no terminal.

Como você está no windows, baixe o [Git Bash](https://git-for-windows.github.io/) para rodar os comandos =)

**Comment by jhonesgoncal** [comment]
eu tenho o gitbash mais é que gosto de usar o cmder

**Comment by fdaciuk** [comment]
Sem problemas, contanto que dê pra rodar esses comandos, tá tudo certo :D

**Comment by jhonesgoncal** [comment]
agora deu certo obrigado

**Comment by jhonesgoncal** [comment]
sabe se tem como salvar essa conversa para consultas futuras?

**Comment by fdaciuk** [comment]
Show @jhonesgoncal! Sim, a issue não morre =)
Ela fica fechada, mas você pode acessar o repositório, ir em "Issues" > "Closed" e ver toda essa conversa =)

Qualquer dúvida, só avisar!

**Comment by le-sousa** [comment]
Valeu pessoal! Pleníssimo 2021 e vocês me salvaram! XD

**Comment by fdaciuk** [comment]
Que bom que ajudou @LettySousa 💃🏾 💃🏾 🎉
