### ISSUE TITLE
Duvida Sobre SSH

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#1788]
Boa tarde Professor,

eu queria saber o que e o SSH , por que sempre faco commit com http porem não sei qual a diferença de fazer o clone com a ssh e tals.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @jhonesgoncal! Em resumo, SSH é uma forma segura de você autenticar e conversar entre duas máquinas =)
Como você disponibilizou sua chave pública para o GitHub, quando você tenta fazer uma conexão, dando pull ou push, que vai fazer você receber informações do GitHub para sua máquina, ou enviar da sua máquina para os servidores do GitHub, e a conexão é SSH, o sistema operacional faz a "ponte" entre a conexão, pegando a chave pública que o GitHub vai enviar, que você disse que é sua, e comparando com sua chave privada, para garantir que é você mesmo que está fazendo o pull / push =)

**Comment by fdaciuk** [comment]
Se quiser saber mais sobre SSH, dá uma [lida aqui](https://pt.wikipedia.org/wiki/Secure_Shell). Tem alguns outros links de referência no post =)

**Comment by jhonesgoncal** [comment]
mais qual a diferença com quando faco isso com http?

**Comment by fdaciuk** [comment]
HTTPs é um outro tipo de protocolo para comunicação entre máquinas na internet, e é mais simples que o SSH, já que você não precisa de nenhuma configuração. Você vai precisar apenas digitar seu usuário e senha toda vez que fizer um pull / push, a menos que você [configure para não precisar digitar sempre](https://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-password-typing-when-using-https-on-github/18362082#18362082).

O status é apenas para saber que o pull request é válido, e vai contar na hora de gerar o certificado. É apenas para controle meu =)

**Comment by jhonesgoncal** [comment]
mais como sei se o exercicio esta certo ou errado?

**Comment by jhonesgoncal** [comment]
uma outra duvida foi que eu fiz como vc orientou certinho na hora de clonar porem nao veio a branch challege 01 somente a master. porem no meu repositorio do github esta la.

**Comment by fdaciuk** [comment]
> mais como sei se o exercicio esta certo ou errado?

Sempre no início das aulas, nós fazemos a correção do desafio da aula anterior, então você pode acompanhar por ali =)

E se tiver alguma dúvida com relação a aula ou à solução do desafio, pode abrir issue aqui que vamos destrinchando a dúvida até que fique claro =)

---

> uma outra duvida foi que eu fiz como vc orientou certinho na hora de clonar porem nao veio a branch challege 01 somente a master. porem no meu repositorio do github esta la.

A menos que você precise mexer em alguma coisa nessa branch, não é necessário puxar ela para o seu local. Mas se ainda assim você quiser fazer, você só precisa rodar o seguinte comando no terminal:

```console
git checkout -b origin/challenge-01 challenge-01
```

Esse comando vai criar a branch do `challenge-01` na sua máquina (local) e já vai fazer o checkout pra ela, baseado na branch `challenge-01` do seu `origin` (seu repositório), ou seja, rodando esse comando você vai estar dentro da branch `challenge-01`. Para voltar para a master, só fazer:

```console
git checkout master
```

=)

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Vou fechar a issue, mas se você tiver qualquer problema relacionado, a gente reabre, ok? :)
