### ISSUE TITLE
challenge-21 dúvida sobre o increment do contador

### ISSUE THREAD

**Issue by fabioaguirre** [da2k/curso-javascript-ninja#1800]
Oi Fernando, tudo bom?

No desafio 21, na hora de incrementar o contador do timer, você explicou que por ser uma string era necessário convertê-la e passou na revisão o modo: $counter.value = +$counter.value + 1;

Quando fiz o desafio, não me atentei a esse detalhe, mas usei uma forma que funcionou logo na primeira vez:
$counter.value ++;

Esta foram que utilizei, apesar de ter dado certo, está errada? Tive sorte em usá-la, ou ela também faz essa conversão e permite que a string seja tratada como número e faça a soma corretamente?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fabioaguirre! Não está errado não =)

Na verdade, o problema de usar o `++` é a questão do efeito colateral que ele causa. É sempre bom manter o código o mais previsível possível, e efeitos colaterais muitas vezes impedem de vermos erros bem embaixo do nosso nariz, por isso eu converti manualmente o valor da string em número e depois somei `1`.

O que o operador `++` faz é, além de modificar o valor da variável, incrementando `1` a ela, sem precisar utilizar o operador de atribuição `=`, se o valor não for um número, ele transforma o tipo para número e só então tenta incrementar. Se o valor transformado não for um número, ele vai retornar `NaN` =)

Então assim: funciona das duas formas, mas evitar efeitos colaterais - ou _side effects_, como você pode encontrar em artigos em inglês - é sempre importante para manter o código o mais previsível possível =)

**Comment by fabioaguirre** [comment]
Oi Fernando, obrigado pela explicação!

Agora ficou totalmente claro pra mim a diferença entre os dois e a vantagem de alterar manualmente!

Muito obrigado!

**Comment by fdaciuk** [comment]
Legal @fabioaguirre! Qualquer dúvida, só avisar :D
