### ISSUE TITLE
challenge-14 - mesmo código, resultados diferentes

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1803]
Olá, professor. Tudo bem?

Eu estava respondendo alguns exercícios e notei que, ao testar o mesmo código no node e no console do chrome os resultados estavam diferentes:

Resultado do código no developer tools: 

[![developer-tools.jpg](https://s26.postimg.org/zea4f3f6x/developer-tools.jpg)](https://postimg.org/image/rljgn497p/)

Resultado do mesmo código no prompt, com o node:

[![node-screenshot.jpg](https://s26.postimg.org/fky0me1t5/node-screenshot.jpg)](https://postimg.org/image/48lf4lt45/)

Vc sabe o porque disso acontecer? Posso ter esse tipo problema ao colocar um projeto no ar?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Roger-Melo! Esse problema, na verdade, é porque no browser já existe uma variável global chamada `name`, que representa o nome da janela atual. Essa variável **sempre** vai ser uma string, por isso você pode ter problema se tentar utilizar uma variável `name` no escopo global, como qualquer outro tipo de valor =)

No caso, ainda que você atribua um array para essa variável, por baixo dos panos, ao avaliar o valor dessa variável, será utilizado o `toString`, fazendo com que o seu array se transforme em uma string e não tenha o método `reduce` :) 

Normalmente códigos de produção, dificilmente você vai utilizar escopo global, sempre vai utilizar uma IIFE para manter tudo local, e só vai exportar para global aquilo que precisar ser compartilhado. Se não chegou nessa parte do curso que fala sobre IIFE ainda, não se preocupe que você ainda vai ver sobre o assunto :D 

Se quiser saber mais sobre isso, [veja aqui](https://developer.mozilla.org/en-US/docs/Web/API/Window/name) =)

Qualquer dúvida, só avisar!

**Comment by Roger-Melo** [comment]
Esclarecido, professor. 
Muito obrigado.

**Comment by fdaciuk** [comment]
Legal :D 
Qualquer coisa avisa ae :D
