### ISSUE TITLE
[challenge-14] - objetos referenciados

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1806]
Olá professor.

No caso do código abaixo, o retorno irá ser true porque o JavaScript, ao invés de referenciar o objeto que eu queria comparar, ele criou um novo objeto (dentro do indexOf) e booleanamente falando, um object tem valor true. É isso?

```

    /*
    Verifique se existe em algum índice de numberObjects um objeto ìgual a
    { number: 2 }. Se houver, mostre no console:
    - "Existe um objeto { number: 2 } em numberObjects!"
    Senão, mostre a frase:
    - "Não existe um objeto { number: 2 } em numberObjects :("
    Consegue prever o resultado? Deixe uma mensagem no console tentando explicar
    o que acontece ;)
    */
    console.log( '\nExiste um { number: 2 } em numberObjects?' );

    console.log(

        numberObjects.indexOf({number: 2} > -1)
        ? "Existe um objeto { number: 2 } em numberObjects!"
        : "Não existe um objeto { number: 2 } em numberObjects :("
    );

```

Para detalhar mais a pergunta, essa foi a resposta do vídeo do exercício, que retornava false:

[![response.jpg](https://s26.postimg.org/xuy8q4ze1/response.jpg)](https://postimg.org/image/cy20lh1d1/)

@fdaciuk

**Comment by fdaciuk** [comment]
> No caso do código abaixo, o retorno irá ser true porque o JavaScript, ao invés de referenciar o objeto que eu queria comparar, ele criou um novo objeto (dentro do indexOf)

Isso mesmo!

> e booleanamente falando, um object tem valor true. É isso?

Essa afirmação também está correta, mas não o motivo é o da primeira frase que você falou: ao tentar comparar duas referências diferentes, o retorno não tem como ser `true`, pois cada um é um objeto diferente =)

Na solução, você passa a referência do objeto que você está procurando para a variável `obj`, então a comparação é sempre entre os mesmos objetos. Nesse caso, o `indexOf` retorna um valor maior que `-1`.

E dentro do `if`, a verificação que está sendo feita já retorna um booleano (`true` ou `false`).

Então o retorno `true` não é porque objeto é _truthy_, mas sim porque você usa o operador de comparação **maior que** :)

**Comment by Roger-Melo** [comment]
Fechou professor. Valeu!
