### ISSUE TITLE
[aula-15] - syntax highlight do atom

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1813]
Olá professor. 

A partir do momento em que escrevi ```var constructor = new MyConstructor();``` a syntax highlight do arquivo mudou. Note a diferença entre os console.log()

![image](https://user-images.githubusercontent.com/29297788/30289657-43d49d26-9703-11e7-9984-e1a3cd2d76ee.png)

Cliquei na msg amarela no canto inferior direito e essa aba foi aberta: 

![image](https://user-images.githubusercontent.com/29297788/30289749-850805bc-9703-11e7-933d-12f3b11f4187.png)

Vc sabe o que pode ser isso?

@fdaciuk

**Comment by fdaciuk** [comment]
O highlight provavelmente é porque você precisa dar um espaço entre a declaração da variável e o console.log.

Já os warnings provavelmente são de algum plugin do atom =)

**Comment by Roger-Melo** [comment]
Olá professor. Eu tentei o que vc sugeriu mas não surtiu efeito. 

Mas, quando mudei o nome da var, o highlight voltou. 
De acordo com [essa](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Classes) página do mdn, me parece object é uma keyword do js. 

De qualquer forma, o highlight voltou ao normal após a alteração: 

![image](https://user-images.githubusercontent.com/29297788/30305639-5327cea0-974a-11e7-81c0-201a1308218f.png)

**Comment by fdaciuk** [comment]
Então, o `constructor` é sim utilizado dentro de uma `class` - novo no ES6 - mas não há problema em nomear variáveis com esse nome, ele não é uma palavra chave reservada.

Mas o seu _syntax highlight_ pode não ter esse tipo de validação, de checar se o `constructor` está dentro de uma classe, para colorir de uma forma, ou se está sendo usado como uma variável, para colorir de outra forma.

Mas isso é apenas configuração de _highlight_, nada que possa dar problema de verdade =)

**Comment by Roger-Melo** [comment]
Valeu professor!
