### ISSUE TITLE
[challenge-15] - objetos this em métodos

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1819]
Olá professor. Tudo bem?

Estou conferindo a resposta do challenge 15 e vi que vc usou o this.nomeDaPropriedade dentro dos  métodos do obj (img abaixo).

[![challenge-15-professor-answer.jpg](https://s26.postimg.org/3nrub2ryx/challenge-15-professor-answer.jpg)](https://postimg.org/image/pmy8ya8t1/)

Fiz o teste com a resposta abaixo e o retorno foi o mesmo. Gostaria de saber quais são as diferenças e se isso pode gerar algum problema:
[![challenge-15.jpg](https://s26.postimg.org/99e9f4snt/challenge-15.jpg)](https://postimg.org/image/3l7yo8ob9/)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Nesse caso específico não tem diferença pq o valor das variáveis `name` e `lastName` que foram passadas para o construtor não serão alteradas.

Se se você tivesse algum método, por exemplo `editName`, o que você mudaria seria a propriedade do objeto instanciado. Nesse caso, ao usar o `getFullName` após fazer a edição do nome com `editName`, o nome só retornaria atualizado se você usasse o `this.name`, e não o `name` que foi passado como parâmetro =)

Mais pra frente nós vamos ver também sobre o `prototype`, acredito que esse uso vai ficar um pouco mais claro =)

**Comment by Roger-Melo** [comment]
Entendi professor. Muito obrigado
