### ISSUE TITLE
off topic: aprendizado

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1821]
Professor, por curiosidade, qual maneira vc considera a ideal para assistir e praticar o curso?

Exemplo, eu anoto nos comentários dos vídeos todas as observações que acho relevante. Isso acrescenta uma interatividade gigantesca, pq parece que quando EU escrevo, absorvo um pouco melhor o conteúdo. Além de poder revisar os conceitos que foram documentados: 

![image](https://user-images.githubusercontent.com/29297788/30357649-27ca5102-9816-11e7-8752-18d310f6790f.png)

Além de fazer os desafios, também já executo os códigos no momento em que são passados nos vídeos. Vc recomenda isso? Sei que é algo bem pessoal mas, vc tem alguma dica, sugestão ou método de práticas para uma melhor absorção do conteúdo das aulas?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Quando eu estou estudando algo, eu faço exatamente isso: escrevo por mim mesmo, pois o cérebro grava melhor a informação quando você executa.

E procuro fazer exercícios também para gravar melhor o aprendizado. Mas um ponto bastante importante nesse momento: tente solucionar o exercício de outras formas. Sempre tem mais de uma forma de se fazer a mesma coisa. Ainda que não pareça "muito certo", mas você já começa a ver outros caminhos que você poderá ter para resolver o mesmo problema =)

**Comment by Roger-Melo** [comment]
Saquei. Muito obrigado professor.

**Comment by fdaciuk** [comment]
haha! Então, coloca os teus estudos aqui no GitHub. Cria um repo pra estudos. Escrevendo em markdown, você consegue usar até _code highlight_ =)

**Comment by Roger-Melo** [comment]
Hum... vou pesquisar sobre MarkDown e Repos de estudos professor. Valeu!

**Comment by fdaciuk** [comment]
Qualquer coisa, tenho alguns links que podem ajudar. Pode começar por esse:
https://blog.da2k.com.br/2015/02/08/aprenda-markdown/
 =)

**Comment by Roger-Melo** [comment]
Esse cara é bom, hein? 
haha. Valeu, professor!

**Comment by fdaciuk** [comment]
haha! Espero que ajude nos estudos :)

**Comment by Roger-Melo** [comment]
Em breve, se o ruimdows deixar, devo começar um curso de jekyll em que vou utilizar markdown. Seu post me ajudará bastante =)

**Comment by Roger-Melo** [comment]
Olá professor! 

Eu segui seu conselho e iniciei um repo de estudos do curso em markdown, olha só: 
https://github.com/Roger-Melo/estudos-curso-javascript-ninja

Já senti uma diferença brutal no workflow e na organização da 
documentação. 

Só tenho a lhe agradecer pela dica, fez uma diferença enorme para mim!

P.s.: Você se incomoda por esse repositório ser público?  Se sim, eu 
assino o plano de repositórios privados do GitHub, sem problemas.

**Comment by fdaciuk** [comment]
Opa, legal @Roger-Melo!

Não tem problema deixar público não, fica tranquilo :)
