### ISSUE TITLE
Aula 29 - Prototype não funcioana

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1827]
Professor

Eu tentei entender sozinho mais não foi. Queria tentar entender o porquê de não consiguir utilizar esse método quando declaro ele com o `prototype`

Tanto que nesse código eu retirei ele.

[Link do código](https://github.com/da2k/curso-javascript-ninja/pull/1826/files#diff-90dacce3e3ad342662cc762cb154212aR58)

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @lucianobarauna! O `prototype` é uma propriedade especial para funções. Nessa propriedade, você pode pendurar métodos que serão reutilizáveis sempre que você criar um novo objeto usando o seu construtor.

O `prototype` faz com que, cada objeto criado reutilize as mesmas funções - pois funções são objetos, e como objetos, também são passadas por referência - , ao invés de criar funções novas para cada objeto criado, o que economiza bastante memória. Por esse motivo, usar `prototype` para criar métodos de construtores é bastante rápido.

No caso, se você pendurar qualquer coisa no `prototype`, esse método só estará disponível se você construir um novo objeto usando `new`, na função que você criou, e que usa o `prototype`.

No seu exemplo, você está fazendo o seguinte:

```js
DOM.isArray = function () {}
```

Essa função é o que chamamos de _método estático_. Ela vai estar disponível para uso, independente de construir um novo objeto. Você pode usar ela sem precisar do `new DOM()`.

Agora olhe esse outro exemplo:

```js
DOM.prototype.isArray = function () {}
```

Se você pendurar no `prototype`, você só consegue de duas formas:

1) construindo um novo objeto:

```js
var dom = new DOM();
dom.isArray();
```

2) usando o método direto do `prototype`:

```js
DOM.prototype.isArray();
```

Ficou claro?

---

Agora talvez possa surgir uma nova questão: quando usar o `prototype`, e quando usar um método estático?

Se essa foi a sua pergunta, a resposta é simples: se no seu método você só precisa fazer algum tipo de computação que não dependa exclusivamente do objeto criado, então você usa um método estático.

Agora, se o seu método precisa funcionar de forma diferente para cada novo objeto criado, pois, por exemplo, você usa o `this` dentro desse método, que vai fazer referência ao novo objeto criado, então você precisa do `prototype`, para garantir que o `this` é sempre a referência para o objeto certo que você está usando =)

Deu pra entender? =)

**Comment by lucianobarauna** [comment]
Opa!
Sim surgiu mesmo mais entendi mais ou menos a explicação rs.
Teria algum exemplo para entender melhor por favor

**Comment by fdaciuk** [comment]
Legal =)
Bom, além do que foi mostrado no curso, se quiser uma explicação mais detalhada, o livro _You don't know JS_ tem um conteúdo bem específico sobre prototype, en inglês: 
https://github.com/getify/You-Dont-Know-JS/tree/master/this%20%26%20object%20prototypes

**Comment by lucianobarauna** [comment]
@fdaciuk 
Vou fechar aqui a issue para não ficar aberta mais a dúvida foi respondida e muito obrigado mais uma vez

**Comment by fdaciuk** [comment]
Show @lucianobarauna! Qualquer coisa avisa ae :D
