### ISSUE TITLE
Erro com repositorio

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#1843]
Bom dia,
estava dando push normal porem hj eu tentei a apareceu esse erro

D:\Codigos\JavaScript-Ninja\curso-javascript-ninja (challenge-06)
λ git push challenge-06
fatal: 'challenge-06' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Faltou o `origin`:

```
git push origin challenge-06
```

Veja se é isso e me avise :D

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
