### ISSUE TITLE
Dúvida challenge 6

### ISSUE THREAD

**Issue by renanol** [da2k/curso-javascript-ninja#1858]
Olá, então, no penútimo exercício desse desafio você fala para criar 5 cores para o seu equivalente hexadecimal, e no ultimo pede para mostrar o hexadecimal de 8 cores diferentes, sendo que criei apenas 5. É isso mesmo?

Abraços! 

@fdaciuk

**Comment by fdaciuk** [comment]
É isso mesmo @renanol! A ideia é verificar se será exibida a mensagem de erro para as cores que não foram mapeadas, por isso o "Tente mostrar" :D 

É só uma forma manual de checar se sua implementação funciona, inclusive mostrando o erro correto quando o parâmetro passado não foi mapeado na função :)

**Comment by renanol** [comment]
@fdaciuk É verdade, não vi:

>  Se a cor passada por parâmetro não estiver entre as selecionadas, mostre
>   a frase: "Não temos o equivalente hexadecimal para [COR]."

Obrigado! =)

**Comment by fdaciuk** [comment]
Isso mesmo @renanol =)
Qualquer dúvida, só aivsar :D
