### ISSUE TITLE
Challenge-19 - Travei

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1863]
Olá, professor. 

Eu estou travado há 2 dias em um exercício, vc pode me ajudar? 

```js
/*
    Vamos criar um método que vai testar se uma classe CSS existe em uma
    marcação HTML.
    - Primeiro, crie uma função chamada `hasClass`;
    - Essa função receberá dois parâmetros: o primeiro chamado `markup`, que
    será a marcação HTML testada, e o segundo `cssClass`, que será a classe que
    iremos testar;
    - A função deve retornar `true` se a classe existir na marcação e `false`
    caso contrário;
    - A marcação usada para testar deve ser a que está na variável `markup`
    abaixo;
    - Não altere a marcação na variável markup!
    - Faça o teste, mostrando no console o resultado para as seguintes classes:
    - "container", "text", "date", "excerpt" e "main".
    - O console deve exibir a frase:
    "[RESULTADO] para a classe [CLASSE]"
    - Ex. de resposta:
    "true para a classe container"
    - Teste uma classe por vez (um console.log por classe).
    - Lembrando que a função deve funcionar para qualquer marcação HTML e para
    qualquer classe que for testada. Os dados passados no exercício são somente
    para exemplificar.
    */
    var markup = '<main>\n  <div class="container">\n    <span class="text date"></span>\n    <p class=\'excerpt\'></p>\n  </div>\n</main>';
    console.log( '\nQuais classes CSS existem na marcação abaixo?\n\n', markup, '\n' );

    var regex = /class=["'](\w+)\s?(\w+)?["']/g;

    function hasClass(markup, cssClass) {

        return regex.test(markup);
    }

    console.log(hasClass(markup, 'container'));
    console.log(hasClass(markup, 'banana'));
```

Não estou conseguindo entender, por exemplo, pq o 2º console.log está retornando true, sendo que a classe não existe na string.

Não olhei o vídeo de correção do challenge pq quero uma dica ao invés da resposta mastigada.

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae @Roger-Melo! Vamos lá: 
Você está passando a marcação e a classe para a função `hasClass`, mas onde você está checando se a classe passada está contida na marcação, dentro da função `hasClass`?

Essa é a dica ;)

**Comment by Roger-Melo** [comment]
Não consegui professor, infelizmente. 
Acho que vou ter que olhar o vídeo da resposta mesmo =/

Vou deixar abaixo 2 tentativas que fiz.

Retorna true para tudo: 
```js
function hasClass(markup, cssClass) {

        return markup.match(cssClass) ? true : false;
    }

    var classes = ["container", "text", "date", "excerpt", "main"];

    classes.forEach(function(item) {

        console.log(hasClass(markup, item));
    });
```

Retorna false para o 'excerpt' e true para 'main'
```js
function hasClass(markup, cssClass) {

        if (markup.match(cssClass) === null) {

            return regex.test(markup) + " para a classe " + cssClass;
        }

        return regex.test(markup) + " para a classe " + markup.match(cssClass);
    }

    var classes = ["container", "text", "date", "excerpt", "main"];

    classes.forEach(function(item) {

        console.log(hasClass(markup, item));
    });
```

**Comment by Roger-Melo** [comment]
Não consegui professor, infelizmente. 
Acho que vou ter que olhar o vídeo da resposta mesmo =/

Vou deixar abaixo 2 tentativas que fiz.

Retorna false para tudo: 
```js

var regex = /class=["'](\w+)\s?(\w+)?["']/g;

function hasClass(markup, cssClass) {

        return markup.match(cssClass) ? true : false;
    }

    var classes = ["container", "text", "date", "excerpt", "main"];

    classes.forEach(function(item) {

        console.log(hasClass(markup, regex.test(item)));
    });
```

Retorna false para o 'excerpt' e true para 'main'
```js

var regex = /class=["'](\w+)\s?(\w+)?["']/g;

function hasClass(markup, cssClass) {

        if (markup.match(cssClass) === null) {

            return regex.test(markup) + " para a classe " + cssClass;
        }

        return regex.test(markup) + " para a classe " + markup.match(cssClass);
    }

    var classes = ["container", "text", "date", "excerpt", "main"];

    classes.forEach(function(item) {

        console.log(hasClass(markup, item));
    });
```
Essa é a regex: 
![image](https://user-images.githubusercontent.com/29297788/30787477-dce5d7bc-a15f-11e7-964b-4188f44aa800.png)

**Comment by fdaciuk** [comment]
O problema é que você está testando só a classe de forma isolada dentro da marcação. Para saber se a palavra é uma classe, você precisa adicionar essa classe na regex para fazer a verificação.

Uma outra dica que eu posso dar é: você precisa criar a regex dentro da função `hasClass`, e inserir a classe dentro da regex =)

Qualquer coisa, dá uma olhada na solução e veja se fica claro. Depois tente refazer sozinho, para ver se você realmente entendeu, ou tente trocar a marcação, ou algo assim.

Mudando o exercício, você testa outras possibilidades e consegue gravar mais fácil a ideia de como resolver esse problema :D 

Se tiver qualquer dúvida, comenta aqui :D

**Comment by Roger-Melo** [comment]
Então, professor. Acho que talvez eu esteja no caminho certo... olha só: 

```js
function hasClass(markup, cssClass) {

        var regex = new RegExp('class=[\"\']' + (cssClass), 'g');

        return regex.test(markup);
    }

    var classes = ["container", "text", "date", "excerpt", "main"];

    classes.forEach(function(classe) {

        console.log(hasClass(markup, classe) + " para a classe " + classe);
    });
```

Fui nas suas dicas, não olhei a resposta, claro.

Só tem um probleminha agora, fazer a regex que case com as classes em qualquer markup. 
Estamos aí, tentando, né? 
Aquela situação em que vc sai do espeto e cai na brasa. Rs

**Comment by fdaciuk** [comment]
> Aquela situação em que vc sai do espeto e cai na brasa. Rs
:joy: :joy: 

O caminho é esse mesmo! Agora é só seguir xD
