### ISSUE TITLE
Dúvida sobre fragment

### ISSUE THREAD

**Issue by edpedroso** [da2k/curso-javascript-ninja#1866]
Olá Fernando,

Entendi a utilidade do fragment, mas qual a diferença de criar o fragment ao invés de simplesmente criar uma variável genérica, montar os itens que serão adicionados no DOM dentro desta variável e depois adicionar a variável no DOM?

Na minha visão inexperiente parece a mesma coisa.

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @edpedroso! Na verdade seria basicamente a mesma coisa mesmo. A única diferença é que, ao criar elementos em uma variável, você precisaria criar um nó pai que receberia todos os filhos antes de colocar tudo no DOM. E, ao colocar no DOM, o pai seria colocado junto.

Criando um fragmento, quando você faz o append dele no DOM, só os filhos são adicionados.

Pense no caso de um `ul`, por exemplo. Se você tiver um `ul` vazio no DOM, e for adicionar as LIs, o fragment funcionaria melhor. Se fosse criar um novo `ul` em memória, ao tentar fazer o append dele inteiro, você teria um `ul` dentro de outro `ul` :)

Então basicamente o fragment vai servir como uma cópia em memória do `document` e, ao inserir ele no DOM, você não precisa se preocupar em limpar nada: tudo o que for adicionado serão só os filhos que estiverem dentro do fragmento :D

**Comment by edpedroso** [comment]
Perfeito @fdaciuk , agora sim ficou bem claro a utilidade do fragment. Obrigado!

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida avisa ae :D
