### ISSUE TITLE
email

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#1875]
Escreva aqui sua dúvida

@fdaciuk
ola,
fiz uma compra pelo udemy do curso javascript ninja porem minha conta do udemy esta castrado com email leoigel@hotmail.com porem meu email valido e leoigeltiko15@gmail.com, gostaria de receber suas avaliacaos neste email : leoigeltiko15@gmail.com

**Comment by fdaciuk** [comment]
Oi @leoigel! Não tem problema =)
Pode seguir fazendo o curso e enviando os desafios com essa sua conta mesmo :D
