### ISSUE TITLE
Seção 28 vídeo 167

### ISSUE THREAD

**Issue by michaelsnogueira** [da2k/curso-javascript-ninja#1902]
Boa tarde Professor, estou acompanhando o vídeo 167 e ao fazer a mesma coisa que você, esta retornando o seguinte erro abaixo:

![image](https://user-images.githubusercontent.com/17577491/31054790-bd685212-a690-11e7-9cc4-3391af1b7e9a.png)

![image](https://user-images.githubusercontent.com/17577491/31054800-d49efbca-a690-11e7-9363-f6e08bd87720.png)

Poderia me ajudar? Desde já grato!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @michaelsnogueira! O problema provavelmente está acontecendo porque você está acessando diretamente o arquivo no browser, usando o protocolo `file:///`.

Para que o Ajax funcione corretamente, você precisa subir um servidor qualquer (ainda que um server estático, como eu mostrei anteriormente, com python mesmo), que deve funcionar, senão ele vai dar o problema de _CORS_, que é esse erro que você teve (e vamos vê-lo mais pra frente ainda em aula) :D 

Mas para funcionar, apenas use um servidor estático qualquer que vai funcionar, só não pode acessar diretamente o arquivo, ok? :)

Qualquer dúvida avisa ae!

**Comment by michaelsnogueira** [comment]
Consegui Professor!! Valeu
