### ISSUE TITLE
Seção 28, aula 168

### ISSUE THREAD

**Issue by michaelsnogueira** [da2k/curso-javascript-ninja#1906]
Boa noite Professor,

                Gostaria de saber o porquê o meu servidor localhost não esta fazendo o Request Headers? conforme abaixo:

![image](https://user-images.githubusercontent.com/17577491/31061060-6a4eaa0a-a6f3-11e7-893e-ded0774458cd.png)

O browser não esta retornando o readyState: 2, 3 e 4.

Meu código:

![image](https://user-images.githubusercontent.com/17577491/31061116-f79595b8-a6f3-11e7-8876-e0d6bfd75c7b.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @michaelsnogueira! Quando você cria qualquer evento com o `addEventListener`, você sempre deve remover o `on` do nome do evento :)

No caso, `onreadystatechange` vira `readystatechange` ;)

Você só usa o `on` se usar o evento como propriedade do objeto, no caso: 

```
ajax.onreadystatechange = function () {}
```

**Comment by michaelsnogueira** [comment]
Valeu Professor!! :)
