### ISSUE TITLE
Aula 33

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1911]
Fala professor !

Algumas dúvidas
 - é interessante termos no nosso github o coverage versionado ou deixa ele no gitignore ?
 - Depois do test passado é só implementarmos ele no código certo ?
 - Hoje a maioria das vagas ainda vejo em TDD poucas que vejo em BDD mais o conceito é o mesmo pelo o que vi no curso só muda mesmo a sintaxe, certo ?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @lucianobarauna! Vamos lá:

> é interessante termos no nosso github o coverage versionado ou deixa ele no gitignore ?

A resposta é: depende. Se você quiser ter uma visualização do coverage da aplicação à partir do seu repositório, você pode versionar. Eu fiz isso [nesse repositório aqui](https://github.com/reportz/ajax).

Agora, se você quiser usar o coverage somente com uma ferramenta de integração contínua, que deve quebrar o deploy ou a integração se o coverage estiver baixo, aí não precisa versionar, pois quando a ferramenta de CI/CD executar o comando de teste e coverage, ele vai gerar os arquivos necessários à partir daquele momento para verificar a cobertura de testes :)

---

> Depois do test passado é só implementarmos ele no código certo ?

Não entendi a pergunta. Se o teste passou, significa que já foi implementado. Aí você entra na etapa de _refactory_, para verificar se há alguma melhoria a ser feita no código antes de escrever o próximo teste que quebre :)

---

> Hoje a maioria das vagas ainda vejo em TDD poucas que vejo em BDD mais o conceito é o mesmo pelo o que vi no curso só muda mesmo a sintaxe, certo ?

Diferentes pessoas vão te dar diferentes definições de TDD e BDD. No meu ponto de vista, até onde eu estudei sobre o assunto, TDD é o que importa: fazer o desenvolvimento guiado por testes. As ferramentas de teste é que normalmente têm as interfaces de asserções como "TDD" ou "BDD", onde BDD seria só uma forma mais "humanamente legível" para escrever as asserções.

O grande ponto é: apenas entenda como funciona testes, como você escreve testes antes da implementação. Entenda que isso é um _mindset_ e que você precisa **pensar** dessa forma. Com isso claro na sua mente, você não precisa ficar se apegando a nomes :)

---

Se algo não ficou claro, comenta ae :D

**Comment by lucianobarauna** [comment]
> Depois do test passado é só implementarmos ele no código certo ?
Ops desculpa rs, O que eu quis dizer aqui é que depois do teste feito e terminado todo o processo é só jogar ele no seu código e continuar para o próxima parte que exija o teste, certo ?

**Comment by fdaciuk** [comment]
Ah sim, ae você pode usar o código testado na sua aplicação :)

**Comment by lucianobarauna** [comment]
Entendi esses termos de testes ainda tá meio turvo para mim rs.
Como estou revisando algumas coisas e criando anotações do curso aqui no github vou aproveitar para dar uma revisada no capítulo de testes.
Não vou aplicar esses testes no último ex não rs acho que vai ser muito complexo para começar rs
Acho melhor aplicar eles nos projetos pessoais do 0

**Comment by fdaciuk** [comment]
Legal! Pois é.. comece a fazer testes em projetos menores, pra ir entendendo bem a ideia, vai ficar mais fácil :)
