### ISSUE TITLE
ECMAScript 2015

### ISSUE THREAD

**Issue by edpedroso** [da2k/curso-javascript-ninja#1915]
Olá Fernando,

Alguma chance de termos uma atualização no curso falando sobre as novidades do ECMAScript 2015?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @edpedroso! Nesse curso especificamente não, mas pra ano que vem teremos algumas novidades =)
Assim que terminar o curso de React (que fala bastante de ES6+), vamos ter várias novidades. Aguarde :D

**Comment by lucianobarauna** [comment]
Conta aew professor @fdaciuk  rs agora fiquei curioso

**Comment by fdaciuk** [comment]
Não posso falar agora @lucianobarauna, só posso dizer que os alunos do JS Ninja vão se beneficiar com a novidade (ou novidades) haha :D

**Comment by lucianobarauna** [comment]
Tranquilo então rs

**Comment by fdaciuk** [comment]
Só aguarde :)
