### ISSUE TITLE
Funções nomeadas

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#1919]
Escreva aqui sua dúvida

Bom dia mestre,
eu não entendi ainda o pq usar função nomeada qdo crio um metodo de objeto

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @jhonesgoncal! O grande ponto de nomear funções é para facilitar o _debug_. Em algum momento você pode ter problemas no seu código, ou o browser vai exibir no console alguns erros relacionado ao código problemático.

Quando você não nomeia as funções, o browser não consegue exibir um nome se o problema for naquela função, então você pode acabar vendo algum erro como:

```
(anonymous) bla bla bla
```

O `(anonymous)` é o nome que o browser coloca quando sua função não tem um nome. Ao nomear, o browser vai usar o nome da função para exibir no erro, no lugar do `(anonymous)`, então fica muito mais fácil saber onde o problema está acontecendo :)

Ficou claro?

**Comment by jhonesgoncal** [comment]
sim ficou sim rsrs é que no livro que estou lendo meio que não aconselha nomear. rsrs ai fiquei confuso. mais a sua explicação superou kk

**Comment by fdaciuk** [comment]
haha! Então.. fica mais verboso, mas é importante pra debug :)
Outro ponto importante: se estiver usando alguma ferramenta pra compilar código, por exemplo: se estiver escrevendo código em ES6+ e compilando pra ES5 com babel, o babel automaticamente nomeia funções anônimas com o mesmo nome da variável. Então, no final, ele faz o trabalho pra você não precisar fazer.

No final, sua função que vc criou anônima vai ter um nome, porque foi adicionado pela ferramenta :)

Mas assim.. hoje os browsers estão mais inteligentes. Ao menos o Chrome já consegue mostrar o nome da variável quando a função é uma expressão e anônima.

Para nomear ou não, acho que vale você testar na sua aplicação e verificar como está retornando :)

Se quiser forçar um erro, pode usar o `throw` para testar:

```
var func = function lala () {
  throw new Error('erro!')
}

func()
```

Quando executar a função no Chrome, você vai ver `lala` como nome da função. Se tirar o `lala`, ele vai mostrar `func`. Então vai de você ir ajustando esses pontos, e nomear se achar necessário :)

**Comment by jhonesgoncal** [comment]
Vlw muito boa a explicação.. tem algum metodo que compara um array com outro e tras somente os diferentes?

**Comment by fdaciuk** [comment]
Tem algumas formas de fazer isso. Uma delas é com o método `filter`:

```js
var arr1 = [1, 2, 3]
var arr2 = [1, 3, 5]

var arr3 = arr1.concat(arr2).filter(function (item, index, array) {
  return array.indexOf(item) === index
})

console.log(arr3) // [1, 2, 3, 5]
```

Nesse método você basicamente "une" dois arrays, e com o `filter`, você checa se o índice do item atual que está sendo iterado é o item do index iterado. Se o elemento já existir, o `indexOf` vai retornar o índice do primeiro valor encontrado, então esse valor retornado do `indexOf` vai ser diferente do `index` atual, fazendo com que aquele valor não entre no novo array. Dessa forma você consegue filtrar e retornar só os valores diferentes :)

**Comment by jhonesgoncal** [comment]
muito obrigado mestre, queria te perguntar também se fazendo os exercícios certinho do curso, a pessoa esta pronta pro mercado quando finalizar?

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Quanto mais você faz, mais você consegue ver o seu nível, e consegue melhorar com isso. Então quanto mais você faz os desafios, e aplica o conhecimento em projetos pessoais, mais você estará preparado para o mercado :D 

Procure fazer pequenos projetos pessoais com o conhecimento adquirido, e, se surgir alguma dúvida de algo que você não saiba fazer, mas encontrar alguma solução pronta, não cole o código na sua aplicação. Procure entender bem o que aquele código faz. Somente assim você conseguirá se profissionalizar :D

**Comment by jhonesgoncal** [comment]
então professor @fdaciuk  o problema é que sempre  é dificil pensar em um projeto, tipo ja fiz uns 10 cursos de javascript pq acho que me ajuda a entender fazer varios cursos da mesma coisa, porem as vezes não consigo imaginar esses projetos.

**Comment by fdaciuk** [comment]
Eu sei como é @jhonesgoncal xD
As vezes a gente fica sem ideia do que fazer pra treinar :)

Mas eu recomendo você fazer o seguinte: quando estiver sem ideia, pegue um projeto já existente, e tente reproduzí-lo com o conhecimento que você tem.

Exemplo: sistema financeiro. O Organizze é bem legal, tente reproduzir as funcionalidades dele.
Trello também é um outro exemplo legal. Tem vários que você pode pegar. A única finalidade é você exercitar mesmo o que está aprendendo.

E não precisaa reproduzí-los por completo: tente pegar uma parte específica: uma modal, no caso do Trello, um card, etc.

São muitas opções, só escolher :D

**Comment by jhonesgoncal** [comment]
Estou na aula 16 vc acredita que ja tenho conhecimento para fazer esse tipo de exercicio?

**Comment by fdaciuk** [comment]
Você só vai saber se tentar :D 
O grande esquema do aprendizado é a prática: ainda que você não tenha certeza se sabe o suficiente, tente fazer, aplique o conhecimento na prática! Quando você travar, busque suporte! Você sabe que pode contar comigo para o que precisar, fique à vontade para tirar dúvidas quando travar em algo no seu aprendizado :)

O grande ponto do curso é você aprender JS de verdade, e você só vai conseguir fazer isso se praticar muito e entender de fato o conteúdo passado! Então vai fundo, sem medo :D

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
