### ISSUE TITLE
Aula 33 - Selecionando button e Error

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1922]
Fala mestre !

Estou na parte do método `DELETE` o que pretendo fazer é nesse caso pegar a minha tr do button que clico para conseguir chegar no valor da placa para assim conseguir excluir ele do banco.

Só que assim funciona:
```
 var $trParent = this.parentNode.parentNode;
$trParent.querySelectorAll('td')
```
______
E assim não funciona e retorna o erro
```
 $($trParent + ' td').getAll()

// Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object HTMLTableRowElement] td' is not a valid selector.
```

Seria por ele está retornando todo o meu elemento como um document.html e não uma tag em si ?

O link do código é esse [aqui](https://github.com/lucianoMeusCursos/jsninja-projeto-lojacarros/commit/ac0e6be13576b4f2a8cd5bbf5dde92d1be0dd3f4)

Assim eu consegui resolver mais estou curioso para saber o que é, creio que a primeira opção me atende mais não utilizo a dom.js e isso me incomoda.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @lucianobarauna! Vamos lá:

Isso aqui não vai funcionar:

```
 $($trParent + ' td').getAll()
```
Pelo seguinte motivo: `$trParent` é um objeto, não uma string com o selector, que você pode concatenar com o `' td'`, saca?

Então sim, só a primeira forma vai funcionar.

Outro ponto importante: ao invés de usar `parentNode.parentNode`, que pode mudar se a sua marcação marcação mudar, adicione um `data-id` ou algo assim no elemento que você precisa manipular. Assim você não depende diretamente de tentar pegar o nó mais acima pra tentar fazer algo, sacou?

Assim, independente se a sua marcação mudar, o elemento que precisa ser manipulado está marcado, e a ação vai se dar nele :)

**Comment by lucianobarauna** [comment]
Verdade @fdaciuk  não tinha me atentado a isso.

Vlw mesmo e que bom que to no caminho !!

Abraço !

**Comment by fdaciuk** [comment]
Segue o rumo \o/

**Comment by lucianobarauna** [comment]
Agora como vou pegar o elemento pai sem dar um `this.parent.parent` eu faço assim para aproveitar a referência do botão

**Comment by fdaciuk** [comment]
Vamos lá: cada TR é única, correto? E cada TR você cria de forma isolada. Então você consegue saber qual botão é específico de qual TR. Então você pode usar `data-js` ou `data-id`, ou `data-qualquercoisa` sempre relacionando essas informações.

Exemplo: imagine que você vai fazer um loop pra renderizar 3 TRs. Quando você faz o loop, você tem o identificador de cada TR, que pode ser o índice na hora da iteração.

Esse índice você usa para, na hora de criar a TR e o botão, relacionar os dois. Na TR vc pode colocar `data-js="tr-<ID>"` e no botão um `data-js="button-<ID>", onde `<ID>` é o índice que está sendo iterado.

Deu pra entender? :)

**Comment by lucianobarauna** [comment]
Deu sim !
Depois disso eu isolo os ID e vejo se eles são iguais ;-)
Vai dar trabalho mais fica legal de ser feito !

**Comment by fdaciuk** [comment]
Então, na verdade eles já estarão isolados! Para facilitar, você pode pegar alguma informação específica que já venha do backend por exemplo para gerar esse ID. A placa do carro seria uma boa, já que é única por carro. Então você, ao clicar em um botão de deleção, já vai ter a placa do carro que precisa apagar, assim fica fácil :D

**Comment by lucianobarauna** [comment]
Verdade eu já vou ter ela no atributo data.

Otimizo meu código dessa forma já aproveitando o que já tenho e no máximo só utilizo um regex para tirar o lixo que eu não quero hehe.

Evita por exemplo eu dar um querselectorAll em tudo e depois fazer um filter e bla bla bla. ( eu já tava pensando nisso ) aheuiaheiaueha

Poxa tudo é a forma de se pensar e aproveitar o máximo que temos antes de escrever algo novo ;-)

**Comment by fdaciuk** [comment]
Isso mesmo! Aproveite as informações que você já tem para facilitar seu trabalho :D 
Somos programadores, temos que pensar na forma mais preguiçosa e menos trabalhosa de fazer as coisas haha!
