### ISSUE TITLE
Aula 34 - Standard

### ISSUE THREAD

**Issue by edpedroso** [da2k/curso-javascript-ninja#1934]
Fernando, instalei o Standard e gostei bastante dele para padronizar o código.

Mas estou recebendo o seguinte erro no XMLHttpRequest:

`[standard] 'XMLHttpRequest' is not defined. (no-undef)`
`var XMLHttpRequest: new () => XMLHttpRequest`

Alguma ideia do motivo? 

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @edpedroso! Cara, esse erro é porque o `XMLHttpRequest` é um objeto global. Para esses casos, você pode colocar no package.json uma entrada `standard` dizendo que ele é global.

Algo assim:

```
{
  "dependencies": {},
  "standard": {
    "globals": ["XMLHttpRequest"]
  }
}
```

Dessa forma o standard vai saber que esse objeto é global e não vai mais xiar xD

**Comment by edpedroso** [comment]
Perfeito @fdaciuk , deu certo. Muito obrigado!

**Comment by fdaciuk** [comment]
Qualquer coisa avisa ae :D
