### ISSUE TITLE
Valor null em forEach com data atributo

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-javascript-ninja#1939]
Fala professor !!

Então solucionei o problema mais não sei se mesmo assim tem como pegar pelo atributo data

Aqui está o link para o código: [Link](https://github.com/lucianoMeusCursos/jsninja-projeto-lojacarros/commit/0c523247684347c7ca12cf14502d91a75684e5d8)

Acontece que quando dei o forEach no array para buscar o atributo data ele me retornou null e para acertar eu tinha que utilizar uma propriedade chamada `dataset` mais percebi que ela só funciona apartir do IE11 e pensando em suporte decidi não utiliza-lá 

```
 console.log(item.getAttribute('[data-js-table-plateid]')); // Só funciona se eu colocar dataset.jsTablePlateid mais só funciona apartir do IE11
```
Então para contornar utilizei o id rs

```
console.log(item.getAttribute('id')); // aqui funciona em tudão
```

- Fiz correto em fazer isso ?
- Sempre fico na dúvida entre for e forEach. Usar o forEach ao invés do for nessa situação é melhor ?

Abrcs!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucianobarauna! Provavelmente não está funcionando porque você está usando os _brackets_ `[]`.

O `getAttribute` espera o nome do atributo mesmo, não um seletor :)

**Comment by fdaciuk** [comment]
Sobre `for/forEach`: o `for` faz loop pra qualquer coisa. Já os métodos de array têm responsabilidades específicas: o `forEach`, por exemplo, não retorna nada, mas como ele recebe uma função, acaba tendo vantagem em relação ao `for` por conseguir criar um escopo para cada item do array que está sendo iterado.

A única vantagem de usar o `for` - que é micrômetros de segundos mais rápido, nem faz tanta diferença em aplicações reais - é que você consegue usar o `break` para parar uma iteração. Já usando `forEach` você não consegue :)

Mas tente ir além: não fique só no `for/forEach`. Se precisar retornar valores, como um novo array, ou um novo objeto, use os métodos `map`, `filter`, `reduce`, `some`, etc. 

Cada um tem uma função específica. Procure entender o que cada um faz, que você saberá quando usar um ou outro :)

Mas se tiver dúvidas com relação ao uso deles, não hesite em perguntar! Estamos aqui pra ajudar :D

**Comment by lucianobarauna** [comment]
Poxa que vacilo meu não tinha me atentado ao erro do `[]` rs
Entendi..eu comecei com o forEach para ver se conseguiria fazer o loop tranquilo.
Mais já que o senhor falou vou tentar talvez utilizar um filter já que eu só preciso de um elemento ;-)

Talvez: Quando eu clicar no botão para remover eu pegue todas as trs que estão ali e utilize um filter para tirar que eu quero ;-)

```
$trsTableCar.forEach(function(item, index){
                        console.log('ta funcionado porra', item.getAttribute('data-js-table-plateid')); // Só funciona se eu colocar dataset.jsTablePlateid mais só funciona apartir do IE11
                        console.log(item.getAttribute('id')); // aqui funciona em tudão
                    },$trsTableCar)
```

**Comment by fdaciuk** [comment]
Exato! Essa é a ideia: entender os métodos, já que todos eles servem para fazer loop, e usar o que mais se encaixa na sua necessidade :)

Qualquer dúvida avisa ae :D

**Comment by lucianobarauna** [comment]
Aew professor @fdaciuk , refatorei o código olha como ficou 

Fiz uma brincandeira maneira eu acho e terminei o último desafio do curso rs
```
createRemoveButton: function buttonRemove(objValuePlate){
    var $button = $.createElement('button');
    $button.setAttribute('class', 'btn-remove');
    $button.setAttribute('data-js-idcar-remove', objValuePlate);
    $button.textContent = "excluir";

    $button.addEventListener('click', app.removeTr, false);
    return $button;
},

removeTr: function removeTr(e){
        e.preventDefault();
        var $buttonIdCar = this.getAttribute('data-js-idcar-remove');
        var $trsTableCar = $('[data-js-table-plateid]').getAll();

        function trGetAtributeId(item){
            return item.getAttribute('data-js-table-plateid')
        }

        function isHasTrButtonRemove(item){
            if(item === $buttonIdCar){
                document.querySelector('#placa' + item).remove()
                app.deleteCarData(item);
            }
                
        }
        // ---- Acho que nesse ponto ficou funcional
        Array.prototype.map.call($trsTableCar, trGetAtributeId).filter(isHasTrButtonRemove);
        // -----
},

deleteCarData: function deleteCarData(valuePlateTr){
    console.log('deletando carro agora');
    var delAjax = new XMLHttpRequest();
    delAjax.open('DELETE', 'http://localhost:4000/car');
    delAjax.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    delAjax.send('&plate=' + valuePlateTr);
}
```

**Comment by fdaciuk** [comment]
Boa @lucianobarauna! Ficou bem legal :D 
A ideia da função `createRemoveButton` foi ótima, parabéns!

Algumas dicas de melhorias:
- Ao remover a `tr`, lembre-se de remover o evento do botão também, senão ele vai ficar sempre "ativo" consumindo memória;

- Nessa linha: `Array.prototype.map.call($trsTableCar, trGetAtributeId).filter(isHasTrButtonRemove);`, na verdade você não precisaa do `map` e `filter` ali, já que essas duas funções sempre **retornam** um valor, que no caso, é um novo array. Como você não está atribuindo o resultado dessa chamada para uma variável, nem é necessário retornar o valor final dessa expressão, você pode trocar o `map` e `filter` por um único `forEach`, já que ele não retorna nenhum valor :)

- Tente reaproveitar ao máximo as funções criadas. As funções `trGetAtributeId` e `isHasTrButtonRemove` foram criadas dentro do método `removeTr`. Lembre-se que funções são como objetos: elas são passadas por referência. E JS tem escopo de função. Então, a cada vez que o método `removeTr` for executado, novas funções `trGetAtributeId` e `isHasTrButtonRemove` serão criadas em memória.

Você consegue reaproveitar essas funções, criando elas fora de `removeTr` e só executando elas ali dentro, quando necessário. Dessa forma você reaproveita a referência da função e economiza memória :)

Não que isso seja um problema enorme, mas é legal saber disso e começar a pensar nesses pontos. Nem sempre é possível reutilizar uma função dessa forma, ainda mais quando uma função retorna outra função, a função interna sempre será criada novamente. E isso não é ruim. Mas há casos e casos.

Se você só precisa passar um valor via argumento para uma função e retornar um valor simples, que não uma outra função, então tente reaproveitar a referência dela :)

- Nomes de funções:
Falando sobre a função `trGetAtributeId`: sempre que você precisa **obter** algum valor, você inicia o nome da função com `get` e faz ela retornar algo. O retorno está ok, mas faz mais sentido se ela começar com `get`, pois aí você sabe que ela vai te retornar algo que você quer.

Sobre a função `isHasTrButtonRemove`: você só deve começar o nome de uma função com `is` ou `has` quando essa função for te retornar um valor booleano. É como se você estivesse fazendo uma pergunta, e, ao executar a função, você irá receber uma resposta `true` ou `false`.

E sempre você vai usar um dos dois, não os dois juntos: se você quer saber se **é** alguma coisa, vocẽ começa a função com `is`:

```
isString(value)
isButton(value)
isCar(value)
```

Nesse caso, você checa se o valor passado **é** alguma coisa.

Agora, para saber se algum valor **tem** alguma coisa, você começa a função com `has` ou `have`:

```
hasButton(value)
hasValue(value)
hasSomething(value)
```

Acho que é isso! Cara, está indo muito bem! Sempre temos coisas a melhorar no código, ele **nunca** vai estar perfeito! Mas praticando, você vai entendendo os problemas mais comuns, e as coisas vão começar a ficar mais claras!

Pratique sempre! Faça outros projetos, refaça, mas não pare! E conte comigo para o que precisar :)

**Comment by lucianobarauna** [comment]
@fdaciuk 
Primeiro mais uma vez muito obrigado pelas dicas no código !

Segue o link: [link código](https://github.com/lucianoMeusCursos/jsninja-projeto-lojacarros/commit/79bb1d081e140971db79d3df629faea5f576ea72)

1. Deletei o evento. Como vejo os eventos ativos na memória ainda ?
1. Consegui entender agora o porquê de usar forEach e não o filter junto do map. 
Como não vou retornar nada faz total sentido mesmo. 
É só perder um tempinho para ver o que é melhor para aquela situação ou não.
1.Hum confesso que eu fique na dúvida sobre o escopo da função ali rs por isso preferi deixar onde estava. Ao meu ver se eu criasse dessa forma como vc está falando estava a errado. Agora se eu fizesse da forma abaixo eu estaria errado nesse padrão ?
```
var app = (function(){

    var isTrRemove = function isTrRemove(element, buttonDeleteId){
            return element.getAttribute('data-js-table-plateid') === buttonDeleteId;
        },

    
    return {

        ...

        removeTr: function removeTr(e){
            e.preventDefault();
            var $buttonDelete = this;
            var buttonDeleteId = $buttonDelete.getAttribute('data-js-idcar-remove');
            var $trsTableCar = $('[data-js-table-plateid]').getAll();
            $trsTableCar.forEach(function(element, index){
                if (isTrRemove(element, buttonDeleteId)) {
                    app.deleteCarData(element);
                    $buttonDelete.removeEventListener('click', app.removeTr, false);
                    $('#placa' + buttonDeleteId).get().remove()
                }
            })
        }

        ...
    };

})()

app.init();

```

Só seria uma funcionalidade que eu não queria que fosse exportada no método do App certo ?
Parando para penssar aqui se eu fosse utilizar isso como uma lib acabaria não tendo esse método ao acesso por conta dessa clousure. Certo ?
Mais nesse padrão de modularização é errado eu usar dessa forma ?
Aliás qual o nome desse padrão se é que tem um nome, rs?
1. Obrigado mais uma vez sobre a explicação sobre o nome das funções e seus padrões.

Obrigado por tudo professor e com certeza vou fazer mais projetinhos desse com vanilla.js

**Comment by fdaciuk** [comment]
Opa, eae @lucianobarauna! Tá mandando bem cara, é por esse caminho mesmo :D 

Vamos às respostas:

> Deletei o evento. Como vejo os eventos ativos na memória ainda ?

Não vê. Por isso você tem que cuidar dos momentos em que você atrela eventos e remove eventos de um elemento, mas não tem uma forma automática de fazer isso. Você é que tem que cuidar dessa parte, criando sua própria técnica para saber quando um evento foi atrelado a um elemento :)

> Ao meu ver se eu criasse dessa forma como vc está falando estava a errado. Agora se eu fizesse da forma abaixo eu estaria errado nesse padrão ?

O código não está errado. Na verdade, não existe "certo" ou "errado". O ideal é sempre tentar manter um padrão no seu código.

No caso do que você fez, o `isTrRemove` poderia ser uma função literal, não há necessidade de atribuir a uma variável e nomear a função. Menos é mais :)

> Só seria uma funcionalidade que eu não queria que fosse exportada no método do App certo ?

Exatamente! Essa função não ficaria disponível "publicamente", fora desse escopo do seu código :)

> Parando para penssar aqui se eu fosse utilizar isso como uma lib acabaria não tendo esse método ao acesso por conta dessa clousure. Certo ?

Exato!

> Mais nesse padrão de modularização é errado eu usar dessa forma ?
> Aliás qual o nome desse padrão se é que tem um nome, rs?

Como eu disse: não há certo ou errado. Apenas tente manter um padrão :)
O nome desse _pattern_ que você está usando se chama _Revealing Module Pattern_, pois você só exporta as funções que precisa para fora do escopo do seu código :)

---

Mas é isso cara, está mandando muito bem! O conhecimento só vem com muita prática! Continue praticamente bastante, errando e aprendendo :D 

E qualquer dúvida, conte comigo :)

**Comment by lucianobarauna** [comment]
Vlw professor !! @fdaciuk
