### ISSUE TITLE
Challenge-23 - Evento atrelado a um array-like

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#1942]
Olá, professor.  
Estou conseguindo atrelar um evento à um array-like: 

```JAVASCRIPT
(function(win, doc) {
    'use strict';

    var $buttonNumbers = doc.querySelectorAll('[data-js="button-number"]');

    $buttonNumbers.forEach(function(number) {
        console.log(number);
    });
})(window, document);
```

```HTML
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Challenge 23</title>
</head>
<body>

    <div class="number-buttons">
        <button data-js="button-number" value="0">0</button>
        <button data-js="button-number" value="1">1</button>
        <button data-js="button-number" value="2">2</button>
        <button data-js="button-number" value="3">3</button>
        <button data-js="button-number" value="4">4</button>
        <button data-js="button-number" value="5">5</button>
        <button data-js="button-number" value="6">6</button>
        <button data-js="button-number" value="7">7</button>
        <button data-js="button-number" value="8">8</button>
        <button data-js="button-number" value="9">9</button>
    </div>

    <script src="challenge-23-b.js"></script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/29297788/31401125-410a37c8-adc8-11e7-8a72-5bd286707fd0.png)

Não era pra isso dar certo. Vc sabe me dizer o que está acontecendo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Você fala do `forEach`?

Se for isso, o código funciona porque alguns navegadores mais modernos já o implementaram para `NodeLists`.

Na época em que o curso foi gravado, isso ainda não existia, por isso usávamos o _hack_ para forçar o _array like_ usar o método `forEach` do `Array` :)

O importante é sempre tentar dar uma olhada na documentação, pois lá pode haver mais informações relevantes sobre essas atualizações da linguagem :)

Referências:
`document.querySelectorAll`: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

`NodeList`: https://developer.mozilla.org/en-US/docs/Web/API/NodeList

Nesses links você pode encontrar essas informações :D 

Qualquer dúvida avisa ae!

**Comment by Roger-Melo** [comment]
Beleza professor. Obrigado!
