### ISSUE TITLE
Questionamento challenge 04

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-javascript-ninja#1944]
@fdaciuk na correção do exercício você diz que: Se atribuir o a variável `qtd` ao resultado ou seja, substituir lá no `return` o método `carro.quantidadePessoas` pela variável `qtd` não vou ter atualizações desse método se ele for feito em outro local, correto ?

No entanto, fiz alguns testes aqui e ele atualizou.
Eu criei uma função de exemplo:
```js
function addX() {
 var x = 1;
 carro.quantidadePessoas += x; 
};

```
Quando eu executo a função acima ele atualiza ambos, quanto o objeto quanto o método.

``` js
carro.adicionarPessoas = function(adicionar) {
  var qtd = carro.quantidadePessoas + adicionar;
  if( carro.quantidadePessoas === carro.assentos && qtd >= carro.assentos ){
    return 'O carro já está lotado!';
  }
  if( qtd > carro.assentos ) {
    var cabem = carro.assentos - carro.quantidadePessoas;
    var pluralOuSingular = carro.quantidadePessoas === 4 ? 'pessoa' : 'pessoas';
    return 'Só cabem mais ' + cabem + ' ' + pluralOuSingular +'!';
  }
  carro.quantidadePessoas += adicionar;
  return 'Já temos ' + carro.quantidadePessoas + ' pessoas no carro!';
};
```

Será que estou vendo coisas onde não tem ? rsrsr :smile:
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @andersoonweb! Desculpe, foi falha minha xD
Como a sua variável `qtd` sempre recebe o valor de `carro.quantidadePessoas`, então ele pode ser usado no `return` sem problemas, que o valor vai estar atualizado sim! 

Mas usamos o `carro.quantidadePessoas` só pra deixar mais claro de onde essa informação realmente deve vir. Pense na variável `qtd` como uma variável temporária. Ela não é a quantidade real de pessoas que vai ser adicionada, mas sim a quantidade que você está **tentando** adicionar.

Para adicionar mesmo pessoas no carro, ele tem que passar de todos os ifs e chegar no final, onde você incrementa o `carro.quantidadePessoas` :)

Mas você está certo: daria pra usar tranquilamente o `qtd` no `return`, ou ainda fazer o `carro.quantidadePessoas` receber o valor de `qtd` quando chegasse no final, antes do último `return` :)

**Comment by fdaciuk** [comment]
Oi @andersoonweb! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
