### ISSUE TITLE
Challenge 17

### ISSUE THREAD

**Issue by filipeltsilva** [da2k/curso-javascript-ninja#1956]
No vídeo da correção do desafio 17, no exercício abaixo:

**_Substitua todas as letras (somente letras) de "D" maiúsculo até "h" minúsculo por "0" (número zero). Mostre o resultado no console:_**

`console.log( '\nTrocando de "D" a "h" por "0":' );`

Foi considerada a resposta `console.log(text.replace(/[D-Za-h]/g, 0));`.

No entanto, também posso usar o `console.log(text.replace(/[D-H]/gi, 0));`, certo? Obtive o mesmo resultado.

@fdaciuk

**Comment by fdaciuk** [comment]
Na verdade não @filipeltsilva, porque o `gi` vai casar com os resultados globalmente, somente ignorando o _case sensitive_. Nesse caso, seria o mesmo que `[D-Hd-h]`, ou seja: não vai cobrir letras de `[I-Z]`, nem de `[a-c]` :)

**Comment by filipeltsilva** [comment]
@fdaciuk, entendo! Então vou alterar para a sua correção. Obrigado.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa avisa ae :D
