### ISSUE TITLE
Minha branch master sumiu

### ISSUE THREAD

**Issue by silvioCoelho** [da2k/curso-javascript-ninja#196]
Ola, @fdaciuk, preciso de uma ajuda.
cara, minha branch master sumiu.
quando eu digito branch checkout master, aparece: error: pathspec 'master' did not match any file(s) known to git.

**Comment by alvesnatan** [comment]
O comando é:

`git checkout master`

**Comment by fdaciuk** [comment]
Fala @silvioCoelho! Você pode pegar da sua branch master do Github. Tente fazer algo como:

```sh
git fetch origin
git checkout origin/master -b master
```

Se não funcionar me avise ;)
