### ISSUE TITLE
Challenge-31

### ISSUE THREAD

**Issue by michaelsnogueira** [da2k/curso-javascript-ninja#1961]
Boa tarde Professor, tudo bem? 
Estou com a seguinte dúvida:
Eu inseri vários carros, quando eu clico em excluir algum carro cadastrado, como eu sei no elemento DOM qual carro foi clicado para ser excluído? 

![image](https://user-images.githubusercontent.com/17577491/31674327-5377c100-b340-11e7-8324-c6194f6df8a8.png)

O exemplo acima, se eu clicar em deletar o segundo carro cadastrado, não estou sabendo achar uma propriedade no DOM que informa qual elemento que eu cliquei. Poderia dar uma luz professor? Desde já grato!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @michaelsnogueira! Vamos lá:

O esquema é basicamente o seguinte: como você inclui o botão dinâmicamente, você precisa colocar uma identificação nele, para saber qual carro aquele botão deve remover.

Quando você adiciona um carro, você tem as informações sobre o carro. Pegue alguma informação que seja única por carro (a placa, por exemplo), e, quando for adicionar a linha do carro e o botão de remover, adicione no botão um `data-js` ou algo assim com a placa do carro que deve ser removida.

Assim, quando clicar no botão, você saberá qual carro deve remover :)

**Comment by michaelsnogueira** [comment]
Obrigado Professor pela dica, consegui sair do outro lado!!

**Comment by fdaciuk** [comment]
Shoow! Qualquer coisa avisa ae :D
