### ISSUE TITLE
Desafio 10

### ISSUE THREAD

**Issue by nibarcellosdev** [da2k/curso-javascript-ninja#1989]
Professor, não consegui compreender esta parte no desafio 10.
Não entendi a parte do !isOperatorValid(operator)

@fdaciuk
``function calculator(operator) {
	if (!isOperatorValid(operator) ) {
		return false;
	}

}``

**Comment by fdaciuk** [comment]
Fala @nibarcellosdev :D 
Vamos lá: basicamente essa verificação é pra checar se operador passado para a função `calculator` é válido. No caso, operadores válidos deveriam ser somente `+`, `-`, `*`, `/` e `%`.

Se qualquer valor diferente desses for passado, então a função retorna `false` :)

No teste que fazemos no `if` usamos o `!` para inverter a operação. A função checa se o operador **é válido**. Invertendo, a checagem vai ser se o operador **não é válido**. E se ele não for válido, retorna false :)

Ficou claro?

**Comment by fdaciuk** [comment]
Oi @nibarcellosdev! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
