### ISSUE TITLE
aula 2

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#1998]
Escreva aqui sua dúvida em fazer a clonagem!!
tipo baixei o git, estou no meu repositorio  https://github.com/leoigel/curso-javascript-ninja, cliquei na clolagem ssh, fui no git te tentei fazer o a clonagem porem da erro, onde estou errando?

da isso
C:\Users\owner>
C:\Users\owner>git clone git@github.com:leoigel/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ola estou com muita duvida ao 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! Vamos começar do início: você tem a chave SSH no seu computador?

**Comment by leoigel** [comment]
infelizmente nao sei como achar a chave ssh do computador...como eu faço?

**Comment by fdaciuk** [comment]
Você está usando windows, correto? 
Dá uma olhada [nesse tutorial aqui](https://help.github.com/articles/connecting-to-github-with-ssh/), que tem todos os passos pra subir uma chave SSH no GitHub. 

Veja que cada link é um passo que você tem que fazer, e tem as opções de escolher o sistema que você está usando, para mostrar o tutorial correto :)

Se tiver qualquer dúvida, só avisar que eu vou te ajudando, ok? :)

**Comment by leoigel** [comment]
entao man... coloquei o comando ssh -T git@github.com  no terminal da git blash porem deu isso aqui:
owner@LAPTOP-IHE92V6T MINGW64 ~
$ ssh -T git@github.com
Enter passphrase for key '/c/Users/owner/.ssh/id_rsa':
Hi leoigel! You've successfully authenticated, but GitHub does not provide shell                 access.

**Comment by leoigel** [comment]
para falar a verdade esto vendo que sim consegui , porem esta surgindo outro problema, nao consigo subir no sublime, 
owner@LAPTOP-IHE92V6T MINGW64 ~/curso-javascript-ninja (challenge-02)
$ subl .
bash: subl: command not found

owner@LAPTOP-IHE92V6T MINGW64 ~/curso-javascript-ninja (challenge-02)
$ git status
On branch challenge-02
nothing to commit, working tree clean

entende?

**Comment by fdaciuk** [comment]
tem que ver se tem esse alias no teu sistema.. se não tiver, você pode criar ou abrir o sublime normal mesmo =)

**Comment by fdaciuk** [comment]
Oi @leoigel! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
