### ISSUE TITLE
Finalização challenge-33

### ISSUE THREAD

**Issue by fabioaguirre** [da2k/curso-javascript-ninja#2011]
Olá Fernando, tudo bom?

Acabei de finalizar o challenge-33 e praticamente o curso, falta apenas a aula bônus.

Você poderia, por favor, validar o código que fiz? Ele está funcionando, mas poderia dizer se tem algo de errado que fiz, mas que por ventura acabou dando certo, e se tiver mais algum comentário ou sugestão serão sempre bem vindos!

O curso foi sensacional! Realmente cumpre o que promete, finalmente aprendi JavaScript.

Muito obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fabioaguirre! Tudo ótimo! Melhor agora lendo isso :heart: 

Com certeza vou olhar sim! Tenho outros dois pra olhar também, mas vou tentar olhar tudo essa semana ainda, ok? :)

Qualquer coisa avisa ae :D

**Comment by fabioaguirre** [comment]
Oi Fernando,

Opa, maravilha! Fico no aguardo!
E pode deixar que qualquer coisa aviso sim!

Muito obrigado!

**Comment by fdaciuk** [comment]
Oi @fabioaguirre! Já passou um tempo e não te dei feedback do seu código, desculpe :\
Vou fechar a issue, mas se você precisar de qualquer coisa, conte comigo, ok? =)
