### ISSUE TITLE
Desafio 22

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2020]
`function sum() {
      console.log(arguments)
      Array.prototype.reduce.call(arguments, function (acumulated, actual, index) {
          return acumulated + actual;
      });
    }`

estou fazendo essa funcao, porem qdo chamo ela com os paramentros ela mostra no console o  array porem em baixo mostra undefined no retorno.

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @jhonesgoncal! O console é só uma ferramenta para debugar o código =)
Para uma função retornar algo, ela precisa, necessariamente, usar a palavra `return`. Nesse caso, essa sua função não está retornando nada, então, por default, quando você não tem `return`, o retorno da função é `undefined` ;)

**Comment by jhonesgoncal** [comment]
mais eu coloquei o console que vc pediu no exercicio. eu coloquei o return ali . return acumulated + actual.

**Comment by fdaciuk** [comment]
Sim, o console é só pra você **visualizar** no console (do node ou do browser) os argumentos passados. Mas o `return` é à nível de função. O `return` que vc tem é do `reduce` :)

Você está fazendo todas as aulas ou está pulando alguma? Só perguntando porque a gente já viu isso em aulas anteriores :)

**Comment by jhonesgoncal** [comment]
Não pulei nenhuma. agora entendi oq vc quis dizer.  no caso eu teria que dar um return Array.protype bla bla

**Comment by jhonesgoncal** [comment]
Declare uma variável chamada `userEntry`, que irá receber alguns valores
  entrados pelo usuário. Mostre para o usuário a seguinte frase:
  "Entre com alguns números que serão somados:"


Não entendi muito bem oq vc quis dizer. tipo pra min pedir para ele dar entrada de uma frase tipo um prompt?

**Comment by fdaciuk** [comment]
> Não pulei nenhuma. agora entendi oq vc quis dizer. no caso eu teria que dar um return Array.protype bla bla

Boa! É isso mesmo :)

> Não entendi muito bem oq vc quis dizer. tipo pra min pedir para ele dar entrada de uma frase tipo um prompt?

Isso mesmo, como vimos em aula :)

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
