### ISSUE TITLE
Problemas com o git

### ISSUE THREAD

**Issue by silvioCoelho** [da2k/curso-javascript-ninja#203]
Cara, eu to apanhando um pouco com o git, eu consegui recuperar a branch master como vc ensinou, o problema agora é que eu enviei o challenge-15 enquanto ainda estava na master. como eu faço pra cancelar esse envio?
vou colar pra vc tentar entender oq eu fiz

git commit -m "Challenge-15"
[master 0319652] Challenge-15

**Comment by fdaciuk** [comment]
Opa! Bom, primeira coisa é vc criar a challenge-15 a partir dessa, já que o desafio 15 já está resolvido:

```
git checkout -b challenge-15
```

Depois, pode subir para o seu repositório:

```
git push origin challenge-15
```

Agora já pode mandar o pull request!

---

Pra atualizar a master:

acesse a master:

```
git checkout master
```

- Pegue o arquivo do desafio 15 sem a solução [daqui]().
- Substitua o arquivo do desafio 15 no seu local.
- Faça o add e commit.
- Suba para o seu repositório com:

```
git push origin master
```

Pronto! :D
