### ISSUE TITLE
challenge-27

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2032]
Olá professor! 

Estou com algumas dúvidas sobre esse exercício, vc pode me ajudar? 

```HTML
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Challenge 27</title>
</head>
<body>

  <a data-js="link" href="">1</a>
  <a data-js="link" href="">2</a>

  <script src="challenge-27.js"></script>

</body>
</html>
```

```JAVASCRIPT 
(function(win, doc) {
  'use strict';
  /*
  Aproveitando a lib DOM que fizemos na semana anterior, crie agora para ela
  métodos semelhantes aos que existem no array, mas que sirvam para os
  elementos do DOM selecionados.
  Crie os seguintes métodos:
  - forEach, map, filter, reduce, reduceRight, every e some.

  Crie também métodos que verificam o tipo do objeto passado por parâmetro.
  Esses métodos não precisam depender de criar um novo elemento do DOM, podem
  ser métodos estáticos.

  Métodos estáticos não obrigam o uso do `new`, podendo ser usados diretamente
  no objeto, como nos exemplos abaixo:
  DOM.isArray([1, 2, 3]); // true
  DOM.isFunction(function() {}); // true
  DOM.isNumber('numero'); // false

  Crie os seguintes métodos para verificação de tipo:
  - isArray, isObject, isFunction, isNumber, isString, isBoolean, isNull.
  O método isNull deve retornar `true` se o valor for null ou undefined.
  */

  function DOM(elements) {
    this.element = doc.querySelectorAll(elements);
  }

  DOM.prototype.on = function on(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.addEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.off = function off(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.removeEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.get = function get() {
    return this.element;
  };

  DOM.prototype.forEach = function forEach() {
    Array.prototype.forEach.apply(this.element, arguments);
  };

  var $a = new DOM('[data-js="link"]');

  $a.forEach(function(element) {
    element.addEventListener('click', function(e) {
      e.preventDefault();
      console.log(element + ' was clicked');
    });
  });

})(window, document);
```

1. Dentro do método forEach, o return foi usado na resposta do exercício, por que é necessário usá-lo neste caso?
2. Era esperado que o console.log dentro da chamada do forEach retornasse o elemento do DOM que foi clicado, mas o que é mostrado após o clique é: 
![image](https://user-images.githubusercontent.com/29297788/32390391-659d5c14-c0b5-11e7-8523-28541c3de012.png)

3. As imagens que eu usava no meu repositório de estudos sumiram: 
![image](https://user-images.githubusercontent.com/29297788/32390454-a6ec62c8-c0b5-11e7-8b50-69e76d74dc93.png)

No lugar delas, sobraram apenas os links e elas não estão mais onde hospedei:  

![image](https://user-images.githubusercontent.com/29297788/32390564-06c52b30-c0b6-11e7-95eb-a6085bb5a9c9.png)

Vc sabe se há como recuperá-las e o por que disso ter acontecido? 

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Roger-Melo!

> 1) Dentro do método forEach, o return foi usado na resposta do exercício, por que é necessário usá-lo neste caso?

Não precisa, eu acabei dando `return` por costume, mas o método `forEach` não deve retornar nada, o retorno deve ser `undefined`. Então o correto é sem `return` :)

---

> 2) Era esperado que o console.log dentro da chamada do forEach retornasse o elemento do DOM que foi clicado

O que aconteceu aqui foi o seguinte: você tentou **concatenar** o elemento com a frase `" was clicked"`.

Lembra que, quando você usa o sinal de `+` com uma string e um outro tipo de dado, o JS tenta transformar esse outro tipo de dado em string, usando `toString`?

Ao dar `toString` em um `a`, você vai receber o valor que está no `href` desse `a`, por isso é mostrada a URL que você está mais a frase `" was clicked"` :)

---

> 3) As imagens que eu usava no meu repositório de estudos sumiram. No lugar delas, sobraram apenas os links e elas não estão mais onde hospedei. Vc sabe se há como recuperá-las e o por que disso ter acontecido?

Cara, normalmente esses links de hospedagem de imagens free deixam a imagem temporariamente ali. Provavelmente foi isso que aconteceu: suas imagens ficaram muito tempo sem serem acessadas, e o link expirou.

Quando for subir imagens, use o GitHub mesmo. Aqui você consegue fazer upload de imagens. Quando você está respondendo a uma issue, nessa caixa onde você digita você pode fazer drag'n drop de imagens que o GitHub vai te dar uma URL do CDN deles =)

Ou você ainda pode subir direto em https://rawgit.com =)

**Comment by Roger-Melo** [comment]
>O que aconteceu aqui foi o seguinte: você tentou concatenar o elemento com a frase " was clicked". Lembra que, quando você usa o sinal de + com uma string e um outro tipo de dado, o JS tenta transformar esse outro tipo de dado em string, usando toString?  Ao dar toString em um a, você vai receber o valor que está no href desse a, por isso é mostrada a URL que você está mais a frase " was clicked" :)  

Melhor assim, então, né? 
```JAVASCRIPT 
  $a.forEach(function(element) {
    element.addEventListener('click', function(e) {
      e.preventDefault();
      console.log(element, 'was clicked');
    });
  });
```

É meio inútil, mas dá um prazer :grin:  
___

>Cara, normalmente esses links de hospedagem de imagens free deixam a imagem temporariamente ali. Provavelmente foi isso que aconteceu: suas imagens ficaram muito tempo sem serem acessadas, e o link expirou. Quando for subir imagens, use o GitHub mesmo. Aqui você consegue fazer upload de imagens. Quando você está respondendo a uma issue, nessa caixa onde você digita você pode fazer drag'n drop de imagens que o GitHub vai te dar uma URL do CDN deles =) Ou você ainda pode subir direto em https://rawgit.com =)

Eu comecei a subir as imagens pegando o link gerado pelas issues, é isso mesmo né? Que treta =)

**Comment by fdaciuk** [comment]
> Melhor assim, então, né?

Exatamente! O console.log aceita vários parâmetros, então é melhor usar assim do que concatenar, já que  ele vai ser transformado em string e pode trazer um resultado diferente do esperado :)

> Eu comecei a subir as imagens pegando o link gerado pelas issues, é isso mesmo né? Que treta =)

Exato! Ao menos aqui no GitHub fica "seguro" xD
Já tive problemas de subir imagens pelas issues e perder a referência do link também. Mas isso foi bem no começo, quando o GitHub lançou a feature. Por via das dúvidas, use o https://rawgit.com :)
