### ISSUE TITLE
[desafio 5]

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#2042]
oi,
quero saber se para continuar o curso preciso da api console? pois nao sei como instalar (e nem quero viu), fora isso quero saber onde estou errando aqui:
function newfunction2(arr,index){
	return arr [index];
}
var myvar = ["leo", null, undefined,5,true];
newfunction2(myvar,0);
 quando faco copy paste para o nodejs ele nao encontra a arrays e da undefined!!!!
fora isso quero saber o pq na primeira funcao --- function newfunction2(arr,index){
	return arr [index];
} o Sr pois um index se ele esta pedindo um numero?? muito confuso
valeu ai!!

**Comment by fdaciuk** [comment]
Oi @leoigel! O console que usamos no curso é o do Node.js :)
Eu recomendo fortemente você instalar ele, pois uma hora ou outra você com certeza vai precisar :)

Mas se quiser usar também o console do navegador, fique à vontade :)
A ideia é a mesma, praticamente :)

Sobre a sua dúvida, vamos lá:

> quando faco copy paste para o nodejs ele nao encontra a arrays e da undefined!!!!

Não entendi. O que dá `undefined`? Consegue me mostrar um print?

> fora isso quero saber o pq na primeira funcao o Sr pois um index se ele esta pedindo um numero muito confuso

O `index` que passamos no argumento da função é o nome da variável que vai receber o argumento passado, quando você invocar a função. No caso, quando você chama `newfunction2(myvar, 0)`, o zero que você passa ali no segundo parâmetro é passado para esse argumento `index` :)

Você está assistindo todas as aulas? Recomendo você fazer isso, e tentar fazer e refazer todos os desafios até ficar claro as dúvidas, e sempre que tiver dúvidas, pode postar aqui :)

Mas fazendo e refazendo os desafios, modificando valores, etc., você consegue ver mais fácil onde e como as coisas acontecem, ok? :)

**Comment by leoigel** [comment]
ok valeu

בתאריך 12 בנוב׳ 2017 11:46 PM,‏ "Fernando Daciuk" <notifications@github.com>
כתב:

**Comment by fdaciuk** [comment]
Ficou claro sobre as suas dúvidas? Qualquer dúvida, só avisar =)
