### ISSUE TITLE
[desafio-5]

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#2043]
Escreva aqui sua dúvida
o que estou fazendo de errado esta e minha function book 
function book (bookname){
	var allbooks = {
		'segredosNinja':{quantidadePaginas:299,autor:'leo',editora:'cultura'
	},

		'html5':{quantidadePaginas:355,autor:'jonh',editora:'novateg'
	},

		'css':{quantidadePaginas:245,autor:'gabriel',editora:'veja'
	},
	}

	 !bookname ? allbooks : allbooks [bookname]; 
}
porem quando chamo book() da undefined

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! Lembre que, para pegar um valor de uma função, a função tem que **retornar** algo. Sacou a deixa? haha :D

**Comment by leoigel** [comment]
opsss haha certo

**Comment by fdaciuk** [comment]
Conseguiu @leoigel? :)

**Comment by leoigel** [comment]
sim cara valeu, as vezes me perco pois eh meio fodinha o javascript...valeu cara

**Comment by fdaciuk** [comment]
haha! Sem crise! E sem pressa =)

O aprendizado vem com a prática mesmo! Pratique bastante, que, aos poucos, isso vai ficando natural :)

E qualquer dúvida, não hesite em perguntar! :D 

O importante é aprender de verdade :)
