### ISSUE TITLE
challenge-17

### ISSUE THREAD

**Issue by saintsfall** [da2k/curso-javascript-ninja#2044]
Fala Fernando!
Cara gostaria de esclarecer algo que não ficou muito claro pra mim.
A variável regexDate recebe simplesmente a expressão "/(\d\d) de (junho|julho) de (\d\d\d\d)/gi" pra poder fazer a captura dos devidos dados da data, e até ai tudo bem pra mim.

Mas quando ao final nós chamamos essa variável que contem somente uma expressão:
"console.log(text.replace(regexDate, replaceDate));"
Não consigo entender como o método replace trabalha com os parâmetros dele... (regexDate, replaceDate) e como os parâmetros vão pra funções subsequentes.

Tentei ver o typeof da variável regexDate e ele retorna Object.
Confesso que fui um pouco alem e tentei debugar colocando um breakpoint apos o console.log pra examinar o conteúdo da variável (não chegamos ainda nesses pontos, mas eu fui meio que no modo tentativa e erro pra tentar ver o que acontecia)  e tentei ver se o regexDate não era um objeto com três propriedades que seriam as capturas que a expressão coletava mas... não mostrou nada disso.

Ai parou de fazer sentido, de maneira que eu nunca ia conseguir chegar no raciocínio que resultou na resposta para a ultima questão...
E dentro disso ainda tem a replaceDate que tem um parâmetro também, como o JavaScript sabe qual dado deve ir para o parâmetro, que nesse caso é o mês?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @saintsfall! :D 

Vamos lá: primeiro é importante entender como o método `replace` trabalha.

`replace` é um método de _strings_, então toda _string_ contém esse método, correto?

```js
var str = 'saintsfall';
console.log(str.replace('s', 'B')) // 'Baintsfall'
```

Veja que o método `replace` sempre recebe dois parâmetros: o primeiro é o que deve ser encontrado na string em que ele está sendo usado (no caso, a variável `str`, que contém o valor `"saintsfall"`).

O segundo é o valor que irá substituir o valor encontrado no primeiro parâmetro.

Me diga se até aqui está claro, ou se é há alguma dúvida, que eu continuo, ok? :)

**Comment by saintsfall** [comment]
Sim! Até aqui esta claro sim

**Comment by fdaciuk** [comment]
Show! Vamos continuar então:

O método `replace` aceita ainda outros tipos de valores nos dois parâmetros: o primeiro pode ser uma regex (que é o que usamos no desafio), e o segundo, pode ser uma função.

A função do segundo parâmetro, você cria e passa via parâmetro para o `replace`, que vai fazer todo o trabalho sujo, manipulando a string, e então executando essa função para cada vez que a regex casar, de alguma forma, com a string passada.

Lembra do método `map` de array? Onde passamos uma função para ele, e ele faz alguma coisa com o array, executando aquela função para cada item do array, e usando o retorno da função para transformar os itens do array, retornando um array novinho transformado? É mais ou menos o que acontece aqui :)

Passando uma regex no primeiro parâmetro da função, sem _flags_, então a função vai receber o primeiro parâmetro com o primeiro valor que casou na regex (rode esse código no seu console):

```js
var str = 'saintsfall';
str.replace(/s/, function (a) {
  console.log('valor de a:', a);
  return a;
});
```

Esse código vai exibir no console:
```
valor de a: s
"saintsfall"
```

O primeiro valor `"valor de a: s"` que ele mostra, é o resultado do `console.log` dentro da função.
O segundo valor, é a nova string. O que acabou de acontecer?

Nós pedimos para ele buscar na string `saintsfall`, o primeiro valor que casasse com `s`. Como você usou uma função no segundo parâmetro, o `replace`, ao executar a função, passou para ela como primeiro parâmetro o valor que ele encontrou, que foi o primeiro `s` da string.

Como nós retornamos esse valor, o `replace` **substituiu** o `s` do início da palavra `saintsfall` pelo retorno, que era `s`, o que resultou na segunda linha `saintsfall`. 

Parece que não aconteceu nada, mas agora, execute o código abaixo no console:

```js
var str = 'saintsfall';
str.replace(/s/, function (a) {
  console.log('valor de a:', a);
  return 'B';
});
```

E ele vai retornar:

```
valor de a: s
"Baintsfall"
```

Veja a segunda linha: o retorno da sua função foi apenas `"B"`. Então ele pegou o valor que casou na string (no caso, o primeiro `s`), e substituiu pelo retorno da função, que foi `"B"`. O que resultou em `"Baintsfall"`.

Agora olha que interessante: se você usar a flag _global_ na regex, o `replace` procura não só o primeiro, mas **todos** os valores que casam com a regex. Execute no console:

```js
var str = 'saintsfall';
str.replace(/s/g, function (a) {
  console.log('valor de a:', a);
  return 'B';
});
```

E olha o que isso retorna:

```
valor de a: s
valor de a: s
"BaintBfall"
```

No console, ao invés de imprimir as duas linhas, como elas são iguais, provavelmente você vai ver um número "2" ao lado da primeira linha, e a terceira linha como está. Isso significa que ele mostrou o valor da primeira linha duas vezes.

Mas veja que dessa vez ele substituiu os 2 `s` que tinham na palavra por `"B"`, porque fizemos uma busca _global_ com a regex, e dissemos que ele deveria dar _match_ com qualquer letra `s`, em qualquer ponto do texto, e não somente o primeiro _match_!

Ficou claro até aqui?

**Comment by saintsfall** [comment]
Sim! A comparação com o método map foi essencial para eu conseguir compreender, com os exemplos ficou melhor ainda.
Existe todo uma maracutaia que fica escondida e que pela minha falta de logica e vivencia com o JS talvez eu ainda não esteja conseguindo pegar de primeira rsrsrs

Mas vamos adiante!

**Comment by fdaciuk** [comment]
Fica tranquilo, é assim mesmo! Com o tempo e praticando bastante você vai pegando, é assim mesmo que funciona o aprendizado :)

Mas seguindo para finalizar:

Quando você faz uma captura - usando parênteses - na regex, então o método `replace` vai passar os parâmetros para a função na seguinte ordem:
- no primeiro parâmetro vai ser o valor que casou com a regex toda;
- nos parâmetros subsequentes, ele vai passar todos os valores que casaram com as capturas. Se você tiver 1 captura, ele passa mais 1 parâmetro. Se tiver 3 capturas, como no exemplo do desafio, ele vai passar mais 3 parâmetros, entendeu?

Então seria algo assim:

```js
var str = 'No dia 10 de julho de 1983 aconteceu algo que não aconteceu no dia 22 de julho de 1984';
str.replace(/(\d\d) de (junho|julho) de (\d\d\d\d)/, function (allMatch, day, month, year) {
  console.log('allMatch:', allMatch);
  console.log('day: ', day);
  console.log('month:', month);
  console.log('year:', year);
  return day + '/' + month + '/' + year;
});
```

Se você executar o código acima no console, vai ver o seguinte resultado:

```
allMatch: 10 de julho de 1983
day:  10
month: julho
year: 1983
"No dia 10/julho/1983 aconteceu algo que não aconteceu no dia 22 de julho de 1984"
```

_O que aconteceu?_

Bom, o primeiro parâmetro foi a captura que casou com a regex inteira. Os outros parâmetros (`day`, `month` e `year`), foram as variáveis que casaram com as **capturas** que fizemos com os parênteses na regex.

_O que o `replace` vai substituir?_

O que foi pego na regex **geral**.

_E qual valor será usado para substituir o que ele casou com a regex?_

O retorno da função!

Veja que retornamos na função a data no formato `day + '/' + month + '/' + year`.

Ou seja: 
- usamos o primeiro parâmetro do método `replace` para casar com uma parte da string que queremos que seja substituída;
- com a função, temos acesso à string que casou com a regex que usamos e à todos os _matches_ das capturas que fizemos;
- e usamos o retorno da função para substituir pelo valor que queríamos :)

Mas perceba que no texto temos 2 datas no formato que a regex está buscando, mas só a primeira foi substituída. Por que?

Porque não fizemos uma busca global na regex! Se mudarmos nossa regex, adicionando a _flag_ de _global_, todas as datas no texto serão substituídas:

```js
var str = 'No dia 10 de julho de 1983 aconteceu algo que não aconteceu no dia 22 de julho de 1984';
str.replace(/(\d\d) de (junho|julho) de (\d\d\d\d)/g, function (allMatch, day, month, year) {
  console.log('allMatch:', allMatch);
  console.log('day: ', day);
  console.log('month:', month);
  console.log('year:', year);
  return day + '/' + month + '/' + year;
});
```

Agora veja que a função foi executada 2 vezes pelo método replace, porque ele casou com as 2 datas que tínhamos:

```
allMatch: 10 de julho de 1983
VM965:4 day:  10
VM965:5 month: julho
VM965:6 year: 1983
VM965:3 allMatch: 22 de julho de 1984
VM965:4 day:  22
VM965:5 month: julho
VM965:6 year: 1984
"No dia 10/julho/1983 aconteceu algo que não aconteceu no dia 22/julho/1984"
```

E no final, ele nos retorna a nova string, com a modificação que queríamos :)

Ficou mais claro agora? :)

**Comment by saintsfall** [comment]
Sim! Ficou mais claro, alguns nós mentais foram desatados e apesar de ter que ler e reler pra poder pegar o processo como um todo já da pra sentir que estou aprendendo e não simplesmente assistindo os videos.

Valeu @fdaciuk pela paciência e serenidade em explicar temas tão complexos.

**Comment by fdaciuk** [comment]
Show @saintsfall! :heart: 

Qualquer dúvida, fique à vontade pra perguntar, o curso é pra isso mesmo: pra aprender **DE VERDADE** :D
