### ISSUE TITLE
Challenge-28 - Problemas com API do viacep

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2048]
Olá professor. 

Não estou conseguindo fazer o código abaixo retornar o `console.log('data error', data);`  
quando digito um cep inválido.  

```JAVASCRIPT 
  function fillCepFields() {
    var data = parseData();
    if(!data)
      return console.log('data error', data);
    appendToField('[data-js="field-logradouro"]', data.logradouro);
    appendToField('[data-js="field-bairro"]', data.bairro);
    appendToField('[data-js="field-estado"]', data.uf);
    appendToField('[data-js="field-cidade"]', data.localidade);
    appendToField('[data-js="field-cep"]', data.cep);
  }

  function parseData() {
    var result;
    try {
      result = JSON.parse(ajax.responseText);
    }
    catch(e) {
      result = null;
    }
    return result;
  }
```

O esperado era que um cep inválido retornasse 'data error null', mas  
não é o que acontece:  

![image](https://user-images.githubusercontent.com/29297788/32587782-7fae1356-c4f1-11e7-9e3e-79aa8f9664a2.png)

É exatamente a mesma técnica que vc usou na aula [29, parte 03](https://www.udemy.com/curso-javascript-ninja/learn/v4/t/lecture/7054868?start=0) aos 10m. 

Código completo: 

```JAVASCRIPT 
(function(win, doc) {
  'use strict';

  function DOM(elements) {
    this.element = doc.querySelectorAll(elements);
  }

  DOM.prototype.on = function on(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.addEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.off = function off(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.removeEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.get = function get() {
    return this.element;
  };

  DOM.prototype.forEach = function forEach() {
    Array.prototype.forEach.apply(this.element, arguments);
  };

  DOM.prototype.map = function map() {
    return Array.prototype.map.apply(this.element, arguments);
  };

  DOM.prototype.filter = function filter() {
    return Array.prototype.filter.apply(this.element, arguments);
  };

  DOM.prototype.reduce = function reduce() {
    return Array.prototype.reduce.apply(this.element, arguments);
  };

  DOM.prototype.reduceRight = function reduceRight() {
    return Array.prototype.reduceRight.apply(this.element, arguments);
  };

  DOM.prototype.every = function every() {
    return Array.prototype.every.apply(this.element, arguments);
  };

  DOM.prototype.some = function some() {
    return Array.prototype.some.apply(this.element, arguments);
  };

  function getObjType(obj) {
    return Object.prototype.toString.call(obj);
  }

  DOM.prototype.isArray = function isArray(obj) {
    return getObjType(obj) === '[object Array]';
  };

  DOM.prototype.isObject = function isObject(obj) {
    return getObjType(obj) === '[object Object]';
  };

  DOM.prototype.isFunction = function isFunction(obj) {
    return getObjType(obj) === '[object Function]';
  };

  DOM.prototype.isNumber = function isNumber(obj) {
    return getObjType(obj) === '[object Number]';
  };

  DOM.prototype.isString = function isString(obj) {
    return getObjType(obj) === '[object String]';
  };

  DOM.prototype.isBoolean = function isBoolean(obj) {
    return getObjType(obj) === '[object Boolean]';
  };

  DOM.prototype.isNull = function isNull(obj) {
    return getObjType(obj) === '[object Null]'
    || getObjType(obj) === '[object Undefined]';
  };

  var $formCep = new DOM('[data-js="form-cep"]');
  var $inputCep = new DOM('[data-js="input-cep"]');
  var ajax = new XMLHttpRequest();

  $formCep.on('submit', handleFormSubmit);

  function handleFormSubmit(e) {
    e.preventDefault();
    ajax.open('GET', getClearUrl());
    ajax.send();
    ajax.addEventListener('readystatechange', handleStateChange);
  }

  function getClearUrl() {
    return 'https://viacep.com.br/ws/[CEP]/json/'.replace('[CEP]', $inputCep.get()[0].value.replace(/\D+/g, ''));
  }

  function handleStateChange() {
    if(isRequestOk()) {
      fillCepFields();
    }
  }

  function fillCepFields() {
    var data = parseData();
    if(!data)
      return console.log('data error', data);
    appendToField('[data-js="field-logradouro"]', data.logradouro);
    appendToField('[data-js="field-bairro"]', data.bairro);
    appendToField('[data-js="field-estado"]', data.uf);
    appendToField('[data-js="field-cidade"]', data.localidade);
    appendToField('[data-js="field-cep"]', data.cep);
  }

  function parseData() {
    var result;
    try {
      result = JSON.parse(ajax.responseText);
    }
    catch(e) {
      result = null;
    }
    return result;
  }

  function appendToField(selectedField, dataInfo) {
    var field = new DOM(selectedField);
    field.get()[0].appendChild(createNewInfoP(dataInfo));
  }

  function createNewInfoP(text) {
    var newP = doc.createElement('p');
    newP.textContent = text;
    return newP;
  }

  function isRequestOk() {
    return ajax.readyState === 4 && ajax.status === 200;
  }

})(window, document);
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Na verdade isso é um problema de alguma atualização que foi feita no Via CEP. Agora, ao dar algum erro, ele tenta fazer um redirect. E acaba exibindo o erro no console. Se você olhar na aba `Network` do DevTools, vai ver que ele dá o erro no request e depois faz um redirect.

Não tem muito o que a gente fazer nesse caso. Recomendo usar [essa outra API](https://apicep.com/api-de-consulta/) que está funcionando certinho :)

**Comment by Roger-Melo** [comment]
Entendi. Valeu professor!

**Comment by Roger-Melo** [comment]
Professor, acho que essa api também está com defeito, ou eu estou fazendo algo errado.  

Quando digito o cep de exemplo da página inicial deles, funciona normalmente: 

![image](https://user-images.githubusercontent.com/29297788/32641325-594b7fd2-c5b4-11e7-881f-585fe778c355.png)

Mas se eu digitar o cep da minha rua, o textContent dos span desaparecem: 

![image](https://user-images.githubusercontent.com/29297788/32641344-7f1c27a2-c5b4-11e7-80d9-d7cacf630ea5.png)

Se eu digitar qualquer coisa no input, dá na mesma. Ou seja, o try/catch não é executado: 

![image](https://user-images.githubusercontent.com/29297788/32641381-bb8d3618-c5b4-11e7-8afa-ee9a58587841.png)

Código completo abaixo:  

```JAVASCRIPT 
(function(win, doc) {
  'use strict';
  
  function DOM(elements) {
    this.element = doc.querySelectorAll(elements);
  }

  DOM.prototype.on = function on(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.addEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.off = function off(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.removeEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.get = function get() {
    return this.element;
  };

  DOM.prototype.forEach = function forEach() {
    Array.prototype.forEach.apply(this.element, arguments);
  };

  DOM.prototype.map = function map() {
    return Array.prototype.map.apply(this.element, arguments);
  };

  DOM.prototype.filter = function filter() {
    return Array.prototype.filter.apply(this.element, arguments);
  };

  DOM.prototype.reduce = function reduce() {
    return Array.prototype.reduce.apply(this.element, arguments);
  };

  DOM.prototype.reduceRight = function reduceRight() {
    return Array.prototype.reduceRight.apply(this.element, arguments);
  };

  DOM.prototype.every = function every() {
    return Array.prototype.every.apply(this.element, arguments);
  };

  DOM.prototype.some = function some() {
    return Array.prototype.some.apply(this.element, arguments);
  };

  function getObjType(obj) {
    return Object.prototype.toString.call(obj);
  }

  DOM.prototype.isArray = function isArray(obj) {
    return getObjType(obj) === '[object Array]';
  };

  DOM.prototype.isObject = function isObject(obj) {
    return getObjType(obj) === '[object Object]';
  };

  DOM.prototype.isFunction = function isFunction(obj) {
    return getObjType(obj) === '[object Function]';
  };

  DOM.prototype.isNumber = function isNumber(obj) {
    return getObjType(obj) === '[object Number]';
  };

  DOM.prototype.isString = function isString(obj) {
    return getObjType(obj) === '[object String]';
  };

  DOM.prototype.isBoolean = function isBoolean(obj) {
    return getObjType(obj) === '[object Boolean]';
  };

  DOM.prototype.isNull = function isNull(obj) {
    return getObjType(obj) === '[object Null]'
    || getObjType(obj) === '[object Undefined]';
  };

  var $formCep = new DOM('[data-js="form-cep"]');
  var $inputCep = new DOM('[data-js="input-cep"]');
  var ajax = new XMLHttpRequest();

  $formCep.on('submit', handleFormSubmit);

  function handleFormSubmit(e) {
    e.preventDefault();
    ajax.open('GET', getClearUrl());
    ajax.send();
    ajax.addEventListener('readystatechange', handleStateChange);
  }

  function getClearUrl() {
    return 'http://apps.widenet.com.br/busca-cep/api/cep/<cepCode>.json'.replace(
      '<cepCode>',
      $inputCep.get()[0].value.replace(/\D+/g, '')
    );
  }

  function handleStateChange() {
    if(isRequestOk()) {
      fillCepFields();
    }
  }

  function fillCepFields() {
    var data = parseData();
    if(!data) {
      return console.log('data error', data);
    }
    var $logradouro = new DOM('[data-js="info-logradouro"]');
    var $bairro = new DOM('[data-js="info-bairro"]');
    var $estado = new DOM('[data-js="info-estado"]');
    var $cidade = new DOM('[data-js="info-cidade"]');
    var $cep = new DOM('[data-js="info-cep"]');
    $logradouro.get()[0].textContent = data.address;
    $bairro.get()[0].textContent = data.district;
    $estado.get()[0].textContent = data.state;
    $cidade.get()[0].textContent = data.city;
    $cep.get()[0].textContent = data.code;
  }

  function parseData() {
    var result;
    try {
      result = JSON.parse(ajax.responseText);
    }
    catch(e) {
      result = null;
    }
    return result;
  }

  function isRequestOk() {
    return ajax.readyState === 4 && ajax.status === 200;
  }

})(window, document);
```

**Comment by Roger-Melo** [comment]
Professor, acho que essa api também está com defeito, ou eu estou fazendo algo errado.  

Quando digito o cep de exemplo da página inicial deles, funciona normalmente: 

![image](https://user-images.githubusercontent.com/29297788/32641325-594b7fd2-c5b4-11e7-881f-585fe778c355.png)

Mas se eu digitar o cep da minha rua, o textContent dos span desaparecem: 

![image](https://user-images.githubusercontent.com/29297788/32641344-7f1c27a2-c5b4-11e7-80d9-d7cacf630ea5.png)

Se eu digitar qualquer coisa no input, dá na mesma. Ou seja, o try/catch não é executado: 

![image](https://user-images.githubusercontent.com/29297788/32641381-bb8d3618-c5b4-11e7-8afa-ee9a58587841.png)

Código completo abaixo:  

```JAVASCRIPT 
(function(win, doc) {
  'use strict';
  
  function DOM(elements) {
    this.element = doc.querySelectorAll(elements);
  }

  DOM.prototype.on = function on(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.addEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.off = function off(eventName, callback) {
    Array.prototype.forEach.call(this.element, function(element) {
      element.removeEventListener(eventName, callback, false);
    });
  };

  DOM.prototype.get = function get() {
    return this.element;
  };

  DOM.prototype.forEach = function forEach() {
    Array.prototype.forEach.apply(this.element, arguments);
  };

  DOM.prototype.map = function map() {
    return Array.prototype.map.apply(this.element, arguments);
  };

  DOM.prototype.filter = function filter() {
    return Array.prototype.filter.apply(this.element, arguments);
  };

  DOM.prototype.reduce = function reduce() {
    return Array.prototype.reduce.apply(this.element, arguments);
  };

  DOM.prototype.reduceRight = function reduceRight() {
    return Array.prototype.reduceRight.apply(this.element, arguments);
  };

  DOM.prototype.every = function every() {
    return Array.prototype.every.apply(this.element, arguments);
  };

  DOM.prototype.some = function some() {
    return Array.prototype.some.apply(this.element, arguments);
  };

  function getObjType(obj) {
    return Object.prototype.toString.call(obj);
  }

  DOM.prototype.isArray = function isArray(obj) {
    return getObjType(obj) === '[object Array]';
  };

  DOM.prototype.isObject = function isObject(obj) {
    return getObjType(obj) === '[object Object]';
  };

  DOM.prototype.isFunction = function isFunction(obj) {
    return getObjType(obj) === '[object Function]';
  };

  DOM.prototype.isNumber = function isNumber(obj) {
    return getObjType(obj) === '[object Number]';
  };

  DOM.prototype.isString = function isString(obj) {
    return getObjType(obj) === '[object String]';
  };

  DOM.prototype.isBoolean = function isBoolean(obj) {
    return getObjType(obj) === '[object Boolean]';
  };

  DOM.prototype.isNull = function isNull(obj) {
    return getObjType(obj) === '[object Null]'
    || getObjType(obj) === '[object Undefined]';
  };

  var $formCep = new DOM('[data-js="form-cep"]');
  var $inputCep = new DOM('[data-js="input-cep"]');
  var ajax = new XMLHttpRequest();

  $formCep.on('submit', handleFormSubmit);

  function handleFormSubmit(e) {
    e.preventDefault();
    ajax.open('GET', getClearUrl());
    ajax.send();
    ajax.addEventListener('readystatechange', handleStateChange);
  }

  function getClearUrl() {
    return 'http://apps.widenet.com.br/busca-cep/api/cep/<cepCode>.json'.replace(
      '<cepCode>',
      $inputCep.get()[0].value.replace(/\D+/g, '')
    );
  }

  function handleStateChange() {
    if(isRequestOk()) {
      fillCepFields();
    }
  }

  function fillCepFields() {
    var data = parseData();
    if(!data) {
      return console.log('data error', data);
    }
    var $logradouro = new DOM('[data-js="info-logradouro"]');
    var $bairro = new DOM('[data-js="info-bairro"]');
    var $estado = new DOM('[data-js="info-estado"]');
    var $cidade = new DOM('[data-js="info-cidade"]');
    var $cep = new DOM('[data-js="info-cep"]');
    $logradouro.get()[0].textContent = data.address;
    $bairro.get()[0].textContent = data.district;
    $estado.get()[0].textContent = data.state;
    $cidade.get()[0].textContent = data.city;
    $cep.get()[0].textContent = data.code;
  }

  function parseData() {
    var result;
    try {
      result = JSON.parse(ajax.responseText);
    }
    catch(e) {
      result = null;
    }
    return result;
  }

  function isRequestOk() {
    return ajax.readyState === 4 && ajax.status === 200;
  }

})(window, document);
```

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! No caso dessa outra API, eles já fazem tratamento de erro, e não enviam um status de erro, eles sempre mandam o status 200.

Então, **para essa API**, para saber se o endereço não existe, você precisa verificar pela propriedade `status`. Se o `status` for `1`, o resultado está OK. Se tiver erro, ele manda um `status` igual a zero :)

**Comment by Roger-Melo** [comment]
Valeu, professor!

**Comment by fdaciuk** [comment]
:metal:

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Vou deixar essa issue aberta como dica, pois vários alunos estão tendo o mesmo problema :D

**Comment by Roger-Melo** [comment]
Show!!!

**Comment by DarioDias** [comment]
Muito boa resposta! Aproveito o tópico para tirar uma duvida.
Vocês conseguiram pegar o JSON gerado pela api de maneira assíncrona? Só consigo pegar os dados gerados de maneira síncronas, usando o false no terceiro parâmetro do ajax.open. @Roger-Melo  @fdaciuk

**Comment by Bruno-hsc** [comment]
Olá, o meu está dando erro, estou na parte 2
o retorno do responseText está diferente, nao traz as infomações

`(function(win,doc){
'use strict';
 function DOM(elements){
   this.element = doc.querySelectorAll(elements);
 }

 DOM.prototype.on = function on(eventType,callback){
   Array.prototype.forEach.call(this.element, function(element){
     element.addEventListener(eventType, callback,false);
   });
 };
 DOM.prototype.off = function off(eventType,callback){
   Array.prototype.forEach.call(this.element, function(element){
     element.removeEventListener(eventType, callback,false);
   });
 };
 DOM.prototype.get = function get(){
   return this.element;
 };

 DOM.prototype.forEach = function forEach(){
   return Array.prototype.forEach.apply(this.element, arguments);
 };

 DOM.prototype.map = function map(){
   return Array.prototype.map.apply(this.element, arguments);
 };

 DOM.prototype.filter = function filter(){
   return Array.prototype.filter.apply(this.element, arguments);
 };

 DOM.prototype.reduce = function reduce(){
   return Array.prototype.reduce.apply(this.element, arguments);
 };

 DOM.prototype.reduceRight = function reduceRight(){
   return Array.prototype.reduceRight.apply(this.element, arguments);
 };

 DOM.prototype.every = function every(){
   return Array.prototype.every.apply(this.element, arguments);
 };

 DOM.prototype.some = function some(){
   return Array.prototype.some.apply(this.element, arguments);
 };


 var $a = new DOM('[data-js="link"]');

 DOM.prototype.isArray = function isArray(param){
   return Object.prototype.toString.call(param) === '[object Array]';
 }

 DOM.prototype.isObject = function isObject(param){
   return Object.prototype.toString.call(param) === '[object Object]';
 }

 DOM.prototype.isFunction = function isFunction(param){
   return Object.prototype.toString.call(param) === '[object Function]';
 }

 DOM.prototype.isNumber = function isNumber(param){
   return Object.prototype.toString.call(param) === '[object Number]';
 }

 DOM.prototype.isString = function isString(param){
   return Object.prototype.toString.call(param) === '[object String]';
 }

 DOM.prototype.isBoolean = function isBoolean(param){
   return Object.prototype.toString.call(param) === '[object Boolean]';
 }

 DOM.prototype.isNull = function isNull(param){
   return Object.prototype.toString.call(param) === '[object Null]'
   || Object.prototype.toString.call(param) === '[object Undefined]';
 }

var $formCep = new DOM('[data-js="form_cep"]');
$formCep.on('submit', handleSubmitFormCep);//manipular o submit do form

var $formCEP = new DOM('[data-js="form_cep"]');
var $inputCEP = new DOM('[data-js="input_cep"]');

var ajax = new XMLHttpRequest();
$formCep.on('submit', handleSubmitFormCep);

function handleSubmitFormCep(event){
  event.preventDefault();
  console.log($inputCEP.get()[0].value);
  var url = 'http://apps.widenet.com.br/busca-cep/api/[cep].json?code=06233-030'.replace(
    '[cep]');
  ajax.open('GET',url);
  ajax.send();
  ajax.addEventListener('readystatechange', handleReadyStateChange);
}

function handleReadyStateChange(){
  if(ajax.readyState === 4 && ajax.status === 200){
    console.log('Popular formulario', ajax.responseText);
  }
  console.log('Carregando...');
}



}(window,document));`

**Comment by Bruno-hsc** [comment]
![sem titulo](https://user-images.githubusercontent.com/22350757/39971250-477d5d9c-56ce-11e8-8d24-42f6f0adaa37.png)

**Comment by fdaciuk** [comment]
Oi @Bruno-hsc! Provavelmente é o formato que você está usando a URL:
```
'http://apps.widenet.com.br/busca-cep/api/[cep].json?code=06233-030'.replace(
'[cep]');
```

Veja que tem um `[cep].json` ali, e você faz o replace do `[cep]`, mas também tem o `code=06233-030`, que seria um cep fixo. O valor que você precisa fazer o `replace` deve ser no número do CEP. o `cep.json` deve permanecer assim, sem os colchetes =)

O correto seria:

```
'http://apps.widenet.com.br/busca-cep/api/cep.json?code=[cep]'.replace('[cep]', '06233-030');
```

**Comment by fdaciuk** [comment]
@Roger-Melo já coloquei uma orientação na aula, falando sobre o problema, e linkando essa issue. Vou fechar ela por enquanto, mas se precisar de algo, só avisar :D
