### ISSUE TITLE
Challenge-28 - get()[0]

### ISSUE THREAD

**Issue by virginiarcruz** [da2k/curso-javascript-ninja#2050]
Fernando,

Estou com uma dúvida em relação a todas as vezes que é necessário para pegar o valor do item chamado, fazer por:

`$inputCEP.get()[0]`

O get() e o indice [0], seriam dos métodos do DOM que fizemos nos exercícios passados ou é necessário adicionar sempre que quisermos saber o valor destes itens?

Não entendi muito bem.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! =)

Na verdade, o que acontece é o seguinte:

Nós criamos um construtor chamado `DOM`, que usamos para facilitar a manipulação de DOM. Mas esse construtor tem seus próprios métodos para manipular os elementos.

Quando precisamos usar algum método que seja específico de um elemento HTML, e nós não temos esse método normalizado na nossa lib `DOM`, nós precisamos pegar a referência direta ao elemento do DOM para usar esse método.

No caso, o método `get` da nossa lib retorna todos os elementos que foram selecionados pelo seletor que usamos ao criar um novo objeto, com `new DOM(seletor)`.

Como nós usamos o `querySelectorAll` para pegar os elementos, ele sempre vai retornar uma NodeList pra gente, nunca um elemento só. Então, para pegar o primeiro elemento da NodeList, nós usamos a mesma sintaxe que usamos no array: o `[0]`.

Ficou claro? :)

**Comment by fdaciuk** [comment]
Para fazer um teste, você pode tentar pegar um elemento da tela com `querySelector`, e depois pegar o mesmo elemento com `querySelectorAll`. Veja que o `querySelector` sempre retorna o primeiro elemento que ele encontra.

Já o `querySelectorAll` retorna todos os elementos, em uma NodeList, que é como se fosse um array (é um _Array like_) =)

**Comment by virginiarcruz** [comment]
Massa @fdaciuk 
Agora entendi que entra no get da library que criamos.

Obrigada.

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
