### ISSUE TITLE
O 3º vídeo da aula 20 esta sem áudio!

### ISSUE THREAD

**Issue by DSouzasas86** [da2k/curso-javascript-ninja#2052]
O 3º vídeo da aula 20 esta com problema no áudio. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DSouzasas86! O áudio desse vídeo realmente falhou em algumas partes, mas dá uma olhada que, na sequência do segundo vídeo, antes de entrar o áudio, tem um documento com a explicação textual do que eu estou falando naquela parte, ok? :)

Qualquer dúvida me avise! :D
