### ISSUE TITLE
[desafio 5]

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#2055]
Escreva aqui sua dúvida
ola
 pq nao ta dando certo essta resposta??
> var numero = 20;
undefined
> while( numero <= 30){
... (numero);
... numero++
... }
30
>

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! O que você esperava que acontecesse nesse caso? Você queria exibir o número? Para isso, ao invés de passar `(numero)` dentro do `while`, você precisa dizer o que quer fazer com ele.. no caso, se quer somente exibir no console, pode usar o método `console.log()`, e passar a variável `numero` como parâmetro que os números serão exibidos :)

Era isso que você queria saber? Qualquer coisa avisa ae :)

**Comment by fdaciuk** [comment]
Oi @leoigel! Vou fechar a issue, mas se tiver qualquer problema relacionado, só avisar que a gente reabre, ok? :)
