### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by ivanwhm** [da2k/curso-javascript-ninja#2056]
Olá Fernando, tudo bem?
Existe como você liberar o acesso aos slides do curso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ivanwhm! Tudo certo, e contigo? :)

Me passa, por favor, via mensagem privada lá na Udemy, o seu e-mail que eu te dou acesso aos slides, ok? :)

**Comment by ivanwhm** [comment]
Feito
