### ISSUE TITLE
Métodos do DOM

### ISSUE THREAD

**Issue by virginiarcruz** [da2k/curso-javascript-ninja#2082]
Fernando,

Estou tentando utilizar os métodos do DOM que criamos mas acho que não entendi bem como fazer.
Por exemplo: 
Quero pegar todos os inputs do form. Achei que pudesse pegar com o método do forEach que temos. Mas não estou sabendo fazer de forma correta.

```
 DOM.prototype.forEach = function forEach() {
    return Array.prototype.forEach.apply(this.element, arguments);
  }

  DOM.prototype.map = function forEach() {
    return Array.prototype.map.apply(this.element, arguments);
  }

  DOM.prototype.reduce = function forEach() {
    return Array.prototype.reduce.apply(this.element, arguments);
  }

```

Como faço pra usar nesse caso? Algum desses 3 métodos?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! Vamos lá :)

Como esses métodos estão no `prototype` da função `DOM`, você consegue usar eles ao criar um objeto com o `DOM`:

```js
var $lis = new DOM('li');
$lis.forEach(function ($li) {});
```

Aí você usa eles da mesma forma que usa os métodos de array :)

Ficou claro?

**Comment by virginiarcruz** [comment]
Opa @fdaciuk  entendi!
Ficou claro sim, é tanta informação que as vezes a solução é tão simples, mas fico querendo dificultar heheh

Obrigada.

**Comment by fdaciuk** [comment]
haha! Sem problemas! Essas coisas ficam mais simples com o uso no dia a dia =)
Qualquer coisa avisa ae :)
