### ISSUE TITLE
Condições Ternários

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2087]
Tem algum problema de não utilizar mais if ou else e somente usa Condições Ternários ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! O ternário não substitui o `if / else` em todos os casos. A diferença, é que o `if` cria um bloco de código. Já o ternário é uma expressão, que vai te retornar um valor.

Por exemplo:

```js
var isNumberOneBiggerThanNumberTwo = 1 > 2 ? true : false;
```

Veja que a expressão do ternário vai fazer uma comparação. Se essa comparação for verdadeira, a variável `isNumberOneBiggerThanNumberTwo` vai receber `true`. Se for falsa, ela vai receber `false`.

Ainda é possível abreviar sem o uso do ternário, já que a verificação `1 > 2` já vai retornar um booleano:

```js
var isNumberOneBiggerThanNumberTwo = 1 > 2;
```

O ponto aqui é que o ternário é uma expressão, e sempre te retorna um valor. Para fazer a mesma coisa com `if`, você teria que **sobrescrever** o valor da variável `isNumberOnBiggerThanTwo`:

```js
var isNumberOneBiggerThanTwo;
if (1 > 2) {
  isNumberOneBiggerThanTwo = true;
} else {
  isNumberOneBiggerThanTwo = false;
}
```

Veja que o `if` só gera um bloco de código, ele não retorna valor algum. Você **não pode**, por exemplo, fazer isso:

```js
var isNumberOneBiggerThanTwo = if (1 > 2) {
  true;
} else {
  false;
}
```

Exatamente porque o `if` não retorna valor algum. Dentro do bloco de código que o `if` gera, você precisa fazer algo com os valores `true` ou `false`, porque eles não serão atribuídos à variável =)

Fora que o ternário **sempre** tem que ter o retorno da condição quando ela for `false`. Já no `if`, o `else` é opcional, e inclusive, desencorajado o seu uso.

Então a regra é: se você precisa comparar valores, e atribuir o resultado dessa comparação à uma variável, ou retornar em uma função, e você tem valores a serem retornados para os dois casos (true ou false), use ternário.

Já no caso de precisar só de um bloco de código, e não um valor retornado por uma expressão, use o `if`. :)

Ficou claro?

**Comment by grodrigues** [comment]
Sim Ficou bem claro. Obrigado

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, avisa ae :)
