### ISSUE TITLE
Utilização do Let

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2094]
É possível utilizar let no lugar de var sem utilizar transpiler como babel ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Hoje `let` e `cosnt`, e algumas outras features do ES6 já estão implementadas nos browsers mais modernos, então, dependendo do suporte que você vai dar à sua aplicação, pode usar sim :)

**Comment by grodrigues** [comment]
Muito Obrigado.

**Comment by fdaciuk** [comment]
Nada! Qualquer dúvida, só avisar :)
