### ISSUE TITLE
Nomear Função 

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2095]
É possível nomear uma função depois de ser executada ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Nesse caso não =)
O nome da função é criado de forma estática, ao criar a função, e então é atribuído à propriedade `name`, que não pode ser modificada :)

Por que você precisaria fazer isso?

**Comment by grodrigues** [comment]
Porque já peguei alguns códigos de outros desenvolvedores que não colocaram nome das function e deu  muito problemas e essa função estava no escopo global, que toda aplicação precisava dela.

**Comment by fdaciuk** [comment]
Entendi.. aí você precisa colocar o nome na criação da função =)
Hoje, se você usa uma função como expressão, atribuindo-a à uma variável, os browsers já têm uma implementação de nomeação automática. Se a função for anônima, ela recebe o nome da variável, pra você não precisar ver mensagens de erro do tipo `undefined is not a function`.

Mas no seu caso, se o código estiver no seu projeto, você pode colocar um nome na função se quiser =)

**Comment by grodrigues** [comment]
Muito Obrigado.
