### ISSUE TITLE
Erro SSH

### ISSUE THREAD

**Issue by nibarcellosdev** [da2k/curso-javascript-ninja#2096]
Está dando este erro no meu terminal. Estava conseguindo enviar tudo corretamente, do nada apareceu isso.

ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @nibarcellosdev! Isso normalmente acontece quando você perde a conexão com a internet no momento que tentar fazer pull ou push. Tente novamente pra ver se não foi isso :)
