### ISSUE TITLE
Challenge - 10

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#2105]
Escreva aqui sua dúvida
no comeco deste desafio vc pediu para 
Sem alterar os códigos nos `console.log` abaixo, faça com que o retorno
 +deles seja "true", usando os Wrapper Objects como "conversores" nos valores
 +das variáveis. Analise o que está sendo impresso no console para saber como
 +resolver o problema corretamente.
 +*/
 var five = '5';
 console.log( five + ' é número?', typeof five === 'number' );

pq quando coloquei esta resposta de certo
var five = Number('5') ;
 console.log( five + ' é número?', typeof five === 'number' );
porem o Sr pediu para usar o Wrapper Objects como "conversores" ou seja acrecentar o new... pois ai crio um novo objeto retiro o a string do '5' e acrencento no lugar Number(5)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
