### ISSUE TITLE
Lexical Environments

### ISSUE THREAD

**Issue by nibarcellosdev** [da2k/curso-javascript-ninja#2107]
Você poderia explicar por favor o que seria Lexical Environments e Execution Contexts? 
Obrigado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @nibarcellosdev! Onde você se deparou com esses termos que causou a dúvida? 
Só pra eu entender melhor o que você quer saber =)

**Comment by fdaciuk** [comment]
Oi @nibarcellosdev! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
