### ISSUE TITLE
Dúvida For In

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2112]
Como mostrado na aula quando eu for utilizar o for tenho que colocar o var assim For(var prop in car){}
ou posso colocar assim For( prop in car) ?

@fdaciuk

**Comment by fdaciuk** [comment]
Sempre criar variáveis usando `var`! Em aulas futuras nós vamos ver sobre escopo, e como a criação de variáveis com a palavra chave `var` afeta esse escopo =)

Então sempre use `var` quando criar uma variável =)

**Comment by grodrigues** [comment]
@fdaciuk Obrigado Daciuk

**Comment by fdaciuk** [comment]
Nada! =)
Qualquer coisa avisa ae :D
