### ISSUE TITLE
Niveis no Array

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2140]
Até quanto níveis pode ser criado em um Array ?

@fdaciuk

**Comment by fdaciuk** [comment]
Não tem um limite. Mas como os valores são gravados em memória, enquanto você tiver memória, você pode criar dados em um array =)

Obviamente, isso falando apenas em quantidade. Quando tratamos de qualidade de código, use o que for necessário, quebrando também quando for necessário.

Quando utilizar essa necessidade você aprende com o tempo, e aplicando na prática o que está aprendendo =)

**Comment by LucasGabrielSI** [comment]
Professor teria como corrigir meus exercícios?

Em 24 de nov de 2017 2:20 PM, "Fernando Daciuk" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Oi @LucasGabrielSI! No início de cada aula você pode acompanhar as soluções dos desafios, e ver se você fez certo ou não =)

Qualquer dúvida que você tenha, pode abrir uma nova issue que eu te ajudo, ok? =)
