### ISSUE TITLE
O atributo data-js

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2149]
Olá, professor.  

Eu entendi que o ideal é deixar os atributos `class` apenas para a estilização e `data-js` para JS. Vc pode me dizer quais são os problemas em se usar `id` para capturar e manipular elementos? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! O `id` tem o efeito colateral nos browsers, de gerar uma variável global que aponta para o elemento que tem aquele ID.

Então, para não gerar variáveis globais desnecessárias, o ideal é usar `data-*` para manipulação de DOM via JS, e usar IDs somente para:
- inputs, por conta da acessibilidade do atributo `for` das labels;
- ou quando você quiser fazer âncoras na sua página, você também precisa do ID.

Para todos os outros casos, evite =)

**Comment by Roger-Melo** [comment]
Entendi. Obrigado, professor.
