### ISSUE TITLE
Sobre validações 

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2168]
Olá, professor. 

Fiz o [challenge 31](https://github.com/Roger-Melo/melos-cars/pull/2) e estou em dúvida quanto às validações de inputs do usuário. O código deste app está grande e sem validações. 

É melhor escrever o código inteiro e fazer a validação depois, importando-a de outro documento? 

No caso desse app de carros, o ideal seria fazer um objeto "car" em que as propriedades sejam os valores dos inputs e validá-los à partir disso? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Sobre essa parte de validações não entramos muito em detalhes para esse app específico no curso, mas você pode fazer como achar mais fácil =)

Minha recomendação é: primeiro faça funcionar. Com o app funcionando, você vai melhorando ele aos poucos.

Se quiser fazer um terceiro arquivo, como uma lib para validações, fique à vontade =)

Mas tente fazer da forma mais simples possível no início. Depois de funcionando o app e as validações, você bate o olho no código e vai vendo o que pode ser melhorado pra ir refatorando =)

Esse é um trabalho que você vai conseguir pegar na prática mesmo!

Quanto mais você praticar, mais vai ficar claro qual é o "melhor caminho" para fazer as coisas funcionarem =)

Então fique à vontade para desenvolver como você achar mais simples, usando o conhecimento que você adquiriu até agora.

Se tiver dúvidas enquanto estiver desenvolvendo, pode abrir issues que eu vou te ajudando, ok? =)

**Comment by Roger-Melo** [comment]
Tranquilo, professor. Obrigado.
