### ISSUE TITLE
challenge - 10

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#2176]
Escreva aqui sua dúvida
to meio confuso pois gostaria de saber o pq o Sr diz que no exercicio ("Agora vamos criar a calculadora.
- Crie uma função chamada `calculator`, que receberá como parâmetro um
operador;
- Se o operador não for válido, a função deve retornar "false";
- Se o operador for válido, retornar uma segunda função que receberá dois
parâmetros;
- Se algum dos parâmetros não for um número, retornar "false";
- Senão, retornar o método do objeto "operation" criado acima, baseado no
operador passado para a função "calculator", e passando para esse método
os dois parâmetros da função de retorno de "calculator".)

no final voce diz que `operation[operator](x,y)` e uma function porem eu entendo que o operation e um objeto atribuido a uma variavel e um metodo da function isOperatorValid (operator){
	return !!operation[operator]
}

seila nao entendo, tem como me da uma ajuda??
*/ 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! Deixa eu ver se entendi sua dúvida =)

O `operation` é um objeto, correto? Esse objeto tem alguns métodos, que são as operações `+`, `-`, `*`, `/` e `%`.

Cada um desses métodos é uma função =)

Então, no caso, o `operator` que você recebe na função `isOperatorValid`, precisa ser algum desses operadores. Se isso for verdadeiro, a função retorna `true`. Caso contrário, retorna `false`.

Lembra lá no começo do curso que nós vimos sobre valores _truthy_ e _falsy_?

Quando um valor é `undefined`, o equivalente booleano desse valor é `false`. E para saber o equivalente booleano de algum valor, nós usamos duas exclamações: `!!`.

Por isso, nós checamos se o `operator` passado para a função `isOperatorValid` existe dentro do objeto `operation`.

Se ele existir, ele será uma função, e o equivalente booleano dele será `true`:

```
console.log(!!operation['+']) // true
console.log(!!operation['qualquercoisa']) // false
```

O `qualquercoisa` passado como `operator` retorna `false`, porque o objeto `operation` não tem esse método. Nesse caso, `operation['qualquercoisa']` vai ser `undefined`. Transformando esse valor em booleano, ele retorna false =)

Já o `operation['+']` é uma função. E funções, quando transformamos em booleano com o `!!`, vai retornar `true` =)

Ficou claro? =)

**Comment by fdaciuk** [comment]
Oi @leoigel! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
