### ISSUE TITLE
Aula 32 - parte 02 [Instalando o Express JS ]

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2177]
Olá professor!  

Estou com uma dúvida, vc pode me ajudar? 

Ao instalar o Express, outras pastas além da pasta express foram colocadas  
dentro de `node_modules`, como se eu tivesse instalado esses módulos.  
Isso é normal? 

![image](https://user-images.githubusercontent.com/29297788/33242024-546eb142-d2b5-11e7-8737-077f74235581.png)

![image](https://user-images.githubusercontent.com/29297788/33242037-920284b6-d2b5-11e7-85e7-dda33eda97e9.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! É normal sim, pois o NPM agora coloca todas as dependências direto dentro de `node_modules`. Ele faz isso pra facilitar o gerenciamento, pois se você tiver dois pacotes que contém as mesmas dependências, na mesma versão, ele não instala duas vezes, e sim aproveita o que já está na raiz da `node_modules` =)

**Comment by Roger-Melo** [comment]
Saquei. Obrigado, professor!
