### ISSUE TITLE
Challenge 13

### ISSUE THREAD

**Issue by julioakiyama** [da2k/curso-javascript-ninja#2198]
Escreva aqui sua dúvida
Fala professor!!! Pq esses dois retornam resultados diferentes?

var filter = map.filter(function (item, index){
	return index % 2 === 0;
});

var filter = map.filter(function (item, index){
	return item.id % 2 === 0;
});

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @julioakiyama! No caso do desafio, os `id`s de cada item começam em `1`. Já o `index`, que é o índice do elmento do array que está sendo iterado naquele momento, começa em zero. Por isso você tem resultados diferentes =)

Imagine o seguinte:

```js
var arr = [
  { id: 1 }, // esse objeto tem índice 0
  { id: 2 } // esse objeto tem índice 1
]

// para acessar os respectivos objetos dentro do array, precisamos do índice do array, que começa em zero:

arr[0].id // 1 - veja aqui que o índice "0" do array tem o `id` igual a 1
arr[1].id // 2 - já aqui, o indíce "1" do array (que é o segundo item), tem o `id` igual a 2
```

Ficou claro? =)

**Comment by julioakiyama** [comment]
Thanks for getting back to me!! Pretty clear now
