### ISSUE TITLE
Use Strict

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2204]
Em quais situações eu devo utilizar o use strict ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Sempre use `'use strict'`! Ele vai garantir um ambiente mais seguro quando você estiver desenvolvendo para web =)

Então sempre use IIFE + `'use strict'` =)

**Comment by grodrigues** [comment]
Muito Obrigado =)

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
