### ISSUE TITLE
[Aula 1] Multiplicando por 3

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2221]
E aí, Fernando, tudo bem?

Então, eu estou fazendo a correção do exercício juntamente e me surgiu uma dúvida...
Quando eu fiz a multiplicação por 3 eu tinha feito _"soma * 3"_, dessa maneira estaria incorreta?
Porque eu vi que na correção você coloca um sinal de " = " ficando " *= ".

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! Não é errado não! A forma como eu resolvi foi só pra mostrar que você também tem essa opção, como mostrei na aula =)

A ideia das primeiras aulas não é usar boas práticas, mas sim aprender o que dá ou não pra fazer com a linguagem =)

Então é só pra saber que essa é uma outra opção de multiplicar e atribuir ao mesmo tempo =)

**Comment by garritanoo** [comment]
Entendi.
Com a prática, eu vou melhorando as minhas "boas práticas".

Obrigado.

**Comment by fdaciuk** [comment]
Então.. não necessariamente isso é uma boa prática, mas é apenas para saber que isso também funciona =)

Mas como eu disse: não se preocupe com boas práticas nesse momento. Agora é momento de entender o que você consegue fazer com a linguagem =)

Vamos tratar de boas práticas em aulas futuras =)

E qualquer dúvida, só avisar =)
