### ISSUE TITLE
[Aula 1]Criar função divisao

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2222]
E aí, Fernando tudo bem (novamente)?

Ainda estou na correção do exercício e na questão para criarmos uma função eu montei de maneira diferente chegando ao mesmo resultado.
Gostaria de saber se está correta da maneira que montei ou se seria melhor fazer da maneira que você exemplificou.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! Então, não é errado você resolver de forma diferente não =)
Só pediria pra você tentar resolver apenas com o conhecimento que está vendo em aula, sem usar nada que ainda não foi visto, para que assim você consiga absorver o máximo de conhecimento possível, ok? =)

Se você já programava alguma coisa em JS, é normal que você encontre soluções "melhores", mas o foco dessas primeiras aulas não é isso, mas sim ver as opções que temos dentro da linguagem =)

**Comment by garritanoo** [comment]
Ah sim.
Então, eu nunca programei em JS, mas já me aventurei, então há resquícios de códigos que ainda lembro.
Mas vou tentar fazer da maneira que você indica.

Obrigado.

**Comment by fdaciuk** [comment]
Legal @garritanoo! Agora é momento de entender bem a linguagem e o que é possível fazer com ela :D
