### ISSUE TITLE
Aula de Ajax

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2225]
Bom dia @fdaciuk , qdo tento fazer uma requisição Ajax para um arquivo aparece um erro Cross origin request are only supported for protocol schemes: http,data, chrome, chrome-extensions , https.

não estou usando nenhum servidor.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Para fazer requisições e não ter problemas de CORS, é necessário subir, ao menos, um servidor estático, pois se tentar fazer qualquer request, cada `file:///` estará em uma _origin_ diferente do local atual, então você terá sempre esse problema =)

Na aula eu mostro como subir um servidor estático com Python. Se você tiver ele instalado na sua máquina, seria só rodar:

```
python -m SimpleHTTPServer 9001
```

O `9001` é a porta que você vai acessar no browser. Rodando esse comando na raiz da sua aplicação, onde está o arquivo `index.html`, você pode acessar no browser:

```
http://localhost:9001
```

que você terá acesso ao arquivo `index.html` =)

Se não quiser usar Python, pode usar Node, com o `http-server`. Instale ele de forma global e use. 

A documentação dele está aqui:
https://www.npmjs.com/package/http-server

Acho que é isso! Qualquer dúvida avisa ae =)

**Comment by jhonesgoncal** [comment]
blz vou fazer isso. obrigado. existe alguma maneira de importar o JS em outro. falo isso por causa da lib. para eu não precisar ficar copiando e colando o codigo dela

**Comment by jhonesgoncal** [comment]
esse em python eu tentei mais ele falo que esse simpleHTTPServer não existe

**Comment by fdaciuk** [comment]
Logo você vai chegar na aula onde falamos sobre módulos, e eu vou mostrar como "importar" arquivos =)
Vai com calma que logo você chega lá :D

**Comment by fdaciuk** [comment]
Sobre o python, veja se você colocou exatamente como mostrei, com o primeiro `S` maíusculo =)

**Comment by jhonesgoncal** [comment]
ata, então coloquei sim.

**Comment by jhonesgoncal** [comment]
pra qual versão do python é isso?

**Comment by fdaciuk** [comment]
Hoje eu estou com a `2.7.12`, mas você pode usar o `http-server` se for o caso, é mais simples =)

**Comment by jhonesgoncal** [comment]
C:\Users\SQZ69
λ py -m SimpleHTTPServer 9001
C:\Program Files\Python36\python.exe: No module named SimpleHTTPServer

no meu aqui não funciona se colocar python tem que ser py . ai ele diz que não tem esse modulo

**Comment by fdaciuk** [comment]
Entendi! Provavelmente tem que instalar à parte. Vai de `http-server` que é mais fácil ;)

**Comment by jhonesgoncal** [comment]
esse modulo simplehttp mudou para py -m http.server 3000
