### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2231]
Existe uma maneira de fazer a instalação do gulp apenas no meu projeto sem instalar ele globalmente na minha máquina ?

@fdaciuk

**Comment by samuelsilvadev** [comment]
opa @grodrigues, blz?  E se você instalar sem a flag -g? 

- Entra no projeto
- npm install gulp --save-dev

**Comment by fdaciuk** [comment]
Isso mesmo! Obrigado pela resposta @samuelsilvadev =)

Só pra complementar @grodrigues: para usar o `gulp`, pode ser que, como ele está instalado como _Dev dependency_, você não consiga rodar o comando `gulp` direto na linha de comando.

Tem duas saídas pra isso:
- Criar um _NPM Script_ com o comando gulp, adicionando uma entrada `scripts` no seu `package.json` local, mais ou menos assim:

```json
{
  "scripts": {
    "gulp": "gulp"
  }
}
```

Que você consegue rodar agora, à partir da raiz do seu projeto, o comando `npm run gulp`;

- Ou ainda usando o `npx`, que já vem instalado com o npm5. Se estiver usando essa versão do NPM, você não precisa adicionar o _NPM Script_. Só precisa rodar direto no terminal:

```
npx gulp
```

Se quiser ler mais sobre, tem esse artigo aqui falando sobre o NPX:
https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by grodrigues** [comment]
@fdaciuk Muito Obrigado

**Comment by jhonesgoncal** [comment]
qual aula o professor mostra gulp?
