### ISSUE TITLE
Pull request acumulados no Git

### ISSUE THREAD

**Issue by silvioCoelho** [da2k/curso-javascript-ninja#224]
cara, eu mandei o pull request do desafio dessa semana, mas foi um monte de coisa junta que parece que esta acumulando, como eu faço pra remover esses pull requests?
só pra ver se vc entende oq eu quero dizer
silvioCoelho added some commits 7 days ago
 @silvioCoelho	Challenge-15	0319652
 @silvioCoelho	Challenge-15	e78f465
 @silvioCoelho	Challenge-15	79bc596
 @silvioCoelho	Merge remote-tracking branch 'upstream/master'	908c495
 @silvioCoelho	Challenge-17	bb9fb11

**Comment by fdaciuk** [comment]
Opa, eae @silvioCoelho  :)

Tem que ver como você está fazendo para atualizar o repositório. O que você deveria fazer:

Ao finalizar um desafio, faça o commit e envie para o seu Github:

```
git add .
git commit -m "Challenge xx"
git push origin challenge-xx
```

Isso vai fazer com que o desafio que você respondeu seja comitado.

Agora você vai começar um novo desafio, precisa seguir os passos a seguir:

- Vá para a branch master: `git checkout master`
- Faça o fetch do repositório do curso: `git fetch upstream`
- Faça o merge para pegar as atualizações: `git merge upstream/master`
- Crie a branch do desafio que você vai resolver: `git checkout -b challenge-xx`

E siga os primeiros passos novamente. Assim deve ser feito para cada desafio.

Para corrigir, o que você precisa fazer é:
Imagine que você está fazendo o desafio 16, mas tem correções do desafio 15. Então você precisa garantir que não tem nada pra commitar na branch do desafio 16, rodando o comando:

```
git status
```

Se não aparecer nada, significa que está tudo ok.

Se tiver algum arquivo alterado, só faça o `git add .` e `git commit -m "Challenge 16"`, para manter esse repositório atualizado.

Mude para o repositório do desafio 15: `git checkout challenge-15`

Faça as alterações no desafio 15, faça o add, commit, e push para o challenge-15.

---

Não há problema se ficar alguns commits acumulados. Você só precisa ter certeza que está enviando o desafio certo na branch certa :)

Se tiver mais alguma dúvida me avise :)
