### ISSUE TITLE
Challenge 02

### ISSUE THREAD

**Issue by worldrules** [da2k/curso-javascript-ninja#2254]
Mano , to com um problema nessa questão . Até peguei algumas respostas da galera por ai , sempre me trás um errinho de syntax.

--->Crie uma função com as seguintes características:
1. A função deve receber 3 argumentos.
2. Se somente um argumento for passado, retorne o valor do argumento.
3. Se dois argumentos forem passados, retorne a soma dos dois argumentos.
4. Se todos os argumentos forem passados, retorne a soma do primeiro com o segundo, e o resultado, dividido pelo terceiro.
5. Se nenhum argumento for passado, retorne o valor booleano `false`.
6. E ainda, se nenhuma das condições acima forem atendidas, retorne `null`.
*/

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @worldrules! Me mostra qual problema você está tendo pra eu conseguir te ajudar =)

**Comment by fdaciuk** [comment]
Se possível, me manda uma mensagem lá pela página da Udemy pra eu achar teu user no curso =)

**Comment by worldrules** [comment]
@fdaciuk eu vou , assistir o vídeo deve ter correção , eu peguei essa resposta da galera 

function novaFuncao(a, b, c){
     if ( a && !b && !c ) {
         return a;
     } else if ( a && b && !c ) {
         return a + b;
     } else if (a && b && c) {
         return (a + b)/c
     } else if (!a || !b || !c ) {
          return false;
     } else {
         return null;
     }
 }

mais queria fazer o meu próprio . No video tu deve falar algo sobre essas questões !! vlw

**Comment by fdaciuk** [comment]
Fazer o seu próprio como assim? Dá uma olhada na correção, pode ajudar sim =)
