### ISSUE TITLE
problema ao clonar o reposítorio com git 

### ISSUE THREAD

**Issue by LucasGabrielSI** [da2k/curso-javascript-ninja#2255]
quando tento dar um git clone me gera esse erro:

Cloning into 'curso-javascript-ninja'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@fdaciuk

**Comment by grodrigues** [comment]
@LucasGabrielSI  Qual é o sistema operacional da sua máquina ?

**Comment by grodrigues** [comment]
@LucasGabrielSI  Você fez a instalação do git na sua máquina ? Porque antes de clonar o repositório tem que está instalado o git na sua máquina.

**Comment by LucasGabrielSI** [comment]
Windows 10. Eu consegui resolver o problema, é que eu não tinha configurado
a chave pública.



Em 29 de nov de 2017 3:01 PM, "Gustavo Rodrigues" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Oi @LucasGabrielSI, que bom que resolveu! =)
Obrigado pela ajuda @grodrigues =)
