### ISSUE TITLE
Regex exec

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2256]
Está lendo a documentação do Regex exec lá no mdn e veio com esse titulo RegExp.prototype.exec().
Você sabe porque os títulos do Regex está com o nome .prototype ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Não sei se você já chegou na aula sobre construtores, mas basicamente o `prototype` é um objeto que você tem disponível para as funções, que permite você criar um construtor, e adicionar métodos nesse construtor que serão compartilhados com todos os objetos criados à partir desse construtor.

No caso da regex, sempre que você cria uma nova regex, seja com a sintaxe literal de `/regex/` ou com o construtor `new RegExp`, a regex criada se torna um objeto do tipo `RegExp`. E nesse objeto você consegue usar qualquer método que foi criado à partir do construtor, como o `exec`, por exemplo =)

Se ainda não chegou lá, mais no final do curso eu mostro isso, aí acredito que vai ficar mais claro =)

**Comment by grodrigues** [comment]
@fdaciuk  Valeu pelo spolier!!! abs

**Comment by fdaciuk** [comment]
:raised_hands:
