### ISSUE TITLE
[Aula 04] Correção do Desafio

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2272]
Opa, Fernando! Tudo bem?
Então, eu estou fazendo a correção do exercício e fiquei com uma dúvida na questão referente a "pessoa fazer 3 aniversários".

Você "chamou" a função 3 vezes para que e pessoa fizesse aniversário.
No entanto, eu apenas coloquei como parâmetro o número 3.

Estaria correto da maneira que eu fiz?

@fdaciuk

**Comment by fdaciuk** [comment]
Como assim @garritanoo? Você diz que passou por parâmetro para o método de fazer aniversário a quantidade de vezes que a pessoa deveria fazer aniversário?

**Comment by garritanoo** [comment]
Justamente isso, @fdaciuk.
Eu fiz fazerAniversario(3);

E quando eu coloquei pessoa.idade; o JS me mostrou exatamente a quantidade de 3 aniversários.

**Comment by fdaciuk** [comment]
Entendi! 
É que o enunciado não pede para passar parâmetro na função `fazerAniversario` =)
Mas não tem problema, não vai dar tanta diferença no final. A ideia é mais ou menos a mesma =)

**Comment by garritanoo** [comment]
Beleza, então!
