### ISSUE TITLE
[Aula 5} Desafio #04

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2283]
Fala, @fdaciuk!
Tudo bem?

Estou fazendo a correção do desafio #04 e na primeira questão eu vi da forma que você montou e deu certo na hora do teste.

Mas quando eu fui fazer sozinho, eu havia montado assim:

var isTruthy =  function (a) {
if (a === true) {
return true;
} else { 
return false.
}

Da maneira que eu montei, eu achei que estava correto.
Quando eu coloco valores falsos, dava resultado falso.
Mas quando eu colocava resultados verdadeiros, dava falso da mesma maneira.

Onde errei?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! O problema com o seu exemplo é que você testa explicitamente se o valor é um booleano. No caso, igual a `true`.

`true` é um tipo de valor _truthy_, mas não representa todos os valores. 
Para entrar nesse `if`, o valor de `a` teria que ser exatamente `true` =)

Lembre que o `if` sempre transforma a expressão passada em booleano. Se o equivalente booleano da expressão for `true`, aí sim ele entra no `if`. Senão ele vai entrar no `false`.

E equivalente booleano é aqueles testes que vimos em aula: temos equivalentes booleanos para valores que sempre vão ser `false`: zero, `null`, `undefined`, string em branco e o próprio `false`.

O equivalente booleano para esses valores - que você consegue obter usando duas exclamações `!!` - vai ser sempre `false`.

Para todos os outros tipos de dados, o equivalente booleano é `true` =)

Ficou claro?

**Comment by garritanoo** [comment]
Ficou sim!
