### ISSUE TITLE
[Challenge-33] removendo um carro do servidor

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2326]
Olá, professor!  

Não estou conseguindo remover um carro do servidor através da placa:  

![image](https://user-images.githubusercontent.com/29297788/33532345-09acc150-d880-11e7-9e8d-e0db89706a81.png)

Quando reinicio o nodemon, dou um refresh no front-end da aplicação e clico  
no botão de remoção do carro, a mensagem `'ok!'` no console aparece:  

![image](https://user-images.githubusercontent.com/29297788/33532388-626e79dc-d880-11e7-8a73-e327ea46c240.png)

Porém, ao atualizar a página novamente, ao invés de não constar nenhum  
carro nela, aparecem dois. Então, devo estar usando o `'DELETE'` de uma  
forma errada, vc pode me ajudar? 

![image](https://user-images.githubusercontent.com/29297788/33532399-83e2aa52-d880-11e7-8c91-1ef293dcfc95.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Passa o link do repositório que você está usando pra eu dar uma olhada no código, mais fácil eu baixar e rodar aqui pra conseguir ajudar =)

**Comment by Roger-Melo** [comment]
Olá, professor. Desculpe, o código está [neste repo](https://github.com/Roger-Melo/melos-cars/pull/7)  

O código do server é o do challenge-33, não o altererei.

**Comment by fdaciuk** [comment]
Opa, legal, já vi aqui seu código =)
Bom, veja que o servidor espera um parâmetro `plate` no `body` da requisição, para comparar com alguma placa cadastrada:
https://github.com/da2k/curso-javascript-ninja/blob/master/challenge-33/server/routes/index.js#L24

No caso, você está mandando uma placa qualquer, mas só o valor, sem a chave `plate`:
https://github.com/Roger-Melo/melos-cars/pull/7/files#diff-0364f57fbff2fabbe941ed20c328ef1aR148

O correto seria enviar dessa forma:
https://github.com/Roger-Melo/melos-cars/pull/7/files#diff-0364f57fbff2fabbe941ed20c328ef1aR150

Já o problema de estar aparecendo dois carros deve ser esse:
https://github.com/Roger-Melo/melos-cars/pull/7/files#diff-0364f57fbff2fabbe941ed20c328ef1aR8

Ao iniciar a sua aplicação, você cria um novo carro. Ou seja: a cada reload, um novo carro será criado, e cada vez vai aparecer mais um se essa chamada de função estiver no `init` :)

**Comment by fdaciuk** [comment]
Outro ponto importante: olhe esse código:
https://github.com/Roger-Melo/melos-cars/pull/7/files#diff-0364f57fbff2fabbe941ed20c328ef1aR139

Percebe o quanto o uso do `parentNode.parentNode` pode ser perigoso se você mudar a sua marcação?

Ao alterar a marcação, você pode mudar quem é o `parentNode` e fazer sua aplicação quebrar.

Para garantir o correto funcionamento, nomeie as `tr`s.

Você pode usar essa função:
https://github.com/Roger-Melo/melos-cars/pull/7/files#diff-0364f57fbff2fabbe941ed20c328ef1aR46

E criar uma identificação específica para cada TR, com `data-js` por exemplo.

Essa mesma identificação você pode adicionar no botão, usando um `data-button` ou algo assim.

Dessa forma, ao clicar no botão, você consegue comparar o `data-button` do botão com o `data-js` da TR, e remover a TR exata, sem precisar fazer "malabarismos" com `parentNode.parentNode`, saca? =)

**Comment by Roger-Melo** [comment]
Professor, acho que eu havia entendido a proposta do exercício de forma errada. Os dados do carro no método POST devem ser baseados no preenchimento do formulário, certo?  

O `registerNewCar()` no método init foi justamente por esse erro. Vou corrigir e refatorar aqui e em breve lhe mostro. Muito obrigado =)

**Comment by fdaciuk** [comment]
Isso mesmo! =)

**Comment by Roger-Melo** [comment]
Olá, professor. 

Refiz praticamente 80% do código, quebrando a cabeça aqui.
Acho que não consegui fazer 100% como vc havia dito, e ainda vou fazer a validação  
para impedir o recadastro de carros repetidos.  

[Nessa issue](https://github.com/da2k/curso-javascript-ninja/issues/2253#issuecomment-349286054), vc recomendou que eu fizesse uma lib com os requests de forma separada, não entendi  
como ela pode ser feita, vc pode explicar novamente?  

[Código atual](https://github.com/Roger-Melo/melos-cars/blob/master/src/js/app.js)

**Comment by fdaciuk** [comment]
Show @Roger-Melo! =)

Bom, a ideia de criar uma lib para fazer requests é basicamente pra não precisar repetir códigos como esses:

1) https://github.com/Roger-Melo/melos-cars/blob/master/src/js/app.js#L23-L26

2) https://github.com/Roger-Melo/melos-cars/blob/master/src/js/app.js#L57-L61

3) https://github.com/Roger-Melo/melos-cars/blob/master/src/js/app.js#L83-L86

4) https://github.com/Roger-Melo/melos-cars/blob/master/src/js/app.js#L160-L163

Veja que a ideia é sempre a mesma: criar um novo objeto, abrir a conexão passando a URL, setar alguns headers se necessário, e enviar os dados.

Você poderia fazer uma lib que abstraia esse comportamento, para que você consiga usar mais ou menos assim:

```js
ajax.get('http://localhost:3000/car', function () {
 // essa função é usada como manipuladora (handler) do evento "readystatechange"
})
```

Para POST e DELETE, onde você precisa enviar um _body_, você pode usar 3 parâmetros:

```js
ajax.delete('http://localhost:3000/car', { plate: 'ABC-1234' }, function () {

})
```

Era isso que eu estava dizendo =)
Claro que vai dar um trabalho você pensar na forma de abstrair isso, pra reutilizar código da forma como eu passei. Da forma que você fez funciona, fique tranquilo =)

É só uma forma de começar a estudar outras formas de abstrair código, reduzindo e isolando repetição, para facilitar alterações futuras =)

Mas no mais é isso cara, parabéns :tada: :tada:

**Comment by Roger-Melo** [comment]
Professor, acho que consegui fazer as [requisições com o 'GET'](https://github.com/Roger-Melo/melos-cars/commit/60ae3861c50eff7ea74c64eef390fc01334877c0).  

Se estiver certo, vou tentar fazer as `'POST'` e `'DELETE'` e juro que  
não nomeio mais parâmetros de `IIFE` com títulos de memes  
internéticos.

**Comment by fdaciuk** [comment]
haha! Boa =)

**Comment by Roger-Melo** [comment]
Acho que [finalizei](https://github.com/Roger-Melo/melos-cars/commit/c9b48f98e775c9fd843fda31d695c7ab2af41e2f), professor.
