### ISSUE TITLE
Não executo a função replaceDate da forma padrão

### ISSUE THREAD

**Issue by Botsiah** [da2k/curso-javascript-ninja#2345]
Escreva aqui sua dúvida
#2344 
Na linha 145 eu não executo a função replaceDate( não uso os parenteses). Por quê?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Botsiah! É que o método `replace` espera que seja passada uma função pra ele. Se você executar, o que vai ser passado é a expressão que a função retorna, entendeu? =)

Seria mais ou menos isso aqui:

O que fizemos:

```js
function replaceDate(){
  return `${arguments[1]}/${getMonthNumber(arguments[2])}/${arguments[3]}`;
}

console.log(text.replace( regexDate, replaceDate));
```

Veja que você cria a função `replaceDate`, e passa a **referência** dessa função para o método `replace`.

Seria o mesmo que você criar a função direto no segundo parâmetro do método `replace`:

```js
console.log(text.replace( regexDate, function (){
  return `${arguments[1]}/${getMonthNumber(arguments[2])}/${arguments[3]}`;
}));
```

O resultado é exatamente o mesmo! Veja que, quando você cria a função direto como expressão no segundo parâmetro do `replace`, você não executa ela =)

E ela não deve ser executada mesmo, pois quem vai executá-la é o método `replace` =)

Eu dei uma explicação mais profunda sobre esse método na issue https://github.com/da2k/curso-javascript-ninja/issues/2044. Dá uma lida e me diga se ficou mais clara a ideia =)

**Comment by fdaciuk** [comment]
E aí @Botsiah? Deu pra entender bem? =)
Qualquer dúvida avisa ae =)
