### ISSUE TITLE
Clousure

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2358]
Escreva aqui sua dúvida

Bom dia Mestre.
na aula vc usa um código mais ou menos assim

```js
var increment = (function(){
	var count = 0;
	return (function(){
		var count = 0;
		return function(){
			count++;
		}
	})();
})()

increment();

```

se fosse sem ser com IIFE não seria a mesma coisa , tipo isso?

```js
var increment = function(){
	var count = 0;
	return function(){
		var count = 0;
		return function(){
			count++;
		}
	}
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! De qual aula estamos falando? Só pra eu ver como é o código aqui =)
Mas tem diferença xD

**Comment by jhonesgoncal** [comment]
na aula 30

**Comment by fdaciuk** [comment]
Legal, peguei aqui o exemplo de como eu tinha feito. Na verdade é um pouco diferente do que você mostrou. O código que foi mostrado no curso é esse:

```js
var increment = (function () {
  var counter = 0;
  return function () {
    return counter++;
  };
})();
```

E a sua pergunta, no caso, seria qual a diferença dessa implementação que eu fiz para a implementação abaixo, correto?

```js
var increment = function () {
  var counter = 0;
  return function () {
    return counter++;
  };
};
```

A diferença é basicamente na forma de executar a função. No exemplo que eu dei, antes da atribuição acontecer, a expressão à direita precisa ser resolvida. Como nós temos uma IIFE, essa função vai se auto-executar, e passar o retorno dela para a variável `increment`. Nesse caso, `increment` recebe a função que é usada no retorno da IIFE, mas com um detalhe: a variável `counter` iniciada em zero.

Então, a cada execução dessa função, como essa função retornada é uma _closure_, ela guardou o valor de `counter` que ela está usando para retornar (que seria a variável declarada no escopo da IIFE).

Agora veja o segundo exemplo: como nós não executamos a função com uma IIFE, para usar o `increment` nós precisamos fazer algo do tipo:

```js
console.log(increment()) // isso vai resolver na função de retorno, a função mais interna.
console.log(increment()()) // assim nós conseguimos invocar a função mais interna. A primeira execução de `increment` retorna uma função, e então podemos executar essa função mais interna usando os parênteses novamente.
```

Veja o que aconteceu: precisamos usar `()()` para conseguir invocar a função interna! A grande diferença aqui, é que se você for dando `console.log(increment()())`, ele nunca vai retornar nenhum valor diferente de zero. E por que?

Exatamente por causa do escopo! A cada vez que você invoca o primeiro `increment`, um novo escopo é criado, a variável `counter` é zerada e então a segunda função é retornada. Como o retorno da segunda função é o valor de `counter`, e só depois ele é incrementado, quando você invocar novamente `increment()`, vai acontecer o mesmo processo: a variável `counter` é atribuída para zero, mas em um novo escopo.

Para que o segundo exemplo funcione como o primeiro, precisamos guardar o valor da primeira execução de `increment`. Dessa forma, a segunda função funciona como uma _closure_ da forma que a gente espera. Olha só:

```js
var keepIncrementing = increment();
console.log(keepIncrementing()); // 0
console.log(keepIncrementing()); // 1
console.log(keepIncrementing()); // 2
```

Entendeu a ideia? =)

**Comment by jhonesgoncal** [comment]
nossa cara que show. vc podia escrever um livro sobre  JS rsrs eu seria o primeiro a comprar. sinceramente essas explicações só com vc rsrs

**Comment by fdaciuk** [comment]
haha! Legal, que bom que ficou claro =)
Quem sabe no futuro =)
