### ISSUE TITLE
Challenger-01

### ISSUE THREAD

**Issue by front-bittencourt** [da2k/curso-javascript-ninja#2368]
Não estou conseguindo encontrar a parte de comparar o pull request para enviar nessa nova plataforma do github

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @front-bittencourt! Ao entrar no seu repositório, você vai ver um link (não muito visível mesmo) "Pull Request". Ao clicar nele, você será levado a abrir um "Pull Request" para o desafio 01. Veja a imagem abaixo:

![selection_023](https://user-images.githubusercontent.com/487669/33628099-c4b1cad8-d9e6-11e7-99a5-73ad7cdf4ae3.png)

Qualquer dúvida, só avisar!
