### ISSUE TITLE
Challenge-32 - Ajuda

### ISSUE THREAD

**Issue by virginiarcruz** [da2k/curso-javascript-ninja#2394]
Fernando,

Pra ser sincera, não sei por onde começar com o challenge-32. =/

Entendi o que você explicou na aula. Mas não estou conseguindo visualizar como vou guardar esses dados no projeto que estamos criando.

Preciso colocar a pasta server dentro do meu projeto?
Você pode dar algum exemplo para que eu possa me basear e aplicar no projeto de cadastro dos carros?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @virginiarcruz! Vamos lá =)
No desafio 32 tem um diretório `server`. Você pode copiar esse diretório para o local onde você começou o desafio 31. Então é só seguir os passos para subir e servidor! É nele que as informações vão ficar guardadas =)

Enquanto o servidor estiver em pé, as informações dos novos carros que você cadastrar vão estar ali. Se você derrubar o servidor e subir novamente, ele irá zerar as informações, ok? =)

Consegui explicar? =)

**Comment by virginiarcruz** [comment]
@fdaciuk acho que consegui hehe
:) 
Tu é fera, obrigada pela dica.

**Comment by fdaciuk** [comment]
Boa, que bom que deu certo! :D
