### ISSUE TITLE
Desafio 3

### ISSUE THREAD

**Issue by carlapveiga** [da2k/curso-javascript-ninja#2442]
Oi Fernando, tudo bem?

Estou no desafio 3. Na correção do desafio, na última questão (a da pessoa.apresentacao), você declarou as variáveis antes do if. Quando fiz, eu não declarei, fiz direto, assim:

pessoa.apresentacao = function() {
... if (pessoa.sexo === 'Feminino') {
..... artigo = 'a'
..... } else { artigo = 'o'}
... if (pessoa.idade === 1) {
..... varanos = 'ano'
..... } else { varanos = 'anos'}
... if (pessoa.caminhouQuantosMetros === 1) {
..... varmetros = 'metro'
..... } else { varmetros = 'metros'}
... return 'Olá! eu sou ' + artigo + ' ' + pessoa.nome + ', tenho ' + pessoa.idade + ' ' + varanos + ', ' + pessoa.altura + ', meu peso é ' + pessoa.peso + 'kg e, só hoje, eu já caminhei ' + pessoa.caminhouQuantosMetros + ' ' + varmetros + '!';
... }

Deu certo mas queria saber se tem algum problema em fazer assim.

Outra dúvida, no vídeo você fala para sempre montarmos a estrutura antes para não nos perdemos, por exemplo, fazer objeto = function () {};, fechar os colchetes e o ";" antes de escrevermos a função. Mas o meu Node.js e no console não deixa eu editar. Se eu errar alguma coisa tenho que escrever tudo de novo. Queria saber como faço para fazer ficar "editável" igual ao seu.

Obrigada!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @carlapveiga! Vamos lá =)

Sobre a questão de declarar as variáveis com `var`, e fazer isso antes do `if`: parece não fazer diferença nesses primeiros exemplos no início do curso, mas mais pra frente vamos ver sobre escopo, e como nosso código pode ser afetado negativamente quando não usamos o `var` para declarar variáveis. Então, para evitar problemas e fazer da maneira certa desde já, sempre declare as variáveis usando o `var`, ok? =)

Sobre declarar dentro do `if`, mesmo esquema: no momento parece não fazer diferença, mas mais pra frente você vai ver que tem. Então, como boa prática, sempre declare as variáveis antes de utilizá-las =)

E sobre escrever a estrutura inteira antes, você pode usar um editor de textos qualquer, e depois só colar o código no console do node. Isso vai exibir pra você os resultados das expressões =)

Nas próximas aulas eu vou mostrar como executar o código direto de um arquivo `.js`, pelo console do Node =)

Acho que é isso! Se tiver qualquer dúvida, só avisar =)

**Comment by fdaciuk** [comment]
Oi @carlapveiga! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
