### ISSUE TITLE
Challenge - 04 Operador Ternário

### ISSUE THREAD

**Issue by gmferreir1** [da2k/curso-javascript-ninja#2459]
Fernando bom dia, so uma duvida que me surgiu.
Poderia avaliar os operadores Truthy e Falsy dessa forma? Seria correto?

var isTruthy = function (a) {
    return !!a ? true : false;
}

var isTruthy = function (a) {
    return !a ? false : true;
}

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gmferreir1!

Poderia sim! Mas concorda comigo que seria trabalho duplicado?

Olha só: quando você usa o operador de equivalente booleano `!!`, ele já retorna pra você um valor booleano - `true` ou `false` - baseado no tipo de dado que você está testando.

Então fazer isso:

```js
var isTruthy = function (a) {
  return !!a ? true : false;
}
```

É exatamente a mesma coisa que fazer:

```js
var isTruthy = function (a) {
  return !!a;
}
```

=)

Sobre o segundo caso, o problema é parecido, mas diferente: o operador de negação `!`, transforma o valor em booleano e inverte o retorno. No caso, o que seria `true` se torna `false`, e vice-versa =)

Ficou claro?

**Comment by gmferreir1** [comment]
Oi @fdaciuk 
So o primeiro caso :(
Para mim o segundo caso ele avalia o a caso ele for falso ele retorna falso, caso contrario retornaria true.
Mas da forma que eu intendi que você disse, ele avaliaria toda a expressão antes e inverteria pois passei o sinal de negação (!)
Seria isso ?
Mas testei e funciona, por isso não entendi :(

**Comment by fdaciuk** [comment]
Opa, deixa eu tentar explicar melhor =)

Da forma como você fez funciona (o segundo exemplo), só pra você saber =)

O que eu tentei explicar é que o operador de negação primeiro converte o valor para o equivalente booleano, e então inverte esse valor.

No caso:

```
!'a' // false -> a string 'a' convertida para o equivalente booleano é true. Mas como usamos o operador de negação, ele inverte o valor para false.

!false // true -> aqui o valor já é um booleano `false`. O equivalente booleano para `false` é `false` mesmo. Invertendo o valor, o resultado é `true` =)
```

Ficou mais claro agora? =)

**Comment by gmferreir1** [comment]
Ahhh, ta. Sim isso já havia entendido nas aulas. Mas de qualquer forma não
esta errado então pois verifico a ausência do (a) e retorno false caso ele
não exista, evitando assim o uso do a == false. Correto ?

Em 10 de dez de 2017 3:26 PM, "Fernando Daciuk" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Legal então, é isso mesmo =)
Qualquer dúvida só avisar =)
