### ISSUE TITLE
Aula 34 - Sourcemaps

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2478]
Olá, professor! 

Estou tentando minificar um arquivo utilizando o `--source-maps`,  
mas uma msg de erro é exibida e o arquivo `.map` não é gerado, vc sabe o  
que pode ser isso?  Pelo que li na documentação, o comando `--source-map`  
está correto:  

![image](https://user-images.githubusercontent.com/29297788/33811596-914eb3da-ddfc-11e7-81c0-6be27ae57295.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Consegue subir o código que você está tentando aplicar o uglify no GitHub pra eu testar aqui? Suspeito que pode ser duas coisas:
- ou problema com o Windows;
- ou o nome do arquivo precisa ser o mesmo que o arquivo do `output`, mas com o `.map` no final.

Mas só vou conseguir ter certeza testando o código que você está usando =)

**Comment by Roger-Melo** [comment]
Olá, professor.  

Subi o código [aqui](https://github.com/Roger-Melo/uglify-tests)  

P.S.: Tem um arquivo `--` sendo criado :unamused:

**Comment by fdaciuk** [comment]
Agora sim =)
Bom, o problema parece ser com a versão. Instalando `uglifyjs` e `uglify-js`, a lib é a mesma. Uma é alias pra outra. Mas a lib mais "atualizada" - ou ao menos a documentação - é a `uglify-js` (com traço):
https://www.npmjs.com/package/uglify-js

Nesse link você vê a documentação com os comandos corretos pra gerar o source-map:

```
uglifyjs main.js --output main.min.js --compress --mangle --source-map "url='main.min.js.map'"
```

**Comment by Roger-Melo** [comment]
Legal, professor, deu certo aqui.  

Vi que também posso especificar `-o` como atalho de `--output`, por exemplo. Bem legal, obrigado!  

Sei que não faz parte do conteúdo do curso, mas vc poderia dizer como fez para habilitar o atalho `pyserver` ao subir um servidor?

**Comment by fdaciuk** [comment]
Opa, show =)

Então, o `pyserver` é só um alias no sistema. Se estiver usando Linux (não sei como fazer no windows, teria que pesquisar), você só precisa adicionar no arquivo de configuração do seu shell  (.bashrc, .zshrc, etc) o seguinte:

```
alias pyserver="python -m SimpleHTTPServer 9001"
```

Ou usar `function`, se o seu shell suportar:

```
function pyserver () {
  python -m SimpleHTTPServer 9001
}
```

Então, após fechar/abrir novamente o terminal você terá o comando `pyserver` disponível =)

Tem algumas outras formas de fazer. Como meu uso ZSH, eu deixo a função no meu `~/.zshrc` :)

**Comment by Roger-Melo** [comment]
Consegui, professor. 

Estou no (r)windows, o comando especificado foi `@DOSKEY pyserver=python -m http.server 9001`.  

Ainda vou estudar mais a fundo sobre aliases, mas por enquanto resolveu o meu problema. Obrigado! =)
