### ISSUE TITLE
Desafio #04

### ISSUE THREAD

**Issue by ViniAx** [da2k/curso-javascript-ninja#2485]
Estou tendo problema no método de adicionar pessoas no carro, o valor não está ficando fixo, e ainda passa do número de vagas.

```js
function adcPessoas(x) {
    carro.quantidadePessoas = x;
    var pluralSingular = 'pessoas';
    var aindaCabem = carro.asssentos - carro.quantidadePessoas;
    
    if(carro.quantidadePessoas === 1) {
        pluralSingular = 'pessoa';
    }
    return 'Já temos ' + carro.quantidadePessoas + pluralSingular + ' no carro!'
    
    if(carro.quantidadePessoas >= 5) {
    return 'O carro já está lotado!';
    }
    
    if(x > aindaCabem) {
    return 'Só cabem mais ' + aindaCabem + ' pessoas!'
    }

}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ViniAx!
No início da próxima aula eu faço a correção desse desafio, mas o seu código tem um problema crítico: essa linha:

```js
```

**Comment by ViniAx** [comment]
Fernando, refiz o código. Aproveitei e adicionei o também um variável para o caso de só ter 1 pessoas no carro, e não aparecer 'Já temos 1 pessoas no carro!'(acho que não tinha essa pedido na questão). 

> carro.adcPessoas = function( numerosPessoas ) {
> 
>     var vagas = carro.assentos - carro.quantidadePessoas;
>     var singularPlural = vagas === 1 ? ' pessoa' : ' pessoas';
>     if( carro.quantidadePessoas === carro.assentos) {
>         return 'O carro já está lotado!';
>     };
>     
>     
>     if( numerosPessoas > vagas ){
>         return 'Só cabem mais ' + vagas + singularPlural + '!';
>     }
> 
>     carro.quantidadePessoas += numerosPessoas;
>     var singularPlural1 = carro.quantidadePessoas === 1 ? ' pessoa' : ' pessoas';
>     return 'Já temos ' + carro.quantidadePessoas + singularPlural1 + ' no carro!';        
>  
> };
> 

Há algum erro estrutural?
Desde já agradeço, abraço.

**Comment by fdaciuk** [comment]
Legal @ViniAx! De estrutura está tudo certo! Se funcionou, segue em frente =)
