### ISSUE TITLE
Aula com Volume baixo

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2488]
A aula 22 está com o volume muito baixo.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Qual vídeo da aula 22? A Udemy normalmente deixa o volume na metade, dando pra aumentar ao menos o dobro do volume atual =)

Tentou fazer isso? Aqui parece bem audível xD

**Comment by grodrigues** [comment]
É o Fone aqui então. Obrigado

**Comment by grodrigues** [comment]
Valeu

**Comment by fdaciuk** [comment]
Beleza =)
