### ISSUE TITLE
Dúvida em como usar o GitHub

### ISSUE THREAD

**Issue by lucasn4** [da2k/curso-javascript-ninja#2491]
Olá Fernando!

Estou com dúvidas sobre como usar a plataforma GitHub, ainda não entendi como te mando um exercício que fiz e o que seria um Fork e para que serve os Branch's e o que é isso. Ficou meio nebuloso se possível ajudar.

Grato!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucasn4! Você chegou a fazer os passos que mostrei na aula? O que você não conseguiu fazer?
Me explica melhor pra eu entender o que não ficou claro =)

**Comment by lucasn4** [comment]
Opa @fdaciuk fiz sim, mas fiquei perdido sobre "enviar" o exercício, fiz o Fork e criei uma nova Branche. Poderia me explicar o que é um Fork e um Branch para melhorar meu entendimento?

**Comment by frankyston** [comment]
@lucasn4 branch é como se fosse uma ramificação na linha do tempo.
Imagine uma linha reta, no momento que você criar uma branch, você esta criando uma nova linha em parelelo partido do momento exato que foi criando essa nova branch. Tudo que for alterado, adicionado só terá efeito nessa nova linha e não na principal (que chamamos de master).

Observe a imagem abaixo:

https://i.stack.imgur.com/VSqbK.png

Fork é como se fosse um clone do repositório original para um repositório seu. É um copia e colar, sendo que da conta do @fdaciuk para a sua @lucasn4.

Espero ter ajudado.

**Comment by fdaciuk** [comment]
Oi @lucasn4! É exatamente isso que o @frankyston comentou. Obrigado @frankyston =)

Para ver se o seu Pull Request foi enviado corretamente, você pode acessar o [link do repositório do curso](https://github.com/da2k/curso-javascript-ninja), clicar na aba "Pull Requests" e procurar ali o seu. Na lista, é exibido o título que você deu ao Pull Request e também o nome do usuário que abriu o PR.

Se o seu nome de usuário estiver ali, só clicando no título do Pull Request você consegue ver o que você enviou =)

**Comment by lucasn4** [comment]
Muito obrigado @fdaciuk e @frankyston !!!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)

**Comment by frankyston** [comment]
@lucasn4 vlw mano, precisando é só chamar 👍
