### ISSUE TITLE
[Aula 2] Problemas/Dúvidas com o Pull Request

### ISSUE THREAD

**Issue by matheuswd** [da2k/curso-javascript-ninja#25]
Olá Daciuk. Então, estou com um problema/dúvida na hora de fazer o pull request. Toda hora que o faço, ele insiste em enviar o challenge 01 e o challenge 02. Can you help me?

**Comment by fdaciuk** [comment]
Fala @matheuswd! Então, seguinte.. o que você precisa fazer é:

1. Faz o fork do repositório original (da2k/curso-javascript-ninja);
2. Já tem o fork e o exercício 1 feito na branch `challenge-01`, certo? Então agora vc precisa clonar seu repositório, com `git clone endereço-do-seu-repositorio`
3. Após isso, vc vai ter no seu PC o seu repositório, setado na branch master.
4. Inclua o repositório principal, como `upstream`, com o comando: `git remote add upstream git@github.com:da2k/curso-javascript-ninja.git`
5. Execute um `git branch` para garantir que você está na branch master.
6. Agora você precisa atualizar o seu repositório com o repositório original, para pegar o desafio 2. Execute o comando: `git fetch upstream && git merge upstream/master`.
6. Feito isso, você cria uma nova branch, baseada na master, com o comando `git checkout -b challenge-02`.
7. Agora você tem tudo atualizado, e está na branch `challenge-02`, com os dois desafios zerados.
8. Para garantir que está na branch `challenge-02`, execute o comando: `git branch`. A `challenge-02` deve ter um asterisco na frente.
9. Faça o desafio 2. Após isso, faça o commit, com o comando: `git add . && git commit -m "Challenge 02"`.
10. Depois, faça o push para o seu repositório, com: `git push origin challenge-02`.
11. Pronto! Agora é só fazer o Pull Request, como mostrado no vídeo :)

Se você se perder em algum desses passos, me avise em qual. Vamos fazendo até você acertar, ok? :wink:
