### ISSUE TITLE
Automatizar

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2522]
Boa tarde,

queria saber se existe alguma forma de automatizar a parte de teste no caso o coverge. para toda vez que eu salvar o arquivo ele automaticamente rode o comando.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Tem sim!
Dá uma lida [nesse artigo](https://blog.da2k.com.br/2015/01/07/code-coverage-em-javascript/) que vai ajudar =)

Qualquer dúvida, só avisar =)

**Comment by jhonesgoncal** [comment]
Então eu falo em automatizar, não apenas um npm script. por exemplo no gulp. que fique assistindo seus arquivos e qdo vc salvar ele automaticamente já rode o comando .

**Comment by fdaciuk** [comment]
Então, mas nesse link que eu passei, eu mostro exatamente isso: um modo _watch_, que fica assistindo os arquivos de teste e, quando eles são atualizados, o teste é "refeito", mostrando o resultado atualizado =)
