### ISSUE TITLE
o ; no começo

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2539]
Bom dia Daciuk,

queria saber pq vc coloca um ; antes da IIFE?
e qual automatizar de tarefas vc usa nos testes ? naquela parte que vc roda aquele plugin que te da a
pagina com o relatorio de teste?

@fdaciuk

**Comment by jhonesgoncal** [comment]
e tbm queria perguntar como eu gero o certificado, finalizei o curso.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Sobre o `;` antes da IIFE, eu explico em aula: é por causa dos parênteses e do ASI (a feature que o JS adiciona ponto-e-virgula automaticamente - ou não - dependendo de como está o seu código).

> e qual automatizar de tarefas vc usa nos testes ? naquela parte que vc roda aquele plugin que te da a
pagina com o relatorio de teste?

Não entendi a pergunta. Os comandos que eu uso eu mostro sempre nas aulas =)

> e tbm queria perguntar como eu gero o certificado, finalizei o curso.

O certificado você consegue gerar diretamente pela Udemy. Finalizando o curso, ele te dá a opção de gerar =)

**Comment by jhonesgoncal** [comment]
então vc tinha comentado comigo que pelo motivo do curso existir antes da udemy. existia uma modelo de certificado próprio.

**Comment by fdaciuk** [comment]
Ah sim! Você pode gerar à partir [desse link](https://certificado.queroser.ninja/), com o e-mail que você tem cadastrado no curso (só não vai funcionar se você comprou direto da Udemy, que não é o seu caso =))

**Comment by jhonesgoncal** [comment]
chegou , porem com 0% de aproveitamento. más eu fiz todos os pull request

**Comment by fdaciuk** [comment]
Provavelmente porque o seu nome de usuário não estava cadastrado. Tente novamente daqui a pouco =)

**Comment by jhonesgoncal** [comment]
Continua com o problema

**Comment by fdaciuk** [comment]
Às vezes pode demorar um pouco pra chegar o e-mail =)
Se não chegar até 12h de hoje, me avise =)

**Comment by jhonesgoncal** [comment]
o email chegou, porem veio novamente zerado o certificado

**Comment by fdaciuk** [comment]
Dá uma olhada se você não olhou o e-mail antigo, aqui pra mim está com 100% =)

**Comment by jhonesgoncal** [comment]
o email ta correto

**Comment by fdaciuk** [comment]
Por via das dúvidas, acabei de te reenviar o e-mail correto ;)
