### ISSUE TITLE
Compatibilidade

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2549]
Sabe me dizer se existe algum plugin mostra tipo quantos por cento do meu codigo é compativel com tal navegador e tals? 

@fdaciuk

**Comment by fdaciuk** [comment]
Tem o http://jscc.info - mas parece que está fora do ar.
O repositório dele é esse:
https://github.com/tbusser/jscc

Você pode clonar o repositório, instalar as dependências, rodar `gulp build` e, dentro do diretório `out` rodar um server estático na sua máquina. Aí você consegue usar o serviço =)
