### ISSUE TITLE
[Desafio 10] Sobre Var Concat

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2587]
Fala aí, Fernando, beleza?

Estou fazendo a correção do exercício 10 e fiquei com dúvida quando você deu a solução da "var concat".

Você disse que podemos usar:

var concat = String(10) + 10; ou var concat = String(10);

Se eu usar var concat = String('10' + '10'); Estaria correto?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! Nesse caso não, porque você não estaria usando apenas os _Wrapper Objects_, mas sim mudando o tipo da variável de número para string manualmente xD
