### ISSUE TITLE
Desafio 2 código git

### ISSUE THREAD

**Issue by DaniloSAS** [da2k/curso-javascript-ninja#2591]
Fernando, eu estou fazendo exatamente como ensina no vídeo, mas quando faço o Git clone dá esse erro:

C:\Users\GTDda\curso-javascript-ninja>git clone git@github.com:DaniloSAS/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@fdaciuk

**Comment by AlexsanderFer** [comment]
Você precisa gerar uma SSH Key (Sse você não tiver uma) e associar a key publica com a sua conta do Github. 

Dê uma olhada aqui: https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by fdaciuk** [comment]
Obrigado @AlexsanderFer! =)

É isso que você precisa @DaniloSAS! Dá uma olhada no link que o @AlexsanderFer passou, e veja como criar uma  chave SSH no windows =)

Seguindo o tutorial certinho, você vai ter o git integrado com seu GitHub para poder fazer os pull requests sem problemas =)

**Comment by DaniloSAS** [comment]
Valeu @fdaciuk e @AlexsanderFer 
Consegui fazer, mas quando eu dou o git commit -m "Challenge 02" aparece uma mensagem parecendo um erro.. olha ai!


$ git commit -m "Challenge 02"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'GTDda@DESKTOP-FIAUVOB.(none)')

**Comment by DaniloSAS** [comment]
Estou achando meio confuso essa parte, mas por falta de conhecimento e prática minha, claro. Eu alterei o challenge-02 para ver se alterou algo e lá no meu repositório não mudou nada.

**Comment by fdaciuk** [comment]
Oi @DaniloSAS! A sua configuração do git está quase completa! Agora, como diz ali na mensagem, você só precisa configurar seu e-mail e seu nome (os mesmos usados aqui no GitHub) para que os seus commits sejam relacionados com o seu usuário. Você só precisa executar os comandos no seu terminal:

```console
# Substitua o you@example.com pelo seu e-mail do GitHub
git config --global user.email "you@example.com"

# Substitua "Your Name" pelo seu nome.
git config --global user.name "Your Name"
```

Assim que você rodar esses comandos, você já poderá fazer seu commit.

Depois é só seguir como foi mostrado no curso que vai dar tudo certo \o/

Qualquer dúvida, só avisar!

**Comment by DaniloSAS** [comment]
Entendi.. esse negócio tá dando trabalho rsrsrsr  Eu fiz e deu certo, mas quando dou o git push challenge-02 aparece isso aqui. 

$ git push origin challenge-02
Enter passphrase for key '/c/Users/GTDda/.ssh/id_rsa':
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  

eu coloquei a senha certinha. @fdaciuk

**Comment by DaniloSAS** [comment]
![2017-12-17 1](https://user-images.githubusercontent.com/34549752/34081646-f87b7250-e32e-11e7-8b9b-43351644dc30.png)

**Comment by fdaciuk** [comment]
Você fez o passo de adicionar sua chave SSH aqui no GitHub?

**Comment by DaniloSAS** [comment]
Eu fiz tudo normal e foi dando certo até esse passo ai

**Comment by fdaciuk** [comment]
Você marcou alguma opção para sua chave não ser para escrita, apenas somente leitura? É o erro que está dando ali.

**Comment by DaniloSAS** [comment]
Fiz o tutorial normal para gerar a ssh. Como faço para resolver isso então?

**Comment by fdaciuk** [comment]
Você precisa pegar o conteúdo da sua chave pública (em `/c/Users/GTDda/.ssh/id_rsa.pub`), e adicionar na sua conta do GitHub. Siga os passos abaixo:

![selection_024](https://user-images.githubusercontent.com/487669/34081965-353d4854-e33d-11e7-9171-13cdbe49c54c.png)

![selection_025](https://user-images.githubusercontent.com/487669/34081966-3824b08e-e33d-11e7-8174-416cac803465.png)

![selection_026](https://user-images.githubusercontent.com/487669/34081967-3b0614f0-e33d-11e7-8cde-d0761d5abbd1.png)

![selection_027](https://user-images.githubusercontent.com/487669/34081968-3dd07450-e33d-11e7-9ed4-9e6c543068c3.png)

---

Após fazer isso, rode no seu terminal:

```sh
ssh -T git@github.com
```

Se exibir uma mensagem de boas vindas com seu nome de usuário, então está tudo certo, e agora deve funcionar =)

**Comment by DaniloSAS** [comment]
apareceu essa mensagem aqui.. acho que já fiz isso, mas foi por outro caminho. 

![ssh and gpg keys](https://user-images.githubusercontent.com/34549752/34083277-4075de98-e34c-11e7-9897-18f930909ff0.png)

**Comment by DaniloSAS** [comment]
Eu segui esse tutorial aqui... https://www.youtube.com/watch?v=VT4He5Xo4D4

**Comment by DaniloSAS** [comment]
Eu dei um ssh -T git@github.com pra ver o que acontecia e apareceu isso. @fdaciuk 

GTDda@DESKTOP-FIAUVOB MINGW64 /c/curso-javascript-ninja/curso-javascript-ninja (challenge-02)
$ ssh -t git@github.com
Enter passphrase for key '/c/Users/GTDda/.ssh/id_rsa':
PTY allocation request failed on channel 0

**Comment by DaniloSAS** [comment]
Estou impossibilitado de continuar os desafios por conta dessa parada :-\  Se você estivesse de bobeira ai poderíamos falar no teamviewer e resolver.

**Comment by fdaciuk** [comment]
Você deve ter colocado uma senha na hora de criar sua chave SSH, correto? Na hora de digitar `ssh -T git@github.com` (veja que o `T` é maiúsculo, ok?), ele deve pedir a senha. Coloque a mesma senha que vc usou para criar a chave.

Se você não quiser deixar sua chave com senha (o que não tem problema se a chave está em um computador pessoal, que só você mexe), você pode remover os arquivos no seu diretório `.ssh` e criar a chave novamente, seguindo esses passos:
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-windows

Só na hora de pedir a senha, dê apenas enter que ele não vai mais pedir senha quando você usar essa chave ;)

Aí é só entrar no GitHub, adicionar a nova chave e pronto! Tenta ae!

**Comment by fdaciuk** [comment]
Só como referência, esse guia ajuda para começar com o básico do Git, se você ainda estiver tendo dificuldades:
https://rogerdudler.github.io/git-guide/index.pt_BR.html

**Comment by DaniloSAS** [comment]
Acho que esse passo agora foi... deu essa mensagem aqui. Vamos ver daqui pra frente se não dá mais nenhum erro. 

$ ssh -T git@github.com
Enter passphrase for key '/c/Users/GTDda/.ssh/id_rsa':
Hi DaniloSAS/curso-javascript-ninja! You've successfully authenticated, but GitHub does not provide shell access.


@fdaciuk

**Comment by DaniloSAS** [comment]
vou tentar fazer o passo do push e do commit pra ver se vai.

**Comment by fdaciuk** [comment]
Legal! Não é pra dar erro, apenas vai pedir, sempre que vc precisar usar essa chave, a senha que vc usou na hora que criou a chave =)

**Comment by DaniloSAS** [comment]
A senha to ligado. Era o T que estava minusculo. Quero ver se consigo fazer tudo certinho agora. Editar os arquivos e criar as challege através do código no terminar do jeito que fez na aula.

**Comment by DaniloSAS** [comment]
Agora quando faço o push ele dá esse erro! 

![image](https://user-images.githubusercontent.com/34549752/34362545-6acc24be-ea53-11e7-8962-406deb210631.png)
@fdaciuk 

Ta froid essa parada de git hub para configurar tudo certinho!

**Comment by DaniloSAS** [comment]
Dando o mesmo erro! 

GTDda@DESKTOP-FIAUVOB MINGW64 /c/curso-javascript-ninja/curso-javascript-ninja (                                                      challenge-02)
$ git push origin challenge-02
Enter passphrase for key '/c/Users/GTDda/.ssh/id_rsa':
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@fdaciuk 

![2017-12-26](https://user-images.githubusercontent.com/34549752/34362612-ed30bafa-ea53-11e7-9329-7f824f1407cd.png)

**Comment by DaniloSAS** [comment]
Parece que a chave que criei é só de leitura.. nem sei como muda isso para resolver.
@fdaciuk

**Comment by DaniloSAS** [comment]
Acho que consegui! :-) Vamos ver se consigo ir até o final..Tive que apagar a chave e fazer de novo usando a opção de ler e escrever.

**Comment by DaniloSAS** [comment]
@fdaciuk  Consegui resolver tudo direitinho, mas agora só tenho uma dúvida. Eu fiz uma alteração básica na challenge-02 só para configurar essa parada do github, agora eu quero resolver o desafio todo, como eu faço para editar lá no sublime e atualizar a pull request?

**Comment by fdaciuk** [comment]
Oi @DaniloSAS! Para fazer uma modificação em um arquivo do challenge-02, você precisa estar acessando essa branch. Para acessar, só é preciso rodar `git checkout challenge-02`. Para mudar de branch, você não pode ter nenhuma alteração "por comitar".

Quando estiver na branch `challenge-02` - você pode checar se está nela com o comando `git branch`. O `challenge-02` deve aparecer com um asterisco na frente - então você já pode fazer a alteração, comitar e fazer o push.

Ao fazer o push, a alteração já vai direto para o pull request aberto, não precisa abrir novamente =)

**Comment by DaniloSAS** [comment]
@fdaciuk  fiz alguma cagada aqui que não estava mais indo, apaguei a pasta dos arquivos para fazer o processo todo novamente, mas agora na parte do push tá dando esse erro:

![image](https://user-images.githubusercontent.com/34549752/34386101-c32b4736-eb05-11e7-8cd5-c7bee182b32b.png)

Toda hora é uma coisa!

**Comment by DaniloSAS** [comment]
eu estou editando a challenge-02 no sublime e no git bash estou dando "git add ." e depois "git push origin challenge-02"  e não esta alterndo.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DaniloSAS! Depois do `git add .` você precisa fazer um _commit_. Após o commit, você terá a alteração no histórico do git, então você vai conseguir fazer o _push_ =)

**Comment by DaniloSAS** [comment]
o commit é como?  git commit ?
@fdaciuk

**Comment by fdaciuk** [comment]
O commit é: `git commit -m "Mensagem de commit"`. Lembra que eu mostrei na aula? =)

**Comment by DaniloSAS** [comment]
Foi! Valeu 👍 
@fdaciuk

**Comment by fdaciuk** [comment]
Show! =)
