### ISSUE TITLE
Sugestão e duvidas

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2595]
Bom dia mestre,

queria saber qual a sua distro do linux que usa no curso?rsrs
aquele terminal é o dela ou customizado?

queria saber tambem qual o seu styleguide de desenvolvimento em JS?

queria sugerir umas aulas sobre o Vim rsrs vc usa lá mais fico muito 
perdido com ele.

@fdaciuk

**Comment by AlexsanderFer** [comment]
Me parece o elementaryOS... =D

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! No curso de JS eu comecei usando o Elementary mesmo, e o Terminator como terminal =)
Hoje eu uso Ubuntu com o terminal padrão + tmux (com o Byobu). [Aqui você encontra](https://github.com/da2k/curso-reactjs-ninja/blob/master/config/README.md) a minha configuração atual =)

E para styleguide (e linter) eu uso o [Standard.js](https://github.com/standard/standard), que eu recomendo no final do curso de JS, e desde o início do curso de React =)
