### ISSUE TITLE
Novos cursos

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#2599]
Olá, professor!  

Terminei o curso e fiquei órfão de mais JS puro.  =)

Estou começando um curso avançado de JS(ES6) em uma famosa plataforma online, mas observei que faltam, por exemplo, tópicos cruciais como o uso das `IIFE` (pelo menos não encontrei no índice).  

Mini-chororô feito, estou curioso em saber se vc pretende fazer um curso de ES6 abordando as entranhas da linguagem como feito no JS Ninja.

@fdaciuk

**Comment by fdaciuk** [comment]
haha! Legal cara =)
Com certeza! Ano que vem teremos várias novidades! Deixa só eu terminar o curso de React :D

**Comment by Roger-Melo** [comment]
Combinado! :boom:
