### ISSUE TITLE
Exercícios Js

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2603]
Existe algum repositório com mais exercício de Javascript e quando os exercícios serão atualizados ?

@fdaciuk

**Comment by fdaciuk** [comment]
Como assim "atualizados" @grodrigues? Os desafios do curso são esses mesmo =)

Mas você consegue encontrar vários outros locais com exercícios para desenvolver o raciocínio lógico com a linguagem. Vou compartilhar aqui alguns links que a @alinebastos e o @marquinhusgoncalves postaram lá no slack do curso:

https://www.freecodecamp.org/
https://www.hackerrank.com/
https://github.com/alinebastos/dev-practice

**Comment by grodrigues** [comment]
Valeu mesmo, vou participar no slack. Abraço
