### ISSUE TITLE
[Desafio #11] Função moreThan()

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2606]
Opa, Fernando!

Eu estou corrigindo o desafio #11 e vi que no exercício onde precisamos criar a função moreThan, você fez de uma maneira que deixa o código um pouco mais extenso.

Eu fiz assim:

function moreThan(age) {
		if (person.age > age) {
			return true;
		}
		return false;
	}
	console.log('The person has more than 25 years old?', moreThan());

Ele corresponde da maneira correta.
Eu sei que você havia falado pra não ultrapassarmos a maneira de fazer, mas foi a solução mais rápida que eu achei e gostaria de saber se está correto.

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! Não entendi muito bem sua dúvida. Na solução do desafio, eu mostrei como resolver com apenas uma linha essa função, então, na verdade, ela fica **menos** extensa =)

No caso, sua implementação também funciona, só faltou passar o valor quando você executa a função `moreThan()` =)

**Comment by garritanoo** [comment]
Eu me expressei mal.
No caso, você tinha colocado o 25 no lugar do "age", só que mais pra frente no vídeo você coloca o age no local do 25 e diz que essa é a maneira correta.

Eu fiz confusão na hora de explicar.

**Comment by fdaciuk** [comment]
Isso! O certo é você colocar a variável, que assim que você chama a função `moreThan(25)` é como se você realmente dissesse `more than 25?`

Se você passasse o 25 dentro da função, não daria pra saber, só pelo nome da função, que ela está testando especificamente por esse valor. Nesse caso, se precisasse testar só por esse valor mesmo, você poderia nomear a função como `moreThan25()`, aí sim faria sentido =)

Era isso que você queria saber?

**Comment by garritanoo** [comment]
Era isso não, mas você acabou explicando o que eu queria saber no vídeo mesmo.
Obrigado.

**Comment by fdaciuk** [comment]
haha! Legal =)
Qualquer coisa avisa ae :D
