### ISSUE TITLE
Boas Praticas

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-javascript-ninja#2639]
Bom dia mestre,

poderia me falar um pouco sobre boas praticas e me indicar materiais sobre?

@fdaciuk

**Comment by jhonesgoncal** [comment]
Artigos e tals

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Isso é bastante relativo na real, mas um lugar onde você pode buscar boas informações sobre isso é aqui:
http://jstherightway.org/
