### ISSUE TITLE
challenge -15

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#2675]
eai cara?
 ta meio complicado este desafio, gostaria de saber se no caso

```js
function Person(name,lastName,age){
    this.name = name
    this.lastName = lastName
    this.age = age
    };
```
o this esta se referindo ao window? pois pelo que eu entendo ele nao esta dentro de um metodo de objeto, esta dentro de uma funcacao que nao esta retornando nado por enquanto(se eu der console.log(Person())ele da undefined, certo?
Porem quando eu acrecento 3 métodos o this vai mudar e apontar para o objeto Person,Isso? se for isso nao entendo quando o o Person e os metodos se  entrelaçao? sera que deu para entender?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! Se você só invocar a função sim, o `this` será referência ao objeto global =)
Mas a ideia da criação dessa função é usá-la como um construtor. Nesse caso, para **construir** um novo objeto do tipo `Person`, você vai usar sempre `new Person()`.

Isso vai fazer com que um novo objeto seja criado, e o `this` passe a apontar para esse novo objeto criado =)

**Comment by leoigel** [comment]
entao issso eu entendi, porem gostria de saber se ao inves de funcao
function Person(name,lastName,age){
  
    this.name = name
    this.lastName = lastName
    this.age = age
    this.getFullName = function getFullName(){

        return + this.name + this.lastName;
  };
   this.getAge = function getAge(){
      return this.age;
   };

   this.addAge = function addAge(){
      this.age += arguments[0];
      return this;
   };
  }
poderia usar Person no lugar de this teoricamente seria o mesmo?
e se eu ao inves de usar por exemplo o metodo com propriedade deste jeito this.getAge = function getAge(){
      return this.age;
poderia usar como uma variavel
tiopo

var getAge = function Person(){
  return this.age;
}
 seria o mesmo? espero que estou sendo claro

**Comment by fdaciuk** [comment]
Entendi o seu ponto! Mas não é a mesma coisa não =)
Na verdade, a sua dúvida caberia melhor em um objeto já construído. Mas pense no seguinte: lembra quando falamos que objetos são passados por referência, e que cada objeto criado ocupa um lugar específico na memória?

Se você tivesse, por exemplo, um objeto `Person`, e usasse sempre essa mesma referência, ainda que internamente, ao invés do `this`, a referência que você teria internamente seria sempre para o mesmo objeto.

O que nós queremos com o uso do construtor é poder criar quantos objetos do tipo `Person` nós quisermos, que irão funcionar independentes um do outro. Então o `this` vai ser a referência para cada objeto criado.

No caso:

```js
var fernando = new Person('Fernando', 'Daciuk', 33);
var leo = new Person('Leo', 'Igel', 20);
```

Veja que nós criamos dois objetos diferentes, mas aproveitando o mesmo "esqueleto" de objeto, que veio do construtor. Veja que os dois objetos são diferentes. Cada um tem uma propriedade `age` interna, mas o `age` do `fernando` não é o mesmo `age` do `leo`. Cada um tem o seu `age` de forma independente.

Diferente seria se você criasse um objeto `person` (sem ser um construtor):

```js
var person = {
  age: 20,
  getAge: function getAge () {
    return person.age;
  }
}
```

Veja que esse objeto já tem suas propriedades definidas. Mesmo que você crie novos objetos à partir dele, sempre que chamar o método `getAge`, a idade retornada será sempre `20`, pois você está pegando a propriedade `age` de `person`.

Ao usar o `this`, você deixa isso genérico para pegar o `age` de quem quer que seja o `this` =)

Ficou claro?

**Comment by leoigel** [comment]
você é foda rapaz...

בתאריך 21 בדצמ׳ 2017 07:11 PM,‏ "Fernando Daciuk" <notifications@github.com>
כתב:
