### ISSUE TITLE
Erro no desafio

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2698]
`function convertToHex(color) {
    switch(color){
        var hexa;
        case 'red':
              hexa = '#FF0000';
              break;
        case 'blue':
              hexa = '#0000FF';
              break;
        case 'green':
               hexa = '#00FF00';
               break;
        case 'black':
              hexa = '#00000';
              break;
        case 'white':
              hexa = '#FFFFFF';
              break;
        default:
            return 'Não temos o equivalente hexadecimal para cor';

    }
    return 'O hexadecimal para a cor' + color + 'é' + hexa + '.';
}`

No console está dando esse erro { Unexpected token (3:8)}

Já olhei e comparei com o vídeo e não consegui encontrar.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Dá uma olhadinha no erro: ele diz que existe um _token_ inesperado, na linha 3 do seu código. O que tem na terceira linha desse seu código? É a pista de onde está o erro ;)

**Comment by grodrigues** [comment]
Valeu

**Comment by grodrigues** [comment]
fez tudo certo mais é assim mesmo. 👍

**Comment by fdaciuk** [comment]
Show! É isso aí =)
É bom que dê esses erros, porque isso acontece no dia a dia. Então é importante entender o que eles significam pra conseguir resolver os problemas que aparecerem =)
