### ISSUE TITLE
[Aula 109] REGEX e grupos de captura

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2779]
Opa Daciuk, beleza ?
Eu fiquei com uma dúvida a respeito dos grupos de captura. Entendi o funcionamento dele perfeitamente, mas fiquei com dúvida no seguinte:

Existem certos elementos que eu não quero capturar, mas quero que eles fiquem em () para que eu possa definir um grupo pra tratar eles de uma certa forma: sendo colocando "?" ou qualquer outra coisa.
Digo:

\w+(azul | vermelho | preto)? 
Nesse exemplo, eu não gostaria de fazer com que ele fosse um item de captura, mas mesmo assim eu preciso que ele esteja entre parenteses para conseguir colocar o "?". 
Como eu faria para agrupar eles, sem coloca-los em um grupo de captura.

Não sei se fui claro!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Acho que entendi sua dúvida sim =)
Você quer apenas agrupar sem criar uma captura, correto? Bom, não sei se você já chegou nessa aula (se não chegou ainda, vai ser alguma das próximas), onde eu mostro o `?:`, usado dentro dos parênteses, que faz exatamente o que você quer: ele agrupa valores sem gerar uma captura =)

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
