### ISSUE TITLE
[DESAFIO 2] Duvida no exercício da linha 67

### ISSUE THREAD

**Issue by Cleysonlb** [da2k/curso-javascript-ninja#28]
Fala Daciuk, cara to me amarrando no curso muito bom mesmo parabens!
Estou com dificuldades pra pensar na lógica da coisa, você pode me dar um help?!
Vlw!

**Comment by fdaciuk** [comment]
Que bom que está gostando @Cleysonlb! É do desafio 2 a sua dúvida?

**Comment by Cleysonlb** [comment]
Desculpe nao especificar, sim e do desafio 2

**Comment by fdaciuk** [comment]
Então cara.. no exercício 2 não tem 67 linhas xD
Dá uma olhada aqui e me diz onde é a sua dúvida: https://github.com/da2k/curso-javascript-ninja/blame/master/challenge-02/README.md

**Comment by Cleysonlb** [comment]
Neste exercício! 
/*
Crie uma função com as seguintes características:
1. A função deve receber 3 argumentos.
2. Se somente um argumento for passado, retorne o valor do argumento.
3. Se dois argumentos forem passados, retorne a soma dos dois argumentos.
4. Se todos os argumentos forem passados, retorne a soma do primeiro com o segundo, e o resultado, dividido pelo terceiro.
5. Se nenhum argumento for passado, retorne o valor booleano `false`.
6. E ainda, se nenhuma das condições acima forem atendidas, retorne `null`.
*/

**Comment by fdaciuk** [comment]
Certo, qual parte exatamente você não entendeu?

Tente fazer aos poucos: 

criar uma função que receberá 3 argumentos:

```js
function myfunction( a, b, c ) {}
```

se somente o primeiro argumento for passado, retorne o valor do argumento:

```js
function myfunction( a, b, c ) {
  if( a !== undefined && b === undefined && c === undefined ) {
    return a;
  }
}
```

E assim por diante :)

**Comment by Cleysonlb** [comment]
Consegui aqui ;) vlw! to enviando o pull request!

**Comment by fdaciuk** [comment]
:+1:
