### ISSUE TITLE
Challenge 01

### ISSUE THREAD

**Issue by Isabelninja** [da2k/curso-javascript-ninja#2818]
Terminei de fazer o desafio 01 salvei na pasta mas quando clico no da2k/curso-javascript-ninja
 nao aparece a parte em que no udemy esta amarelinho para enviar (compare e pull request), como faço para aparecer?

**Comment by fdaciuk** [comment]
Oi @Isabelninja! Nesse caso, você pode enviar o PR manualmente. Dá uma olhada na issue https://github.com/da2k/curso-javascript-ninja/issues/2368 que eu expliquei ali como faz =)

Qualquer dúvida, só avisar! =)

PS.: Sempre que abrir uma issue, deixe a marcação do meu usuário `@fdaciuk` aqui, senão eu não recebo notificação da sua dúvida, ok? =)
