### ISSUE TITLE
Problema de acesso (publickey) depois da formatação

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-javascript-ninja#283]
e ae @fdaciuk , depois que eu formatei meu notebook eu mantive os arquivos das aulas no meu D:, porem agora não consigo mais enviar, tentei refazer as autenticações mas não to tendo progresso, e como se ele tivesse mantido as chaves, mas perdeu as configurações, como eu faço pra resolver isso??

**Comment by fdaciuk** [comment]
Fala @brunotortelli! Você chegou a criar novas chaves SSH, ou fez backup das antigas?
Se estiver usando as antigas, era pra estar funcionando. Senão, você precisa criar novas chaves. Pode usar esse tutorial para fazer isso: https://help.github.com/articles/generating-ssh-keys/#platform-windows

Seguindo esses passos, já vai funcionar certinho :D 

Qualquer dúvida grita aqui xD

**Comment by brunotortelli** [comment]
deu certo vlw

**Comment by fdaciuk** [comment]
Show :dancer:
