### ISSUE TITLE
Challenge-18

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2839]
Boa tarde Daciuk, tudo bem ?

Cara, me veio uma dúvida enorme nesse challenge, mais especficiametne nesse exercicio

```js
  var texto = "<h1>Título da página</h1><p>Este é um parágrafo</p><footer>Rodapé</footer>";
    var regex = /<(\w*)>([^<]+)\</\w+>/g;
   console.log(texto.replace(regex, '<$1> O texto dentro da tag "$1" é "$2" </$1>\n'));
```

Eu não consigo ver como a resposta sai com exatidão, já que o $1 seria o "h1", como que depois o $1 virá o "p" por exemplo ? Eu pensei que o p seria o $3, e assim por diante. Parece que rolou um for pra cada estrutura /<(\w*)>([^<]+)\</\w+>/g encontrada, onde o $1 e o $2 vai sendo substituido . 

Como funciona o replace ? Não sei se fui muito claro, mas é que realmente esse me confundiu de uma maneira absurda.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! É isso que acontece mesmo, mas por baixo dos panos =)
Dá uma olhada na explicação que eu dei na issue https://github.com/da2k/curso-javascript-ninja/issues/2044 e me diga se fica mais claro como funciona o `replace` =)

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
