### ISSUE TITLE
Challengers

### ISSUE THREAD

**Issue by front-bittencourt** [da2k/curso-javascript-ninja#2842]
Estou tentando enviar os desafios pelo git, primeiro acontece o seguinte.
Eu já tenho um branch chamada challenge-01 criada no github, quando baixo meu repositorio forkado pelo git ele só vem com a branch master e não a challenge-01.

Outra coisa, quando faço o git push origin challenger-02 ele me aparece esse erro:
Enter passphrase for key '/c/Users/mthbi/.ssh/id_rsa':
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Como faço para prosseguir?

**Comment by fdaciuk** [comment]
Oi @front-bittencourt! 

Não é necessário baixar todas as branchs, a menos que você vá trabalhar em alguma delas.
Mas se ainda assim quiser fazer, o processo manual é com os comandos:

Rode esse comando uma vez:

```sh
git fetch origin
```

Então, execute esse comando para cada branch que você queira local:

```sh
git checkout origin/challenge-01 -b challenge-01
```

Só altere o nome em `challenge-01` no comando acima para o nome da sua branch.

---

Se estiver usando linux, dá uma olhada na issue https://github.com/da2k/curso-javascript-ninja/issues/79 que eu expliquei como faz um for no terminal pra buscar automaticamente todas as branchs do repositório =)

---

Sobre o erro que você está tendo ao tentar subir o `challenge-02`, você pode ter digitado a senha da sua chave SSH errada =)

Para configurar corretamente, veja esses artigos aqui do GitHub para o seu SO, que ali mostra passo a passo como criar a chave e subir no GitHub de forma correta:
 https://help.github.com/articles/generating-ssh-keys

---

PS.: Sempre que abrir uma issue, deixe a marcação do meu usuário `@fdaciuk` aqui, senão eu não recebo notificação da sua dúvida, ok? =)

**Comment by fdaciuk** [comment]
Oi @front-bittencourt! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
