### ISSUE TITLE
Desafio 15 

### ISSUE THREAD

**Issue by hmilena** [da2k/curso-javascript-ninja#2853]
#586  Daciuk, também é ok dar o retorno assim: 

`this.addAge = function(){
     return this.age + arguments[0];
}`

?? Ao invés de assim: 

`this.addAge = function(){
     this.age += arguments[0];
     return this;
}`

Evitando o encadeamento? Ou é problemático mais pra frente? Ou precisamos fazer retornando o this porque é assim que pedia o enunciado? HEHE 

Obrigada. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hmilena! Nesse caso específico, seria um problema fazer como o seu primeiro exemplo, pelo fato do método `this.getAge` depender do que está na variável `this.age`. O seu primeiro exemplo simplesmente retorna tudo o que foi tem em `this.age`, somando com o primeiro argumento passado no método `addAge`, mas não incrementa o valor na variável `this.age` que será usada quando você chamar `this.getAge()` =)

No caso, se você não quiser usar encadeamento, não tem problema. O retorno do `this` no segundo exemplo não é obrigatório. É apenas uma forma de facilitar a chamada de outros métodos, já que o `addAge` não precisaria necessariamente ter um retorno, entende? =)

A ação do `addAge` é somente adicionar uma idade ao objeto criado, então ele não precisa retornar valor. No caso do `getAge`, aí sim nós esperamos como resultado a idade, então esse método tem que, obrigatoriamente, retornar algum valor, não sendo possível retornar o `this` nele para fazer encadeamento =)

Ficou claro?

**Comment by hmilena** [comment]
Mais ou menos! Vou ler mais algumas vezes pra entender melhor. 

Obrigada.

**Comment by fdaciuk** [comment]
Beleza! Qualquer coisa me chama no slack que talvez conversando em tempo real fique mais fácil compreender =)
