### ISSUE TITLE
Aula 121

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2882]
Bom dia Daciuk, tudo bem ?
Achei muito interessante a explicação sobre o DOM. O que mais me fascinou foi a captura dinamica dos elementos dons sem que haja a necessidade de um comando pra fazer novamente a copia do documento HTML.
Como funciona essa parada ? Em toda alteração feita, o javascript se encarrega de reler o DOM ? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Então, como acontece é uma implementação específica do browser. Cada browser pode fazer da forma que quiser, desde que ele mantenha a coleção de itens atualizada.

Mas como eu mostrei mais à frente, cuidado ao usar esses métodos: essa mutabilidade automática causa o que chamamos de **efeitos colaterais** (ou _side effects_), que significa que, quando você não tem controle de algum valor, e não sabe exatamente quando ele vai mudar, pois qualquer outro código na página pode inserir, de forma dinâmica, outros inputs na tela, você acaba perdendo a previsibilidade daquele código.

E quando você não consegue prever o que um código faz, fica bem mais difícil encontrar bugs quando eles aparecem.

Quando você usa os métodos `querySelector` e `querySelectorAll`, você tem confiança de que os valores daquela variável são sempre os mesmos, não tem nada que possa modificá-los, a menos que você faça uma reatribuição.

Isso garante previsibilidade e evita vários bugs que você poderia perder horas tentando resolver em aplicações um pouco maiores =)

**Comment by MatheusDidier** [comment]
Perfeito Daciuk, pode deixar que levarei essa dica comigo! Muito obrigado cara

**Comment by fdaciuk** [comment]
Boa =)
