### ISSUE TITLE
Livro sobre Expressão Regular 

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2890]
Você já leu esse livro ? 
http://piazinho.com.br/

@fdaciuk

**Comment by fdaciuk** [comment]
@grodrigues não li o livro ainda, mas conheço o Aurelio, e ele manja muito de expressões regulares e shell xD

Pretendo adquirir esse livro em breve =)

**Comment by grodrigues** [comment]
Então a partir de hoje todos as variáveis do exercício de expressão regular passaram a ser chamadas de AURELIO :o:
