### ISSUE TITLE
Sobre o event loop

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2897]
Opa Daciuk, tudo bem com você  ?

Cara, achei muito interessante a discussão sobre o Event Loop, e com sua explicação, me veio uma solução à uma dúvida minha que tive há um tempo atrás, não sei se estou correto, então peço por gentileza que caso eu não esteja, me corrija.

Minha dúvida era a seguinte: logo no inicio da explicação das IIFEs eu pensei  "Que estranho. Agora eu vou 'perder' minhas funções. Não vou conseguir acessar elas no meu console - esse é só um exemplo de um caso - , caso eu queira", e dai veio uma preocupação minha, pois eu sabia que tinha como acionar eventos com javascript. Mas ai eu pensei, como o evento vai ser acionado, se ele estava dentro da minha IIFE, e minha IIFE já foi executada ?

Não sei se fui claro. Mas agora me parece que veio a solução: A resposta é o event loop. No momento que minha iife foi executada, o evento adicionado dentro da minha função passou a fazer parte do event loop, e foi assim que eu não perdi o acesso a ela!

Estou correto ?

E enquanto eu escrevia isso me veio outra dúvida: 

Vamos supor que eu tenha um tal documento JS

(function(){
   function teste(){
         console.log("teste");
    }
})();

Essa função está dentro da iife. Não consigo acessar ela fora da iife. Porém, se eu adicionar um evento que execute essa função, eu meio que vou conseguir acessar ela fora da iife, e não só quando a iife foi executada. ISso quer dizer que o event loop traz com ele uma cópia da função que ele deveria executar ? Pois minha função foi declarada dentro da iife, e uma vez executada a iife, as funções ali presentes não estão mais "presentes". 

Não sei se fui claro. Talvez eu tenha confundido um pouco DSUAHSDUD, mas podemos conversar melhor! Aguardo resposta, e muitissimo obrigado por suas aulas!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! 

> A resposta é o event loop. No momento que minha iife foi executada, o evento adicionado dentro da minha função passou a fazer parte do event loop, e foi assim que eu não perdi o acesso a ela!

É isso mesmo! A IIFE impede que o seu código seja acessado de forma global. Você "perde" o acesso às variáveis e funções à partir do console, porque ali você só consegue usar o que estiver no escopo global. Isso, na verdade, é uma vantagem, visto que, se você não tem acesso, nenhum código externo também vai ter, e sua aplicação fica mais segura e isenta de bugs que ocorreriam se o código estivesse em escopo global =)

Sobre a questão do evento, é isso mesmo: assim que a IIFE é executada, e também o método `addEventListener`, a sua função usada no evento vai para o eventloop. Você não vai ter acesso à função, pois ela está em escopo local, mas à partir do console você consegue selecionar o objeto e disparar o evento sim, pois o DOM está disponível para ser acessado de qualquer lugar, inclusive no escopo global =)

---

> Essa função está dentro da iife. Não consigo acessar ela fora da iife. Porém, se eu adicionar um evento que execute essa função, eu meio que vou conseguir acessar ela fora da iife, e não só quando a iife foi executada. ISso quer dizer que o event loop traz com ele uma cópia da função que ele deveria executar ? Pois minha função foi declarada dentro da iife, e uma vez executada a iife, as funções ali presentes não estão mais "presentes".

Como eu falei acima: você não vai ter acesso à função em si se usar ela como listener de um evento. Você consegue, fora da IIFE, ter acesso ao elemento do DOM que tem o evento e, ao disparar o evento, a função é executada.

Funções são objetos, então sempre que uma função é criada, ela ocupa um espaço em memória. O event loop não cria uma cópia da função, ele simplesmente sabe o espaço de memória em que essa função está e executa ela à partir dali. Se a função não for mais usada, e não tiver mais como ser acessada, aí entra em ação o _garbage collector_, removendo essa função da memória e liberando o espaço que ela estava ocupando =)

Se você ainda não viu sobre o _garbage collector_, fique tranquilo que deve estar umas aulas à frente =)

Acho que é isso! Ficou claro?

**Comment by MatheusDidier** [comment]
Ficou muitissimo claro! Então o event loop guarda com ele o endereço de memórias das funções que ele executa(caso ele execute alguma). Muito interessante isso cara! Muito legal mesmo.
Opa, não vejo a hora de ver garbage collector então! Muito completo seu curso Daciuk, valeu cara!

**Comment by fdaciuk** [comment]
> Então o event loop guarda com ele o endereço de memórias das funções que ele executa(caso ele execute alguma)

Na  verdade, é você que passa essa informação pra ele. Quando você cria uma função, e passa a referência dessa função para o `addEventListener`, ele sabe que a função está em memória, e onde ela se encontra pra ser executada =)

> Muito completo seu curso Daciuk, valeu cara!

Fico feliz que está curtindo \o/
