### ISSUE TITLE
Reduce

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#2905]
Boa Tarde Daciuk, estou com uma dúvida quando e em qual situação eu devo utilizar o reduce ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @grodrigues! Os métodos de array, você vai usar dependendo do retorno que você precisa. Por exemplo:

O **map** retorna sempre um novo array do mesmo tamanho do original, mas com os valores transformados, conforme o retorno da função.

O **filter** retorna sempre um novo array **menor** ou do mesmo tamanho do array original, com os valores originais. O que vai dizer se o valor do array vai entrar no novo array ou não é se a função retornar `true`. Ao retornar `false` o valor não entra no novo array.

Já o **reduce** pode retornar qualquer tipo de dado, não somente um array. Esse é basicamente o diferencial dele: você tem um array, e precisa de um objeto, por exemplo, criado à partir desse array: esse é um caso para o `reduce` =)

Você tem um array de números e quer somar todos eles: pode usar o `reduce`.

A ideia dele é basicamente essa: você tem um array, e precisa - à partir dos dados desse array - gerar um outro tipo diferente. Pode até gerar um novo array se quiser, mas normalmente os métodos `map` e `filter` já resolvem esses casos =)

Ficou claro?

**Comment by grodrigues** [comment]
Ahh agora. Sim ficou bastante claro.

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa só avisar =)
