### ISSUE TITLE
[Seção 2, Aula 09] - Operadores Unários

### ISSUE THREAD

**Issue by fga36** [da2k/curso-javascript-ninja#2908]
Boa noite, Fernando
Fiquei só com uma curiosidade referente aos operadores unários, posso utilizar eles em quais situações específicas?
Por exemplo, se tiver um exercício de equação onde o 'x' não pode ser negativo, eu poderei usá-lo?
Se tiver outras situações tbm que poderia me dizer, agradeço.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fga36! Quanto à questão de uso, não se preocupe tanto agora, pois mais pra frente nós vamos ver vários casos de uso do que estamos aprendendo no curso. Essas primeiras aulas do curso vão servir para mostrar o que podemos ou não fazer com a linguagem. 

Quando usar, ou qual a é a melhor forma de usar, nós vamos ver mais pra frente. Foque agora em entender como as coisas funcionam, que depois isso vai ficar mais claro, ok? =)

**Comment by fga36** [comment]
Certo Professor! Muito obrigado pela ajuda, farei isso sim.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
