### ISSUE TITLE
Sobre threads

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2909]
Boa noite Daciuk, tudo bem com você ?

Eu estou com uma dúvida a respeito de Threads. Vejo você falando bastante sobre elas durante as aulas. Se não me engano, em uma aula você disse que o navegador fazia uso de uma thread. O que seria isso ? Quem define quantas vou usar ? 

Pelo o que eu entendi, thread é um grupo de coisas a serem executadas por uma parte de um processador. Não sei se estou falando besteira kkk

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Vou te indicar um artigo que fala de forma bem detalhada o que são threads, ok?
https://www.tecmundo.com.br/internet/9669-o-que-sao-threads-em-um-processador-.htm

A partir daí já vai ficar mais claro de entender porque o JavaScript é executado em _single thread_, e porque quando vamos fazer computações muito demoradas precisamos trabalhar de forma assíncrona.

Não sei em qual aula você está, mas mais para o final do curso, vamos falar um pouco mais sobre como trabalhar com computações assíncronas no JS.

Mas qualquer dúvida que você ainda tiver, só avisar =)

**Comment by MatheusDidier** [comment]
Opa, muitissimo obrigado Daciuk! Vou ler sim! Valeu cara

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida que surgir só avisar que a gente reabre a issue =)
