### ISSUE TITLE
Sobre recursividade

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2910]
Boa noite Daciuk, tudo bem ? Ouvi você falando de recursividade(um assunto que eu conhecia bem pouco) e resolvi tentar criar sozinho uma função recursiva, pois acredito que enfrentando o desconhecido é a melhor maneira de treinar a lógica. Porém, vi algo assustador enquanto debugava o código que fiz.

Fiz uma função recursiva para calcular o fatorial de um número(acredito que eu não tenha feito da melhor forma). Acontece que ao debugar, notei que eu consigo chegar no valor que eu quero, porém, após o meu return com o resultado do fatorial de um número, parece que minha função "começa a voltar no tempo " kkkkkk. Os valores passam a voltar o que eram na execução passada de cada chamada da função recursiva. 

Você poderia me dar uma ajuda ? 

  function fatorial(numero){
        return fatorialRecursivo(numero, numero);
    }
    function fatorialRecursivo(resultado, numero){
        resultado = resultado * --numero;
        if(numero == 2){
           return resultado;
        }
        fatorialRecursivo(resultado, numero);
    }

console.log(fatorial(5));

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! O problema do seu exemplo é que você precisa sempre de um valor sendo retornado pela função `fatorialRecursivo` para saber qual o próximo `resultado`. Como você só retorna valor quando `numero` for igual a `2`, não vai funcionar mesmo =)

Nesse caso, você poderia fazer o seguinte para resolver:

Primeiro você checa se número é 2 e retorna `resultado`. Essa é a condição para a função recursiva parar, e normalmente você aplica ela antes de qualquer computação.

Depois disso, você, ao invés de fazer com que `resultado` receba o valor da computação de `resultado * --numero`, você faz  ele receber o próximo resultado, já chamando o `fatorialRecursivo`. Ficaria assim:

```js
function fatorial(numero){
  return fatorialRecursivo(numero, numero);
}
function fatorialRecursivo(resultado, numero){
  if (numero === 2) {
    return resultado;
  }

  resultado = resultado * --numero;
  return fatorialRecursivo(resultado, numero);
}

console.log(fatorial(5));
```

---

Ou ainda, usando uma expressão com o operador ternário:

```js
function fatorial (numero){
  return fatorialRecursivo(numero, numero);
}
function fatorialRecursivo (resultado, numero){
  return numero === 2 ? resultado : fatorialRecursivo(resultado * --numero, numero);
}

console.log(fatorial(5));
```

---

E melhor ainda se você não modificar os valores passados, mas criar suas próprias variáveis sempre que necessário:

```js
function fatorial(numero){
  return fatorialRecursivo(numero, numero);
}
function fatorialRecursivo(resultado, numero){
  var multiplicador = numero - 1
  return numero === 2 ? resultado : fatorialRecursivo(resultado * multiplicador, multiplicador);

}

console.log(fatorial(5));
```

---

Enfim, tem várias formas de criar uma função de `fatorial`, mas tente levar em consideração - sempre que possível - a imutabilidade dos valores. Precisa de um novo valor? Não sobrescreva uma variável, crie uma nova. Dessa forma seu código se torna muito mais previsível e fica muito mais fácil de encontrar bugs, quando surgirem =)

**Comment by MatheusDidier** [comment]
> Oi @MatheusDidier! O problema do seu exemplo é que você precisa sempre de um valor sendo retornado pela função fatorialRecursivo para saber qual o próximo resultado. Como você só retorna valor quando numero for igual a 2, não vai funcionar mesmo =)

Daciuk, isso eu não entendi muito bem. Eu consegui entender o resto, de como fazer funcionar certinho. Mas na minha cabeça, o que fiz está tão logico que ta difícil eu entender. A minha função retorna um valor quando numero for 2, certo ?
 Quando há o return, não há a execução de mais nada na função após isso. Na minha cabeça está assim, se não tiver return, ele vai executar a função de novo, mandando como parametro cada variavel que foi modificada.
Digo, por que preciso colocar como return a execução da função, ao invés de simplesmente mandar ela executar novamente ?

**Comment by fdaciuk** [comment]
O `return` é necessário para a função te devolver a computação do valor anterior. Quando você não usa o `return`, ela não devolve valor algum, e você não guarda esse valor. Então a computação será feita, mas no final ela não vai ter resultado pra exibir =)

**Comment by MatheusDidier** [comment]
Perfeito então Daciuk. O return da função vai servir pra retornar o resultado então! Beleza, muito obrigado!

**Comment by fdaciuk** [comment]
Isso mesmo @MatheusDidier! Ao começar a aplicar recursão na prática, o conceito fica mais claro e mais fácil de entender =)
