### ISSUE TITLE
[Git] Git add, Git push, Git pull

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2947]
Opa, e ai Fernando, tudo bem?

Apesar de ter tido uma experiencia com Git, estive parado durante um tempo e perdi a pratica.
Então resolvi subir os arquivos pro repositório da maneira que você ensina nos videos.

**O problema é que quando eu faço "add ." e depois eu dou um git push os arquivos parecem ser enviados, mas o meu repositório está vazio.**

Já estou no challenge-17 e creio ter perdido tudo o que fiz.

Obs: Antes do challenge 15 eu fazia o push manualmente. Pegava meu código, copiava e colava e depois fazia o commit pelo github mesmo.

@fdaciuk

**Comment by garritanoo** [comment]
Só pra exemplificar

Começo com:
_git commit -a -m "challenge(número correspondente)._

Em seguida eu faço:
_git push --set-upstream origin challenge-(número correspondente)_

**Obs:** "_Número correspondente_" ao exercício que eu estou fazendo.

**Comment by fdaciuk** [comment]
Oi @garritanoo! As correções estão sendo enviadas corretamente. Para navegar no GitHub por cada "branch" que você está criando, só precisa fazer o seguinte:

1) Acesse seu repositório: https://github.com/garritanoo/curso-javascript-ninja

2) Clique no botão para visualizar as branches:

![selection_031](https://user-images.githubusercontent.com/487669/34722962-084277c0-f530-11e7-8043-9ff80a07b6bc.png)

3) Escolha alguma branch:

![selection_032](https://user-images.githubusercontent.com/487669/34723006-311b1404-f530-11e7-83df-2e88f4cd5dd7.png)

4) Olhe no diretório do desafio, e ele está lá!

![selection_033](https://user-images.githubusercontent.com/487669/34723050-542251c4-f530-11e7-8f37-5b174455395e.png)

![selection_034](https://user-images.githubusercontent.com/487669/34723074-61cf1bfe-f530-11e7-8d4b-5b868ba7a4e0.png)

![selection_035](https://user-images.githubusercontent.com/487669/34723102-787bfc0a-f530-11e7-82cb-71b67c76a204.png)

---

Se você tiver qualquer dúvida com relação ao Git, esse tutorial inicial pode te ajudar:
https://rogerdudler.github.io/git-guide/index.pt_BR.html

Qualquer dúvida, só avisar!

**Comment by garritanoo** [comment]
Entendi.
Mas eu achei que quando eu fizesse, por exemplo o challenge-08, automaticamente no branch challenge-08, eu teria os challenges anteriores.

Porque como eu disse, antes estava fazendo manualmente, depois que comecei a fazer pelo terminal.

Outra coisa, o meu "master" sempre fica em branco? ou posso dar o merge de um challenge e ir atualizando ele (master)?

**Comment by fdaciuk** [comment]
Na verdade não. A ideia que eu mostrei no curso é pra que, em cada branch fique somente o desafio referente àquela branch =)

Mas você pode fazer o seguinte: deixe a master "limpa", para o caso de você precisar pegar algum desafio limpo, e crie uma outra branch, "challenges" ou algo assim. Ae você pode fazer merge de todas as branchs com os desafios resolvidos nela =)
