### ISSUE TITLE
Challenge 22 - Call e Apply

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2954]
Boa noite Daciuk, tudo bem ?

Fiquei com uma grande dúvida a respeito da diferença entre as duas chamadas Call e Apply.

Pelo o que eu entendi, o primeiro parametro das duas é o this da minha função, e o segunda, no caso do call é uma função, e no caso do apply um array. Só que ai embolou minha cabeça algumas coisas:

Na aula do arrayLike você disse que era possivel fazer algo mais ou menos assim:

Array.prototype.forEach.apply(arguments, [function(...)...
Esse array do segundo parametro, em que passo a função nele me confundiu bastante. Como o javascript sabe que a primeira posição vai ser a função do forEach ? Não sei se fui claro.

Algumas considerações que fiz: 
Pelo o que eu entendi, no apply é possivel passar os arguments em forma de array: [1, 2, 3, 4]
Já no call, se passa os arguments normalmente: 1, 2, 3, 4

Só que no challenge, quando você vai executar a função sum, você utiliza do apply, pois extraimos um array a partir da entrada do usuario. Só que a gente fez dessa forma: sum.apply(sum, numbers). Por que eu passo o sum como parametro ? 

Acho que embaralhei demais as coisas, peço desculpas por isso!

Mais resumindo, a duvida principal mesmo é qual a diferença entre apply e o call ? E as minhas considerações estão corretas ?

Muitissimo obrigado pela atenção! Suas aulas são show

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier!

Sobre as diferenças entre .call e .apply: basicamente as duas funções fazem exatamente a mesma coisa: executam uma função, injetando um "this" na função (que não é obrigatório, podemos usar null se não precisarmos injetar um "this"), e passando parâmetros para a função principal.

A diferença entre elas é a forma que você passa os parâmetros: você pode usar o `call` sempre que souber a quantidade de parâmetros que você tem e vai passar para a função. Já o `apply` você usa quando não tem essa informação. 

O `call` recebe quantos parâmetros forem necessários, e, à partir do segundo, ele passa para a função. Já o `apply` recebe só dois: o "this" a ser injetado e um array. Quando a função for executada, cada parâmetro do array será passado de forma independente para a função.

Vamos a um exemplo pra tentar deixar mais fácil de compreender. Imagine uma função que retorna o maior número de dois passados:

```js
function greater (x, y) {
  return Math.max(x, y);
}
```

Você ainda poderia usar o `Math.max` com o `call` ou com o `apply` se quisesse, por saber que só dois parâmetros serão passados para a função:

```js
function greater (x, y) {
  return Math.max.call(null, x, y);
}
```

E Usando apply:

```js
function greater (x, y) {
  return Math.max.apply(null, [x, y]);
}
```

Veja que, usando `apply`, você precisa passar um array no segundo parâmetro. Isso vai fazer com que, quando a função `Math.max` for executada, o `x` e o `y` sejam passados pra ela não como um array no primeiro parâmetro, mas cada item desse array vai ser passado como um argumento na função. Então isso:

```
return Math.max.apply(null, [x, y]);
```

É o mesmo que:

```
return Math.max(x, y);
```

Basicamente essa é a diferença entre `call` e `apply`.

Agora pense no seguinte: e se você quisesse, por exemplo, saber quem é o maior número, mas o número de parâmetros fosse variável? Ou seja: você poderia passar quantos parâmetros quisesse? Como você faria?

Nesse caso, podemos usar o `arguments`, que não é um array, mas é um array-like, ou seja: ele tem o mesmo formato de um array, podendo pegar os itens dele à partir do índice (`arguments[0]`, `arguments[1]`) e ainda tem o `length` (`arguments.length`) pra saber quantos itens foram passados, mas ele não herda do construtor Array, logo ele não tem métodos de array. Isso significa que ele não é um array de verdade, mas um tipo de dado "parecido" com um array.

Bom, sabemos que o `apply` precisa de um array no segundo parâmetro para ser passado cada item como argumento para função, mas ele não precisa de um array de verdade, pois ele não usa nenhum método do array. Ele só precisa das posições de cada item no array pra passar pra função na ordem que estiverem nesse array. Nesse caso, um array-like serve, pois resolve o nosso problema.

Sabendo disso, podemos reescrever a função acima da seguinte forma:

```js
function greater () {
  return Math.max.apply(null, arguments);
}
```

Isso vai fazer com que todos os argumentos passados para a função `greater` sejam também passados para a função `Math.max`.

Se você usasse o `call`, só seria passado um argumento para a função `Math.max`: o array-like que está em "arguments". E essa função não espera um array como argumento, mas sim números.

Ficou mais clara a diferença?

**Comment by MatheusDidier** [comment]
Entendi! Ficou muito mais claro agora Daciuk, muitissimo obrigado!

**Comment by fdaciuk** [comment]
Legal, qualquer coisa só avisar!
