### ISSUE TITLE
Sobre addEventListener

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#2961]
Boa tarde Daciuk, tudo bem ?

Fiquei com uma dúvida a respeito do terceiro parametro passado para a função addEventListener.
Geralmente, durante as aulas, quando usamos essa função, colocamos false no parametro.

Fui dar uma pesquisada, e encontrei no doc do mozilla falando o seguinte: "Se true, o evento pode ser acionado por conteúdo não-confiável." 
Mas ainda não saquei muito bem. O que seria acionar por conteúdo não confiável ? 

Valeu Daciuk!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Esse parâmetro, em resumo, é para informar a ordem em que os eventos são disparados, quando você tem um elemento HTML dentro de outro, e os dois, tanto o pai quanto o filho têm eventos atrelados a eles.

Exemplo:

Dado o seguinte HTML:

```js
<div>
  <a href="#">Link</a>
</div
```

Vamos adicionar eventos tanto para a `div` quanto para o `a`:

```js
var div = document.querySelector('div');
var a = document.querySelector('a');

a.addEventListener('click', function (e) {
  e.preventDefault();
  alert('clicou no a!');
}, false);

div.addEventListener('click', function (e) {
  alert('clicou na div!');
}, false /* mude aqui para true e veja a diferença */);
```

Se você executar esse exemplo (deixei ele [funcionando aqui](https://codepen.io/fdaciuk/pen/opqzXL) pra você testar), ao clicar em cima da palavra "Link", você verá os "alerts" na ordem:

```
clicou no a!
clicou na div!
```

Essa ordem é a ordem "natural", propagando o evento de baixo pra cima, desde o elemento mais "profundo" que foi clicado - no caso, o `<a>` - até o seu pai que também tem um evento, e também foi clicado, visto que o `a` está dentro da `div`.

Se você alterar o `false` do evento da `div` para `true`, vai ver que agora o evento da `div` é disparado primeiro. Faça o teste e altere para `true` onde está comentado. O resultado vai ser os alerts na ordem:

```
clicou na div!
clicou no a!
```

Ou seja: o evento agora vai propagar de cima pra baixo.

Ficou claro? =)

---

Sobre o seu comentário:

> "Se true, o evento pode ser acionado por conteúdo não-confiável."

Não encontrei isso na documentação. Pode passar o link aqu pra eu dar uma olhada? Acredito que não se trata especificamente desse parâmetro, pois essa API foi atualizada, e agora você pode passar novos parâmetros. Provavelmente essa informação é sobre os novos parâmetros adicionados :)

**Comment by MatheusDidier** [comment]
Daciuk, ficou muito claro sua explicação. Agora entendi muito bem! Fiz os testes conforme sua explicação, e ficou muito claro.

O link em que eu havia visto foi esse https://developer.mozilla.org/pt-BR/docs/Web/API/Element/addEventListener . Entretanto, fui dar outra olhada, pra ver o porquê de eu não ter entendido, e vi que o erro foi meu. Vi esse parametro de usarCaptura em uma posição errada!
Valeu Daciuk!

**Comment by fdaciuk** [comment]
Ah, show! Qualquer coisa só avisar :D
