### ISSUE TITLE
[Aula 01] Como enviar a tarefa para a correção?

### ISSUE THREAD

**Issue by robysonagenor** [da2k/curso-javascript-ninja#2965]
Olá Fernando,
Tudo bem?

Fernando, iniciei meu curso sobre JavaScript hoje. Adorei a primeira aula. Como já fiz um curso básico sobre "Ruby", percebi que existe muita similaridade entre as duas linguagens. Pelo menos no início. Enfim, na verdade a minha dúvida é sobre como faço para lhe enviar o exercício após sua execução. Algumas imagens que aparecem no seu vídeo de explicação estão diferentes para mim. Por exemplo, para mim não aparece aquela mensagens sutil em "rosa" falando sobre o tempo em que atualizei o exercício, e principalmente não aparece ao lado direito o botão "Compare & pull request" para eu cliclar. Portanto, não consigo te enviar o exercício finalizado. Para simplificar, tirei prints das visões: 
**Imagem 01)**- é o que se vê através do seu vídeo de explicação;
**Imagem 02)**- é o que vejo através da minha perspectiva.

Muito obrigado pela atenção :)
Robyson

![imagem02](https://user-images.githubusercontent.com/33930115/34746013-b131e11a-f579-11e7-9bcc-fe64b235bf68.png)

![imagem01](https://user-images.githubusercontent.com/33930115/34745772-be838482-f578-11e7-9745-3ad218f86ac2.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @robysonagenor! Tudo ótimo, e contigo? =)

Dá uma olhada na issue https://github.com/da2k/curso-javascript-ninja/issues/2368, que eu mostrei exatamente isso =)

Como o GitHub foi atualizado, então tem algumas diferenças mesmo na nova interface :)

Mas se ainda tiver dúvidas, pode perguntar que eu reabro a issue aqui, ok? =)

**Comment by robysonagenor** [comment]
Bom dia!

Obrigado pela explicação. Já te enviei o exercício finalizado!

Fernando, tenho mais três dúvidas:

1) Por que toda vez antes de vc digitar alguma linha de código no programa
"Node" (baixei e instalei oq vc falou), vc digita a frase em cor azul
"curso-js-nija". Não fiz isso nenhuma vez enquanto faço meus exercícios.
Sinceramente, não entendi o porquê;

2) Baixei o programa "Git" num site qualquer e o instalei. Fique em dúvida
na hora da instalação sobre o padrão do "Git" que eu deveria marcar. Fiz um
print dessa imagem e estou te enviando em anexo a opção que deixei marcada;

3) Mesmo com dúvida sobre a instalação do "Git" segui em frente. Porém,
após a instalação, quando tento abir o "Git" para digitar os códigos do seu
vídeo, não aparece a tela em cor preta para eu digitar. Ao invés disso,
aparecem três links em cor azul pedindo para eu inserir algum tipo de
informação que não entendo. Eu imagino que talvez seja porque eu tenha que
configurar o "Git" primeiro. Se eu realmente tiver que configurá-lo, vc
pode, por favor, me ajudar?

Estou adorando o curso. Estou super motivado. Eu por eu ter tido um contato
inicial com "Ruby", estou conseguindo assimilar o conteúdo do curso bem
tranquilo. Na verdade, a minha dificuldade tem sido na preparação do
ambiente de trabalho (instalar e configurar programas).


Atenciosamente,

Robyson Agenor

2018-01-10 10:40 GMT-02:00 Fernando Daciuk <notifications@github.com>:

**Comment by fdaciuk** [comment]
Oi @robysonagenor! Vamos lá:

> 1) Por que toda vez antes de vc digitar alguma linha de código no programa
"Node" (baixei e instalei oq vc falou), vc digita a frase em cor azul
"curso-js-nija". Não fiz isso nenhuma vez enquanto faço meus exercícios.
Sinceramente, não entendi o porquê;

Na verdade eu não digito.. esse é o prompt do meu terminal. Eu deixei configurado para exibir o diretório em que eu estou atualmente, por isso aparece o nome "curso-js-ninja", pois esse é um diretório do meu computador que eu estou nele, quando estou usando o terminal. Ele fica sempre visível antes de cada comando =)

---

> 2) Baixei o programa "Git" num site qualquer e o instalei. Fique em dúvida
na hora da instalação sobre o padrão do "Git" que eu deveria marcar. Fiz um
print dessa imagem e estou te enviando em anexo a opção que deixei marcada;

Respondendo e-mail para uma issue do GitHub o anexo não chega. Você pode responder direto aqui na issue e arrastar a imagem para esse campo onde você escreve o texto, que o GitHub já faz um upload dessa imagem automaticamente pra você =)
Ou você pode ainda subir em algum outro lugar e colar o link aqui pra eu ver =)

---

> 3) Mesmo com dúvida sobre a instalação do "Git" segui em frente. Porém,
após a instalação, quando tento abir o "Git" para digitar os códigos do seu
vídeo, não aparece a tela em cor preta para eu digitar. Ao invés disso,
aparecem três links em cor azul pedindo para eu inserir algum tipo de
informação que não entendo. Eu imagino que talvez seja porque eu tenha que
configurar o "Git" primeiro. Se eu realmente tiver que configurá-lo, vc
pode, por favor, me ajudar?

Claro que ajudo =)
Não sei se você já tinha trabalhado alguma vez com terminal. Você está usando windows? Se sim, normalmente é mais chatinho de usar terminal no windows mesmo, mas não se preocupe que vai funcionar também =)
Só use algum dos terminais que eu recomendei no início do curso, que vai facilitar seu trabalho.
Para ter uma base inicial para configurar e trabalhar com git, recomendo que você dê uma lida nesse tutorial:
https://rogerdudler.github.io/git-guide/index.pt_BR.html

Tem também um curso gratuito do Willian Justen que vai te ajudar a começar, recomendo você fazer ele pra ficar mais fácil acompanhar as aulas:
https://www.udemy.com/git-e-github-para-iniciantes/

---

Acho que, com essas dicas, já vai ficar mais fácil você seguir em frente! Se ainda tiver qualquer dúvida, só avisar! =)

**Comment by robysonagenor** [comment]
Boa tarde!

Obrigado pelas explicações anteriores, Fernando!
Já te enviei o challenge 01.

Fernando, segui seu conselho e inicie o curso do Willian Justen sobre "Git e GitHub". 

Contudo, ainda não consegui resolver o meu problema. O Willian até mostra o lugar exato onde se deve baixar o "Git", porém, a minha dificuldade é na hora de instalar e configurar o "Git" para poder iniciar a digitar as linhas de códigos. No caso, o Willian simplesmente baixa o programa e já começa a digitar linhas de códigos na tela preta. Mas até agora não encontrei essa tela preta porque quando abro "Git" para digitar os códigos, não aparece essa tela em cor preta para eu digitar. Ao invés disso,
aparecem três links em cor azul pedindo para eu inserir algum tipo de
informação que não entendo.

Segue print da tela:
![git imagem](https://user-images.githubusercontent.com/33930115/34841355-1eb9394c-f6ef-11e7-8973-910b6c51f004.png)

Talvez esse problema pode ser porque eu marquei alguma opção errada na hora da instalação. Aliás, na hora da instalação fiquei com dúvida em dois momentos. Seguem os prints das opções que deixei marcado na hora da instalação. Fiquei em dúvida sobre qual opção marcar.

![instalacao git01](https://user-images.githubusercontent.com/33930115/34841306-f7a0bac4-f6ee-11e7-9e6a-1491890027f2.png)

![instalacao git02](https://user-images.githubusercontent.com/33930115/34841281-e53eb73c-f6ee-11e7-855a-2157ba5755d4.png)

Desculpa pelo incomodo. Sei que para vc deve ser a coisa mais estúpida do mundo, mas o problema é que nunca utilizei nenhum terminal. Desde o momento que comecei a aprender sobre programação até o início do seu curso, só tinha utilizado o editor de textos "sublime text".

**Ah, o sistema operacional do meu note é o "Windows 7".**

Atenciosamente,
Robyson Agenor

**Comment by LucasGabrielSI** [comment]
Cara, boa tarde, vai no local dos arquivos que você quer enviar, clica com
o botão direito e vai na opção Git bash

Em 11 de jan de 2018 3:56 PM, "robysonagenor" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Oi @robysonagenor! O @LucasGabrielSI deu a dica do que você precisa fazer =)

**Comment by robysonagenor** [comment]
Fala @LucasGabrielSI e @fdaciuk , tudo bem?
Agradeço as dicas, porém ainda não entendi nada. Não consigo abri o Git para digitar as linhas de código.

Farei o curso sem enviar as tarefas mesmo. Afinal, sempre tem as correções no final de cada aula.

Abraço,
Robyson

**Comment by fdaciuk** [comment]
Oi @robysonagenor! O que o @LucasGabrielSI comentou seria basicamente você, ao abrir o explorer, onde está a lista de arquivos do seu projeto, você clica com o botão direito ali e manda abrir com o Git Bash =)

Fazendo isso, um terminal do Git será aberto já no diretório que você está =)

De qualquer forma, você não precisa obrigatoriamente enviar os desafios, mas ao menos tente fazer eles na sua máquina, para praticar, ok? :D
