### ISSUE TITLE
setTimeout and setInterval 

### ISSUE THREAD

**Issue by LucasGabrielSI** [da2k/curso-javascript-ninja#2970]
Olá professor, boa noite, poderia explicar um pouco mais sobre setTimeout e setInterval, o assunto bugou um pouco minha cabeça e não consegui entender muito bem a utilidade e como eles funcionam realmente, principalmente o setInterval. Grato desde já pelo feedback, abraço! 👍 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @LucasGabrielSI! Vamos lá =)

Antes de entrar mais a fundo no assunto, deixa eu te perguntar: você conseguiu compreender bem como funcionam os eventos, e o que é código síncrono e código assíncrono?

**Comment by LucasGabrielSI** [comment]
Sim, essa parte eu consegui entender, complementei a aula lendo alguns
artigos.

Em 10 de jan de 2018 10:03 AM, "Fernando Daciuk" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Legal! Bom, então: basicamente o `setTimeout` e o `setInterval` servem para criar ações assíncronas. A função passada para esses métodos é sempre executada após o tempo em milissegundos passado no segundo parâmetro.

A diferença entre elas é que a função passada para o `setTimeout` é executado apenas uma vez após o tempo passado. Já o `setInterval` fica eternamente executando, até que você use o `clearInterval` ou feche a página onde o `setInterval` está sendo executado :)

Era isso que você tinha ficado em dúvida?

**Comment by LucasGabrielSI** [comment]
Show, obrigado professor!

Em 10 de jan de 2018 11:05 AM, "Fernando Daciuk" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
