### ISSUE TITLE
Desafio 20, sobre a função isValidEmail

### ISSUE THREAD

**Issue by Moraissz** [da2k/curso-javascript-ninja#2990]
Boa tarde Daciuk, tive uma dúvida na regex, estava criando a regex no site regex101, e consegui, pórem, fiquei com uma dúvida.
![duvidaregex](https://user-images.githubusercontent.com/32682312/34794804-0139ac3e-f637-11e7-9abd-fc1e278bccbe.png)
Basicamente a diferença das duas é apenas o final.  As duas formas funcionaram para os emails, porém eu não entendi porque a primeira forma funcionou. Então, ela funcionou por que depois do ? que é o opcional, depois dele tudo fica opcional?
Porque analisando a expressão 
![duvidaregex](https://user-images.githubusercontent.com/32682312/34794961-939a4d9a-f637-11e7-8820-fa90a61e2bb2.png)
deixa o significado que o email deve terminar com 1 ou 2 caracteres alfanuméricos correto? testei o email "sandro@culinaria.dahora" é funcionou, no caso, ele termina com 4 caracteres alfanuméricos.(Mas ele é opcional ? , mesmo com o sinal antes dele ? )
Por isso fiquei na duvida.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Moraissz! Na verdade, é assim: o `?` vai dizer que é opcional o caractere que estiver à esquerda dele, ou seja, o que vem antes.

No caso da primeira regex, o que é opcional é apenas o caractere representado pelo ponto, que está dentro de `(?:.)?`. Esse último sinal de interrogação diz que esse caractere é opcional.

Já na segunda regex, você está dizendo que todo o final da regex é opcional (tudo o que está nos parênteses):

```js
(?:.\w{1,2})?
```

Veja que você diz nessa regex que o final é opcional, pois tem uma interrogação logo após os parênteses.

Só não confunda essa interrogação de fora com a interrogação seguida de dois-pontos, dentro dos parênteses. `(?:)` esse sinal significa para apenas "agrupar" valores na regex e **não fazer captura**, diferente do sinal de interrogação que fica fora dos parênteses, significando que aquele caractere é opcional =)

Ficou claro?

**Comment by Moraissz** [comment]
Entendi, Fernando, porém, porque a primeira regex dá certo(casa) pro email "sandro@culinaria.dahora", sendo como eu não coloquei opcional no 
![duvidaregex](https://user-images.githubusercontent.com/32682312/34849414-727d1d04-f709-11e7-8129-3d5e7f357f4b.png)
ela deveria não dar match, já que não termina com no máximo dois caracteres, correto?

**Comment by fdaciuk** [comment]
Na verdade esse final seria qualquer coisa que vier depois de `.dahora`. O que está casando com `.dahora` é o `\w{2,}` que vem antes desse final :)

**Comment by Moraissz** [comment]
Entendi.
Obrigado!
