### ISSUE TITLE
[Desafio #20] $inputUsername e $inputEmail

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2994]
E aí, Fernando, beleza?

Nesse exercício nas duas var que eu declarei: 

var $inputUsername = document.querySelector('[type="text"]');
var $inputEmail = document.querySelector('[type="email"]');

E na sua correção está assim:

var $inputUsername = document.querySelector('input[**type**="text"]');
var $inputEmail = document.querySelector('input[**type**="email"]');

Ambas as formas estão corretas?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @garritanoo! Sim, as duas formas estão corretas. A diferença é apenas o que o seletor vai buscar: no meu exemplo, eu adicionei `input` para que ele busque o atributo `type` apenas em tags do tipo `input`. Colocando como seletor apenas o atributo, todas as tags serão verificadas, até que alguma com o atributo `type="text"` seja encontrado =)

É meio que tentar dar menos trabalho para o browser =)

**Comment by garritanoo** [comment]
Entendi.
Obrigado!
