### ISSUE TITLE
[Desafio #20] addEventListener

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#2998]
Opa!

Meu código está assim:

$button.addEventListener('click', function(event) {
		event.preventDefault();
		if (!$inputUsername.value)
			return alert('Preencha com o nome de usuário!');
		if (!$inputEmail.value)
			return alert('Preencha com o email!');
		if (!isValidEmail($inputEmail.value))
			return alert('Entre com um email válido]');
		if (!$message.value)
			return alert('Preencha a mensagem!');
		if (!confirm('Tem certeza de que deseja enviar o formulário?'));
			alert('Não enviado!')
		return alert('Enviado com sucesso!');
	}, false);

Mas quando eu envio o formulário ele dá esse erro:

_Uncaught TypeError: Cannot read property 'addEventListener' of null_

O que pode ser?

@fdaciuk

**Comment by garritanoo** [comment]
Consegui resolver.

**Comment by fdaciuk** [comment]
Show! =)
