### ISSUE TITLE
[Desafio 12] - Erro ao transformar array em objeto

### ISSUE THREAD

**Issue by brunogbr** [da2k/curso-javascript-ninja#3003]
To recebendo um erro quando tento converter o array de volta para objeto, já fiz igual na aula e mesmo assim da erro, o código: https://repl.it/@BrunoGoncalves/errro 

```
books = [];
books.push({name:'Harry Potter', pages: 400});
books.push({name: 'Volta 80 dias', pages:200});
books.push({name:'Js Ninja', pages: 300});
console.log(JSON.stringify(books)); // funciona

/*
  Converta os livros novamente para objeto.
  */

books = JSON.parse(books);  // erro 
console.log(books);
```

Erro: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    at eval:11:9

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brunogbr! O erro acontece porque nenhum dos métodos do objeto `JSON` causam efeito colateral, modificando o valor da variável. Quando você roda:

```js
console.log(JSON.stringify(books)); // funciona
```

e diz que esse código funciona, você apenas exibiu no console o valor de `books` em formato de _string_, mas ele continua sendo um objeto. Para que `books` receba o objeto "stringificado", você precisa atribuir esse resultado à variável novamente:

```js
books = JSON.stringify(books);
console.log(books);
```

Dessa forma, você acaba de modificar e reatribuir o valor da variável `books`, que antes era um objeto, mas agora sim se tornou uma _string_ que você consegue "parsear" pra objeto novamente :)

No caso do seu código, o erro aconteceu porque você tentou parsear um objeto, não uma string.

Ficou claro? =)

**Comment by brunogbr** [comment]
Ficou sim, obrigado.

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar =)
