### ISSUE TITLE
DOM Fragment e performace

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3007]
Daciuk, tudo bem ?

Cara, eu achei muito genial e interessante o lance do Fragment. Fiquei mais fascinado ainda quando entendi que colaboraria bastante na performace. Fiquei curioso pra ver a diferença entre eu criar o fragment e acessar diretamente o document. 

Usei aquela função do browser que você ensinou na aula de debug: console.time e console.timeEnd

Minha surpresa foi ver que a execução do fragment foi  mais demorada do que a do acessando diretamente a DOM. Gostaria de saber se realmente há alguns casos que isso acontece, ou se eu fiz alguma coisa errada! Muito obrigado! 

JAVASCRIPT
```js
(function(window, doc){

    var fragment, linha, coluna;

        console.time("fragment");
         fragment = doc.createDocumentFragment();
        for(i = 0; i < 4; i++){
             linha = doc.createElement("tr");
            for(j = 0; j < 10; j++){
                 coluna = doc.createElement("td");
                linha.appendChild(coluna);
            }   
            fragment.appendChild(linha);
        }
        doc.querySelector(".table1").appendChild(fragment);
        console.timeEnd("fragment");


        console.time("normal");
        var $tabela = doc.querySelector(".table2");
        for(i = 0; i < 4; i++){
             linha = doc.createElement("tr");
            for(j = 0; j < 10; j++){
                 coluna = doc.createElement("td");
                linha.appendChild(coluna);
            }
            $tabela.appendChild(linha);
        }
        console.timeEnd("normal");
        

    
})(window, document);
```

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @MatheusDidier! Bom, na verdade, esse teste é bem falho xD
Faça o seguinte teste: altere a ordem, fazendo o teste "normal" antes do "fragment", e veja o fragment ser bem mais rápido xD

Como você pode ver, reaproveitar variáveis, fazendo um teste logo após o outro não vai te trazer um resultado real, ou ao menos próximo disso. A ordem implica bastante no resultado.

Outro ponto de erro: testar com apenas 4 itens não faz muito sentido. Para testar performance, tem que testar com muitos, muitos itens mesmo, além de tentar manter o mesmo uso de memória / processamento para cada teste.

Então assim: se quiser testar algo que seja mais "próximo" da realidade, uma ferramenta que pode ajudar é o https://jsperf.com/

Ali você consegue criar alguns casos de teste para comparar dois ou mais tipos de código.

Mas leve em consideração que existem vários fatores que irão influenciar em testes no browser:
- memória usada no momento do teste;
- aplicações rodando no momento do teste;
- browser usado no momento do teste;
- etc.

É bem difícil chegar em um resultado "real", mas você consegue ter uma noção. Cada browser pode fazer suas próprias otimizações de performance, então de browser pra browser vc pode ter diferença nos resultados =)

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
