### ISSUE TITLE
challenge-02 git push

### ISSUE THREAD

**Issue by marinhoOliv** [da2k/curso-javascript-ninja#3009]
fala Fernando, blza man?
Estou com um erro ao executar o 'push':
ERROR: The key you are authenticating with has been marked as read only.
não consigo alterar o status da key. Poderia me ajudar nisso?
abs

@fdaciuk

**Comment by marinhoOliv** [comment]
Valeu @fdaciuk eu não estava marcando o check box para permitir a escrita.

**Comment by fdaciuk** [comment]
Boa! =)
Qualquer coisa avisa ae :D
