### ISSUE TITLE
Sobre AJAX e Requisições

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3020]
Daciuk, tudo bem ?

Ajax é um assunto completamente novo pra mim, e não consegui, infelizmente, consolidar algumas coisas.

Pelo o que eu entendi, ajax me permite fazer requisições ao meu servidor de maneira assincrona, ou seja, sem comprometer minha thread principal. Porém algumas coisas eu não entendi muito bem:

Na aula 28 fazemos isso aqui

    ajax.open("GET", '/');

GET, pelo o que eu entendi, é o metodo que vai me retornar o que eu requisitei, certo ? Nesse caso foi a raiz. Mas não entendi muito bem isso. Porque requisitar pro meu servidor a raiz, que seria o HTML ?

E não entendi muito bem aquele lance de header, que é o estagio 2 do readyState. O que é ele ?

Desculpa a enxurrada de perguntas, mas sinto que é um assunto bem importante, e você tem uma didática ótima, então não tem como eu não aprender.

Valeu Daciuk!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! A ideia do Ajax é fazer com que, através do objeto `XMLHttpRequest`, você consiga comunicar o frontend da sua aplicação com o backend, recebendo assim uma resposta, sem que seja necessário "recarregar" a página.

O grande ponto chave aqui é o protocolo HTTP. Ele é o responsável por receber e enviar informações, que faz com que seja possível a comunicação de um servidor com o browser, por exemplo.

Quando você acessa uma URL qualquer, o que acontece por baixo dos panos é uma requisição HTTP do tipo "GET", que nesse caso significa "pegar", "obter". Esse tipo de requisição normalmente é feito para "obter" alguma informação de algum lugar.

No nosso exemplo, nós fizemos um "GET" para a raiz da nossa aplicação, e com isso nós obtemos todo o HTML que é exibido quando você acessa a aplicação em si =)

Para tentar deixar mais claro, é importante conhecer um pouco mais sobre o protocolo. Dê uma lida nesse artigo, que com certeza vai ficar mais fácil de compreender o assunto:
https://nandovieira.com.br/entendendo-um-pouco-mais-sobre-o-protocolo-http

Qualquer dúvida, só avisar =)

**Comment by MatheusDidier** [comment]
Perfeito Daciuk, muitissimo obrigado cara! Vou ler esse artigo que você passou!

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa avisa ae =)
