### ISSUE TITLE
Aula29 - Execução app().init()

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3028]
Daciuk, tudo bem ?

Cara, fiquei com grandes duvidas a respeito da necessidade de uma função retornar um objeto que tem varias funções nele, e executar o init.

Entendo que seja uma boa pratica, mas ainda não entendi muito bem. Acho que é porque não entendi muito bem o porque do module pattern. Seriam boas praticas pra no futuro fazer testes unitarios ? Tipo, pra nosso sistema ficar menos dependente, e a gente conseguir executar funções em qualquer lugar ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Primeiramente quero dizer que é bastante comum ter essa dúvida, pois quando nós ainda não sentimos necessidade de algo, fica mais complicado de entender  a real necessidade daquilo.

Eu só consegui entender de fato a ideia de usar módulos quando eu precisei, mas vou te dar um resumo do que você precisa saber para entender quando usar ou não módulos, ok? =)

Você já viu no curso sobre escopo, já sabe que é importante manter código de forma local (dentro de funções) pois no escopo global qualquer valor está suscetível a ser alterado, o que pode trazer vários tipos de problemas. Por exemplo: dois lugares alterando, ao mesmo tempo, o mesmo valor global. Fica difícil então saber qual o real valor de uma variável global, pois ela pode ser alterada de qualquer lugar.

Outro ponto que passamos antes de usar módulos: quando você começa a escrever uma aplicação usando muito JavaScript, o código tende a ficar gigantesco. Escrever todo o código em um único arquivo é ruim, pois é complicado ficar rolando pra cima e pra baixo pra tentar descobrir o que cada variável / função / etc. está fazendo.

Esse é o momento em que você começa a pensar em módulos. Você separa o seu código, colocando em cada arquivo partes comuns da sua aplicação.

Imagine que você está fazendo um site que tenha várias interações: um banner rotativo, um accordion que, ao clicar em um todos os outros fecham, um formulário onde você precisa fazer algumas validações dos campos antes de enviar o valor para ser salvo, etc.

Já pensou tudo isso em um único arquivo, ou mesmo compartilhando o mesmo escopo? Ficaria praticamente impossível de dar manutenção se surgisse algum problema.

Os módulos servem para isso: você isola as partes comuns do código em módulos, e assim consegue trabalhar de forma muito mais organizada na sua aplicação. Você pode colocar o código relacionado ao accordion em um módulo, o código para o banner rotativo em outro, a validação de formulário em outro, etc.

Essa é basicamente a ideia dos módulos: facilitar a organização do código =)

Com isso, você consegue também ter mais previsibilidade do código, pois vai usar todos os módulos apenas de forma local. Quando precisar usar algo daquele módulo em outro local, reaproveitando o mesmo código, você consegue "exportar" aquela funcionalidade pendurando o método no objeto `window`, que é global, e comum (acessível) à partir de qualquer parte da aplicação =)

O uso dos módulos vai ficar mais claro quando você começar a criar aplicações, e ver elas crescendo.

Não se preocupe que esse é um processo natural. Erre bastante, teste, pratique, que no momento certo você vai conseguir compreender a real necessidade de tudo o que está aprendendo aqui no curso! =)

Acho que é isso. Qualquer dúvida, pode perguntar =)

**Comment by MatheusDidier** [comment]
Caraca, show a sua explicação Daciuk!
Entendi, vou segurar um pouco minha ansiedade mesmo e saber que é um processo natural.
Mas ficou mais claro, seria uma forma de organização do código, e com isso eu posso até estabelecer comunicação entre meus scripts, correto ? Utilizando o objeto window como parametro.
E também entendi o porquê de ser uma boa pratica, já que vou  separar muito bem os scripts e delegar à eles suas funções, como você disse:

> Um banner rotativo, um accordion que, ao clicar em um todos os outros fecham, um formulário onde você precisa fazer algumas validações dos campos antes de enviar o valor para ser salvo, etc.

Achei show mesmo cara, muito obrigado!

**Comment by fdaciuk** [comment]
Massa! =)

> Mas ficou mais claro, seria uma forma de organização do código, e com isso eu posso até estabelecer comunicação entre meus scripts, correto ? Utilizando o objeto window como parametro.

Exatamente! =)

Qualquer coisa avisa ae :D
