### ISSUE TITLE
Erro esquisito na declaração de variaveis

### ISSUE THREAD

**Issue by silvioCoelho** [da2k/curso-javascript-ninja#303]
(function(win, doc) {
  'use stric';
  var $inputNumber = doc.querySelector( '[data-js="input"]' );
  var $numberBtn = doc.querySelectorAll( '[data-js="btnNumber"]' );
  var $operatorBtn = doc.querySelectorAll( '[data-js="operatorBtn"]' );
  $equalBtn = doc.querySelector( '[data-js="equalBtn"]' );
  var $ceBtn = doc.querySelector( '[data-js="ceBtn"]' );

})( window, document);

nesse codigo ele só consegue achar o $qualBtn que é qual eu nao usei a palavra var antes, todos os outros quando eu invoco ele diz que não foi declarado! agora se eu tirar a palavra var eu consigo invocar. ce sabe qual é o problema doido que ta ocorrendo?

**Comment by ffabiorj** [comment]
Cara, vc não consegue acessar, pq a palavra var restringe a variável dentro da function como local. Quando vc criar um variável sem a palavra var o interpretador do Js interpreta aquilo como variável global, mais vc só consegue acessar ela depois que você chama a função uma vez.

**Comment by silvioCoelho** [comment]
po, valeu @ffabiorj. foi vacilo meu, eu tava tentando testar pelo console se o valor estava sendo  atribuída a variavel, mas podia ter testado com um simples console.log dentro da function. valeu pelo salve

**Comment by ffabiorj** [comment]
Tranquilo cara.

**Comment by fdaciuk** [comment]
Obrigado pela resposta rápido @ffabiorj :)
É exatamente essa a questão xD
@silvioCoelho, a ideia de usar a IIFE é exatamente essa: restringir o acesso às variáveis somente no escopo da função onde elas foram declaradas :)

Só tem um errinho no seu script: no início, deve ser `use strict`, faltou um `t` :)

Com essa cláusula escrita corretamente, você teria um erro quando tentasse declarar uma variável sem o `var` :D
