### ISSUE TITLE
Dificuldade em prosseguir com o curso!

### ISSUE THREAD

**Issue by LucasGabrielSI** [da2k/curso-javascript-ninja#3044]
Professor cheguei no desafio 23, passei um tempo considerável tentando mais infelizmente não consegui fazer nada além do básico, que foi o HTML e  a captura dos botões mais além disso não consegui prosseguir pois não sabia o que usar, o senhor acha que vale a pena eu continuar o curso, ou Realmente se eu não consegui fazer é porquê não entendi nada até aqui? Eu realmente sinto que se não saiu uma calculadora básica, não vai sair um projeto profissionalmente.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @LucasGabrielSI!

Quando nós estamos tendo contato pela primeira vez com uma linguagem de programação, e ainda não fizemos muito com ela, é **super normal** ter dificuldades em fazer coisas que, olhando outros fazerem, parece simples =)

Deixa eu te explicar uma coisa bastante importante: o aprendizado da linguagem vai vir de forma natural, enquanto você está praticando. Pratique bastante, faça códigos, refaça, tente refazer os desafios feitos até aqui sozinho, e não só uma vez: faça, apague, refaça.

Dessa forma, alguns problemas comuns que estamos resolvendo nos desafios do curso começam a ficar mais "comuns" ao seu cérebro, e é aí que o aprendizado DE VERDADE começa =)

Se você não conseguiu resolver sozinho o desafio, a única coisa que te falta é **praticar mais**! Apenas isso =)

Assista às aulas com as soluções do desafio, e faça a solução junto comigo.

Após isso, apague a solução e tente resolver sozinho.

O processo de aprendizado é assim mesmo. Não se preocupe, pois você **está no caminho certo**!

Lembre-se que ninguém nasce sabendo. O conhecimento vai depender do esforço e de quanto a pessoa pratica, então faça isso, ok? Pratique muito!

E se tiver qualquer dúvida, pode perguntar que eu estou aqui pra te ajudar :D
