### ISSUE TITLE
Challenges - Exercicios Resolvidos

### ISSUE THREAD

**Issue by fga36** [da2k/curso-javascript-ninja#3058]
Professor, tenho gostado deste método de resolução de exercícios que você propõe a cada módulo.
Em certos desafios eu acabo não conseguindo resolver e vejo a resolução feita nos videos.
Mesmo assim, nos meus tempos livres refaço todos os exercicios.
Concluindo: Notei que aquela dificuldade inicial muitas vezes some, consigo resolver os exercícios com mais agilidade e facilidade, sem ao menos olhar para resolução feita.
Seguindo este método de refazer os exercicios, você acredita que também me ajudará no aprendizado? Mas alguma outra dica para acrescentar também?

Muito obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fga36! Legal cara, o caminho é esse mesmo! Como certeza fazer e refazer ajuda muito no aprendizado!

O que eu sempre falo para os alunos é: pratique bastante! Ainda que você não consiga resolver sozinho, assista a solução, depois tente fazer sozinho, e refazer, não só uma vez, mas várias.

É com a repetição e prática que você aprende de verdade =)

E não deixando passar dúvidas. Qualquer coisa que fique subentendido, pode perguntar, só não guarde a dúvida pra você, por mais boba que possa parecer :D 

Esse é o caminho, segue assim que você vai longe!

**Comment by fga36** [comment]
Farei isso sim, com certeza. 
Obrigado mesmo 👍

**Comment by fdaciuk** [comment]
Nada! Qualquer coisa, só avisar =)
