### ISSUE TITLE
aula 12

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#3061]
eu realmente nao consigo entender o que seria o books[i], tipo pelo que entendo o i e de onde comeca o loop for, ai tem uma condicao e depois uma afirmacao no caso 
for(var i = 0; i < books.length; i++){
	for(var prop in books[i]){
		console.log(prop + ':' + books[i][prop])
	}

}
porem ainda nao entendo o que seria o books[i]

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! Vamos lá:

O `for` basicamente fica repetindo até que uma certa condição seja `true`. No caso do primeiro `for`, ele inicia a variável `i` com o valor zero, e ele executará todo o bloco de código quantas vezes forem necessárias, enquanto o `i` for menor `books.length`, ou seja: enquanto o `i` for menor que a quantidade de itens no array `books`. O terceiro parâmetro do `for` diz que, a cada vez que o `for` começar um novo loop, o valor de `i` será incrementado em 1.

Nesse caso, o que acontece? Imagine o array `books` dessa forma:

```js
var books = [
  { name: 'Livro 1', pages: 100 },
  { name: 'Livro 2', pages: 200 },
  { name: 'Livro 3', pages: 300 }
];
```

Veja que eu tenho 3 objetos inseridos no array. Eu consigo pegar um objeto específico através de um índice do array. No caso, se eu chamar:

```js
console.log(books[0]) // { name: 'Livro 1', pages: 100 }
```

Veja que eu peguei o primeiro índice do array (`books[0]`). No primeiro índice, eu tenho o objeto referente ao `Livro 1`. Então `books[i]`, dentro do primeiro `for`, é uma referência a cada uma desses objetos, em ordem. Primeiro, como `i` vai ter o seu valor zero, `books[i]` vai ser o mesmo que `books[0]`.

Quando o `for` for executado novamente, o valor de `i` será incrementado, então ele passará a valor `i + 1`. No caso `0 + 1 = 1`. Agora `i` vale 1, então `books[i]` vai ser igual a `books[1]`.

Deu pra entender a lógica?

No primeiro `for`, nós conseguimos pegar, através de `books[i]`, cada objeto que está dentro do array de forma isolada.

Fazendo isso, nós conseguimos fazer um segundo `for in` por dentro de cada objeto para pegar cada propriedade do objeto.

Então o segundo `for`, onde você criou a variável `prop` que será uma propriedade do objeto `books[i]`, na verdade significa o seguinte:

`books[i]` vai ser um dos 3 objetos no array `books`. Cada objeto tem duas propriedades: `name` e `pages`.

Esse segundo `for` vai iterar por cada propriedade desse objeto, e, uma a uma, vai atribuir à variável `prop` o nome dessas propriedades.

Logo, `books[i][prop]`, na primeira iteração do segundo `for`, e na primeira iteração do primeiro `for`, vai ser o mesmo que `books[0]['name']`. Isso vai retornar o nome do livro =)

Veja que `'name'` é uma string. Lembre-se que, quando nós não sabemos o valor de uma propriedade de um objeto, ou essa propriedade é uma string, precisamos usar os colchetes para obter esse valor do objeto.

No caso, se soubéssemos que esse objeto vai sempre ter só o `name`, poderíamos fazer:

```js
console.log('name:' + books[i].name);
```

Mas como nós queremos pegar todas as propriedades do objeto - independente de quantas sejam - então fazemos um loop para garantir que todas as propriedades serão passadas. Se você adicionar mais propriedades nos objetos, vai ver que todas elas serão corretamente exibidas no console =)

Acho que é isso. Ficou mais claro? =)

**Comment by fdaciuk** [comment]
Oi @leoigel! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
