### ISSUE TITLE
Podemos utilizar somente 1 branch para os desafios?

### ISSUE THREAD

**Issue by Morette** [da2k/curso-javascript-ninja#3063]
Bom dia Daciuk,
procurei por aqui pelo GitHub, mas não encontrei sobre..

Minha dúvida é se eu não poderia criar somente uma branch como por exemplo "challenges" e nesta branch colocar todos os desafios.

Já que estou mudando arquivos diferentes, pensei que não teria problema.

Tentei fazer isso no Challenge-03 e não consegui dar o push, só consegui quando criei uma nova branch.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Morette! Pode fazer isso sim! No curso eu mostrei para deixar um desafio por branch, para que, quando você enviasse o Pull Request, somente os arquivos daquele desafio fossem mostrados como "alterados". Mas não tem problema você fazer os desafios separados, e depois fazer "merge" de cada um em uma branch "challenges" =)
