### ISSUE TITLE
Sobre javascript ser uma linguagem compilada

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3077]
Bom dia Daciuk, tudo bem ?

Eu estava lendo um forum esses dias, e li que javascript é uma linguagem compilada em tempo de execução. 
Eu não entendi muito bem o que quer dizer isso. Também vi outros usos para tipos de linguagems: interpretada, compilada.

O que seriam essas denominações ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Na verdade, JS não é compilado, e sim, interpretado.

Isso significa o seguinte: em linguagens **compiladas**, como Java, C, etc., você escreve código "humanamente legível", e, antes de "servir" esse código, ou antes de disponibilizá-lo para ser utilizado, o código passa por um processo de compilação, que vai transformar (ou compilar) aquele código escrito de forma "humanamente legível" em código de máquina, binário (zeros e uns).

JavaScript não tem compilador, ele é uma linguagem interpretada. Da forma como você escreve seu código, o interpretador da linguagem (que vai estar no browser que você usa, ou mesmo no Node.js) vai reconhecer aquele código e executá-lo.

Esse assunto é bem avançado, se você quiser ter mais conhecimento futuramente sobre isso, você pode fazer uma pesquisa sobre compiladores que vai ajudar =)

Você também pode achar boas informações sobre isso pesquisando por AST e Babel.

O Babel é o que chamamos de "transpiler" de JavaScript. Ele não compila o código, mas com ele você consegue escrever JavaScript com as features mais novas (das versões ES6, ES7, ES8, etc), e o Babel fica responsável por transpilar o código na versão que os browsers conseguem reconhecer, que seria o ES5, que é essa versão que você está aprendendo no curso =)

É um assunto bem legal pra se estudar após terminar o curso :)
