### ISSUE TITLE
Desafio 5

### ISSUE THREAD

**Issue by ffabiorj** [da2k/curso-javascript-ninja#308]
Alguém pra dar um luz aqui no exercício?

/*
Crie uma função chamada `book`, que recebe um parâmetro, que será o nome do
livro. Dentro dessa função, declare uma variável que recebe um objeto com as
seguintes características:
- esse objeto irá receber 3 propriedades, que serão nomes de livros;
- cada uma dessas propriedades será um novo objeto, que terá outras 3
propriedades:
    - `quantidadePaginas` - Number (quantidade de páginas)
    - `autor` - String
    - `editora` - String
- A função deve retornar o objeto referente ao livro passado por parâmetro.
- Se o parâmetro não for passado, a função deve retornar o objeto com todos
os livros.
*/
```
function book(livro){
	livro = { 
		pequenoPrincipe: {quantidadePaginas: 501, autor: 'Jose Silva', editora: 'Novatec'},
		madMax: {quantidadePaginas: 301, autor: 'Jorge', editora: 'Abril'},
		tropoDeElite: {quantidadePaginas: 402, autor: 'Cezar Oliveira', editora: 'Globo'}
		};
		return livro;
};
```
Travei na função.  :/

**Comment by fdaciuk** [comment]
Deu certo agora né? xD
