### ISSUE TITLE
Realizar o comando push

### ISSUE THREAD

**Issue by fga36** [da2k/curso-javascript-ninja#3085]
Quando digito o comando: git push origin challenge-04
aparece:

ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

@fdaciuk

**Comment by fga36** [comment]
Então usei o comando 'git clone ' com a chave do SSH, mas quando aperto o enter, aparece:
git clone git@github.com:fga36/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by fga36** [comment]
Eu configurei a chave conforme o passo a passo do video do challenge 02. Não deu erro no início, mas depois neste challenge 4 começou a dar problemas

**Comment by fdaciuk** [comment]
Os desafios 2 e 3 você conseguiu enviar corretamente?

**Comment by fdaciuk** [comment]
Se sim, então pode ter sido só uma instabilidade no GitHub. Tente novamente pra ver se dá o mesmo erro =)

**Comment by fga36** [comment]
Sim, os desafios 2 e 3 foram enviados normalmente. 
Tentei agora assim como você falou e funcionou normalmente.
Agradeço por  todo suporte.

**Comment by fdaciuk** [comment]
Show! Se antes funcionava e começou a dar timeout, normalmente é problema ou no GitHub ou com sua conexão com internet =)

Que bom que deu certo! Qualquer coisa só avisar =)
