### ISSUE TITLE
Desafio 1 - Challenge 1

### ISSUE THREAD

**Issue by profale** [da2k/curso-javascript-ninja#3102]
Escreva aqui sua dúvida

@fdaciuk
Fiz o meu desafio e até o momento não tive retorno da correção.
Att, Alessandra Ferreira

**Comment by fdaciuk** [comment]
Oi @profale! Pode seguir o curso normalmente! Como o curso já está todo gravado, você pode acompanhar a correção sempre no início da próxima aula =)

Se você tiver qualquer dúvida com relação ao conteúdo, ou à correção que eu mostrei, pode abrir issue aqui que eu te ajudo a entender sua dúvida, ok? =)
