### ISSUE TITLE
Melhorias no desafio 4

### ISSUE THREAD

**Issue by DaniloSAS** [da2k/curso-javascript-ninja#3103]
Fala @fdaciuk , beleza?
Cara, eu fiz o desafio 4 de uma forma que talvez tenha fica mais legal e gostaria que você opinasse. O código foi o seguinte. 
Fiz assim porque quando  add 0 pessoa no carro ele avisa que o carro esta vazio, quando add apenas 1 pessoa ele diz que foi add 1 pessoa no singular, quando vai add mais pessoas ele vai avisando e quando chega a 4 ele avisa que só tem mais 1 lugar, quando chega a 5 ele avisa que lotou o carro e se tentar add mais ele não permite e não add mais pessoas do que quantidade de assentos e a variável quatidadePessoas fica com no máximo 5. 

Diz ai o que achou. Abraço! 

```js
/////////////////////////////////////////////////////////////////////


var carro = {
    marca: 'volkswagen',
    modelo: 'up',
    placa: 'sdk - 3219',
    ano: 2017,
    cor: 'Branco',
    quantasPortas: 4,
    assentos: 5,
    quantidadePessoas: 0
};


//////////////////////////////////////////////////////////////////


 carro.addPessoas = function(x){
    carro.quantidadePessoas += x;

    if(carro.quantidadePessoas <= 3){
        if(carro.quantidadePessoas === 1){
            return 'Já temos '+ carro.quantidadePessoas +' pessoa no carro!' ;

        }else if(carro.quantidadePessoas === 0){
            return 'O carro esta vazio!';
        }
        return 'Já temos '+ carro.quantidadePessoas +' pessoas no carro!' ;

    } else if(carro.quantidadePessoas === 4){
        
        return 'Já temos '+ carro.quantidadePessoas +' pessoas no carro. Só cabe mais '+ (carro.assentos - carro.quantidadePessoas); 

    }else if(carro.quantidadePessoas === carro.assentos){
        return 'Já temos '+ carro.quantidadePessoas +' pessoas no carro. Agora o carro ficou lotado!'

    }else{
        carro.quantidadePessoas = carro.assentos;
        return 'Desculpa, mas o carro já esta cheio!'
    } 
};
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DaniloSAS! Legal =)
Só ficou um problema: se eu tentar adicionar mais de 5 pessoas de uma vez (10, por exemplo), ele deixa entrar as primeiras 5, e mostra a mensagem dizendo que o carro está cheio. Isso dá a impressão de que eu não estou adicionando nenhuma pessoa, apenas que eu não vou conseguir adicionar as 10.

Depois, o carro já estando cheio, mesmo que eu tente adicionar 1 pessoa eu não vou conseguir xD

Deu pra entender o problema? =)

**Comment by DaniloSAS** [comment]
Esse ponto de add 10 e ele add as 5 e não avisar que das 10 5 foi add, entendi... Vou ver se acho uma solução e aviso aqui. Nos cursos que estou vendo por ai o pessoa esta indicando não usar mais VAR e sim LET e também dizem que há uma tendencia a não usar mais o ponto e virgula no final das sentenças. O que acha? No curso você aborda alguma coisas da nova especificação?

**Comment by fdaciuk** [comment]
Esse curso é especificamente sobre ES5. Não há problema em usar `var`, desde que se entenda a questão do escopo quando usado. Ao escrever códigos em ES6+, obviamente não vamos mais usar, mas o aprendizado de ES6 são apenas features novas que vieram para complementar o ES5. Então foque nos estudos do ES5, entenda como funciona a questão do escopo - que vai vir algumas aulas mais pra frente - e só então comece a estudar ES6+. Você vai ver que assim as coisas vão fazer bastante sentido =)

Sobre o ponto-e-vírgula, como mostrado no curso, continue usando. No final do curso eu mostro com mais detalhes quando é seguro não usar, mas nesse momento o foco é ensinar a linguagem em sua essência, então continue usando =)

Nesse curso não tem nada sobre ES6+, mas esse ano ainda vou lançar um curso sobre as novidades da linguagem :)

**Comment by fdaciuk** [comment]
Oi @DaniloSAS! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)

**Comment by DaniloSouza-Ti** [comment]
Tranquilo.
