### ISSUE TITLE
desafio 16

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#3108]
Escreva aqui sua dúvida
uma pergunta...
qual seria a diferenca em escrever assim
var name = 'leonardo';

    for(var i = 0; i < name.length; i++){
         console.log(name[i] + ' é a ' + (i + 1 ) + ' ªletra do meu nome.');
    }
ou sem o console.log() pois vejo que o resultado nao eo mesmo tipo como se o loop nao funciona

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! O loop continua funcionando, a diferença é que, sem o console.log, você não vê o resultado sendo exibido no console =)

A ideia do `console.log` é exibir alguma coisa pra você no console, só isso =)

**Comment by fdaciuk** [comment]
Oi @leoigel! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
