### ISSUE TITLE
Challenge 19

### ISSUE THREAD

**Issue by Aleks15** [da2k/curso-javascript-ninja#3116]
Fernando, boa tarde.
Ao realizar o desafio 19, mais precisamente na última questão, eu desenvolvi o código abaixo como resolução., contudo está retornando false para date, mas se testar a expressão no regex101, ou se eu criar uma variável diretamente no console de um browser qualquer, o match em date é feito sem problemas. Poderia me informar por que acontece este comportamento?

```
var markup = "<main>\n  <div class="container">\n    <span class="text date"></span>\n    <p class=\'excerpt\'></p>\n  </div>\n</main>";
	console.log( '\nQuais classes CSS existem na marcação abaixo?\n\n', markup, '\n' );

	function hasClass(markup, cssClass){
		var findClass = new RegExp('class=[\"\'](?:[\w\s]+)?'+cssClass,'gm');
		return findClass.test(markup)  + " para a classe " + cssClass;
	}

	console.log(hasClass(markup,'container'));
	console.log(hasClass(markup,'text'));
	console.log(hasClass(markup,'date'));
	console.log(hasClass(markup,'excerpt'));
	console.log(hasClass(markup,'main'));

	//true para a classe container
	//true para a classe text
	//false para a classe date
	//true para a classe excerpt
	//false para a classe main
```
caso necessite:
https://github.com/Aleks15/curso-javascript-ninja/tree/challenge-19/challenge-19

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Aleks15! Lembre-se que, quando você cria uma regex com o objeto `RegExp`, e passa a regex como string, você precisa escapar sempre que usar as barras invertidas, quando elas não forem usadas especificamente para escape, senão a interpretação vai ser de que, ao invés de usar um espaço - com `\s` - , você está simplemente, dentro da string, escapando o caractere `s`, e a regex vai tentar casar com esse caractere =)

**Comment by fdaciuk** [comment]
Oi @Aleks15! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
