### ISSUE TITLE
Challenge-32

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3124]
Fala Daciuk, tudo bem ?

Minha dificuldade só veio aflorar nessa reta final mesmo. Cara, tive muita muita muita dificuldade pra realizar esse challenge. Na verdade, nem fiz ele ainda. Me confundiu muito isso de GET e POST. 

Eu não sei o app.js vai ser o que eu vou importar pra o meu index, ou o index.js
Não consegui ver a diferença entre esses depois arquivos javascript.

E também não entendi essa parte:
- Para listar os carros cadastrados ao carregar o seu projeto, faça um request GET no endereço
`http://localhost:3000/car`
- Para cadastrar um novo carro, faça um POST no endereço `http://localhost:3000/car`, enviando
os seguintes campos:

Onde eu faço o POST e onde eu faço o GET ? 
O POST nada mais é do que o envio de dados, certo ? E o get é pra pegar os dados, mas no código está isso: 
    `router.post('/',` function(req, res) {
    data.push({
        image: req.body.image,
        brandModel: req.body.brandModel,
        year: req.body.year,
        plate: req.body.plate,
        color: req.body.color 
    });
    res.json({ message: 'success' });
    `});`

E isso eu não entendi, porque eu to enviando dados, sendo que eu quero o request deles ? Por quê usar o post aqui ? Eu pensei que seria o contrário, ai eu faria desse o get, e no app eu ia colocar um post assim 

`app.post("/",` function(request, response){
  var image = "https://www.clickgratis.com.br/fotos-imagens/de-carro/aHR0cDovL3d3dy5kZXNjb21wbGljYW5kby5jb20vaW1nL2ZvdG9zL2NhcnJvJTIwZGUlMjBjb250cm9sZSUyMDQuanBn.jpg";
  response.send("image="+image+"&brandModel=13&year=2013&plate=EEE-2342&color=vermelho")
`});`

Com certeza devo ter sido muito confuso, e peço desculpas por isso. Só que eu cheguei nessa parte, e tenho certeza que requisições ajax são muito importantes, e me preocupa o fato de eu não ter entendido muito bem. 

Aguardo resposta, valeu Daciuk!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Na verdade, é mais simples do que parece:
Se você chegou até aqui, você já viu como fazer um request para pegar informações de algum lugar, correto?

A única coisa "diferente" que você precisa fazer nesse desafio é: 
você só precisa copiar o diretório "server" - que está dentro do diretório "challenge-32" aqui do repositório do curso - para o mesmo local (diretório) onde você começou a desenvolver essa aplicação (que começou nos challenges 29 e 30).

Feito isso, via terminal, acesse o diretório "server" e execute os comandos conforme instruções [aqui](https://github.com/da2k/curso-javascript-ninja/blob/master/challenge-32/challenge-32.js#L10-L12).

Você não precisa se preocupar com o código dentro do diretório "server", só precisa executar as instruções que estão no desafio que tudo vai funcionar conforme o esperado =)

Feito isso, se precisar continuar usando o terminal, você terá que abrir outro, pois esse vai ficar "ouvindo" o nosso servidor onde os carros ficarão salvos =)

À partir de então, você terá um servidor em `http://localhost:3000`. Esse endereço é o endereço do servidor que você acabou de "subir" pelo terminal, quando executou "node app.js".

Agora é só seguir com o processo normal que você já estava fazendo =)

Ficou mais claro agora?

**Comment by MatheusDidier** [comment]
Caraca Daciuk! Que vacilo meu cara, eu realmente tinha entendido a parada de outro jeito, e tava quebrando minha cabeça pra entender o app e o index.js! Acabei de fazer o exercicio, e o que eu fiz ta funcionando perfeitamente, trazendo os dados do servidor! 
Caraca, show demais suas aulas viu!

Alias, vou aproveitar pra te fazer uma pergunta. Seria dessa mesma forma que iriamos persistir os dados com banco de dados, só que a diferença é que o nosso servidor ia estar se comunicando com o banco ? 
Valeu Daciuk!

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Seria mais ou menos dessa forma xD
Da forma como eu deixei no desafio, os dados ficam persistidos em memória, ou seja: enquanto o servidor estiver no ar, os dados estarão ali, independente se você recarregar a tela do browser.

Os dados só irão se perder se você derrubar o servidor =)

Então esse tipo de persistências não é o que usaríamos em produção. Pra isso existem bancos de dados, que persistem os dados em disco mesmo, então ainda que o servidor caia, ele consegue puxar os dados do local que foi gravado no disco, à partir do banco de dados, e mostrar as informações corretamente =)

Essa é só uma maneira "rápida" pra fazer persistência, mas a ideia base é sempre essa =)

**Comment by MatheusDidier** [comment]
Cara, mas que legal isso!

Mas então porque javascript não é considerada uma linguagem de backend também ? Porque ele consegue tratar os dados recebidos e guardar num banco, não ?

**Comment by fdaciuk** [comment]
Mas você pode usar JavaScript no backend também, com Node.js =)
Foi o que eu fiz no diretório server: é o JavaScript rodando do lado do servidor com Node.js :D
