### ISSUE TITLE
[Challenge 10] Dúvida sobre uma notação

### ISSUE THREAD

**Issue by clarabatt** [da2k/curso-javascript-ninja#313]
Oi @fdaciuk ! 
```javascript
return operation/[operator]( x, y );
```
Eu sei que o operation[operator] chama a propriedade do objeto operation definida pela variável operator. Se eu usasse variáveis diferentes em operation e em calculator, funcionaria? 
Exemplo:
```javascript
    var operation = {
        '+': function( valor1, valor2 ){
            return valor1 + valor2;
        },
        '-': function( valor1, valor2 ){
            return valor1 - valor2;
        },
        '*': function( valor1, valor2 ){
            return valor1 * valor2;
        },
        '/': function( valor1, valor2 ){
            return valor1 / valor2;
        },
        '%': function( valor1, valor2 ){
            return valor1 % valor2;
        }
    }
/*-------------------------------------------------------------------------*/
    function calculator( operator ){
        if ( !isOperatorValid( operator ) ){
            return false;
        }
        return function( number1, number2 ){
            if (typeof number1 !== 'number' || typeof number2 !== 'number'){
                return false;
            }
            return operation[operator]( number1, number2 );
        }
    }
```
Eu preciso dar uma treinada no olho, eu passei um tempinho pra entender a notação do `operation[operator]( x, y )` . Mas no fim eu entendi que é basicamente uma função.

**Comment by fdaciuk** [comment]
Oi @clarabatt xD
Funcionaria sim! O que precisa ficar claro é o seguinte: cada função tem uma "assinatura". No caso, ela espera que um tipo específico seja passado por parâmetro, e retorna também um tipo de valor.

De quais valores estamos falando? Vai depender de função para função.

Exemplo: para facilitar a visualização, poderíamos separar os métodos de `operation` em funções literais:

```js
function sum( valor1, valor2 ) {
  return valor1 + valor2;
}
```

Qual a assinatura dessa função? Ela espera que dois números sejam passados por parâmetro, para que possa efetuar uma soma. Como você usa ela?

```js
sum( 1, 2 ); // 3
```

O que nós utilizamos foi uma forma de trabalhar com métodos de objetos, de uma forma que fique fácil a visualização do que está acontecendo. Criamos a função `calculator`, que vai receber um operador qualquer. esse operador deve existir no objeto `operation`, que é o responsável por cada operação matemática.

No final, o retorno da função que `calculator` retorna, é:

```js
return operation[operator]( number1, number2 );
```

Ou seja: você está invocando um método do objeto `operation`, e passando os dois números que ele espera por parâmetro.

Uma forma que vai facilitar a visualização do todo, é tentar utilizar valores fixos:

```js
operation[ '+' ]( 1, 2 ); // 3
operation[ '*' ]( 2, 3 ); // 6
```

Depois você só vai substituindo os valores fixos pelos valores dinâmicos :)

Nesse caso, não podemos usar a notação de ponto, pois o nome do método é uma string. Por isso precisamos usar a notação de colchetes. Mas se o nome do método fosse um nome válido para nomeação de variáveis, poderíamos chamar o mesmo método com:

```js
operation.sum(1, 2); // 3
```

Ficou mais claro?

**Comment by clarabatt** [comment]
Muito obrigada, ficou bem claro!

**Comment by fdaciuk** [comment]
:smile:
