### ISSUE TITLE
Dificuldade com Git em atualizar o projeto

### ISSUE THREAD

**Issue by ricardomirannda** [da2k/curso-javascript-ninja#3133]
Olá Fernando,
Estava criando a branch através do Github, mas fiquei um tempo sem usar e estou com dificuldades no processo. Decidi então usar o terminal e estou seguindo passo a passo pra atualizar o projeto, porém estou passando por esse problema:

MacBook-Pro-de-Ricardo:curso-javascript-ninja ricardomirannda$ cd challenge-07
MacBook-Pro-de-Ricardo:challenge-07 ricardomirannda$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
MacBook-Pro-de-Ricardo:challenge-07 ricardomirannda$ git fetch upstream
**fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.**

**Please make sure you have the correct access rights
and the repository exists.**
MacBook-Pro-de-Ricardo:challenge-07 ricardomirannda$ 
 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Provavelmente você não adicionou o repositório principal do curso como `upstream`.

O que mostra no seu terminal se você executar `git remote -v`?

**Comment by ricardomirannda** [comment]
Oi Fernando,
Aparece a seguinte mensagem: 

curso-javascript-ninja ricardomirannda$ git remote -v
origin	https://github.com/ricardomirannda/curso-javascript-ninja.git (fetch)
origin	https://github.com/ricardomirannda/curso-javascript-ninja.git (push)

**Comment by fdaciuk** [comment]
É isso mesmo! Pra adicionar o upstream, só executar:

```sh
git remote add upstream git@github.com:da2k/curso-javascript-ninja.git
```

**Comment by fdaciuk** [comment]
E se quiser mudar o seu repo (origin) pra acessar via SSH (pois está acessando via HTTPS), só executar:

```sh
git remote set-url origin git@github.com:ricardomirannda/curso-javascript-ninja.git 
```

**Comment by ricardomirannda** [comment]
Qual a seria a diferença entre SSH e HTTPS? 
Esse comando **upstream** define quem é a fonte principal do projeto?

**Comment by ricardomirannda** [comment]
MacBook-Pro-de-Ricardo:curso-javascript-ninja ricardomirannda$ git remote set-url origin git@github.com:ricardomirannda/curso-javascript-ninja.git 
MacBook-Pro-de-Ricardo:curso-javascript-ninja ricardomirannda$ git fetch upstream
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
MacBook-Pro-de-Ricardo:curso-javascript-ninja ricardomirannda$

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Por SSH tem uma segurança a mais, por precisar de uma chave SSH =)

Esse erro que está dando é porque você, provavelmente, não tem essa chave, ou não configurou no GitHub =)

Tem duas formas de resolver:
- Ou você cria a chave e configura no GitHub, seguindo [esses passos](https://help.github.com/articles/connecting-to-github-with-ssh/);
- Ou então você deixa como HTTPS mesmo, não tem problema =)

Se quiser deixar como HTTPS mesmo, só executar:

```sh
git remote set-url origin git@github.com:ricardomirannda/curso-javascript-ninja.git 
```

E depois:

```sh
```

**Comment by fdaciuk** [comment]
Sobre o `upstream`: normalmente usamos esse nome pra definir quem é o repositório principal. O `origin` é sempre o seu, e o `upstream` seria o repositório à partir do qual você fez o seu fork.

Mas ele poderia ter qualquer nome, não precisaria ser especificamente upstream =)

Se quiser saber mais sobre Git e GitHub, tem um curso gratuito do meu amigo @willianjusten que pode te ajudar:
https://www.udemy.com/git-e-github-para-iniciantes/

**Comment by ricardomirannda** [comment]
Vou fazer o Curso do William que você recomendou.
Muito obrigado pelos esclarecimentos !!

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, só avisar =)

**Comment by PedroVOliveira** [comment]
Daciuk, tive o mesmo problema porém essas opções não funcionaram '-

**Comment by PedroVOliveira** [comment]
A seguinte mensagem aparece:
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by fdaciuk** [comment]
Oi @PedroVOliveira! O seu problema provavelmente é com a chave SSH. Você chegou a criar a chave e subir no GitHub a pública?

**Comment by PedroVOliveira** [comment]
Sim, eu fiz todo o processo que foi pedido no curso. Só que troquei de
sistema operacional, mudei do Windows para o Ubuntu, tem alguma relação?

Em seg, 1 de abr de 2019 10:43, Fernando Daciuk <notifications@github.com
escreveu:

**Comment by fdaciuk** [comment]
Entendi! Tem sim =)
A chave SSH é única por sistema operacional. Você pode usar a mesma nos dois sistemas, ou usar uma para cada um. Aí tem que fazer o mesmo processo no Ubuntu, só que pode deixar a chave pública do Windows que foi configurada no GitHub também.

Se quiser usar a mesma, é basicamente copiar as chaves do Windows para o diretório `~/.ssh` no seu Ubuntu que já deve funcionar :)

**Comment by PedroVOliveira** [comment]
Poderia me informar o comando exato?

Em seg, 1 de abr de 2019 11:04, Fernando Daciuk <notifications@github.com
escreveu:

**Comment by fdaciuk** [comment]
@PedroVOliveira são os passos que eu passei [nesse comentário aqui](https://github.com/da2k/curso-javascript-ninja/issues/3133#issuecomment-358711169) =)

**Comment by PedroVOliveira** [comment]
Consegui resolver o problema, agradeço pela ajuda :)

Em seg, 1 de abr de 2019 20:31, Fernando Daciuk <notifications@github.com
escreveu:

**Comment by fdaciuk** [comment]
Show @PedroVOliveira! Qualquer coisa, só avisar :)

**Comment by oandersonx** [comment]
O meu ainda continua quando digito push -u origin master

Please make sure you have the correct access rights
and the repository exists.


Digito git remote -v aparece

origin  git@github.com:oandersonx/documento_django.git (fetch)
origin  git@github.com:oandersonx/documento_django.git (push)

**Comment by fdaciuk** [comment]
Oi @oandersonx! O seu problema é a chave SSH que não está configurada :)
Dá uma olhada no link que eu mandei [nesse comentário](https://github.com/da2k/curso-javascript-ninja/issues/3133#issuecomment-358711169) :)

**Comment by Raeski** [comment]
a

**Comment by Guedesou** [comment]
Fernando, muito obrigado por nos ajudar através dos anos. De verdade! 
Não consio mesmo e me sinto um noob. Não consegui por HTTP, dá erro  de permissão, criei a chave SSH que o tutorial ensina, mas mesmo assim olha:

➜  nintendo git:(master) ✗ xclip -selection clipboard < ~/.ssh/id_ed25519.pub
➜  nintendo git:(master) ✗ git push -u origin master

github@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(tá meio diferente porque tô usando o ohmyzsh- e já em arrependi tmb).

**Comment by fdaciuk** [comment]
Oi @Guedesou! No passo onde você copia a chave, você precisa subir ela na sua conta do GitHub. Depois de subir, você vai usar `ssh -T git@github.com` para confirmar que o GitHub reconheceu a chave, e você tem permissão de escrita no repositório, e só então você vai fazer o `git push` para enviar as alterações para o seu repositório :)

**Comment by ludeoliveira** [comment]
> E se quiser mudar o seu repo (origin) pra acessar via SSH (pois está acessando via HTTPS), só executar:
> 
> ```shell
> git remote set-url origin git@github.com:ricardomirannda/curso-javascript-ninja.git 
> ```

@fdaciuk MUITO OBRIGADA eu tava há mais de 10h tentando resolver um problema e a sua resposta aqui me salvou <33333

**Comment by fdaciuk** [comment]
Que bom que foi útil @ludeoliveira :D

**Comment by hochforce** [comment]
Fernando, tudo bom?
Eu alterei o nome do meu repositório no github e agora não consigo mais fazer pushs.
Como faço pra atualizar com o novo nome no meu repo local?

**Comment by fdaciuk** [comment]
Oi @hochforce! Pode usar o comando `git remote set-url` que mostrei nos comentários anteriores, passando a URL atualizada do seu repo :)

**Comment by thiagokassabian** [comment]
@fdaciuk Obrigado pela ajuda. Estava com dificuldades mas li seus comentários e consegui resolver os problemas para fazer push no github

**Comment by fdaciuk** [comment]
Show @thiagokassabian :D
