### ISSUE TITLE
Challenges 

### ISSUE THREAD

**Issue by martinsana** [da2k/curso-javascript-ninja#3148]
Olá, comecei meu curso agora, e minha dúvida é: Eu preciso ficar atualizando as minhas Challenges através do git também?(não estou atualizando). Para fazer meus exercícios crio uma nova Challenge, a partir da já existente e faço os exercícios nela. Estou na n°5.
Estou fazendo certo? Caso não, o que me aconselha?(Não tenho experiencia com GitHub).

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @martinsana! Tudo bem? =)

Da forma que eu mostrei nos vídeos, seria apenas pra facilitar o envio dos pull requests. A cada pull request, só iria aparecer as alterações de um único desafio.

Mas não tem problema fazer como você está fazendo não =)

Na verdade, não é obrigatório o envio dos desafios também, mas é importante que você tente resolvê-los, pois é com a prática que conseguimos aprender de verdade =)

De qualquer forma, pode seguir em frente, e se tiver qualquer dúvida, só avisar que eu te ajudo =)

**Comment by martinsana** [comment]
ok, obrigada!

**Comment by fdaciuk** [comment]
=)
