### ISSUE TITLE
Challenge-27

### ISSUE THREAD

**Issue by Moraissz** [da2k/curso-javascript-ninja#3151]
Boa tarde Daciuk,
Nesse desafio, você pede para criar métodos estáticos de IsArray, isFunction etc, você usou o prototype para cria-los. Mas você teve que instanciar um objeto para usar os métodos.
Eu fiz desse modo : 
![isarray](https://user-images.githubusercontent.com/32682312/35167318-23b8234c-fd3c-11e7-9e27-bc1af7bb7f61.png)
E então eu fui capaz de chama-lo desse modo:
![chamadaisarray](https://user-images.githubusercontent.com/32682312/35167327-33b88660-fd3c-11e7-9116-6f13783983bf.png)
E então funciona certinho.
Isso é errado? ou está certo?
Porque eu pendurei na lib DOM os métodos, assim não precisando de criar uma variável do tipo DOM  para poder utiliza-los

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Moraissz! Cara, mil desculpas, realmente a forma como você fez é que está correta.. provavelmente na hora de resolver o desafio, eu estava tão focado nos métodos anteriores que acabei cometendo essa gafe :speak_no_evil: 

Vou adicionar uma nota logo após esse vídeo para explicar essa situação, mas a forma correta é exatamente essa que você fez =)
