### ISSUE TITLE
Erro de permissão na hora de clonar no git

### ISSUE THREAD

**Issue by leandromac** [da2k/curso-javascript-ninja#32]
Esta aparecendo a seguinte mensagem de erro na hora de clonar o repositório.

Mac-mini:~ leandromacedo$ git clone git@github.com:leandromac/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Mac-mini:~ leandromacedo$

**Comment by NzN-Projetos** [comment]
cara eu tava com o mesmo problema. ai gerei a chave localmente, inseri ela no git em  Settings >ssh keys ai foi.
Segui o conteudo desse link pra gerar o SSH:
http://blog.dmatoso.com/2011/09/git-no-windows-github/

**Comment by leandromac** [comment]
Não conseguir fazer isso no MacOS? =/

**Comment by fdaciuk** [comment]
Oi @leandromac, precisa fazer o que o @NzN-Projetos fez: gerar as chaves SSH. Para fazer isso no Mac, pode seguir esse tutorial aqui: https://help.github.com/articles/generating-ssh-keys/#platform-mac

Qualquer dúvida grita ae :D

**Comment by leandromac** [comment]
Então Fernando.
Segui os passos do link acima e fiquei enganchado em onde esta o meu "SSH key" para poder colocar em setting do github.
O tutorial explicou tudo direitinho mas nessa parte não consegui entender.
Pode me dar um help nisso?
Aguardo

**Comment by fdaciuk** [comment]
@leandromac, a SSH Key fica em "~/.ssh".
É um diretório oculto dentro da sua pasta de usuário. Pelo terminal, você consegue acessar via:

```sh
cd ~/.ssh
```

Dentro desse diretório, execute o comando `ls -la`.

Você deve ver ao menos dois arquivos: `id_rsa` e id_rsa.pub`. O arquivo pode ter outro nome além de  `id_rsa`, mas devem conter 2 com o mesmo nome, mas um com a extensão `.pub`.

É esse que você precisa adicionar no seu GitHub. Como fazer?

Se o arquivo com extensão `.pub` se chamar `id_rsa.pub` mesmo, você pode executar:

```sh
cat id_rsa.pub
```

Que será mostrado o conteúdo do arquivo. Agora é só ir nas suas configurações do Github e colar essa chave lá!

Só lembre que tem que ser a `.pub`, ok? A outra é sua chave privada, e você não deve compartilhar com NINGUÉM! :D 

Se ainda tiver dúvidas, me avise :)

**Comment by fdaciuk** [comment]
@leandromac vou fechar a issue. Se tiver mais alguma dúvida referente a isso, eu reabro, ok? :smile:

**Comment by robinhodemorais** [comment]
nossa, ja estava quase formatando o pc, valew salvou minha vida

**Comment by LaurianoElmiroDuarte** [comment]
boa noite galera, eu estava tendo o mesmo problema, os amigos aí acima esqueceram de dizer um detalhe, depende do sistema operacional, nem todos geram os dois arquivos, pelo menos no meu fedora 29 não existem esses 2 arquivos, somente um denominado know-hosts. e a forma apresentada pelo amigos não resolve o problema .

**Comment by fdaciuk** [comment]
Oi @LaurianoElmiroDuarte! Você precisa gerar os arquivos :)
Olha o primeiro link que eu postei :)

**Comment by JnrMoraes** [comment]
Olá @fdaciuk melhor jeito! Se possível, escreve até em inglês, tem muito gente apanhando com o tutorial feito por eles :/

**Comment by fdaciuk** [comment]
Oi @JnrMoraes! Você se refere ao tutorial do GitHub?

**Comment by JnrMoraes** [comment]
@fdaciuk sim, tentei varias vezes, mas estava dando sempre esse mesmo erro. Já vc fala pra executar 'cat id_rsa.pub' e ai sim vc tem a chave. Lá ele não menciona isso ou eu que não entendi pra fazer esse tipo de execução por não saber usar o terminal ainda.

**Comment by fdaciuk** [comment]
@JnrMoraes entendi. Lá no tutorial ele pede pra usar o xclip pra copiar direto para o clipboard, isso pode confundir em alguns casos :)
Mas legal a dica, vou ver de escrever um tutorial, ou talvez gravar um vídeo mostrando o passo-a-passo de como fazer isso :)

**Comment by romulo2902** [comment]
tentei inserir a chave gerada  no "Deploy Keys" e continua dando chave invalida no github na hora de salvar

Key is invalid. You must supply a key in OpenSSH public key format

**Comment by fdaciuk** [comment]
Oi @romulo2902! Você seguiu a dica [desse comentário](https://github.com/da2k/curso-javascript-ninja/issues/32#issuecomment-92752896)? :)

**Comment by bellatriz** [comment]
> Key is invalid. You must supply a key in OpenSSH public key format

@romulo2902  vc está adicionando a chave com ssh-rsa na frente?
