### ISSUE TITLE
desafio 2, ultimo exercicio

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#324]
Opa @fdaciuk !

Não estou conseguindo  essa parte.

6. E ainda, se nenhuma das condições acima forem atendidas, retorne `null`.

function somar(a,b,c){ 

        if( a !== undefined && b === undefined && c === undefined){
            return a;
        }
        else if(a === undefined && b !== undefined && c === undefined){
            return b;
        }
        else if(a !== undefined && b !== undefined && c === undefined){
            return a+b;
        }
          else if(a !== undefined && b !== undefined && c !== undefined){
            return (a+b)/c;
        }
         else if( a === undefined && b === undefined && c === undefined ){
            return false;
        }
        else{
            return null;
        }
}

se uso  uma string como argumento  da o seguite erro,no erro abaixo eu coloquei meu nome para testar, e não retorna o null como deveria ser.

Uncaught ReferenceError: lucas is not defined
    at <anonymous>:2:7
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)

se uso string com aspas simples ou duplas ele mostra a string.Em um outro codigo que fiz ele mostrava a string + undefined

fiz varios testes usei a letra f como argumento a saida é um form relacioando a pesquisa por voz do google

**Comment by fdaciuk** [comment]
Opa @LucasCMota! Na verdade o `null` nunca será retornado para essa função :)
O problema aconteceu com o seu nome, porque você não usou uma string, e sim uma variável que não está definida! Lembre-se: strings são qualquer caractere que esteja entre aspas simples ou duplas!

Qualquer valor que você digite fora de aspas, o Javascript irá tentar interpretar como um valor da linguagem. Se não for uma palavra chave (como function, for, if, etc), o JS vai tentar interpretar como uma variável. 

Como você não tem uma variável chamada `lucas`, ele diz que `lucas is not defined`, ou seja: não foi definida nenhuma variável chamada `lucas`! :)

Quando você usa string no primeiro parâmetro, ele cai na primeira condição do seu `if`:

```js
if( a !== undefined && b === undefined && c === undefined){
   return a;
```

Como `a` é o primeiro parâmetro, e ele é diferente de `undefined`, e os outros parâmetros não foram passados (logo, eles são iguais a `undefined`), então é retornado o valor que você passou, no caso, a sua string :)

Ficou claro essa parte?

**Comment by LucasCMota** [comment]
quanto ao f retornar um form?

**Comment by LucasCMota** [comment]
@fdaciuk não queria fazer vendo a correção, depois tentei mais um pouco e consegui diminuir a quantidade de codigo

function somar( a, b , c ){
       if( a === undefined && b === undefined && c === undefined ){
           return false;
        }
        if( a !== undefined  && b === undefined  && c === undefined){
            return a;
        }
        else if(c === undefined){
            return a+b;
        }
        else if(c !== undefined){
            return (a+b)/c;
        }
        else if(false){
             return null;
        }
       
     }

**Comment by fdaciuk** [comment]
> @fdaciuk 
> quanto ao f retornar um form?

@LucasCMota, provavelmente você estava testando na página inicial do Google, onde o form tem um `id` chamado `f`. Por isso quando você passou a variável `f` mostrou o form :)

Mas isso nós vamos ver beeem mais pra frente :)

O que você precisa saber aqui é que você passou uma variável no lugar de uma string :)

**Comment by fdaciuk** [comment]
> @fdaciuk não queria fazer vendo a correção, depois tentei mais um pouco e consegui diminuir a quantidade de codigo

Os problemas com essa função eu marquei no seu pull request. Dá uma olhada lá ;)
