### ISSUE TITLE
Sobre testes de funções void

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3249]
Fala Daciuk, tudo bem cara ?

Como funcionaria os testes de funções void, sendo que uma função void sempre retorna undefined. Como ele avaliaria minha função ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Normalmente esse tipo de função você usa apenas para chamar outras, ou então você faz mock do contexto que precisa testar. Por exemplo: se uma função que não retorna valor modifica o valor interno de um objeto, criado à partir de um construtor, você faz um mock pra testar se o valor foi modificado corretamente.

Esse tipo de função é mais difícil de testar, então é bom evitar o seu uso sempre que possível =)

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
