### ISSUE TITLE
Usando uma variavel em varias funções

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3254]
Daciuk, percebi que é uma má pratica utilizar objetos globais sempre, porque acaba demandando memoria.
Qual seria uma solução para manipular uma variavel entre funções diferentes no escopo local sem usar o objeto window ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! A única forma de comunicação da linguagem JS hoje - falando de frontend - é o escopo global.

O importante é entender que é possível usar a maior parte do seu código de forma local, e só o que você precisa usar de forma compartilhada, "exportar" no escopo global.

Assim você mantém o seu código o mais previsível possível =)

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
