### ISSUE TITLE
WRAPPER OBJECTS - Seção 10 - Aula 58

### ISSUE THREAD

**Issue by fga36** [da2k/curso-javascript-ninja#3268]
Boa Tarde Fernando !

Uma dúvida minha é o uso dos conversores, sei que você não mostrou até então nos vídeos anteriores como converter valores das variáveis.
Mas vou te passar um exemplo, aí você me diz qual é mais usado para converter, ok ?

Exemplo:
var myVar = '10';
myVar = parseInt(myVar);
// ou
myVar = Number(10);

Qual é a melhor maneira ? Ou fica ao meu critério de uso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi  @fga36! Na verdade, são duas funções diferentes.

O `parseInt` vai transformar o número sempre em um **inteiro**, de algum tipo.

Essa função deve receber dois parâmetros: o primeiro, uma string que é o valor a ser convertido para inteiro, e o segundo, uma **base** matemática que será usada para fazer a conversão. Exemplo:

```js
console.log(parseInt('122', 10)) // 122
```

Usando com a base **10**, o número será convertido em decimal.

Já se usarmos a base 8, o número será convertido para octal:

```js
console.log(parseInt('122', 8)) // 82
```

E se usarmos base 16, ele será convertido para hexadecimal:

```js
console.log(parseInt('122', 16)) // 290
```

O problema de não usar o segundo argumento (a base, ou _radix_, conforme [a documentação](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)), é que o valor pode ser **implicitamente** convertido.

Por exemplo: se a string começar com `0x` ou `0X`, ela vai ser convertida para hexadecimal, não para decimal, como esperado:

```js
console.log(parseInt('10')) // 10
console.log(parseInt('0x10')) // 16
```

Veja que são resultados diferentes, mas como a entrada é uma string, isso pode acontecer.

Mas essa explicação foi só pra dar uma explicação de como usar corretamente o `parseInt`.

---

Sobre o que você queria saber:

A diferença é que o `parseInt` sempre vai retornar um número inteiro. No caso:

```js
console.log(parseInt('1.25')) // 1
```

Já o _Wrapper Object_ `Number` vai sempre tentar transformar o valor para número, pois não existem **inteiros** de verdade em JS. Todos os números são tratados como **ponto flutuante** (ou, mais conhecidos como _números quebrados_, ou _com casas decimais_.

Então, convertendo a string `'10'`, com os dois métodos você terá o mesmo resultado. Mas se tentar converter a string `'1.25'`, `Number` vai sempre te devolver esse número `1.25`. Já o `parseInt` vai **parsear o número para inteiro** =)

Ficou claro? =)

**Comment by fga36** [comment]
Ficou sim, foi muito bem explicado, abriu minha mente para esses dois conteúdos. :D
Muito obrigado .

**Comment by fdaciuk** [comment]
Massa! Qualquer dúvida, só avisar =)
