### ISSUE TITLE
Duvida sobre Module Pattern

### ISSUE THREAD

**Issue by Moraissz** [da2k/curso-javascript-ninja#3283]
Boa noite Daciuk, Minha duvida sobre isso, é no desafio 29, nós criamos a função app, só que você fez ela retornar um objeto, sendo cada um dele uma função do seu projeto ( no caso métodos ), no meu caso eu só fiz a função app englobando todas as outras funções que eu já tinha feito sem fazê-los sendo métodos. Até porque a utilização de muitos "this" faz o código não ficar tão "clean" na minha opinião. Então gostaria de saber se há alguma vantagem de usar o app retornando um objeto com métodos, ou posso deixa-lo apenas  como uma função "englobadora" pra poder exportar?

Agradeço a ajuda.

@fdaciuk

**Comment by Moraissz** [comment]
OBS: No caso do "this", eu quero dizer, que ele foi usando em muitos contextos diferentes, o que torna o código mais difícil de ser interpretado, na minha opinião

**Comment by fdaciuk** [comment]
Oi @Moraissz! Faz todo o sentido o seu comentário =)
Eu fiz a apresentação do _Module Pattern_ apenas para apresentar um tipo de pattern que podemos usar no JS, mas existem vários outros possíveis, inclusive você pode usar como você achar que fica mais legível! O ponto é realmente você tentar deixar o código o mais previsível possível, e facilitar para que outras pessoas - e até mesmo você, no futuro - consiga entender o que está acontecendo :D 

O `this` é pode realmente se tornar um problema a longo prazo. Não vejo problema algum em usar o 
`app` apenas para exportar outras funções :)

**Comment by Moraissz** [comment]
Entendi, muito obrigado!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
