### ISSUE TITLE
challenge- 23

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#3296]
fala cara?
meu to tentado fazer o challenge 23, mas ta muito dificil cara!!! tipo ate agora eu faco todos o challenges (tem varios que nao consigo ai apago e faco de novo) porem esse ai ta muito dificil, isso e normal, tem varios outros alunos como eu? gostaria de saber qual seria a melhor forma de estudar seu curso?  se eu ver as aulas resolver os excercicios junto com voce (vendo as respostas) e depois refazer...o que voce me aconcelha???

@fdaciuk
Escreva aqui sua dúvida
uma pergunta...
qual seria a diferenca em escrever assim
var name = 'leonardo';

    for(var i = 0; i < name.length; i++){
         console.log(name[i] + ' é a ' + (i + 1 ) + ' ªletra do meu nome.');
    }
ou sem o console.log() pois vejo que o resultado nao eo mesmo tipo como se o loop nao funciona

@fdaciuk

**Comment by fdaciuk** [comment]
Opa! Respondi no #3297 :D
