### ISSUE TITLE
challenge - 23

### ISSUE THREAD

**Issue by leoigel** [da2k/curso-javascript-ninja#3297]
fala cara?
meu to tentado fazer o challenge 23, mas ta muito dificil cara!!! tipo ate agora eu faco todos o challenges (tem varios que nao consigo ai apago e faco de novo) porem esse ai ta muito dificil, isso e normal, tem varios outros alunos como eu? gostaria de saber qual seria a melhor forma de estudar seu curso?  se eu ver as aulas resolver os excercicios junto com voce (vendo as respostas) e depois refazer...o que voce me aconcelha???

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leoigel! =)

Cara, fique tranquilo! Você está aprendendo um conteúdo completamente novo, então é normal sentir dificuldades. Muitos outros alunos também sentem isso =)

O que eu sempre aconselho a fazer é: primeiro, tente resolver sozinho. Se você perceber que alguma coisa não ficou clara, que você não conseguiu resolver, assista à solução.

Se com a solução você entendeu tudo o que deveria fazer, apague o desafio resolvido, e tente fazer de novo, sozinho.

Faça isso várias vezes. É a prática e a repetição que vão fazer você conseguir aprender a linguagem de verdade :D 

Na verdade, prática e repetição valem pra qualquer aprendizado **na vida!** =)
