### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by NzN-Projetos** [da2k/curso-javascript-ninja#33]
Fala Fernando blz.
Então cara foi meio zica pra eu conseguir fazer as coisas pelo git aqui no terminal e confesso que algumas coisas não entendi muito bem, mas de boa consegui fazer funcionar. Meu SO aqui é Windows então já sabe como é.
Fiquei meio confuso sobre aquele exemplo que você explicou da variavel um e variavel dois. Não entendi muito bem isso.
```javascript
var um = 1;
var dois = um++;
}
```
Ai lendo umas coisas também teve outra coisa que eu não entendi, se você puder explicar pra gente.

Por que aqui o valor é true?
```javascript
var a = 1;
var b = 1;
a == b;
a === b;
}
```
E aqui é false?
```javascript
var a = [1,2,3];
var b = [1,2,3];
a == b;
a === b;
}
```

**Comment by fdaciuk** [comment]
Olá @NzN-Projetos! Vamos lá:

Nesse exemplo:

 ```js
var um = 1;
var dois = um++;
```

Acontece o seguinte: o operador unário `++` faz uma atribuição **implícita**, ou seja, nós não vemos a atribuição acontecendo, mas ela existe. Por isso dizemos que esse operador causa um efeito colateral. Ele muda o valor da variável mesmo sem mostrar isso **explicitamente**.

Seria o mesmo que fazer: 

```js
var um = 1;
var dois = um;
um = um + 1;
```

Pois utilizamos o operador de **pós-incremento**, ou seja, só fazemos o incremento **APÓS** a avaliação da variável.

O Javascript interpreta exatamente como mostrei acima:

1. Atribui o valor `1` à variável `um`;
2. Atribui o valor da variável `um` (que nesse caso é `1`) à variável `dois`;
3. Faz o incremento de `1` na variável `um`, que agora vale `2`.

Se eu utilizasse o operador de **pré-incremento**, então o incremento aconteceria antes de avaliar a variável. O código:

```js
var um = 1;
var dois = ++um;
```

 Seria interpretado dessa forma:

```js
var um = 1;
um = um + 1;
var dois = um;
```

Ou seja:

1. Atribuímos `1` à variável `um`;
2. Fazemos o incremento de `1` na variável `um`, que agora vale `2`;
3. Fazemos a atribuição do valor da variável `um` na variável `dois`. Agora as duas valem `2` :)

Ficou claro essa parte?

**Comment by fdaciuk** [comment]
Agora, sobre o segundo caso, o que acontece é o seguinte:

Quando trabalhamos com arrays e objetos, por mais que os valores dos mesmos sejam iguais, eles **NUNCA SERÃO** os mesmos objetos.

Por exemplo: como nós vimos na última aula, um **literal** nunca pode ser mudado. Então `1` sempre será o número `1`. A string `'ninja'` sempre será a string `'ninja'`.

Mas um array eu posso mudar. Posso adicionar mais elementos, posso remover elementos.

Por isso que, se você tentar comparar:

```js
[1, 2, 3] === [1, 2, 3] // => false
```

Sempre será avaliado como falso. Você só terá um resultado `true`, se você estiver avaliando o mesmo array, ou o mesmo objeto. Exemplo:

```js
var a = [ 1, 2, 3 ];
var b = [1, 2, 3 ];
```

Aqui eu criei dois arrays, que estão registrados em lugares diferentes da memória.

Se eu tentar comparar:

```js
a === b // => false
```

Agora, seu eu fizer isso:

```js
var a = [ 1, 2, 3 ];
var b = a;

a; // => [ 1, 2, 3 ]
b; // => [ 1, 2, 3 ]
a === b // => true
```

Agora o resultado é `true`, pois a referência é para o mesmo array. Se eu adicionar mais um item ao `b`, por exemplo, a variável `a` também será atualizada:

```js
b[3] = 4;
b; // => [ 1, 2, 3, 4 ]
a; // => [ 1, 2, 3, 4 ]
```

Pode fazer o teste aí pra você ver :)

Deu pra entender? :smile:

**Comment by fdaciuk** [comment]
Sobre essa comparação de arrays, estamos só no começo ainda. Vamos falar muito sobre esse assunto ainda, mas se ainda tiver dúvidas com o que já foi falado no curso, pode comentar aqui, ou abrir outras issues, ok? :smile:

**Comment by fdaciuk** [comment]
@NzN-Projetos vou fechar a issue. Se tiver alguma dúvida com relação a esse assunto, eu reabro, ok? :smile:
