### ISSUE TITLE
Criação de Objetos - Object.create

### ISSUE THREAD

**Issue by felipegandradee** [da2k/curso-javascript-ninja#3304]
Olá Fernando, tudo bem?

Eu estava analisando a propriedade ' hasOwnProperty ' com base na explicação de aula.
Por exemplo:
```
var obj = { x: 1, y: 2 };
var obj2 = Object.create(obj);
obj2.x = 'one';

for (var prop in obj) {
    if (obj.hasOwnProperty(prop)) {
        console.log(prop);
    }
} // x y

for (var prop in obj2) {
    if (obj2.hasOwnProperty(prop)) {
        console.log(prop);
    }
} // x
```
Neste caso , apareceu que o 'obj ' possui como suas próprias propriedades o ' x ,  y '
e o 'obj2' possui o ' x ' como propriedade própria.

Minha dúvida é a seguinte: Mesmo que um objeto herde as propriedades de um outro, se eu altero as propriedades do objeto herdado, o JavaScript entende que essas propriedades alteradas no objeto herdado são como propriedades próprias para ele?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felipegandradee! Propriedades "própriais" - _own properties_ - só contam quando você cria diretamente naquele objeto. Propriedades herdadas não pertencem ao novo objeto criado, mas sim ao objeto que foi usado como "base" para a cópia =)

No seu exemplo, `x` e `y` pertencem à `obj`, já que foram criadas nele. `obj2` apenas pode "usar" essas propriedades, mas elas não pertencem à `obj2`, e sim a `obj`. =)

**Comment by felipegandradee** [comment]
Ok, entendi, muito obrigado. :D

**Comment by fdaciuk** [comment]
Show! Qualquer coisa avisa ae =)
