### ISSUE TITLE
challenge-23 duvidas 

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-javascript-ninja#3315]
fala dacuk, cara estou tento um problema com esse exercício até vi os videos da responta mas como eu estava fazendo de outro modo queria saber se o jeito que fiz teria como fazer ele somar com mais de 1 operador, fiz um o pull requests mas como não tive respontas fiquei com duvida se eu tinha feito correto ou se você ainda estaria fazendo desse jeito o suporte o link do repo meu https://github.com/angelilton/curso-javascript-ninja/blob/challenge-23/challenge-23/challenge-23.js

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! As soluções que eu mostro nos vídeos não são as únicas, sempre existe uma outra forma - ou formas - de resolver =)

Então, se a sua solução funcionou, está valendo =)

O importante é sempre ver que, por mais que tenhamos mais de uma possível solução, tentar manter sempre a que deixa o código o mais claro possível para quando você for ler ele no futuro, ou algum outro dev for ler esse código, ele deve conseguir entender o que você quis fazer.

Se você conseguiu passar essa mensagem, então está tudo certo :D

**Comment by angelilton** [comment]
então na verdade eu queria se você desse uma olha no que eu estou errando porque ele só está somando quando tem apenas 1 operador ( 4+2) se eu colocar mais de um ( 4+2-3) ele acaba não seguindo o if e caindo na soma de volta

**Comment by fdaciuk** [comment]
Oi @angelilton! Para resolver da forma como você fez, tem alguns problemas que vc precisa resolver:

Você separou os números e os operadores em arrays diferentes. Mas dentro do `reduce` que deveria te trazer o resultado, você [busca novamente os operadores sem necessidade](https://github.com/angelilton/curso-javascript-ninja/blob/challenge-23/challenge-23/challenge-23.js#L88-L90), pois você já havia feito isso antes, então pode remover essas linhas.

Outra coisa que vc precisa ter em mente é sobre o uso do `reduce`: lembre-se que, quando você não passa o segundo parâmetro para esse método, ele usa o primeiro item do array no valor `acumulado`, e o segundo item em `atual`. Isso vai fazer com que ele itere uma vez menos do que o tamanho do array. 

Nesse caso, você pode passar "zero" como segundo parâmetro do `reduce`, para esse ser o valor de `acumulado` na primeira iteração, e `atual` ser o primeiro item do array `number`.

O `for` dentro do `reduce` não faz muito sentido, pois o `reduce` já vai iterar pelo array `number`, saca? Não há necessidade de uma segunda iteração.

Então você só precisa pegar o operador certo para cada operação.

No caso, o índice zero do array `operator` é a primeira operação, entre o primeiro e o segundo itens do array `number`. Nesse caso, para fazer esse cálculo, quando o `number.reduce` estiver iterando pelo segundo item do array `number`, o índice da iteração vai ser 1, não zero.

Logo, conseguimos concluir que, a cada iteração em `number`, eu preciso pegar sempre o índice do `operator` menos 1.

Isso funciona bem, até pensarmos na primeira iteração com índice zero dentro do `reduce`, onde `0 - 1 = -1`. E não existe índice -1, então isso vai dar um erro para o array `operator`.

O que você pode fazer pra resolver é checar se o índice do `number.reduce` é zero, e usar como operador o `+`, que não vai interferir no cálculo de `0 + <qualquer_numero>`, pois o resultado vai ser sempre o `<qualquer_numero>`. Já se o índice dentro do `number.reduce` não for zero, vc pode pegar o operador de `operator[i - 1]`, que vai funcionar como vc espera =)

Sacou a ideia?

**Comment by fdaciuk** [comment]
Oi @angelilton! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
