### ISSUE TITLE
Escopo de Funções -  Seção 9, Aula 51 

### ISSUE THREAD

**Issue by ricardomirannda** [da2k/curso-javascript-ninja#3327]
Olá Fernando, bom dia! tudo bem contigo?
Na aula sobre Escopo de Funções, você informa o conceito de Closure, onde ela pode acessar parâmetros externos, mas a função "pai", não pode acessar parâmetros da Closure(filha).  

Ex:

function minhaFuncao(){
  var numero1 = 1;
  var numero2 = 2;
  
  function soma(){
    return numero1 + numero2;
  }
  
  return soma();
}

Nesse caso, minhaFuncao(), poderia ou deveria pode ter acessar tudo, já que ela é principal. 

Poderia esclarecer melhor esse conceito pra mim? 
Agradeço desde já! 

@fdaciuk

**Comment by ricardomirannda** [comment]
Tudo bem comigo Fernando ! 
Muito obrigado pela explicação, da forma como eu gosto, lúdica, o que me ajuda muito no entendimento. Brigadão !!!

**Comment by fdaciuk** [comment]
Show de bola!
Qualquer coisa, só avisar =)
