### ISSUE TITLE
Aula#25 - Eventos inline

### ISSUE THREAD

**Issue by Joaoh3326** [da2k/curso-javascript-ninja#3351]
Sobre a questão de eventos inline, você usou o onClick="boom()" (tipo eu fiquei, caramba ele fez oque os frameworks fazem, mas sem precisar de um framework), logo me gerou uma duvida se fazer isto é errado, porque o angular e o vueJs utilizam isso e chamam de diretivas ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Joaoh3326! Não posso dizer com relação ao Vue ou Angular porque não conheço como eles funcionam, mas posso falar sobre o React. Tem uma grande probabilidade de Angular e Vue funcionarem de forma ao menos parecida.

O que acontece quando criamos um evento inline no React, é que, na verdade, ele não fica inline. Como usamos JSX, nós escrevemos o evento inline apenas para manter as ações do componente "próximas" a ele.

Por baixo dos panos, quando o JSX é transformado em funções JS (`React.createElement`), no momento em que o método `render` do `react-dom` é executado, ele coloca os elmentos na árvore do DOM, e atrela os eventos que estavam inline, mas agora usando a forma correta, que seria com o `addEventListener`.

Já usando JS puro, eventos inline ficam exatamente como eles são, não vai ter nenhuma transformação, vai ser inline mesmo, entende? =)

**Comment by Joaoh3326** [comment]
Tranquilidade, no React eu já sabia que era assim, eu tenho o curso do react ninja(só dei uma pausa, pra poder aprender js de verdade), é mas deve ser como você falou acho que por traz dos panos eles devem fazer algo parecido com o react :D

**Comment by fdaciuk** [comment]
Isso ae =)

Qualquer dúvida, só avisar! =)
