### ISSUE TITLE
[Desafio #29] ajax.open();

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#3352]
Opa!

E aí, beleza?

Então, eu fiquei com uma dúvida e fiquei quebrando a cabeça achando que tivesse feito algo de errado.
E depois percebi que não fiz nada de errado.

O detalhe é:

no seu código você coloca: ajax.open('GET', '/company.json', true);
no meu código eu tive que colocar: ajax.open('GET', '\company.json', true);

a única diferença é que eu coloquei uma "\", se não for assim, não consigo trazer as informações.

Qual seria a causa disso?

Obrigado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! Provavelmente você somente abriu o arquivo `index.html` direto no browser (clicando duas vezes nele) ao invés de abrir usando um servidor estático, correto?

Se na barra de endereços do seu navegador, o endereço do arquivo apareceu com `file://` ao invés de `http://`, significa que você está abrindo o "arquivo puro" pelo browser, e isso vai sim dar erro ao tentar fazer requisições ajax, pois o sistema de arquivos do windows é diferente do sistema de arquivos do Linux e Mac.

Pra funcionar corretamente, você pode usar o `SimpleHTTPServer` do Python, como eu mostrei na aula, ou então usar o `http-server` do Node, que já vai resolver.

Aí você consegue abrir o seu arquivo usando o protocolo `http`, que é a forma correta =)

---

## Como usar o SimpleHTTPServer do Python

Se você tiver o python instalado na sua máquina, você só precisa, via terminal, acessar o diretório do projeto que você quer rodar, e executar o comando:

```python
python -m SimpleHTTPServer 8000
```

Onde `8000` é a porta onde você vai conseguir acessar o projeto via HTTP. Fazendo isso, se você acessar no browser `http://localhost:8000`, você vai conseguir visualizar a sua `index.html` e o request ajax vai funcionar certinho =)

## Como usar o http-server do Node

Se você não quiser instalar o python, e já tiver o Node.js e o NPM instalados, pode usar o http-server, que vai funcionar da mesma forma.

Você só precisa instalar ele de forma global pelo terminal, assim:

```sh
npm i -g http-server
```

E então é só executar o comando abaixo no diretório do seu projeto (pelo terminal):

```sh
http-server
```

Rodando esse comando, você pode acessar `http://localhost:8080`, que já deve funcionar =)

Qualquer dúvida que você tenha, avisa que eu te ajudo =)

**Comment by garritanoo** [comment]
Então, pior que eu nem cliquei duas vezes em cima do ícone.
Eu uso o ATOM e instalei um plugin de live preview nele. Quando eu mexe no código e aperto ctrl+s ele salva o arquivo e já atualiza a página.

Como eu uso esse plugin, ele coloca automaticamente um endereço numérico para o localhost (http://127.0.0.1:(a porta que eu for usar)).

Funciona bem de boa, mas eu acho que pode ter sido algum conflito.

Eu já usei o NetBeans e nele já vinha incluso um servidor.

Mas eu tive que me acostumar com o Atom, eu acho ele um pouco mais leve que o NetBeans.

De qualquer maneira, obrigado pelas dicas de HttpServer.

Depois eu vou mexer com esse do Node.

**Comment by fdaciuk** [comment]
Entendi! Nesse caso deveria ter funcionado xD

Não sei se tem algum problema com o uso do Atom pra isso (não deveria ter), mas com o SimpleHTTPServer ou o http-server do node com certeza vai funcionar =)
