### ISSUE TITLE
[Aula 3] Desafio 3 - método fazerAniversario

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#336]
Grande Fernando, 

Na criação do método não estou conseguindo acessar  variavel idade veja abaixo.

Até aqui esta tubo bem.
```javascript
var pessoa = {
   nome: 'Danilo', 
   sobrenome: 'agostinho', 
   sexo: 'masculino',
   idade: 23, 
   altura: 1.85, 
   peso: 64,
   andando: false,
   caminhouQuantosMetros: 0
}
```

Agora aqui não consigo acessar a variável diz: is not defined

```javascript
pessoa.fazerAniversario = function() {
	return idade++;
}
```

Como resolver isso?

**Comment by DaniloAgostinho** [comment]
consegui revolver vou enviar as alterações no PullRequest.

**Comment by fdaciuk** [comment]
:)
