### ISSUE TITLE
Server challenge-32

### ISSUE THREAD

**Issue by Moraissz** [da2k/curso-javascript-ninja#3372]
Boa noite Daciuk,
 Estava fazendo o challenge-32, e tentei criar umas coisas na parte do servidor : 
![duvidasv](https://user-images.githubusercontent.com/32682312/35706659-c6104b5a-078d-11e8-817c-e2a0238578c3.png).
A parte comentada é o código que eu tinha feito, mas percebi que você deixou tudo pronto na parte do servidor. Pois funcionou tudo, e ele já adicionava ao array e retornava o objeto {message:suscess} no POST e no GET retornava o array de carros. Queria saber se isso que eu fiz daria certo, e também como você fez ele adicionar ao array ( e mandar mensagem de sucesso, usando o POST) e como ele também retorna o array de carros que eu requisito no verbo GET. Fiquei com essa dúvida pois no app.js não vi nenhum código que faça isso.
Agradeço pela ajuda.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Moraissz! Sim, o backend eu deixei todo funcional =)

A lógica está no arquivo da rota (que eu importei como `routes`) =)

**Comment by Moraissz** [comment]
Entendi, dei uma olhada aqui. Muito Obrigado!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar =)
