### ISSUE TITLE
challenge-05

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#340]
@fdaciuk  não entendi o enunciado.

/*
Crie uma função que receba dois parâmetros: o primeiro, um array de valores; e o
segundo, um número. A função deve retornar um índice do array que foi passado
no primeiro parâmetro. O índice a ser retornado, deve ser o número passado no
segundo parâmetro.
*/

comecei fazendo dessa forma ->  function towParam ( ["lucas", 1,3,4] , 1 ) {};

**Comment by fdaciuk** [comment]
@LucasCMota dessa forma como você fez, você misturou a criação da função, com a execução da função.

Tem que lembrar o seguinte:

Na criação da função, nós passamos variáveis nos parâmetros que receberão valores quando a função for executada:

```js
function sum(x, y) {
  return x + y;
}
```

No exemplo acima, eu **criei** a função. Os parâmetros `x` e `y` pode ser qualquer coisa: arrays, objetos, números, strings, etc. Nós esperamos que sejam números, mas não há nenhum tratamento para garantir a entrada só de números.

Na execução dessa função, eu posso chamar ela assim:

```js
sum(1, 2); // 3
sum('Fer', 'nando'); // "Fernando"
sum([1, 2, 3], 2]); // "1,2,32"
```

No exemplo acima, eu estou **chamando**, **invocando** a função. Tente compreender a diferença das duas coisas :)

Conseguiu compreender?

**Comment by LucasCMota** [comment]
@fdaciuk eu cosegui entender como invoca a função, o  que não consegui enteder direito foi a questão;

  " Crie uma função que receba dois parâmetros: o primeiro, um array de valores;"

crie uma funcão -> function towParam ( ) {};
que receba dois parâmetros: o primeiro, um array de valores;-> function towParam ( ["lucas", 1,3,4] , 1 ) {};

**Comment by fdaciuk** [comment]
@LucasCMota, na criação da função, você simplesmente passa as variáveis que irão receber os valores quando você invocar a função. Independente do valor recebido, serão somente variáveis que você deve usar na hora de criar a função.

O enunciado é só pra você saber o que será feito com esses valores, quando a função for invocada :)

Entendeu?

**Comment by LucasCMota** [comment]
sim entendi

**Comment by fdaciuk** [comment]
Massa! Qualquer dúvida grita aqui :smile:
