### ISSUE TITLE
Organização de código, modularização

### ISSUE THREAD

**Issue by lorrandavid** [da2k/curso-javascript-ninja#3407]
Daciuk, tem mais materiais para organização de código? Estou tentando seguir os standards do airbnb/javascript, mas quando leio meu código, que está funcional, parece que não está muito legal, está meio bagunçado. Tem alguma dica?

Estou trabalhando em cima do projeto final que foi construído no curso: https://github.com/lorrandavid/fcc-jsninja/tree/es6

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lorrandavid! Legal que você tá transformando tudo pra ES6+ =)

Existem alguns patterns que você pode usar pra organizar o código, recomendo [essa leitura aqui](https://addyosmani.com/resources/essentialjsdesignpatterns/book/) pra ajudar =)

Mas com ES6, eu gosto de usar o `export` (sem o default), pra exportar só o que eu preciso do módulo. Aí você pode usar só funções simples mesmo, que fica até mais fácil de dar manutenção =)

Exemplo [desse arquivo aqui](https://github.com/lorrandavid/fcc-jsninja/blob/es6/js/app.js).

Ao invés de dar um `export default` na primeira função, como o módulo, por default, já fica local, você não precisaria envolver tudo em uma função, e poderia só fazer isso:

```js
export const getCars = () => {}
export const addCar = (data) => {}
```

Ae, na hora de importar, você só pega as funções que precisa:

```
import { getCars } from './app'
```

=)

**Comment by fdaciuk** [comment]
Oi @lorrandavid! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
