### ISSUE TITLE
[Aula 03] Dúvida sobre objetos

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#343]
É possível criar Loops com objetos? hhhahha sei lá mandar um for em um objeto! :)

**Comment by fdaciuk** [comment]
Ola @DaniloAgostinho! É possível sim :smile: 

Mas em breve você vai ver isso, já falamos isso nas aulas :dancer: :dancer:

**Comment by DaniloAgostinho** [comment]
Ok!   :+1:
