### ISSUE TITLE
Como disparar um evento apenas no filho

### ISSUE THREAD

**Issue by MatheusDidier** [da2k/curso-javascript-ninja#3430]
Boa tarde Daciuk, tudo bem ? 
Desenvolvendo um sistema aqui para a empresa, me deparei com um problema que já havia pensado antes, mas  tinha deixado pra lá.

O problema em questão é o fato de o javascript disparar eventos, tanto no elemento filho, quanto no elemento pai.

Pra ser mais claro:

```
<div id="A">
  <div id="B"></div>
</div>
```

Vamos supor que adicionei um evento click para o A, e um evento click para o B. Nesse caso, quando eu disparar o evento click do A, apenas o A irá executar. Até ai perfeito.

Agora se eu acionar o B, dois eventos serão disparados. O evento do click B e o evento do click A. Acontece que queria apenas disparar o evento do filho, no caso B. 

Existe alguma ferramenta presente no javascript que me permita conseguir isso que desejo, ou teria que construir alguma coisa ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusDidier! Quando você dispara um evento, esse evento "propaga" do filho para o pai. Então é comum acontecer isso: ao clicar no `#a`, somente o evento do `#a` é disparado. Já ao clicar no `#b`, tanto o evento do `#b` quanto o evento do `#a`, são disparados, pois o `#b` está dentro do `#a`, logo, você está clicando nos dois =)

Mas tem como evitar que isso aconteça sim: como eu disse, o evento "propaga" de baixo pra cima.
Para evitar essa propagação, você pode usar o `event.stopPropagation()` no filho, que, quando o evento do filho for disparado, ele deixa de propagar, e não dispara mais qualquer evento que esteja atrelado a um _parent_ =)

Seria mais ou menos isso:

```js
var $a = document.querySelector('#a');
var $b = document.querySelector('#b');

$a.addEventListener('click', function () {
  console.log('clicou no a');
}, false);

$b.addEventListener('click', function (e) {
  e.stopPropagation();
  console.log('clicou no b');
}, false);
```

**Comment by MatheusDidier** [comment]
Caraca Daciuk, impressionante seu conhecimento! Valeu cara, ajudou demais. Não achei isso em nenhum forum. Valeu mais uma vez!

**Comment by fdaciuk** [comment]
Que bom que ajudou @MatheusDidier :heart: 
Qualquer dúvida, só avisar! :D
