### ISSUE TITLE
Duvida sobre refactory ultimo challenge

### ISSUE THREAD

**Issue by Moraissz** [da2k/curso-javascript-ninja#3433]
Boa noite Daciuk, estava fazendo refactory do ultimo desafio pois estava com muito código repetido, apesar de estar funcionando perfeitamente. Portanto uma das coisas que eu tentei fazer e não estou conseguindo é o seguinte, eu tenho no meu HTML 
![tablehtml](https://user-images.githubusercontent.com/32682312/35886067-fa6a8982-0b76-11e8-86cf-ffe099b6e2fd.png)
Então, eu adiciono as trs na tag tbody usando o JS, com createElement e tal, porém, eu estou querendo quando ele adicionar uma nova linha, eu queria que todas as linhas da tbody fossem excluídas e depois puxaria do server tudo atualizado. Porém não estou conseguindo excluir as linhas(trs) da tbody. Para fazer isso eu estou tentando usar a propriedade innerHTML, porém ela aparece vazia. Não entendi porque ela está vazia,mesmo que tenha uma tr nela. Segue a imagem.
![duvidacorretatbody](https://user-images.githubusercontent.com/32682312/35886243-90c778e0-0b77-11e8-8147-1334033e03f3.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Moraissz! Preciso ver como está seu código pra entender o problema =)
Cola aqui o link de onde está esse código, por favor? =)

**Comment by Moraissz** [comment]
https://github.com/Moraissz/Projeto-Curso-JS-Ninja/blob/challenge-33/challenge-33/JS/challenge-333.js

Esse é o código. Basicamente eu quero adicionar uma função pra limpar todo o conteúdo da tag tbody, como não deu certo eu apaguei a função.

**Comment by Moraissz** [comment]
![cleartable](https://user-images.githubusercontent.com/32682312/35920918-6a78db6e-0c00-11e8-8d65-61147f2f67ec.png)
Essa seria a função, que eu apaguei

**Comment by fdaciuk** [comment]
Consegue atualizar o código do repositório com o código que não está funcionando? Preciso entender exatamente o que você está fazendo pra te dizer o porquê do problema =)

**Comment by Moraissz** [comment]
https://github.com/Moraissz/Projeto-Curso-JS-Ninja/tree/challenge-33-help/challenge-33-help
Atualizei o código para mostrar, o erro, o que está comentado é o que eu queria tirar. A minha ideia nisso é que toda a vez que ele adicionar um carro, a tabela seja limpada e depois puxada do servidor.

**Comment by fdaciuk** [comment]
Agora sim eu consegui ver o seu problema =)
Na verdade, o que acontece é que, como na lib DOM nós usamos o `querySelectorAll`, ele simplesmente pega os elmentos do DOM no momento em que é executado.

Lembre-se que ele não mantém uma lista "viva", então qualquer atualização no elemento do DOM não vai refletir no conteúdo da variável, entendeu? Nesse caso, a cada vez que você precisar dos dados atualizados de `$tableBody`, você precisa "pegar" novamente o elemento =)

**Comment by Moraissz** [comment]
Ah, entendi, Muito Obrigado.

**Comment by fdaciuk** [comment]
Legal! Qualquer dúvida, só avisar =)
