### ISSUE TITLE
algoritimos

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#347]
@fdaciuk 
sabe de algum site que tenha exercicios de algoritimos para mim faze-los em js, preciso praticar muito essa parte, melhorar minha logica,  ja procurei no google não consegui encontrar, so encontrei livros e por sinal bem caros

**Comment by fdaciuk** [comment]
@LucasCMota, tem vários lugares onde você pode encontrar exercícios de lógica, principalmente em inglês. Mas o ideal é você tentar manter o ritmo do curso, fazendo os desafios, estudando o que está sendo passado o máximo possível.

Conhecendo a linguagem, vai melhorar muito a sua forma de pensar em lógica. Até porque isso vai depender sempre da linguagem que você está utilizando. Javascript pode ser escrito usando vários paradigmas, e nós iremos aprender vários deles.

Continue com os desafios, tente mudar alguns, passar valores diferentes, tentar gerar erros. Dessa forma você vai entrando mais em contato com a linguagem e vai aprendendo cada comportamento dela :D 

Se eu puder ajudar em algo a mais, me avise :)

**Comment by LucasCMota** [comment]
@fdaciuk 
teve 2 exercicios que bati muito a cabeça tetando resolver, e quando vi a resolução era tão simples,fiquei indignado de não ter conseguido pensar daquela forma

**Comment by fdaciuk** [comment]
@LucasCMota, então, mas isso é questão de treinar. Procurar entender o problema e testar formas diferentes de resolvê-lo. Assim você vai conseguir pensar em diferentes formas de resolução.

Mas nem sempre a forma que eu mostro é a melhor forma de resolver. Em alguns exercícios, depois que eu fiz a revisão, vi que poderia ter feito de forma melhor. Esse é um período de evolução: quanto mais você tem contato com a linguagem e mais treina, mais fácil fica de resolver os problemas :)

O segredo é treinar bastante! Fazer e refazer os exercícios, tentar resolver de várias formas diferentes!

Você vai ver que, com o passar das aulas, você vai se desenvolvendo! Procure sempre enviar os pull requests antes de ver a solução do desafio. Assim fica mais fácil de você gravar outras formas de resolver o mesmo problema :)

**Comment by LucasCMota** [comment]
@fdaciuk , somete em 2 exercicios eu dei uma espiada, e depois fiz do meu jeito,porque não adiataria de nada eu ficar vendo a resolução sem bater um pouco a cabeça, pois essa parte é a que mais gosto,algo que me faça exercitar a mente, no entanto eu ja estava a 3 dias no mesmo exercicio

**Comment by LucasCMota** [comment]
@fdaciuk um vizinho trabalha com js, me deu um desafio, isso ja faz uns 4 meses.
  fazer um programa que entre com um numero qualquer e retorne um numero romano equivalente a ele, nunca consegui resolver.

**Comment by fdaciuk** [comment]
Até um pouco antes do final do curso você já vai ter as skills necessárias para resolver esse desafio :D

**Comment by LucasCMota** [comment]
ele disse que quando eu conseguisse resolver eu estaria pronto para ir atraz de um trampo na area

**Comment by fdaciuk** [comment]
É um desafio bastante complicado por sinal, pois tem bastante lógica envolvida :)

Mas conhecendo a lógica de como os números romanos são montados, e conhecendo a linguagem, para saber o que você pode usar, você consegue resolver sim :D

**Comment by LucasCMota** [comment]
@fdaciuk 
```js
function decimalToRoman( decimal ) {
    var roman = { M:1000, CM:900, D:500, CD:400, C:100, XC:90, L:50, XL:40, X:10, IX:9, V:5, IV:4, I:1};
    var setRoman = '';
    var i;

    for( i in roman ){
       while(decimal >= roman[i] ){
            setRoman += i;
            decimal -= roman[i];
        }
    }
    return setRoman;
}
```

**Comment by fdaciuk** [comment]
\o/
Muito bom cara :D

**Comment by LucasCMota** [comment]
pois é, depois que consegui resolver  vi que somente isso não vai me dar um trampo, na hora que consegue resolver é maravilhoso, depois de um uns dias vi que eu que não era tão maravilho assim e eu que era burro que não tinha pensado nisso antes

**Comment by fdaciuk** [comment]
haha! Capaz cara.. é tudo a forma de pensar.. você está evoluindo bastante a cada desafio no curso, e isso vai fazer toda a diferença daqui pra frente.

Agora que você já conseguiu resolver esse problema, siga em frente nos desafios do curso, e tente criar alguns projetos por conta própria, para treinar ainda mais! Você vai ver que, em pouco tempo, o resultado do que você vai estar fazendo vai ser surpreendente :D

**Comment by LucasCMota** [comment]
valeu pelo incentivo

**Comment by fdaciuk** [comment]
o/
