### ISSUE TITLE
challenge-07 duvida

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#348]
@fdaciuk 
por quê nesse exemplo ele mostra no fim o 20 duas vezes?

``` js
   var init =10;
    while(init <=20){
        console.log(init);
        init++;
    };  
 // 10 11 12 13 14 15 16 17 18 19 20 20
```
e nesse outro não? sendo que a estrutura é a mesma só diferencia porque está dentro de uma  ```function() ```
``` js
function cont(){
   var init = 10;
    while (init <=20){
        console.log(init);
        init ++;
    };
}
cont();
// 10 11 12 13 14 15 16 17 18 19 20 
```

**Comment by fdaciuk** [comment]
@LucasCMota, você deve estar testando direto no console, correto? Isso acontece porque o console mostra, na última linha, o resultado da expressão.

Como no while você está modificando o valor do `init`, vai ser feito o while, mostrando os valores do console.log(), e no final, o valor final do `init`.

No caso da função, como ela não tem retorno, o resultado dela é `undefined`.

Por isso é mostrado os números de 1 a 20, e no final `undefined`. 

Perceba que tem uma setinha quando ele mostra o resultado da expressão:

![selection_146](https://cloud.githubusercontent.com/assets/487669/10090703/d1b59e28-6308-11e5-957b-21ee1378241f.png)

![selection_147](https://cloud.githubusercontent.com/assets/487669/10090705/d642b8fe-6308-11e5-941f-e5507c7330a1.png)


Para ver o que acontece realmente no código, você pode testar no [jsbin.com](http://jsbin.com/wisicuzuzu/edit?js,console), ou importar o seu script em um arquivo html.

Ficou claro? :)

Outro detalhe: não se utiliza ponto e vírgula ao final de estruturas de repetição, estruturas condicionais e funções literais :)

**Comment by LucasCMota** [comment]
saquei, não tinha reparado no undefined, era outra duvida que eu tinha sobre o uso do ponto e virgula, achava que era usado tambem no fim das instruções  for e while alem das variaves

**Comment by fdaciuk** [comment]
Massa! Então, sobre a regra do ponto-e-vírgula, você vai usar ele no final de toda expressão. Basicamente, o que não são expressões em JS (e onde você não vai usar o ponto e vírgula), é:

após `if` e `switch`, `while`, `do/while`, `for`, `try/catch` e `function` literal. Se estiver atribuindo uma função à uma variável, então você deve usar o ponto-e-vírgula.

Basicamente isso xD

**Comment by LucasCMota** [comment]
fechou então,não esqueço mais
