### ISSUE TITLE
Challenge-15

### ISSUE THREAD

**Issue by felipegandradee** [da2k/curso-javascript-ninja#3493]
Boa noite Fernando, tudo bem ?

Minha dúvida é apenas um detalhe que deixei escapar algumas vezes, é sobre o 'console.log'
`console.log(felipe.getFullName(), 'tem', felipe.getAge(), 'anos.');
  console.log(felipe.getFullName() + 'tem' + felipe.getAge() + 'anos.');`

Neste caso se eu usar tanto a vírgula ou o sinal de mais para concatenar, não há problema? E qual é mais recomendado usar?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felipegandradee! O `console.log` pode receber "infinitos" parâmetros, separados por vírgula. Eu recomendo usar sempre dessa forma.

Usando o `+` pra concatenar, todos os valores serão transformados em _string_ antes de serem exibidos.

Isso não é problema se todos os tipos a serem exibidos forem primitivos (string, number, boolean). Agora, se for algum objeto - do tipo `console.log('Meu objeto:' + { prop: 1 })` -, será exibido `Meu objeto:
 [object Object]`, pois o objeto será convertido em string, já que você está tentando concatenar com uma string =)

Então minha recomendação é sempre usar como parâmetros mesmo, separando por vírgula, que os valores serão sempre exibidos corretamente =)

**Comment by felipegandradee** [comment]
Muito obrigado @fdaciuk , sanou minhas dúvidas :D

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
