### ISSUE TITLE
[Dúvida] Desafio 5 

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#351]
@fdaciuk ,

Pode me dizer onde esta o erro nesta minha função? Quando eu passo por paramêtro o nome do Livro tenho um retorno undefined.

```javascript
function book( livro ) {
	var livros = {
		 crepusculo: {quantidadePaginas: 260, autor: ' clarice ' , editora: 'Abril'},
		 alquimista: {quantidadePaginas: 260, autor: ' Paulo coelho ' , editora: 'Abril'},
		 mensagens: {quantidadePaginas: 260, autor:  ' Flavio siqueira ' , editora: 'Abril'}
	};

	return livro;

	if( livro === undefined ) {
		return livros;
	}

}
```
Será que é no return?

**Comment by fdaciuk** [comment]
@DaniloAgostinho, lembre-se do seguinte: sempre que você usa o `return`, tudo o que vem após ele é ignorado.

Você está fazendo um `if` após o `return livro`. Esse `if` nunca será executado :)

**Comment by fdaciuk** [comment]
Outro erro é que você está retornando o próprio parâmetro. Deveria retornar o objeto `livros`, com base no parâmetro passado ;)

E mais um: as propriedades do objeto podem ser strings, então você pode colocar o nome completo do livro :)

**Comment by DaniloAgostinho** [comment]
@fdaciuk Okay, resolvido!
