### ISSUE TITLE
Problemas no blog

### ISSUE THREAD

**Issue by Joaoh3326** [da2k/curso-javascript-ninja#3516]
Daciuk, esta ocorrendo um problema no seu blog, pelo menos comigo, não estou conseguindo acessar esta dando o erro de privacidade quando tento acessar seu blog, só pra avisar :) , e tbm porque quero dar uma lida nos posts :D

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, valeu por avisar! Já estou resolvendo =)

Comento aqui assim que estiver tudo ok =)

**Comment by fdaciuk** [comment]
Done ;)
