### ISSUE TITLE
challenge-08

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#354]
@fdaciuk 
estou tendo dificuldades com esse exercicio, o parametro da 1° function que recebe o operando está concatenando com o os paramentros da segunda function,não sei como resolver esse problema

```js
Crie uma função literal chamada `calculator`, que funcione assim:
- A função deve receber um parâmetro que dirá qual operação matemática ela
vai efetuar. Será uma string com os valores `+`, `-`, `*`, `/` ou `%`;
- Essa função deve retornar uma segunda função que fará o seguinte:
  - Essa segunda função deve receber dois parâmetros;
  - Esses dois parâmetros serão os operandos usados na operação matemática;
  - O retorno dessa segunda função é a operação matemática completa, com a frase:
  "Resultado da operação: [NUMERO1] [OPERADOR] [NUMERO2] = [RESULTADO]."
  - Se o operador não for válido, retornar a frase:
  "Operação inválida."
```

**Comment by fdaciuk** [comment]
@LucasCMota, envia o Pull Request como está pra eu ver como você está fazendo. Assim fica mais fácil de te ajudar :)

Dae vou te acompanhando na resolução do desafio, ok? :)

**Comment by LucasCMota** [comment]
@fdaciuk 
não estou conseguindo dar o pr, tem uma mensagem que diz que há conflitos e devem ser resolvidos

**Comment by fdaciuk** [comment]
Consegue me mandar o print com um `git status` pra eu ver qual arquivo está com conflito?

**Comment by LucasCMota** [comment]
![gitstatus](https://cloud.githubusercontent.com/assets/13294634/10125755/a382422c-6556-11e5-9d44-88acd895898b.png)

**Comment by fdaciuk** [comment]
@LucasCMota, comentei lá no seu PR, mas o que você tem que fazer é atualizar a sua branch, fazendo o fetch e merge nessa branch do desafio 8.

Também tem essa alteração no desafio 07, que você deve voltar para o arquivo original antes de comitar.

Depois disso, é só fazer o push que vai ficar tudo certo :)

Qualquer problema me avise :)

**Comment by LucasCMota** [comment]
@fdaciuk sempre que faço uma atualização, todos os meu arquivos locais voltam ao original sem a resolução.

**Comment by fdaciuk** [comment]
@LucasCMota, sempre que você volta para a branch master, deve ser exatamente esse o comportamento: nenhum exercício deve estar resolvido. As branchs são como ambientes separados. Por isso nós criamos uma branch por desafio. Em cada branch vai resolução de apenas um desafio, relacionado àquela branch. :)

**Comment by LucasCMota** [comment]
@fdaciuk entao o correto é ficar limpo mesmo? sempre que isso acontecia eu dava um ctrl z

**Comment by fdaciuk** [comment]
Isso, o correto **na master** é ficar limpo sim :)

**Comment by fdaciuk** [comment]
@LucasCMota vou fechar essa Issue, se tiver mais alguma dúvida referente à esse problema, pode reabrir, ok? :)
