### ISSUE TITLE
Função de CallBack - Exercício 09 - Parte 2

### ISSUE THREAD

**Issue by ricardomirannda** [da2k/curso-javascript-ninja#3566]
Olá Daciuk, tudo bem contigo?
Esse exercício me deixou bastante confuso. 

function calculadora( numero1, numero2 ){
  
  return function( callback ){
    return callback( numero1, numero2 );
  };

}

var sum = calculadora( 10, 2 ); 

console.log('O resultado da soma é:',  sum(function( number1, number2 ) {
  return number1 + number2;
}) );

----------- DÚVIDA -----------------

Aqui **sum** já está recebendo uma função 
var sum = calculadora( 10, 2 ); 

Aqui **sum** está agora recebendo uma função anônima 
sum(function( number1, number2 )

Se a variável **sum** já recebe uma função **CALCULADORA** e em seguida recebe uma outra **função anônima**, ela seria automaticamente **SOBRESCRITA**, ou seja, se a função anônima foi atribuída por último, logo o valor da função **calculadora**, será perdido automaticamente. 

Você poderia me explicar melhor esse exercício? 

Agradeço desde já !

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Vamos lá =)

Se você reparar bem, você não faz duas atribuições, logo não está acontecendo nenhuma sobrescrita =)

Veja se [essa explicação deixa um pouco mais clara a intenção do exercício](https://github.com/da2k/curso-javascript-ninja/issues/1268#issuecomment-279402106).

Se ainda ficou alguma dúvida, comenta aqui que eu vou tentando detalhar melhor, ok? =)

**Comment by ricardomirannda** [comment]
Olá Daciuk, 
Eu li e reli várias vezes o link que você enviou com uma dúvida de uma aluna, mesmo assim ainda continuo com uma dúvida ... 

 var sum = calculadora(1,2); // Estamos **atribuindo** a sum uma função 

console.log('O resultado da soma é:',  sum(function( number1, number2 ) // sum está **recebendo** uma função anônima.

Uma das dúvidas é:
Como sum consegue ter **atribuição** da função calculadora e depois consegue **receber** uma função anônima?  Eu pensei que isso não fosse possível.

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Sem problemas, vamos lá =)

Bom, o problema no entendimento está, na verdade, na leitura da primeira atribuição.

O que nós fazemos aqui:

```js
var sum = calculadora(1,2);
```

Na verdade não é **atribuir uma função** para a variável `sum`. Veja que estamos **executando** a função `calculadora`. Nesse caso, o que está sendo passado para `sum` é o **resultado** da função `calculadora`, ou seja: o que ela retorna =)

E o que a função `calculadora` retorna? Uma nova função! Por isso agora nós podemos usar `sum` como função :D 

Essa função que é passada para `sum` faz o seguinte: ao ser executada, ela espera que uma outra função seja passada por parâmetro.

É a função que chamamos de `callback`.

O que acontece é que, dentro da função `calculadora`, nós fazemos o que é chamado de **inversão de controle**. Como `callback` vai ser uma função, não interessa para a `calculadora` o que ela faz. A `calculadora` só executa ela e passa os dois valores que ela recebeu de volta.

Nesse caso, é responsabilidade da função `sum` fazer alguma coisa com esses dois valores, pois a responsabilidade de fazer algo com o `callback` foi passada para `sum` =)

Veja que usamos a função `calculadora` apenas para passar dois valores. O que vamos fazer com esses dois valores vai depender da chamada da próxima função.

No caso de `sum`, nós passamos para ela uma função que retorna a soma dos dois valores recebidos.

Com isso, nós conseguimos fazer todas as operações matemáticas, reaproveitando os valores passados para `calculadora` =)

Ficou mais claro? =)

**Comment by ricardomirannda** [comment]
Oi Daciuk,
Passei o final de semana procurando sobre o assunto, aliado a sua explicação, ficou bem mais claro o funcionamento da função de callback. 

Muito obrigado pela explicação e pela atenção, são essas características que fazem você um cara muito foda !!!

**Comment by fdaciuk** [comment]
Obrigado @ricardomirannda :heart: 
Que bom que ficou claro =)
Qualquer dúvida, só avisar :D
