### ISSUE TITLE
duvida IIFE

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#359]
@fdaciuk Vi toda a aula 09 e antes de fazer o exercicio fui pensar sobre o que seria uma IIFE, me veio algumas ideias do que ela seria e fiz algumas analogias. A IIFF  "seria como uma especie de casulo,escudo ou algo do tipo para proteger o codigo" e tive a ideia de quadrados dentro de varios outros quadrados no caso os quadrados seriam as functions(ou um aninhamento de functions).Isso seria algo certo a a se pensar sobre a IIFF?
seria correto sempre ultiliza-la em todo o tipo de codigo? esse tipo de codificação gera algum tipo de segurança ao projeto?

**Comment by ffabiorj** [comment]
Há vários locais que podemos usar uma IIFE, porém o mais comum é quando queremos criar um escopo no JavaScript para que as variáveis definidas dentro da função não poluam o escopo global (variáveis definidas no window).

Isso é tudo a respeito de evitar ao máximo criar variáveis globais no JavaScript, e criar escopos quando e onde precisarmos.

Assim mantemos as variáveis todas dentro do nosso código, evitando que o JavaScript de outras pessoas alterem nossas variáveis. Como libs de terceiros ou curiosos com o DevTools aberto. Imagina alguém alterando o preço de um produto porque a variável “productPrice” é global? Não seria legal. (Um exemplo hipotético, acho que você sacou a ideia)

**Comment by LucasCMota** [comment]
@ffabiorj posso colocar todo o projeto dentro da IIFE? pelo que entendi gera seguraça

**Comment by ffabiorj** [comment]
sim. Mais em projeto de verdade vc não vai fazer isso..rsrsr

Lá para frente do curso, vc vai ver melhor.

**Comment by fdaciuk** [comment]
@LucasCMota, a IIFE é só uma função auto-executável. Como o @ffabiorj comentou, ela serve para manter o código local, já que o JS tem escopo de função, e tudo o que está declarado dentro de uma função pertence somente àquele escopo, e não vaza pra fora.

A ideia da IIFE é servir como uma closure. Não me apeguei a esses termos técnicos ainda, porque vamos ver isso mais pra frente, quando falarmos sobre modularização de código.

Mas a ideia base da IIFE é manter o código interno "protegido" do código de fora mesmo :)

E sim, você pode colocar todo o seu projeto dentro de uma IIFE, mas não deve colocar tudo em um arquivo só. Mas cada arquivo deve sim ter uma IIFE (dependendo da forma que vc vai modularizar seu código).

Mas IIFE serve também para outras coisas. Quando formos estudar o conceito de closures e modularização você vai entender melhor :)

Por enquanto, ela é somente uma "protetora" pra não deixar nosso código ficar no escopo global xD

**Comment by fdaciuk** [comment]
Se quiser saber mais sobre IIFE, escrevi esse artigo: http://blog.da2k.com.br/2015/02/20/os-segredos-da-iife/

:)
