### ISSUE TITLE
Correção exercício challenge-17

### ISSUE THREAD

**Issue by fsoaresjunior** [da2k/curso-javascript-ninja#3601]
Escreva aqui sua dúvida
Na correção do último exercício você cria uma função que manipula a data, e na hora de fazer o replace você simplesmente chamou a função e sem utilizar o () e nem passar os devidos parâmetros:

console.log(text.replace(regexDate, replaceDate));

Gostaria que você me explicasse o porque do código funcionar, já que eu não estou invocando a função nem passando os parâmetros necessários.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fsoaresjunior! Veja que o método `replace` espera sempre no segundo parâmetro, ou uma string, ou uma função.

Nós passamos a função sem executar, porque ela é executada pelo método `replace`. Se nós executarmos essa função, o que será passado para `replace` não vai mais ser a função, e sim o **retorno da função** =)

Veja o seguinte exemplo:

```js
console.log(text.replace(regexDate, function replaceDate() { /* código da função aqui */ }));
```

Perceba que, fazendo dessa forma, nós só passamos uma função para `replace`, não executamos ela, correto?

É exatamente a mesma coisa. A diferença é que nós extraímos a função, e só passamos a referência para o método `replace`, pois não somos nós que iremos executar a função, e sim o método `replace`:

```js
function replaceDate() { /* código da função aqui */ }
console.log(text.replace(regexDate, replaceDate));
```

Ficou mais claro?

**Comment by fsoaresjunior** [comment]
Ficou sim, muito grato pela resposta.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa só avisar =)
