### ISSUE TITLE
Sugestão de melhorias - Operador de módulo

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#362]
@fdaciuk 

Estou praticando o operador de módulo, criei esta função que descobre se o número é par ou impar, o If foi bem empregado aqui? 

<pre>
function descobreTipo() {
	var numero1 = prompt('digite seu numero1: ');
	var numero2 = prompt('digite seu numero2: ');

	//condicional if ternário
	numero1 % numero2 === 0 ? console.log('numero par') : console.log('impar')
}
</pre>

**Comment by fdaciuk** [comment]
@DaniloAgostinho, o ternário pode ser utilizado em 2 casos:

1. Quando você atribui o resultado à uma variável;
1. Quando você retorna o resultado de uma função.

Se for utilizar ele "solto", só para mostrar uma mensagem no console, melhor usar o `if`.

Uma melhor forma de utilizar, nesse caso do seu exemplo, seria:

```js
function descobreTipo() {
    var numero1 = prompt('digite seu numero1: ');
    var numero2 = prompt('digite seu numero2: ');

    //condicional if ternário
    return numero1 % numero2 === 0 'par' : 'impar';
}
console.log( descobreTipo() );
```

Lembrando que, se você está utilizando uma função para testar o retorno de algum valor, a função deve sempre retornar esse valor (usando `return`), e não usar o console.log no lugar do return.

O console.log serve somente para fins de debug. Se usar console.log dentro da função, sem usar return, a função retornará `undefined`, já que não tem nenhum `return` nela, fazendo com que a sua validação possa ficar inconsistente :)

**Comment by DaniloAgostinho** [comment]
@fdaciuk Boas considerações, mas essa função esta retornando um erro.

![sem titulo](https://cloud.githubusercontent.com/assets/13303320/10229703/e7050678-684f-11e5-8468-78f6de3d6374.png)

**Comment by DaniloAgostinho** [comment]
@fdaciuk Encontrei o erro estava faltando o sinal de interrogação.

![solucao](https://cloud.githubusercontent.com/assets/13303320/10229801/459dc51c-6850-11e5-945a-e49fe863091f.png)

**Comment by DaniloAgostinho** [comment]
@fdaciuk Thanks!

**Comment by fdaciuk** [comment]
Perfeito, isso mesmo! Desculpe pelo erro de digitação :)

**Comment by DaniloAgostinho** [comment]
@fdaciuk estamos aqui pra isso! Errar e aprender.
