### ISSUE TITLE
challenge 15 

### ISSUE THREAD

**Issue by marianathyelle** [da2k/curso-javascript-ninja#3626]
Olá @fdaciuk, tudo bem? 
Eu vi o vídeo da correção do exercício 15 e notei que em uma parte, eu fiz algo um pouquinho diferente e queria saber se tem algum problema o que eu fiz. 
Seguinte: 
Pra criar o método **addAge** da função construtora, você fez: `this.addAge = function addAge() { this.age += arguments[0]; return this; };`
E quando foi invocá-lo, você fez: `person.addAge(2).getAge()`

E eu fiz assim: `this.addAge = function addAge() { return this.age += arguments[0] };`
E pra invocá-lo: `person.addAge(2)`

Foi um pouquinho diferente, eu coloquei o return já antes da instrução ao invés de colocar `return this`. e ai pra invocar só chamei o método e passei o argumento. Funcionou, teve o mesmo resultado. Mas tá errado fazer dessa forma? Tem algum problema? Obrigada desde já! 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marianathyelle! Tudo ótimo, e contigo? =)

Nesse caso, o resultado é um pouquinho diferente =)

O que acontece: a ideia do método `addAge` seria somente adicionar mais "anos" à pessoa. Logo, ela não precisaria retornar valor algum, pois para "pegar" o valor, temos o método `getAge`, certo?

Nesse caso, a diferença é que: como você fez, `addAge` agora retorna um valor, que é a idade final.

Seria o mesmo que usar o `getAge` já faz.

No exemplo que eu mostrei, como `addAge` não precisaria retornar um valor, eu retornei o `this`, pois o `this` vai representar o objeto instanciado, a nova pessoa criada.

E a nova pessoa tem os métodos `addAge` e `getAge`. Logo, retornando o `this`, nós teremos acesso ao método `getAge` logo após executar o `addAge`, podendo usar assim:

```js
console.log(person.addAge(2).getAge());
```

No caso, da forma que você fez, para "pegar" a idade logo após adicionar, não daria pra usar o método `getAge` encadeado, teríamos que usar duas expressões:

```js
person.addAge(2);
console.log(person.getAge());
```

A ideia de fazer como eu fiz é apenas para tentar manter o código mais "semântico". Uma função que se chama `addAlgumaCoisa` deveria "adicionar alguma coisa", não retornar um resultado.

Já funções que começam com `get`, significa que nós vamos usá-la para "obter" algum valor =)

Ficou claro a diferença? =)

**Comment by marianathyelle** [comment]
Ahhh, entendi! Ficou claro sim, obrigada! =')

**Comment by fdaciuk** [comment]
Legal! Nada =)
Qualquer dúvida, só avisar :D
