### ISSUE TITLE
Duvidas aula 10

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-javascript-ninja#364]
"sum" agora é uma função, e, se o sinal correto não foi passado para a
função "calculator", "sum" será false. Certifique-se de que "sum" não é
"false", e então atribua às variáveis "number1" e "number2", dois números
que serão os operandos da operação de soma.
Após isso, mostre no console o resultado da operação, passando dois
parâmetros para o método "log" de "console":
- O primeiro será a mensagem da operação (usando a função criada acima);
- O segundo, a função de soma, passando os dois operandos.
- Se "sum" for "false", mostrar no console a mensagem de erro.

quando eu atribuo um operador incorreto á calculator, meu código da erro, no caso desse exercício a atribuição das variaveis e feita dentro do console.log, pois as variaveis ja tao la na função calculator. 

em que aula começamos a pegar itens de um input, criei um projeto aqui bem simples e so falta isso pra eu poder por ele no ar. essa parada de programação funcional é loka demais, to curtindo pra caramba.

**Comment by fdaciuk** [comment]
> quando eu atribuo um operador incorreto á calculator, meu código da erro, no caso desse exercício a atribuição das variaveis e feita dentro do console.log, pois as variaveis ja tao la na função calculator.

@brunotortelli, preciso ver como você está fazendo para te ajudar :)
Envie o pull request e comente lá a sua dúvida, que eu vou ver para te ajudar, ok? xD

---

> em que aula começamos a pegar itens de um input, criei um projeto aqui bem simples e so falta isso pra eu poder por ele no ar.

Na aula 15 começamos com JS no browser aprendendo um pouco mais sobre escopo.
Na aula 20 já damos início à manipulação de DOM. Após essa aula é praticamente tudo no browser xD

**Comment by fdaciuk** [comment]
> essa parada de programação funcional é loka demais, to curtindo pra caramba.

Que bom que está gostando! Isso que iremos ver só a parte mais básica, para entender como tudo funciona no JS! Depois você vai poder estudar muito mais sobre se quiser :D
