### ISSUE TITLE
Problemas com git - pull requests

### ISSUE THREAD

**Issue by raphaelanjos1** [da2k/curso-javascript-ninja#3659]
Boa tarde Daciuk, estou abrindo essa issue porque estou fazendo algo de errado, percebi isso quando comparei meus pull requests com o de colegas.

O meu challenge-01, que foi feito na mão, saiu perfeito, mas a partir do pull request challenge-02, o problema surgiu. Quando faço o pull request, ao invés de enviar somente o commit referente ao challenge, ele está enviando todos os commits feitos até o momento (de outros challenges, e eles nem aparecem no git status). E pra piorar a situação, o código simplesmente some do meu vscode após esse processo...

olha só como está o meu pull do challenge-03:
https://github.com/da2k/curso-javascript-ninja/pull/3653

Se você puder me ajudar, ficaria muito grato, pois só vou prosseguir com o curso quando conseguir fazer tudo da forma correta :100: 

No mais, todas as aulas tem sido ótimas.

@fdaciuk

**Comment by raphaelanjos1** [comment]
Resolvido ! Estava errando na hora do pull request!

**Comment by fdaciuk** [comment]
Opa, conseguiu resolver? Legal! Qualquer coisa, conte comigo =)
