### ISSUE TITLE
um problema na resolução da atividade 14 

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-javascript-ninja#3660]
Escreva aqui sua dúvida

ao percorrer meu array "numberObjects" ele sempre tras como return -1
sendo q foram declarados como :
 numberObjects=[]

for (var i = 0; i<10 ; i ++) {

    numberObjects.push({numero :i})
}
 
-----------------------------------------------------------------

aqui utilizando o indexOf : 

 
 if ( numberObjects.indexOf({ numero: 2 }) > -1) {
console.log("tem esse objeto")
}else 
console.log("nao tem esse objeto");
-----------------------------------------------------------------
outra duvida é , poderia utilizar o formato :
variavel ? true : false

Vlw Daciuk , seus cursos estão massa !!

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @TMiranda7! 

Sobre o `indexOf` retornar só `-1`, é isso mesmo!
Dá uma olhada na solução do desafio que eu explico certinho o que acontece =)

Sobre usar ternário no lugar do `if`: veja que o ternário é uma expressão, ou seja: ele sempre te retorna um valor.

Já o `if` apenas cria um bloco de código para você fazer algo se alguma condição for `true`, sem te retornar nada.

Então, para saber quando usar `if` e quando usar ternário:
- Se você precisa do valor retornado pela expresão para atribuir à uma variável ou retornar em uma função, você pode usar o ternário.
- Se apenas precisa testar uma condição, e não precisa usar diretamente o valor, pode usar `if`.

No caso do exemplo, o que você faz ao testar por `numberObjects.indexOf({ numero: 2 }) > -1`? 

Apenas exibe um `console.log` certo? Então, nesse caso, você não precisa do valor retornado pelo resultado da expressão. Aí você usa `if` =)

Agora, se você fosse usar o resultado da expressão `numberObjects.indexOf({ numero: 2 }) > -1` para atribuir a uma variável ou retornar de uma função, então você poderia usar o ternário =)

Ficou claro? =)

**Comment by TMiranda7** [comment]
Sim , entendi , Vlw pelo esclarecimento !

**Comment by fdaciuk** [comment]
Legal! Qualquer dúvida, só avisar =)
