### ISSUE TITLE
Editoconfig

### ISSUE THREAD

**Issue by garritanoo** [da2k/curso-javascript-ninja#3670]
Opa!

E aí, tudo bem Fernando!?

Eu estou com algumas dúvidas referente ao Editorconfig.

Eu gostaria de saber o que significa o _"supported values"_ de cada linha e esse _"root"_.

root
charset (supported values: latin1, utf-8, utf-16be, utf-16le)
end_of_line (supported values: lf, crlf)
trim_trailing_whitespace (supported values: true, false)
insert_final_newline (supported values: true, false; Setting this to false strips final newlines)
max_line_length

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @garritanoo! Vamos lá =)

O `root` é uma configuração específica do `editorconfig`, que serve, basicamente para que, ao encontrar o arquivo `.editorconfig` no seu projeto, e ver o `root=true` ali, ele pára de procurar, e sabe que é esse arquivo que tem que usar. É uma configuração apenas para otimização.

Citando a documentação:

> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

---

O `charset` é pra setar a tabela de caracteres usada por padrão para abrir os arquivos. `utf-8` normalmente é usado pois contém todos os caracteres que nós precisamos e usamos diariamente para escrever código.

`end_of_line` é usado pra controlar o tipo de quebra de linha. O padrão Unix (mac e Linux) é `lf`. Deixando esse padrão, ele será usado no windows também que tem um padrão diferente.

`trim_trailing_whitespace` é pra remover espaços ao final de cada linha.

`insert_final_newline` é pra adicionar uma quebra de linha ao final de cada arquivo. Isso é útil, por exemplo, quando você usa comandos como `cat` no linux pra ler um arquivo. Se tiver uma quebra de linha no final, o final do arquivo não vai se misturar com o prompt do terminal que vc está usando, já que o `cat` (e outros comandos de leitura de arquivos) não adicionam uma quebra de linha ao terminar de ler o arquivo. É para facilitar a legibilidade do código.

`max_line_length` acho que só funciona no `vim`, e serve pra colocar aquela "linha" vertical, marcando a quantidade de colunas que um arquivo deve ter. Por padrão, eu gosto de usar 80, pra dizer que você só pode colocar 80 caracteres em uma linha. Isso facilita a leitura, já que o código não fica muito "horizontal", tendo que ficar fazendo scroll pra direita e esquerda. Com 80 caracteres, você mantém o código bem vertical em qualquer monitor, e ainda se quiser separar a tela em 2, pra colocar o editor de um lado, e o browser do outro =)

**Comment by garritanoo** [comment]
Obrigado!

Em 26 de fev de 2018 16:01, "Fernando Daciuk" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
