### ISSUE TITLE
rodando a aplicação 

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-javascript-ninja#3718]
boa tarde , Fernando
na resolução da atividade , não consegui faze-la retornar no console.
na construção da minha index estava tudo ok  , inclusive na inspeção consegui ver meu arquivo challenge-15 mas não havia retorno , isso é uma forma de erro ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Não entendi muito bem o problema. Consegue compartilhar o repositório com o código que você está em dúvida, pra tentar deixar mais claro? =)

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)

**Comment by TMiranda7** [comment]
ola , boa tarde , consegui verificar o problema e resolvi , nn tive tempo
de fechar mas desde de já agradeço

2018-03-08 11:49 GMT-03:00 Fernando Daciuk <notifications@github.com>:

**Comment by fdaciuk** [comment]
Show @TMiranda7! Qualquer coisa só avisar =)
