### ISSUE TITLE
subir arquivos em diferentes branchs depois de prontos

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-javascript-ninja#374]
eu tenho feito mais de um exercício antes de poder subir para o github, como eu faço pra subir o exercicio certo em cada branch, quando eu dou status aparece 3 arquivos.

**Comment by fdaciuk** [comment]
Olá @brunotortelli! O que você precisa fazer é o seguinte:

1. Rodar o `git status` pra ver se precisa comitar algo
1. Se estiver tudo ok, ir para a master, com `git checkout master`
1. Atualizar a master com `git fetch upstream` e depois `git merge upstream/master`
1. Depois, criar a branch do desafio que você irá resolver, com `git checkout -b challenge-xx`, trocando o `xx` pelo número do desafio
1. Feito isso, você deve resolver **só esse desafio**
1. Com o desafio resolvido, faça o add, commit e push: `git add .`, depois `git commit -m "mensagem de commit"`, depois `git push origin challenge-xx`

Feito isso, já estará no Github o seu desafio, na branch correta.

Para fazer os próximos desafios, siga os mesmos passos, indo sempre para a master antes de atualizar :)

Qualquer dúvida grita xD

**Comment by matheuswd** [comment]
Aproveitando a Issue, acho que comigo aconteceu a mesma coisa. Fiz o 5 e o 6. Ja havia feito o PR da 5 e resolvi o exercicio 6 e fiz o commit (tudo na branch certa, ou seja, na branch challenge-06). Contudo, na hora de fazer o PR sobe os dois challenges.

**Comment by matheuswd** [comment]
@fdaciuk será que dá pra dar um help?

**Comment by fdaciuk** [comment]
@matheuswd o problema é o mesmo: provavelmente você fez criou a branch `challenge-06` enquanto estava na branch `challenge-05`.

Para resolver o seu caso, você precisa pegar o arquivo original do desafio 05 (sem a solução), e substituir ele na branch do `challenge-06`. 

Assim, quando for mandar o PR, não vai dar diferença nesse arquivo :)

**Comment by brunotortelli** [comment]
então eu preciso apenas me atentar a ter somente o arquivo certo modificado na hora de subir ?

**Comment by fdaciuk** [comment]
@brunotortelli exatamente ;)
