### ISSUE TITLE
Curso e Vida real - orientação

### ISSUE THREAD

**Issue by ricardomirannda** [da2k/curso-javascript-ninja#3761]
Olá Daciuk, tudo bem?
Estou num dilema, eu sou um cara que veio de interface e que está migrando para código, ainda preciso desenvolver bastante minha lógica, pois em são situações do dia a dia, eu travo diante do problema e não sei como resolvê-los. Estou adorando o curso, mas por outro não sei bem como colocar em prática, pela dificuldade natural também por ter que trabalhar com Angular no trabalho atual, ou seja, duas coisas pra aprender, Javascript e as particularidades do Angular. 

Eu queria uma orientação no sentido de como mesclar o que eu estou aprendendo no curso e o que eu passo no trabalho, porque os exercícios não representam bem os problemas que passo na vida real. 

Você recomenda fazer o curso todo, ficando na teoria e prática do curso? 
Como eu posso tentar avançar com situações que possam me deixar mais confortável no trabalho? 

Ou nenhuma dessas opções está certa e o aprendizado é realmente demorado e eu preciso respeitar o tempo? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Vamos lá!

O aprendizado - de fato - de algo só vem com muita prática. Quanto mais você pratica, mais fácil fica de entender como as coisas funcionam, e como resolver problemas com aquela linguagem.

Com JS não é diferente. Então eu recomendo sim, você continuar fazendo o curso, praticando com os desafios, e tentando fazer suas próprias aplicações em JS, para praticar.

O segredo **é a prática**.

Quando você começar a ficar mais confortável com as features apresentadas no curso, você vai perceber o quanto de JS puro você consegue usar no angular pra deixar o código mais legível, mais previsível, e para resolver problemas que, muitas vezes, somente com o que o angular disponibiliza não é suficiente :)

Você tocou no ponto certo: o tempo. O tempo que você se dedica não apenas a estudar, mas a praticar, é que vai fazer toda a diferença pra você. E aprendizado não vem de uma hora pra outra. 

Siga praticando, e entre em contato sempre que tiver dúvidas, estou à disposição pra te ajudar a alcançar o nível Ninja :D

**Comment by ricardomirannda** [comment]
Daciuck, 
Suas palavras acalmam meu coração e a minha mente, pois eu tento acompanhar pessoas que já trabalham a mais tempo com programação no trabalho, como não consigo, acabo me frustrando. 

Estou fazendo da seguinte da forma: 

1. Assisto as aulas 
2. Faço os exercícios 
3. Passo para o próximo assunto 

Atualmente estou assistindo as aulas, fazendo os exercícios e em seguida partindo para o próximo assunto. Como o curso é grande, estou tentando adiantar pra terminá-lo o mais rápido possível, com o objetivo de estar mais preparado no trabalho.  Essa é a forma correta?

Vamos dizer que assisti a aula sobre Funções, por quanto tempo devo continuar estudando Funções? Por quanto tempo devo ficar praticando, para em seguida partir para o próximo assunto?

Estou querendo encontrar a melhorar maneira para conciliar, mas também não quero ficar muito tempo preso em apenas um assunto.  

Queria uma orientação sua nesse sentido.

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Você pode seguir fazendo dessa forma sim! Só adicione um ponto, antes de prosseguir para a próxima aula: se ficou qualquer dúvida sobre qualquer coisa que foi falado na aula, abra uma issue aqui e pergunte, para que não fique dúvidas!

Quando estiver tudo claro, você passa para o próximo tópico =)

É claro que é difícil você lembrar de tudo o que foi falado quando chegar no final do curso, algumas coisas podem se perder mesmo. 

Mas com a prática e estudos constantes, você vai lembrar das partes mais importantes e vai conseguir seguir em frente. E também, como o acesso ao curso é vitalício, você poderá acessar sempre que precisar reasistir alguma aula, para relembrar algum tópico =)

Enfim, é isso. Não tem segredo: é praticar e estudar sempre. E conte comigo para o que precisar =)

**Comment by ricardomirannda** [comment]
Oi Daciuk,
Muito, muito obrigado pela sua atenção, suas palavras me dão confiança e segurança para continuar e ter certeza que vou alcançar o nível ninja !!

**Comment by fdaciuk** [comment]
Show de bola @ricardomirannda! Qualquer coisa, conte comigo =)
