### ISSUE TITLE
challenge-28

### ISSUE THREAD

**Issue by saintsfall** [da2k/curso-javascript-ninja#3769]
Fala Fernando,
Estou fazendo o desafio 28 e algo não fez sentido pra mim.

Inicialmente eu não estou usando a lib pq na minha opinião, e eu tenho certeza de que estou errado pq sou um iniciante, não me pareceu interessante criar uma referencia a um arquivo externo cuja lib usamos apenas pra criar document.querySelector e addEventListener.

Dessa maneira meu challenge-28.js não tem referencia a lib.

Minha duvida é a seguinte, quando vamos fazer o try/catch ele teoricamente deveria retornar null e com isso fazer o update da div que armazena os status.

Porém o try/catch só é disparado dentro da função fillCEPFields() que só é disparada se o status estiver OK, e para o status estar OK o ajax.status precisa ser  === 200.

O fato é que quando eu preencho qualquer coisa errada lá meu ajax.status retorna 404  e ele nunca vai cair no try/catch.

Eu vi e revi a revisão mas não consegui entender pq no seu código quando se coloca informação errada ainda assim o ajax.status continua retornando 200, ja que ele cai na sua fillCEPFields e vai para o catch.

[challenge-28.zip](https://github.com/da2k/curso-javascript-ninja/files/1775404/challenge-28.zip)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @saintsfall! Seu problema provavelmente pode estar acontecendo por conta da API do ViaCEP que mudou =)

Dá uma olhada [nessa issue](https://github.com/da2k/curso-javascript-ninja/issues/2048) que eu acho que vai resolver seu problema =)

Qualquer coisa me avise =)

**Comment by fdaciuk** [comment]
Oi @saintsfall! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
