### ISSUE TITLE
Dúvida no desafio challenge 11.js

### ISSUE THREAD

**Issue by RafaelMouraFrontend** [da2k/curso-javascript-ninja#3773]
Fiz da seguinte forma a última parte do desafio, com o loop while, ao inves do for, como você fez no exemplo, mas não entendi por que ele não funcionou, poderia me dar uma ajudinha...

```
console.log( 'Pares de 0 a 20:' );
  counter = 0;
  number =[];
  while ( counter < 20) {
    if (counter % 2 === 0) {
      continue;
    }
    number.push(counter++);
  }
  console.log(number);
})();
```

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @RafaelMouraFrontend! O problema é que a variável `counter` nunca é incrementada quando cai no `if (counter % 2 === 0)`.

Nesse caso, como vc usou o `continue`, o loop recomeça com o counter no mesmo valor que caiu no `if`, e fica assim infinitamente =)

**Comment by fdaciuk** [comment]
Oi @RafaelMouraFrontend! Ainda ficou alguma dúvida sobre isso? Vou fechar a issue, mas se você ainda tiver dúvidas, me avise que reabrimos, ok? =)
