### ISSUE TITLE
[challenge-02] Dúvida sobre return null e false

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#378]
Boa tarde @fdaciuk !

Estou refazendo meus exercícios afim de melhorá-los, :) 

Tenho uma grande dúvida com relação a: <code>return null e false</code>

Neste exemplo:

![retorno null](https://cloud.githubusercontent.com/assets/13303320/10350832/a2af2c66-6d1c-11e5-8fd4-026d112966c4.png)

Pelo que eu entendi, se nenhuma das condições acima forem atendidas, retorne `null`, certo! Mas o return null ou false ele quebra alguma ação?  Ou dá um salto feito o return e break? 

Se puder me dar alguns detalhes sobre o impacto dos retornos  <code> null, false</code>

Grato ;) :+1:

**Comment by fdaciuk** [comment]
Fala @DaniloAgostinho! Na verdade, o `false` é um valor do tipo **booleano**, que significa que o valor é "diferente de verdadeiro". E o `null` significa "sem valor", "valor nulo".

Os dois valores são de tipos primitivos da linguagem. Eles não causam nenhum efeito colateral, nem saltos, nem nada disso, são apenas valores.

Diferente da palavra chave `return`, que pára toda a execução de uma função quando o interpretador do JS chega nela :)

Ficou claro?

**Comment by DaniloAgostinho** [comment]
@fdaciuk bem claro! Eras isso! ;)
