### ISSUE TITLE
Limpar o console do node.js

### ISSUE THREAD

**Issue by filipeltsilva** [da2k/curso-javascript-ninja#38]
Olá, Fernando!

Qual atalho você utilizou pra limpar o console do node.js, como foi feito na aula de operadores de igualdade e relacionais?

**Comment by fdaciuk** [comment]
Olá @filipeltsilva! É só pressionar Ctrl + L! :)

**Comment by educavalcante** [comment]
Oi estou iniciando, na aula de funções vc "zerou" o nodejs, tipo limpando a memoria qual o atalho?

**Comment by ffabiorj** [comment]
é só vc sair do node e entrar de novo. Não tem atalho.

**Comment by fdaciuk** [comment]
Fala @educavalcante! É como o @ffabiorj disse: para "zerar" a memória você precisa sair do **REPL**, pressionando duas vezes Ctrl + C, ou uma vez Ctrl + D.

Para limpar a tela, só pressionar Ctrl + L.

O Ctrl + L pode depender do terminal que você está utilizando, mas o Ctrl + C normalmente é o comando que funciona em qualquer um =)

**Comment by educavalcante** [comment]
grato, 
Depois de criar uma fn tem como alterar?
falo isso neste nivel que estou do primeiro desafio, vc chegou a mostrar isso?
criei uma função divisão, porem não adicionei o return, tem como alterar esta mesma função? acho que sim, mas não sei se mostrou nesse video;

**Comment by fdaciuk** [comment]
@educavalcante se você estiver usando o REPL do Node, não dá pra alterar, mas você pode sobrescrever. Só escrever a função novamente, que a última implementação sobrescreve a anterior ;)

**Comment by educavalcante** [comment]
prof o "REPL"
é o prompt? descupa mas são muitos detalhes.... ( é essa tela preta? baixei o node.js primeira vez esses dias) REPL é uma sigla? descupa sou iniciante mirim ainda rs
![image](https://cloud.githubusercontent.com/assets/18662007/14874098/4f39bfae-0cd3-11e6-8e04-48b8348d6152.png)

**Comment by fdaciuk** [comment]
Isso mesmo @educavalcante xD
Desculpe não deixar claro =)

O REPL é quando você digita "node" no terminal, e ele entra nessa tela preta, com o `>` pra você começar a digitar os comandos :D

E sim, é uma sigla. Se quiser saber mais, pode [ver aqui](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) :smile:

**Comment by elizeusousa** [comment]
> Fala @educavalcante! É como o @ffabiorj disse: para "zerar" a memória você precisa sair do **REPL**, pressionando duas vezes Ctrl + C, ou uma vez Ctrl + D.
> 
> Para limpar a tela, só pressionar Ctrl + L.
> 
> O Ctrl + L pode depender do terminal que você está utilizando, mas o Ctrl + C normalmente é o comando que funciona em qualquer um =)

Boa; Ctrl + L no console Node.JS Resolveu!

**Comment by pedro-vaf** [comment]
console.clear() também serve para limpar o terminal no node.js
