### ISSUE TITLE
algoritmo da questao

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-javascript-ninja#3834]
De alguma forma essa logica está errada? 

var regexDate = /\d\d de (junho|julho) de \d\d\d\d'/g,$1 ;
newDate = regexDate.replace(/de/g,'/').match(getMonthNumber($1))
console.log(newDate)

so consigo usar minhas marcações ($1) dentro da mesma linha de cogido em q declarei  ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Na verdade sim =)

A variável `regexDate` está recebendo o valor da regex `/\d\d de (junho|julho) de \d\d\d\d'/g`. O que está vindo após isso - `,$1` é outra coisa. Essa sintaxe não é válida.

Quando você precisa passar argumentos para uma função, você deve usar a vírgula apenas **dentro dos parênteses**. A vírgula ali dentro é usada para separar os argumentos que a função está recebendo.

No caso, você deveria passar a variável `regexDate` como primeiro argumento do método `match`, e o `$1` como string - entre aspas simples ou duplas - após a vírgula, no segundo argumento.

Acredito que o que você tentou fazer seria atribuir a uma variável, de uma única vez, os dois argumentos para a função, mas dessa forma que você escreveu, essa sintaxe não é válida =)

**Comment by TMiranda7** [comment]
ah cara , entendi , valeu , foi uma duvida pra esclarecimento de como funciona por debaixo dos panos :P

**Comment by fdaciuk** [comment]
Legal @TMiranda7! Que bom que ficou claro =)
Qualquer dúvida, pode perguntar =)
