### ISSUE TITLE
Dúvida sobre essa questão

### ISSUE THREAD

**Issue by FelipeCampos-sp** [da2k/curso-javascript-ninja#3847]
Um hotel cobra R$ 80,00 a diária e mais uma taxa de serviços conforme tabela abaixo. Monte uma interface onde o usuário possa calcular sua despesa total informando quantos dias ficou hospedado.

R$ 5,50 por diária, se o número de diárias for maior que 15;
R$ 6,00 por diária, se o número de diárias for igual a 15;
R$ 8,00 por diária, se o número de diárias for menor que 15.
Quantos dias ficou hospedado em nosso hotel? 

TOTAL (inclui taxas de serviços):

  <article class="maior panel panel-primary">
    <h2><span class="glyphicon glyphicon-bed"></span> Diárias do hotel</h2>
    <p>Um hotel cobra R$ 80,00 a diária e mais uma taxa de serviços conforme tabela abaixo. Monte uma interface onde o usuário possa calcular sua despesa total informando quantos dias ficou hospedado.</p>
    <ul>
      <li>R$ 5,50 por diária, se o número de diárias for maior que 15;</li>
      <li>R$ 6,00 por diária, se o número de diárias for igual a 15;</li>
      <li>R$ 8,00 por diária, se o número de diárias for menor que 15.</li>
    </ul>
    <div class="panel-body">
      <p class="form-inline">
        <label for="dias">Quantos dias ficou hospedado em nosso hotel?</label>
        <input type="number" id="dias" class="form-control">
      </p>
      <p>
        <button id="calcula-dias" class="btn btn-primary">CALCULAR</button>
        <button id="limpa-hotel" class="btn btn-danger resetar">LIMPAR CAMPOS</button>
      </p>
      <p class="form-inline">
        <label for="consumo">TOTAL (inclui taxas de serviços):</label>
        <input class="form-control" type="text" id="resposta-hospedagem" disabled>
      </p>
    </div>
  </article>

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @FelipeCampos-sp! Você colocou a questão, mas qual seria a dúvida? xD

**Comment by fdaciuk** [comment]
Oi @FelipeCampos-sp! Vou fechar a issue, mas se ainda tiver dúvida com relação a esse assunto, só avisar que a gente reabre, ok? =)
