### ISSUE TITLE
Como clonar o repositorio do Curso ?

### ISSUE THREAD

**Issue by danielldante** [da2k/curso-javascript-ninja#395]
O repositório do curso é apenas para consulta, ou pode ser clonado em um projeto local ? Preciso configurar a chave SSH e tudo mais ?

**Comment by ffabiorj** [comment]
vc já configurou o git na sua máquina?

**Comment by danielldante** [comment]
Tenho o Git na máquina sim. Porém nunca configurei um repositório do zero. Sei até fazer o procedimento para configurar a chave SSH no gitbash, add o projeto. Fazer commit e o push. Mas, configurar para poder tudo funcionar do zero, nunca fiz. Estou com o Git aberto, como faço ? :)

**Comment by ffabiorj** [comment]
vc já começou assistir os videos, lá ele ensina.

para clonar vc faz assim   git clone git@github.com:da2k/curso-javascript-ninja.git
depois 
git remote add upstream git@github.com:da2k/curso-javascript-ninja.git

esses comandos vao sincronizar com o repositorio do projeto.

git checkout master
git fetch upstream
git rebase upstream/master

depois vc criar branchs..

Ver os video que ele ensina.

V

**Comment by danielldante** [comment]
estou nas aulas da primeira semana. Essa fase de configurar o Git só fala sobre as issues e pull requests. Mas valeuzãooo!

**Comment by ffabiorj** [comment]
Tranquilo.

da uma olhada aqui. http://rogerdudler.github.io/git-guide/index.pt_BR.html

**Comment by fdaciuk** [comment]
Olá @danielldante! Como o @ffabiorj comentou, nos vídeos das primeiras aulas tem todos os passos, desde clonar o repositório até enviar um pull request :)

Mas se tiver alguma dúvida, pode colar aqui xD

Obrigado pela ajuda @ffabiorj :+1:

**Comment by ffabiorj** [comment]
Tranquilo @fdaciuk .
