### ISSUE TITLE
Dúvida no Challenge 33

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-javascript-ninja#3951]
bom dia da2k
vocês poderia me dar um help no ultimo exercício não estou conseguindo pensar em como capturar a placa para enviar no ajax poderia ver o meu código https://github.com/angelilton/projectcar/tree/challenge-32

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! Você deve seguir o padrão natural de criação de um formulário: adicionar `id` e `name` nos campos. Fazendo isso, no evento de `submit` do `form`, você consegue pegar os campos pra fazer o request e enviar a placa e todos os outros dados :)

**Comment by fdaciuk** [comment]
Oi @angelilton! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
