### ISSUE TITLE
JSON.parse e JSON.

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-javascript-ninja#402]
@fdaciuk to tendo problemas no video da aula mostra que o stringify transforma um objeto em string e o parse a string em objeto, eu fiz a conversão de obj pra string e logo depois converti de volta usando parse e fiz um for pra exibir, ta dando erro na linha do parse.

--------------------------mensagem no console
[object Object],[object Object]
 ^
SyntaxError: Unexpected token o
    at Object.parse (native)
    at D:\curso-javascript\curso-javascript-ninja\challenge-12\challenge-12.js:71:6
    at Object.<anonymous> (D:\curso-javascript\curso-javascript-ninja\challenge-12\challenge-12.js:110:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
-------------------------fim da mensagem do console

>Converta os objetos que ficaram em `books` para strings.
*/
 JSON.stringify(books);
console.log( '\nLivros em formato string:' );
  /*
Mostre os livros nesse formato no console:
*/
console.log(books);
/*
Converta os livros novamente para objeto.
*/
JSON.parse(books);
  console.log( '\nAgora os livros são objetos novamente:' );
/*
Mostre no console todas as propriedades e valores de todos os livros,
no formato abaixo:
    "[PROPRIEDADE]: [VALOR]"
*/
for(i = 0; i <= books.length; i++){
  console.log('name: ' + books[i].name);
  console.log('pages: ' + books[i].pages);
};

**Comment by fdaciuk** [comment]
@brunotortelli, me mostra o código de como você tá fazendo :)

**Comment by brunotortelli** [comment]
>Converta os objetos que ficaram em books para strings.
/
JSON.stringify(books);
console.log( '\nLivros em formato string:' );
/
Mostre os livros nesse formato no console:
/
console.log(books);
/
Converta os livros novamente para objeto.
/
JSON.parse(books);
console.log( '\nAgora os livros são objetos novamente:' );
/
Mostre no console todas as propriedades e valores de todos os livros,
no formato abaixo:
"[PROPRIEDADE]: [VALOR]"
*/
for(i = 0; i <= books.length; i++){
console.log('name: ' + books[i].name);
console.log('pages: ' + books[i].pages);
};

**Comment by brunotortelli** [comment]
@fdaciuk

**Comment by fdaciuk** [comment]
@bruno, deixa eu ver seu código todo.. consegue mandar pr? Ae eu vejo direto lá :)
Só manda o PR (incompleto mesmo) e me marca lá, marcando também essa issue aqui (#402) que eu vou saber do que se trata :)

**Comment by fdaciuk** [comment]
@brunotortelli, deixa eu ver seu código todo.. consegue mandar pr? Ae eu vejo direto lá :)
Só manda o PR (incompleto mesmo) e me marca lá, marcando também essa issue aqui (#402) que eu vou saber do que se trata :)
