### ISSUE TITLE
Dúvida no Challenge 12

### ISSUE THREAD

**Issue by Diogo-Queiroz** [da2k/curso-javascript-ninja#4061]
Olá Professor, estou com dúvida no desafio. Eu sempre tento realizar sem assistir a revisão para não comprometer meu desafio de superar meus conhecimentos, mas porém todavia entretanto. Uma parte do desafio para converter os objetos do array "books" em string e mostrar no console nesse formato.
Minha melhor alternativa para resolver essa questão seria converter e passar o resultado para uma variável, uma vez que o método `JSON.stringify()` não gera efeito no próprio objeto, correto? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Diogo-Queiroz! É exatamente isso =)
Os métodos do objeto `JSON` não modificam o objeto, eles sempre retornam um novo valor, que, se necessário o seu uso futuro, é necessário guardar o resultado em uma variável mesmo =)

**Comment by Diogo-Queiroz** [comment]
Opa, professor!! Consegui me resolver! Hehehe!! Usei o próprio `books`. Agora deu certo.
Agora estou com outra dúvida, nas últimas perguntas, estou usando o `join()` em todas para ficar melhor de visualizar o resultado no console, tem problema não né?

**Comment by fdaciuk** [comment]
Se funcionou, segue em frente =)
Depois, se a solução que eu mostrar ficar muito diferente da sua, e você ficar com alguma dúvida, só abrir issue aqui =)
O importante é fazer funcionar, e usar apenas o que foi visto em aula até então =)

**Comment by Diogo-Queiroz** [comment]
Fantástico professor @fdaciuk, o solução ficou igualzinha. Só o ultimo exercício que eu interpretei errado como resolver na hora de ordenar o array, usei o `join()` também! Já pode fechar a issue aqui, me respondeu a dúvida já! Obrigado!

**Comment by fdaciuk** [comment]
Show de bola! Qualquer dúvida, só avisar =)
