### ISSUE TITLE
challenge-02

### ISSUE THREAD

**Issue by carlacfw** [da2k/curso-javascript-ninja#4067]
Oi Fernando.
Eu acabei de terminar o challenge 02 e no ultimo exercicio, pede para chamarmos a funcao e testar com todas as posibilidades de argumentos.
porem eu nao consigo retornar 'null'. Como eu conseguiria retornar null?
tentei desse jeito, mas os retornos fazem sentido, mas eu queria retornar null tambem.
Ou eh totalmente desnecessario?
Grata desde ja!!

```
tresArg(1, 2, 3, 4, 5)
1
tresArg('argumento')
"argumento"
tresArg('argumento', 5)
"argumento5"
```

@fdaciuk

**Comment by fsoaresjunior** [comment]
Bom dia, você nunca conseguirá retornar null, por quê? Porque as verificações do if não permitem.
Por mais que você passe diferentes valores, eles sempre cairão em uma das verificações do if, impedindo que chegue no else e retorne null.

**Comment by fdaciuk** [comment]
Oi @carlacfw! Desculpe, por algum motivo eu não recebi notificação da sua dúvida :thinking: 
Mas enfim, é o que o @fsoaresjunior comentou mesmo: nesse exemplo, o `null` nunca será exibido =)

Alguns desses primeiros desafios são bastante "inúteis", por assim dizer, para se usar no dia a dia. A ideia deles é para que você possa praticar mesmo, entender como as coisas funcionam na linguagem, para que você fique cada vez mais próxima do uso dessas ferramentas =)

Mais uma vez, mil desculpas por não ter te respondido antes! Vou te pedir que, se por acaso eu não responder em até 2 dias, você faça um novo comentário na issue, me marcando (com `@fdaciuk`). Pode ter sido algum bug momentâneo no GitHub, não sei te dizer porquê não recebi essa notificação =)

**Comment by fdaciuk** [comment]
Oi @carlacfw! Vou fechar a issue, mas se você ainda tiver problemas ou qualquer outra dúvida, me avise, ok? =)
