### ISSUE TITLE
Remover pastas antigas de branchs mais recentes

### ISSUE THREAD

**Issue by filipeltsilva** [da2k/curso-javascript-ninja#41]
Posso ficar a vontade para remover pastas dos desafios passados de branchs mais recentes para fim de organização dos meus repositórios?

Como posso adicionar tags como a "question" em issues que eu venha a criar?

**Comment by fdaciuk** [comment]
Olá @filipeltsilva! Acho que seria legal manter, pois na hora do pull request vai aparecer que vários arquivos foram deletados, levando em consideração que teremos muitos exercícios no futuro.
Mas se estiver ruim para você se organizar, pode apagar sim :)

Sobre as tags, infelizmente o Github só libera essa feature para o admin do repositório =/
Mas eu vou taggeando, sem problemas :)

**Comment by filipeltsilva** [comment]
Tudo bem!

Vou seguir o conselho de manter os arquivos.
