### ISSUE TITLE
[Vídeos não carregam]

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#411]
Boa noite @fdaciuk,

Os vídeos não estão aparecendo lá no vimeo, já inseri a senha para assitir as aulas e nada, Há algum problema?

Grato! ;)

**Comment by fdaciuk** [comment]
Fala @DaniloAgostinho! Mandei um e-mail no domingo falando sobre isso. Chegou a receber? É um problema no Vimeo sim :disappointed: 

Mas dá pra assistir ainda, usando as instruções que passei no e-mail. Se não chegou pra você, me avisa que eu reenvio, ok? :)

Se usa Gmail, dá uma olhada na aba Promoções, ou em SPAM :)

**Comment by DaniloAgostinho** [comment]
@fdaciuk  não chegou não. Aguardando o reenvio. ;)

**Comment by DaniloAgostinho** [comment]
@fdaciuk 

Encontrei o e-mail, já recebi! vlw!

**Comment by fdaciuk** [comment]
o/
