### ISSUE TITLE
Objects

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#420]
@fdaciuk  qual a diferença de object e Object?

**Comment by fdaciuk** [comment]
@LucasCMota `Object` (com `O` maiúsculo) é um construtor da linguagem, como `Array`, `String`, `Number`, `Boolean`, etc :)

Esses construtores são basicamentes os **tipos** de dados que temos em Javascript.

Vimos uma introdução sobre isso na aula 10. Usando o `new` antes desses construtores, você cria um novo objeto com o tipo específico:

```js
var obj = new Object();
var obj2= {};
```

As duas linhas acima são equivalentes; os dois criam um novo objeto vazio. O `{}` é um `atalho` para `new Object()`, e seu uso é preferível. Mesmo esquema no caso de arrays:

```js
var arr = new Array();
var arr2 = [];
```

As duas linhas acima também são equivalentes. Usar os atalhos normalmente são mais performáticos e menos suscetíveis a problemas que criar novos objetos com `new`, por isso são preferíveis.

Para strings, números, boolean, etc., a ideia é a mesma:

```js
var str = new String('Lucas');
var str = 'Lucas';

var num = new Number(10);
var num2 = 10;

var bool = new Boolean(true);
var bool2 = true;
```

Para todos os casos, sempre que você vai usar um tipo de dado em Javascript, você tem a opção de fazer usando o construtor, ou o formato `literal`.

E `object`, com `o` minúsculo, não é nada em JS. Pode ser usado sem problemas como nome de variável, função, ou argumento de função :)
