### ISSUE TITLE
[Ajuda] Challenge 02

### ISSUE THREAD

**Issue by tiro-dev** [da2k/curso-javascript-ninja#4207]
Preciso de ajuda, por favor.

Após o comando **git push origin challenge-02** ocorre o erro abaixo. Sabe o que pode ser?

**remote: Permission to da2k/curso-javascript-ninja.git denied to tiagorodrigues-swd.
fatal: unable to access 'https://github.com/da2k/curso-javascript-ninja.git/': The requested URL returned error: 403**

@fdaciuk

**Comment by danilorb** [comment]
@tiagorodrigues-swd você precisa fazer o fork do projeto para seu GitHub e realizar o commit no seu fork. Depois basta dar o pull request para o repositório do curso.

Qualquer dúvida, segue o link abaixo para te ajudar.

https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/

**Comment by fdaciuk** [comment]
Obrigado @danilorb =)

Oi @tiagorodrigues-swd! Como o Danilo comentou, você precisa fazer o fork do repositório principal, e fazer o clone na sua máquina do *seu repositório*, não do repositório em `/da2k` :)

Mas assim: não é obrigatório enviar os desafios aqui no GitHub, ok? Se você tiver dificuldades em usar o Git, fique à vontade para não enviar. Só tente fazer na sua máquina mesmo, pois é praticando que o aprendizado vem :D 

E se quiser enviar também, para praticar e entender como funciona o git e GitHub, também fique à vontade =)

Conte comigo se tiver qualquer dúvida :)

**Comment by fdaciuk** [comment]
Oi @tiro-dev! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
