### ISSUE TITLE
challenge 05

### ISSUE THREAD

**Issue by juliomig99** [da2k/curso-javascript-ninja#4210]
Escreva aqui sua dúvida

@fdaciuk
Bom dia Fernando,
Na aula JS no browser você comenta sobre servidor Python ou Apache e que tem um arquivo ensinando como instalar o servidor. Eu utilizo o apache no eclipse/java. Como faço pra utilizar com JS e Atom?
Poderia informar o seu e-mail de contato?

Abraço,

Júlio Sá

**Comment by fdaciuk** [comment]
Oi @juliomig99! O ideal seria você fazer a configuração do servidor na sua máquina, não dependendo do editor :)

O mais fácil para o seu caso, se você ainda não tem nenhum servidor rodando na sua máquina, seria:
- ou instalar o python, e usar o `SimpleHTTPServer`, como eu mostrei na aula;
- ou instalar, via NPM, qualquer ferramenta que você possa utilizar como um servidor estático, apenas para conseguir acessar o `index.html` do desafio que você está tentando via `localhost:<PORTA>` no seu navegador :)

Você pode usar, por exemplo, o [serve](https://www.npmjs.com/package/serve) =)

Você só precisa instalar ele de forma global com o NPM:

```
npm i -g serve
```

E então, pelo terminal, no diretório onde está sua index.html, rodar o comando:

```
serve .
```

Pronto! Agora você pode acessar no seu browser `localhost:5000` (ou a porta que for exibida no seu terminal) que você deve ver o conteúdo da sua index.html :)

**Comment by juliomig99** [comment]
Boa tarde @fdaciuk , 
Obrigado pelo retorno. Sempre prestativo e atencioso com seus alunos. Poderia indicar literatura e/ou cursos a respeito do assunto e também HTML e CSS. Creio que está faltando conhecimento básico.
Na parte de Web Design o que recomenda?
Obrigado, abraço.

**Comment by juliomig99** [comment]
@fdaciuk,
Poderia dar um help, sensação de não conseguir prosseguir nas aulas é horrível.

Entrei no site https://www.python.org/downloads/  e baixei e instalei a versão Download Python 3.6.5 for win10.
Onde eu rodo o comando python -m SimpleHTTPServer 9001 pra startar o servidor?
Depois é só executar no browser localhost9001?
Como faço pra indicar o local onde está o index.html para que o browser enxergue?

Att,
Júlio Sá

**Comment by juliomig99** [comment]
@fdaciuk,
Quando você cria o arquivo com o comando touch index.html --> você está utilizando qual aplicativo?

**Comment by fdaciuk** [comment]
Oi @juliomig99!

> Poderia indicar literatura e/ou cursos a respeito do assunto e também HTML e CSS. Creio que está faltando conhecimento básico. Na parte de Web Design o que recomenda?

Quais dificuldades você está sentindo? Se for sobre HTML e CSS, tem o curso da Fernanda Bernardo, que é bem legal pra quem está iniciando:
https://www.udemy.com/frontend-basico-do-zero-a-uma-pagina-com-html-e-css/

> Entrei no site https://www.python.org/downloads/ e baixei e instalei a versão Download Python 3.6.5 for win10. 
> Onde eu rodo o comando python -m SimpleHTTPServer 9001 pra startar o servidor?
> Depois é só executar no browser localhost9001?
> Como faço pra indicar o local onde está o index.html para que o browser enxergue?

Você precisa acessar o seu terminal! Lá você navega até o diretório do seu projeto, onde está a `index.html` que você quer visualizar, e roda o comando `python -m SimpleHTTPServer 9001`.
Ao fazer isso, é só você ir até o browser e entrar em `localhost:9001` que lá estará sendo exibida a `index.html` do diretório onde você rodou o comando no seu terminal :)

> Executei o comando no git pyserver, mas deu erro: --> bash: pyserver: command not found

O comando que eu rodo `pyserver` é uma alias no meu sistema que eu criei para que, quando eu rodar esse comando, ele execute o comando `python -m SimpleHTTPServer 9001`, então ele não vai funcionar pra você, a menos que você crie também esse mesmo alias =)

Teria só que pesquisar como criar isso no windows. Como estou usando Linux, não sei te dizer como funciona alias no windows :)

**Comment by juliomig99** [comment]
Boa tarde Fernando, @fdaciuk 
Primeiro, obrigado por seu retorno (Ponto forte do curso).
A dificuldade toda se deu por não saber "o quê e aonde" por não ter familiaridade com este assunto de "Servidor WEB Local". Com base na sua orientação não sabia do que se tratava e por onde começar. Por exemplo, o que eu tenho que instalar? O que eu devo configurar e onde? Como eu sei que funcionou? Os comandos são executados no git, no NodeJS, no prompt de comando do windows? NPM é de comer ou beber, kkk? NPM está instalado ou não no NodeJS, como faço?
Bom, a partir dessas dúvidas fui pro oráculo "google" e achei um video no youtube do SW9 Paulo Eduardo (https://youtu.be/59OG7vg4nYI) que pode ajudar outros colegas perdidos como eu neste ponto.
Feito isto, consegui executar o index.html e visualizar no console do browser as informações do main.js
Abraço e obrigado.
Júlio Sá

**Comment by juliomig99** [comment]
Fernando, @fdaciuk 
Só mais uma encheção. Quero sair do mundo windows pro Linux. Tem uma indicação de curso/literatura?
Valeu,
Júlio Sá

**Comment by fdaciuk** [comment]
Oi @juliomig99! Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
