### ISSUE TITLE
Challenge-13

### ISSUE THREAD

**Issue by pnxbill** [da2k/curso-javascript-ninja#4267]
Escreva aqui sua dúvida

Fala Daciuk, beleza?
Então cara, na aula de revisão do Challenge-13, mais precisamente na aula 82, minuto 10:35, você diz que pode se fazer o exercício de duas formas.

A primeira seria:

var map = newBrasil.map(function (item,index,array) {
    item.id++;
    item.estado += ' pertence ao Brasil!';
    return item;
});

**E você diz também que o metódo map não causa efeito colateral.**
Então, mas se você usar dessa primeira forma, o método causa efeito colateral por algum motivo.
**Se você chamar o newBrasil no console, vai notar que as propriedades dele também sofreram alteração.** 

Como estou usando o console do Firefox Developer Edition pra rodar o código, pensei que poderia ser definição do navegador, então testei com o Chrome e depois com o console do node.js, onde aconteceu a mesma coisa nos dois casos.

Queria saber se esse é o comportamento esperado do método map e você deixou de verificar o newBrasil depois, ou se foi alguma atualização do ECMAScript que fez essa mudança.

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pnxbill! Você está certíssimo! Me precipitei no que eu falei! Se fizer a modificação direto no `item`, como ele é um objeto, a referência dele se mantém, ainda que use o `map`. A única coisa que o `map` vai fazer é criar um novo array, sem mexer na referência de `newBrasil`, mas os objetos internos ao array `newBrasil`, cada um tem sua própria referência, e o `item` dentro do `map` são exatamente as mesmas referências dos objetos em `newBrasil` =)

Obrigado por reportar, vou adicionar um adendo logo após a aula explicando essa errata :)
