### ISSUE TITLE
[DÚVIDA] - challenge-06

### ISSUE THREAD

**Issue by Srubens** [da2k/curso-javascript-ninja#4281]
Na challenge-06 o exercicio com o switch, eu posso colocar o return em cada case e continuara correto ou não?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Srubens! Poderia sim! Só que aí você repetiria bastante código =)
Da forma como eu mostrei (dá uma olhada na solução do desafio), você usa o switch apenas para fazer a atualização do único valor que precisa ser modificado na frase que a função deve retornar =)

**Comment by fdaciuk** [comment]
Oi @Srubens! Ficou clara a resposta? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by Srubens** [comment]
ok pode fechar

Em sex, 3 de ago de 2018 às 15:17, Fernando Daciuk <notifications@github.com>
escreveu:
