### ISSUE TITLE
[Dúvida] Challenge-11

### ISSUE THREAD

**Issue by guilherme64** [da2k/curso-javascript-ninja#4313]
Na última questão, vimos que a resolução pode ser a seguinte:

numbers = [];
for (var i = 0; i <= 20; i++) {
  if(i % 2 === 0) {
    numbers.push(i);
  }else{
    continue;
}

Porém, enquanto resolvia, eu tentei utilizar a seguinte estrutura, mas obtive um erro de sintaxe ao utilizar o continue:

numbers = [];
for ( var i = 0; i <= 20; i++) {
  ((i % 2) === 0) ? numbers.push(i): continue;
}

Sendo assim, gostaria de saber a motivação do erro.
Desde já, obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @guilherme64! Vamos lá:

Apesar de fazer praticamente a mesma coisa, o `if` é diferente do ternário. 

As diferenças são as seguintes:
O `if` é uma **estrutura condicional**. Ele apenas gera um bloco de código que será executado se a expressão passada entre parênteses for verdadeira. Caso contrário, se houver um `else`, o bloco do `else` será executado.

Já o ternário é uma **expressão** condicional. Lembra dos exemplos que eu mostrei quando falamos sobre o ternário? Ele sempre **retorna** um valor, diferente do `if`, que só gera um bloco de código, e executa se a expressão retornar `true`.

Veja que `continue` é uma palavra-chave na linguagem JavaScript, não um valor. Então você não consegue **retornar** a palavra-chave `continue`. Ela é usada apenas dentro de um loop, para dizer ao interpretador do JS que ele deve fazer o próximo loop à partir dali.

Então é isso: o erro acontece no seu código, porque `continue` não é um valor que pode ser atribuído a uma variável, ou retornado de uma função, por exemplo. Ele é uma palavra-chave apenas =)

Aí você me pergunta: _então quando eu devo usar `if`, e quando usar ternário?_

A resposta é: você precisa do valor que vai ser retornado pela condição? Se sim, use ternário. Senão, use `if` =)

No caso do exemplo, se a expressão for `true`, você dá um `push` no array `numbers`, logo, não precisa desse valor.

E se for `false`, você dá um `continue` no loop, logo, também não precisa desse valor. Esse é um caso para se usar `if` ao invés do ternário =)

Ficou claro?

**Comment by guilherme64** [comment]
Obrigado pela explicação, Fernando =] Ficou tudo muito claro. Fecharei a Issue, ok?

**Comment by fdaciuk** [comment]
Legal @guilherme64! Qualquer dúvida, só avisar =)
