### ISSUE TITLE
Seção 1 Aula 2

### ISSUE THREAD

**Issue by rodcantanhede** [da2k/curso-javascript-ninja#4445]
Escreva aqui sua dúvida

@fdaciuk
Perdoe-me pela minha dúvida tão boba, mas se eu erro alguma coisa ao digitar no Node.JS, ele gera uns "..." 3 pontos que sou obrigado a fechar e abrir de novo. Declarar variaveis de novo. Há como resolver isso sem fechar?

**Comment by fdaciuk** [comment]
Oi @rodcantanhede! Isso acontece porque, nesse ambiente chamado de REPL, você precisa digitar comandos linha a linha, e se o interpretador do JS perceber que faltou alguma coisa no seu código, ele deixa esses `...` para dizer que falta alguma coisa, e você precisa continuar digitando, pois a expressão ainda não terminou :)

Para facilitar, você pode criar um arquivo `.js`, e colocar os comandos que você precisa todos nesse arquivo.

Depois, para executar o arquivo, seria só rodar o comando `node arquivo.js`, (trocando `arquivo.js` pelo nome do seu arquivo), que os comandos só irão rodar assim que esse comando for executado no terminal :)

Ficou claro? =)

**Comment by rodcantanhede** [comment]
Fernando, agradeço por sua resposta. Novamente, como vou saber quais comandos eu preciso colocar no arquivo? Eu só quero ir acompanhando as aulas sem precisar fechar o node. Não entendi quais comandos preciso colocar nesse arquivo.

**Comment by fdaciuk** [comment]
Oi @rodcantanhede! Vamos lá: a ideia de criar o arquivo `.js` seria não abrir o REPL do node (digitando `node` no terminal), mas ao invés disso, você cria um arquivo `.js` e coloca os comandos dentro desse arquivo, um abaixo do outro, como se estivesse escrevendo no REPL do node mesmo, saca?

Depois, para executar os comandos que estarão nesse arquivo, você pode rodar `node nome-do-arquivo.js`, que os comandos serão executados =)

Ficou claro? =)

**Comment by rodcantanhede** [comment]
Perdão, Fernando. Não ficou. Sou iniciante em JS e não sei nada de Node. Não sei exatamente quais comandos você se refere. Sei que para você parece muito claro, mas eu não sei o que colocar. Eu sei que eu abro no NodeJS e se eu errar qq coisa tenho que fechar o programa e abrir de novo. Sinceramente, estou quase desistindo.

**Comment by fdaciuk** [comment]
Oi @rodcantanhede! Não desista =)

Se não ficou claro, vou tentando usar outras abordagens para explicar até que fique, ok? :D 

Vamos lá:

O seu problema acontece quando você abre o terminal e executa o comando `node` e, ao tentar digitar qualquer coisa "linha a linha", se algo ficou faltando, você tem que começar o processo de novo, certo? Abrir o terminal, digitar `node` e digitar os códigos, correto?

Como você ainda está na aula 2, pode ser um pouco complicado de fazer. Na aula 5 você vai ver como fazer isso que eu estou falando, mas por enquanto vamos tentar outras alternativas =)

Talvez uma solução que fique mais "fácil" para você conseguir visualizar seja fazer o seguinte:

Você sabe adicionar um arquivo JavaScript no HTML, e abrir esse arquivo no browser?

**Comment by rodcantanhede** [comment]
Sim, eu já fiz algumas coisas em JS assim, inclusive usando o javascript em arquivo distinto do html. Porém, eu estou tentando quebrar a cabeça para aprender a usar a ferramenta do curso.

**Comment by fdaciuk** [comment]
Legal @rodcantanhede! Então, eu comentei sobre o browser, pq a ideia seria mais ou menos essa: você pode criar um arquivo JS, adicionar ele no HTML e escrever o código que está tentando escrever quando vc digita `node` no terminal, e ver o código rodando no browser, saca? =)

Ou ainda nem precisaria escrever em um arquivo separado: abrindo o console do browser, você pode digitar códigos assim como você faz quando digita `node` no terminal, é uma alternativa também =)

Isso resolve o seu problema, por enquanto? =)

**Comment by rodcantanhede** [comment]
Sim, resolve. Obrigado pela atenção. Espero mais a frente entender como
resolvo essa minha deficiência para não acabar ficando "manco". Obrigado,
Fernando.

Em 17 de maio de 2018 10:15, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by RenatoSiqueira** [comment]
Vou tentar responder de outra forma.
Quando cria uma (por exemplo)
```
function nome(x,y) { 
 return x+y;
} 
```
Observe que voce abre uma **{** e ao final vai fechar com a **}** certo?
Então, o node (e o navegador) sabem que quando abre uma { vai ter que ter uma } pra fechar.. entao, voce pode dar vários ENTER que ele vai colocar os `...` pra te avisar que voce ainda está dentro daquele bloco (e ainda nao fechou o que abriu).

Deu pra sacar?
Resumindo, quando tiver os `...` é porque voce abriu algo, continua dentro e ainda falta fechar.

**Comment by rodcantanhede** [comment]
Sim, RenatoSiqueira. Você me ajudou. Obrigado.
