### ISSUE TITLE
Duvidas de Refatoramento 

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-javascript-ninja#4446]
Boa tarde professor 
faz algumas horas q tento rafatorar o codigo mas nao consigo :/
sei das minhas "limitações" e tenho de perguntar se esse conceito está errado rsrsrs
pois nao aprenderei se nn conseguir compreender agora 
-------------------------------------------------------------------------------------

  function DomEvent(eventDom){
    return function (){
      Array.prototype.eventDom.apply(element,arguments);  
    }
  }
  
 DOM.prototype.map = DomEvent('map');
um exemplo;
outra duvida , tem como refatorar passando todos os items (forEach, map, filter, reduce, reduceRight, every e some) num array ? assim criaria todos de uma unica vez :)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Legal cara! Se tiver dúvidas tem que perguntar mesmo haha :D 

Vamos lá: sua ideia não está errada, só tem um ponto de problema aí: você está usando a sintaxe de ponto para acessar uma propriedade do prototype de Array. Ao fazer isso, quer dizer que você espera que aquela propriedade de fato exista no objeto para ser acessada.

No caso, a propriedade que eu estou falando é a `eventDom`. Olhe o seu código:

```js
Array.prototype.eventDom
```

Mas `eventDom` não existem no `prototype` de `Array` :)

Lembre-se que, para pegar propriedades de forma dinâmica, você precisa usar a sintaxe de colchetes:

```js
Array.prototype[eventDom]
```

Isso vai fazer com que, o valor que veio na variável `eventDom` seja usado como propriedade do objeto `Array.prototype` =)

Ajustando esse detalhe, seu código deve funcionar corretamente :)

Sobre passar um array com os métodos para criar todos de uma vez, você pode fazer um `for` (ou usar o `forEach`), e, para cada item do array vc chama a sua função `DomEvent` passando o método que você quer criar no `DOM.prototype` :)

Só lembre-se também que nós só devemos usar letras maíusculas no nome de funções quando essas forem construtores. No seu caso, `DomEvent` é apenas uma função simples, não um construtor, então é melhor chamar de `domEvent` :)

**Comment by TMiranda7** [comment]
Pow , Professor ! não existe descrição para a sensação de ver seu código rodar e conseguir entender perfeitamente o q está acontecendo  kkk , valeu mesmo , esses feed back's são grandes incentivos !

**Comment by fdaciuk** [comment]
Show de bola @TMiranda7! A prática leva a isso, prossiga! E conte comigo para o que precisar :)
