### ISSUE TITLE
Dúvida Challenge 20

### ISSUE THREAD

**Issue by Diogo-Queiroz** [da2k/curso-javascript-ninja#4463]
Opa beleza. Seguinte, estou sofrendo um pouco com o regex na `function isValidEmail()` criei o regex usando o Regex101, com a lista de e-mails válidos e inválidos para testar. Fui testar usando esses mesmos e-mails num array e passando num for o `regex.test(emails[i])` para mostrar no console. Porém, se tiver dois emails válidos um seguido do outro no for, o regex.test retorna false e não true. Vou mostrar um print exemplificando o detalhe. Até coloquei dois e-mails iguais e eles retornam `false` e `true`

| print |
|-------|
| ![capturar](https://user-images.githubusercontent.com/5124139/39579928-4c4bf2d8-4ebe-11e8-900f-58fa84c7da4e.PNG) |

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Diogo-Queiroz! Cola o seu código aqui pra eu testar, por favor (em texto)?

**Comment by Diogo-Queiroz** [comment]
Opa @fdaciuk é pra já!
```
(function () {
  'use strict';
  const regex = new RegExp('(^[\\w+.]+)(@[\\w]+)(\\.\\w{2,})(?:\\.[a-z]{2})?$', 'gm');
  const str = [
    'meu.email+categoria@gmail.com',
    'juca_malandro@bol.com.br',
    'pedrobala@hotmail.uy',
    'walter-da-silva@maraca.br',
    'sandro@culinaria.dahora',
    'rita-marica@titica.a.b',
    'agua_@evida.br.com',
    'juca_malandro@bol.com.br'
  ];

  console.log(regex);

  for (var i = 0; i < str.length; i++) {
    console.log('Teste para ' + str[i] + ' é = ' + regex.test(str[i]));
  }	
})();
```

**Comment by fdaciuk** [comment]
Fala @Diogo-Queiroz! Na verdade, o problema é a flag que você está usando.. no Regex101, você deve ter adicionado todos os e-mails, um em cada linha, e fez a regex usando a flag `g` (global) e `m` (multiline).

Nessa verificação, todos os e-mails funcionam como uma única string, então as flags são necessárias para testar.

Mas no seu código, você testa os e-mails um a um, então as flags não são necessárias (inclusive, é a flag de global que está dando problemas).

Faça um teste sem essas flags, e o seu código deve retornar o resultado esperado :)

**Comment by Diogo-Queiroz** [comment]
Show, deu super certo. Nem imaginei que o problema poderia ser com a flag global, achei que pudesse ser a multiline. Muito obrigado @fdaciuk.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
