### ISSUE TITLE
Pull-Request

### ISSUE THREAD

**Issue by Daerun** [da2k/curso-javascript-ninja#4479]
Bom dia mestre.
Não consigo enviar o "pull".
Seguindo o video, ao clicar no nome do repositório, ele me leva para a lista de "desafios", mas não mostra a dita linha com o que eu alterei.
Teria alguma nova instrução???

Desde já, agradeço.

![js-ninja-pull-none](https://user-images.githubusercontent.com/18708752/39629983-51539f12-4f84-11e8-9187-01e8aee811df.JPG)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Daerun! O GitHub fez alguns updates na interface, então tem algumas coisas diferentes :)

Mas você pode acessar a página do seu repositório (https://github.com/Daerun/curso-javascript-ninja), clicar ali no Select de "Branch" e escolher a branch do desafio que você quer enviar o Pull Request.

Ao fazer isso, você pode clicar no link "Pull Request" que vai aparecer, que o efeito é o mesmo. Dá uma olhada na imagem:

![selection_061](https://user-images.githubusercontent.com/487669/39648712-8bd40f16-4fb9-11e8-8e7b-506910c56bfd.png)

=)

**Comment by Daerun** [comment]
Blz chefe!
Fiz como disse... Assim... Espero que tenha dado certo. 
Como vou saber se funcionou? 

[]'s

@fdaciuk

**Comment by fdaciuk** [comment]
Legal! Pra conferir, só olhar na lista de Pull Requests aqui do repositório. O seu deve ser o primeiro da lista:
https://github.com/da2k/curso-javascript-ninja/pulls

=)

**Comment by Daerun** [comment]
Yessss!!!

_Thx bdy!!!
Waiting for your feedback._

@fdaciuk

**Comment by fdaciuk** [comment]
Legal! Pode seguir com o curso! A solução desse desafio você vai encontrar no início da próxima aula, assim como as soluções para todos os desafios, sempre no início da próxima aula =)
Se tiver dúvidas, só perguntar que eu te ajudo =)
