### ISSUE TITLE
[Dúvida] - Eventos e funções

### ISSUE THREAD

**Issue by joeyclapton** [da2k/curso-javascript-ninja#4514]
@fdaciuk

Boa noite. Por que quando chamamos uma função ao adicionar eventos não se faz o uso dos () ?

Exemplo:
`$start.addEventListener( 'click', startTimer, false);`

**Comment by fdaciuk** [comment]
Oi @joeyclapton! Precisamos fazer dessa forma pelo seguinte:
Quando você executa uma função - usando o operador `()` - o código que estiver dentro da função é executado, e a função retorna o seu valor (se houver `return` na função).

Quando você passa uma função para um evento, você não quer que ela seja executada no momento em que você está criando o evento, mas sim quando o **evento é disparado**, correto?

Por isso você passa somente a referência da função, sem executar! Pois a função vai ser executada apenas no momento em que o evento for disparado =)

Se você executar a função ao passar ela para um evento, o que vai ser passado ali vai ser o retorno da função (se houver). E como um listener de evento sempre espera uma função, você não vai ter o comportamento esperado =)

Ficou claro? =)

**Comment by stefannibrasil** [comment]
Legal, também estava com essa dúvida e já ia abrir um Issue :P

**Comment by fdaciuk** [comment]
Oi @joeyclapton e @stefannibrasil! Vou fechar a issue, mas se ainda tiver qualquer problema, me avise que eu reabro, ok? =)
