### ISSUE TITLE
For Each pode ser substituto pelo Map

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#4557]
Daciuk nesse ele está usando o For Each, eu poderia utilizar o map em vez de usar o For Each ?

![script](https://user-images.githubusercontent.com/3936016/39876740-58971504-544a-11e8-86f4-25a79e03b48c.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @grodrigues! Para esse exemplo, os dois métodos teriam o mesmo efeito, mas não seria "correto" usar o map. Nesse caso, o melhor seria o `forEach` mesmo.

E o grande ponto é: para saber qual o melhor método usar, é importante entender o que cada método **retorna**. É isso que vai te dizer qual método de array você deve usar, pois todos eles vão iterar o array e fazer alguma coisa específica =)

Para saber mais, dá uma lida nessa explicação que eu [dei aqui](https://twitter.com/fdaciuk/status/979039537224667136) =)

Qualquer dúvida, só avisar :D

**Comment by grodrigues** [comment]
Obrigado @fdaciuk, valeu.

**Comment by grodrigues** [comment]
Entendi ; D

**Comment by fdaciuk** [comment]
=)
