### ISSUE TITLE
Não consigo mais ver os videos...

### ISSUE THREAD

**Issue by nono21** [da2k/curso-javascript-ninja#456]
@fdaciuk Não to conseguindo ver os videos das aulas... Fica um espaço em branco onde era pra ter o video. O que fazer?

**Comment by fdaciuk** [comment]
Fala @nono21! É um problema no Vimeo :(
Mas eu mandei um e-mail mostrando como dá pra assistir (ao menos até eles resolverem pra assistir da forma como era antes).

Veja se você recebeu. Se não recebeu, me avise que te encaminho novamente, ok? :)

**Comment by nono21** [comment]
Não estou achando... Posso ter apagado sem querer...

2015-11-10 21:01 GMT-03:00 Fernando Daciuk <notifications@github.com>:

**Comment by fdaciuk** [comment]
Vou reencaminhar :)

**Comment by fdaciuk** [comment]
Mandei! Qualquer dúvida me avise! :D
