### ISSUE TITLE
[Dúvida] - Testes Browser

### ISSUE THREAD

**Issue by samuelsilvadev** [da2k/curso-javascript-ninja#4577]
Tudo bele?

Então, após ver as aulas de testes fiquei com duvidas..

Quando você fez os tests usou os modulos do node (padrão CommomJS) certo? Mas como ficaria para fazer os mesmos testes nos arquivos que desenvolvemos durante o curso? Por exemplo no appModule que é uma IIFE e só retorna a função init por exemplo?

Eu não consegui imaginar como fazer os testes, e queria cobrir todo o projeto com testes..

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samuelsilvadev! =)

Legal! Bom, nesse caso, foi apenas uma introdução aos testes. Existem vários tipos de testes que podemos fazer para cobrir ao máximo nossa aplicação, e garantir seu correto funcionamento.

Por exemplo: no caso de testar a IIFE, quando precisamos compartilhar algum código entre arquivos, nós precisamos "pendurar" esse código no objeto global (no caso do browser, o `window`).

Rodando os testes no node, você teria alguns erros ao tentar buscar essa informação de `window`, já que esse objeto não existe do lado do servidor.

Uma solução seria usar o que chamamos de UMD (Universal Module Definition). Esse tipo de sistema de módulos surgiu antes dos ES Modules (nova feature da linguagem).

A ideia dele, basicamente, é checar em qual ambiente você está, testando algumas variáveis, para exportar o que você precisa corretamente.

Um exemplo do UMD você pode ver aqui:
https://github.com/fdaciuk/ajax/blob/dev/src/ajax.js#L1-L11

Mas isso apenas para exemplificar. Como eu falei anteriormente, existem vários tipos de testes que você pode fazer na sua aplicação. Além dos testes unitários, mostrados no curso, para testar códigos específicos da aplicação, que envolvem ações do usuário na tela, você teria que fazer testes do tipo E2E.

Existem algumas ferramentas que ajudam nesse tipo de teste, como o cypress.io, por exemplo =)

Bom, esse é um assunto bastante extenso, e daria pra escrever um livro, ou um curso só pra falar sobre isso (inclusive tem um curso na Udemy do Willian Justen sobre o assunto, super recomendo) =)

O importante é você tentar começar aos poucos: separe as funções que você percebe que apenas recebem valores, e retornam alguma coisa, com base nesses valores recebidos, sem modificar nada externamente. Essas funções são fáceis de testar de forma unitária. É sempre um bom começo tentar isolá-las e ir escrevendo testes para elas =)

Depois você consegue ir evoluindo, fazendo testes de integração (quando vc precisa testar se a aplicação está conversando corretamente com alguma API, por exemplo), e então, se ainda precisar cobrir alguns cenários, pode partir para os E2E =)

Não sei se ficou claro, mas qualquer coisa comenta aqui que eu vou tentando te ajudar na medida do possível para você alcançar o que quer fazer no seu projeto =)

**Comment by samuelsilvadev** [comment]
Entendido, eu bem que imaginei que não seria um assunto tão simples rsrs, de qualquer modo eu agradeço a ajuda, vou fazer o curso do Will pra ter mais conhecimento no assunto.

**Comment by fdaciuk** [comment]
Legal @samuelsilvadev! =)
Qualquer dúvida, só avisar =)
