### ISSUE TITLE
Dúvida referente ao clone (git)

### ISSUE THREAD

**Issue by gabrielbahniuk** [da2k/curso-javascript-ninja#4663]
Oi Fernando.

eu fiz o clone do repositório do curso aqui em casa, então uso o Git Bash integrado ao VSCode e tudo roda perfeitamente: tenho localmente o que crio de códigos e faço push/PR.

O problema é: tenho outro PC (notebook) e quero clonar nele o que tenho localmente, ou seja, se tenho até o Desafio 20 pronto aqui na minha maquina, quero dar um "clone" e pegar o repositório com tudo feito até o desafio 20. Mas o que está acontecendo é que quando dou clone ele pega o repositório zerado, como se eu não tivesse editado nada.

Poderia me dizer como posso resolver isso?

Obrigado desde já.

@fdaciuk

**Comment by felipebossolani** [comment]
Gabriel

Veja se o problema não é na branch selecionada no segundo local.

Abs

**Comment by gabrielbahniuk** [comment]
Acabei de achar a [solução](https://github.com/da2k/curso-javascript-ninja/issues/696)...

Obrigado.

**Comment by fdaciuk** [comment]
Legal @gabrielbahniuk! Qualquer dúvida, pode perguntar =)
E obrigado pelo help @felipebossolani =)
