### ISSUE TITLE
[Dúvida] - Regex para validação de e-mail

### ISSUE THREAD

**Issue by eduardocintra** [da2k/curso-javascript-ninja#4689]
Bom dia,

Na aula 109 seção 18, tem uma hora que você dá um exemplo de uma regex para validar endereços de e-mail, daí você mostra no site regex101, eu fui e coloquei alguns endereços de e-mail válidos e inválidos em um array e percorri eles com forEach aplicando a regex, porém um e-mail que na teoria era para ser inválido, a regex deu match, eu até entendo o pq deu válido, é porque dentro da string completa, que é o e-mail + alguns caracteres que tornariam o e-mail inválido, tem uma cadeia de caracteres que combinam com o padrão passado para teste, mas minha pergunta é, como contornar isso?

Segue abaixo código e saída do console para entender melhor:

Código:

```javascript
var urls = [
	'fernando@email.com',
	'jos+e@hotmail.com',
	'maria@teste.com.br',
	'jose@silva@.com.br',
	'jose.com.br',
	'eduardocintra@uol.com.br.1928228281h'
];

urls.forEach(function(item) {

	var regex = /[\w+]+@\w+\.\w+(\.\w\w)?/;

	if(item.match(regex) !== null){
	
		console.log(item + ' [VÁLIDO!]');
    
	} else {
	
		console.log(item + ' [ERROOOOO!!!]');
		
    }
});
```
Resultado:

```
fernando@email.com [VÁLIDO!]
jos+e@hotmail.com [VÁLIDO!]
maria@teste.com.br [VÁLIDO!]
jose@silva@.com.br [ERROOOOO!!!]
jose.com.br [ERROOOOO!!!]
eduardocintra@uol.com.br.1928228281h [VÁLIDO!]
```

O e-mail em questão é o último!

Desde já agradeço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @eduardocintra! 
Bom, realmente o padrão do último e-mail pode sim casar, pois vc pode ter um email criado em cima de um subdomínio, que teria exatamente esse padrão que você mostrou =)

Dá pra resolver? Em partes. A ideia do exercício era tentar validar especificamente aqueles e-mails que eu passei, mas podem haver muitas outras possibilidades que talvez ficariam impossíveis de cobrir com regex.

Você consegue ir adicionando regras na regex, mas vai deixar ela cada vez mais complexa =)

Como caso de estudo, e para treinar suas habilidades em regex, você poderia chegar a uma solução, forçando para que, após o `@`, sejam permitidos apenas 2x aparecer caracteres seguidos de ponto.

Isso resolveria esse problema, mas podem haver outros padrões que você não irá conseguir cobrir =)

Onde eu quero chegar? Como exercício, faz todo o sentido brincar com isso. Mas em uma aplicação real, o importante é permitir que o usuário entre com seu e-mail (seja ele qual for), e ainda que não bata com um padrão específico, se esse for um e-mail válido, ele deverá conseguir ter acesso ao seu sistema.

E como garantir isso? Claro que é um outro assunto, mas uma solução para esse caso seria: quando o usuário finalizar o cadastro, deixe ele entrar com qualquer e-mail, sem tentar validar. Então você poderia enviar um link com uma hash para o usuário, e fazer uma validação no seu sistema: se a hash foi a que você gerou para esse usuário, então permita o cadastro dele. Enquanto isso, o cadastro fica bloqueado =)

Ficou claro? =)

**Comment by eduardocintra** [comment]
@fdaciuk 
Entendi sim, faz todo sentido o que você disse, vou a nível de estudo chegar na solução deste problema melhorando a regex, mas não faz sentido mesmo ficar se preocupando demais com isso no front-end, até porque, não tem como garantir no front-end que o usuário digitou um e-mail válido.

Muito obrigado!
