### ISSUE TITLE
[Challenge 23] Correção regex

### ISSUE THREAD

**Issue by gabrielbahniuk** [da2k/curso-javascript-ninja#4695]
Fala professor, tudo certo?

Sou iniciante ainda e posso estar falando besteira (me corrija caso sim), mas pelo que percebi no **challenge 23** o Regex que você fez na calculadora ficou assim:

`\d+[\+\-\*\/]?/g`

Então se alguém faz -8+8 na calculadora, retorna 16, o que é errado.

Pra ajeitar é só adicionar os operadores opcionais na frente, ficando dessa forma: `[\+\-\*\/]?\d+[\+\-\*\/]?/g`

Estou certo?

PS: Se falei alguma besteira, me notifique pra eu dar close na issue.

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gabrielbahniuk! Entendi seu ponto! Pode fazer sentido sim =)
Não cheguei a testar seu código, mas a ideia pode funcionar sim =)
