### ISSUE TITLE
[Dúvida] - Branches dos desafios subsequentes

### ISSUE THREAD

**Issue by felipebossolani** [da2k/curso-javascript-ninja#4722]
Pessoal,

Vocês estão abrindo as branches dos desafios 02, 03 em diantes em cima da branch anterior ou da master?

abs

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felipebossolani! O correto é abrir sempre em cima da master, para que cada branch fique apenas com o desafio daquela branch resolvido =)

**Comment by fdaciuk** [comment]
Oi @felipebossolani! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
