### ISSUE TITLE
duvidas da criação do botao

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-javascript-ninja#4726]
boa noite professor 
durante a criação do botão notei q qualquer click q eu dê , sempre envia o formulario , mermo q eu tenha algum outro evento criado , ai me gerou a duvida , se isso é devido a function criada no curso de "initEvents", na qual o parametro envaiado é o submit ,mas na Real eu nao sei 

@fdaciuk

**Comment by gabrielbahniuk** [comment]
Oi @TMiranda7 .

O evento 'click'  ocorre antes de enviar o formulário, já o evento 'submit' você pega depois do envio, portanto no evento 'click' você pode 'desativar' o redirecionamento antes do seu envio, da seguinte maneira:

$botaoEnviar.addEventListener('click', function(event) {
    event.preventDefault();
   console.log('Console log pós preventDefault!');
  }, false);

Acredito que essa tenha sido sua questão.

Se não foi peço desculpas e ignore minha resposta.

**Comment by fdaciuk** [comment]
Obrigado pela resposta @gabrielbahniuk!

Mas na verdade é o seguinte: o evento de `click` você pode colocar no botão. O evento de `submit` você coloca no formulário. Os dois eventos são diferentes pelo seguinte: o evento de clique acontece no botão, e não tem relação alguma com o form.

Já o evento de `submit`, no objeto passada para a função você tem acesso a todos os campos do formulário, podendo inclusive previnir a ação padrão de envio do form, com `e.preventDefault()`, pois o evento é disparado quando o formulário **começa** a ser submetido, não depois que o servidor retorna, até porque, se fosse assim, você não teria mais acesso aos dados, já que a página recarregou e o JS não teria mais controle sobre esse evento =)

Então @TMiranda7, o que está acontecendo é que, provavelmente, você não usou o `preventDefault()`, e o formulário está sempre sendo enviado ao clicar no botão antes de fazer as ações que você precisa fazer =)

Testa ae e me diz se era isso mesmo =)

**Comment by fdaciuk** [comment]
Oi @TMiranda7 e @gabrielbahniuk! Vou fechar a issue, mas se ainda tiver qualquer problema, só avisar que eu reabro, ok? =)
