### ISSUE TITLE
[Challenge 29] Chamando função dentro de outra

### ISSUE THREAD

**Issue by gabrielbahniuk** [da2k/curso-javascript-ninja#4788]
Olá professor,

estou fazendo um refactoring e gostaria que o código abaixo funcionasse:

 initTableElements : function initTableElements() {
        var $fragment = document.createDocumentFragment();
        var $imagem = document.createElement('img');
        var $tbody = document.createElement('tbody');
        var $linha = document.createElement('tr');
        var $tdImagem = document.createElement('td');
        var $tdMarca = document.createElement('td');
        var $tdModelo = document.createElement('td');
        var $tdPlaca = document.createElement('td');
        var $tdAno = document.createElement('td');
        var $tdCor = document.createElement('td');
        this.appendFields();
        return $fragment.appendChild($tbody);
      },
      appendFields : function appendFields() {
        $tdImagem.appendChild($imagem);
        $linha.appendChild($tdImagem);
        $linha.appendChild($tdMarca);
        $linha.appendChild($tdModelo);
        $linha.appendChild($tdPlaca);
        $linha.appendChild($tdAno);
        $linha.appendChild($tdCor);
        $tbody.appendChild($linha);
        return $tbody;
      }

Estou chamando uma função dentro da outra, e está me retornando o erro $tdImagem is not defined, pois uma função não ta conseguindo acessar os atributos da outra.

Não seria só executar o método do jeito que estou fazendo acima? Ou tem mais algo que deve ser feito?

Minha ideia é fazer um InitTableElements, depois AppendFields...e ir quebrando em vários métodos até todos ficarem menores. Atualmente tenho o método InsertNewCar que está sobrecarregado de código e responsabilidades.

Obrigado.

@fdaciuk

**Comment by gabrielbahniuk** [comment]
@fdaciuk 

Eu entendi o que você quis dizer, mas confesso que to um pouco perdido no código.

Poderia me auxiliar?

Código:

      initTableElements : function initTableElements() {
        let $imagem = document.createElement('img');
        let $tbody = document.createElement('tbody');
        let $linha = document.createElement('tr');
        let $tdImagem = document.createElement('td');
        let $tdMarca = document.createElement('td');
        let $tdModelo = document.createElement('td');
        let $tdPlaca = document.createElement('td');
        let $tdAno = document.createElement('td');
        let $tdCor = document.createElement('td');
        return this.appendFields($tbody, $linha, $tdImagem, $imagem, $tdMarca, $tdModelo, $tdPlaca, $tdAno, $tdCor);
      },
      appendFields : function appendFields(tbody, linha, tdImagem, imagem, tdMarca, tdModelo, tdPlaca, tdAno, tdCor) {
        tdImagem.appendChild(imagem);
        linha.appendChild(tdImagem);
        linha.appendChild(tdMarca);
        linha.appendChild(tdModelo);
        linha.appendChild(tdPlaca);
        linha.appendChild(tdAno);
        linha.appendChild(tdCor);
        tbody.appendChild(linha);
        return tbody;
      },
      insertNewCar : function insertNewCar() {
        let $fragment = document.createDocumentFragment();
        let tbody = this.initTableElements();
        let $image = tbody.firstElementChild.children[0];
        let $marca = tbody.firstElementChild.children[1];
        let $modelo = tbody.firstElementChild.children[2];
        let $ano = tbody.firstElementChild.children[3];
        let $placa = tbody.firstElementChild.children[4];
        let $cor = tbody.firstElementChild.children[5];

        app.setValues($image, $('[data-js="input-imagem"]'),'img');
        app.setValues($marca, $('[data-js="input-marca"]'),'td');
        app.setValues($modelo, $('[data-js="input-modelo"]'),'td');
        app.setValues($ano, $('[data-js="input-ano"]'),'td');
        app.setValues($placa, $('[data-js="input-placa"]'),'td');
        app.setValues($cor, $('[data-js="input-cor"]'),'td');

        return $fragment.appendChild(tbody);
      },
      setValues : function setValues(column, field, fieldType) {
        switch(fieldType) {
          case 'td':
            return column.textContent = $(field).get().value;
          case 'img':
            return column.setAttribute('src', $(field).get());
        }

Estou debugando e quando chego na linha:

 app.setValues($image, $('[data-js="input-imagem"]'),'img');

ele vai pro método:

function DOM(elements) {
      if (!(this instanceof DOM))
        return new DOM(elements);
      this.element = this.getElements(elements);
    }

PS: Nesse método acima, ele cai no primeiro if.

E me retorna o erro:

Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.

**Comment by gabrielbahniuk** [comment]
Claro, entendi sim, obrigado!

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, só avisar =)
