### ISSUE TITLE
Desafio 21 

### ISSUE THREAD

**Issue by felipet66** [da2k/curso-javascript-ninja#4791]
Escreva aqui sua dúvida

Fernando, 

Para resolver o desafio 21, acabei utilizando funções anônimas para resolve-lo, vi a sua solução e fiquei na dúvida, a melhor forma para resolver em questão de performance e afins, seria sempre nomeando as funções ?

Meu código: 
`(function(window, document){`
```
'use strict';
var $btnStart = document.querySelector('[data-js="btnStart"]');
var $btnStop = document.querySelector('[data-js="btnStop"]');
var $btnReset = document.querySelector('[data-js="btnReset"]');
var $timer = document.querySelector('[data-js="timer"]');

var temporizador;

$btnStart.addEventListener('click', function(){
    var contador = 0;
    function timer(){
        $timer.value = contador++;
        temporizador = setTimeout(time, 1000);
    }
}, false);

$btnStop.addEventListener('click', function(){
   clearTimeout(temporizador);
}, false);

$btnReset.addEventListener('click', function(){
    $timer.value = 0;
    clearTimeout(temporizador);
 }, false);
```

`})(window, document);``

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felipet66! Não há problemas em criar funções anônimas, passando direto para o método `addEventListener`, desde que você não precise remover esse evento depois =)

Agora, se você precisar remover o evento, você teria que, obrigatoriamente, criar a função de forma separada, pois o método `addEventListener` e `removeEventListener` precisam compartilhar a mesma referência da função. Se você criasse uma função anônima para passar para o `addEventListener`, e criasse uma outra, ainda que com o mesmo conteúdo, para passar para o `removeEventListener`, como funções são objetos, a cada vez que você cria uma função usando `function () {}`, um novo objeto é criado.

Ainda que elas sejam "parecidas", ou tenham "o mesmo conteúdo", elas não são a mesma referência na memória. Logo, o evento não seria removido quando o `removeEventListener` fosse chamado =)

Ficou claro? =)

**Comment by felipet66** [comment]
Ficou sim, obrigado!

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, só avisar =)
