### ISSUE TITLE
Problema com pull request

### ISSUE THREAD

**Issue by guilhermeTaira** [da2k/curso-javascript-ninja#4805]
Opa, tudo bom?

Estou fazendo o desafio 1 e não consigo fazer o pull request... Parece que o layout do github mudou também. Poderia me ajudar?

@fdaciuk

**Comment by rudieriel** [comment]
Tenho o mesmo problema, parece que não vai o challenge-01!

**Comment by rudieriel** [comment]
Eu consegui enviar, entrei de novo no meu repositório e estava la o commit e abri ele e enviei, sou noob em github, mas apareceu no teu repo como Update la com o usuario rudieriel!

**Comment by fdaciuk** [comment]
Oi @guilhermeTaira e @rudieriel! Vou fechar a issue, mas se ainda tiver qualquer problema, me avise que eu reabro, ok? =)
