### ISSUE TITLE
CPF Máscara e Validação

### ISSUE THREAD

**Issue by ricardomirannda** [da2k/curso-javascript-ninja#4813]
Olá Daciuk, bom dia! tudo bem contigo?
Será que teria como você me dar uma pequena ajuda? 

Estou precisando validar e colocar uma máscara no campo de CPF.
Quando utilizo **APENAS** a função de **VerificaCPF**, o script funciona normalmente. 

Quando utilizo **APENAS** o script de **formatar (máscara)** funciona normalmente. 

Porém quando utilizo **as duas funções** no CPF, deixa de validar
e todos os CPF's são informados como **NÃO VÁLIDO**. 

Você tem ideia de como resolver?

Código 
https://codepen.io/ricardomirannda/pen/dKoGvm?editors=1010

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! O seu problema acontece porque, na função `vercpf`, você está recebendo o CPF com pontos e o traço. Logo, o `length` dele vai ser maior que 11 e sempre vai retornar `false` =)

Antes de verificar o length, remova os pontos e o traço, deixando somente números na string que tudo vai funcionar como esperado =)

**Comment by ricardomirannda** [comment]
Muito obrigado pela ajuda Daciuk !!!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
