### ISSUE TITLE
Curso

### ISSUE THREAD

**Issue by fsoaresjunior** [da2k/curso-javascript-ninja#4844]
Boa tarde Fernando, concluí o curso e gostaria de agradecer imensamente pelo conteúdo passado. Foi o melhor investimento que já fiz, e hoje tenho uma direção do que aprender daqui em diante.

Gostaria que você avaliasse o meu projeto que está nesse [link](https://github.com/fsoaresjunior/Carros-Web) sugerindo melhorias.

Além disso, ouvi boatos de que estaria lançando um curso de es6/7/8, não sei se é verdade kkk abraço e sucesso.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fsoaresjunior! Parabéns cara \o/
Vou dar uma olhada no seu desafio sim =)

Em breve teremos novos cursos sim :D

**Comment by fdaciuk** [comment]
Oi @fsoaresjunior! Percebi que passou um tempo e eu não dei feedback do seu código ainda, desculpe :\
Vou fechar a issue, mas se você ainda precisar de mim pra qualquer coisa, só avisar, ok? ≃)
