### ISSUE TITLE
[ajuda] - SpeechRecognition API e refatoração

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#4848]
Olá, professor! Sou "ex-aluno" do curso e gostaria de suas sugestões. 

Como posso refatorar esse código feio? Cheguei a encadear um map() no outro, não tá legal. Promise seria uma alternativa? E para o restante do código, o que você indica? 

```javascript
window.SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;

const recognition = new window.SpeechRecognition();
let p = document.createElement('p');
const words = document.querySelector('[data-js="words"]');
words.appendChild(p);

recognition.interimResults = true;

recognition.addEventListener('result', e => {
  const transcript = Array.from(e.results).map(result => result[0]).map(result => result.transcript).join('');
  p.textContent = transcript;
  if(e.results[0].isFinal) {
    p = document.createElement('p');
    words.appendChild(p);
  }

  if(transcript.includes('óculos')) {
    console.log('palavra óculos detectado');
  }

  if(transcript.includes('areia')) {
    console.log('palavra areia detectada');
  }

  console.log(transcript);
});

recognition.addEventListener('end', recognition.start);
recognition.start();
```

Caso possa dar uma olhada, o código completo da aplicação está hospedado [aqui](https://github.com/Roger-Melo/javascript-speech-recognition)

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Roger-Melo! Tudo bem? =)

O código que você gostaria de refatorar seria esse?

```js
const transcript = Array.from(e.results).map(result => result[0]).map(result => result.transcript).join('');
```

Se for, a parte dos dois `map`s, você poderia fazer:

```js
const transcript = Array.from(e.results).map(result => result[0].transcript).join('');
```

Já reduziria um `map` =)

No mais, acho que tá legal =)

Dá pra tentar evoluir o código pensando em alguns conceitos diferentes, como imutabilidade. Tente não modificar valores de variáveis e propriedades de objetos (sempre que possível), para começar a praticar mais esse conceito!

Mas o caminho é esse mesmo: com a prática é que você consegue subir de nível :D 

Parabéns pelo projeto =)

**Comment by Roger-Melo** [comment]
Massa professor! Estou com um pouco de dificuldade em entender o aninhamento de informações no console

![s1](https://user-images.githubusercontent.com/29297788/41177892-f9e69a80-6b3b-11e8-9129-230f43b7cb1b.jpg)

Se entendi, o 

```javascript
const transcript = Array.from(e.results);
```

me dá um SpeechRecognitionResult, que é um array com apenas um item. Esse item é um objeto (SpeechRecognitionAlternative). Para que eu acesse o SpeechRecognitionAlternative, que é o 1º e único item do SpeechRecognitionResult, encadeio o: 

```javascript
.map(item => item[0]);
```

e para acessar a propriedade transcript do SpeechRecognitionAlternative, faço: 

```javascript
.map(item => item[0].transcript);
```

Até aqui, o array gerado pelo map possui apenas uma string. Para que eu junte itens desse array em uma só string (mesmo o item sendo apenas uma string), faço o .join(''), passando ```''``` como parâmetro para que não haja nenhum caractere na junção. É isso?

**Comment by Roger-Melo** [comment]
Entendi, professor! =) 

Escrevi o código seguindo um [tutorial](https://youtu.be/0mJC0A72Fnw) do Wes Bos. No próprio vídeo ele diz que se preocuparia apenas em fazer o código funcionar, sem pensar em boas práticas. 

O `e.results` gera, algumas vezes, um array like (SpeechRecognitionResultList) com dois objetos.  Mas o último SpeechRecognitionResultList mostrado no console sempre contém apenas 1 objeto com a frase que falei no microfone (na propriedade transcript): 

![sr](https://user-images.githubusercontent.com/29297788/41205529-57b9fd56-6ccb-11e8-8dc7-2f9c4cf14d3d.jpg)

Eu testei o 

```javascript
const transcript = e.results[0][0].transcript;
```

e não houve erro. Então talvez realmente não precise do map(), né?

**Comment by fdaciuk** [comment]
Legal! Eu nunca estudei a fundo essa API, então não sei te dizer se usar `e.results[0][0].transcript` poderia ser um problema ou não xD

Mas, das possibilidades que eu testei, funcionou bem. Talvez seja útil fazer o `map` apenas quando você precisa tratar todas as entradas. Como você está usando só a entrada final "com `.isFinal`, pode ser que essa forma que eu passei sempre funcione, mas não vou saber te dizer com certeza =)

Mas é isso mesmo: o importante primeiro é fazer funcionar! Depois, se houver algum problema, você vai arrumando conforme os problemas forem surgindo =)

**Comment by Roger-Melo** [comment]
Massa, professor! Muito obrigado!  :grin:
