### ISSUE TITLE
[duvida] Ajax e retorno

### ISSUE THREAD

**Issue by gabrielbahniuk** [da2k/curso-javascript-ninja#4874]
Olá (novamente) professor,

estou com um problema de retorno de AJAX (GET) que não consegui resolver de jeito nenhum.

tenho um app.js que é o seguinte:

```
(function() {

    'use strict';          
    const URL = 'http://localhost:3000/api/users';

    const app = (function(){
        
        return {
            initApp : function() {
                this.initEvents();
            },
            initEvents : function initEvents() {
                const $btn = document.querySelector('[data-js="button"]');
                $btn.addEventListener('click', function(){
                    console.log(app.getAjax());
                }, false);
            },
            getAjax : function getAjax() {
                var ajaxGet = new XMLHttpRequest();
                ajaxGet.open('GET', URL);
                ajaxGet.send();
                let data;
                ajaxGet.addEventListener('readystatechange', function(){
                    if(ajaxGet.readyState === 4 && ajaxGet.status === 200) {
                        data = JSON.parse(ajaxGet.responseText);
                        // console.log(data);
                        return data;
                    }
                        
                }, false);
            }                
        };

    })();

    app.initApp();

})();
``` 

o código comentado `//console.log(data)` retorna certinho no console, mas quando eu executo a função `app.getAjax()` que por sinal tem um `return data` aparece `undefined`.

Estou há algum tempo quebrando a cabeça com isso.

Poderia me dizer o que estou fazendo de errado?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae @gabrielbahniuk! 

Só antes de responder, uma dica: quando for usar blocos de código, coloque o código entre 3 crases (3 antes e 3 depois).

Uma crase é só pra códigos "inline" =)

---

Sobre a sua dúvida: lembra quando vimos sobre código assíncrono vs código síncrono no curso? Esse é o ponto =)

O `return` que você está usando é dentro da função que é usada como _callback_ do evento `readystatechange`. `app.getAjax()` não tem retorno algum, por isso retorna `undefined` :)

De qualquer forma, ainda que você tentasse colocar um `return` em `getAjax()`, você não teria a informação da forma que espera.

Sempre que você precisar fazer uma chamada assíncrona, e precisar do resultado dessa chamada, mas a chamada está isolada em uma função - assim como você fez - o que você precisa fazer é o que fizemos lá no desafio da calculadora: inversão de responsabilidade.

Você passa uma função via argumento para o `getAjax()` - que chamamos de _callback_, pois ela vai ser executada no futuro - e, quando o request finalizar, você executa essa função.

Exemplo:

```js
getAjax: function getAjax (callback) {
  // ...seu código aqui
  ajaxGet.addEventListener('readystatechange', function () {
    // ... código da função
    // ao invés de `return data`, você executa o callback que foi passado via argumento lá em cima, passando para ele o `data`:
    callback(data)
  }, false)
}
```

Agora, quando você executar `app.getAjax()`, você precisa passar uma função via argumento, que vai ser executada quando o request terminar. E quando esse request terminar, essa função que você passou via argumento, vai receber um outro argumento, que são os dados da resposta do request.

Exemplo:

```js
app.getAjax(function (data) {
  // aqui dentro você tem acesso aos dados do request:
  console.log(data)
})
```

Deu pra entender a ideia? =)

**Comment by gabrielbahniuk** [comment]
@fdaciuk Explicação ótima, agora consegui aqui passando a function de callback, tinha esquecido disso.

Muito obrigado!!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar =)
