### ISSUE TITLE
Propriedades dentro de métodos

### ISSUE THREAD

**Issue by Hamiltonspjunior** [da2k/curso-javascript-ninja#4889]
Olá, Fernando. 
Uma dúvida: sempre que estivermos acessando uma propriedade de um objeto, dentro de um método, precisamos mesmo especificar o objeto? Ex:
Pessoa.nomeCompleto: function(){
    Return pessoa.nome + pessoa.sobrenome
}

Não podemos suprimir o pessoa e usar apenas nome e sobrenome já que tudo está dentro do mesmo objeto?
Obrigado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Hamiltonspjunior! Nesse caso não, pois `nome` e `sobrenome`, por exemplo, seriam nomes válidos de variáveis que não existem nesse caso. Tirando o `pessoa.` da frente do nome da propriedade, não tem como o JS saber de onde vem os valores de `nome` e `sobrenome`, entende? =)

**Comment by Hamiltonspjunior** [comment]
Entendi sim.
Muito obrigado pela resposta.

Em ter, 12 de jun de 2018 13:14, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
