### ISSUE TITLE
Challenge29

### ISSUE THREAD

**Issue by felipet66** [da2k/curso-javascript-ninja#4892]
Fala Fê, blz ?

Estou tentando inserir o botão remover no exercicio da challange 29.

Criei meu td ação
`var $tdAcao = document.createElement('td');`
Meu botão
`var $btnRemover = document.createElement('button');`

Adicionei os Atributos class e textContet
`$btnRemover.setAttribute('class', 'btn btn-danger');
        $btnRemover.textContent = 'X';`

Adicionei no td o botão remover
`$tdAcao.appendChild($btnRemover);`

Agora vou criar ação para o meu btnRemover passando meu tr por parametro.
`$btnRemover.on('click', this.handleRemoveElement($tr));`

Ai apresenta o erro:
> TypeError: $btnRemover.on is not a function[Learn More]

Pode me ajudar ?
____________________________________________________________
Código completo abaixo:
`(function($) {
  'use strict';

  var app = (function(){
    return{
      init: function init(){
        this.companyInfo();
        this.initEvents();
      },
      initEvents: function initEvents(){
        $('[data-js="form-register"]').on('submit', this.handleSubmit);
      },
      handleSubmit: function handleSubmit(e){
        e.preventDefault();
        var $tableCar = $('[data-js="table-car"]').get();
        $tableCar.appendChild(app.createNewCar());
      },
      createNewCar: function createNewCar(){
        var $fragment = document.createDocumentFragment();
        var $tr = document.createElement('tr');
        var $tdImage = document.createElement('td');
        var $image = document.createElement('img');
        var $tdBrand = document.createElement('td');
        var $tdYear = document.createElement('td');
        var $tdPlate = document.createElement('td');
        var $tdColor = document.createElement('td');
        var $tdAcao = document.createElement('td');
        var $btnRemover = document.createElement('button');

        $btnRemover.setAttribute('class', 'btn btn-danger');
        $btnRemover.textContent = 'X';
        $tdAcao.appendChild($btnRemover);
        $btnRemover.on('click', app.handleRemoveElement($tr));

        $image.setAttribute('src', $('[data-js="image"]').get().value);
        $tdImage.appendChild($image);
        $tdBrand.textContent = $('[data-js="brand-model').get().value;
        $tdYear.textContent = $('[data-js="year').get().value;
        $tdPlate.textContent = $('[data-js="plate').get().value;
        $tdColor.textContent = $('[data-js="color').get().value;

        $tr.appendChild($tdImage);
        $tr.appendChild($tdBrand);
        $tr.appendChild($tdYear);
        $tr.appendChild($tdPlate);
        $tr.appendChild($tdColor);
        $tr.appendChild($tdAcao);

        return $fragment.appendChild($tr);
      },
      handleRemoveElement: function handleRemoveElement(tr){
        tr.remove();
      },
      companyInfo: function companyInfo(){
        var ajax = new XMLHttpRequest();
        ajax.open('GET', 'json/company.json', true);
        ajax.send();
        ajax.addEventListener('readystatechange', this.getCompanyInfo, false);
      },
      getCompanyInfo: function getCompanyInfo(){
        if(!app.isReady.call(this))
          return;
        var data = JSON.parse(this.responseText);
        var $companyName = $('[data-js="company-name"]').get();
        var $companyPhone = $('[data-js="company-phone"]').get();
        $companyName.textContent = data.name;
        $companyPhone.textContent = data.phone;
        },
      isReady: function isReady(){
        return this.readyState === 4 && this.status === 200;
      }
    };
  })();

  app.init();

})(window.DOM);`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felipet66! Você criou o botão usando a variável `$btnRemover`, mas para atrelar um evento a esse elemento, ele precisa já fazer parte do DOM.

Nesse caso, após fazer o `appendChild`, você precisa "pegar" esse elemento lá do DOM - com `document.querySelector`, ou usando a lib DOM; não usando a variável que você usou para criar o elemento -, e então atrelar o evento. 

Sacou a ideia? =)

**Comment by felipet66** [comment]
@fdaciuk Bom dia mano,

Acho que entendi...

Eu consegui fazendo desta forma:

 
        ```
var $tdAcao = document.createElement('td');
        var $btnRemover = document.createElement('button');

        $btnRemover.setAttribute('class', 'btn btn-danger');
        $btnRemover.textContent = 'X';
        $btnRemover.addEventListener('click', handleRemoveElement)

        function handleRemoveElement(){
          $tr.remove();
        }

        $tdAcao.appendChild($btnRemover);
```


Mas repara que eu utilizei o remove() do JQuery... Como eu poderia fazer pra criar essa funcao remove ?

**Comment by fdaciuk** [comment]
Legal! Nesse caso, a função `handleRemoveElement` vai receber um argumento: o objeto do evento, já que ela é um _handler_ do evento de _click_ do botão de remover. Com esse objeto, você consegue pegar através da propriedade `target`, e fazer a remoção do elemento que você quer remover, sem precisar do jQuery =)
