### ISSUE TITLE
[Aula 10]: Desafio da Calculadora

### ISSUE THREAD

**Issue by daviccardoso** [da2k/curso-javascript-ninja#4899]
Olá, Fernando!

Como vai? Espero que muito bem.

Gostaria de, humildemente, apontar algo que identifiquei no desafio da calculadora que construímos na aula 10.

Observei que, apesar de validarmos o tipo dos parâmetros, não tratamos o caso negativo na invocação da operação aritmética, de modo que é possível passar como parâmetro um tipo não-numérico e, ainda assim, receber a mensagem da operação como se fosse um caso positivo.

Veja meu comentário abaixo e um exemplo de execução:

```javascript
operationSignal = '+';
var sum = calculator(operationSignal);

if (sum) {
    number1 = 10;
    number2 = 5; // Se passarmos 'JS Ninja', por exemplo, a mensagem apresentará false como resultado.
    console.log(showOperationMessage(operationSignal, number1, number2), sum(number1, number2));
} else {
    console.log(showErrorMessage(operationSignal));
}
```

![image](https://user-images.githubusercontent.com/20673538/41372739-8d061174-6f24-11e8-89d9-447b9a40ed2c.png)

Sei que é complicado tratar isso com o vídeo já gravado, mas gostaria de saber se minha análise faz sentido para você e se estou no caminho certo.

Tenho gostado muito do curso! Estou aprendendo muito e já o indiquei para alguns amigos.

Muito obrigado por compartilhar seu conhecimento conosco, Fernando!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @daviccardoso! Tudo ótimo sim :D 

Acho que entendi seu ponto =)

Esse seria sim um outro ponto de atenção a se considerar. É importante ressaltar que sempre há a possibilidade de melhorias em todo desafio que foi passado. Muitas vezes você irá encontrar uma solução melhor do que a que eu apresentei. 

E ao conseguir encontrar esses pontos de melhoria, isso mostra o quanto você está atento e que de fato você está conseguindo absorver bem o conteúdo. Parabéns!

Fico feliz que está curtindo o curso =)

Qualquer dúvida, pode abrir issue! Estou aqui para ajudar no que for necessário :D

**Comment by daviccardoso** [comment]
Combinado, @fdaciuk. ;^)

Muito obrigado pela atenção e gentileza!
