### ISSUE TITLE
[Desafio 2]

### ISSUE THREAD

**Issue by gabrielazevedo** [da2k/curso-javascript-ninja#49]
Fala @fdaciuk blz?
Estou atrasado nos exercícios devido a alguns contratempos.

Estou tendo dificuldade neste exercício, sera que poderia me ajudar a entender?

/*
Crie uma função com as seguintes características:
1. A função deve receber 3 argumentos;
2. Se qualquer um dos três argumentos não estiverem preenchidos, a função deve retornar a string:
    Preencha todos os valores corretamente!
3. O retorno da função deve ser a multiplicação dos 3 argumentos, somando `2` ao resultado da multiplicação.
*/  

Obrigado

**Comment by fdaciuk** [comment]
Olá @gabrielazevedo! Sem problemas meu caro :)

Vamos lá: onde você travou nesse exercício?

Dica: Tente ir fazendo passo-a-passo para saber onde é exatamente a sua dúvida, ok? :)

**Comment by fdaciuk** [comment]
O problema nesse exercício está sendo normalmente para verificar se um argumento foi passado ou não. Se for essa a sua dificuldade, é assim:

Lembra que falamos sobre `null` e `undefined`? Que `undefined` é quando uma variável não tem nenhum valor definido?

Esse é o mesmo caso! Para saber se um parâmetro não foi passado, é só verificar se ele é igual a `undefined` :)

**Comment by gabrielazevedo** [comment]
Olha o que eu fiz.

function nova(x, y, z){
	if(x == undefined || y == undefined || z == undefined){
		"Preencha todos os valores corretamente!"
	}
	return x * y * z;
}

**Comment by fdaciuk** [comment]
É quase isso, só tem uns pequenos ajustes :)
Manda PR que fica mais fácil de comentar na linha certa pra você saber onde está o erro, pode ser?

**Comment by gabrielazevedo** [comment]
O problema que não fiz os outros exercícios abaixo.
Vou estar fazendo os exercícios e mando o PR hoje mais tarde, pode ser?
Ai você ja me manda tudo que tenho que concertar.

**Comment by fdaciuk** [comment]
Sem problemas! :D
