### ISSUE TITLE
forEach

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-javascript-ninja#4918]
Olá Fernando.

Tudo bom?

Já tenho o curso mas ainda não comecei. Mesmo assim vou fazer uma pergunta sobre JavaScript aqui e você me diz se pode me ajudar.

Preciso fazer um array com valores dinâmicos a partir de xAnos atrás, por exemplo, de 10 ou mais anos atrás até o ano corrente.

Algo do tipo:

yearFrom ={1990, 1991, 1992, ... 2017}
yearTo ={1991, 1991, 1992, ... 2018}

Não quero fazer isso hard code então pensei em usar o forEach para gerar esse array.
Por favor, já tem algum vídeo desse curso de JavaScript que ensina a usar o forEach e o map ou você pode me dar dicas para eu me virar?
 
Obrigado

@fdaciuk

**Comment by Alexandre1202** [comment]
Perfeito! 
Obrigado

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
