### ISSUE TITLE
.reduce()

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#4920]
Olá, professor! 

O código abaixo me retorna um array com 3 objetos, e cada objeto possui duas propriedades, `codigo` e `valor`: 

```javascript
$button.onclick = () => {
  fetch('http://localhost:3000/notas')
  .then(handleStatus)
  .then(arrObjsNotas => arrObjsNotas.reduce((acumulado, atual) => acumulado.concat(atual.itens), []))
  .then(objsCodigo => objsCodigo.filter(item => item.codigo === '2143'))
  .then(console.log)
  .catch(console.log);
};
```

![objs-retornados](https://user-images.githubusercontent.com/29297788/41510197-8b5efb1e-7236-11e8-81ec-1bb665d2ca2d.jpg)

Considerando que, caso eu faça um reduce para obter a soma total dos valores das propriedades `valor` de cada objeto, e não utilize o segundo parâmetro, que poderia ser `0`, por exemplo, o esperado é que o parâmetro `acumulado` do reduce seja o primeiro objeto do array, certo? Mas não estou entendendo pq o resultado final é `NAN`, sendo que o primeiro objeto tem a propriedade `valor`: 

```javascript
$button.onclick = () => {
  fetch('http://localhost:3000/notas')
  .then(handleStatus)
  .then(arrObjsNotas => arrObjsNotas.reduce((acumulado, atual) => acumulado.concat(atual.itens), []))
  .then(arrObjs => arrObjs.filter(item => item.codigo === '2143'))
  .then(arrObjs2 => arrObjs2.reduce((acumulado, atual) => acumulado.valor + atual.valor))
  .then(console.log)
  .catch(console.log);
};
```

![nan](https://user-images.githubusercontent.com/29297788/41510234-4b095554-7237-11e8-8301-802bede64ec6.jpg)

Só funciona se eu passar o segundo parâmetro (`0`)! 

```javascript
$button.onclick = () => {
  fetch('http://localhost:3000/notas')
  .then(handleStatus)
  .then(arrObjsNotas => arrObjsNotas.reduce((acumulado, atual) => acumulado.concat(atual.itens), []))
  .then(arrObjs => arrObjs.filter(item => item.codigo === '2143'))
  .then(arrObjs2 => arrObjs2.reduce((acumulado, atual) => acumulado + atual.valor, 0))
  .then(console.log)
  .catch(console.log);
};
```

![funcionou-com-parametro](https://user-images.githubusercontent.com/29297788/41510252-8fab3e16-7237-11e8-9fba-1526b1dea817.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! O problema não está na primeira iteração, e sim nas próximas: lembre-se que o valor acumulado é sempre que a função passada para o `reduce` retorna. Se não passar o `0` no segundo parâmetro, na primeira iteração, o `acumulado` vai ser um objeto, com a propriedade valor.

O que você retorna dessa função? `acumulado.valor + atual.valor`, correto?

Na próxima iteração, `acumulado` não vai mais ser um objeto, e sim um **número**: o resultado da soma de `acumulado.valor + atual.valor`.

Isso significa que `acumulado` sendo um número, ele não vai ter uma propriedade chamada `valor`. Logo, `acumulado.valor` seria `undefined`, que, ao tentar "somar" com `atual.valor`, vai retornar `NaN` =)

Por isso é sempre importante passar o segundo argumento do `reduce`, sempre representando o tipo de dado que o `reduce` vai retornar no final =)

**Comment by Roger-Melo** [comment]
Ahhhhhhh :sweat_smile:, fez todo sentido, professor. 

Muito obrigado! =)

**Comment by wilsonazer** [comment]
ajudou bastante, eu estava cometendo um erro idiota. tentando algo do tipo "acumulado.valor",  que agora sei bem retornará not a number
