### ISSUE TITLE
Publicação de Desafios via GIT

### ISSUE THREAD

**Issue by Hernany** [da2k/curso-javascript-ninja#4941]
Fernando, bom dia!
Tem como confirmar se os meus desafios foram publicados no GIT.
Estou desconfiado que está faltando algo!
Não tenho costume de usar o site do GIT para publicar e a versão do GIT na época do curso está um pouco distinta da atual.

Aguardo breve retorno!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Hernany!

Está vindo tudo certinho sim =)

Mas se não quiser, não precisa se preocupar em enviar os desafios aqui no GitHub, pois antes era necessário para gerar o certificado. Agora a Udemy mesmo gera =)

Mas fique à vontade para enviar ou não, ok? Se não quiser mandar, apenas tente fazer no seu computador, de forma local mesmo, para praticar :D 

Mas se for mandar, e quiser ver se seus PRs foram enviados corretamente, é só clicar na aba "Pull Requests" aqui no repositório do curso mesmo:

![selection_069](https://user-images.githubusercontent.com/487669/41662903-836e2760-7478-11e8-8be8-2b555ea9ac81.png)

E depois selecionar a opção "Author", digitar seu nome de usuário e pressionar ENTER:

![selection_072](https://user-images.githubusercontent.com/487669/41663026-dac01d66-7478-11e8-926e-9d6a212159e9.png)

Assim você vai ver somente os PRs que você enviou:

![selection_073](https://user-images.githubusercontent.com/487669/41663070-f896284e-7478-11e8-93da-a3b3c301098e.png)

Qualquer dúvida, só avisar =)

**Comment by fdaciuk** [comment]
Oi @Hernany! Deu certo? Vou fechar a issue, mas se você ainda tiver qualquer problema, só avisar que eu reabro, ok? =)
