### ISSUE TITLE
Duvida sobre Github

### ISSUE THREAD

**Issue by raphaelanjos1** [da2k/curso-javascript-ninja#4942]
Fala Daciuk, beleza? 

Surgiu uma dúvida sobre uma funcionalidade do github:

Como posso configurar o mesmo repositório do curso javascript ninja em outro computador? Digo, conseguir fazer commits, push, criar branches e fazer pull requests dos desafios no mesmo repositório forkado que já uso em outro computador, só que de outro pc, que já está com ssh configurada. 

Geralmente estudo de casa, onde tenho o repositório em funcionamento com 19 branches.. Gostaria de continuar fazendo meus pull requests de onde quiser, e sempre atualizando o meu repositório.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @raphaelanjos1! Você pode seguir os passos dessa issue aqui:
https://github.com/da2k/curso-javascript-ninja/issues/79

=)

**Comment by raphaelanjos1** [comment]
@fdaciuk, consegui fazer o push e o pull request no trabalho apenas clonando o repositório e criando a branch nova normalmente, já que a ssh já estava pronta para este pc.

Minha dúvida agora é a seguinte, para atualizar meu repositório de casa, que já tem todas as outras branches, menos a criada no trabalho hoje, basta dar um git pull?

**Comment by fdaciuk** [comment]
Ah sim, se você queria apenas pegar o repositório principal, e resolver desafios novos, só o clone / pull / push resolvem mesmo.

Agora, se quiser atualizar tudo, inclusive com todas as branches anteriores, ae seria seguir o link que passei acima =)

**Comment by raphaelanjos1** [comment]
Valeu mestre! @fdaciuk
