### ISSUE TITLE
Fork do Repo

### ISSUE THREAD

**Issue by willmorim** [da2k/curso-javascript-ninja#4963]
Olá, quando vou fazer do fork deste repo, tem a seguinte mensagem: 

**_fork-js-ninja_NAO_FACA_FORK_DESSE_REPO_**

Devo continuar o fork acompanhando ele?
Devo fazer fork de outro repo e acompanhar?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willmorim! O repositório correto é esse que você abriu a issue (/da2k/curso-javascript-ninja) =)

Esse que está dizendo que não é pra fazer o fork está no meu perfil (/fdaciuk) =)

**Comment by willmorim** [comment]
Então, quando eu tento fazer o fork deste repo **https://github.com/da2k/curso-javascript-ninja**
ele me manda para o que tem a mensagem do **fork-js-ninja_NAO_FACA_FORK_DESSE_REPO**

**Comment by fdaciuk** [comment]
Como assim? Você está clicando no botão _Fork_ e está sendo direcionado para outro repositório?  :thinking:

**Comment by willmorim** [comment]
Isso mesmo, por algum motivo quando eu clicava em FORK no **(/da2k/curso-javascript-ninja)**, ele me redirecionava para o do **(/fdaciuk)**...

deletei o repo e dei FORK no correto e foi O/

Obrigado!

**Comment by fdaciuk** [comment]
Legal @willmorim! Provavelmente acontecia isso porque você já tinha forkado do repo que estava no meu perfil em algum momento =)

Que bom que deu tudo certo agora! Qualquer dúvida, só avisar =)
