### ISSUE TITLE
[Desafio 9] Erro

### ISSUE THREAD

**Issue by italodfs** [da2k/curso-javascript-ninja#4972]
Logo no início em myFunction era pra retornar a soma de number1 + number2, só que não foi retornado apenas os console.log por quê?

Se tirarmos myFunction de dentro do escopo da IIFE, o resultado da soma aparece.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @italodfs! Não consegui entender muito bem qual é a sua dúvida. Consegue detalhar melhor? =)

**Comment by fdaciuk** [comment]
Oi @italodfs! Você ainda está com essa dúvida? Vou fechar a issue, mas se você ainda tiver qualquer problema, só avisar que eu reabro, ok? =)
