### ISSUE TITLE
Error ao dar git clone

### ISSUE THREAD

**Issue by Douglas-Ssilva** [da2k/curso-javascript-ninja#5022]
Boa noite, Professor!
Ao dar o git clone, com meu git já instalado, e no meu repositório, ao selecionar a opção SSH aparece a seguinte mensagem: 
```
λ git clone git@github.com:Douglas-Ssilva/curso-javascript-ninja.git
Cloning into 'curso-javascript-ninja'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

E quando mudo para HTTPs ele faz o clone normal, baixando todas as challenges...

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Douglas-Ssilva! Não há problema! Provavelmente você só não tem a chave SSH configurada =)
Mas pode usar HTTPS sem problemas =)

**Comment by fdaciuk** [comment]
Oi @Douglas-Ssilva! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver qualquer problema, só avisar que eu reabro, ok? =)
