### ISSUE TITLE
[MRW#06]  Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by guilhermealbuquerquegit** [da2k/curso-javascript-ninja#5029]
Estou com esse erro.   

Aqui está o link do meu projeto => https://github.com/guilhermealbuquerquegit/react-learn

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @guilhermealbuquerquegit! Pode abrir essa issue no repositório do curso de React?

O link é esse: https://github.com/da2k/curso-reactjs-ninja/

Valeu =)
