### ISSUE TITLE
Correção do Desafio

### ISSUE THREAD

**Issue by radharay** [da2k/curso-javascript-ninja#5068]
Escreva aqui sua dúvida
Olá, gostaria de saber se você demora muito para corrigir os desafios.

Obrigada, Ray 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @radharay! Eu não estou mais corrigindo os desafios um a um, pois o curso agora já está pronto, e você pode acompanhar a solução de cada desafio sempre no início da próxima aula =)

Mas estou aqui pra te ajudar sempre que você tiver dúvidas, seja sobre o conteúdo passado ou sobre o desafio (ou a solução do mesmo), ok? :D 

Qualquer dúvida, pode abrir issue que eu te ajudo =)

**Comment by fdaciuk** [comment]
Oi @radharay! Vou fechar a issue, mas qualquer problema, só avisar que eu te ajudo, ok? =)
