### ISSUE TITLE
[GIT] Remover arquivos não monitorados

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-javascript-ninja#522]
@fdaciuk blz? Estou com um probleminha, não sei o que eu fiz mas apareceu os diretorios 27,28 e 29 para commit, como eu retiro eles ?
![captura de tela de 2015-12-20 21 19 32](https://cloud.githubusercontent.com/assets/13294634/11920826/ba7a288c-a75f-11e5-9a2a-4fe54544936e.png)

**Comment by fdaciuk** [comment]
Fala @LucasCMota! O problema acontece porque você fez o fetch na branch do seu desafio. Tem que fazer o fetch sempre na branch **master**.

Mas para resolver é fácil: pode só remover esses arquivos dessa branch `challenge-16` que não vai ter problema :)

**Comment by LucasCMota** [comment]
@fdaciuk, eu pesquisei no google como remover mas não encontrei

**Comment by fdaciuk** [comment]
Deletar mesmo, com `rm -rf <nome-do-arquivo>` :)

**Comment by LucasCMota** [comment]
@fdaciuk deu certo

**Comment by fdaciuk** [comment]
o/

**Comment by marcotropeco** [comment]
Tente usar git clean -f
