### ISSUE TITLE
Projeto Final (ongoing)

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-javascript-ninja#5257]
Mestre, empaquei tentando arrumar um flip-card que me fugiu do controle. Criei um switcher para alterar o status dos  carros (alugado, disponível ou em manutenção). Após essas melhorias que quis implementar, o flip-card está funcionando de uma forma aleatória. Se vc cria vários carros e depois altera o status deles, ao fim, na hora de desvirar o card, apenas alguns deles funcionam, aparentemente de forma bem aleatória - de tal forma que eu não to conseguindo debbugar. Como eu fui além das coisas que vc pediu nos últimos challenges, talvez seja necessário ver o projeto rodando no browser.

https://github.com/pamplonapaulo/cursoJavascriptNinjaBackup/tree/master/FINAL-PROJECT

PS: Para alterar o status do carro, arraste o ícone à direita ou esquerda, ou simplesmente cliqie junto ao mecânico ou na estradinha. (É um input type=range).
Gratidão!

@fdaciuk

**Comment by pamplonapaulo** [comment]
Mestre, consegui resolver. Me dei conta que poderia usar "querySelectorAll" em um elemento específico (e suas children). Depois me diz o que acha do meu projetinho. Vou mandar brasa agora na parte de back-end (challenge 32). Abração!

**Comment by fdaciuk** [comment]
Legal @pamplonapaulo! Vou fechar a issue então, mas se tiver qualquer dúvida relacionada a isso ainda, pode comentar aqui que eu reabro, ok? =)
