### ISSUE TITLE
Functional Programing

### ISSUE THREAD

**Issue by Hamiltonspjunior** [da2k/curso-javascript-ninja#5288]
Olá, Fernando. Tudo bem?

Estou na aula de Functional programing. Durante a aula você deu essa função como exemplo: 

function add(x){
   return function(y){
      x + y
   }
}
add(2)(5)//7

Não ficou muito claro pra mim o do por que é preferível fazer algo como o exemplo acima ao invés de: 
function add(x, y){
	return x + y;
}
add(2, 5)//7

Ou seja, por que devemos usar a programação funcional ou invés de imperativa ou OO?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Hamiltonspjunior! Na verdade, o ponto não é nem sobre usar Funcional, imperativa ou OO.

O que eu quis mostrar nessa aula foi apenas que, com JavaScript, você consegue trabalhar com qualquer paradigma! É importante conhecer ao menos alguns detalhes de cada um para conseguir aproveitar ao máximo o uso da linguagem =)

Mas não há problema algum em fazer da forma como você mostrou =)

Até porque, não significa que a forma que você mostrou não possa ser usada se você estiver usando Programação Funcional :D 

A ideia é mostrar o máximo de coisas possíveis para se fazer com a linguagem, e mais pra frente você vai ver o quanto esse tipo de técnica é útil =)

**Comment by Hamiltonspjunior** [comment]
Entendi.

Mais uma vez muito obrigado!

Em qua, 25 de jul de 2018 12:02, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer dúvida, só avisar =)
