### ISSUE TITLE
[Aula 1] Problema no pull request

### ISSUE THREAD

**Issue by philipetessarin** [da2k/curso-javascript-ninja#5341]
Respondi o desafio da semana. O problema é que a opção **Compare & pull request** não aparece para mim.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @philipetessarin! Eu mostrei como fazer isso na issue #2368, dá uma olhada se te ajuda =)
Qualquer dúvida, só avisar =)

**Comment by philipetessarin** [comment]
Muito obrigado, consegui enviar.

**Comment by fdaciuk** [comment]
Show @philipetessarin! \o/
Qualquer coisa, só avisar :D
