### ISSUE TITLE
Challenge 07

### ISSUE THREAD

**Issue by flaviaguterres** [da2k/curso-javascript-ninja#5352]
Escreva aqui sua dúvida
Há diferença entre: counter % 2 !== 0 e counter % 2 === 1 ? Qual é a melhor prática?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @flaviaguterres! Lógica e matematicamente falando, os dois são similares, não há diferença nesse caso, pois qualquer valor dividido por 2 sempre terá resto 0 ou 1.

Então, nesse caso, tanto faz! Não há diferença =)

**Comment by fdaciuk** [comment]
O único ponto de atenção seria sempre garantir que você está fazendo comparação com números! Ao tentar usar o operador de módulo com qualquer outro tipo de dado, o resultado pode ser o objeto `NaN` (que é do tipo "número", mas é a representação de que o resultado gerado não pode ser exibido em formato numérico por isso `NaN` - `Not a Number`)  =)

Se você ainda não viu sobre o `NaN` no curso, não se preocupe que você ainda vai chegar lá =)

É só pra deixar registrado que isso pode acontecer =)

**Comment by flaviaguterres** [comment]
Pois então, pelo fato de você sempre fazer esse tipo de alerta (como o NaN) no curso que surgiu a dúvida. Na minha resolução do desafio 7 eu usei o "counter % 2 === 1" e na revisão você usou "counter % 2 !== 0". Como nesse exercício você não se prolongou sobre possíveis erros ou outras alternativas, achei melhor perguntar para não ficar com dúvidas e/ou utilizar a expressão de forma indevida. De todo modo, entendi a sua explicação. Obrigada! :)

**Comment by fdaciuk** [comment]
Show de bola! A dica que eu poderia dar para esses casos que tem mais de uma solução é:
Escolha a solução que, para você, fica mais clara e/ou legível!

Se por acaso nenhuma das duas ficar tão clara (como esse caso), você pode isolar a regra em uma função com um nome que dê a entender a sua intenção. Por exemplo, para checar se um número é par, você pode criar uma função `isEven()` e passar o número por parâmetro:

```js
function isEven (number) {
  return number % 2 !== 0;
}
```

Dessa forma, você pode usar tanto `number % 2 === 1` como `number % 2 !== 0`, pois o que vai dar a legibilidade ao código é o nome da função. E lendo o nome da função, fica fácil saber o que ela faz, independente da regra que você usou para garantir isso =)

**Comment by flaviaguterres** [comment]
Certo! Estou ciente sobre a importância da nomenclatura de uma função. Tenho feito comentários no próprio exercício para deixar claras as possibilidades de resolução e ajudar na fixação. Obrigada mais uma vez! :)

**Comment by fdaciuk** [comment]
Perfeito então! Qualquer dúvida, só avisar :D
