### ISSUE TITLE
Challenge - 28 - duvida

### ISSUE THREAD

**Issue by renanssantos1** [da2k/curso-javascript-ninja#5383]
Professor bom dia, estou com uma dúvida sobre o preenchimento do campo, pois no exercicio vc faz da mesma maneira aqui das fotos, mas o meu fica dando esse erro, ja verifiquei no campo e não vi esse caractere que esta pedindo. Ele retorna o endereço correto, mas não preenche os campos. 

**Aparece isso no console**
![screem1](https://user-images.githubusercontent.com/30409223/43838166-f5b1f1fa-9af0-11e8-99a6-8f98fe2a3968.PNG)

**E isso no debbuger;**
![screem2](https://user-images.githubusercontent.com/30409223/43838252-3be54636-9af1-11e8-9060-3851773a3169.PNG)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanssantos1! Esse é um problema com a API do viacep =)

Dá uma olhada [nessa thread](https://github.com/da2k/curso-javascript-ninja/issues/2048) que eu mostro como resolver =)

**Comment by renanssantos1** [comment]
A certo consegui aqui vlw professor 👍

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar =)
