### ISSUE TITLE
Seção 8, aula 46

### ISSUE THREAD

**Issue by leonampd** [da2k/curso-javascript-ninja#5394]
Oi @fdaciuk tudo bem?

Cara, primeiro de tudo tô gostando muito das aulas! A minha dúvida é a seguinte:

```js
function adder(x) {
  return addOther(y) {
    return x +y;
  }
}
```

Como  o javascript trata o valor de `x`? Imagino que o interpretador armazene esse valor de alguma maneira mas não ficou claro o funcionamento disso. Exemplo:

```js
let add = adder(2);

console.log(add(5))
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leonampd! Que bom que tá curtindo as aulas :D 

O nome disso que acontece com o valor de `x` sendo guardado é o que chamamos de `closure`!

Eu dei uma explicação sobre isso nessa issue: https://github.com/da2k/curso-javascript-ninja/issues/2358#issuecomment-349408686

Dá uma olhada se fica mais claro =)

Qualquer coisa me avise que eu complemento a resposta; se por acaso não ficar muito claro, ou se ainda ficar alguma outra dúvida, ok? =)

**Comment by leonampd** [comment]
Oi @fdaciuk brigadão pela resposta. Fez sentido a explicação!

**Comment by fdaciuk** [comment]
Show @leonampd! Qualquer coisa, só avisar =)
