### ISSUE TITLE
Challenge - 31

### ISSUE THREAD

**Issue by renanssantos1** [da2k/curso-javascript-ninja#5436]
Prof bom dia, to quase acabando em :D 

Então estou com a seguinte dúvida, quando crio a linha da tabela de carros, ela ja vem com o botão de remover, mas tentei colocar o evento de um simples console.log, e não funciona, pode me ajudar.

![btn-fail-code](https://user-images.githubusercontent.com/30409223/44341810-6b122600-a45f-11e8-9189-bb4b07a7f34f.PNG)

Logo o resultado fica assim

![btn-fail](https://user-images.githubusercontent.com/30409223/44341834-7c5b3280-a45f-11e8-81ba-54ff15d39669.PNG)

Não sei oq seja, pois ja tentei até mudar o evento 👍 

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @renanssantos1! Que legal \o/
Consegue subir esse projeto no GitHub e me passar aqui o link pra eu testar? Ae já te digo o que pode estar errado =)

**Comment by renanssantos1** [comment]
Acabei de fazer um PR,  esta na branch separada como aprendi com o senhor mestrão :D challenge-31 

https://github.com/renanssantos1/cars-javascript-ninja/pull/2

**Comment by renanssantos1** [comment]
Puts flagrei a parada é como se não existisse o botão, mas fiz umas alterações hoje, reutilizei a função on, criada na lib DOM, como na foto , pois dentro do evento de criação da linha não funcionava o evento. Queria saber se é considerado uma boa pratica essa forma de utiliza-lo no inicio da chamada initEvents.

![code-remove-row](https://user-images.githubusercontent.com/30409223/44441803-d9143580-a5a4-11e8-9d08-fa0d81f488e1.PNG)


De resto esta tudo funcionando normal, ao clicar no botão ele vai removendo as linhas a partir da ultima adicionada. 👍  


![add-car](https://user-images.githubusercontent.com/30409223/44441883-55a71400-a5a5-11e8-90d3-984297a57035.PNG)

![remove-car](https://user-images.githubusercontent.com/30409223/44441895-5cce2200-a5a5-11e8-87e7-6097ce12367b.PNG)

**Comment by fdaciuk** [comment]
Boa prática é desde que você tenha os botões já em tela. Nesse caso, você sempre deixa o botão e vai removendo o último adicionado. Mas e se eu quiser remover o primeiro? Ou algum outro que não seja o último?

Sacou o problema? =)

Cada linha deve ter o seu próprio botão de remover =)

**Comment by renanssantos1** [comment]
A certo, refiz essa parada agora esta funcionando correto, eu estava esquecendo que em um sistema real, era escolhido a linha, não o ultimo de baixo pra cima, vlw mesmo prof 💃

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D
