### ISSUE TITLE
Dificuldade

### ISSUE THREAD

**Issue by ribeiroMarcus** [da2k/curso-javascript-ninja#5527]
Olá professor iniciei ontem o curso de JS e estou tendo um pouco de dificuldade para enviar o desafio aqui pelo git, seria possível outra forma de envio ?
Poderia por exemplo te mandar o código via e-mail.
Desde já obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ribeiroMarcus! Se você não quiser fazer os Pull Requests, não precisa =)
Antes eu usava as informações dos PRs para gerar o certificado, mas agora você consegue gerar assim que finalizar o curso, direto pela Udemy =)

Mas tente apenas resolver de forma local, na sua máquina, para praticar, pois esse é o segredo para alcançar o nível ninja: muita prática :D

E conte comigo se tiver qualquer dúvida :D

**Comment by fdaciuk** [comment]
Oi @ribeiroMarcus! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
