### ISSUE TITLE
Challenge-31

### ISSUE THREAD

**Issue by lefialho** [da2k/curso-javascript-ninja#5555]
Escreva aqui sua dúvida

Fernando, tentei fazer o desafio de apagar a linha da tabela até onde eu deu.

Sei que está totalmente errado, mas é o máximo que consegui. 

Tentei criar uma função para remover, que fosse separada do método createNewCar, porém não funcionou de forma alguma. Outra coisa, é que a não consegui utilizar a lib do DOM pra fazer o método de remover, sendo assim, acabei utilizando o addEventListener diretamente no botão de remover que foi criado. 

Também não consigo remover a linha da tabela específica, pois da maneira que consegui fazer, está removendo sempre a última linha, não importa qual botão seja clicado. 

Aguardo a sua ajuda,

O link é esse: <a href="https://github.com/lefialho/Car-s-store/pull/2/files">Link do projeto</a>

Abraço

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lefialho! Eu testei aqui, e está removendo a linha certa. Consegue me passar em que momento você tem algum problema pra eu tentar reproduzir?

**Comment by lefialho** [comment]
@fdaciuk existem 3 problemas que eu gostaria de resolver:

# 1º 
Não consegui criar um método de remover o botão, separado da função createNewCar(), pois as variáveis estão dentro dessa função de escopo local. Tentei jogar as variáveis para fora do escopo da função createNewCar(), para que fossem acessadas por qualquer função pelo escopo global, porém fazendo isso, parou de funcinar corretamente a função createNewCar().

<img src="https://raw.githubusercontent.com/lefialho/code/master/imagens/Screenshot_1.png">

# 2º
Criei o método de remover o botão diretamente pelo addEventListener, não consegui fazer de uma maneira que aproveitasse a lib do DOM.
<img src="https://raw.githubusercontent.com/lefialho/code/master/imagens/Screenshot_2.png">

# 3°
Não consigo remover a linha específica da tabela. Gostaria que ao clicar no botão, removesse a linha onde está o botão, no entanto, mesmo clicando no botão de linha diferente, remove sempre a última. A figura abaixo ilustra essa situação.
<img src="https://raw.githubusercontent.com/lefialho/code/master/imagens/car-table.png">

Se achar mais fácil pode comentar diretamente nas linhas do código tb.
<a href="https://github.com/lefialho/Car-s-store/pull/2/files">link aqui.</a>

**Comment by fdaciuk** [comment]
Legal @lefialho! Ficou mais clara a sua dúvida agora =)
Vamos lá:

> 1º - Não consegui criar um método de remover o botão, separado da função createNewCar(), pois as variáveis estão dentro dessa função de escopo local. Tentei jogar as variáveis para fora do escopo da função createNewCar(), para que fossem acessadas por qualquer função pelo escopo global, porém fazendo isso, parou de funcinar corretamente a função createNewCar().

A ideia é criar o evento para o botão no momento em que você cria um novo carro mesmo! A única coisa que você poderia melhorar, se quiser isolar essa função, seria:
Ao invés de usar `$tr.parentNode.removeChild($tr)`, você pode colocar **na linha da tabela** o ID do carro, como um `data-plate`, por exemplo, pois ele deve ser único para cada carro (no caso, o ID seria a placa do carro).

Dessa forma, você consegue isolar a função que faz a remoção, passando como argumento apenas a placa do carro, e lá na função que vai manipular o evento de remover o carro, você faz a busca no DOM pela TR que vai ter o `data-plate=SUA_PLACA`, e remove essa TR =)

Sacou a ideia?

---

> 2º - Criei o método de remover o botão diretamente pelo addEventListener, não consegui fazer de uma maneira que aproveitasse a lib do DOM.

Para esse caso não há problema, pois a lib DOM vai tentar pegar elementos do DOM para usar os métodos que criamos nela. Para criar novos elementos em memória (com o `document.createElement`), e então manipular esses elementos, nós precisaríamos fazer algumas adições na lib. Se quiser tentar fazer isso, fique à vontade! Mas não há problema em fazer como você fez =)

---

> 3° - Não consigo remover a linha específica da tabela. Gostaria que ao clicar no botão, removesse a linha onde está o botão, no entanto, mesmo clicando no botão de linha diferente, remove sempre a última. A figura abaixo ilustra essa situação.

Ao fazer o que eu comentei na sua primeira pergunta, você já resolve também esse problema, já que cada linha vai ter um `data-plate` com a placa que deve ser removida. Essa propriedade `data-plate` pode estar relacionada com o botão de remover também: você pode adicionar um `data-plate-button` ou qualquer coisa do tipo no botão, e assim você consegue saber exatamente que, ao clicar em um botão, você "pega" ele através do objeto de evento, checa a propriedade `data-plate-button`, e faz a busca no DOM pela TR que tem essa mesma `data-plate`, saca? Assim você consegue relacionar o botão de remover com a linha que precisa ser removida, sem precisar fazer tudo em uma função só =)

---

Veja se consegue fazer, e me deixe saber se você tiver qualquer dúvida ou dificuldade, ok? =)

**Comment by fdaciuk** [comment]
@lefialho chegou a ver as respostas que eu coloquei?

**Comment by lefialho** [comment]
Vi sim @fdaciuk .

Só não tive tempo ainda de fazer os testes, porque hoje estou agarrado no trampo.
Mas obrigado, assim que eu fizer te dou um retorno se deu tudo certo e agente fecha a issue.

Abraço

**Comment by lefialho** [comment]
@fdaciuk Foi mal, mandei sem querer kkkk

**Comment by fdaciuk** [comment]
ahah! Sem crise xD

**Comment by lefialho** [comment]
@fdaciuk Fiz de uma forma um pouco diferente da que você sugeriu pois achei um pouco complexo, e acabou dando certo. 

Adicionei um ID no tr que recebe os valores do [data-js=plate] e também no botão de remover recebendo o mesmo valor. Só de fazer isso, o $tr.parentNode.removeChild($tr), passou a remover a linha que eu queria, magicamente kk.

Não sei se é considerada uma forma correta de fazer, mas deu certo. Fiz um teste tb, e mesmo tirando do botão os valores do [data-js=plate], ainda continua funcionando, ou seja, bastou apenas adicionar um ID no tr recebendo os valores do plate.

Da uma conferida no código
<a href="https://github.com/lefialho/Car-s-store/pull/2/commits/d992ff53506a4e5a2b5da5bb1ba0429950c9a270"> link </a> 

Se essa forma é correta, gostaria de saber como o botão reconheceu o $tr.parentNode.removeChild($tr) da linha correta apenas colocando o ID no tr. Porque tipo, fiz funcionar sem saber porque funcionou, loucura isso kk..

Vlw aguardo o retorno!

**Comment by fdaciuk** [comment]
Oi @lefialho! Então, como eu tinha dito antes: eu testei seu código, e já estava funcionando xD
Ele já estava removendo a linha correta =)
O único problema de fazer dessa forma que você fez, usando `parentNode` ao invés do ID na TR e no botão, é que, se você modificar qualquer coisa na sua marcação, você quebra seu código.

Fazendo como eu falei, o código JS não depende da marcação HTML =)

**Comment by lefialho** [comment]
Entendi @fdaciuk .
A questão é que eu até consegui adicionar o ID na tr e no botão, no entanto eu não sei como montar a função que detecta pelo id e faça a remoção do botão correto como vc sugeriu. To fraco em js msm rsrs...

**Comment by fdaciuk** [comment]
@lefialho

Lembra que o objeto do evento vem com o target (elemento clicado em `e.target`)? O target é o botão. Ae você pega o valor do atributo `data-plate` desse target, e busca a TR que tem esse mesmo valor no `data-plate`, e faz o remove =)

**Comment by lefialho** [comment]
@fdaciuk 
* No dom está dessa forma:
<img src="https://raw.githubusercontent.com/lefialho/code/master/imagens/Screenshot_4.png">

* não sei se entendi a ideia do e.target, mas fiz assim:
<img src="https://raw.githubusercontent.com/lefialho/code/master/imagens/Screenshot_3.png">

Está correto agora? A linha correta está sendo removida, mas não sei se a lógica é essa mesmo...

**Comment by fdaciuk** [comment]
Na verdade não. Dessa forma você sempre precisa criar a funçãao `handleClick` novamente, a cada novo carro criado, pra ter acesso à `$tr`.

O que eu sugeri foi quase isso =)
É um pouco mais simples:

```js
function handleClick (e) {
  var $trToRemove = $('#' + e.target.getAttribute('data-plate')).get();
  $trToRemove.remove();
}
```

Ou ainda, sem precisar criar a variável:

```js
function handleClick (e) {
  $('#' + e.target.getAttribute('data-plate')).get().remove();
}
```

**Comment by lefialho** [comment]
@fdaciuk  Obrigado cara! Agora entendi a lógica...

Tentei até refatorar um pouco, jogando a função removeCar() pra fora do createNewCar, não sei se está certo..

<img src="https://raw.githubusercontent.com/lefialho/code/master/imagens/Screenshot_5.png">

Meu problema é esse, tenho muita dificuldade com JS, mas quando vejo algo pronto eu consigo entender. O que me arrebenta é criar algo do zero, é quase como pegar uma folha em branco e começar a desenhar sem olhar nada. fica tudo vazio na minha cabeça kkk...

**Comment by fdaciuk** [comment]
Legal cara! Muito bom, é isso ae mesmo =)

> Meu problema é esse, tenho muita dificuldade com JS, mas quando vejo algo pronto eu consigo entender. O que me arrebenta é criar algo do zero, é quase como pegar uma folha em branco e começar a desenhar sem olhar nada. fica tudo vazio na minha cabeça kkk...

Esse processo é super comum, e acontece com TODO MUNDO! O que te faz melhorar nisso é PRATICAR! Praticar MUITO! Só a prática vai te ajudar a entender certos tipos de lógica que você vai perceber - com o tempo e prática - que você pode usar a mesma ideia em vários lugares diferentes =)

Mas para desenvolver isso, é preciso praticar muito! Faça vários pequenos projetos, faça e refaça repetidas vezes, tentando sempre melhorar alguma coisa. Você vai ver como as coisas vão ficando mais simples com o tempo =)

E fique sempre à vontade para perguntar! Estou aqui pra te ajudar =)

Vou fechar a issue, mas se você precisar de qualquer ajuda ainda com esse assunto, só avisar, ok? =)
