### ISSUE TITLE
recursividade

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#5572]
Oi professor! Estou fazendo um exercício sobre recursão e estou em dúvida do que essa função abaixo está fazendo após a 1ª chamada.

```js
function factorial(num) {
  if(num === 0)
    return 1

  return num * (factorial(num - 1))
}

console.log(factorial(4))
```

Na 1ª invocação, o 12 é retornado. Para onde foi esse 12?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! =)

Para fazer recursão, o JavaScript usa um novo contexto para "ir guardando" os valores das chamadas recursivas, até que o último valor seja resolvido, e ele possa ir "voltando" e atribuindo os resultados corretamente até que você tenha um resultado final.

Esse contexto é chamado de **contexto de execução** ou _execution context_.

Aqui tem algumas informações mais detalhadas sobre como tudo isso funciona:
https://javascript.info/recursion

Se ainda tiver alguma dúvida, ou problemas pra entender o artigo em inglês, só avisar :D

**Comment by Roger-Melo** [comment]
Professor, estou estudando o artigo e me veio outra dúvida; porque utilizar funções recursivas? 
Por ser mais elegante que um loop? Legibilidade? 

Ainda não consegui enxergar uma vantagem clara para utilizar a recursão. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Na verdade, funções recursivas são uma feature normalmente encontradas em linguagens puramente funcionais, pois nessas não existe loops, por exemplo. A única forma de fazer iterações é com recursão =)

No caso do JavaScript, pode ser mais simples usar recursão em alguns casos específicos, ao invés de loops.

Um caso em que eu gosto bastante de usar esse modelo é quando eu preciso iterar muitas informações. Dependendo da quantidade de informações, como o `for` - ou qualquer loop e/ou método de iteração em JS - é síncrono, essa ação vai bloquear a thread em que ao JS está rodando até que a iteração termine.

Para esses casos, eu posso, por exemplo, usar uma função recursiva assíncrona, iterando apenas alguns itens a cada x milissegundos (com setTimeout), garantindo assim que a interface nunca fique bloqueada.

Existem algumas outras funções também que são usadas normalmente para fazer animações com JS, que funcionam de forma recursiva, como o [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) por exemplo =)

**Comment by Roger-Melo** [comment]
Ficou mais claro, professor. Agora é estudar o post que vc me indicou até entender de vez essa parada, hahah. Muito obrigado! =)
