### ISSUE TITLE
Challenge-31

### ISSUE THREAD

**Issue by vitorlsouza** [da2k/curso-javascript-ninja#5588]
Olá Fernando, fiz a parte de remover a linha da tabela. Só fiquei em dúvida se fiz alguma má prática.

[link pull request](https://github.com/vitorlsouza/store-car/pull/2)

```js
$buttonRemove.setAttribute('type', 'button');
  $buttonRemove.setAttribute('id', id);
  $buttonRemove.textContent = 'remover';
  $buttonRemove.addEventListener('click', () => this.removeRow(id));
  $tdRemove.appendChild($buttonRemove);
```

```js
removeRow: function removeRow(id) {
      var $button = document.getElementById(id);
      var $tr = $button.parentNode.parentNode;
      $tr.remove();
  }
```

@fdaciuk

**Comment by fdaciuk** [comment]
Legal @vitorlsouza! Mas recomendo fazer de outra forma:
A função `addEventListener` passa para a função que vai manipular esse evento um objeto com várias informações importantes sobre o evento, incluindo o elemento que fez disparar o evento.

Eu mudaria duas coisas no seu código:

**Primeiro:** Ao invés de usar `$button.parentNode.parentNode` na função `removeRow`, você pode fazer o seguinte: no momento em que for criar um carro, você vai criar a linha da tabela e o botão de remover. Nesse momento, você passa um `data-plate` por exemplo, tanto na TR quanto no botão. Dessa forma você relaciona o botão com a TR sem depender especificamente da marcação HTML. Assim, quando clicar no botão, a função que vai ser manipuladora do evento recebe um objeto com os dados do evento, incluindo o elemento que disparou o evento. Nese caso, o botão. Aí então seria só pegar a propriedade `data-plate` do botão, procurar um `tr[data-plate]` que seja igual ao do botão e remover a linha toda, sacou? =)

Se usar `$button.parentNode.parentNode`, e sua marcação HTML mudar - por exemplo, se você colocar mais uma div envolvendo o botão, sei lá - você já vai quebrar seu script, pq vai ter que colocar mais um `.parentNode`. Com o ID na TR e no botão você não tem essa dependência =)

**Segundo:** ao invés de usar uma _arrow function_ no evento apenas para passar o ID para a função `removeRow`, passe só a referência da função `removeRow`, e deixe o `addEventListener` passar para essa função o objeto de evento, para que você consiga fazer o que eu comentei acima =)

**Comment by vitorlsouza** [comment]
Olá Fernando, fiz o refactoring no código conforme sua orientação.
Vê se agora está melhor.

[Link do pull request](https://github.com/vitorlsouza/store-car/pull/2/files)

**Comment by fdaciuk** [comment]
Legal @vitorlsouza, muito bom, é isso ae mesmo =)

Bom, vou fechar a issue, mas se você ainda tiver qualquer dúvida relacionada, só avisar que eu te ajudo, ok? =)
