### ISSUE TITLE
Challenge-32

### ISSUE THREAD

**Issue by vitorlsouza** [da2k/curso-javascript-ninja#5608]
Olá Fernando,

Não sei se utilizei a melhor forma para resolver a atualização da tabela.
Mas vê por favor se fiz alguma má prática.

[Link do pull request](https://github.com/vitorlsouza/store-car/pull/3)

@fdaciuk

**Comment by fdaciuk** [comment]
Legal @vitorlsouza! Se está funcionando, show de bola =)
Tem algumas coisas que dá pra melhorar sim:
- [Essa função](https://github.com/vitorlsouza/store-car/pull/3/files#diff-9be36054379fcd47ab7e2a4c3d639c57R44) poderia ter um nome mais claro do que ela faz, já que ela não "salva" um carro especificamente, mas sim adiciona um evento ao formulário. Poderia se chamar `initEvents`, ou algo do tipo =)

- Usar IDs [dessa forma](https://github.com/vitorlsouza/store-car/pull/3/files#diff-9be36054379fcd47ab7e2a4c3d639c57R134) não é muito legal porque, por mais que o número seja aleatório, ele pode, em algum momento, gerar dois IDs iguais, e isso vai ser um problema. Use a placa do carro como ID, já que a placa deve ser única por carro, que já vai resolver esse problema =)
Lembre-se também que IDs (atributo HTML) criam elementos globais no DOM, então use `data-id` ao invés do atributo `id` para manipular dados no JS =)

- E uma outra dica seria tentar evitar ao máximo o uso do `this`, já que a gente sabe que ele pode mudar, dependendo de como a função é chamada. Como o seu objeto é único, pode usar sempre o `app.` no lugar do `this.` =)

No mais tá legal, dá pra ir evoluindo as coisas aos poucos. Parabéns!
