### ISSUE TITLE
Link grupo no WhatsApp e Telegram

### ISSUE THREAD

**Issue by ricardomirannda** [da2k/curso-javascript-ninja#5624]
Daciuk, boa noite! 
Você poderia passar o link do grupo no WhatsApp e Telegram?

Agradeço desde já !

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Me manda seu e-mail por favor que eu te envio o convite (lá pela Udemy, via DM, pra não deixar público, ok?) =)

**Comment by ricardomirannda** [comment]
Oi @fdaciuk, boa noite! 
Meu email é **ricardomirannda@gmail.com** 

Fico muito agradecido !!!

**Comment by fdaciuk** [comment]
Oi @ricardomirannda! Te enviei o convite do Slack do curso! Editei seu post pra não deixar seu e-mail público, ok? =)

**Comment by fdaciuk** [comment]
=)
