### ISSUE TITLE
Download of files

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-javascript-ninja#5626]
Oi Fernando,

Por favor, veja se pode me ajudar com um assunto que talvez eu possa resolver com JavaScript.

Preciso muito fazer download de centenas de arquivos que estão no site do governo. O SUS contém muitas informações importantes e eu trabalho para o ramo da saúde. Preciso delas.
Para fazer o download eu preciso preencher os parâmetros (SELECT FIELDs) de um formulário e clico em enviar.
Em seguida ele atualiza essa mesma página com novas informações e abre um (TEXT FIELDs) para eu colocar o nome do arquivo e Enviar novamente.
Na última etapa ele gera traz uma outra página com um link para um zip que contém uma lista de arquivos contendo as informações mês a mês, ano a ano e demais filtros que parametrizei anteriormente.

@fdaciuk

**Comment by fdaciuk** [comment]
Entendi. Bom, com JS no browser não acredito que tenha muito o que fazer. O que eu poderia te sugerir é tentar usar uma ferramenta de testes E2E, onde você cria um script que vai navegando nas páginas e clicando nos links que são necessários para o download.

Uma ferramenta que você pode usar pra ver se resolve o seu problema é o https://cypress.io

E no browser que for aberto, você só define que o download vai ser feito sem abrir uma "caixa de diálogo", perguntando onde você quer que seja feito o download: defina no browser um diretório e deixe os downloads acontecerem sempre nesse diretório.

Não sei se é um caminho muito eficaz, mas pode funcionar. Aí é com você pra aprender como funciona a ferramenta e ver se supre a sua necessidade =)

**Comment by victorblevi** [comment]
@Alexandre1202 Acho que você quer fazer um crawler né? você pode usar o [ puppeteer ](https://github.com/GoogleChrome/puppeteer) acho que pode ajudar você.

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
