### ISSUE TITLE
Dúvida sobre certificado

### ISSUE THREAD

**Issue by renanviana** [da2k/curso-javascript-ninja#5629]
Sr. Fernando Daciuk, boa tarde.

Iniciei o curso recentemente e notei que não é necessário efetuar os Pull Requests como era feito no inicio do curso. Desta forma, criei uma branch em meu repositório onde dei o Fork, e nesta branch pretendo por todos os execícios do curso, isso irá dificultar em algo no momento de retirar o certificado do curso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanviana! Não vai não =)
Assim que terminar o curso, você vai conseguir gerar o certificado direto pela Udemy =)

**Comment by fdaciuk** [comment]
Oi @renanviana! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
