### ISSUE TITLE
quokka js

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#5739]
Oi professor! Estou usando essa extensão e gostando bastante. Ela testa grande parte dos valores no próprio editor, sem precisar abrir o terminal. Vc conhece / gosta?  https://quokkajs.com/

P.S.: sou grande fã do terminal e o utilizo bastante também.

@fdaciuk

**Comment by fdaciuk** [comment]
Bacana! Já tinha visto sim, mas não cheguei a testar ainda :D 
Mas parece bem interessante mesmo =)

Vou deixar a issue marcada como tip =)

**Comment by Roger-Melo** [comment]
Show!
