### ISSUE TITLE
Exercício 04

### ISSUE THREAD

**Issue by andersonweb** [da2k/curso-javascript-ninja#576]
No exercício temos que executar esse exemplo que está abaixo. Consegui fazer tranquilamente. Só estou meio equivocado e quero ter certeza se estou certo.

A variável **total** ela é passada para que os **ifs**  tenha os valores atualizado, ou seja soma.

E passamos  `carro.quantidadePessoas += NumeroPessoa;` pois se não cair no ifs ele pega tudo que a variável tem e soma.

Está certo? :smile:
 
```js
carro.adicionarPessoas = function(NumeroPessoa){
	var total = carro.quantidadePessoas + NumeroPessoa;
	if( carro.quantidadePessoas === carro.assentos && total >= carro.assentos) {
		return 'O carro já está lotado';
	}

	if( total > carro.assentos ) {
		var PessoasCabem = carro.assentos - carro.quantidadePessoas;
		var SingularPlural = PessoasCabem === 1 ? 'pessoa' : 'pessoas'; 
		return 'Só cabem mais ' + PessoasCabem + ' ' + SingularPlural + '!';
	}
	carro.quantidadePessoas += NumeroPessoa;
	return 'Já temos ' + carro.quantidadePessoas + ' pessoas no carro!';
};
```
@fdaciuk

**Comment by fdaciuk** [comment]
O `total` ainda não foi adicionado à `carro.quantidadePessoas`. É um valor temporário, para saber se vai ser possível adicionar as pessoas ou não.

Como no `if` tem um `return`, se o valor que seria o total for maior que a quantidade de assentos, ele nem chega a atribuir esse valor à `carro.quantidadePessoas`.

Essa atribuição só é feita se o valor for válido ;)

Ficou claro?

**Comment by andersonweb** [comment]
Só reformulando meu pensando pra ter certeza que está certo.

**Variável total:** Nutri os ifs! Quero dizer com isso que é temporário mesmo. Mas ela só server para os ifs.

**Atribuição final:** Atribui o valor a propriedade `quantidadePessoas`.

Tá tudo ok?! :smile: 

@fdaciuk

**Comment by fdaciuk** [comment]
Isso mesmo! Até para facilitar, daria pra dar outro nome para a variável `total`. Algo como `quantidadeDePessoasQueDeveriamEstarNoCarro`.

Dessa forma, a comparação ficaria bem mais clara:

```js
if( quantidadeDePessoasQueDeveriamEstarNoCarro > carro.assentos )
```

:)

**Comment by andersonweb** [comment]
Bom! Valeu!!! :smile:
