### ISSUE TITLE
Desafio 7

### ISSUE THREAD

**Issue by DaniloAgostinho** [da2k/curso-javascript-ninja#580]
@fdaciuk fiquei em dúvida com relação a seguinte parte do enunciado. 

> Crie uma função chamada `addItem`, que irá adicionar itens no array criado.
A função deverá retornar o array atualizado.

Crie o seguinte: 

```js
function addItem() {
	return myArray;
}
```

Pergunta: Essa função serve apenas para mostrar o array criado ou também já deve adicionar itens no array?. Exemplo.

```js
function addItem() {
	myArray.push('item');
	return myArray;
}
```

Aqui que não entendi direito:

> Adicione um novo array ao array criado no início do desafio, com ao menos 3 itens de tipos diferentes, mostrando o resultado no console.

Pergunta: Aqui eu devo usar o 'push', dentro da função acima ou isoladamente. Fazendo com que essa função adicione e mostre o array atualizado. Exemplos:

```js
function addItem() {
	var addItemArray = myArray.push([undefined, function(){}, {}]);
	console.log(addItemArray);
}
```

Ou seria assim...

```js
var addItemArray = myArray.push([undefined, function(){}, {}]);
console.log(addItemArray);
```
Não sei se me expressei bem, Grato!

**Comment by fdaciuk** [comment]
Fala @DaniloAgostinho!

Então, no enunciado diz que a função deve fazer duas coisas: 

1) Adicionar itens no array criado anteriormente
2) Retornar esse array com os valores atualizados.

Mas como você faz para adicionar novos itens no array, usando uma função? ;)

---

Na sua segunda dúvida, que o próximo exercício do enunciado, você deve usar a função que acabou de criar (`addItem`) para adicionar os itens no array :)

Ficou mais claro agora? xD

**Comment by DaniloAgostinho** [comment]
@fdaciuk entendi. Corrigir o exercício e envie-o. vlw!

**Comment by fdaciuk** [comment]
\o/
