### ISSUE TITLE
Dificuldade de envio via GitHub

### ISSUE THREAD

**Issue by MarcelDusek** [da2k/curso-javascript-ninja#5823]
Fernando, estou com uma dificuldade em clonar o repositório do curso. Não consigo acessar o link do SSH.No meu repositório não aparece a sidebar a direita onde se encontra entre outras coisas , este link. Estou enviando um print. Posso ter feito algo errado. Preciso da sua ajuda. Obrigado, Marcel
![captura de tela 2018-11-13 18 11 48](https://user-images.githubusercontent.com/26858190/48440401-fdc91500-e76f-11e8-92cf-b6d89d50b40d.png)

@fdaciuk

**Comment by MarcelDusek** [comment]
Valeu Robson! Obrigadão!!!

**Comment by fdaciuk** [comment]
Obrigado pela ajuda @robsonribeiros! =)

@MarcelDusek, fique à vontade para enviar ou não os Pull Requests, ok? E sempre que tiver dúvidas, só avisar =)

**Comment by brubriele** [comment]
Oi Fernando e pessoal,

Será que alguém pode ajudar?

Quando tento git clone ele retorna o erro: 
"git: fatal: Could not read from remote repository"

Obrigada!

Abs, 
Bruna

**Comment by fdaciuk** [comment]
Oi @brubriele! Você tá tentando clonar o seu repositório mesmo? Se sim, provavelmente você está tentando clonar com SSH sem ter a chave configurada. Tenta clonar usando HTTPS:


![selection_172](https://user-images.githubusercontent.com/487669/48484435-4975d000-e7fd-11e8-9ed4-00d889c323f9.png)

**Comment by matgoncalves** [comment]
Olá, bom dia!!

Estou atualizando a resolução do meu problema que postei de ontem para hoje (comentário acima).
Consegui pesquisando aqui que era somente eu fazer uma configuração de um usuário mais o email do usuário no Git.

`git config --global user.name "usuário"`
`git config --global user.email "email"`

Através dessa configuração, consegui dar o "push" para subir o arquivo.

OBS: Para quem tiver dúvida igual eu tive, segue o link da minha resolução:
 [https://www.youtube.com/watch?v=YKjPi7Td3ZQ](url)

**Comment by fdaciuk** [comment]
Oi @matgoncalves! É isso mesmo =)

Para o Git saber quem foi o usuário que fez o commit, é necessário configurar essas duas variáveis no seu ambiente =)

Que bom que conseguiu resolver! Qualquer dúvida, só avisar :D

**Comment by fdaciuk** [comment]
Pessoas, vou fechar a issue, mas se vcs ainda tiverem problemas, só avisar que a gente reabre, ok? =)
