### ISSUE TITLE
[Challenge-02] [Erro ao clonar "Could not read from remote repository"]

### ISSUE THREAD

**Issue by brubriele** [da2k/curso-javascript-ninja#5826]
Oi Fernando e pessoal,

Será que alguém pode ajudar?

Quando tento git clone ele retorna o erro:
"git: fatal: Could not read from remote repository"

Obrigada!

Abs,
Bruna

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brubriele! Respondi lá na issue #5823, mas vou colocar a resposta aqui também, ok? =)

---

Você tá tentando clonar o seu repositório mesmo? Se sim, provavelmente você está tentando clonar com SSH sem ter a chave configurada. Tenta clonar usando HTTPS:

![selection_172](https://user-images.githubusercontent.com/487669/48484435-4975d000-e7fd-11e8-9ed4-00d889c323f9.png)

**Comment by brubriele** [comment]
Oi @fdaciuk o mesmo erro agora qdo tento fazer o upstream, tentei com os dois HTTPS e SSH. Fiz tudo de novo e continua dando "Could not read from remote repository" com ssh e https "invalid refspec".

Desculpe pela confusão, primeiro contato com git. :/

**Comment by fdaciuk** [comment]
Oi @brubriele! Consegue me mostrar o comando que você tá rodando pra tentar clonar o repositório? Pode ser algum problema aí =)

**Comment by fdaciuk** [comment]
Só pra eu entender melhor: você está tentando fazer o clone, ou já fez o clone e está tentando fazer push?

**Comment by fdaciuk** [comment]
haha! Legal @brubriele, que bom que deu certo \o/

Se você quiser enviar os Pull Requests dos desafios para pratica e ir acostumando a usar Git e GitHub, pode mandar sem problemas! Mas não é obrigatório! Fique à vontade para fazer como achar melhor =)

E conte comigo sempre que tiver dúvidas =)
