### ISSUE TITLE
Challenge 03

### ISSUE THREAD

**Issue by filipewk** [da2k/curso-javascript-ninja#5830]
fiz usando uma função para chamar a string é correto usar assim?

```js
  function getSex() {
  if( pessoa.sexo === 'masculino' ){
    return 'Olá, eu sou o ';
  } else {
    return 'Olá, eu sou a ';
  }
}
 
function getIdade() {
  if( pessoa.idade === 1 ){
    return ' ano, ';
  } else {
    return ' anos, ';
  }
}
 
function getMetros() {
  if( pessoa.caminhouQuantosMetros <= 1 ){
    return ' metro!';
  } else {
    return ' metros!';
  }
}
 
pessoa.apresentacao = function(){
    return getSex() + pessoa.nomeCompleto() + ', tenho ' + pessoa.idade + getIdade() + pessoa.altura + 'm' + ', meu peso é ' + pessoa.peso + 'Kg,' + ' e só hoje, eu caminhei ' + pessoa.caminhouQuantosMetros + getMetros();
  }
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @filipewk! Te respondi pela Udemy, mas vou responder por aqui também:
Pode fazer dessa forma sim! Só tente deixar em cada função o código referente a exatamente o que ela está fazendo. No caso do `getSex`, pode retornar só `o` ou `a`. Nas outras funções, retorne, só a palavra, sem vírgula, espaços, e ponto de exclamação. Assim, na função `apresentacao`, a frase final vai fazer mais sentido =)

**Comment by fdaciuk** [comment]
Oi @filipewk! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
