### ISSUE TITLE
Aula#06 [while funcionamento]

### ISSUE THREAD

**Issue by tuliomarcos** [da2k/curso-javascript-ninja#5833]
Olá @fdaciuk comprei o curso a pouco tempo mas estou a todo vapor nele, ótimo conteúdo, espero realmente sair um ninja do curso =D

Mas enfim, na aula#06 eu fiquei com duvida em uma parte do funcionamento da estrutura de repetição while, quando eu falo pra ele ir decrementando o valor do contador até enquanto o contador for maior que 0, ele imprime e repete o '1' duas vezes. Gostaria de saber porque isso ocorre

![captura de tela 2018-11-15 as 22 24 47](https://user-images.githubusercontent.com/32531481/48590366-60fca800-e926-11e8-9841-ffd0b31da51e.png)
 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tuliomarcos! Esse é só um efeito colateral do REPL, que, ao final do while, ele exibe o valor da última expressão (que seria o valor final da variável `counter`).

Você pode testar isso colocando uma frase no `console.log`, pra ver que esse 1 não é exibido por causa desse console.log:

```js
var counter = 10;
while (counter > 0) {
  console.log('valor de counter', counter)
  counter--
}
```

=)

**Comment by fdaciuk** [comment]
Oi @tuliomarcos! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
