### ISSUE TITLE
Novas verses do JS

### ISSUE THREAD

**Issue by victorblevi** [da2k/curso-javascript-ninja#5914]
Olá professor, vai ter algum update para as novas features do JS? Como async/await, lambdas etc?
Seria muito bom falar sobre isso, alem disso sobre callbacks arrow functions...

Obrigado, até mais !

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @victorblevi! Vai ter um curso novo falando sobre as novidades da linguagem sim! E o JS Ninja vai ser pré-requisito, pois é necessário saber a base da linguagem antes de entender as novas features =)

Mas vamos ter sim, fique tranquilo :D

**Comment by fdaciuk** [comment]
Oi @victorblevi! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
