### ISSUE TITLE
#Challenge03 

### ISSUE THREAD

**Issue by caiqdaniels** [da2k/curso-javascript-ninja#5939]
Boa noite Fernando ! Pode me ajudar ? Travei na última pergunta do Challenge 03. Já procurei e procurei, mas não encontrei meu erro :( 
No console do node está dando o seguinte erro:

> ReferenceError: apresentacao is not defined at object.pessoa.apresentacao (repl:22:115)

Mas logo no inicio eu já declarei o objeto, segue o código abaixo:

`Só que, antes de retornar a string, você vai fazer algumas validações:
- Se o `sexo` de `pessoa` for "Feminino", a frase acima, no início da
apresentação, onde diz "eu sou o", deve mostrar "a" no lugar do "o";
- Se a idade for `1`, a frase acima, na parte que fala da idade, vai mostrar a
palavra "ano" ao invés de "anos", pois é singular;
- Se a quantidade de metros caminhados for igual a `1`, então a palavra que
deve conter no retorno da frase acima é "metro" no lugar de "metros".
- Para cada validação, você irá declarar uma variável localmente (dentro do
método), que será concatenada com a frase de retorno, mostrando a resposta
correta, de acordo com os dados inseridos no objeto.
*/
pessoa.apresentacao = function () {
    var apresentacaoSexo;
    var apresentacaoIdade;
    var apresentacaoMetrosCaminhados;

    if (pessoa.sexo === 'feminino') {
        pessoa.apresentacaoSexo = 'a';
    } else {
        pessoa.apresentacaoSexo = 'o';
    }
    if (pessoa.idade === 1) {
        pessoa.apresentacaoIdade = 'ano';
    } else {
        pessoa.apresentacaoIdade = 'anos';
    }
    if (pessoa.caminhouQuantosMetros === 1) {
        pessoa.apresentacaoMetrosCaminhados = 'metro';
    } else {
        pessoa.apresentacaoMetrosCaminhados = 'metros';
    }
    
    return "Olá, eu sou " + pessoa.apresentacaoSexo + " " + pessoa.nomeCompleto + "tenho " + pessoa.idade + " " + apresentacao.idade + " " + pessoa.altura + " , meu peso é " + pessoa.peso + " e, só hoje, eu já caminhei " + pessoa.caminhouQuantosMetros + " " + pessoa.apresentacaoMetrosCaminhados + "!";
}`

Não sei se coloquei da maneira correta, é minha 1ª vez abrindo issue no github rs

Agradeço desde já :)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @caiqdaniels! Colocou a dúvida certo sim haha :D 
Bom, pelo erro, está dizendo que você está tentando acessar a função `apresentacao` usando `object.pessoa.apresentacao`. É isso mesmo?

Se for, o problema é só esse `object.` no começo. De onde ele veio? =)

**Comment by fdaciuk** [comment]
Oi @caiqdaniels! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
