### ISSUE TITLE
[Aula 21] Dúvida sobre o Event-loop !

### ISSUE THREAD

**Issue by ruanvalente** [da2k/curso-javascript-ninja#5949]
Fala mestre tudo bom ? Na Aula 126 na semana da **Aula-21** você fala um pouco sobre **Sync e Async** dentro do Javascript e fala sobre o **Event-loop**.

O conceito do Event-loop não ficou muito claro pra mim, poderia me explicar melhor como funciona esse trem ? rsrs. Abraços!!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ruanvalente! Vamos lá =)

Bom, basicamente quando escrevemos códigos JavaScript, esse código é síncrono, ou seja: todos os "comandos" serão executados um após o outro, mantendo a ordem.

O problema de escrever dessa forma síncrona o tempo todo é que o JavaScript roda em uma única thread do procesador. Se nós precisarmos, por exemplo, fazer qualquer ação que demore para ser finalizada - um loop em um array gigante, por exemplo - essa thread vai ficar bloqueada até que a ação termine.

E por "bloquear a thread" entenda o seguinte: imagine você navegando em um site na web: hoje os navegadores conseguem criar uma thread por aba, para que o código JavaScript que estiver rodando naquela aba não interfira nas outras.

Mas pense na situação onde você visita um site qualquer - Youtube, por exemplo - e lá ele vai exibir todos os vídeos do site de uma só vez, fazendo um loop por um array que contém as informações dos vídeos e então, de forma síncrona, exibindo esses vídeos na tela.

Você não precisa ver todos os vídeos do Youtube listados ao mesmo tempo, concorda? E se o Youtube realmente fizesse isso, enquanto todos os vídeos não estivessem exibidos, você não conseguiria navegar no site. A thread estaria ocupada renderizando aquele código síncrono, e você não conseguiria sequer clicar para abrir algum vídeo, rolar a tela, ou mesmo ver um efeito de "hover", já que todo o recurso daquela thread estaria sendo usado pelo JavaScript.

É aí que entra código assíncrono e o event loop: quando nós escrevemos algum código assíncrono no JavaScript, nós delegamos ao sistema operacional aquela carga de processamento. O event loop não fica rodando na mesma thread que a aplicação JavaScript está rodando, por isso qualquer coisa que tenha sido delegada para o event loop não vai bloquear a thread principal que o JS está rodando =)

Então normalmente delegamos ações como: eventos, requests, leitura de arquivos (no caso do Node.js), etc. Essas são ações "pesadas", que demoram para ser executadas. Então quem vai cuidar dessas ações vai ser outra thread, não a _main thread_ - que seria a thread principal, rodando a aplicação JS.

Agora explicando um pouco sobre o event loop: imagine que o event loop é um recurso circular, onde o JS vai delegar alguns eventos pra ele em alguns momentos (como nos exemplos que eu dei anteriormente).

Na linguagem em si, sempre que precisamos delegar algo para o eventloop - ou escrever código assíncrono - nós precisamos criar uma função para dizer ao event loop:

_Event loop, assim que essa ação for completada, você executa essa função aqui!_

Lembra do `setTimeout`? Ele serve para delegar ações para o event loop, e tirar o "peso" da thread principal.

Quando usamos um código assim:

```js
setTimeout(function () {
  console.log('essa mensagem vai aparecer só depois de 1 segundo, de forma assíncrona')
}, 1000)
```

O que estamos fazendo é dizer ao event loop o seguinte:

_Event loop, quando passar 1 segundo, se você já tiver terminado de fazer tudo o que você tem pra fazer - ou seja, o mais rápido possível após esse 1 segundo -, execute a função que foi passada via argumento para o `setTimeout`._

Pode acontecer de, ao se passar 1 segundo, o event loop ainda pode estar liberando algum código, então a função pode demorar pouco mais de 1 segundo para executar, mas ele vai aguardar pelo menos 1 segundo para então executar a função, e o código dentro da função vai ser executado na _main thread_, passando novamente o controle daquele código para o JavaScript =)

Deu pra entender melhor a ideia? =)

**Comment by ruanvalente** [comment]
Perfeitamente mestre, muito obrigado pela aula. Estou estudando um pouco mais essa parte, para fixar ;) agora ficou muito mais claro !!

:)

**Comment by fdaciuk** [comment]
Show de bola! Qualquer dúvida, só avisar :D
