### ISSUE TITLE
Challenge 28 mensagem de erro não aparece

### ISSUE THREAD

**Issue by ThalesAlonso** [da2k/curso-javascript-ninja#6013]
Bom dia Professor, minha aplicação do challenge 28 ta funcionando, porém quando digito um cep inválido a mensagem de erro não aparece. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ThalesAlonso! Na aula 28, antes do último vídeo, tem um documento explicando exatamente esse problema =)

É a "Lecture 171". Dá uma olhada lá, e se tiver qualquer dúvida, pode comentar aqui, ok? =)

**Comment by ThalesAlonso** [comment]
valeu professor.

**Comment by fdaciuk** [comment]
Se tiver qualquer dúvida, só avisar :D

**Comment by fdaciuk** [comment]
Oi @tbthiago2! Não se preocupe! Não é necessário mais enviar os desafios, ok? Apenas tente fazer na sua máquina, que já está ótimo! O importante é praticar!

E sempre que tiver dúvidas, por favor, abra uma nova issue, acessando o repositório do curso:
https://github.com/da2k/curso-javascript-ninja

Clique na aba "Issues";

E clique no botão "New issue".

Não hesite em perguntar sempre que tiver dúvidas, ok? =)
