### ISSUE TITLE
Exercício #10

### ISSUE THREAD

**Issue by andersonweb** [da2k/curso-javascript-ninja#602]
Bom no exercício a gente vem criando uma calculadora. Sei que cada qual tem sua abordagem. Queria saber o que você acha da minha, pois não ficou igual a tua. No meu ponto de vista, ficou mais fácil de ler e um fácil entendimento.
```js
number1 = 50;
number2 = 30;
calculator( number1, number2 );

console.log( 
	showOperationMessage( operationSignal, number1, number2 ), 
	sum !== false ? sum( number1, number2 ) : showErrorMessage( operationSignal )  
);
 ```

Eu penso que, essa abordagem pode prejudicar a peformace, sei lá...  Porque vou reescrevendo as variáveis em outros exemplos..

O método que tu utilizou, colocando as variáveis e valores dentro do `if` a peformace aumenta? As variáveis está em um escopo local? 

E enfim, o que tu acha da abordagem... Pra mim ficou linda :smile: 
Abs!!! @fdaciuk

**Comment by brunotortelli** [comment]
cara eu tentei usar ternário também, mas por exemplo no teu código o showOperationMessage vai aparecer independente de qualquer coisa, sendo que, caso sum seja false, o único retorno do console.log seria a mensagem de erro mesmo. no seu código caso o operador seja false, o console vai retornar showOperationMessage e a showErrorMessage, espero ter ajudado.

**Comment by andersonweb** [comment]
@brunotortelli show, acabei de fazer um teste aqui e você está certo. Só não entendi o porque na verdade. @fdaciuk ajuda noix!!!

Valeu demais @brunotortelli ajudou bastante cara.

**Comment by fdaciuk** [comment]
@andersonweb, a ideia do exercício é mostrar uma frase, dentre duas possibilidades. Se os parâmetros criados para o cálculo estiverem ok, vai mostrar a mensagem:

```console
A operação 1 + 2 = 3
```

Que é o resultado da função `showOperationMessage()` e da função da operação (`sum`, `multiply`, etc).

Agora, se for passado um operador que não existe, então o resultado vai ser:

```console
Operação "lalal" não permitida!
```

---

No seu exemplo, o que vai retornar é o seguinte:

Com a operação correta:

```console
A operação 1 + 2 = 3
```

Já se tiver algum erro na operação:

```console
A operação 1 lala 2 = Operação "lala" não permitida!
```

Entendeu? Como você está colocando a condição para mostrar ou não somente o resultado de `sum` ou a mensagem de erro, a mensagem da operação sempre vai aparecer =)

---

Mas assim.. da forma como eu mostrei não é pra ser uma regra. Simplesmente foi uma definição para **esse exercício** em específico. 

Eu defini que: 

1. Ou vai ser mostrado a operação e o resultado da operação; ou
2. Vai ser mostrado uma mensagem de erro.

Em uma aplicação real, você deve saber o que sua aplicação precisa mostrar ou não, para fazer a condição no momento correto. Não se apegue a regras. Quem faz as regras da sua aplicação é você =)

**Comment by andersonweb** [comment]
Show! Entendido! :smile:
