### ISSUE TITLE
Funcionamento do GIT

### ISSUE THREAD

**Issue by theleoad** [da2k/curso-javascript-ninja#6035]
Fernando, mesmo que você não esteja mais fazendo as correções eu acho importante para meu aprendizado fazer os exercícios e postar aqui no Github. Mas sinceramente não tenho certeza se estou fazendo da maneira correta. 
Na verdade desde desde o desafio 6 toda vez que abro um pull request, todos os anteriores aparecem também.
Será que poderia só olhar se está correto?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @theleoad! Esse problema que você está vendo acontece por, pelo menos, dois motivos:
- ou você está fazendo commits direto na master do seu repositório, e ao criar uma nova branch com base na master, essas alterações vão junto;
- ou você está criando as novas branchs com base no desafio anterior. Exemplo: você está na branch `challenge-06`, resolve o desafio, commita, e ao invés de voltar para a master e criar a branch `challege-07`, você faz direto da branch `challenge-06` =)

Deu pra entender a ideia? =)

**Comment by fdaciuk** [comment]
Oi @theleoad! Vou fechar a issue, mas se vc ainda tiver problemas, só avisar que a gente reabre, ok? =)
