### ISSUE TITLE
Atualizar aula Desafio da semana#01

### ISSUE THREAD

**Issue by Matheuskbrasil** [da2k/curso-javascript-ninja#6062]
Favor atualizar a aula com  as orientações de como dar um pull request. Pois perdi mais tempo procurando o novo caminho, do que propriamente codando.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Matheuskbrasil! Tudo bem? =)

Muito obrigado pela dica! Já deixei um artigo com algumas instruções antes do vídeo do desafio, na primeira aula.

Isso vai ajudar quem está chegando agora a não se perder na hora de tentar enviar um desafio!

Muito obrigado pelo seu feedback, e conte comigo para o que precisar :heart:
