### ISSUE TITLE
Dúvida sobre aula de nomear funções // Seção 8, aula 45

### ISSUE THREAD

**Issue by gugaah** [da2k/curso-javascript-ninja#6069]
Olá Fernando, tudo bem?
Minha dúvida pode parecer um tanto quanto boba visto que estou fazendo o curso agora no final de 2018 então acredito que possam ter havido atualizações referentes a isso.
A dúvida é o seguinte: nomear funções que serão atribuídas a alguma variável é totalmente válido devido as questões de debug e também para fins de organização e manutenção do código, porém percebi que mesmo não nomeando a função que será atribuída a uma variável qualquer, a propriedade name funciona quando invoco o nome da variável.propriedadeName e ele retorna o nome da variável. Testei no console do nodeJS.
Obrigado, Gustavo!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gugaah! Sim, hoje os browsers fazem essa atribuição de forma automática: se a função é anônima, ela recebe o nome da variável à qual ela foi atribuída =)

**Comment by gugaah** [comment]
Obrigado pelas explicações.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
