### ISSUE TITLE
Challenged 10 - Função isOperatorValid

### ISSUE THREAD

**Issue by Hamiltonspjunior** [da2k/curso-javascript-ninja#6128]
Olá, Professor. 
Acabei de fazer o challenge 10 e gostei bastante porém fiquei com uma dúvida. 
Na função isOperatorValid nos é pedido que verifique se o operador passado é válido ou não retornando true ou false e que façamos isso sem usar if ou switch. 
A solução foi: 

return !!operation[operator]; 

Isso não é ruim pelo fato da função ficar dependendo do objeto operation? 
Por exemplo, se caso eu precisasse usar essa função em outra parte do código não seria possível pois ela só funciona se a calculadora for implementada com o objeto operation. Se fosse feita de outra forma ela não funcionar.

Obrigado e Feliz ano novo. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Hamiltonspjunior!

Sim, esse é um ponto importante de atenção :)

Para esse desafio em específico, essa função vai ser usada somente nessa parte do código. Mas normalmente, quando precisamos isolar uma função mais genérica, nós podemos passar todos os valores que essa função vai usar via argumento.

Mas assim: não se prenda tanto a isso. Não é necessário prever que uma função vai ou não ser reutilizada no futuro.

Sempre que você for trabalhar em um projeto, você vai escrever funções para a sua necessidade naquele momento.

Se uma hora você perceber que vai precisar reescrever o mesmo código, aí sim é o momento de abstrair para reutilizar =)

**Comment by Hamiltonspjunior** [comment]
Entendi. Muito obrigado professor.

Em sáb, 29 de dez de 2018 21:42, Fernando Daciuk <notifications@github.com
escreveu:

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
