### ISSUE TITLE
challenge-08 rodar arquivo JS

### ISSUE THREAD

**Issue by ifermino** [da2k/curso-javascript-ninja#6143]
Boa tarde, Fernando.

Gostaria de rodar um arquivo .js pelo Node.js. Meu ambiente é windows 10 e estou com dificuldade. Tentei com as 3 opções abaixo e não tive sucesso: 

`node D:\Documentos\Conhecimento\Cursos\Udemy\JS Ninja\challenge-08.js`
`SyntaxError: Unexpected identifier`

`node "D:\Documentos\Conhecimento\Cursos\Udemy\JS Ninja\challenge-08.js"`
`SyntaxError: Unexpected string`

`node 'D:\Documentos\Conhecimento\Cursos\Udemy\JS Ninja\challenge-08.js'`
`SyntaxError: Unexpected string`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ifermino! Tente entrar no diretório que está o arquivo JS, e rodar o comando `node challenge-08.js` ali dentro. 

Esse problema que você está tendo pode ter dois motivos:
- o primeiro é por conta dos espaços em branco no nome dos diretórios sem escapar (na verdade, se for mesmo isso, ele deveria dar outro erro);
- se não for isso, pode ser algum erro de sintaxe mesmo no arquivo. Qual o conteúdo desse arquivo `challenge-08.js`?

**Comment by fdaciuk** [comment]
Legal @ifermino! Que bom que deu certo =)
Qualquer coisa, só avisar :D
