### ISSUE TITLE
Funções 'handle' e eventos em formulários

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-javascript-ninja#6144]
Olá, professor! 

Tenho um form em que o valor que o user entrar no input 'birthday' irá desencadear a adição de outros inputs no form. Estava pensando em fazer o seguinte: declarar uma função `handleBirthDate`, que irá ser o callback de um evento `keyup` atrelado ao input 'birthday'. Tipo isso: 

```javascript
function handleBirthDate () {
  // if (isUserAgeEqualOrGreaterThanEighteen())
    // insertCNHInputsOnForm()
  // se não, insertParentInputsOnForm()
}
```

É um bom caminho? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Pode seguir esse caminho sim =)

**Comment by Roger-Melo** [comment]
Show, professor. Obrigado!
