### ISSUE TITLE
Duvida ao fazer "Pull Request"

### ISSUE THREAD

**Issue by dioliveira84** [da2k/curso-javascript-ninja#6147]
Boa tarde! Acho q durante os challenges iniciais fiz algum pull request de forma errada ... todo novo pull request q tento submeter  vem com 3 linhas de commits passados que fiz em Nov e Dez´18. 

Como tirar essas 3 linhas de meus futuros pull requests? 

Obrigado, 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @dioliveira84! Eu respondi essa dúvida [aqui](https://github.com/da2k/curso-javascript-ninja/issues/6035#issuecomment-446942086), dá uma olhada =)

**Comment by fdaciuk** [comment]
Oi @dioliveira84! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
