### ISSUE TITLE
Duvida sobre declara objetos e recomendação de livro

### ISSUE THREAD

**Issue by bygabrielantunes** [da2k/curso-javascript-ninja#6184]
Professor pra declara um objeto é necessário atribui-lo a uma variável ? ou pode ser objeto = { ... } ? eou precisa ser:  **var** objeto = { ... } ?

E por ultimo, quais livros sobre js vc me recomendaria ? 

desde ja obrigado, muito boa suas aulas.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @bygabrielantunes! No seu primeiro exemplo, você já está atribuindo o objeto a uma variável, mas não está **declarando** a variável. Isso é uma má prática. Sempre declare as variáveis que você for utilizar, usando a palavra chave `var` =)

Nas novas versões do JavaScript, existem outras duas formas de declarar variáveis (`let` e `const`), mas você pode continuar usando `var` até o final do curso, para entender bem toda a base da linguagem. 

Ao finalizar o curso, você já pode estudar sobre as novidades que vieram com ES6, ES7, etc =)

Sobre os livros, depende do seu objetivo.

Dos livros que eu li, eu recomendaria "O Guia definitivo", e "Os segredos do Ninja JavaScript". Os dois são muito bons, mas boa parte do conteúdo deles eu já abordo no curso =)

**Comment by fdaciuk** [comment]
Oi @bygabrielantunes! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
