### ISSUE TITLE
Dúvida sobre o ";"

### ISSUE THREAD

**Issue by GugaDavi** [da2k/curso-javascript-ninja#6237]
Boa Noite Daciuk,

Cara, antes de mais nada, parabéns pelo trabalho. Sem desmerecer seus colegas, mas o seu é o terceiro curso de JS que compro, e finalmente, acredito, que estou criando uma base solida. Comecei agora, mas vamos lá.

Queria tirar uma dúvida sobre o uso do ";" em outro curso que fiz o instrutor dizia que o ";" era opcional. E em outro curso dizia que era opcional, mas recomendado. Como eu venho do Python, lá quase não usa, dai estou tendo um perrengue danado para me acostumar, mas me diz, é mesmo necessário ou não?

Estou querendo tirar essa dúvida porque quero me habituar a codar da forma que o mercado faz, pra quando entrar nele, ser menos uma coisa para se acostumar.
Aguardo tua resposta.

Abraço.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @GugaDavi! Obrigado por abrir a issue aqui =)

Fico bastante feliz em saber que o curso está te ajudando :D 

O JavaScript tem uma feature chamada "ASI" (_Automatic Semicolon Insertion_, ou _Inserção Automática de ponto-e-vírgula_).

Por esse nome, é possível deduzir que ponto-e-vírgula na linguagem é opcional; já que essa feature existe, o JS coloca o ponto-e-vírgula automaticamente onde precisa, certo?

E a resposta é: **mais ou menos!**

Essa feature segue algumas regras, então para deixar de usar ponto-e-vírgula com segurança na linguagem, é importante conhecer **todas** essas regras =)

Como você está começando agora com a linguagem, recomendo que **use sempre** o ponto-e-vírgula.

Mais para o final do curso, vamos falar sobre uma ferramenta chamada "linter", que te ajuda a evitar "problemas" no seu código, como: variáveis não utilizadas, manter um estilo de código bem definido, etc.

E isso inclui avisar também quando é ou não necessário o uso do ponto-e-vírgula =)

Então assim: enquanto você está aprendendo a linguagem, e entendendo o que ela é ou não capaz de fazer, use o ponto-e-vírgula, para evitar surpresas.

Depois que chegar na parte onde vamos falar sobre o linter, você decide se usa ou não ponto-e-vírgula, ok?

Mas já adianto que é questão de gosto: tem gente que prefere usar, tem gente que prefere não usar.

Se o seu caso for a preferência por não usar, desde que você tenha essa ferramenta de lint bem configurada, ela vai impedir que você faça besteira no código, e você poderá deixar de usar com segurança =)

Espero que tenha ficado claro, e fique à vontade para perguntar sempre que tiver dúvidas =)

**Comment by GugaDavi** [comment]
Vlw Cara! Vou tentar me habituar então.

Abraços

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar =)
