### ISSUE TITLE
Acesso as aulas 31, 32 e 33

### ISSUE THREAD

**Issue by lucasmaiaesilva** [da2k/curso-javascript-ninja#624]
Boa noite @fdaciuk, notei que existem 2 novos desafios, 31, 32 e 33, porém nos links que me foram enviados, apenas constam acesso até a aula 30, está correto, seria possível me enviar o acesso a essas aulas?

**Comment by fdaciuk** [comment]
Opa, tudo certo @lucasmaiaesilva? xD

Cara, você usa gmail né? Dá uma olhada se os e-mails não caíram em SPAM ou na aba "Promoções". Normalmente e-mails do Mailchimp caem lá =(

Mas arrastando pra aba "Entrada", eles começam a cair na sua caixa de entrada normalmente =)

Verifica lá, e se não tiver chegado mesmo, eu te reencaminho, pode ser? :)

**Comment by lucasmaiaesilva** [comment]
Já vi aqui, valeu!

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida me avise :D
