### ISSUE TITLE
Erro de permissão na hora de clonar o git

### ISSUE THREAD

**Issue by hargentoni** [da2k/curso-javascript-ninja#6305]
E ai pessoal, blz?
Estou tentando clonar o meu git. A chave publica dele já foi gerada e copiada para o git. Porém, continua dando o mesmo erro se liguem ai no erro:

sudo git clone git@github.com:hargentoni/shellscript.git
[sudo] password for hargentoni: 
Your password will expire in 4 day(s).
Cloning into 'shellscript'...
**ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights**

Podem me ajudar por favor? Minha distro do linux é Fedora 26

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hargentoni! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
