### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by Hamiltonspjunior** [da2k/curso-javascript-ninja#6336]
Boa tarde, Professor. 
Eu assisti a aula sobre objetos e protótipos mas ainda não ficou muito claro para mim essa questão dos prototypes.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Hamiltonspjunior! Consgue me dizer o que você não entendeu dos prototypes, e em qual aula você viu, que não ficou claro o assunto?

Só pra eu conseguir entender melhor a sua dúvida, e conseguir te ajudar :D

**Comment by fdaciuk** [comment]
Oi @Hamiltonspjunior! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
