### ISSUE TITLE
Dúvida desafio #20

### ISSUE THREAD

**Issue by gugaah** [da2k/curso-javascript-ninja#6431]
Fernando, tudo bem?

Gostaria apenas de verificar, referente ao desafio #20, na parte onde validamos se o usuário informa um nome de usuário. Quando é realizada a pergunta e cancelamos, ele grava na variável a informação de que o usuário é "Desconhecido" o que poderia ser considerado um nome, certo?. Então, no EventListener eu coloquei ( $inputUsername.value === 'Desconhecido' ), dessa forma ele avisa para o usuário que o mesmo não digitou um usuário válido. Se apenas negarmos o !$inputUsername.value ele considera o Desconhecido como um nome válido. Esta correta essa observação?

As aulas estão muito boas, estou aprendendo demais! Muito obrigado! :)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gugaah! Tudo ótimo, e contigo? =)

Então, na verdade, deixando o código como fizemos, ele nunca vai entrar no `if` do username mesmo =)

Essa forma que você fez é uma forma de resolver, mas o "estar correto" ou não é relativo, pelo seguinte motivo: O usuário pode não querer passar o nome verdadeiro, então ele pode ficar como "Desconhecido" mesmo, ou algo do tipo.

Poderíamos também não deixar um nome setado por padrão, caso o valor no `prompt` não tenha sido preenchido, deixando a cargo do usuário preencher o nome, ou deixar em branco, ou ainda preencher com um nome fake qualquer.

O ponto chave nesse caso é: não existe uma forma correta de resolver isso, apenas abordagens diferentes, dependendo do objetivo da sua aplicação =)

Fico feliz que você está curtindo! Qualquer dúvida, só avisar :D

**Comment by fdaciuk** [comment]
Oi @gugaah! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
