### ISSUE TITLE
Dúvida no Desafio #07

### ISSUE THREAD

**Issue by didiraja** [da2k/curso-javascript-ninja#6445]
Olá Daciuk, tô conseguindo acompanhar tranquilamente o curso. Conclui este desafio, mas na resolução do último exercício me bateu uma dúvida:

**Dessa maneira funciona tranquilamente.**
```
console.log( 'Números ímpares entre 111 e 125:' );
for (i = 111; i >= 111 && i <= 125; i++) {
  if (i % 2 !== 0) console.log(i)
}
```
**Mas dessa aqui, o console não retorna nada (undefined).**
```
console.log( 'Números ímpares entre 111 e 125:' );
for (i = 100; i >= 111 && i <= 125; i++) {
  if (i % 2 !== 0) console.log(i)
}
```

Por quê a diferença nas respostas?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @didiraja! O problema é o resultado da expressão passada para o `for`: 

```js
for (i = 100; i >= 111 && i <= 125; i++) {
```

Veja que você inicia o valor de `i` com `100`, mas diz que ele deve entrar no `for` **enquanto** o valor de `i` for **maior ou igual** a `111` **E menor ou igual** a `125`. Ou seja: para entrar no `for`, as duas expressões precisam ser verdadeiras.

Como a primeira expressão é falsa (`i` não é maior ou igual a `111`), então ele nem entra no `for` :)

Ficou claro? =)

**Comment by didiraja** [comment]
Aaaahhh, podes crer. Compreendido, valeu!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
