### ISSUE TITLE
Dificuldade é normal?

### ISSUE THREAD

**Issue by jhenrique-dev** [da2k/curso-javascript-ninja#6464]
Fernando, tudo bem? 
Estou na aula 23 realizando o desafio, consegui fazer pelo menos metade do que foi pedido só que depois travei.
Nos outros desafio senti algumas dificuldades e em pelo menos uns 3 exercicios travei também na resolução, de resto consegui resolver.
É normal travar assim ? 
Entendo que pode ser minha lógica também.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhenrique-dev! É normal sim! E a solução pra isso é a prática!

Você melhora seu raciocínio lógico, quando você começa a conhecer melhor as possibilidades, quando começa a entender os problemas, e aprende as várias formas de resolvê-los.

Por isso eu sempre bato na tecla de praticar muito! Se sentiu dificuldade em algum desafio, faça e refaça quantas vezes forem necessárias, até que fique claro pra você conteúdo!

E de tempos em tempos (um, dois ou até de três em três dias) volte e tente refazer aquele desafio que você tinha dificuldades.

É com repetição e prática que a gente aprende, ok? :D 

É um processo super normal! Siga estudando e praticando, e pergunte sempre que tiver dúvidas. Estou aqui pra te ajudar =)

**Comment by jhenrique-dev** [comment]
@fdaciuk , muito obrigado pelo preve retorno.
Irei praticar muito, não havia pensado em refazer o desafio, ótima dica

**Comment by fdaciuk** [comment]
Show de bola! Qualquer coisa, só avisar :D
