### ISSUE TITLE
Dica para Estudos

### ISSUE THREAD

**Issue by MarksPro** [da2k/curso-javascript-ninja#6485]
Então professor eu só preciso de uma dica, eu vi que até a aula 14 tem um conteúdo para trabalhar firme com a parte logica, eu me engasguei em 3 ou 2 exercícios, minha ideia é chegar na aula 14 - OBS "estou na aula 12" e voltar a fazer o curso de novo, claro em um ritmo mais acelerado, e fazendo os exercicios de novo, até realmente eu entender oque tudo faz, sem precisar me consultar com você ate mesmo procurar fontes por ai.
acha que estou exagerando recomeçar o curso já, para avançar para o browser ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MarksPro! Na verdade, tudo vai depender do seu tempo disponível, e do seu objetivo :)
O que eu recomendaria você fazer é:
- assista as aulas;
- tente resolver o desafio sozinho;
- se travar, assista à correção;
- faça a correção junto comigo;
- apague e tente fazer novamente algumas vezes, até perceber que ficou claro;
- passe para a próxima aula.

De tempos em tempos (um, dois ou até de três em três dias), volte nos desafios que você sentiu dificuldades, e tente refazê-los novamente, sozinho, pra ver se você realmente entendeu o problema e sabe como resolvê-lo.

Essa prática vai ajudar a gravar o conteúdo na sua mente =)

O importante é sempre estar praticando! E pergunte sempre que tiver dúvidas! Estou aqui pra te ajudar =)

Consulte outras fontes também, se você acha que isso pode te ajudar. Mas o mais importante é sempre PRATICAR! É a prática que vai te fazer entender os problemas e aprender de verdade =)

E dica de ouro: se você usa, evite autocomplete no seu editor enquanto estiver aprendendo uma linguagem ou ferramenta. Digite TUDO! Assim é muito mais fácil gravar os comandos :D 

Quando você estiver mais confortável, aí sim você poderá voltar a usar o autocomplete, ok? =)

**Comment by fdaciuk** [comment]
Oi @MarksPro! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
