### ISSUE TITLE
Alterei a branch Master

### ISSUE THREAD

**Issue by Julyemerson** [da2k/curso-javascript-ninja#6510]
Olá professor, tudo bem?
Então, enquanto eu fazia os exercicios do challenge-03 eu percebi que alterei a branch Master com os desafios do challenge-02 como eu posso fazer para retornar ao estado original? 

Ps. Estou no challenge-03

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Julyemerson! Tudo certo, e contigo? =)

É bem simples de resolver isso: acesse a sua branch master local, e copie os arquivos que você precisa voltar diretamente da branch master do repositório do curso:
https://github.com/da2k/curso-javascript-ninja

Depois de feito isso, faça o commit na sua master, e ela deve estar limpa novamente :)

**Comment by fdaciuk** [comment]
Oi @Julyemerson! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que a gente reabre, ok? =)
