### ISSUE TITLE
Desafio da semana #2

### ISSUE THREAD

**Issue by fabianogosilva** [da2k/curso-javascript-ninja#6583]
Fala professor bom dia!  cara estou com algumas dúvidas em relação ao entendimento do processo. no desafio 1 foi tranquilo... porem no desafio 2 .. fiquei um pouco travado nos 2 últimos exercícios onde foi preciso criar as funções.. fiquei extremamente perdido e não consegui enxergar a solução... não fiz os exercícios. 

porem nos exercícios anteriores a esses.. eu fiz.. mas de uma forma diferente da proposta na correção.. tanto é que deixei direto no exercício.. a forma q fiz e a correção do professor para você dar uma olhada em como eu estou pensando e escrevendo os códigos...  preciso que me ajude a entender pq estou pensando dessa forma.. quando a solução é simples.... hahaha.    e como prosseguir para compreender melhor o processo. 

```js
 function dados(a, b, c){
    if(a === "" || b === "" || c === "" ){
        var res = "Preencha todos os valores corretamente!";
        return  res;
    } else {
        var res2 = a*b*c;
        res2 += 2;
        return res2;
    }

}

//correcao professor
function novosValores(a, b, c){
    if(a === undefined || b === undefined || c === undefined){
    return "Preencha todos os valorers corretamente!";
    }else{
        return (a*b*c) + 2;
    }
}
```

OK!  espero que entenda ... desculpe alguma coisa.. e quero muito ser ninja em JS. 

Obrigado. 

@fdaciuk

**Comment by rafaelnoronha** [comment]
@fabianogosilva 

Não sei se entendi sua dúvida, más vou tentar ajudar :smile: 
```js

function dados(a, b, c){
if(a === "" || b === "" || c === "" ){  // Existe uma diferença entre '', null, e undefined. '' é como se fosse uma string vazia, null é como se fosse 'nenhum valor (mesmo null sendo um valor)' e undefined é valor indefinido, inexistente, quando não é fornecido nada  
var res = "Preencha todos os valores corretamente!";
return res;
} else {
var res2 = a_b_c; // Aqui você poderia ter pegado a mesma variável res e ter sobrescrevido ela. Confere se colocou o operador de multiplicação '*' mara multiplicar os valores de a, b e c.
res2 += 2;
return res2;
}

}

```

**Comment by fdaciuk** [comment]
Obrigado pela ajuda @rafaelnoronha! =)

Oi @fabianogosilva! A ideia seria essa mesma que o @rafaelnoronha comentou: quando você testa algum valor por `''`, você está verificando se foi passada uma string vazia. String é um tipo de dado, então pra chegar uma string vazia, esse dado tem que ser explicitamente passado como parâmetro para a função.

É como se executássemos a função assim:

```js
dados('', '', '')
```

No caso de passar os 3 valores como strings vazias :)

Por isso testamos por `undefined`, que pode ser um valor passado, mas também significa "ausência de valor". Quando você não passa um valor via parâmetro para uma função, dentro da função esse valor vai ser `undefined` :)

Mas a dificuldade no início é comum mesmo, fique tranquilo! Esses últimos exercícios do desafio 2 eu avacalhei um pouco mesmo, pra ajudar a queimar um pouco de neurônios haha! Mas não se preocupe se não conseguiu resolver sozinho. Sempre que isso acontecer, acompanhe comigo a correção do desafio, logo no início da próxima aula, e depois tente fazer sozinho.

Tente depois apagar e refazer sozinho algumas vezes, e repita o processo depois de 1 a 3 dias nos exercícios que você sentiu mais dificuldade, pois isso vai ajudar a você saber se realmente gravou aquele conteúdo :)

E pergunte sempre que tiver dúvidas, estou à disposição para ajudar :D

**Comment by fabianogosilva** [comment]
Valeu!! abraço pessoal e bora estudar!!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
