### ISSUE TITLE
Desafio da semana #4 [Funções]

### ISSUE THREAD

**Issue by rafaelnoronha** [da2k/curso-javascript-ninja#6587]
Olá professor, tenho uma dúvida sobre funções.
Qual a diferença entre criar uma `function()` em uma variável e de criar uma `function()` normal com nome?
**Ex:**
```js
function myFunction() {};

var myFunction = function() {};
```

**Quando usar cada método?**
**Qual a vantagem de cada um?**

_O curso está sendo TOP de maaaaais!_

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafaelnoronha! Que bom que está curtindo o curso, fico muito feliz em saber :grin: :grin: 

Sobre as diferenças, na maior parte das vezes, você pode usar qualquer uma das duas formas.

Mas mais pra frente no curso, vai ficar mais claro alguns usos específicos para as duas.

A primeira forma, somente usando a palavra chave `function` e o nome da função, você está criando o que chamamos de **função literal**. Ao criar uma função dessa forma, é obrigatório que ela tenha um nome, senão você não consegue acessá-la depois de criar a mesma (salvo se usar IIFE, que é um assunto que você vai ver em aulas futuras).

Já criando a função como expressão (seu segundo exemplo), significa que essa expressão será avaliada e irá retornar um valor. E o valor retornado é a referência para essa função criada (vamos falar sobre referência mais pra frente também, não se preocupe).

E uma diferença nesse caso é que, como funções também pode ser usadas como expressões, elas podem ser usadas dentro da linguagem como qualquer outro tipo de valor: você pode atribuir uma função à uma variável, passar sua referência via parâmetro para outra função, fazer uma função retornar outra função, passar uma função como propriedade de um objeto, etc =)

Bom, falando por cima é isso. Mais pra frente nós vamos ver bem sobre esses tipos de uso, e vai ficar mais claro. Por enquanto, não se preocupe com "a melhor maneira", apenas entenda o que dá e o que não dá pra fazer com a linguagem, e mais pra frente nós iremos falar sobre boas práticas, o que fazer, e o que evitar, ok? =)

E pergunte sempre que precisar, estou à disposição para ajudar :)
