### ISSUE TITLE
Referente ao desafio 28

### ISSUE THREAD

**Issue by hallancma** [da2k/curso-javascript-ninja#6647]
Fernando no desafio 28, o retorno do XMLHttpRequest não consegui pegar forma alguma, sendo a requisição e retorno vem normalmente pela chamada.Fiz o pull request do meu código para que possa analisar e tentar me ajudar.

Fiz 2 a aula mas mesmo assim não consegui resolver, quando puder poderia me ajudar?

Desde de já muito obrigado e parabéns pelo curso, mudou minha forma de ver o JS.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hallancma! Fico feliz que está curtindo o curso :D 
Vou dar uma olhada no seu Pull Request, provavelmente é alguma mudança que teve na API :\

Daqui a pouco eu volto aqui com a resposta :)

**Comment by fdaciuk** [comment]
Oi @hallancma! Já vi o problema =)
Veja que [aqui](https://github.com/da2k/curso-javascript-ninja/pull/6646/files#diff-88e848e870b512fbe580c947b978fd7cR94) você espera que a função `parseData` receba o objeto `ajax`. Mas [aqui](https://github.com/da2k/curso-javascript-ninja/pull/6646/files#diff-88e848e870b512fbe580c947b978fd7cR73), onde você executa a função, você não passa esse objeto, logo, dentro da função `parseData`, `ajax` sempre será `undefined` :)

Tem duas soluções: ou você usa a variável global que foi criada, e remove o argumento que `parseData` espera, ou então, na chamada de `parseData`, você passa via parâmetro esse objeto :)

Para esse caso em que você só precisa fazer um request por vez, qualquer uma das duas formas funciona.

Para outros casos, onde você pode precisar de objetos `ajax` diferentes, para diferentes requests, é importante passar via parâmetro mesmo, para que a função consiga pegar os resultados de cada request de forma separada :)
