### ISSUE TITLE
Hoisting

### ISSUE THREAD

**Issue by joaopedron** [da2k/curso-javascript-ninja#667]
Fala @fdaciuk, veja se o meu entendimento sobre `hoisting` está correto, seguindo esse exemplo:

`var escope = 'global';`

`
function f() {
  console.log(escope);
  var escope = 'local';
}
`

O JS entende que dentro do corpo da função f, existe uma váriavel escope e então ele 'iça' ela para o topo da função, porem ele não atribui valor a ela, retornando undefined.

Está correto esse pensamento ? 

Abraços.

**Comment by fdaciuk** [comment]
Mais ou menos isso.. o içamento sempre acontece, para variáveis e funções, dentro do escopo em que elas se encontram, mas a atribuição continua sendo feita no mesmo local.

No caso do seu exemplo, como você está declarando a variável `escope` dentro da função `f`, mas "usando" ela antes de atribuir valor, é isso que vai acontecer:

```js
var escope = 'global';

function f() {
  var escope;
  console.log(escope);
  escope = 'local';
}
```

É dessa forma que o içamento acontece =)

Ficou claro?

**Comment by joaopedron** [comment]
Foi isso que eu disse, ele joga a variável para cima mas não atribui valor a ela, logo o primeiro console.log vai retornar undefined.

Acho que ficou claro, sim! Obrigado mestre.

**Comment by fdaciuk** [comment]
Então é isso mesmo :D
Qualquer dúvida grita ae =)
