### ISSUE TITLE
Challenge 11 - return e object

### ISSUE THREAD

**Issue by tiagosatur** [da2k/curso-javascript-ninja#6672]
E ae Daciuk! Tenho duas dúvidas:
1)
Nesse for:
```js
   for (const prop in person) {
        counter++;
        console.log(`The ${prop} of person is ${person[prop]}`);
    }
```

Como que person[prop] retorna o valor daquela propriedade?

2) Por que na função moreThan há o retorno de false? Na minha intepretação deveria retornar somente caso fosse true (idade de person maior do que idade passada por parâmetro). Mas, a função retorna true/false de qualquer forma.
```js
function moreThan(age) {
      return person.age > age;
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tiagosatur! Vamos lá :)

# 1)

O `for in` sempre vai iterar por todas as chaves de um objeto. A variável `prop` que criamos vai representar uma chave por vez, a cada iteração.

Exemplo: 

```js
var person = {
  name: 'John Doe',
  age: 30
};

for (var prop in person) {
  console.log(`The ${prop} of person is ${person[prop]}`);
}
```

Vamos fazer um teste de mesa pra ver o que acontece a cada iteração?

Você tem o objeto `person` com duas chaves: `name` e `age`. Ou seja: ao iterar por esse objeto usando o `for in`, duas iterações serão feitas, uma para cada chave :)

Logo, a cada iteração, o valor da variável `prop` vai mudar, vamos ver:

Na primeira iteração, `prop` vai ser `name`, e o resultado vai ser:

```js
console.log('The name of person is John Doe')
```

Pois `prop` vai retornar `name` e `person[prop]` é o mesmo que `person['name']`, que retorna o valor que está nessa propriedade `name` no objeto `person`, que será a string `'John Doe'` :)

Na segunda iteração, `prop` vai retornar `age`. Então o resultado será:

```js
console.log('The age of person is 30')
```

Já que, na segunda iteração, o valor de `prop` muda para a próxima chave (`age`), o valor 30 é retornado pois `person[prop]` vai ser igual a `person['age']`. E 30 é o valor da propriedade `age`, no objeto `person` :)

---

# 2)

Na função `moreThan`, você está fazendo uma comparação, usando o operador **maior que** (`>`), e esse operador sempre retorna um valor booleano (`true` ou `false`). 

Essa função funciona como uma pergunta: **a ideia da pessoa é maior que o valor passado por parâmetro?**.

Logo, a resposta pode ser tanto positiva quanto negativa :)

Ficou claro? :)

**Comment by tiagosatur** [comment]
Ficou claro sim, obrigado doutor!

**Comment by fdaciuk** [comment]
Perfeito! Qualquer dúvida, só avisar :D
