### ISSUE TITLE
Dúvida desafio #30

### ISSUE THREAD

**Issue by gugaah** [da2k/curso-javascript-ninja#6680]
Olá Fernando, tudo bem?

Referente ao pull request do repositório novo que criei no meu GitHub e que eu enviei pra vc naquele console.log, eu devo fazer o "merge" das duas branches ou deixo exatamente assim? Fiquei com essa dúvida agora.

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gugaah! Pode fazer o merge, sem problemas :)
Na verdade, pode sempre criar a nova branch com base na anterior, pra você aproveitar o código já feito :)

**Comment by fdaciuk** [comment]
Ou melhor: faça o merge na master, mas crie uma branch nova para cada funcionalidade :D

**Comment by gugaah** [comment]
Certo, uma branch nova para cada uma das funcionalidades que verei nas aulas seguintes, entendido!
Obrigado pelas dicas Fernando :)

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer coisa, só avisar :D
