### ISSUE TITLE
Referente ao desafio #31

### ISSUE THREAD

**Issue by gustakock** [da2k/curso-javascript-ninja#6688]
E aí Fernando, blza?
Estou com um pouco de dificuldade para entender sobre a questão do escopo das variáveis dentro dos métodos de objeto.

Vou exemplificar a minha dúvida: estou criando a funcionalidade de remover o registro do carro quando o mesmo é adicionado na tabela. Criando tudo dentro do mesmo método, apenas adicionando um evento de listener no botão de remover o carro e passando a função direto no scope, eu consegui fazer, porém se eu crio a função como um novo método do objeto, eu não consigo acessar a variável "$tr" do outro método. Deve ser algo bem simples que não estou vendo kkkk

Conforme imagem em anexo, eu consigo acessar a função createNewCar, porém não a variável.

![code](https://user-images.githubusercontent.com/44760279/54483094-ed639c80-482c-11e9-857b-000f44018726.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gugaah! Só com a imagem não tem como eu saber o que está acontecendo no contexto geral.
Sobe seu projeto no GitHub e me passa o link pra eu dar uma olhada? :)

**Comment by gugaah** [comment]
Segue código atualizado abaixo, estou trabalhando no `challenge-29.js`

https://github.com/gugaah/super-stock-cars/tree/challenge-31

Então, da forma como eu estava fazendo antes, eu acabei conseguindo fazer, acredito que tenha bugado o meu editor, pois hj simplesmente funcionou!

Mas acredito que para deixar o código mais clean e legível, seja interessante colocar esse evento de listener de remover o carro no método initEvents, junto com o handleSubmit, certo?

Fiz isso porém agora não consigo acessar a variável "$removeImage" que está dentro do método "createNewCar". A minha ideia é fazer assim que o usuário clicar na removeImage ele limpe toda a linha, no caso a variável "$tr".

**Comment by fdaciuk** [comment]
Oi @gugaah! Legal :D 
Bom, no caso do evento para remover o carro, você não vai colocar ele no `initEvents`. Vou explicar o motivo:

A ideia do `initEvents` é iniciar os eventos que precisam ser atrelados quando a aplicação começar a rodar.

No caso do evento de remover um carro, ele precisa ser atribuído ao botão no momento em que uma nova linha da tabela é criada, que é quando o botão de remover também é criado. Assim você tem a referência do botão e da linha sendo criada, para atrelar o evento no objeto correto, e remover ele quando necessário :)

Então seu pensamento estava certo! :D 

Era essa a sua dúvida? Qualquer coisa avisa aí que eu vou ajudando :)

**Comment by gugaah** [comment]
Certo, enviei o pull request no console.log do desafio 31 com a funcionalidade implementada. Está funcionando, porém tive que colocar a variável "$tr" no "local scope" para que ela possa ser usada nos dois métodos distintos, isso está correto assim ou teria alguma forma melhor de apresentar isso?
Melhor quero dizer no sentido de não deixar aquela variável "voando" lá em cima kkkk

Obrigado por todas as dicas Fernando :)

**Comment by fdaciuk** [comment]
Então, você pode criar a linha (`$tr`) dentro do método `createNewCar` sem problemas. Para remover, lembre-se que a função que é listener do evento recebe um objeto do evento via argumento, e, à partir desse objeto, você consegue pegar o botão clicado para saber qual linha deve ser removida, e então remover a linha toda :)

Uma dica para facilitar pegar a linha e "linkar" o botão com a linha: adicione uma propriedade `data-id` na linha e no botão. Esse ID tem que ser único por linha, então você pode usar a placa para preencher o valor dessa propriedade.

Quando o botão for clicado, você pega o `data-id` do botão, e procura o `tr` que tem o mesmo `data-id`, e deleta ele :)

Sacou a ideia? :)

**Comment by gustakock** [comment]
Bah procurei por tudo, olhei e re-olhei várias vezes as aulas de Module Pattern, a de Clousure e nada.
Não entendi como faço para acessar uma variável q foi declarada no scope de outro método do mesmo objeto.

**Comment by fdaciuk** [comment]
Oi @gustakock! Na verdade, isso não tem como fazer mesmo, e nem é isso que eu espero que você faça :)
 
No momento da criação do carro, você vai fazer o seguinte: vai criar a `tr`, as `td`s que vão dentro dessa `tr`, e o botão de excluir.

Já na ação de remover, ao clicar no botão, é preciso remover a `tr` que o botão está contida. Mas você não precisa, necessariamente, usar essa relação, de pai / filho.

Por isso eu comentei que, na hora de criar a `tr`, vc coloca um atributo `data-id` com a placa do carro tanto na `tr` quanto no botão.

Dessa forma, a `tr` e o botão estarão relacionados à partir desse atributo `data-id`.

Ao clicar no botão para remover, você só precisar selecionar a `tr` que tem o `data-id` igual ao do botão clicado, e remover ela =)

Ficou claro? =)

**Comment by gustakock** [comment]
Sim, entendi!
Vou arrumar o meu código e implementar isso e depois commitar as mudanças pro meu repositório.
Obrigado e desculpa o incômodo.

**Comment by fdaciuk** [comment]
Perfeito! Não é incômodo algum, é um prazer ajudar :)
Conte comigo para o que precisar :D
