### ISSUE TITLE
Conteúdo para estudo Rest API

### ISSUE THREAD

**Issue by jhenrique-dev** [da2k/curso-javascript-ninja#6715]
Fernando, boa noite!
Nas últimas aulas, você mostra como aplicar a arquitetura REST no projeto final.
Minha pergunta é, poderia me informar um conteúdo auxiliar para estudar mais sobre REST API? 
Obrigado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhenrique-dev! Na internet tem bastante conteúdo sobre APIs Restful, mas você pode começar por aqui:
https://www.restapitutorial.com/

:)

**Comment by brunopulis** [comment]
Oi @jhenrique-dev vi sua pergunta aqui e o @fdaciuk já te resonpdeu de forma bem bacana, existe uma lista de API's abertas que você pode brincar com elas, segue o link [Public APIs](https://github.com/toddmotto/public-apis)

**Comment by fdaciuk** [comment]
Boa @brunopulis!

**Comment by fdaciuk** [comment]
Trocando a label de `question` para `tip` :D

**Comment by jhenrique-dev** [comment]
Muito obrigado @fdaciuk  e @brunopulis pelas dicas.
