### ISSUE TITLE
sou iniciante demais

### ISSUE THREAD

**Issue by ScheidtObrien** [da2k/curso-javascript-ninja#6721]
boa  noite professor,  vi logo na primeira aula que precisa ter conhecimentos em html  e css,  porém na hora de comprar o curso,  não vi que precisava disso, pensei que era um curso desde lógica de programação até java completo, porém parece que precisa ter conhecimento já, será que o senhor tem outros vídeos que podem, me dar essa base para continuar a prosseguir no curso java script ninja ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ScheidtObrien! Não é necessário conhecimento de lógica de programação, ou nada do tipo. É importante sim conhecer HTML e CSS, mas esse conhecimento será necessário só do meio do curso pra frente :)

Continue o curso, pergunte sempre que tiver dúvidas, e se sentir muita dificuldade por falta de conhecimento de HTML e CSS, tem uma playlist bem legal no YouTube que pode ajudar :D 

https://www.youtube.com/playlist?list=PLV7VqBqvsd_0XDZab8VaQchHJBkWXtTBO
