### ISSUE TITLE
você chegou a ver o meu primeiro exercício ?

### ISSUE THREAD

**Issue by ScheidtObrien** [da2k/curso-javascript-ninja#6726]
eu fiz o primeiro desafio challenger 1,  porém não tive resposta, acho que encaminhei errado, chegou a conseguir ver ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ScheidtObrien! Quando você envia um desafio aqui no repositório, aparece uma mensagem falando sobre a dinâmica de como você pode seguir com o andamento do curso, e acompanhar a resolução, sempre no início da próxima aula.

Provavelmente você deve ter enviado o Pull Request no seu próprio repositório, ao invés de aqui, no repositório do curso, por isso não deve ter visto essa mensagem :)

De qualquer forma, pode seguir com o curso sem problemas, e acompanhar as soluções sempre no início da próxima aula, e sempre que tiver dúvidas, pode perguntar que eu vou te ajudando, ok? :D

**Comment by ScheidtObrien** [comment]
o problema que você quer usar uma plataforma bem complicada para nos comunicarmos, tem outra plataforma tipo facebook ? algum outro lugar ? porque eu não sei usar isso aqui ainda

**Comment by fdaciuk** [comment]
@ScheidtObrien pode tirar suas dúvidas lá pela Udemy sem problemas! Não precisa enviar os Pull Requests aqui se não quiser, fique tranquilo! Apenas tente resolver os desafios na sua máquina. O importante é praticar pra que você consiga aprender :)

No futuro, Git e GitHub serão muito essenciais para a sua carreira como desenvolvedor. Mas por enquanto, pode enviar suas dúvidas pela Udemy mesmo, e tentar resolver os desafios só na sua máquina, ok? :)

Conte comigo para o que precisar :D
