### ISSUE TITLE
parece que o git hub atualizou

### ISSUE THREAD

**Issue by ScheidtObrien** [da2k/curso-javascript-ninja#6729]
boa noite professor, parece que o site atualizou e algumas instruções dos seus vídeos não estão funcionado para o github ou eu que posso estar errando em alguma coisa, porém, eu segui os passos do teu vídeo para enviar o desafio,porém quando clico no da2k/javascript ninja não aparece essa opção que eu mandei a imagem aí, o senhor tem skype ou discord pra me ensinar a mexer no github ? se não quiser entrar em call comigo sem problema
![image](https://user-images.githubusercontent.com/48873926/54965286-ac673880-4f4e-11e9-879a-8a548942fc82.png)

@fdaciuk

**Comment by ScheidtObrien** [comment]
![image](https://user-images.githubusercontent.com/48873926/54965390-1089fc80-4f4f-11e9-9f83-65ec765b2412.png)
esse é o meu desafio 1 porém como não consegui te enviar por pull request ou sei lá o que kkkkkkkkk( me perdoe ser extremamente leigo no git hub ) to te enviando via issues

**Comment by fdaciuk** [comment]
Oi @ScheidtObrien! Sem problemas meu caro :)
Como eu disse anteriormente, não precisa se preocupar com a parte do GitHub. Apenas pegue os desafios e tente resolvê-los na sua máquina, não precisa enviar os pull requests :)

Para ver se você fez corretamente, acompanhe a correção sempre no início da próxima aula, e qualquer dúvida, pode perguntar :)
