### ISSUE TITLE
git hub

### ISSUE THREAD

**Issue by ScheidtObrien** [da2k/curso-javascript-ninja#6733]
o senhor disse para fazer o trabalho e simplesmente esquecer o git hub porém, não sei como fazer o trabalho sem usa-lo e dessa vvez eu não consigo nem criar uma branch pro challenger 2 para editar o challenger 2 com minhas respostas, vou ter que ver o tutorial para o  git hub antes do curso, infelizmente

@fdaciuk

**Comment by fdaciuk** [comment]
@ScheidtObrien, na branch `master` aqui do repositório, você tem todos os diretórios dos desafios. Baixando o repositório uma única vez, você terá todos os desafios para resolver na sua máquina :)

**Comment by fdaciuk** [comment]
Só acessando essa página:
https://github.com/da2k/curso-javascript-ninja

Você poderá ver os desafios (challenges) separados em diretórios. Acesse cada diretório, e dentro dos diretórios você vai encontrar o arquivo para o desafio :)

**Comment by ScheidtObrien** [comment]
mas pra isso tem que ter o git instalado ?

**Comment by fdaciuk** [comment]
Não, só acessar esse link que te passei! O GitHub é um site onde os arquivos ficam todos públicos :)

**Comment by ScheidtObrien** [comment]
ainda não consegui fazer o que  você tá pedindo, é melhor eu ver um tutorial mesmo

**Comment by fdaciuk** [comment]
@ScheidtObrien talvez o que te falte seja um pouco de conhecimento de web em geral :)
Você já escreveu algum site com HTML + CSS antes? Se não, acho melhor começar por aí, para depois partir para JavaScript, vai te ajudar bastante :)

**Comment by ScheidtObrien** [comment]
nunca, mas eu comprei o curso porque ele dizia ser do zero, e é no zero que eu estou kkkkkkkkk, o máximo que eu fiz foi ter concluído lógica de programação na microlins

**Comment by fdaciuk** [comment]
Sim, o curso fala de JavaScript do zero, não de desenvolvimento web :)
Foca nessa parte de HTML e CSS primeiro então, faz ajudar bastante e deixar as coisas mais claras :)

HTML e CSS é simples, eu já te passei um link de uma playlist pra começar, não? Começa por ela, e vá com calma que vai dar tudo certo :D

**Comment by ScheidtObrien** [comment]
Boa noite professor, daciuk, tudo bem ? eu andei procrastinando um pouco no nosso curso de java script ninja kkkkkk, mas resolvi seguir sua recomendação de ter noção de html e css pra então encarar o curso de java script ninja que compre com você na udemy, porém, você lembra que eu estava com dificuldade de mexer no github até pra me comunicar contigo ?  e fazer os  nosso exercícios ? então professor, eu acabei pesquisando sobre o github e percebi que é da bastante importância que um aprendiz de programador aprenda lidar com o github, e antes de voltar ao nosso curso  de java script eu acho que farei um curso de github, e como você até então demonstrou ser um professor atencioso, acho que vou comprar o seu curso de git hub, o único medo que eu tenho dele  é que ele é  o curso com mais horas de git hub da udemy kkkkkk, mas acho que vou encarar kkkkkkkkk, obrigado

**Comment by fdaciuk** [comment]
haha! Pode ir tranquilo @ScheidtObrien! O curso todo tem 8h, dá pra terminar rápido, e lá tem bastantes exemplos de uso e boas práticas para trabalhar sozinho e/ou em times com mais pessoas :)

Enfim, fique à vontade para perguntar sempre que precisar, você terá todo o suporte necessário em qualquer curso meu que fizer :)
