### ISSUE TITLE
Não consigo concluir após gerar chave pública! git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by pedradanamente** [da2k/curso-javascript-ninja#6739]
Olá, já gerei a chave públic no linux pelo comando ssh-keygen, criou dois arquivos um com nome de id_rsa e outro com o nome de id_rsa.pub,

Dei um cat no arquivo e levei o código pro git adicionando a chave pública, até ai ok.

No moment ode gerar a chave pelo comando a cima criou na minha pasta do repositório que estava aberto o terminal, eu tirei eles de lá, e entrei levantar os arquivos pro repositório.

Quando eu mando os arquivos o erro permanece, parece que não está vinculando minha chave com o git:

**Comment by LaurianoElmiroDuarte** [comment]
boa tarde @pedradanamente gere as chaves com o comando novamente e observe se houve erros, havendo erros, certifique-se que erro foi, caso não ocorra erro, vá até configurações de "ssh keys or gpg keys" do github e entre com a nova chave, só um detalhe é a pública, caso dê erros, certifique-se que erro foi esse .. 
qualquer dúvida poste aqui novamente .

**Comment by fdaciuk** [comment]
Oi @pedradanamente! Conseguiu resolver? Desculpe a demora na resposta, não recebi notificação da sua dúvida pois meu usuário não foi marcado nessa issue :)

Obrigado pela ajuda aqui @LaurianoElmiroDuarte! :)

Vou fechar a issue, mas se você ainda estiver com problemas, só avisar que vamos te ajudando, ok? :)
