### ISSUE TITLE
Armazenando informações definitivamente no server e as removendo

### ISSUE THREAD

**Issue by gustakock** [da2k/curso-javascript-ninja#6740]
Boa noite Fernando, blza?

Seguinte, estou com dificuldade de conseguir manter um POST q faço para o server.
Eu consigo fazer o POST porém o mesmo é substituído quando cadastro um novo veículo. Como posso fazer para manter o histórico?
E referente a funcionalidade de remover o registro do server, preciso usar um outro método ou então tipo, quando clico no botão de remover, fazer um novo POST em branco?

Repositório do projeto com o último commit.
https://github.com/gustakock/super-stock-cars/tree/challenge-32

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gustakock! O seu problema está na função `putDataInTable`.

Pense no seguinte: você tem uma só tabela, mas precisa criar uma `tr` para cada carro, correto?

Então cada `tr`, e cada elemento dentro da `tr` devem ser criados dentro do `forEach`, enquanto você itera pelos carros que vieram do server.

Como você está criando uma única `tr`, a cada iteração você está modificando o conteúdo DESSA `tr`, pois isso só o último carro cadastrado é exibido :)

Sobre o `fragment`: pense nele como uma cópia da tabela em memória, uma cópia "virtual". Antes de colocar as informações na tabela "real" (DOM), você preenche todo o `fragment`, e só depois do fragment preenchido (somente após o `forEach`), é que você faz o append do `fragment` na tabela real :)

Deu pra sacar a ideia? Fazendo isso, você já consegue resolver o problema de carregamento dos carros.

Sobre o DELETE, não sei se chegou a ver o diretório do desafio 33, mas lá explica certinho o que precisa ser feito para remover no server. Se não chegou lá ainda, a ideia é remover apenas no DOM mesmo :)

Qualquer dúvida, só avisar :D

**Comment by fdaciuk** [comment]
Detalhe importante: cada linha da tabela precisa ter seu próprio botão de remover, então você não pode criar um só objeto para o botão, nem ter somente um evento atrelado. Cada botão precisa ter seu próprio evento :)

**Comment by gustakock** [comment]
Consegui completar o desafio 32, tudo certo.
Obrigado mais uma vez com as dicas.

Grande abraço :)

**Comment by fdaciuk** [comment]
Perfeito @gustakock! Qualquer coisa, só avisar :D
