### ISSUE TITLE
[Aula 2] Desafio da semana

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#6753]
C:\Users\PC>git clone git@github.com:xfelipee/curso-javascript-ninja.git
fatal: destination path 'curso-javascript-ninja' already exists and is not an empty directory.

Por que está acontecendo isso?
Estou seguindo os passos do vídeo mas não está dando certo.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Olhando a mensagem de erro:
> destination path 'curso-javascript-ninja' already exists and is not an empty directory.

Ela diz que você já tem um diretório com esse nome `curso-javascript-ninja`, e esse diretório não está vazio :)

Você já deve ter clonado o repositório. Se quiser clonar novamente, tem que apagar o diretório já criado :D

**Comment by xfelipee** [comment]
Olá, bom dia. Preciso do seu email para mandar imagens.

**Comment by fdaciuk** [comment]
Oi @xfelipee! Dá pra mandar imagens por aqui mesmo :)
Só arrastar e soltar na área de comentários, que o GitHub faz o upload pra você :)

**Comment by xfelipee** [comment]
![Screenshot_2019-06-22 xfelipee curso-javascript-ninja](https://user-images.githubusercontent.com/19687110/60146931-d1638580-97a1-11e9-9aee-a6415be1bf4f.png)
![Screenshot_2019-06-25 xfelipee curso-javascript-ninja](https://user-images.githubusercontent.com/19687110/60146933-d58fa300-97a1-11e9-9933-c12d2bd5f417.png)
Olá, bom dia. Esses prints são só para ajudar. Eu uso windows e estou com muita dificuldade no git, tudo que eu coloco não funciona. Gostaria de uma ajuda. Tem como resetar meu github pra começar de novo?

**Comment by fdaciuk** [comment]
Oi @xfelipee! Se quiser ignorar o Git por enquanto, fique à vontade :)
Apenas tente resolver os desafios no seu computador, e depois assista à correção para ver se ainda ficou alguma dúvida :)

Se quiser começar o repositório do GitHub novamente, não tem como "resetar", mas você pode apagar e fazer um novo fork :)

**Comment by xfelipee** [comment]
Ok. Mas uma dúvida. É normal ter dificuldade nos exercícios?

**Comment by fdaciuk** [comment]
SUPER NORMAL meu caro! Você está aprendendo algo novo, e isso te tira da sua zona de conforto. A dificuldade faz parte do processo :)
Com o tempo e a prática, você vai ficando mais confortável, conforme você vai aprendendo a lidar com a linguagem, e descobrindo como resolver os problemas :)

Não se preocupe! Siga estudando! Tente sempre resolver o desafio sozinho. Não conseguiu? Assista a correção. Ainda ficou dúvida? Cola aqui que eu te ajudo :D
