### ISSUE TITLE
Branch challengers

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#6754]
Quando eu abri meu challenge-01 e copiei do master, copiou todos os challengers para o challenge-01

 	.github 	Update issue template 	6 months ago
	challenge-01 	Challenge 01 	4 years ago
	challenge-02 	Improve challenge 02 	4 years ago
	challenge-03 	Improve challenge 03 	4 years ago
	challenge-04 	Fix error on challenge-04 	4 years ago
	challenge-05 	Update challenge 05 	a year ago
	challenge-06 	Improve challenge-06 	4 years ago
	challenge-07 	Add challenge-07 	4 years ago
	challenge-08 	Add challenge-08 	4 years ago
	challenge-09 	Add challenge-09 	4 years ago
	challenge-10 	Challenge 10 	4 years ago
	challenge-11 	Fix challenge 11 	4 years ago
	challenge-12 	Fix challenge 12 	3 years ago
	challenge-13 	Add challenge 13 	4 years ago
	challenge-14 	Add challenge 14 	4 years ago
	challenge-15 	Challenge 15 	4 years ago
	challenge-16 	Challenge 16 	4 years ago
	challenge-17 	Fix challenge-17 	a year ago
	challenge-18 	Add challenge 18 	4 years ago
	challenge-19 	Add Challenge 19 	4 years ago
	challenge-20 	Fix error on challenge 20 	4 years ago
	challenge-21 	Fix typo 	4 years ago
	challenge-22 	Add challenge 22 	4 years ago
	challenge-23 	Add challenge 23 	4 years ago
	challenge-24 	Fix index challenge 24 	4 years ago
	challenge-25 	Update challenge 25 	4 years ago
	challenge-26 	Fix challenge 26 	4 years ago
	challenge-27 	Add challenge 27 	4 years ago
	challenge-28 	Update challenge-28.js 	3 years ago
	challenge-29 	Add company.json 	4 years ago
	challenge-30 	Add instructions to create .gitignore 	3 years ago
	challenge-31 	Add challenge 31 	3 years ago
	challenge-32 	Change project name 	3 years ago
	challenge-33 	Add challenge 33 	3 years ago
	.editorconfig 	Fix .editorconfig 	4 years ago
	.gitignore 	Simple server started 	3 years ago
	README.md 	Fix course link 

Tem algum problema nisso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Não tem problema. Como todos os desafios já estão no repositório, isso vai acontecer mesmo. A diferença é que, quando você comitar, somente os arquivos do `challenge-01` devem ter sido alterados. E assim você faz com todas as branchs, para seguir o que foi feito no curso :)
