### ISSUE TITLE
challenge-05 retorno da função

### ISSUE THREAD

**Issue by edurezende10** [da2k/curso-javascript-ninja#6777]
boa noite professor,

Estou com dúvidas em duas questões

1- Invoque a função criada acima, fazendo-a retornar todos os valores do último
array criado.

não entendi como eu posso fazer para que retorno todos os itens do array.

2 - Crie uma função chamada `book`, que recebe um parâmetro, que será o nome do
livro. Dentro dessa função, declare uma variável que recebe um objeto com as
seguintes características:
- esse objeto irá receber 3 propriedades, que serão nomes de livros;
- cada uma dessas propriedades será um novo objeto, que terá outras 3
propriedades:
    - `quantidadePaginas` - Number (quantidade de páginas)
    - `autor` - String
    - `editora` - String
- A função deve retornar o objeto referente ao livro passado por parâmetro.
- Se o parâmetro não for passado, a função deve retornar o objeto com todos
os livros.

Não entendi o por que não está retornando o objeto referente ao parâmetro que informei.

function book (name) {
 var  library= {dom: { quantidadedePaginas: 100 , autor : 'paulo' , editor: 'maria'} , chapeu : { quantidadedePaginas : 200, autor : 'juju' , editor : 'dante'}
 }
return library.name ; 
 
  }
 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edurezende10! As respostas para essas perguntas você vai conseguir assistindo a correção desse desafio :)
Lá eu explico em detalhes esses pontos :)

Se depois de assistir você ainda tiver dúvidas, pode comentar aqui que eu te ajudo, beleza? :D
