### ISSUE TITLE
Perdi o Repositório

### ISSUE THREAD

**Issue by Cleysonlb** [da2k/curso-javascript-ninja#68]
Fala @fdaciuk rapaz, deu um problema aqui e eu perdi o repositório com os desafios feitos, posso refazer e te mandar junto com o desafio 04?!

**Comment by fdaciuk** [comment]
Opa! Pode sim cara :)
Ou melhor: tenta mandar eles separados: cria a branch certinho pra cada desafio, e só resolve o desafio da branch específica. Ae manda os pull requests separados, ok?

Se tiver dúvidas de como fazer me avise que eu te dou uma força ;)

**Comment by Cleysonlb** [comment]
Show!! vou fazer todo o procedimento aqui, qualquer duvida te aviso! vlw Daciuk!!

**Comment by fdaciuk** [comment]
Valeu o/
