### ISSUE TITLE
[aula 2] Novas branchs não foram clonadas

### ISSUE THREAD

**Issue by brnocesar** [da2k/curso-javascript-ninja#6829]
Iniciei o curso e realizei as duas primeiras tarefas criando branchs como descrito na aula 1, pelo site do GitHub. Não cheguei a dar pull request em nenhuma delas.

Após isso, executei o procedimento para clonar o repositório remoto digitando o comando abaixo:
$ git clone git@github.com:brnocesar/curso-javascript-ninja.git

Acontece que as duas branchs criadas para as tarefas, não foram clonadas. Quando dei o comando para listar as branchs, aparecia apenas a master:
- o que aconteceu:
    $ git branch
    *master
- o que eu esperava:
    $ git branch
    *master
    challenge-01
    challenge-02

Enfim, isso é o que devia ter acontecido mesmo? Esperava que as novas branchs fossem clonadas, pois elas estavam no meu repositório (o que foi forkado) e foi esse o repositório que clonei.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brnocesar! 

É normal clonar só a branch master sim :)

Na verdade, não é necessário baixar todas as branchs, a menos que você vá trabalhar em alguma delas.
Mas se ainda assim quiser fazer, o processo manual é com os comandos:

Rode esse comando uma vez:

```sh
git fetch origin
```

Então, execute esse comando para cada branch que você queira local:

```sh
git checkout origin/challenge-01 -b challenge-01
```

Só altere o nome em `challenge-01` no comando acima para o nome da sua branch.

---

Se estiver usando linux, dá uma olhada na issue https://github.com/da2k/curso-javascript-ninja/issues/79 que eu expliquei como faz um for no terminal pra buscar automaticamente todas as branchs do repositório =)

**Comment by brnocesar** [comment]
Beleza, tava pulando as explicações sobre git e tal, brigadão.
Acabei mandando uns pull request pro repositório principal (da2k) sem querer haha.

**Comment by fdaciuk** [comment]
haha! Sem problemas @brnocesar!
Na verdade, era pra lá mesmo que era pra mandar :D 
Bom, se tiver qualquer dúvida, só avisar :)
