### ISSUE TITLE
[aula 2] comparação de variáveis

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-javascript-ninja#6853]
Daciuk, me tira uma dúvida por gentileza: não é possível eu fazer a comparação de várias variáveis de um só vez no JS? Tipo:

`var a, b, c;
if (a === b === c === undefined) { return true; }`

Em linguagem C isso é bem corriqueiro, tipo:

`(a == b == null)`
se a e b forem null retorna true, se não: false;

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! Isso não funcionaria corretamente em JS, pois o valor retornado pelo operador de comparação é um booleano.

Então, ao testar `a === b`, os dois são `undefined`, e isso vai retornar `true`. Quando for fazer a próxima comparação, ele vai pegar o resultado dessa comparação (`true`), e comparar com o valor de `c` (`undefined`), e o resultado vai ser `false`.

As comparações são resolvidas sempre de dois em dois operadores:

```js
// essa é sua expressão completa:
a === b === c === undefined
// então primeiro será resolvido o valor de `a === b`:
(a === b) === c === undefined
// `a === b` retorna `true`, então esse valor resolvido é comparado com o valor de `c`:
true === c === undefined
// ao comparar se `true` é igual a `c`, o resultado é `false`:
(true === c) === undefined
false === undefined
// no final, `false` não é igual E NEM do mesmo tipo de undefined, então o resultado final é `false`
false
```

No final, você teria `false` por esse motivo =)

Deu pra entender? :)
