### ISSUE TITLE
Comparação de variáveis

### ISSUE THREAD

**Issue by jefersonbaixo** [da2k/curso-javascript-ninja#6874]
Boa noite Fernando!

Fiz a comparação de variáveis do seguinte modo:
function qualquer2(x, y, z){
    if(x && !y && !z){
        return x;
    } else if(x && y && !z){
        return x + y;
    } else if(x, y, z){
        return (x + y) / z;
    } else if(!x && !y && !z){
        return false;
    } else {
        return null;
    }
}

Pelos testes que fiz a função funcionou da mesma maneira. 
Tem algum motivo para não fazer desse jeito? Em alguma situação pode sair o resultado diferente do esperado?

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jefersonbaixo! Para esse desafio, pode usar dessa forma sim, sem problemas :)
Só no penúltimo `else if`, seria `x && y && z` ao invés de `x, y, z` :)

E mais algumas aulas pra frente nós vamos ver as diferenças de testar especificamente por `undefined` ou só usar a variável pra isso, pode ficar tranquilo :)
