### ISSUE TITLE
Funcionalidade de deleção do veículo do server

### ISSUE THREAD

**Issue by gustakoch** [da2k/curso-javascript-ninja#6884]
Olá Fernando, tudo bem?

Então, estou com uma dúvida sobre a implementação da remoção do veículo do server. Utilizei o método DELETE na requisição Ajax como utilizado no método POST, porém está um pouco confuso. Se eu cadastro os veículos informando a placa do veículo, ele não remove o veículo e quando eu cadastro os veículos, sejam eles quantos for, sem informar a placa, ele remove todos os veículos do server, kkkkkkkkk

Consegue me dar um help?

Link do commit atualizado: https://github.com/gustakock/super-stock-cars/blob/challenge-33/projetoFinal.js

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gustakock! Não entendi muito bem sua dúvida =)
No código que você postou, na branch `challenge-33`, você não está enviando uma placa para o servidor. O valor de `car.plate` está vindo vazio :)

Veja sua função `carInfo`: como é que você sabe qual carro está sendo deletado, se você não tem referência nenhuma da placa, no momento do clique no botão? ;)

**Comment by fdaciuk** [comment]
Oi @gustakoch! Vou fechar a issue, mas se ainda tiver problemas, só avisar que eu te ajudo, beleza? :)
