### ISSUE TITLE
[desafio 10]

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-javascript-ninja#6894]
Caro Daciuk,
No desafio 10, no paço 3, eu não estou entendendo o que você quer, tipo: minhas funções estão funcionando corretamente, mas o título do "passo 3" não está claro qual objetivo

PASSO 3:
  "sum" agora é uma função, e, se o sinal correto não foi passado para a
  função "calculator", "sum" será false. Certifique-se de que "sum" não é
  "false" **(certificar no sentido de EU pessoa ter certeza, ou verificar usando função?**, e então atribua às variáveis "number1" e "number2", dois números
  que serão os operandos da operação de soma.
  Após isso, mostre no console o resultado da operação, passando dois
  parâmetros para o método "log" de "console":
  - O primeiro será a mensagem da operação (usando a função criada acima); **A função criada logo acima é sum que não retorna mensagem, retorna uma função ou false**
  - O segundo, a função de soma, passando os dois operandos. **Aqui está claro**
  - Se "sum" for "false", mostrar no console a mensagem de erro. **Aqui também está claro**
  */

Estou questionando antes de assistir a resolução, pois minha intenção é tentar fazer tudo sozinho, e como o problema aqui é de entendimento do enunciado, acho melhor perguntar. Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! Perfeito, vamos às dúvidas :)

---

> Certifique-se de que "sum" não é "false" **(certificar no sentido de EU pessoa ter certeza, ou verificar usando função?**

Aqui tem um complemento: 
_Certifique-se de que "sum" não é "false", e então atribua às variáveis "number1" e "number2", dois números que serão os operandos da operação de soma._

A ideia aqui é sempre fazer essas verificações no código, testando se o valor de `sum` é uma função ou é `false` =)

---

> O primeiro será a mensagem da operação (usando a função criada acima); **A função criada logo acima é sum que não retorna mensagem, retorna uma função ou false**

Aqui estamos falando da função que já foi criada anteriormente (não a função exatamente anterior ao enunciado). É aquela função que exibe a mensagem da operação :)

---

Acho que é isso! Ficou claro? Qualquer coisa, só avisar :D
