### ISSUE TITLE
Documentação do JavaScript

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#6895]
Boa tarde mestre! Gostaria de saber sobre quem mantem o javaScript. Ex.: Quem mantem o HTML é a w3c. Quanto ao javaScript?
Também gostaria de saber sobre a documentação, você poderia me mandar um link? 
Agradeço muito.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! A especificação da linguagem é mantida pela Ecma:
http://www.ecma-international.org/publications/standards/Ecma-262.htm

E existe um grupo de trabalho, chamado TC39, que cuida da implementação das novas features na linguagem, testes, etc:
https://github.com/tc39
https://github.com/tc39/ecma262

A documentação com as formas de usar a linguagem, você encontra no MDN:
https://developer.mozilla.org

Aqui tem a documentação de toda a parte de Desenvolvimento Web:
https://developer.mozilla.org/en-US/docs/Web

Dentro desse último link, tem a parte da doc do JavaScript :)

Uma ferramenta bem legal que consome o conteúdo da MDN, e que facilita o uso de documentações no dia a dia, é o DevDocs:
https://devdocs.io/

Acho que é isso! Qualquer coisa, só avisar :)

**Comment by PauloTxJS** [comment]
Muito obrigado. Você é show.

________________________________
De: Fernando Daciuk <notifications@github.com>
Enviado: sexta-feira, 3 de maio de 2019 17:28
Para: da2k/curso-javascript-ninja
Cc: PauloTeixeira; Mention
Assunto: Re: [da2k/curso-javascript-ninja] Documentação do JavaScript (#6895)


Oi @PauloTxJS<https://github.com/PauloTxJS>! A especificação da linguagem é mantida pela Ecma:
http://www.ecma-international.org/publications/standards/Ecma-262.htm

E existe um grupo de trabalho, chamado TC39, que cuida da implementação das novas features na linguagem, testes, etc:
https://github.com/tc39
https://github.com/tc39/ecma262

A documentação com as formas de usar a linguagem, você encontra no MDN:
https://developer.mozilla.org

Aqui tem a documentação de toda a parte de Desenvolvimento Web:
https://developer.mozilla.org/en-US/docs/Web

Dentro desse último link, tem a parte da doc do JavaScript :)

Uma ferramenta bem legal que consome o conteúdo da MDN, e que facilita o uso de documentações no dia a dia, é o DevDocs:
https://devdocs.io/

Acho que é isso! Qualquer coisa, só avisar :)

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
