### ISSUE TITLE
[aula 2] dúvida do  NaN

### ISSUE THREAD

**Issue by caiomyrapereira** [da2k/curso-javascript-ninja#6901]
**Resolvido**
> typeof NaN

pq   return   tipo number??

**Comment by fdaciuk** [comment]
Oi @caiomyrapereira! Desculpe, não recebi a notificação dessa issue porque o meu usuário não foi marcado :\

Mas basicamente isso significa que `NaN` é um **tipo numérico** em JavaScript, que significa que o valor **não é um número** :)

Pode parecer meio complicado de entender no começo, mas é a forma da liguagem entender que alguma operação feita com números foi inválida, e devolveu esse tipo de valor que não é um número válido :)

Qualquer dúvida, só avisar!
