### ISSUE TITLE
[Desafio 12] Sort case sentitive?

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-javascript-ninja#6904]
Caro Daciuk,

Ao verificar a saída do `myName.sort();` verifiquei que única letra em maiúsculo precede as outras em ordem alfabética, é isso mesmo? Ele classifica as maiúsculas e, posteriormente, as minúsculas?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! O método `sort`, antes de tentar ordenar os valores, transforma cada valor em string e usa a [tabela Unicode](https://unicode-table.com/en/#control-character) para ordenar os valores. Por isso as maiúsculas são colocadas antes das minúsculas :)
