### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by GugaDavi** [da2k/curso-javascript-ninja#6905]
Opá Daciuk, antes de mais nada, mais uma vez e de novo, parabéns pelo curso, hoje posso dizer que tenho uma base solida no JS. Experiencia, ainda adquirindo, mas essa base ajuda e muito.

Queria saber se você tem interesse de adicionar um modulo no curso ou criar outro curso, sei lá, para falar/ensinar sobre as mudanças do ES6?

Grande Abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @GugaDavi! Muito obrigado pelo comentário, fico muito feliz em saber que o curso tem agregado na sua carreira :D 

Em breve teremos novidades com relação a isso, mas teremos sim um curso falando sobre as novidades da linguagem :D
