### ISSUE TITLE
[Desafio 16] Se dá pra complicar, pra quê simplificar

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-javascript-ninja#6922]
Nossa Fernando, precisava comentar. Depois que vi a revisão de você resolvendo da forma mais simples possível e falando que a gente tinha que fazer assim, tinha que mostrar o tanto que compliquei, veja:

`console.log( 'Roberto'.split('').reverse().join('').replace('o','a').split('').reverse().join('') );`

@fdaciuk

**Comment by fdaciuk** [comment]
haha! Na verdade, sempre tem mais de uma forma de resolver o mesmo problema! 
Se você conseguiu resolver dessa forma, ótimo! O primeiro passo é sempre conseguir resolver o problema :D 

Com o tempo, você vai aprendendo formas diferentes e mais eficientes de resolver =)
