### ISSUE TITLE
Challenge-09 - Primeira questão.

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [da2k/curso-javascript-ninja#6929]
Não entendi direito sobre envolver o código com IIFE. Seria para acionar as funções dentro da IIFE?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @HidemitsuHashimoto! É pra manter o código em um escopo local. Como funções têm escopo proprio, todo o código dentro de uma IIFE só vai ser visível ali, não vai "vazar" para o escopo global :) 

E só criamos com IIFE pra não precisar criar uma função no escopo global e executar ela :)

**Comment by HidemitsuHashimoto** [comment]
Acho que entendi. Muito obrigado grande mestre.

**Comment by fdaciuk** [comment]
Legal! Qualquer dúvida, só perguntar :)
