### ISSUE TITLE
Truthy e Falsy - Curiosidade

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#6931]
Professor! A título de curiosidade, pesquisando aqui eu verifiquei que 'falsy' significa 'falsamente', mas 'Truthy' não tem tradução. 'Truly' seria 'verdadeiramente' em inglês. Houve um erro ou o termo em javaScript é 'Truthy' mesmo? Agradeço o esclarecimento.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Por mais incrível que possa parecer, o termo é [esse mesmo](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) :grin:

**Comment by fdaciuk** [comment]
Na verdade (sobre a tradução), não tem tradução no Google Translate, mas é um termo válido:

https://en.wiktionary.org/wiki/truthy

:grin:

**Comment by PauloTxJS** [comment]
Valeu mestre. Vc é 10.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
