### ISSUE TITLE
[desafio #11]

### ISSUE THREAD

**Issue by heliton1988** [da2k/curso-javascript-ninja#6935]
Olá Daciuk.
 
minha dúvida é a seguinte, no desafio 11 nas ultima questão onde pede para mostrar os números pares de 0 à 20 usando um loop. Somente funciona com o loop for, já que tentei usar tanto o while quanto o dowhile e sempre dá um erro, mas esse erro só acontece quando implemento teste para saber se o número é par ou ímpar.

console.log( 'Pares de 0 a 20:' );
    numbers = [];
    for( var i = 0; i <= 20; i++ ) {
        if( i % 2 === 1 ) {  //quando uso esse teste no while sempre dá erro
            continue;
        }
        numbers.push( i );
    }
    console.log( numbers );

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @heliton1988! O seu problema provavelmente é no momento em que você está incrementando (ou decrementando) a variável contadora, aquela que vai garantir que o loop vai executar "x" vezes antes de finalizar o processo.


Veja que, usando o `for`, o incremento da variável contadora vai na estrutura da criação do `for`.
Já no `while`, você deve "gerenciar" isso manualmente.

Se você fizer um `if` que tenha um `continue` antes da variável contadora ser incrementada, o `while` vai executar novamente com o mesmo valor de antes, que vai fazer com que a execução caia no 'if` novamente, e o `continue` vai ser executado novamente, voltando ao início do `while` sem mudar o valor, e assim por diante...

Tem que achar uma forma de incrementar o valor independente da execução do `if` :)

Deu pra entender o problema? :)

**Comment by heliton1988** [comment]
Olá @fdaciuk !
  Obrigado pela tutoria. Entendi perfeitamente sua explicação.
O que estava ocorrendo é que como eu estava incrementando após a condição if(), meu código entrava em um loop infinito, mas foi possível resolver apenas mudando o incremento de posição.

**Comment by fdaciuk** [comment]
Exatamente isso @heliton1988 =)
Qualquer dúvida, só avisar :)
