### ISSUE TITLE
Dúvida sobre concatenação

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [da2k/curso-javascript-ninja#6940]
Estou com uma dúvida bem básica. Quando concatenamos strings com variáveis temos tanto a opção de '+' quanto a ','. Qual a diferença entre elas? Em que situação usar uma ou a outra?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @HidemitsuHashimoto! Não existe a opção de concatenar strings usando vírgula. Em ES5, só temos a o sinal de `+`, ou o método `concat` :)

**Comment by HidemitsuHashimoto** [comment]
Então quando fazemos isso:

`console.log( 'Eu tenho uma empresa chamada:', empresa );`

Como se chama quando eu uso a ',' ao invés do '+'? E em que situação fica melhor usar um ou outro?

**Comment by fdaciuk** [comment]
Nesse caso, é o método `log` do objeto `console` que recebe mais de um argumento. E todos os argumentos que ele recebe, ele concatena pra você :)

**Comment by fdaciuk** [comment]
Sacou a ideia? É como se você criasse uma função:

```js
function log (arg1, arg2, arg3) {
  return arg1 + ' ' + arg2 + ' ' + arg3;
}

// aí você usa ela assim:
log('string 1', 'string 2', 'string 3')
```

Deu pra entender? :)

**Comment by HidemitsuHashimoto** [comment]
Nossa. Entendi agora. Muito obrigado. :)

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
