### ISSUE TITLE
Seção 2 - Aula 13 - Desafio da semana #02

### ISSUE THREAD

**Issue by icarobuzz** [da2k/curso-javascript-ninja#6955]
@fdaciuk

Na hora de realizar o comando git push, recebo um erro =/

![image](https://user-images.githubusercontent.com/13529530/58173619-32171400-7c72-11e9-83f4-c6d341f7b55b.png)

**Comment by fdaciuk** [comment]
Oi @icarobuzz! O erro diz que você já tem algum commit que está no repositório "na frente" dos seus commits locais.

O que você precisa fazer é rodar um `git pull origin master`, para puxar as alterações que estão no repositório para o seu PC, antes de fazer o `git push` :)

**Comment by icarobuzz** [comment]
Usei o comando mas não deu certo. Acontece que eu já tinha tentado fazer o exercício aqui mesmo no GitHub,  antes de ver o vídeo sobre baixar o Git. Será que tem algo a ver?

**Comment by fdaciuk** [comment]
Provavelmente sim! Se você resolveu no GitHub, você já tem o arquivo modificado. Se o mesmo arquivo está modificado no GitHub e no seu local, quando você tentar fazer o `git pull`, você vai receber uma mensagem de conflito :)

Mas assim: não se preocupe com o GitHub agora.. tente resolver tudo local mesmo, sem subir aqui, não tem problema.

O importante é você praticar, e conseguir resolver os desafios, ok? :)

**Comment by icarobuzz** [comment]
Beleza! Valeu, Daciuk!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
