### ISSUE TITLE
Atualizando arquivos com locais com o repositório do github (branches e arquivos)

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-javascript-ninja#696]
Fernando, boa noite.
Sei que ensinou a atualizar via terminal, mas eu fiz os desafios 1, 2,3 4 e 5 utilizando o github mesmo, criando as branches e editando os arquivos por lá mesmo.

Bom agora segui os passos do vídeos 12, clonei o meu repositório, adicionei o upstream e dei merge da master/upstream, segue print do meu terminal abaixo.
![captura de tela 2016-04-16 as 19 28 43](https://cloud.githubusercontent.com/assets/910377/14584027/2beb10d2-040b-11e6-993c-bf3697e6a1ec.png)

Agora segue as minhas dúvidas:
Sabe o por que onde esta a branch master tem esse asterisco?

Como faço para baixar o que eu já fiz no github (branches e arquivos dos desafios que resolvi).

**Comment by fdaciuk** [comment]
Opa! Eae @gustavom! :D 
Desculpe a demora em responder. Sempre que abrir uma issue, pode me marcar (com "@fdaciuk"), que eu recebo notificação e já respondo aqui xD

O asterisco provavelmente é porque deve ter alguma coisa que você pode ter comitado direto na master, e ficou diferente do repositório principal. Com um `git status` você consegue ver quais arquivos foram modificados, e com um `git diff`, você vê o que está diferente =)

Para baixar as suas branchs para sua máquina, você precisa fazer uma a uma, o seguinte comando:

```sh
# Atualiza com seu repositório
$ git fetch origin

# Aqui você cria uma branch local, chamada `challenge-01`, com base nessa mesma branch do seu repositório (`origin/challenge-01`)
$ git checkout origin/challenge-01 -b challenge-01
```

Agora só precisa fazer o mesmo comando para todas as branchs que você quiser baixar, mudando o `challenge-01` para o nome da branch que você tem no GitHub :D

**Comment by diogorodrigues** [comment]
@fdaciuk aproveitando essa ISSUE, tive alguns problemas também:

O primeiro exercício, fiz utilizando o terminal e subindo o arquivo depois. Até aqui tudo bem. No entanto, quando fui fazer o upstream que você comentou no segundo vídeo, segui todo o passo a passo no meu repositório que já havia clonado antes, mas na hora de fazer um "git add .", o arquivo não era adicionado de jeito nenhum. Daí tentei forçar, mas mesmo assim não consegui adicioná-lo: uma msg era exibida informando que tinha arquivo alterado para ser adicionado, mas... 

Por isso, excluí todo o meu repositório local e fui tentar clonar utilizando o SSH para ver se o problema podia ter sido o fato de eu ter utilizado o HTTPS, mas não dá certo também: há problema de permissão. 

Concluindo, acabei clonando com HTTPS novamente, e não fiz o processo do upstream. Sabe me dizer o que posso ter errado?

**Comment by fdaciuk** [comment]
@diogorodrigues seu problema é um pouco mais específico, vou te chamar pra trocar uma ideia sobre isso, blz? =)

**Comment by fdaciuk** [comment]
@gustavom, conseguiu resolver? Vou fechar a issue, mas se tiver alguma dúvida sobre isso, me marca aqui que eu abro de novo, ok? =)

**Comment by Giljared** [comment]
Olá! Muito obrigada.

De grande valia esse espaço aqui.

Att,

**Comment by fdaciuk** [comment]
Que bom que ajudou @Giljared :D

**Comment by rodrigoosantoss** [comment]
Tendo eu criado um vinculo da minha pasta local com o repositório, ao fazer alteração na minha pasta local como eu atualizo para o repo?

**Comment by fdaciuk** [comment]
@rodrigoosantoss se você já está na branch correta, só precisa fazer o commit, para escrever na árvore do Git, e então fazer o `push` para empurrar as alterações para o seu repositório, na branch de mesmo nome do seu local :)
