### ISSUE TITLE
Dúvida com operadores - incremento

### ISSUE THREAD

**Issue by ngoncalves17** [da2k/curso-javascript-ninja#7038]
Olá professor, será que pode me ajudar com uma dúvida? Preciso fazer um contador, conforme exemplo abaixo:

![contador](https://user-images.githubusercontent.com/50850440/59157367-f3f65e80-8a7f-11e9-81f0-00bcf4b1610b.gif)

Aqui segue como está meu html:

```html
<div class="counter">
            <button type="button" id="menos">
              <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42">
              <path d="M4.667 0A4.668 4.668 0 0 0 0 4.667v32.666A4.668 4.668 0 0 0 4.667 42h32.666A4.668 4.668 0 0 0 42 37.333V4.667A4.668 4.668 0 0 0 37.333 0H4.667zm28 23.333H9.333v-4.666h23.334v4.666z" /></svg>
            </button>
            <input type="number" name="numero" id="num" placeholder="0" />
            <button type="button" id="mais">
              <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42">
              <path d="M4.667 42h32.666A4.668 4.668 0 0 0 42 37.333V4.667A4.668 4.668 0 0 0 37.333 0H4.667A4.668 4.668 0 0 0 0 4.667v32.666A4.668 4.668 0 0 0 4.667 42zm4.666-23.333h9.334V9.333h4.666v9.334h9.334v4.666h-9.334v9.334h-4.666v-9.334H9.333v-4.666z" /></svg>
            </button>
          </div>
``` 

E aqui como está meu código javascript, que está funcionando, porém não consegui fazer com que o contador ao clicar no "menos", só vá até o 0, e não apareça números negativos. Pode me ajudar? E me dizer se está correto o código, se há algo que possa melhorar. Como não cheguei na parte de eventos do javascript no curso, tentei me virar, não sei se está da melhor forma.

```js
var numero = 0;

function less() {
  numero--;
  setValue(numero);
}

function more() {
  numero++;
  setValue(numero);
}

function setValue(value) {
  document.getElementById("num").value = value;
}

setValue(numero);

var botaoMenos = document.getElementById("menos");
var botaoMais = document.getElementById("mais");
botaoMenos.onclick = function() {
  return less();
};

botaoMais.onclick = function() {
  return more();
};
```

Obrigada desde já.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ngoncalves17! Claro que posso! Vamos lá :)

Pra funcionar essa parte que você precisa, é só checar, dentro da função `less` (usando `if`), se o valor da variável `numero` é menor ou igual a zero (já que é possível entrar com algum valor manualmente, senão era só testar se o valor é igual a zero) =)

Se o valor for igual a zero, você pode simplesmente usar o `return` para ignorar qualquer código posterior dentro da função;

Ou ainda dar um `return` (pra não precisar do `else`) chamando o `setValue` com o valor `0` :)

---

Existem algumas oportunidades de melhorias no seu código, mas não se preocupe com isso por enquanto! A ideia inicial é sempre tentar fazer funcionar do jeito que precisa funcionar, antes de qualquer coisa. 

Depois que o funcionamento estiver como você espera, aí sim você pode partir para a parte de refatoração, melhorando o código :)

Se precisar de dicas, ou qualquer ajuda, só avisar! Estou à disposição :)

**Comment by ngoncalves17** [comment]
Funcionou perfeitamente, obrigada! Deixei a função dessa forma:
`function less() {
  if (numero <= 0) {
    return setValue(0);
  }
  numero--;
  setValue(numero);
}`

Tenho uma outra pergunta. Ao invés de usar todo esse código que usei para fazer o click nos botões, que é mais extenso, eu tinha apenas invocado as funções diretamente nos botões, usando `onclick="less()"` e `onclick="more()"`. Porém isso não estava funcionando. Só funcionava caso eu colocasse todo meu código javascript no próprio html, pela tag <script>. Senão, no arquivo javascript externo, onde está meu código, aparecia essa mensagem: **'less' is defined but never used. (no-unused-vars) eslint**
Sabe dizer porque? Não sei se é algo do site que estou utilizando, pois é um teste que preciso fazer e estou usando o editor CodeSandbox, sabe?

**Comment by fdaciuk** [comment]
Então, com esse código atual, vc separa o código JS do seu HTML. E quando precisa fazer o JS "conversar" com o HTML, vc faz através da DOM API (no caso, selecionando elementos do DOM, adicionando eventos, etc).

Em aplicações usando JS puro (sem bibliotecas ou frameworks), é importante manter essa separação, tanto para facilitar a manutenção do código, quanto para deixar o código unobtrusivo (funcional, independente do JS).

Esse é um assunto um pouco extenso, mas você vai ver isso com mais detalhes no curso :)

Para resumir, colocando os eventos diretamente no HTML não é uma boa prática, mas no seu caso, o código não funciona pois, quando você coloca o evento diretamente no elemento HTML, é esperado que a função usada no evento esteja no escopo global da aplicação.

Ao usar o codesandbox, ele faz com que o código JS, em um arquivo separado do HTML, fique em um escopo de "módulo", separado do escopo global da aplicação, por isso não funciona :)

Se quiser testar: para funcionar, ainda que o código JS fique em um arquivo separado, "pendure" as funções "less" e "more" no objeto global "window", dessa forma:

```js
window.less = function () {
  ...
}

window.more = function () {
  ...
}
```

Não é uma boa prática, mas vale o teste pra você ver como isso funciona :)

No decorrer do curso, você vai entender porque isso não é uma boa prática, e como desenvolver de forma correta :)

**Comment by ngoncalves17** [comment]
Ah, se não for abusar, tenho mais uma dúvida, rs. O que estou fazendo é um formulário, onde além do contador, tem uma parte com checkboxes. O que eu queria era fazer uma validação, que ao tentar enviar o formulário, ele não deixasse caso um desses itens não estivesse preenchido e mostrasse alerts para ajudar o usuário. Ou seja:
- caso não tenha algum checkbox selecionado, apareça a mensagem "Selecione um ou mais stickers!"
- caso o número inserido no contador seja igual ou menor que 0, apareça a mensagem "Escolha a quantidade de stickers desejada!"
- caso não tenha nenhum checkbox selecionado e o número do contador seja igual ou menor que 0, apareça a mensagem "Selecione um ou mais stickers e escolha a quantidade desejada!"

Quebrei a cabeça aqui por horas, rs, mas só consegui fazer duas verificações, pois ele não chega na terceira. Entendo porque não está funcionando, mas não consegui uma forma de fazer isso, de mostrar  esses 3 alerts diferentes.

Segue o html do formulário:

```
<form action="" name="compraStickers">
        <fieldset>
          <legend>Quais stickers:</legend>
          <div>
            <input type="checkbox" id="react" name="sticker" value="react" checked />
            <label for="react"><span></span>React</label>
          </div>
          <div>
            <input type="checkbox" id="vue" name="sticker" value="vue" />
            <label for="vue"><span></span>Vue</label>
          </div>
          <div>
            <input type="checkbox" id="angular" name="sticker" value="angular" />
            <label for="angular"><span></span>Angular</label>
          </div>
        </fieldset>
        <fieldset>
          <legend>Quantos stickers de cada?</legend>
          <div class="counter">
            <button type="button" id="menos">
              <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42">
              <path d="M4.667 0A4.668 4.668 0 0 0 0 4.667v32.666A4.668 4.668 0 0 0 4.667 42h32.666A4.668 4.668 0 0 0 42 37.333V4.667A4.668 4.668 0 0 0 37.333 0H4.667zm28 23.333H9.333v-4.666h23.334v4.666z" /></svg>
            </button>
            <input type="number" name="numero" id="num" placeholder="0" required />
            <button type="button" id="mais">
              <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42">
              <path d="M4.667 42h32.666A4.668 4.668 0 0 0 42 37.333V4.667A4.668 4.668 0 0 0 37.333 0H4.667A4.668 4.668 0 0 0 0 4.667v32.666A4.668 4.668 0 0 0 4.667 42zm4.666-23.333h9.334V9.333h4.666v9.334h9.334v4.666h-9.334v9.334h-4.666v-9.334H9.333v-4.666z" /></svg>
            </button>
          </div>
        </fieldset>
        <fieldset>
          <legend>Observações:</legend>
          <textarea
            name="descricao"
            placeholder="Alguma dúvida? Recado?"
          ></textarea>
        </fieldset>
        <footer>
          <button type="submit" id="enviar">Enviar</button>
        </footer>
      </form>
```

Segue o js:

```
function validaForm() {
  var algumChecado = false;
  var inputs = document.compraStickers.getElementsByTagName("input");
  for (var i = 0; i < inputs.length; i++) {
    if (
      inputs[i].type === "checkbox" &&
      inputs[i].checked === true &&
      numero > 0
    ) {
      algumChecado = true;
      return;
    }
    if (numero <= 0) {
      alert("Escolha a quantidade de stickers desejada!");
      return false;
    } else if (!algumChecado) {
      alert("Selecione um ou mais stickers!");
      return false;
    } else if (numero <= 0 && !algumChecado) {
      alert("Selecione um ou mais stickers e escolha a quantidade desejada!");
      return false;
    }
  }
  return true;
}

var botaoEnviar = document.getElementById("enviar");
botaoEnviar.onclick = function() {
  return validaForm();
};
```

**Comment by fdaciuk** [comment]
Certo, vamos lá =)
Alguns pontos importantes que você deve levar em consideração:

**atualização do contador**

ao atualizar o valor do contador, é importante sempre tomar como base o valor anterior que estava nele.
Se você usar sempre a variável `numero` para verificar o valor que está no input, você pode ter estar buscando a informação de uma fonte que não vai te falar a verdade.

E o motivo é o seguinte: como é possível fazer a alteração manual do valor do input, imagine que o a variável `numero` tem o valor 3, mas eu digitei manualmente no contador o valor `1`.

Veja o problema: o usuário entrou com o valor `1`, pois ele quer apenas 1 sticker, mas a sua variável `numero` tem o valor `3`. Isso pode ser um problema grande na hora de finalizar uma compra, por exemplo :)

Pra resolver isso, sempre antes de incrementar ou decrementar o valor do input, é preciso pegar o valor **que está no input** no momento do clique dos botões `+` e `-`.

**Sobre pegar o valor dos outros campos** 

ao invés de atrelar um evento de clique no botão, você pode usar o evento de submit do formulário. Semanticamente faz muito mais sentido, já que o `form` é o "dono" daqueles campos :)

Toda função "listener" de evento recebe, via argumento, um objeto com informações do evento.

Nesse objeto você consegue pegar os valores de cada campo dentro desse formulário, o estado dos checkboxes (checado ou não checado), etc.

E à partir daí você consegue fazer uma validação mais simples e previsível :)

Como você não chegou na parte de manipulação de DOM e eventos do curso ainda, recomendo, nesse momento, você pular algumas aulas, e assistir essas aulas sobre DOM e eventos, que irão te ajudar bastante a concluir esse desafio que você está fazendo :)

Depois você pode voltar e continuar o curso de onde parou :D 

Se tiver qualquer dúvida, pode ir abrindo issue, ou perguntar aqui, se for relacionado à essa dúvida, que eu vou te ajudando, ok? :D
