### ISSUE TITLE
Verificar as correções

### ISSUE THREAD

**Issue by diogorodrigues** [da2k/curso-javascript-ninja#705]
Hey @fdaciuk , blz man?

Não entendi muito bem como faço para ver as correções dos exercícios. 
Acompanhar por e-mail é quase impossível, rss, pois recebo muitos. Então, há alguma maneira de eu saber quando o arquivo foi comentado através do github? Eu clico em pull requests, vou até o que eu fiz e quando abro ele não aparece nada.

**Comment by fdaciuk** [comment]
Opa! Fala @diogorodrigues! No topo, do lado direito, ao lado da tua foto, tem um botão de "+" e um ícone para as notificações. Sempre que um pull request seu for comentado, deve aparecer ali. Só clicar nesse ícone para acompanhar. 

Sempre que eu corrijo, se tem algo pra ajustar eu marco com a label "awaiting correction". Se estiver ok, eu marco com "revised" e fecho o pull request, mas sempre comento, para você saber o status daquele exercício :D 

Como tem muitos pull requests, eu posso demorar um pouco até conseguir corrigir todos, mas vou fazer um a um, não se preocupe =)

Se você tiver alguma dúvida específica de algum exercício, de algo que não entendeu, pode criar issues aqui que eu vou dando prioridade para as dúvidas, ok?
