### ISSUE TITLE
Exercício 06

### ISSUE THREAD

**Issue by andersonweb** [da2k/curso-javascript-ninja#707]
No exercício abaixo, eu fiz uma coisa diferente, e ACHO que não tem muita importância. 
Bom, na verificação eu neguei o array juntamente como o documento `!teams[numbers]`. Testando pelo zero, ele retorna:  
`O time que está em 0º lugar é o undefined.`

_PS: Achei bem mais fácil, vai que temos mais times, teremos que adicionar itens no array e mudar na verificação..._

Mas visto que a questão retorna a posição de times, não faz sentido o usuário/alguém passar a posição 0, certo?

Mas por questão de segurança (uma vez li em um artigo que não deve-se confiar no usuário. Se tiver apenas uma maneira de ele fazer o projeto todo virar uma  bosta, ele vai fazer):
```
if( !teams[number] || number === 0 ) {
		return 'Não temos a informação do time que está nessa posição.';
	}
```

Qual tua opinião ?

```
Crie uma função chamada `showTeamPosition` com as seguintes características:
    - A função deve receber um número por parâmetro;
    - A função deve retornar a frase:
    "O time que está em [POSIÇÃO]º lugar é o [NOME DO TIME].";
    - Onde [POSIÇÃO] é o valor passado por parâmetro e [NOME DO TIME] é o time
    que está nessa posição no array criado acima com os nomes dos times.
    --------------
    Dica: lembre-se que arrays começam no índice zero, então a posição passada
    deve ser sempre um número a mais que o índice do array ;)
    --------------
    - A função só deve retornar a frase acima somente se o time estiver entre
    os 5 primeiros.
    - Se não houver time para a posição passada, deve retornar a mensagem:
    "Não temos a informação do time que está nessa posição."
```

**Comment by fdaciuk** [comment]
Essa é uma outra forma de fazer, que também funciona, mas não me parece tão claro. Se você perceber, é até redundante:

Quando você testa por `!teams[number]|`, o zero já está incluído nessa verificação, não é preciso verificar explicitamente por zero. Lembre-se: o operador `!` converte o valor para o seu equivalente booleano, e depois nega.

Então, se esse número for zero, o equivalente booleano é `false`. Ao negar, ele vira `true` e entra na condição =)

Mas assim.. os desafios não são pegadinhas para dificultar a solução. É para você treinar sua parte lógica, junto com o que está aprendendo no curso.

A questão de "verificação de segurança" não é uma preocupação que eu faria você ter ainda na aula 6, que é o início do curso, e vimos pouco sobre a linguagem.

Você se preocupa com segurança depois que você já começa a ter um domínio maior da linguagem, conhece como ela trata as entradas do usuário, para vocẽ se garantir e dar uma saída segura.

Mas não é uma preocupação que você deve ter no início do curso =)
