### ISSUE TITLE
[Aula 9] Operadores lógicos

### ISSUE THREAD

**Issue by MichelleVieira** [da2k/curso-javascript-ninja#7088]
Fiquei com dúvida quando você ensinou o operador lógico Not (!)...
Eu entendi que,
=!  Retorna verdadeiro caso os operadores não sejam iguais, independente da tipagem.
==! retorna verdadeiro caso os operadores não sejam iguais e do mesmo tipo.
===!  ? ( Não entendi esse)
Poderia me explicar ?

**Comment by fdaciuk** [comment]
Oi @MichelleVieira! Desculpe a demora na resposta! Como foi removido a marcação do meu usuário, eu não recebi notificação da sua dúvida :)

Mas vamos lá :)

Na verdade, o operador é sempre com o `!` na frente =)

`!=` e `!==` são válidos. Essa terceira opção, com o sinal de `!` e 3 sinais de igual não existe. Onde você viu essa parte? :)

**Comment by fdaciuk** [comment]
Oi @MichelleVieira! Conseguiu entender essa parte? Vou fechar a issue, mas qualquer dúvida, só avisar que a gente reabre e eu te ajudo, beleza? :)
