### ISSUE TITLE
Arquivos com o código resolvido

### ISSUE THREAD

**Issue by rodrigocan** [da2k/curso-javascript-ninja#7093]
Professor, tem algum local com o código feito no vídeo? Eu perdi o código que tinha feito do projeto e não queria refazer, gostaria de dar continuidade. Grato pela atenção.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rodrigocan! Os desafios resolvidos não tem, mas vou providenciar isso em breve, e aviso lá pelas mensagens da Udemy :D

**Comment by rodrigocan** [comment]
Obrigado. Eu deveria estar usando o git rs

**Comment by fdaciuk** [comment]
haha! Iria facilitar bastante :)
Mas relaxa que em breve eu vou disponibilizar isso :D 

Vou fechar a issue, mas se tiver qualquer dúvida, só avisar :)
