### ISSUE TITLE
Desafio 08

### ISSUE THREAD

**Issue by Cristuker** [da2k/curso-javascript-ninja#7096]
Eu fiz esse código abaixo e ele me da o retorno com a operação feita porém embaixo vem escrito undefined, e não entendi da onde esta vindo

function calculator(operacao) {

    switch (operacao != null) {
        case operacao == '+':
            return function(x, y) {
                var res = x + y;

                return console.log('Resultado da operação: ' + x + ' ' + operacao + ' ' + y + ' = ' + res + '.')
            }
            break;

        case operacao == '-':

            return function(x, y) {
                var res = x - y;
                return console.log('Resultado da operação: ' + x + ' ' + operacao + ' ' + y + ' = ' + res + '.')
            }
            break;

        case operacao == '*':

            return function(x, y) {
                var res = x * y;
                return console.log('Resultado da operação: ' + x + ' ' + operacao + ' ' + y + ' = ' + res + '.')
            }
            break;

        case operacao == '/':

            return function(x, y) {
                var res = x / y;
                return console.log('Resultado da operação: ' + x + ' ' + operacao + ' ' + y + ' = ' + res + '.')
            }
            break;

        case operacao == '%':

            return function(x, y) {
                var res = x % y;
                return console.log('Resultado da operação: ' + x + ' ' + operacao + ' ' + y + ' = ' + res + '.')
            }
            break;

        default:
            console.log('Digite um operador valido')
            break;
    }
}
-------------Chamadas e atribuições-------------
var sum = calculator('+')
console.log(sum(5, 4))

var subtraction = calculator('-')
var division = calculator('/')
var mod = calculator('%')

console.log(subtraction(2, 1))
console.log(division(10, 2))
console.log(mod(5, 2))
--------------------Retorno no console--------------
Info: Start process (11:37:41)
Resultado da operação: 5 + 4 = 9.
undefined
Resultado da operação: 2 - 1 = 1.
undefined
Resultado da operação: 10 / 2 = 5.
undefined
Resultado da operação: 5 % 2 = 1.
undefined
Info: End process (11:37:42)

@fdaciuk

**Comment by rodrigocan** [comment]
Também sou aluno do curso, mas vejo um problema no seu código. Esses blocos
com return e console.log. sugiro ver no bloco de aulas extras do curso a
aula que mostra a diferença entre console.log é return

Em qui, 27 de jun de 2019 12:36, Cristian Magalhães <
notifications@github.com> escreveu:

**Comment by Cristuker** [comment]
Obrigado mano, agora eu consegui resolver

**Comment by fdaciuk** [comment]
Oi @Cristuker! Legal que conseguiu resolver! Só alguns adendos:
- Você usou o `switch`, passando para ele uma expressão de comparação, que vai ter um retorno booleano (true ou false), e em cada `case`, você faz um novo teste, comparando a variável `operacao` com a string da operação, que vai também retornar um valor booleano (true ou false). Veja que, ao usar o switch, ele vai comparar o valor que foi passado para o switch com o valor do case.

Nesse caso, ele vai sempre comparar dois valores booleanos, ao invés de comparar o valor da variável `operacao` com as strings usadas para fazer as operações matemáticas :)

Nesse caso, seria melhor usar `if` mesmo :)

Outro ponto importante: evite criar funções dentro de estruturas de bloco: dentro de cada `case` você está criando e retornando uma nova função. Mas perceba que todas as funções têm a mesma estrutura: elas sempre recebem dois valores (`x` e `y`), e retornam uma operação com esses dois valores.

Ao invés de fazer isso, você pode retornar uma só função dentro de `calculator`, que vai receber os argumentos `x` e `y`, e **dentro** dessa função você pode fazer o `switch` ou `if`, ok? :)

Qualquer dúvida, só avisar :)
