### ISSUE TITLE
desafio 28 - Consigo popular os dados em um<span> mais não consigo popular em um <input type="text">

### ISSUE THREAD

**Issue by FabioMauadie** [da2k/curso-javascript-ninja#7098]
### 
Olá Professor 
depois de fazer  o desafio busca cep, resolvi fazer de novo para reforçar, porém resolvi colocar <input type="text" no lugar do <span> para mostrar os dados na tela.... porém não estou conseguindo fazer os dados aparecer no <input> mais quando retiro o <input> e coloco o <span> os dados são mostrados na tela.. Pode me ajudar por favor

![cep](https://user-images.githubusercontent.com/38436258/60308908-8a040300-9921-11e9-90c3-8aff7f8990e4.PNG)

 
![html](https://user-images.githubusercontent.com/38436258/60309031-3fcf5180-9922-11e9-8a67-279d35b1cc15.PNG)
![js](https://user-images.githubusercontent.com/38436258/60309098-8de45500-9922-11e9-9f29-660021f839ba.PNG)

estou gostando muito do curso

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @FabioMauadie! Campos de formulário funcionam de forma um pouco diferente: para adicionar dados em um `input`, é preciso utilizar a propriedade `value` do elemento:

```js
$cep.get()[0].value = data.cep;
```

Fazendo isso vai funcionar como esperado :)

**Comment by FabioMauadie** [comment]
entendi.. Obrigado por tirar minha Dúvida....estou gostando muito do curso...

**Comment by fdaciuk** [comment]
Show de bola @FabioMauadie! Fico feliz que está curtindo :)
Conte comigo para o que precisar :)
