### ISSUE TITLE
Observação Aula 5 Vídeo 28 Parâmetros de Funções como arrays e objetos. 

### ISSUE THREAD

**Issue by zorasantos** [da2k/curso-javascript-ninja#7115]
Pra chamar qualquer propriedade da variável obj não precisei criar outra função para retornar uma propriedade especifica. 
Apenas passei como argumento do myFunction o nome da variável com o nome da propriedade.
Por exemplo:
myFunction(obj.curso); dai ele me retorna o valor da propriedade curso.
Algum problema fazer assim ou é necessário criar uma nova função pra retornar uma propriedade especifica?
Obrigado!    

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @zorasantos! Poderia me dizer o tempo do vídeo onde eu mostro isso? Só pra eu entender o contexto :)

Porque a ideia das aulas iniciais do curso é para que o aluno comece a ficar maisi confortável com a linguagem, então eu vou mostrar várias formas de fazer a mesma coisa, saca? :)

Não se preocupe com "melhores maneiras" de fazer as coisas no primeiro momento. Primeiro é importante conhecer a linguagem, entender o que dá e o que não dá pra fazer, como fazer, para assim começar a ficar confortável com ela. 

Depois você pode começar a pensar em boas práticas, performance, etc :)

**Comment by zorasantos** [comment]
Obrigado Professor!
É mais ou menos assim:

`function myFunction(arg) {
return arg;
};`
`var obj = {
propriedade: 'zora',
idade: 33
};`
Eu posso a acessar a propriedade idade assim:
`myFunction(obj.idade);`
sem precisar fazer isso, uma nova função:
`function myFunction(arg) {
return arg.idade;
};`
`myFunction(arg);` para retornar a propriedade especifica idade.

Era só isso mesmo, fiquei satisfeito com o seu feedback, obrigado!

**Comment by fdaciuk** [comment]
Perfeito @zorasantos, então era o que eu estava pensando mesmo :)

> Era só isso mesmo, fiquei satisfeito com o seu feedback, obrigado!

Perfeito meu caro! Fique à vontade para questionar sempre que precisar. Estou à disposição para ajudar :)
