### ISSUE TITLE
[DUVIDA SOBRE BRANCH]   

### ISSUE THREAD

**Issue by Srubens** [da2k/curso-javascript-ninja#7128]
Olá daciuk tudo bem eu fiz uma branch no próprio github, agora eu quero que a branch mais a master fique na minha maquina local e no caso quando eu clono só vem a master a branch não vem.

@fdaciuk

**Comment by Srubens** [comment]
Olá @fdaciuk  consegui obgado!

**Comment by fdaciuk** [comment]
Opa @Srubens! Legal que resolveu :)
Qualquer coisa, só avisar :)
