### ISSUE TITLE
[Aula 167] Revisão desafio da semana #27 método estático

### ISSUE THREAD

**Issue by eduardocintra** [da2k/curso-javascript-ninja#7134]
Bom dia Professor,

Estou com a seguinte duvida, no vídeo da revisão da aula 167 estamos criando alguns métodos estáticos para verificar o tipo de dado, você nos disse que para acessar o método sem instanciar a lib nós teríamos que fazer assim:

```js

;(function( win, doc ) {

    function DOM( elements ) {
        this.elements = doc.querySelectorAll( elements );
    }

    DOM.prototype.isArray = function( parameter ) {
        return /Array/.test(Object.prototype.toString.call(parameter));
    };

	console.log( DOM.prototype.isArray([1,2,3,4]) );
})();
```

Mas dai eu achei estranho e resolvi testar de outra forma, e deu certo também, essa maneira que eu encontrei é criar o método sem o `prototype`, está errado fazer dessa maneira?

```js


;(function( win, doc ) {

    function DOM( elements ) {
        this.elements = doc.querySelectorAll( elements );
    }

    DOM.isArray = function( parameter ) {
        return /Array/.test(Object.prototype.toString.call(parameter));
    };

	console.log( DOM.isArray([1,2,3,4]) );
})();
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @eduardocintra! Cara, mil desculpas, realmente a forma como você fez é que está correta.. provavelmente na hora de resolver o desafio, eu estava tão focado nos métodos anteriores que acabei cometendo essa gafe :speak_no_evil: 

Adicionei uma nota logo após esse vídeo para explicar essa situação, mas a forma correta é exatamente essa que você fez =)
