### ISSUE TITLE
[Aula 18]  revisão do desafio challenge-18

### ISSUE THREAD

**Issue by heliton1988** [da2k/curso-javascript-ninja#7138]
Olá @fdaciuk !!
tenho uma pequena dúvida aqui, talvez até meio boba. 
Na resolução do desafio da aula 18, fiz a implementação da Regex de uma forma que até funcionou, mas como mesmo pesquisando na internet não encontrei nada que fosse pelo menos parecido, então gostaria de saber se é uma forma aplicável ou é bizarra de mais.

```js
/*
    Crie uma função chamada `cleanCPF`, que receba um CPF por parâmetro, e
    retorne esse CPF limpo (somente os números).
    Usando os CPFs abaixo, mostre no console que a limpeza funciona para todos
    eles! Use um console.log para cada CPF.
    - "049-214 3421-1"
    - "210.458.522-05"
    - "735 500 794 - 22"
    - "101.123-131x32"
    */
    console.log( 'Limpando CPFs:' );
    function cleanCPF( cpf ) {
        return cpf.match(/\d/g).join( '' );
    }
    
    console.log( cleanCPF("049-214 3421-1") );

```

**Comment by fdaciuk** [comment]
Oi @heliton1988! Qualquer solução que funcione é válida =)
A única coisa que você precisa analisar, depois de fazer funcionar, é se existe alguma forma mais simples, ou mais legível de resolver o mesmo problema :)

Mas o objetivo é esse: encontrar soluções para o problema com o conhecimento que você tem!
As melhorias no código você vai fazendo com o tempo, conforme vai aprendendo mais da linguagem :)

Qualquer coisa, só avisar :)
