### ISSUE TITLE
Challenge 2, null e undefined

### ISSUE THREAD

**Issue by bigbruno** [da2k/curso-javascript-ninja#715]
Fiz os exercícios utilizando null e funcionou, porém no vídeo que demonstra a resolução diz que deveria funcionar apenas com undefined, porém para funcionar com o null utilizei == e !=, não o === e !==.

Não devia ter apresentado erro?

Exercícios que funcionaram:

function aula( a, b, c ) { if( a == null || b == null || c == null ) { return 'Preencha todos os valores corretamente!'  } else { return  a * b * c + 2 } };

function final( $1, $2, $3 ) {
if( $1 != null && $2 == null) { return $1 } else if(
    $1 != null && $2 != null && $3 == null) { return $1 + $2 } else if(
    $1 != null && $2 != null && $3 != null) { return ($1 + $2) / $3 } else if(
    $1 == null && $2 == null && $3 == null) { return false} else { return null }
};

**Comment by fdaciuk** [comment]
Fala @bigbruno! Isso vai ficar mais claro na aula 4, onde veremos os tipos de valores que o JavaScript trata como _truthy_ e _falsy_.

Quando você não testa pelo tipo (usando `==` ou `!=`), em uma estrutura condicional (nesse caso, o `if`), o JS faz a conversão dos valores para o tipo que ele acha que é mais apropriado, por isso é importante testar sempre com a verificação de tipos =)
