### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7236]
Eu alterei a Branch master sem querer, tem como copiar novamente sem ser pelo git?
Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! A maneira mais simples de fazer é copiando o conteúdo da branch master aqui do repositório principal, e colando na sua branch master. Aí sua master vai ficar "zerada" novamente :)

**Comment by xfelipee** [comment]
Po, como eu faço isso?

**Comment by fdaciuk** [comment]
Bem simples: qual arquivo você alterou direto na sua master? Acesse esse arquivo aqui do repositório [pela interface do GitHub](https://github.com/da2k/curso-javascript-ninja), copie o conteúdo dele, cole no arquivo que você modificou na sua master, e faça um commit que a master vai ficar zerada :)

Ficou claro? :)
