### ISSUE TITLE
Sobre como verificar se os argumentos não estão preenchidos

### ISSUE THREAD

**Issue by diogorodrigues** [da2k/curso-javascript-ninja#724]
@fdaciuk , no exercício 02, você pediu para criar uma função que verificasse se os argumentos não estão preenchidos. Vendo a correção desse exercício na aula 03, vi que você fez da seguinte forma:
`if ( a === undefined || b === undefined || c === undefined  )`
Assim, quero saber se também é correto fazer:
`if( !num1 || !num2 || !num3 ) `
?

**Comment by fdaciuk** [comment]
Fala @diogorodrigues! Na maior parte dos casos, isso funciona bem sim, você pode usar qualquer uma das duas formas.

Tem algumas particularidades que você vai entender melhor quando chegar na aula 4, quando veremos sobre como o JS trata valores _truthy_ e _falsy_ =)

**Comment by diogorodrigues** [comment]
Blz @fdaciuk ;)
