### ISSUE TITLE
curso terminado

### ISSUE THREAD

**Issue by tuilopes70** [da2k/curso-javascript-ninja#7251]
ola professor,eu estou fazendo o curso em 2019 e ele já esta completo, eu só poderia entrar no github para fazer os desafios ou eu teria que utilizar o git.
E eu também poderia utilizar o VSCode para retornar o código js no próprio VSCode

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tuilopes70! Sim, pode resolver os desafios só no seu computador, sem problema algum :)
E fique à vontade para usar o editor de sua preferência!

E qualquer dúvida, conte comigo :)
