### ISSUE TITLE
Server python

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7281]
Mestre! Estou com dúvida na forma de usar o servidor python. Eu rodo o comando 'python -m SimpleHTTPServer 9001', aí o terminal retorna 'Serving HTTP on 0.0.0.0 port 9001 ...' e fica nisso. Quando você vai pro browser percebi que na url aparece 'localhost:9001'. No meu aqui não aparece isso, aparece o caminho do arquivo. Pode me ajudar? Agradeço...

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Você precisa digitar o endereço `localhost:9001` na barra de endereços do seu navegador :)

No meu já apareceu porque eu deixei pré-digitado, apenas pra facilitar =)

**Comment by PauloTxJS** [comment]
Blz... Então estou fazendo certo.kkkkkkk valeu mestre.😊

Em sex, 16 de ago de 2019 15:36, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Show! =)
Qualquer coisa, só avisar :D
