### ISSUE TITLE
Avaliação de lógica de pessoas no carro

### ISSUE THREAD

**Issue by ralsouza** [da2k/curso-javascript-ninja#7287]
Olá @fdaciuk, gostaria que você avaliasse a lógica neste método.

Crie um método que irá adicionar pessoas no carro. Esse método terá as
seguintes características:

-  Ele deverá receber por parâmetro o número de pessoas entrarão no carro. Esse

número não precisa encher o carro, você poderá acrescentar as pessoas aos
poucos.

- O método deve retornar a frase: "Já temos [X] pessoas no carro!"

- Se o carro já estiver cheio, com todos os assentos já preenchidos, o método
deve retornar a frase: "O carro já está lotado!"

- Se ainda houverem lugares no carro, mas a quantidade de pessoas passadas por
parâmetro for ultrapassar o limite de assentos do carro, então você deve
mostrar quantos assentos ainda podem ser ocupados, com a frase:

  "Só cabem mais [QUANTIDADE_DE_PESSOAS_QUE_CABEM] pessoas!"

- Se couber somente mais uma pessoa, mostrar a palavra "pessoa" no retorno
citado acima, no lugar de "pessoas".

```
carro.addPessoas = function( param ) {

  var assentosDisp = carro.assentos - carro.quantidadePessoas;
  
  if ( assentosDisp === 0 && assentosDisp >= carro.assentos ) {
    return 'O carro está lotado!';
  } else if ( param > assentosDisp ) {
    return 'Só '+ (assentosDisp === 1 ? 'cabe' : 'cabem') +' mais ' + assentosDisp + ' ' + (assentosDisp === 1 ? 'pessoa' : 'pessoas');
  } else {
    carro.quantidadePessoas += param;
  }
  
  return 'Já temos ' + carro.quantidadePessoas + ' pessoas no carro!';
};
```

**Comment by fdaciuk** [comment]
Oi @ralsouza! Perfeito meu caro! Se o problema foi resolvido, você cumpriu com o objetivo do desafio! Independente do "como" você resolveu, o importante sempre é fazer funcionar :)

Com o tempo e a prática, você vai melhorando a sua forma de pensar e resolver os mesmos problemas :)

E qualquer dúvida, conte comigo! :D
