### ISSUE TITLE
Conexão com Banco de Dados

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7294]
Mestre! Não sei se estou fugindo muito do curso.... Ainda estou no challenge-23... Tenho uns trabalhos da faculdade aqui pra fazer e gostaria de saber como fazer conexão com banco de dados? Mysql, SqlServer e MongoDb. Agradeço...

@fdaciuk

**Comment by PauloTxJS** [comment]
Não irei utilizar express... Quero conectar com um banco mysql.

Em sex, 23 de ago de 2019 11:16, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Nessa documentação, apesar de estar no site do express, ele mostra como usar o driver de cada banco, independente de usar o express ou não :)

**Comment by PauloTxJS** [comment]
Ok

Em sex, 23 de ago de 2019 13:23, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
