### ISSUE TITLE
Servidor http javaScript

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7295]
Mestre! Você usou um servidor python na aula... hoje na faculdade vi um servidor php. Não existe um servidor javaScript? Agradeço...

@fdaciuk

**Comment by PauloTxJS** [comment]
Show

Em sex, 23 de ago de 2019 11:18, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
