### ISSUE TITLE
Quero saber se aparece para vc tudo que estou fazendo ... fiz a lição 1 !

### ISSUE THREAD

**Issue by WellderLG27** [da2k/curso-javascript-ninja#7303]
Não sei se estou fazendo o certo... só veja pra mim se esta certo o passo a passo que segui pfv ! Obrigado !

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @WellderLG27! Vi que você está resolvendo eu já subiu no seu repositório! Show de bola :)
Não precisa enviar o Pull Request, pode só continuar fazendo como você começou :)

Sempre acompanhe a correção do desafio no início da próxima aula, e se surgir qualquer dúvida, fique à vontade para perguntar, estou à disposição para ajudar :)
