### ISSUE TITLE
Dúvida no challenge-29

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7324]
Mestre! Não consegui fazer o exercício... Nem mesmo copiando o seu... Fiz a cópia e mesmo assim não está rodando aqui.

@fdaciuk

**Comment by PauloTxJS** [comment]
Mestre! Gostaria muito de agradecer... Funcionou... Mas tá faltando só a parte do ajax, o nome do app. Isso ainda não consegui.

**Comment by PauloTxJS** [comment]
Tentando resolver eu acabei travando tudo de vez aqui. kkkkk melhor apagar e começar tudo do zero.

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :)
