### ISSUE TITLE
Símbolo da Divisão

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7334]
Mestre! Gostaria de saber como você fez aquele símbolo da divisão.... original?.... Sem ser esse( / ).

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Eu copiei da internet :)
Existem tabelas de código ASCII que contém esse tipo de caractere :)
Se você pesquisar por algo como "ascii table division symbol", deve aparecer nos primeiros resultados :)

**Comment by PauloTxJS** [comment]
Ok mestre... Obrigado.

Em sex, 30 de ago de 2019 08:41, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
