### ISSUE TITLE
Ler propriedades de um objeto

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7343]
Mestre! É o seguinte: eu tenho um objeto aqui e algumas das propriedades são objetos também, estou usando o 'for in' pra ler as propriedades do objeto mas quando chega na propriedade que também é um objeto ele não mostra.
``` 
let person = {
    name: 'fulano',
    address: 'rua do papoco s/n',
    formação_academica: {
        tecnico_em_informática: 'cepep',
        analista_de_sistemas: 'unifor'
    }
}

for(let prop in person){
    console.log(prop+' -> '+person[prop]);
}
```
O resultado tá saindo assim:
name -> fulano
address -> rua do papoco s/n
formação_academica -> [object Object]

Como resolvo a formação acadêmica?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Vamos falar de 3 pontos:
1. Entender o por quê da exibição do `[object Object]`;
2. Primeira forma de resolver o problema;
3. Segunda forma de resolver o problema.

Vamos lá:

**1. Entender o por quê da exibição do `[object Object]`**

Veja que, para exibir o resultado no console, você está usando a seguinte expressão:

```js
console.log(prop+' -> '+person[prop]);
```

Quando você concatena uma string com qualquer outro tipo de dado, o interpretador do JavaScript vai **converter** esse outro tipo de dado em uma string. É basicamente o mesmo que você pegar qualquer valor, de qualquer tipo de dado diferente de string, e usar o método `.toString()` nele.

No caso de um objeto, é esse resultado que você tem, quando tenta transformá-lo em string:

```js
var obj = {};
console.log(obj.toString()); // '[object Object]'
```

Então esse é o motivo dessa mensagem estar aparecendo no seu console :)

**2. Primeira forma de resolver o problema**

A forma mais simples para resolver esse problema é deixar que o objeto seja exibido no console como ele é, sem transformá-lo em string. Por isso o método `log` do objeto `console` permite que você passe quantos argumentos quiser para esse método. Então, ao invés de fazer:

```js
console.log(prop+' -> '+person[prop]);
```

Você pode fazer:

```js
console.log(prop, ' -> ', person[prop]);
```

Viu a diferença? Ao invés de concatenar tudo em uma string só, você passa cada valor como argumento para o método `log`, e ele vai exibir corretamente cada valor, da forma que ele é, no seu console :)

**3. Segunda forma de resolver o problema**

Existe ainda uma outra forma de resolver o mesmo problema: você pode verificar se a o valor da propriedade do objeto que está sendo iterada naquele momento é um outro objeto, e então fazer um novo `for in`. Seria algo como: 

```js
for (let prop in person) {
  if (person[prop].toString() === '[object Object]') {
    for (let propDaProp in person[prop]) {
      console.log(prop, ' -> ', propDaProp, ' -> ', person[prop][propDaProp])
    }
  } else {
    console.log(prop, ' -> ', person[prop]);
  }
}
```

Essas duas soluções resolvem seu problema! Agora é só ver qual se encaixa melhor no seu objetivo com esse código :)

**Comment by PauloTxJS** [comment]
Valeu mestre! Gostei mais da primeira forma de resolver o problema... mas entendi, tanto a primeira quanto a segunda.... Você é o cara...

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
