### ISSUE TITLE
Problema no challenge-29

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#7347]
```
(function($) {
  'use strict';

  /*
  Vamos estruturar um pequeno app utilizando módulos.
  Nosso APP vai ser um cadastro de carros. Vamos fazê-lo por partes.
  A primeira etapa vai ser o cadastro de veículos, de deverá funcionar da
  seguinte forma:
  - No início do arquivo, deverá ter as informações da sua empresa - nome e
  telefone (já vamos ver como isso vai ser feito)
  - Ao abrir a tela, ainda não teremos carros cadastrados. Então deverá ter
  um formulário para cadastro do carro, com os seguintes campos:
    - Imagem do carro (deverá aceitar uma URL)
    - Marca / Modelo
    - Ano
    - Placa
    - Cor
    - e um botão "Cadastrar"

  Logo abaixo do formulário, deverá ter uma tabela que irá mostrar todos os
  carros cadastrados. Ao clicar no botão de cadastrar, o novo carro deverá
  aparecer no final da tabela.

  Agora você precisa dar um nome para o seu app. Imagine que ele seja uma
  empresa que vende carros. Esse nosso app será só um catálogo, por enquanto.
  Dê um nome para a empresa e um telefone fictício, preechendo essas informações
  no arquivo company.json que já está criado.

  Essas informações devem ser adicionadas no HTML via Ajax.

  Parte técnica:
  Separe o nosso módulo de DOM criado nas últimas aulas em
  um arquivo DOM.js.

  E aqui nesse arquivo, faça a lógica para cadastrar os carros, em um módulo
  que será nomeado de "app".
  */

  var app = (function appController(){
    return {
      init: function init(){
        this.companyInfo();
        this.initEvents();
      },

      initEvents: function initEvents(){
        $('[data-js="form-register"]').on('submit', this.handleSubmit);
      },

      handleSubmit: function handleSubmit(e){
        e.preventDefault();
        console.log('submit');
        var $tableCar = $('[data-js="table-car"]').get()[0];
        $tableCar.appendChild(app.createNewCar());
      },

      createNewCar: function createNewCar(){
        var $fragment = document.createDocumentFragment();
        var $tr = document.createElement('tr');
        var $tdImage = document.createElement('td');
        var $image = document.createElement('img');
        var $tdBrand = document.createElement('td');
        var $tdYear = document.createElement('td');
        var $tdPlate = document.createElement('td');
        var $tdColor = document.createElement('td');

        $image.setAttribute('src', $('[data-js="image"]').get()[0].value);
        $tdImage.appendChild($image);


        $tdBrand.textContent = $('[data-js="brand-model"]').get()[0].value;
        $tdYear.textContent = $('[data-js="year"]').get()[0].value;
        $tdPlate.textContent = $('[data-js="plate"]').get()[0].value;
        $tdColor.textContent = $('[data-js="color"]').get()[0].value;

        $tr.appendChild($tdImage);
        $tr.appendChild($tdBrand);
        $tr.appendChild($tdYear);
        $tr.appendChild($tdPlate);
        $tr.appendChild($tdColor);

        return $fragment.appendChild($tr);
      },

      companyInfo: function companyInfo(){
        var ajax = new XMLHttpRequest();
        ajax.open('GET', '/company.json', true);
        ajax.send();
        ajax.addEventListener('readystatechange', this.getCompanyInfo, false);
      },

      getCompanyInfo: function getCompanyInfo(){
        if(!app.isReady.call(this))
          return;

        var data = JSON.parse(this.responseText);
        var $companyName = $('[data-js="company-name"]').get()[0];
        var $companyPhone = $('[data-js="company-phone"]').get()[0];
        $companyName.get()[0].textContent = data.name;
        $companyPhone.get()[0].textContent = data.phone;
      },

      isReady: function isReady(){
        return this.readyState === 4 && this.status === 200;
      }
    };
  })();
  app.init();
})(window.DOM);
 ```

Mestre! Deu erro de novo e não estou conseguindo resolver... Nem cadastra os carros e o ajax não funciona. Help me please.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Me passa o link do seu repositório onde tem esse código, por favor? Pois assim eu consigo baixar e testar, pra ver onde pode estar o problema :)

**Comment by PauloTxJS** [comment]
https://github.com/PauloTxJS/curso-javascript-ninja/tree/challenge-29/challenge-29

**Comment by PauloTxJS** [comment]
O problema é só o AJAX... O nome do app não está sendo passado via ajax.

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! O primeiro problema está [nessa linha](https://github.com/PauloTxJS/curso-javascript-ninja/blob/challenge-29/challenge-29/challenge-29.js#L43). Veja que você chama a função `this.getCompanyInfo()`, mas essa função deveria ser chamada somente quando iniciar o request ajax.

Provavelmente você queria chamar `this.companyInfo()` :)

Após trocar a chamada da função, vai aparecer um erro no console, mas esse acredito que você consiga resolver :)

Qualquer coisa, só avisar ;)

**Comment by PauloTxJS** [comment]
Mestre! Entendi, troquei 'this.getCompanyInfo()' por 'this.companyInfo()', deu um erro no console, mas eu consegui resolver... Mesmo assim o ajax ainda não está funcionando.

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Ajustando o erro do console era pra ter resolvido. Aqui o request está funcionando corretamente. Consegue atualizar o repositório com o seu código atual pra eu ver o que pode estar acontecendo?

**Comment by PauloTxJS** [comment]
https://github.com/PauloTxJS/curso-javascript-ninja/tree/challenge-29/challenge-29

**Comment by fdaciuk** [comment]
Pronto! O problema era exatamente o que eu achava que você iria conseguir resolver :)
Mas vamos lá. vou te dar uma pista: o erro está nessas linhas aqui:

https://github.com/PauloTxJS/curso-javascript-ninja/blob/challenge-29/challenge-29/challenge-29.js#L99-L102

Olhando para a mensagem no console, o que você acha que precisa fazer pra resolver? Tenta aí depois me diz :)

**Comment by PauloTxJS** [comment]
Mestre! Eu realmente não estou conseguindo realizar o challenge-29 como ele deve ser.... Só está faltando mesmo o nome do app via ajax.... Mas realmente não consigo. Não está dando nenhuma mensagem de erro no console, está cadastrando os carros e tudo mais... Só tem o problema quanto ao nome via ajax....

**Comment by fdaciuk** [comment]
Você chegou a ver as linhas que eu marquei acima no repo? Antes de tentar resolver, olhando para essas linhas, comenta aqui pra mim, o que você acha que pode estar errado, olhando para essas 4 lihas? :)

**Comment by PauloTxJS** [comment]
Irei assistir novamente as aulas de ajax, não tô conseguindo encontrar o problema.

**Comment by fdaciuk** [comment]
@PauloTxJS o problema não é na parte de Ajax, isso está certo. Inclusive, o request está sendo feito e os dados estão vindo direitinho. Dá uma olhada nesse link que eu mandei, nas linhas marcadas. O problema está ali :)

**Comment by PauloTxJS** [comment]
Mestre! Olhei as 4 linhas, pra mim elas estavam corretas... mas como você disse que o problema estava lá, eu já modifiquei de todas as formas aqui que eu consigo pensar e não deu certo....

**Comment by fdaciuk** [comment]
Sem problemas! As vezes a gente fica tão focado no problema que fica difícil ver a solução :)
Vou trazer as linhas pra cá e te mostrar onde é esse problema:

```js
var $companyName = $('[data-js="company-name"]').get()[0];
var $companyPhone = $('[data-js="company-phone"]').get()[0];
$companyName.get()[0].textContent = data.name;
$companyPhone.get()[0].textContent = data.phone;
```

Esse é o seu código. Perceba que as variáveis `$companyName` e `$companyPhone` estão recebendo o elemento do DOM que obtivemos através da nossa lib DOM, ou seja: pra pegar o elemento, você usa o `get()[0]`, certo?

Mas nas duas lihas subsequentes, você "tenta pegar" novamente o elemento do DOM, usando novamente `.get()[0]`, saca? As variáveis já receberam o valor correto, não precisar usar novamente o `.get()[0]` =)

Sacou onde está o problema? :)

**Comment by PauloTxJS** [comment]
https://github.com/PauloTxJS/curso-javascript-ninja/tree/challenge-29/challenge-29

Eu modifiquei isso antes, mas mesmo assim não deu certo.
Desculpa pela pertubação, mas tô quase pedindo 'pinico' desse desafio.

**Comment by PauloTxJS** [comment]
Mestre! Ainda não deu certo... Tô quase pedindo 'pinico' desse desafio.
https://github.com/PauloTxJS/curso-javascript-ninja/tree/challenge-29/challenge-29

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Está funcionando normal agora! Ah, o que pode estar acontecendo no seu caso, é que você deve estar abrindo o arquivo index.html com um duplo-clique, não? Isso faz com que o arquivo seja aberto com o protocolo `file://`, não com `http://` :)

Para abrir com HTTP, se você já tem o Node.js instalado no seu computador, é só acesar, via terminal, o diretório do seu projeto, e rodar o comando 
```
npx http-server .
```. 

Isso irá subir um servidor http estático, que irá servir seu arquivo index.html na porta 8081 :)

Me deixe saber se isso funciona pra você :)

**Comment by PauloTxJS** [comment]
Mestre!!!! Deu certo...kkkkkkkkkk Foi na porta 8080. Tô quase chorando de satisfação aqui...

**Comment by PauloTxJS** [comment]
Mestre! Lá atrás, quando você colocou pra rodar o server python eu fiquei sem entender o motivo... JavaScript não é uma linguagem server-side e client-side? JavaScript funciona tanto fora do servidor quanto dentro... então porque você estaria rodando um server nas aulas? Posso entender que existem comandos do javaScript que só funcionam no server? É isso mesmo?

**Comment by PauloTxJS** [comment]
Você poderia me explicar um pouco sobre esse comando: "npx http-server".

Ele starta um servidor http também... que nem o "python -m SimpleHTTPServer 9001"... ou o "php -S localhost:8080"... É isso mesmo? Uma vez eu lhe perguntei se existia um server javaScript... qual o comando pra starta-lo?
Agradeço muuuuuuiiiiiiiiiiittttttttooooooo.

**Comment by fdaciuk** [comment]
> Mestre! Lá atrás, quando você colocou pra rodar o server python eu fiquei sem entender o motivo... JavaScript não é uma linguagem server-side e client-side? JavaScript funciona tanto fora do servidor quanto dentro... então porque você estaria rodando um server nas aulas? Posso entender que existem comandos do javaScript que só funcionam no server? É isso mesmo?

Na verdade, subir um servidor http não tem a ver com o JavaScript em si. Nesse caso, o servidor http vai apenas "servir" sua aplicação. Para que você consiga fazer requisições HTTP, você precisa estar com sua aplicação rodando sobre um servidor HTTP. O navegador tem alguns protocolos de segurança, e ele não permite que você faça requisições HTTP usando o protocolo `file://` :)

Acho que não deixei muito claro nas aulas a real necessidade de subir um servidor HTTP. Vou tentar melhorar essa parte do conteúdo :)

---

> Você poderia me explicar um pouco sobre esse comando: "npx http-server".

O `npx` é uma ferramenta do NPM (surgiu com a versão 5 ou 6 do NPM, se não me engano), e basicamente serve para executar binários criados com Node.js. Qualquer ferramenta de linha de comando escrita com Node.js, que normalmente você instalaria de forma global para ter esse comando disponível no seu terminal, você pode substituir por `npx <COMANDO>`.

No caso do `http-server`, normalmente você primeiro instalaria ele de forma global:

```
npm i -g http-server
```

E depois executaria ele com o comando:

```
http-server .
```

Usando `npx http-server .`, ele vai instalar temporariamente o `http-server`, vai executar o comando `http-server .`, e então, quando você derrubar o servidor, e o http-server não for mais necessário, o NPM remove ele da sua máquina. 

A ideia do `npx` é substituir a instalação de pacotes globais :)

---

> Ele starta um servidor http também... que nem o "python -m SimpleHTTPServer 9001"... ou o "php -S localhost:8080"... É isso mesmo? Uma vez eu lhe perguntei se existia um server javaScript... qual o comando pra starta-lo?

É isso mesmo! Você pode usar qualquer servidor HTTP para subir sua aplicação. Nas aulas eu mostro o server HTTP do Python, mas você pode usar o do PHP, ou algum dos vários do Node.js, como o `http-server`, inclusive criar o seu próprio, como eu respondi na outra issue :)

**Comment by PauloTxJS** [comment]
Você é simplesmente show... Depois do meu notebook, o dinheiro mais bem
gasto foi comprando o curso javaScript ninja do Fernando Daciuk.

Em qua, 4 de set de 2019 15:27, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
haha! Fico feliz que está curtindo :heart: 
Qualquer dúvida, só avisar :)
