### ISSUE TITLE
Dúvida com o editor de código

### ISSUE THREAD

**Issue by dnegrisolli** [da2k/curso-javascript-ninja#7352]
Olá pessoal! Estou com uma dúvida, sem dúvida é algo muito básico mas eu estou faz dias tentando fazer funcionar. Baixei o Sublime e o Atom, mas nenhum deles executa a ação após o comando...! Eu não sei o que ligar pra que o editor faça o comando!
Agradeço a ajuda.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @dnegrisolli! Qual comando você está tentando rodar que não está dando certo? Consegue gravar um video do que você está tentando fazer pra eu tentar entender o seu problema?

**Comment by dnegrisolli** [comment]
Olá Fernando! Eu gravei um pequeno vídeo https://1drv.ms/v/s!AoIpvxb-GR_oscQIJnVR8f03kGXwMw?e=7fLOA5
agradeço muito!

**Comment by fdaciuk** [comment]
Ah, legal @dnegrisolli! Entendi seu problema :)
Bom, tem duas formas de você fazer isso, e na verdade, não é no editor. Você precisa escrever esses comandos ou no REPL do Node.js, ou no console do navegador.

Você está usando Windows, correto? Então a primeira coisa a fazer é instalar o Node.js. Só baixar e instalar desse site aqui:
https://nodejs.org/en/

Após fazer a instalação, você pode abrir um terminal qualquer (no Windows 10 tem o terminal do Ubuntu. Procurando por "Ubuntu" deve aparecer esse terminal, é um software de tela preta pra você digitar comandos).

Ao abrir esses terminal, depois de instalar o Node.js, você deve conseguir executar o comando "node" nessa tela preta. Ao digitar "node", vai abrir o que chamamos de REPL, que é um ambiente onde você consegue digitar comandos JavaScript, e ele vai exibindo o resultado desses comandos.

Pressionando CTRL + C você sai do REPL, aí pra entrar de novo é só digitar "node" novamente :)

Para acessar pelo navegador é mais simples: em qualquer página (preferencialmente abrindo uma nova aba no navegador), você pode clicar com o botão direito e selecionar a opção "Inspect" ou "inspecionar elemento".

Ao fazer isso, vai ser aberto uma caixa de ferramenta com algumas abas. Encontre a aba "Console". Nessa aba, você consegue digitar comandos igual ao REPL do Node.js :)

Você pode usar qulalquer uma dessas duas opções, fique à vontade para escolher :)

E qualquer dúvida, não hesite em perguntar! Inclusive se não der certo, ou se você tiver qualquer problema, só avisar que eu te ajudo, beleza? :D

**Comment by dnegrisolli** [comment]
AH!!!! Então não não é no programa!!! 
Eu estava me achando mega burro por não conseguir fazer isso no Sublime ou no Atom! ahahahaha
irei tentar fazer, agradeço!

**Comment by fdaciuk** [comment]
haha! Que nada :)
Fique tranquilo, e qualquer problema, não deixe de entrar em contato. Estou aqui pra te auxiliar no que for preciso :)
