### ISSUE TITLE
# Desafio da semana #2

### ISSUE THREAD

**Issue by gamer0292** [da2k/curso-javascript-ninja#7357]
Boa tarde estou com uma dúvida , como devo responder a isso ?

> Crie uma função que adicione um valor à variável criada acima, e retorne a string:
    O valor da variável agora é VALOR.
    Onde VALOR é o novo valor da variável.

eu li , reli , vi os vídeo de novo , mas não consigo entender e responder 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gamer0292! Conseguiu entender? :)

**Comment by gamer0292** [comment]
sim consegui , a resposta é simples eu que demorei para ligar os pontos

Em ter, 3 de set de 2019 às 17:28, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :)

**Comment by gamer0292** [comment]
Professor eu cometi um pequeno erro , eu estava respondendo o desafio 09,
mas não reparei que era  na Branch-Master  , eu mudei apenas a ordem das
funções , e dei commit, foi desatenção minha

Em qua, 4 de set de 2019 às 11:05, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Entendi =)
Mas você precisa de ajuda com algo?

**Comment by gamer0292** [comment]
Não preciso , só entrei em contato para informar mesmo o pequeno erro.

Em qui, 5 de set de 2019 às 16:52, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Ah, beleza! Bom, qualquer coisa, só avisar :)
