### ISSUE TITLE
Challenge 05 Dúvida sobre instrução

### ISSUE THREAD

**Issue by nalucode** [da2k/curso-javascript-ninja#7361]
"
Crie uma função que receba dois parâmetros: o primeiro, um array de valores; e o
segundo, um número. A função deve retornar o valor de um índice do array que foi passado
no primeiro parâmetro. O índice usado para retornar o valor, deve ser o número passado no
segundo parâmetro.

`var funcaoNumero = function(arg1, arg2) {
  return arg1[arg2] }`

Declare uma variável que recebe um array com 5 valores, de tipos diferentes.

`var numbersList = [1,5,9.5,10,3.14]`

**Invoque a função criada acima, fazendo-a retornar todos os valores do último
array criado**"
Neste trecho não entendi muito bem, pois minha função retorna exatamente o valor índice. Uma via que vejo seria verificar se o arg2 foi definido. Me corrija caso tenha entendido a instrução, por favor.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @nalucode! A função vai receber o array e o índice, do qual o valor deve ser retornado, certo?

O que você precisa fazer agora é apenas usar esse array que você acabou de criar, e passar ele como argumento para a função, junto com todos os índices desse array (um a um), para que todos os valores sejam exibidos :)

Basicamente é fazer uma chamada da função para cada índice do array :)

Deu pra entender a ideia? :)

Qualquer coisa, dá uma olhada na solução desse desafio que pode ajudar :)

**Comment by fdaciuk** [comment]
Oi @nalucode! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
