### ISSUE TITLE
Challenge 05 - Problemas na interpretação

### ISSUE THREAD

**Issue by lettcamara** [da2k/curso-javascript-ninja#7363]
Olá professor, tudo bem? Estou com dificuldades na interpretação dos problemas...consegui fazer todos os exercícios do 1 ao 3....mas quando cheguei no exercício 4 (aquele exercício maior do challenge 4...não consegui nem iniciar e nem fazer sozinha) e 5, confesso que estou tropeçando na interpretação....não consigo sequer dar um primeiro passo.....o que o senhor sugere? Continuo as aulas - fazendo o exercício e acompanhando a sua revisão (quando tenho dúvida) ou volto do zero, pois isso é falta de aprendizado (de minha parte)?! Muito obrigada!!! Suas aulas são sensacionais!!!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lettcamara! Continue sim! O importante é praticar! Tente fazer o que você entendeu do enunciado. Se sua interpretação ficar diferente do que será mostrado na solução do desafio, não tem problema! O importante é tentar resolver o problema =)

Se tiver dificuldade para resolver algum desafio, pode assistir a correção, e depois tentar fazer novamente, mas dessa vez sozinha. 

Repita esse processo quantas vezes forem necessárias, até que você tenha a certeza que entendeu porque o problema foi resolvido daquela forma, ok? :)

Quando estamos aprendendo algo novo, é super comum ter dúvidas.

Se ainda assistindo a correção, ficar alguma dúvida, fique à vontade para perguntar por aqui! Estou à disposição para te ajudar a aprender de VERDADE! Esse é o propósito desse curso :)

A única coisa que você **não pode fazer** é seguir com dúvidas, combinado? :D

**Comment by ricardon91** [comment]
Isso tambem está acontecendo comigo e luto para não olhar as respostas e fazer sozinho mas fico travado sem ideia do que fazer ai vou e vejo o video com a solução. Na solução eu entendo o que está sendo feito e penso "puta como sou burro pq não pensei desse jeito". Aí fico um pouco frustrado pensando oq faço pra ter uma logica assim.

No mais, após o término do curso vc indica algum projeto para por em pratica todo o ensinamento do curso? Pra colocar a teoria numa coisa real do dia-a-dia de trabalho. Falo isso pq caso apareça uma entrevista seria legal levar um projeto feito por mim. Já fiz alguns projetos mas foi sempre vendo outros fazerem e copiando o passo a passo dessa pessoa.

**Comment by fdaciuk** [comment]
Oi @ricardon91! Como eu falei acima: é super normal isso acontecer quando estamos aprendendo uma coisa nova! Muitas vezes é difícil pensar de forma lógica, quando não estamos ainda acostumados com a linguagem. Mas não se preocupe: isso vem com o tempo e prática.

Apenas siga em frente, consulte a solução sempre que não conseguir resolver sozinho, e não deixe de tirar dúvidas. 

Não tem problema não saber algo. O problema é desistir! Siga em frente, continue estudando e praticando! Com o tempo, a parte lógica vai ficando mais clara na sua mente, conforme você vai aprendendo e conhecendo mais da linguagem :)

E como eu disse para a @lettcamara, vale também pra você e para todos os meus alunos e alunas: conte comigo para **o que precisar**! Estou à disposição para te ajudar a alcançar no nível Ninja :D

**Comment by lettcamara** [comment]
Isso que o Ricardo descreveu, acontece muiiiito comigo!! Mas estou confiante que dessa vez, irei terminar um curso realmente ninja em JS!!!
Acho que minha maior dúvida está na função....quando coloco parametros ou quando crio variáveis!! E quando os crio, qual chamo no return..... 
Ainda faço muiita confusão com isso!! 
Tinha muita dúvida em entender o objetivo do return - mas graças a sua aula consegui entender!! 
Muiiiito obrigada professor!!!!

**Comment by ricardon91** [comment]
Dessa vez não vou desistir nem desanimar. Pela primeira vez tô gostando de um curso online. Vou ser ninja.

**Comment by fdaciuk** [comment]
Que legal @lettcamara! Fico muito feliz em saber que está conseguindo evoluir!
É isso mesmo @ricardon91! Siga firme :D 

Contem comigo para o que precisarem, de verdade. Serei parceiro de vocês nessa jornada rumo ao nível Ninja! :D
