### ISSUE TITLE
Inicializando duas variáveis no loop for

### ISSUE THREAD

**Issue by ralsouza** [da2k/curso-javascript-ninja#7409]
Boa noite!

Olá @fdaciuk, não entendi muito bem a lógica em inicializar duas variáveis no loop for? Poderia descrever alguma situação mais prática que poderíamos usar este recurso?

```
// Inicializando duas variáveis
for( var num = 2, arroz = 3; num < 5; num++ ) {

	console.log( num );

	console.log( arroz++ );
}
```

**Comment by fdaciuk** [comment]
Oi @ralsouza! Não existem muitos casos em que isso é realmente necessário. O que foi mostrado no curso foi apenas para exemplificar, e pra você saber que isso é possível, se algum dia você precisar :)

**Comment by fdaciuk** [comment]
Oi @ralsouza! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
