### ISSUE TITLE
Utilização do indexOf

### ISSUE THREAD

**Issue by wtorresx** [da2k/curso-javascript-ninja#7429]
Percorra o array `brasil` e verifique se o Ceará está incluído, atribuindo o
  resultado à uma variável. Se esse estado existir no array, mostrar a frase no
  console:

  - Ceará está incluído!

  Senão, mostrar a frase:
  - Ceará não foi incluído :(

Nesta questão ao invés de percorrer o array, utilizei o método "indexOf" para saber se o estado Ceará estava incluso no meu array, caso ele retorna-se "-1", seria false, se >=0 "true" e joguei em um "if" conforme segue abaixo:

```
if(brasil.indexOf('Ceará')>-1){
    console.log('Ceará está incluído!');
  }else{
    console.log('Ceará não foi incluído :(');
};
```
A duvida é: Desta forma, há alguma queda no desempenho?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @wtorresx! A ideia dos desafios do curso não é nem a preocupação com desempenho, já que, ao trabalhar com poucos dados, não faz diferença o que você vai usar.

O ponto chave é você tentar resolver os desafios com o conteúdo que já foi apresentado dentro do curso, pra ver se você realmente entendeu e conseguiu absorver o conteúdo que foi passado :)

Se você conseguiu entender o que foi mostrado no curso, e já sabe como funciona o `.indexOf`, se ele ainda não tiver sido apresentado, pode ser qualquer uma das soluções sem problemas, e sem preocupação com desempenho :)

O importante é que você aprenda de fato o conteúdo passado, pra conseguir ter o máximo de ferramentas possíveis para conseguir resolver problemas do dia a dia :)

Ainda falando sobre desempenho: são poucos momentos em que você, de fato, precisa se preocupar com isso. E normalmente é quando você trabalha com grandes cargas de dados (na cada dos milhares).

Trabalhando com pequenos arrays (na casa das centenas o dezenas de dados), qualquer coisa que você usar vai executar rápido o suficiente, e não vai dar a percepção de "travamento" na sua aplicação :)

Acho que é isso! Qualquer dúvida, fique à vontade para perguntar. Estou à disposição para ajudar :)

**Comment by fdaciuk** [comment]
Oi @wtorresx! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
