### ISSUE TITLE
Desafio Finalizado

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#744]
Daciuk viu o que finalizei?

**Comment by grodrigues** [comment]
https://github.com/grodrigues/curso-javascript-ninja/tree/grodrigues-patch-1/challenge-01

**Comment by fdaciuk** [comment]
Boa @grodrigues! Finalizando o desafio, pode enviar pull request aqui no repositório, que eu vou corrigindo os desafios na ordem em que eles são enviados, ok? =)

No final da aula 1, e no começo de todas as outras aulas, eu mostro como deve ser enviado o pull request. Se tiver dúvidas, pode criar issue aqui - não esqueça de me marcar com `@fdaciuk` - que nós vamos resolvendo :D
