### ISSUE TITLE
(operation['+']);

### ISSUE THREAD

**Issue by lettcamara** [da2k/curso-javascript-ninja#7447]
Oii professor!! Na revisão do exercicio, o senhor explicou sobre pegar os operadores que estão dentro do objeto "operation" - quando fosse diferente de undefined - até aí entendi bem....tive só dificuldade de entender o array passado (operation['+']);
Quero agradecer ao senhor, que antes nem conseguia ter dúvidas.....agora sinto que estou aprendendo de verdade!!!! Muiiiito obrigada mesmo!!!

@fdaciuk

**Comment by lettcamara** [comment]
Ahhh na continuação do video o senhor explica que, por ser uma string e não saber o valor passado, foi usado um array - por isso não usou o ".".....
Acho que a minha principal dúvida no JS é conseguir interpretar, criar a função, dividir para cada caso e depois linkar elas.....

**Comment by lettcamara** [comment]
Ihhh professor, não entendi naada dessa linha: **return operation[operator](x,y);**

**Comment by fdaciuk** [comment]
Oi @lettcamara! Vamos lá :)

Legal que você conseguiu entender sobre usar a sintaxe de colchetes ao invés da de ponto! Vamos para as outras dúvidas então:

Sobre criar funções, e dividir, isso vai depender do seu projeto. Com o tempo, você vai "sentir" que o seu código começa a ficar muito grande, quando você escreve "tudo de uma vez só", entende? 

Aí você mesma vai começar a perceber a necessidade de isolar alguns códigos: ou porque eles se repetem, ou porque você vai conseguir reaproveitar melhor usando uma função, ao invés de escrever o mesmo código duas ou três vezes, sendo que alguma coisa que muda é somente uma variável, ou algo assim. Fique tranquila que isso vai vindo com o tempo e prática.

Por isso é importante sempre praticar. Pegar os desafios do curso e tentar resolver de formas diferentes, mudar alguns valores, tentar pensar em formas diferentes.

Isso vai começar a abrir sua mente, e você vai começar a entender melhor esses pontos. Mas fique tranquila que isso vem com o tempo, ok? :)

Sobre essa linha:

```js
operation[operator](x,y)
```

O que acontece aqui é o seguinte:

Sabemos que `operation` é o seguinte objeto:

```js
var operation = {
  '+': function (a, b) { return a + b; },
  '-': function (a, b) { return a - b; },
  'x': function (a, b) { return a * b; },
  '÷': function (a, b) { return a / b; }
}
```

Veja que cada operação matemática recebe uma função, logo podemos executá-las à partir desse nome, certo?

Agora, a minha pergunta: como é que nós "alcançamos" ou "acessamos", ou ainda "chegamos" a essas funções, para conseguir executá-las?

Veja que `operation` é o objeto. A variável `operator` vai ser uma string com algum dos sinais que estão dentro de `operation`:

A variável `operator` pode ser algum dos sinais: `'+'`, `'-'`, `'x'` ou `'÷'`, correto?

Logo, usando essa variável, nós podemos "alcançar" a função que está dentro do objeto `operation`.

Se `operation` receber `'+'`, por exemplo, então a chamada:

```js
operation[operator]
```

Seria o mesmo que:

```js
operation['+']
```

Concorda?

Com isso, o valor que `operation['+']` retorna é uma função. Logo, podemos executar essa função usando o operador `()`. Aí que vem a chamada:

```js
operation[operator](x, y);
```

Que é o mesmo que:

```js
operation['+'](x, y);
```

Isso claro, levando em consideração que `operator` é igual a `'+'`.

Como essa variável `operator` pode ser qualquer um dos sinais, é possível acessar qualquer função dentro desse objeto `operation`, já que eu posso passar qualquer valor para `operator` :)

E veja um detalhe importante: todas as funções dentro do objeto `operation` tem a mesma assinatura. Assinatura significa que todas elas recebem exatamente a mesma quantidade de parâmetros, ou seja: independente de qual função nós executarmos, nós vamos sempre ter que passar dois parâmetros, que são dois números. 

Por isso podemos chamar com segurança:

```js
operation[operator](x, y);
```

Pois sabemos que, independente do valor de `operator`, ele sempre vai ser retornar uma função que espera dois números :)

Ficou mais claro essa parte? Qualquer coisa, só avisar :)

**Comment by lettcamara** [comment]
Professor, o senhor é sensacional!!!! Super entendi!!! Muiiiiiiito obrigada 🙏

**Comment by fdaciuk** [comment]
ahhh, que show! Qualquer dúvida, conte comigo :grin:
