### ISSUE TITLE
Console do chrome

### ISSUE THREAD

**Issue by maykonsousa** [da2k/curso-javascript-ninja#7459]
Cara preciso saber como você faz para continuar um bloco de códigos dentro do console tanto do chrome como do Node JS. Por exemplo, vou digitar a função
```Fuction soma(x,y) {```
aí quando eu dou enter, ao inves de ele ir pra linha de baixo ele tenta executar o código imcompleto
![print](https://user-images.githubusercontent.com/53588064/65111831-d8222300-d9b3-11e9-832c-45e4b9092a7d.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @maykonsousa! Dentro do console, vc pode usar "Shift + Enter" para quebrar de linha :)
Só o "Enter" vai executar aquele comando :)
Desculpe não ter sido claro nessa parte :)

**Comment by henriquejp** [comment]
A Função não está indo pra linha de baixo, pois esta faltando o **'n'** do nome (function). ;D

**Comment by fdaciuk** [comment]
O ponto do @henriquejp também é válido, é preciso ficar ligado em erros de sintaxe :)

Bom, vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
