### ISSUE TITLE
Server - Duvida

### ISSUE THREAD

**Issue by wtorresx** [da2k/curso-javascript-ninja#7461]
Professor, bom dia.

Iniciei a semana 15 ontem e durante a aula foi passado que iremos subir um servidor em algumas atividades. Paralelamente as suas aulas de JavaScript, estou estudando Java (JEE) e subi um servidor através do tomcat para iniciar os testes com a integração com o o HTML. A duvida é, até o final do curso, eu consigo manter este mesmo ambiente de testes ou terei que mudar para para me enquadrar com alguma aula?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @wtorresx! Pode seguir com o tomcat sem problemas. A ideia é apenas ter um servidor qualquer para acessarmos nossas aplicações via protocolo HTTP.

Qualquer servidor deve funcionar sem problemas :)

**Comment by fdaciuk** [comment]
Oi @wtorresx! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
