### ISSUE TITLE
Não entendo.

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7463]
![Untitled-1](https://user-images.githubusercontent.com/19687110/65157150-a8e8d180-da06-11e9-8750-d557324a817e.jpg)

1) Não entendo o porquê do 0 === false ser FALSE e do 0 == false ser TRUE. Não faz sentido, mesmo eu tendo assistido novamente os videos de "iguais" e de truthy e falsy!

2) Não entendi essa expressão também. "Não imprime o 0 porque ele é falsy". Não entendi isso.

while(0) {
     console.log("zero");
}

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Vamos lá :)

Veja que `0` (número zero) e `false` são valores com **tipos** diferetes. O zero é do tipo `Number` (tipo de dado que representa - ou serve para trabalhar com - números dentro da linguagem JavaScript).

Já o `false` é do tipo `Boolean` (tipo de dado que representa valores binários: verdadeiro ou falso, aberto ou fechado, etc., sempre representando esses valores com as palavras `true` ou `false`).

Sempre que você tenta comparar dois valores (usando `==` ou `===`), o resultado vai ser um booleano, para te dizer se essa comparação é verdadeira ou falsa, certo?

No caso, podemos entender como valores _falsy_, os valores que, ao serem convertidos para o seu equivalente booleano, vão sempre retornar `false`. A ideia é que eles, basicamente, representam valores "vazios".

Por isso, dentro do JavaScript, os valores que são _falsy_ (ou que representam "vazio" dentro de um tipo), são:

- `0` (zero, quando o tipo é `Number`);
- `""` ou `''` (string vazia, quando o tipo é `String`);
- `false` (o próprio `false`, que é do tipo `Boolean`);
- `null` e `undefined` (que representam os tipos `Null` e `Undefined`).

Todos esses valores, quando os convertemos para o seu equivalente booleano, retornam `false`.

Quando comparamos `0` com `false`, usando `==`, ele retorna `true`, dizendo que os valores são "iguais", independente do tipo.

O `==` compara sem levar em consideração o tipo. Para fazer essa comparação, o JavaScript faz uma "inferência de tipo", ou seja, ele vai converter um dos valores, com base em uma tabela, para deixar os dois do mesmo tipo, e então compará-los.

A tabela é essa:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#Loose_equality_using

Olhando para a tabela, dá pra entender o que acontece: No caso do seu exemplo (comparar zero com `false`), temos como **Operando A** o valor zero, que é um número (tipo `Number`), e o **Operando B** como `false`, que é um booleano (tipo `Boolean`):

![operandos](https://user-images.githubusercontent.com/487669/65273168-ed539a80-daf6-11e9-9576-68ac38d4641d.png)

Quando cruzamos esses dois dados, conseguimos ver o tipo de "inferência" ou "transformação" é feita em algum dos tipos, para gerar um resultado:

![comparar-zero-com-false](https://user-images.githubusercontent.com/487669/65273385-6eab2d00-daf7-11e9-9c1e-341faefeda43.png)

Veja que, de acordo com a tabela, o JavaScript transforma o **Operando B** em um número antes de comparar, usando uma função interna chamada `ToNumber`. Não precisamos conhecer essa função, nem temos acesso a ela diretamente na linguagem, mas temos algumas formas, dentro da linguagem, de converter valores. Vamos ver isso mais pra frente, mas já vou te adiantar que, usando a função `Number`, podemos transformar qualquer valor para o seu equivalente numérico.

No caso, se você rodar no seu console `Number(false)`, vai ver que o resultado vai ser zero.

Por isso, quando comparamos `0` com `false` **sem testar o tipo**, usando `==`, o resultado é `true` :)

Ficou claro? :)

---

OBS.: Sobre a função `Number`: vamos ver sobre ela mais pra frente, fique tranquilo, ok? :)

**Comment by fdaciuk** [comment]
Oi @xfelipee! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
