### ISSUE TITLE
Primeiro exercício do desafio

### ISSUE THREAD

**Issue by lettcamara** [da2k/curso-javascript-ninja#7483]
_- `addAge` - esse método não deverá ter nenhum parâmetro, mas ao invocá-lo
    iremos passar um único argumento, que é a quantidade de anos que devem ser
    adicionados à idade original (age). Esse método deverá retornar o objeto
    que será instanciado._

`this.addAge = function addAge(){
      this.age += arguments[0];
      return this;
   };`

Olá professor!! Boa noite!!! Não entendi as linhas:
`this.age += arguments[0];` e
`return this;`

Tinha entendido que o 'arguments' é para exibir todos os argumentos passados numa função, mas não entendi o uso dele especificadamente aí, poderia esclarecer melhor isso para mim?!
Muito obrigada!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lettcamara! O `arguments` é um tipo de objeto que funciona de forma parecida com o array: ele recebe, em uma lista, todos os argumentos passados para a função.

> Só pra reiteirar: ele funciona de **forma parecida** com um array, mas **não é** um objeto do tipo Array :)

Para acessar cada um desses argumentos, nós fazemos isso usando o índice: o primeiro argumento tem índice `0` (zero), o segundo argumento tem índice `1`, e assim por diante, da mesma forma que um array.

E para "pegar" os valores passados para esses argumentos, nós usamos a mesma sintaxe de array. Então, `arguments[0]` vai retornar o valor passado no primeiro argumento. Se dois argumentos fossem passados, você consegue pegar o segundo usando `arguments[1]` :)

No caso do exemplo, o que vai ser passado para a função `addAge` é um número, que representa "quantos anos" eu quero "aumentar", correto? Logo, nós simplesmente somamos esse valor (que eu pego com `arguments[0]`) na variável `this.age`, que contém a idade atual :) 

Deu pra entender? :)

E sobre o `return this`, você entendeu o propósito? :)

**Comment by fdaciuk** [comment]
Oi @lettcamara! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
