### ISSUE TITLE
dúvida do desafio 26.

### ISSUE THREAD

**Issue by caiomyrapereira** [da2k/curso-javascript-ninja#7486]
olá,tudo bem.
porque você utilizou 'prototype' para atribuir os métodos ??
não é recomendada atribuir dentro da  function usando 'this' ??

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @caiomyrapereira! A ideia de usar o `prototype` é para economizar memória, aproveitando as referências das funções :)

Lembra que vimos que funções são do tipo "objeto", e são passadas por referência? Se você cria os métodos de uma função construtora, colocando-os no `prototype`, a cada novo objeto criado com esse construtor, as mesmas referências desses métodos serão utilizadas, independente de quantos novos objetos você precisar criar.

Agora, se você deixar os métodos dentro da função construtora, como ela tem um escopo próprio, a cada objeto criado, todas as funções serão recriadas, ainda que elas façam a mesma coisa, ocupando assim memória desnecessária no computador onde esse código está utilizado :)

Deu pra entender a ideia? :)

**Comment by caiomyrapereira** [comment]
pelo que entendi os métodos  apontam para mesma memória certo?

**Comment by caiomyrapereira** [comment]
pelo que entendi os métodos  apontam para mesma memória certo?

@fdaciuk

**Comment by fdaciuk** [comment]
Isso mesmo! Para cada objeto criado, os métodos que foram criados no `prototype` irão apontar para a mesma referência dessa função na memória :)
