### ISSUE TITLE
Sobre o challenge-02

### ISSUE THREAD

**Issue by myronrezzo** [da2k/curso-javascript-ninja#7502]
Professor, tudo bem?
Fiz o código de forma diferente da sua resolução. Porém, a meu ver, ele não está incorreto.
O que você acha?

```
function somaMultipla(a, b, c) {
    if (a === undefined && b === undefined && c === undefined) {
        return false;
    } else if (a !== undefined) {
        if (b !== undefined) {
            if (c !== undefined) {
                return (a + b) / c;
            } else {
                return a + b;
            }
        } else {
            return a;
        }
    } else {
        return null;
    }
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Sim, funciona, pode fazer assim se quiser :)
É importante frizar que **não existe código incorreto** se ele funciona como deveria.

O que pode acontecer é um código ser mais complexo e de difícil leitura, ou mais simples, mais fácil de ler, e talvez com menos código (não necessariamente).

Mas nesse primeiro momento do curso, não se preocupe com isso! Teste novas formas de resolver o mesmo problema, assim como você fez com esse! Isso vai te dar uma visão geral do que é melhor, e mais simples de ler :)

Parabéns, é assim mesmo que se aprende :clap: :clap:
