### ISSUE TITLE
Sobre o challenge-05

### ISSUE THREAD

**Issue by myronrezzo** [da2k/curso-javascript-ninja#7511]
Professor, tudo beleza?
Talvez a dúvida fuja um pouco do escopo da aula, mas perguntarei porque ela surgiu aqui.
Fiz o código abaixo e percebi que a propriedade **nomeCompleto** apresenta o valor **_'undefined undefined'_**. Qual forma de atribuir os valores das propriedades **nome** e **sobrenome** à propriedade **nomeCompleto** na definição do objeto?

```
var objectVar = {nome: "Myron",
                sobrenome: "Rezzo",
                nomeCompleto: this.nome + " " + this.sobrenome};

function imprimeObject(objectArg) {
    return objectArg;
}

imprimeObject(objectVar);
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Não é possível fazer dessa forma =)
O único jeito é usando um método no objeto. Mas não se preocupe, pois veremos como fazer isso em aulas futuras :)
