### ISSUE TITLE
Aula 08 - 45 A importância de nomear funções

### ISSUE THREAD

**Issue by myronrezzo** [da2k/curso-javascript-ninja#7525]
Professor, tudo beleza?
Sobre essa aula, percebi o seguinte comportamento, diferente do que foi dito na aula.
Fiz o seguinte código:

```
var func = function() {
	return 'hi!';
}
console.log(func());
console.log(func.name);
```

Só que, na execução de **console.log(func.name);**, o retorno está sendo **func**; ou seja, igual ao nome da variável à qual a função foi atribuída.
Desde a gravação da aula, isso mudou no JavaScript ou é um comportamento novo do Node?
Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Sim, esse comportamento mudou :)

Na verdade, esse é um comportamento do motor que roda a linguagem. No caso do `v8` - motor usado em vários navegadores, como Chromium, Google Chrome, Opera, etc; e no Node.js - esse comportamento foi alterado para facilitar a vida dos desenvolvedores :)

De qualquer forma, a premissa desses motores é sempre "não quebre a web". Então essas alterações não causam problemas em códigos já existentes, apenas facilitam o debug de novos códigos :)
