### ISSUE TITLE
Nao aparece o botão pra editar

### ISSUE THREAD

**Issue by Bobsp2018** [da2k/curso-javascript-ninja#7527]
Boa noite professor! 
Nao aparece o botão pra eu editar!
![Screenshot_1](https://user-images.githubusercontent.com/42824148/66094078-0fbecc80-e569-11e9-9923-db9f379fb9dd.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Bobsp2018! Você deve ter clicado no link "do meio" da lista de desafios, no seu repositório.

Se você clicar nome do arquivo, vai aparecer um "lápis", dando a opção de editar :)

Segue prints pra você conseguir acompanhar:

![Selection_178](https://user-images.githubusercontent.com/487669/66132017-c7d09180-e5ca-11e9-9683-3b057115cf2b.png)

---

![Selection_179](https://user-images.githubusercontent.com/487669/66132098-f0588b80-e5ca-11e9-852f-816557b5348b.png)

---

![Selection_180](https://user-images.githubusercontent.com/487669/66132200-13833b00-e5cb-11e9-8df8-f451c0e3ad8d.png)

---

Acho que isso já vai ajudar :)

Qualquer coisa, só avisar :)

**Comment by Bobsp2018** [comment]
Show! Agora foi!!!

**Comment by Bobsp2018** [comment]
A tempo! Quanto material no curso!!!! Rs obrigaduuuu!

**Comment by fdaciuk** [comment]
Show! Sim, tem bastante conteúdo :D 

Qualquer coisa, só avisar :D
