### ISSUE TITLE
Aula 08 - 46. Introdução à Functional Programming

### ISSUE THREAD

**Issue by myronrezzo** [da2k/curso-javascript-ninja#7530]
Professor, tudo bem?
Na aula, é falado sobre **Funções e Objetos Literais**; porém, não são apresentados exemplos do que seriam os, digamos, objetos e funções "não literais".
Além dos literais, de que outros modos Objetos e Funções podem ser classificados?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Legal, boa pergunta :)
No JavaScript, cada tipo de dado é representado por um objeto que chamamos de "construtor".

Vamos ver sobre construtores mais pra frente no curso. 

Mas, basicamente, alguns tipos de dados têm uma "representação literal" na linguagem. Alguma forma que você simplesmente "usa" alguns caracteres especiais, e o interpretador da linguagem reconhece esses tipos de dados, pela forma como eles foram criados.

Vou dar alguns exemplos pra facilitar o entendimento:

Quando queremos criar um novo objeto, nós podemos criar assim:

```js
var obj = {};
```

As chaves representam a forma "literal" de criar objetos. O interpretador da linguagem entende que, nessa estrutura, ao atribuir as chaves para alguma variável, por exemplo, a intenção é criar um novo objeto :)

Mas também podemos fazer o mesmo usando a função construtora `Object`:

```js
var obj = new Object();
```

Para arrays, mesma coisa:

```js
var arr = [];
```

ou:

```js
var arr = new Array();
```

Os dois códigos funcionam praticamente da mesma forma. Mas a representação literal é mais simples, mais curta, e mais rápida de ser interpretada. 

E cada tipo de dado na linguagem tem a sua própria função construtora (números, strings, booleanos, etc). Mas não se preocupe, pois mais pra frente nós iremos falar mais sobre esse assunto :)
