### ISSUE TITLE
mensagem na hora de clonar

### ISSUE THREAD

**Issue by Bobsp2018** [da2k/curso-javascript-ninja#7536]
![Screenshot_2](https://user-images.githubusercontent.com/42824148/66262611-93232c80-e7ba-11e9-9597-d40bc0f6598f.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Bobsp2018! Tem duas formas de resolver: a mais simples é usar o link com HTTPS para clonar. Dessa forma, você só vai precisar entrar com seu usuário e senha do GitHub pra conseguir clonar.

A outra forma é criando uma chave SSH, e configurando essa chave na sua conta do GitHub. Para fazer isso, é só seguir esses tutoriais do próprio GitHub, com base no seu sistema operacional:
https://help.github.com/articles/connecting-to-github-with-ssh/

Qualquer coisa, só avisar :)

**Comment by Bobsp2018** [comment]
Valeu professor! Deu certo!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
