### ISSUE TITLE
Não entendo.

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7537]
![Untitled-1](https://user-images.githubusercontent.com/19687110/66313001-fc548e00-e8e7-11e9-82e8-edc30024a5ae.jpg)

Olha só, nesse exercício(Desafio aula 8) você fala que "var sum" também é uma função. pelo que eu entendi é por causa disso aqui:

var sum = calculator( operador ) {
              return function( number1, number2 ) { ....

SE TRANSFORMA NISSO AI:

var sum = function( number1, number2 );

* Não sei se você entendeu. Mas a variável "sum" recebe o retorno de calculator e assim "sum" se vira uma função. É isso?

@fdaciuk

**Comment by fdaciuk** [comment]
É isso mesmo @xfelipee! A função `calculator`, quando executada, retorna outra função. E quando você executa `calculator`, você atribui o **retorno** de `calculator` para a variável `sum`. Então `sum` **recebe** o retorno de `calculator`, que é uma função. 

Logo, podemos executar essa função que `calculator` retornou à partir do nome da variável `sum` :)

**Comment by xfelipee** [comment]
Daciuk, eu estou com um problema.

Como um desenvolvedor experiente você deverá me responder.

Eu estou tentando usar a documentacao da MDN para antecipar e revisar alguns assuntos. Mas eu acho ela muito rasa, não tem muitos exemplos e etc. Eu tenho dificuldade de aprende. Imaginemos que não houvessem professores como você, como é que uma pessoa como eu poderia aprender uma linguagem de programação?

**Comment by fdaciuk** [comment]
Oi @xfelipee! O JavaScript é uma das poucas linguagens que possuem documentação precária. Realmente, só pelo MDN, apesar de ter muito conteúdo, ele não abrange tudo o que é necessário para aprender a linguagem.

Esse foi o motivo principal de eu ter criado esse curso =)

Se não for pelo curso, você pode aprender: 
- com livros; 
- artigos pela internet - principalmente em inglês;
- e em projetos mesmo, na "vera", na base da tentativa e erro :)

Eu demorei muito tempo pra conseguir aprender o que eu sei hoje, porque sei como é difícil encontrar bons materiais falando sobre a liguagem em si. Você encontra muita coisa falando sobre DOM, mas pouco sobre a linguagem. Hoje meio que isso mudou um pouco: você consegue encontrar mais conteúdos relevantes na internet falando sobre a linguagem mesmo.

Um site que eu gosto bastante é o https://javascript.info/

Os livros "You don't know JS", do Kyle Simpson, também são um ótimo guia para aprender a linguagem, nos dias de hoje :)

**Comment by fdaciuk** [comment]
Oi @xfelipee! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
