### ISSUE TITLE
Aula 12, vídeo 69: Revisão desafio semana #11 - Parte 1

### ISSUE THREAD

**Issue by myronrezzo** [da2k/curso-javascript-ninja#7543]
Professor, tudo bem?
Por volta de 07:20 do vídeo, você diz (não com essas palavras, mas com esse sentido): usa-se o **for / in** se não se sabe a quantidade de propriedades do objeto. Se você souber, pode-se utilizar o for "normal".

Minha dúvida é como fazer para acessar as propriedades do objeto quando se utiliza um for "normal", já que passaremos a ter números na variável de controle do for e não mais uma string com o nome da propriedade do objeto?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Entendi, e realmente não fui muito claro nessa parte. Vamos lá :)

O que eu quis dizer foi basicamente com relação a iterar arrays ou objetos. Arrays também são do tipo "objeto", mas como eles têm a propriedade `length`, é possível saber o tamanho do array, e assim usar o `for` "normal" para iterá-los.

Já objetos não têm essa propriedade, logo não é possível saber a quantidade de chaves de um objeto, sem antes transformá-lo em um array.

Desculpe não ter sido muito claro nesse ponto, mas o uso é o que eu mostrei mesmo: para iterar objetos, usa-se o `for in`. Para arrays, você pode usar o `for in` ou o `for` "normal" :)

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
