### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by carlosbertarinijr** [da2k/curso-javascript-ninja#7549]
Olá Mestre
Eu formatei o meu pc, aquela velha história de abandonar o NT e entrar no mundo linux.
Porém minha duvida é a seguinte;
Adicionei minha SSH Key no github, atraves da linha de comando, entrei no diretório que eu desejava clonar o meu repositorio aqui do github,com o comando 
git clone git@github.com:carlosbertarinijr/curso-javascript-ninja.git
tudo certo, com a branch selecionada no *master porém quando eu faço o comando para saber a branch que eu estou, eu encontro só a *master e eu tenho 22 Branchs feita. 
como eu faço pra obtelas de volta ? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @carlosbertarinijr! Dá uma olhada na issue #79 que eu respondi isso lá :)
Se ainda ficar alguma dúvida, só avisar :)

**Comment by carlosbertarinijr** [comment]
Muito bom, o dialogo sobre a explicação ficou bem claro! 
Obrigado pela atenção! 
tmj !

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :)
