### ISSUE TITLE
dúvida GIT

### ISSUE THREAD

**Issue by jlsan81** [da2k/curso-javascript-ninja#7553]
Olá! Não tenho muita intimidade com o GIT. Pelo que entendi eu posso fazer tudo pelo navegador. Estou certo? Prefiro assim porque faço no trabalho e em casa. E no trabalho tem muita restrição, sendo pela internet fica possível. 

Pergunto isso porque já fiz 3 exercícios e não entendi como recebo a informação que o exercício está correto. Também não vi nenhum comentário corrigindo algo. Será que fiz algo errado no envio dos desafios?

Se puder verificar se vc visualiza meus 3 desafios eu agradeço. Abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jlsan81! Na aula anterior ao primeiro desafio, eu deixei um conteúdo em texto, dizendo que o PR não é necessário :)

Apenas tente resolver os desafios na sua máquina, e acompanhe a correção do desafio sempre no início da próxima aula. 

E se surgir qualquer dúvida, fique à vontade para abrir uma issue aqui, ok? :)

Estou à disposição para ajudar :)

**Comment by fdaciuk** [comment]
Oi @jlsan81! Vou fechar a issue, mas se ainda tiver dúvidas com relação a esse assunto, só avisar que a gente reabre, ok? :)
