### ISSUE TITLE
Aula #8 - Vídeo 45 - Funções nomeadas 

### ISSUE THREAD

**Issue by brunogbr** [da2k/curso-javascript-ninja#7561]
```
var func = function(){ return 'hi';}
console.log(func()); // hi 
console.log(func.name); // retorna 'func' (no vídeo retorna string vazia)
```

Nesta aula é falado que para função retornar o NAME, é preciso nomeala, mas o exemplo acima ao ser executado retornou "func" para mim e não string vazia como é no vídeo, algo mudou na linguagem para que isso ocorra?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brunogbr! Esse comportamento foi alterado nos motores que rodam o JavaScript. Agora o nome da variável é atribuído à propriedade `name` da função, quando essa é anônima :)
