### ISSUE TITLE
Acesso :(

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#757]
A senha é essa e ainda continua dando o mesmo problema quando eu coloco na Aula #7
**, quando eu entro só consigo visualizar as mesmas aulas.

**Comment by grodrigues** [comment]
da #1 aula até #6 aula.

**Comment by grodrigues** [comment]
Quando eu termino de Assistir a #6 não passa para a #7 e adiante.

**Comment by fdaciuk** [comment]
@grodrigues te mandei inbox com as instruções =)
