### ISSUE TITLE
Aula 05

### ISSUE THREAD

**Issue by Marcelosilva10** [da2k/curso-javascript-ninja#7580]
Crie uma função chamada `book`, que recebe um parâmetro, que será o nome do
livro. Dentro dessa função, declare uma variável que recebe um objeto com as
seguintes características:
- esse objeto irá receber 3 propriedades, que serão nomes de livros;
- cada uma dessas propriedades será um novo objeto, que terá outras 3
propriedades:
    - `quantidadePaginas` - Number (quantidade de páginas)
    - `autor` - String
    - `editora` - String
- A função deve retornar o objeto referente ao livro passado por parâmetro.
- Se o parâmetro não for passado, a função deve retornar o objeto com todos
os livros.

Fernando minha dúvida é a seguinte, sei que vai passar o nome do livro no parâmetro dessa função, mas quando entra na hora de ter que declarar um variável dentro dessa função eu fiquei com uma dúvida, ela vai passar dentro de variável dois objetos uma com o nome de 3 livros e outra com as descrição de autor, quantidade de páginas e editora, ou vai ter um objeto e que nesse objeto vai chamar o nome do livro, autor, quantidade de páginas e editora?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Marcelosilva10! A ideia é ter um objeto só. 

Como objetos são tipos de dados chave/valor, a chave será o nome do livro, e o valor, um novo objeto com as informações do livro :)

Mas tudo isso dentro de um único objeto principal :)

Qualquer coisa, dá uma olhada na correção desse desafio, no início da próxima aula, que acredito que vai ficar mais claro a ideia :)

**Comment by Marcelosilva10** [comment]
Olá @fdaciuk vou dar um olhada na correção, estou achando um ótimo curso, muito obrigado! :)
Espero começar a fazer o seu curso de React também.

**Comment by fdaciuk** [comment]
Perfeito @Marcelosilva10! Qualquer coisa, só avisar :)
