### ISSUE TITLE
Fiz o último commit challenge 06

### ISSUE THREAD

**Issue by Marcelosilva10** [da2k/curso-javascript-ninja#7615]
Fernando tudo bem?
Eu fiz meu pull request pelo terminal sobre o challenge 06 e provavelmente subiu sudo que estava na master com os demais exercícios resolvido, preciso fazer um git revert para que mande novamente da maneira correta para  você? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Marcelosilva10! Não precisa se preocupar com isso, fique tranquilo :)

Inclusive, se não quiser, não precisa mandar os PRs. Apenas tente resolver os desafios no seu computador, ok?

O importante é praticar!

**Comment by Marcelosilva10** [comment]
Sem, dúvida próximo passo e arrumar um home office o que mais sonho.
Obrigado!
@fdaciuk

**Comment by fdaciuk** [comment]
Show de bola! Siga firme estudando e praticando, que o sonho vem :D
