### ISSUE TITLE
Sobre o challenge-27 (métodos estáticos)

### ISSUE THREAD

**Issue by myronrezzo** [da2k/curso-javascript-ninja#7643]
Fernando, tudo beleza?
Houve alguma mudança na forma de declarar métodos estáticos?
Pergunto isso porque não consegui fazer da seguinte forma:
 ```
 DOM.prototype.isArray = function (val) {
    <código>
  }
```
Mas funciona perfeitamente quando uso assim:
```
  DOM.isArray = function (val) {
    <código>
  }
```

Quando uso a palavra-chave **prototype**, recebo o seguinte erro no console:

> Uncaught TypeError: DOM.isArray is not a function

É isso mesmo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @myronrezzo! Realmente a forma como você fez é que está correta =)

Eu adicionei uma nota logo após esse vídeo para explicar essa situação, mas a forma correta é exatamente essa que você fez, sem o `prototype` =)
