### ISSUE TITLE
NÃO ENTENDO

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7671]
![Screenshot_2019-11-12 JS Bin](https://user-images.githubusercontent.com/19687110/68658429-2c5d0580-0514-11ea-9128-20161fd75a33.png)
![Screenshot_2019-11-12 JS Bin2](https://user-images.githubusercontent.com/19687110/68658440-34b54080-0514-11ea-8993-b50abf66f5c6.png)

Olá, as dúvidas são as seguintes:

- Por que a variável numeros está declarada com ""; e o que isso signifca?
- Por que na execução do for da primeira imagem no final tem **i + "";**  o que significa essas **""** no final? 
- Na segunda imagem a variavel respostas também está declarada com = ""; ela entrada em baixo, na execução como o que? undefined, null ou como as "" mesmo? (exemplo: resposta + "" + numero + " x " ...) 

Espero que tenha ficado claro, abs

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Até que parte do curso você assistiu? Pergunto isso porque a resposta para essas suas dúvidas estão logo nas primeiras aulas do curso :)

Dá uma olhada lá de novo, e se ainda tiver alguma dúvida, pode voltar aqui que eu te ajudo, beleza? :)

**Comment by xfelipee** [comment]
Boa tarde, estou na aula 10. Eu já fiz revisão das aulas já, e não vi isso. Mas de qualquer forma agradeço. Abraço.

**Comment by xfelipee** [comment]
Talvez você não tenha entendido. A minha pergunta não é sobre concatenação. É sobre declarar uma variável dessa forma: var variavel = ""; e a inclusão de "" na execução numeros = numeros + i + "";. Eu não entendi essas duas questões, não sei o que significa uma variável declarada com = ""; e essa essa incrementação de "" no final da execução. Me desculpe tomar seu tempo, isso é de uma livro que estou lendo.

**Comment by fdaciuk** [comment]
Ah, ok! Realmente eu não tinha entendido dessa forma, vamos lá :)

Basicamente, a variável foi inicial com uma string vazia. Lembra que vimos que strings podem ser reprentadas tanto por aspas simples como por aspas duplas? É basicamente o que está acontecendo ali: a variável está sendo iniciada com o tipo de dado que será usado após sua modificação. Ela começa como uma string vazia, e depois é modificada, dentro do `for`, mas o valor da variável, apesar de alterado, continua sendo do tipo string. Esse é o motivo dela ser inicializada com `""`.

Já no momento da concatenação, provavelmente o autor escreveu o código dessa forma apenas para "garantir" que o valor final será uma string. Olhando para esse exemplo, as aspas no final são desnecessárias, mas pensando no caso de que o valor da variável `numeros` poderia ser um número, não uma string, quando você usa o operador `+` com números, ele os soma. Já se um valor é número, e o outro é uma string, os dois valores são concatenados.

Então a string vazia no final é só para garantir que a variável vai continuar sendo uma string, e não será convertida para número :)

Desnecessário, mas provavelmente foi esse o motivo usado :)

Deu pra entender? :)

**Comment by xfelipee** [comment]
Obrigado, me desculpe por tomar o seu tempo.

**Comment by fdaciuk** [comment]
Jamais meu caro, é um prazer ajudar :)
Pergunte sempre que tiver dúvidas :)
