### ISSUE TITLE
Instalação do Github - Dúvida

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#769]
Essa  linha instala todas as dependências do github da fonte do git?

$ yum install curl-devel expat-devel gettext-devel \
  openssl-devel zlib-devel

**Comment by fdaciuk** [comment]
@grodrigues o GitHub é a plataforma que a gente usa para colocar repositórios git. Você quer instalar o git na sua máquina? 

Se for isso, só acesar: https://git-scm.com/

E baixar a versão para o seu sistema. É isso que vc quis dizer?

**Comment by grodrigues** [comment]
Mas essa Linha faz essa instalação via terminal?

$ yum install curl-devel expat-devel gettext-devel \
openssl-devel zlib-devel

**Comment by fdaciuk** [comment]
Para instalar o git via terminal, veja aqui qual a sua distribuição e o comando correto para ela: 
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by grodrigues** [comment]
Ok
