### ISSUE TITLE
Aula 10

### ISSUE THREAD

**Issue by Marcelosilva10** [da2k/curso-javascript-ninja#7697]
Estou com a seguinte dúvida @fdaciuk estou passando o código do exercicio aula 10, e estou com a seguinte dúvida, durante a ação de buscar o parâmetro estabelecido dentro do objeto, conforme a correção vi essas duas funções.

Minha dúvida é isso, quando você passa o parâmetro errado, dentro função com o símbolo que está definido no objeto, por acaso ele percorre aonde tem condição IF da primeira função ou ele anula esse execução e passa diretamente na segunda função.  OBS Cliquei no preview e não apareceu os códigos que mencionei, se aparecer para você me avise dai.

```js
function calculator(operator) {
        if( !isOperatorValid(operator) ) {
            return false;
        }
        return function (number1, number2) {
            if( typeof number1 !== 'number' || typeof number2 !== 'number') {
                return false;
            }
            return operation[operator](number1,number2);
        };
    }

function showErrorMessage(operator) {
        return 'Operação "'+ operator +'" não permitida!';
    }
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Marcelosilva10! Editei sua mensagem para aparecer os códigos :)
Só precisa colocar eles junto com a sua mensagem, não na mensagem de exemplo que eu deixei, ok? :)

Vamos à sua dúvida:
Veja que, ao executar a função `calculator`, temos dois possíveis retornos:
- `false`, se o valor passado para `operator` não for um operador válido;
- uma nova função, se não passar no `if` acima.

Como usamos o `return` dentro do `if`, se por acaso a condição for verdadeira, e o corpo do `if` for executado, todo o restante da execução da função será ignorado, já que usamos o `return false` dentro do `if` :)

Já se o operador passado for válido, o corpo do `if` será ignorado, e a outra função será retornada :)

Ficou claro? :)

**Comment by Marcelosilva10** [comment]
Entendi então quer dizer que se cair no primeiro if, ele chama a função showErrorMessage, e mesma coisa que se cair com valores errados, suponhamos que eu coloque uma letra na no number1 automaticamente ele vai entrar no return false, e vai chamar a função showErrorMessage.

**Comment by fdaciuk** [comment]
Não exatamente. São dois momentos diferentes: quando você executa calculator, e passa um operador inválido (algo como `var sum = calculator('arroz')`), o retorno dessa função será `false`.

Se essa primeira execução já retornar `false`, significa que o operador é inválido, pois é a primeira validação que fazemos na função. Então a variável `sum` recebe `false`.

Então, antes de fazer qualquer coisa, nós verificamos se o valor de `sum` é `false`. Se for, então nós chamamos a função `showErrorMessage`, dizendo que o operador é inválido.

Se o valor não for `false`, significa que passou desse primeiro `if`, e a variável `sum` vai receber o retorno de `calculator` que está fora do `if`. No caso, uma função que espera dois números.

Aí é outro momento: passamos da primeira validação, logo `sum` não é `false`, e sim uma função.

Se é uma função, podemos executá-la, correto? E essa função espera que dois números sejam passados. Dentro dessa função tem uma outra validação, para checar se os valores passados são realmente números. Se não forem, essa outra função retorna `false`, para que possamos validar isso também.

No exemplo eu não mostrei uma validação para essa segunda parte, mas ela poderia ser feita: só precisamos verificar se o valor retornado pela execução dessa função é `false`. Seria algo como:

```js
var result = sum('a', 1);
if (result === false) { // aqui testamos exatamente por false, pois um cálculo matemático pode retornar zero, que também é falsy. Então usamos "if (result === false)" ao invés de "if (!result)"

  // aqui vc pode exibir uma mensagem de erro
  console.log('Os dois valores passados devem ser números.');
} else {
  // aqui vc faz alguma coisa com o resultado final :)
}
```

Pegou a ideia? :)

**Comment by Marcelosilva10** [comment]
Peguei sim, ele faz dois tratamento de erro, como ele passa na validação retornando com um parâmetro válido, ele entra no retorno da função como localizado o parâmetro do objeto, sendo que se ele for inválido ele já é barrado em duas condições de testes, com o parâmetro inexistente dentro do objeto.

Vi umas duas suas aula por aqui, até compreender como funções é muito da hora, vlw por explicar. :)

**Comment by fdaciuk** [comment]
Perfeito meu caro! Qualquer dúvida, fique à vontade para perguntar :)
