### ISSUE TITLE
Aula 04 - Desafio - Parte adicionar pessoas

### ISSUE THREAD

**Issue by brandaoti** [da2k/curso-javascript-ninja#7710]
```
carro.adicionarPessoas = function(qtdPessoas){
    
    var totalPessoas = carro.quantidadePessoas + qtdPessoas;

    if(carro.quantidadePessoas === carro.assentos){ 
		return 'O carro já está lotado!';
    }

      //Chamando fora do IF pra verificar se vai funcionar o retorno final
        var pessoaSingular = qtsPessoasCabem === 1 ? 'pessoa': 'pessoas';

	if(totalPessoas > carro.assentos){
        var qtsPessoasCabem = carro.assentos - carro.quantidadePessoas;

        /* //define se vai ser singular ou plural, quando só restar 1 vaga
            var pessoaSingular = qtsPessoasCabem === 1 ? 'pessoa': 'pessoas';
        */
        return `Só cabem mais ${qtsPessoasCabem} ${pessoaSingular}!`;
    }

    carro.quantidadePessoas += qtdPessoas;
    
    //Chamei aqui o pessoaSingular, pra definir quando no incio add 1 pessoa
    return `Já temos ${carro.quantidadePessoas} ${pessoaSingular} no carro!`;     
};
```
-->
Boa noite professor, referente a parte de adicionar pessoas, ate ai beleza, conseguir fazer uma parte, e outra sentir dificuldade e fui vê a correção. 
Na parte do retorno `Já temos ${carro.quantidadePessoas} ${pessoaSingular} no carro!`;

Definir também o ${pessoaSingular} pra aparecer 1 pessoa, quando add 1 unica pessoa no carro, 
porem não define o nome, e continua tipo: 1 pessoas, ao invés 1 pessoa.

Tentei usar a chamada fora do IF pra ver se funcionaria mas ainda assim nada...

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brandaoti! Você chegou a ver essa parte na correção do desafio? Eu mostro como resolver essa parte lá :)

**Comment by brandaoti** [comment]
Olá @fdaciuk , assistir todo conteúdo da aula, mas possa ser que tenha me passado realmente. Só vi a chamada dentro do ir no retorno.. não vi concatenar pluralOrSingular no retorno final.

Mas obrigado pelo retorno. Estou aprendendo bastante com o curso.

Boa tarde.

**Comment by fdaciuk** [comment]
@brandaoti mil desculpas! Acabei de ver aqui que a parte que você comentou realmente não está na correção. O que foi feito o tratamento do singular / plural foi apenas a parte de quantas pessoas cabem no carro :)

Mas fazer essa parte final é bem simples, acompanhe comigo:

Veja que a quantidade de pessoas está sendo exibida corretamente, certo? A quantidade de pessoas **dentro** do carro, e a quantidade de pessoas **que cabem** no carro são valores diferentes. Então não podemos reutilizar a mesma variável de singular / plural para as duas mensagens, precisamos criar uma variável diferente para tratar esse caso.

Para fazer isso, podemos criar uma variável no final da função, logo antes do `return`, verificando se `carro.quantidadePessoas` é igual a 1. Se for, a palavra é "pessoa". Senão, a palavra é "pessoas". E então só precisamos concatenar essa variável na frase final, que foi retornada da função :)

Deu pra entender a ideia? :)

**Comment by brandaoti** [comment]
@fdaciuk, muito obrigado pelo retorno, acompanhei sua ideia. Vou fazer essa verificação, obrigado novamente professor

**Comment by fdaciuk** [comment]
Show de bola! Desculpe mais uma vez pela falha :)
E fique à vontade para perguntar sempre que tiver dúvidas :)
