### ISSUE TITLE
Dúvida com o método some

### ISSUE THREAD

**Issue by Marcelosilva10** [da2k/curso-javascript-ninja#7742]
Minha dúvida é a seguinte sei que está usado o a condição ternário de if e else no console, mas quando eu uso o if e else dentro da function some, o console da outra resposta ele da loop e verifica todos os items desse array até achar o nome Ceará isso é normal ou tem algo de errado que fiz?

```
 console.log( '\nCeará está incluído em `brasil`?' );
    var some = brasil.some(function(item){
        return item === 'Ceará';
    });
    console.log(some ? 
        "Ceará está incluído!"
        :
        "Ceará não foi incluído :(");


```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Marcelosilva10! Consegue me mostrar como você está fazendo que está dando problema?

**Comment by Marcelosilva10** [comment]
Nessa seguinte maneira.

    console.log( '\nCeará está incluído em `brasil`?' );
    var some = brasil.some(function(item){
        if(item === 'Ceará'){
            return 'Ceará está incluído!';
        }
        return 'Ceará não foi incluído :(';
    });
    console.log(some);

**Comment by fdaciuk** [comment]
Certo, vamos lá: Nós vimos em aula alguns métodos que usamos para iterar arrays. Cada método, além de iterar o array, faz alguma ação específica. E para fazer essa ação, esse método depende exclusivamente do retorno da função passada para esse método.

No caso do `some`, esse método espera que seja passada uma função, e que o **retorno dessa função** seja sempre um valor **booleano** (`true` ou `false`).

E o resultado da execução do `some` vai também retornar um valor booleano.

Quando fazemos o retorno `return item === 'Ceará'`, o que está sendo retornado é um valor booleano, pois, antes de fazer o retorno, a expressão `item === 'Ceará'` será avaliada. 

Lembre-se que o operador de comparação `===` verifica se os dois operandos são iguais (ou, se tratando de objetos, são a mesma referência), e retorna `true` caso verdadeiro, e `false` caso contrário.

No caso do seu código você sempre está retornando uma **string** na função passada para o `some`. Como o `some` sempre espera um valor booleano, essa string será transformada no seu equivalmente booleano. Strings com qualquer conteúdo, transformando para booleano, irão retornar `true` (lembra das primeiras aulas do curso que falamos sobre isso?). Logo, o seu código é exatamente o mesmo que fazer:

```js
var some = brasil.some(function (item) {
  return true;
});
```

Por isso não funciona conforme esperado, já que a expresão sempre vai retornar `true`. Ficou claro? :)

**Comment by Marcelosilva10** [comment]
Entendi, isso faz com que ele passe por todo o array até fazer uma busca no elemento solicitado, é isso.
por isso que eu observei que ele passava no parametro zero dava o segundo return e por assim vai até encontrar dentro do array a busca que era compatível com a condição do if.

**Comment by fdaciuk** [comment]
Na verdade o `some` vai retornar `false` por padrão, a menos que algum item do array case com a expressão e retorne `true`. No caso do seu exemplo, ele não deve passar do primeiro item do array, já que, independente da iteração, o resultado é sempre o equivalente booleano para `true` :)

Se quiser fazer o teste, coloque um `console.log` logo no início do seu `some`, para exibir o `item`, que você vai ver que só o primeiro será exibido :)

**Comment by Marcelosilva10** [comment]
ótimo entendi ele buscar qualquer valor desse array e busca esse valor como true,
var some = brasil.some(function(item){
   console.log(item);
    if(item === 'Ceará'){
        return 'Ceará está incluído!';
    }
    return 'Ceará não foi incluído :(';
});
console.log(some);

No console.log veio o estado do Paraná que é o primeiro item do meu array, meu é muito top isso. vlw

**Comment by fdaciuk** [comment]
Exatamente! Por isso você precisa fazer a exibição da frase **fora do some** :)
