### ISSUE TITLE
Novo Repositorio

### ISSUE THREAD

**Issue by brandaoti** [da2k/curso-javascript-ninja#7746]
Olá, boa noite, como posso adicionar em um novo computador a fork que fiz?
Por exemplo, como estou viajando, estou utilizando um notebook pra estudos, o principal é um PC e esta meu repositório.
Estou querendo criar outro local em um notebook, e ter acesso as branch que já criei e as tarefas.

Nesse caso, é só fazer um clone do repositório referente ao meu fork, e setando na pasta que criei, ?
Obrigado. 
Att Daniel

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brandaoti! Dá uma olhada na issue https://github.com/da2k/curso-javascript-ninja/issues/79 que pode te ajudar com isso :)

**Comment by brandaoti** [comment]
Opa! Acabei de da uma olhada, muito obrigado.  Então só é preciso iniciar o comando  [ for remote in `git branch -r | grep -v master `; do git checkout --track $remote ; done ]

Então, nesse caso não é preciso fazer outro clone?  add um remote seria a mesma coisa de um clone?

Achava que precisava pegar o repo do meu fork, no sua explicação, entendi que preciso pegar do seu principal.

Se for isso, entendi, muito obrigado...

**Comment by fdaciuk** [comment]
Primeiro você faz o clone do seu repositório, depois roda esse comando para ele baixar todas as branchs que estão no seu repo :)

**Comment by brandaoti** [comment]
Ah sim! Muito obrigado, estava até assistindo as aulas de git ninja pra ver se tinha algo referente.
Vou fazer os teste aqui.

Até a próxima dúvida rs

**Comment by fdaciuk** [comment]
haha! Show :)
Qualquer coisa, só avisar :)
