### ISSUE TITLE
Exercício 06 -Campeonato, forma de resolução

### ISSUE THREAD

**Issue by felrespin** [da2k/curso-javascript-ninja#7753]
Olá Fernando , parabéns pelo curso! Estou gostando da curva de aprendizado. 
Só queria esclarecer 2 dúvidas .

Dúvida 01 - 
Seção 6 aula 06 -  33- revisão 05 p 2
 Nó código 
```
function myFunction2 (arr, index) {
     return arr [index];
}
```
poderia ser escrito?
```
function myFunction2 ([], index) {
     return [] index;
```
Duvida 02 
Em relação ao exercício do campeonato, eu entendi que era para fazer algo muito mais complexo parecido com exercício dos livros. Já olhei a correção, bem mais simples. Mas como seria a resolução? E se em algum momento o que pensei seria útil? Também não consegui finalizar.
Desde já obrigado!

```
function showTeamPosition(position) {
	var allTeams = {
		1: 'Flamengo',
		2: 'Santos',
		3: 'Palmeiras',
		4: 'Grêmio',
		5: 'Athlético-PR',
	};

	allTeams = position;
	return position;
}

showTeamPosition(1);

if (showTeamPosition() < 1 || showTeamPosition() >5) {
	console.log('Não temos a informação do time que está na ' + position + 'ª posição.');
} else {
	console.log('O time que está em ' + position + 'º lugar é o ' + [TIME] + ' .');
}

```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felrespin! Vamos lá :)

A primeira coisa que eu recomendo é que você sempre teste os códigos que você acha que poderiam funcionar. É sempre legal ver as mensagens de erro que a linguagem dispara, e dá pra aprender muito com isso! :D 

Sobre as suas dúvidas:

**Dúvida 01:**

O código não pode ser escrito dessa forma, por alguns motivos:
- No momento da declaração da função, os parâmetros precisam ser nomeados com nomes válidos para variáveis, pois esses parâmetros nada mais são que variáveis, que irão receber os valores passados via argumento quando a função for executada. Você não pode ter um parâmetro nomeado como `[ ]`, pois esses caracteres, na linguagem, significam a criação de um novo array. Isso seria um valor, não um nome válido de parâmetro. 

Se você tentar executar esse código, deve obter um `SyntaxError`, ou **Erro de Sintaxe**, já que o interpretador do JavaScript não vai entender o que você estava querendo fazer, pois essa sintaxe é inválida :)

- O segundo ponto é o retorno da função: `return [] index;`

Isso também daria um erro de sintaxe, visto que `[]` vai representar a criação de um novo array, e então você simplesmente passa uma variável ao lado.

A ideia de usar a sintaxe `arr[index]`, é porque o parâmetro `arr` recebeu um array quando a função `myFunction2` foi executada. Pense nessa sintaxe mais ou menos da seguinte forma:

Atribuindo um array a uma variável:

```js
var arr = [1, 2, 3, 4, 5]; // a variável `var` recebe um array [1, 2, 3, 4, 5]
```

Passando um array via argumento para uma função:

```js
function myFunction2 (arr, index) {
  // aqui dentro, o parâmetro `arr` é uma variável, que recebe o array [1, 2, 3, 4, 5]. Parecido com o exemplo da atribuição, mostrado acima :)
}

myFunction2([1, 2, 3, 4, 5], 2); // aqui nós invocamos a função, passando o array [1, 2, 3, 4, 5] no primeiro argumento, que será recebido lá dentro da função pelo parâmetro `arr` :)
```

Ficou claro essa parte? :)

---

**Dúvida 02:**

No seu exemplo, você cria uma variável chamada `allTeams`, e atribui a ela 5 times, em um objeto com chaves numéricas. Mas logo na linha abaixo, você **reatribui** o valor da variável `allTeams`, e diz que agora ela não é mais um objeto, e sim o valor de `position`, passado via argumento para essa função.

E depois só retorna o valor de `position`. No final das contas, o que você fez é similar a fazer apenas:

```js
function showTeamPosition (position) {
  return position;
}
```

Deu pra entender? Como cada função cria um escopo próprio, a variável declarada **dentro da função** não pode ser acessada **fora** da função. Se você declara uma variável dentro de uma função, mas não faz nada com ela, é a mesma coisa que você nem ter criado essa variável :)

Outro detalhe importante: após a definição da função `showTeamPosition`, você executa essa função, mas não faz nada com o valor retornado dela:

```js
showTeamPosition(1);
```

Ao fazer isso, a função retorna o valor `1` (já que você disse que a função deveria retornar `position`), mas você não faz nada com esse valor. Logo, o retorno é ignorado.

E depois, no `if`, você executa novamente a função, mas não passa nenhum argumento para ela:

```js
if (showTeamPosition() < 1 || showTeamPosition() >5) {
	console.log('Não temos a informação do time que está na ' + position + 'ª posição.');
} else {
	console.log('O time que está em ' + position + 'º lugar é o ' + [TIME] + ' .');
}
```

Nesse caso, quando você não passa argumentos para uma função, e a função espera algum valor, esse valor é recebido como `undefined` (lembra lá do desafio da semana 2?) :)

Por isso esses seus exemplos não funcionam. Mas a ideia é essa mesmo: tentar coisas diferentes do que está sendo mostrado, e ver qual o resultado disso! Dá pra aprender bastante coisa dessa forma!

E sempre que tiver dúvidas, pode perguntar, ok? Estou sempre à disposição para ajudar :)

No mais, deu pra entender porque o seu código não funciona? :)

**Comment by felrespin** [comment]
Bom dia, Fernando! 
Obrigado pelos esclarecimentos!
Entendi , vou seguir o curso e no final vou rever essa ideias paralelas que tiver como fixação do aprendizado.
Qualquer dúvida eu grito!
Valeu!
Felipe Resende
