### ISSUE TITLE
Dúvida ao clona repositorio 

### ISSUE THREAD

**Issue by jscarmo** [da2k/curso-javascript-ninja#7754]
Professor realizo os procedimentos de clone do repositório conforme é demonstrado no desafio 02, consigo clonar normalmente mais quando executo o comando git branch o mesmo só me retorna o branch master. 
Poderia me explicar o motivo

@fdaciuk

**Comment by brandaoti** [comment]
Você pode ir criando suas branch de acordo com  suas necessidade..

Como você clonou o repositório digamos em "produção" veio apenas a master, o ideal é você criar por exemplo; " git checkout -b desafio-02, e dentro dela você pode fazer o exercício. Depois é fazer os commits e da um git push origin desafio-02 .
E sobe o pull request...

Mas aguarda @fdaciuk explicar direitinho, pode ter sido equívoco meu pensar dessa forma, mas na minha máquina funciona  😅

Bom estudo.

**Comment by fdaciuk** [comment]
Oi @jscarmo! Te respondi lá pela Udemy, mas dá pra seguir tranquilamente essa ideia que o @brandaoti passou! Obrigado Daniel :)

Vou responder aqui também, se mais alguém tiver essa dúvida: para clonar todas as branchs já criadas, você só precisa seguir os passos dessa issue:

https://github.com/da2k/curso-javascript-ninja/issues/79

Se ficar qualquer dúvida, só avisar :)
