### ISSUE TITLE
Referente aos Challenges

### ISSUE THREAD

**Issue by brandaoti** [da2k/curso-javascript-ninja#7763]
Boa noite professor.
Bem, estava pensando em criar um repositório meu com os desafios do seu curso, se não houver problema com isso, claro.
Estarei dando créditos ao curso, com link da udemy, e outras indicações caso queria que eu faça.

Sei que já faço os pull com os desafios..
Dessa vez queria jogar os exercicios na master do repor que pretendo criar, já ficando com as resoluções, nesse caso as minhas rs, 

Acho que pode ajudar em  manter o meu github mais ativo, afim de recrutadores no futuro vê as atividades.

Também gostaria que se possível dá dicas de portfólio pra já ir montando.
Você faz monitoria? auxiliar mais de 'perto, online' as pessoas?

 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brandaoti! Claro, pode criar o repositório sem problemas :)

Mentoria individual, infelizmente eu não consigo fazer. Mas sempre que tiver dúvidas, pode postar aqui, o se for algo específico que não possa ficar público, pode postar no privado da Udemy, que eu vou te ajudando sem problemas :)

**Comment by brandaoti** [comment]
Muito obrigado professor.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
