### ISSUE TITLE
NÃO ENTENDO! 

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7786]
![Screenshot_2019-12-12 Function expressions](https://user-images.githubusercontent.com/19687110/70681635-c67ead80-1c7a-11ea-97f8-0190c2235ee0.png)
The Function Declaration (1) creates the function and puts it **into the variable named** sayHi
Pode me esclarecer isso ai? - "Dentro de uma variável chamada..." -

@fdaciuk

**Comment by Daanlc** [comment]
@xfelipee quando tu declara uma função, você a atribui a uma variável que no caso seria o nome da função, sayHi, se fizer a chamada de sayHi() você chama sua função e se chamar apenas sayHi você chama a variável que contém a função

**Comment by xfelipee** [comment]
ok

**Comment by xfelipee** [comment]
Na verdade ainda não entendi.

sayHi < --- é uma variável?

"se chamar apenas sayHi você chama a variável que contém a função..."

Isso ai ficou meio confuso. 

pelo que estou entendendo a função é "{ }", function é a palavra chave e variável que contém a função é sayHi!

**Comment by Daanlc** [comment]
> Na verdade ainda não entendi.
> 
> sayOi <--- é uma variáve, certol?
> 
> **"se chamar apenas dizerOi, você chama uma variável que contém uma função ..."**
> 
> Isso ai ficou meio confuso.
> 
> pelo que estou entendendo a função "{}", a função é a palavra-chave e a variável que contém a função é sayHi!
> 
> * Não seria ... "você chama o valor da variável" sayHi "..." ???

![Screenshot_20191212-065535_JS Run](https://user-images.githubusercontent.com/26926844/70702221-82a49c00-1cac-11ea-97df-639d07854b1d.jpg)

**Comment by xfelipee** [comment]
Isso eu entendi perfeitamente. A questão não é essa. A questão é que eu não sabia que "sayHi" é uma variável, eu queria apenas uma explanação sobre isso.

**Comment by fdaciuk** [comment]
Oi @xfelipee! No curso tem uma aula falando especificamente sobre isso :)
No seu exemplo, `sayHi` é o nome da função. Mas funções são o que chamamos de "cidadãos de primeira classe" em JavaScript. Isso significa que, como qualquer outro tipo de dado (strings, number, boolean, objetos, etc), funções também podem funcionar da mesma forma:
- Vc pode criar uma função literal (assim como cria um objeto literal com `{}`);
- vc pode atribuir uma função a uma variável (assim como faz com um objeto ou qualquer outro tipo de dado);
- vc pode passar funções como argumento para outras funções;
- e o poder maior das funções: você pode EXECUTÁ-LAS, usando o operador `()` :D 

Funções são referências em memória. Você pode ter acesso a essa referência usando o nome da função (sem executar, ou seja, sem usar os parênteses), e passar para uma variável, por exemplo, fazendo com que a variável aponte exatamente para o mesmo espaço de memória que essa função se encontra :)

No curso eu explico isso em detalhes :)

Alguns conteúdos que podem te ajudar:

Escrevi um artigo sobre funções, bastante útil:
https://blog.da2k.com.br/2015/01/30/javascript-como-invocar-funcoes/

Esse artigo que escrevi sobre referências também é muito importante:
https://blog.da2k.com.br/2017/01/25/objetos-referencias-de-valores-em-javascript/

E dei uma palestra no Front in Sampa ano passado, falando sobre imutabilidade, que tem muito a ver com a sua dúvida também, dá uma olhada:
https://www.youtube.com/watch?v=eKka6vj1uig

Esses conteúdos, além do que foi passado no curso, vai te ajudar a entender o que acontece nesse código :)

Qualquer dúvida, só avisar :)
