### ISSUE TITLE
o site hospedado no meu github não atualiza

### ISSUE THREAD

**Issue by garaguns** [da2k/curso-javascript-ninja#7797]
o site hospedado no meu github não actualiza.
eu actualizei e dei o commit do meu projecto no git como sempre fiz, só que quando eu clico no link do site hospedado no git que deixei na descrição ele continua desactualizado.

no git em si esta actualizado todas as pastas e arquivos que fiz, o commit mostra tudo certo
o que posso fazer pra arrumar isso?

https://garaguns.github.io/Renan-Marques-Portif-lio/.
https://github.com/garaguns/Renan-Marques-Portif-lio

**Comment by fdaciuk** [comment]
Oi @garaguns! O GitHub só aceita sites estáticos. Pelo que vi, você tem arquivos PHP no seu projeto. Eles não irão rodar aqui. Pra isso, você precisa de uma hospedagem específica para PHP.

Bom, vou fechar a issue, pois ela não tem relação com o curso, ok? :)

**Comment by Joao-Amancio** [comment]
O meu não PHP é dando o mesmo problema.
