### ISSUE TITLE
Dúvida sobre if e else

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7802]
![nentendo](https://user-images.githubusercontent.com/19687110/70956606-41690f00-2053-11ea-805c-a8ecab5c75e3.jpg)

Olá, Fernando!

Não sei se você precisa do resto do código, caso precise eu tirarei um print maior.

Minha dúvida é, esse "if" aninhado dentro do "else" poderia ser colocado do lado de fora sem interferir no resultado ou no desempenho do código?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Isso vai depender muito do resultado esperado. É importante tentar não aninhar ifs, pois ifs aninhados deixa o código bem mais difícil de compreender.

Mas pra saber como melhorar esse código, tirando esse aninhamento, só tendo uma visão geral dele, e entendendo qual o objetivo do mesmo :)
