### ISSUE TITLE
NÃO ENTENDO - "use strict"

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7804]
![nentendo](https://user-images.githubusercontent.com/19687110/71116329-ba32ad00-21b2-11ea-9173-811fb51ef22d.jpg)

Olá Fernando!

**Video 94**
- Minha mensagem apareceu diferente da do vídeo, para não ficar na dúvida eu resolvi perguntar(atribuição para variável não declarada "o").
- Da no mesmo ? Tem algo relacionado ao ES6? 
- "Declarada" e "Definida", são sinônimos em JS?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! O Firefox exibe uma mensagem de erro um pouco diferente, mas o significado é o mesmo: "declarada" e "definida" podem ser considerados o mesmo sim :)
