### ISSUE TITLE
Inicio do curso

### ISSUE THREAD

**Issue by Edinhomarques** [da2k/curso-javascript-ninja#7805]
Uma duvida, estou iniciando hoje o curso, posso fazer os exercicios usando algumas features ecmascript 6 em alguns casos? Por exemplo arrow function? posso usar as declarações de variaveis e funçoes em inglês para práticar meu inglês?
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Edinhomarques! Legal que está começando o curso agora, seja bem vindo! :D 

Vamos as dúvidas:

Sobre usar features do ES6+: não recomendo usar essas features, ao menos por enquanto, pois elas não substituem o que você irá aprender em ES5. Por exemplo: arrow functions não são uma substituição às funções padrão. Elas têm um outro objetivo. Então eu recomendo você estudar como é mostrado no curso, e depois partir para o estudo das novas features, para entender o porquê elas foram adicionadas, e o que de fato pode ser substituído, e o que foi acrescentado, ok? :)

Só pra você entender melhor sobre o que eu estou falando: eu escrevi um artigo mostrando tudo sobre as arrow functions, e em que momentos elas podem ou não substituir as funções padrão da linguagem:
https://blog.da2k.com.br/2019/01/07/javascript-tudo-sobre-arrow-functions/

Sobre escrever em inglês: pode sim! Na verdade, eu começo mostrando em português, pois muitas pessoas que começam o curso nunca tiveram antes o contato com uma linguagem de programação. Mas com o passar das aulas, eu vou explicando o significado das nomenclaturas, e indico que tudo seja escrito em inglês mesmo :)

Acho que é isso! Qualquer dúvida, fique sempre à vontade para perguntar. Estou à disposição para ajudar no que for preciso :D

**Comment by Edinhomarques** [comment]
Show, entendi e seguirei seu conselho. Obrigado

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, avisa aí :)
