### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by Edinhomarques** [da2k/curso-javascript-ninja#7806]
Você colocou variavel na questão a variavel --> myvar
queria saber se a nomeção de variavel deve ser camelCase? por exemplo se o correto ou o mais usado seria myVar ou myvar? ou tanto faz?
@fdaciuk

**Comment by fdaciuk** [comment]
oi @Edinhomarques! Normalmente usamos _camel case_ mesmo, mas nas primeiras aulas você não precisa se preocupar com padrões, performance ou boas práticas. Essas primeiras aulas servem especificamente para apresentar e você aprender as funcionalidades básicas da linguagem.

Mais pra frente, com um pouco mais de conhecimento do que a liguagem pode te oferecer, vamos falar mais sobre esses assuntos :)
