### ISSUE TITLE
NÃO ENTENDO - "use strict"

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7810]
OIá Fernando.

- No vídeo **94**  você fala que o "use strict" pode quebrar códigos de terceiros. Mas isso me deixou confuso. Como por exemplo isso poderia acontecer?

Obrigado mais uma vez.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Quando você usa o `"use strict"` fora do escopo de uma função **criada por você** (normalmente uma IIFE), essa _flag_ vai afetar qualquer código global que esteja na sua aplicação.

Imagine que você tem uma biblioteca de terceiros na sua aplicação. Essa biblioteca virá em um arquivo JS, que você irá colocar em uma tag script na sua aplicação, mas você não tem controle diretamente ao que essa biblioteca faz, pois o código não é seu. Outra pessoa o fez.

Você não sabe se essa pessoa fez o código com tudo global, ou se ela fez bonitinho, com tudo local, usando IIFE.

Por isso usar `"use strict"` no escopo global é perigoso: já que dispara alguns erros, conforme os casos citados na aula, isso pode quebrar o seu app.

Por isso a importância de criar a IIFE, e deixar o `"use strict"` sempre **dentro** da IIFE :)

**Comment by xfelipee** [comment]
Olá, Fernando. Então o uso o IIFE pega os outros arquivos do documento? é como se ele pasasse a diretiva também para o outro arquivo? Igual a você explicou que sem o escopo local eu posso acessar a variável de outro documento? - Não sei se entendeu. Caso não tenha entendido eu repito.

**Comment by fdaciuk** [comment]
Oi @xfelipee! Não entendi muito bem a sua dúvida :)

**Comment by xfelipee** [comment]
Por exemplo, eu colocar a **"use strict" em um documento js no escopo global**, ela por está no aspecto global, ela irá interferir nos outros scripts relacionados? como uma variável, que no aspecto global é acessível de outros documentos javascript relacionados!

Veja nessa aula(90):

- Você faz a comparação da variável global x local. Dai acontece que a global é acessível ao documento "2" quando ela é global. A minha pergunta é justamente referente a isso. o "use strict" tem esse afeito, ele atinge os outros documentos relacionados, por isso ele quebra os códigos de terceiros se ele estiver no aspecto global?

![Screenshot_2019-12-26 Curso JavaScript Ninja](https://user-images.githubusercontent.com/19687110/71496896-69672800-2834-11ea-80bf-0be9b8d02e34.png)

**Comment by xfelipee** [comment]
O que eu digitei errado ai?
![x1](https://user-images.githubusercontent.com/19687110/71496992-eb575100-2834-11ea-9b63-fd1c6bcc95d8.jpg)

Outra coisa:

- Você falou que não devemos utilizar no regex uma a lista dessa forma [A-z], porque faz math com caracteres que não queremos. Mas se os caracteres não estiverem no texto, faz math do mesmo jeito? fiquei confuso com isso.

PS: Muito obrigado por tirar minhas dúvidas. Se caso eu estiver sendo incoveniente ou estiver mandando perguntas de forma errada, favor avisar. abraço.

**Comment by fdaciuk** [comment]
> Por exemplo, eu colocar a "use strict" em um documento js no escopo global, ela por está no aspecto global, ela irá interferir nos outros scripts relacionados? como uma variável, que no aspecto global é acessível de outros documentos javascript relacionados!

É exatamente isso! A diretiva `"use strict"`, assim como variáveis declaradas com `var`, tem escopo de função. Então se ela for declarada em escopo global, todo o código estará rodando no modo "estrito" :)

---

> Você falou que não devemos utilizar no regex uma a lista dessa forma [A-z], porque faz math com caracteres que não queremos. Mas se os caracteres não estiverem no texto, faz math do mesmo jeito? fiquei confuso com isso.

O _match_ só acontece quando o texto contém exatamente o algoritmo criado na regex. Se você usar na regex só `[A-z]`, isso significa casar com apenas 1 caractere, entre `A` e `z`. Se qualquer um dos caracteres dentro desse limite estiverem no texto, vai ser feito o _match_ :)

Ficou claro?

---

> PS: Muito obrigado por tirar minhas dúvidas. Se caso eu estiver sendo incoveniente ou estiver mandando perguntas de forma errada, favor avisar. abraço.

Fique sempre muito à vontade para perguntar sempre que sentir necessidade. Estou aqui pra te ajudar a alcançar o nível Ninja! :D
