### ISSUE TITLE
Ajax e servidor local

### ISSUE THREAD

**Issue by kevinbreno** [da2k/curso-javascript-ninja#7815]
Olá professor, eu comecei a aprender o módulo de ajax recentemente no curso de Javascript, aí percebi que ia precisar utilizar um servidor local (antes eu criava um arquivo html para os desafios e abria no navegador pelo computador mesmo). Ai eu pesquisei como criar um servidor local e criei um utilizando node e view engine mas não está funcionando muito bem, tem algum modo mais fácil de criar um servidor local e rodar o arquivo html nele?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kevinbreno! Tem algumas bibliotecas que ajudam com isso. Para o curso, pode usar o [http-server] :)

Se você estiver usando a versão `5.2` ou superior do NPM, ele já vem com uma ferramenta chamada `npx`, que facilita o uso do `http-server`. 

Para saber sua versão do NPM, execute no seu terminal:

```
npm -v
```

Se a versão for maior que 5.2, você pode usar o `http-server` assim:

Primeiro, acesse via terminal o diretório do seu projeto, onde está o arquivo `index.html`.

Nesse diretorio, execute o comando no seu terminal:

```
npx http-server .
```

Esse comando vai subir um servidor local na porta `8081` (se for alguma porta diferente, vai aparecer o endereço correto no seu terminal).

Para derrubar o servidor, é só voltar ao terminal e pressionar `Ctrl + C` :)

**Comment by kevinbreno** [comment]
Fiz tudo como o recomendado e deu certo, tive um problema com o navegador pois ele não estava atualizando as mudanças feitas nos arquivos como o javascript mas foi só desabilitar o cachê que deu certo
Obrigado @fdaciuk

**Comment by fdaciuk** [comment]
Legal @kevinbreno! Se você rodar o comando com `-c`, você pode definir um tempo para usar como cache. Se usar `-c10`, ele vai usar 10 segundos. Se usar `-c-1`, ele não faz cache :)

No comando todo, ficaria:

```
npx http-server -c-1 .
```

=)

**Comment by fdaciuk** [comment]
Mas que bom que deu certo! Qualquer coisa, avisa ae que eu vou ajudando :)
