### ISSUE TITLE
Aula11= Revisão da semana 10 parte 3 - linha 57

### ISSUE THREAD

**Issue by felrespin** [da2k/curso-javascript-ninja#7816]
Olá Fernando!

Fiquei com duas dúvidas na linha 57 nó código.

```
function isOperatorValid(operator) {
	return !!operation[operator];
}
```
1- Eu entendi a ideia, mas não a sintaxe ' !! ' achei que seria apenas um '!' ou '!==". 
Tive até dificuldade de achar documentação que explicasse.

2- Não consegui entender muito bem como conseguimos juntar o "operation" com o "[operator]" Porque é preciso o array, não poderia ser com "()"?

Obrigado e boas festas!
Felipe Resende

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felrespin! Vamos lá:

1) Eu apresentei o operador de equivalência booleana `!!` na aula 4, você chegou a ver? Foi no vídeo falando sobre "Truthy" e "Falsy" (terceiro vídeo da aula `#04` :)

2) Isso eu também mostrei nas primeiras aulas, mas mostrei com mais detalhes na correção do desafio 5. Mais especificamente no terceiro vídeo da aula `#06`.

Dá uma olhada nessas aulas que vai ficar mais claro esse assunto :)

Se ainda assim ficar alguma dúvida, volte a comentar aqui que eu vou te ajudando a entender, ok? :)

**Comment by felrespin** [comment]
Olá Fernando! 
Eu refiz as aulas indicadas e entendi os conceitos.Ficou mais fácil de entender. 
Vamos em frente com o curso!
Obrigado!
Feliz 2020!

**Comment by fdaciuk** [comment]
Perfeito meu caro! Qualquer coisa, só avisar :)
Boas festas :)
