### ISSUE TITLE
NÃO ENTENDO - "use strict" vídeo 132.

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#7818]
![Screenshot_2019-12-29 Curso JavaScript Ninja_01](https://user-images.githubusercontent.com/19687110/71563841-13cd8e00-2a75-11ea-8edb-21d1e0af7e29.png)
Olá, @fdaciuk 

- Minuto 7:00 (O senhor fala que com o uso do "use strict" o this se torna o "window". Mas pelo que eu entendi no vídeo "95", ele se torna undefined. E no caso do lastName pelo que eu entendi, ele só é "is not defined" porque o "use strict" não deixa o this se referenciar ao window. Por favor me esclareça. Atenciosamente.

PS: A propriedade .name da função, foi explanada em qual vídeo antes do 132? Eu posso ter deixado batido. Obrigado mais uma vez, boa noite.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Vamos lá:

> Minuto 7:00 (O senhor fala que com o uso do "use strict" o this se torna o "window". Mas pelo que eu entendi no vídeo "95", ele se torna undefined. E no caso do lastName pelo que eu entendi, ele só é "is not defined" porque o "use strict" não deixa o this se referenciar ao window. Por favor me esclareça. Atenciosamente.

Sim, foi falha minha. O que eu quis dizer foi exatamente isso: ao usar o `"use strict"`, o `this` dentro de uma função que não é invocada como construtora é `undefined`. Se não usar o `"use strict"`, aí sim ele vai se referir ao objeto global `window` :)

---

> PS: A propriedade .name da função, foi explanada em qual vídeo antes do 132? Eu posso ter deixado batido. Obrigado mais uma vez, boa noite.

Eu mostrei sobre essa propriedade no segundo vídeo da aula `#08` =)

**Comment by xfelipee** [comment]
vlw
