### ISSUE TITLE
Use Strict não funcionou - Video 94 - Aula 16

### ISSUE THREAD

**Issue by brugbarros** [da2k/curso-javascript-ninja#7819]
`(function() {
  "use strict";
  name = "teste";
  console.log(name);
})();
console.log(name + " fora da func");
`

Bom dia/tarde/noite professor, fiz o exemplo da aula conforme está acima (identico ao vídeo) e o 'use strict' parece não funcionar, o console.log() de fora da IIFE mostrará a msg 'teste fora da func', não deveria mostrar que a variavel 'name' não existe, como no vídeo? Mudou a implementação do use strict nas versões atuais? 

Notei que isso só acontece no browser, se eu executar o mesmo código com 'node main.js' dará que a variável realmente não existe. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brunogbr! Dá uma olhada na resposta [dessa issue](https://github.com/da2k/curso-javascript-ninja/issues/7808#issuecomment-567960572) que eu detalhei bem lá o que acontece especificamente com essa variável `name` :)

Se ainda ficar alguma dúvida, só avisar aqui :)

**Comment by fdaciuk** [comment]
Oi @brugbarros! Vou fechar a issue, mas se você ainda tiver qualquer dúvida, só avisar que a gente reabre, ok? :)
