### ISSUE TITLE
[ challenge-02 ]

### ISSUE THREAD

**Issue by baltazarparra** [da2k/curso-javascript-ninja#783]
@fdaciuk 

Porque eu não posso escrever dessa forma.

**if (x  || y  || z === undefined) {**

```javascript
function littlePigs (x,y,z) {
  if (x  || y  || z === undefined) {
    return 'Preencha todos os valores corretamente!';
  } else {
    return ( x * y * z ) + 2;
  }
};
```

**Comment by fdaciuk** [comment]
@baltazarparra o interpretador do JS vai entender cada verificação separadamente. Quando você faz uma verificação usando `if`, o JS vai usar o equivalente booleano desse valor para verificar se ele é verdadeiro ou falso.

Nesse caso, ele vai fazer as seguintes verificações:

- Se `x` for `true` **ou** `y` for `true` ou `z` for `undefined`, faça algo...
Senão (`else`), faça esse outro algo...

Nas próximas aulas, você vai ver que o JS tem equivalentes booleanos para cada tipo de valor. E quando você testa qualquer tipo de variável sem o operador de comparação em uma cláusula `if`, esse valor vai ser convertido para `true` ou `false`, dependendo do valor atribuído a essa variável =)

O que você precisa saber agora: para saber se um parâmetro foi passado para uma função, verifique sempre se a variável é igual a `undefined`, como você fez com o `z` =)

Não sei se ficou claro. Se tiver dúvida ainda, me avise =)

**Comment by baltazarparra** [comment]
Caralho, você respondeu muito rápido kkkkk

Ficou claro sim mano, valeu =]

**Comment by fdaciuk** [comment]
Tava navegando no GitHub e vi a pergunta xD
Mas dúvidas são sempre prioridade =)

Qualquer coisa grita ae :grin:
