### ISSUE TITLE
Problemas com Pull Request

### ISSUE THREAD

**Issue by youssfbr** [da2k/curso-javascript-ninja#7831]
Seguindo o video desafio da semana #01, aos exatos 6:30, após fazer o commit e clicar em forked from da2k/curso-javascript-ninja
Não aparece a mensagem pushed branches para poder comparar e fazer o pull request. Como procedo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @youssfbr! Dá uma olhada [nessa resposta aqui](https://github.com/da2k/curso-javascript-ninja/issues/7633#issuecomment-549067355) que eu mostrei em imagem como proceder :)

Qualquer coisa, só avisar!
