### ISSUE TITLE
Avaliação sobre função

### ISSUE THREAD

**Issue by ralsouza** [da2k/curso-javascript-ninja#7876]
@fdaciuk, sobre o desafio 16, fiz uma função para o exercício que diz:
```
/*
 - Declare uma variável chamada `fullName`, que receba seu nome completo,
   escrito no formato de slug (caixa baixa e palavras separadas por um traço).
   Ex: o nome "Fernando Daciuk" ficaria "fernando-daciuk"
- Faça a primeira letra de cada nome ficar em caixa alta, e troque o traço por um espaço.
- Detalhe: o código que você escrever abaixo deve funcionar para qualquer nome, então fique à vontade para usar as artimanhas que já viu até agora no curso para fazer isso funcionar corretamente :)
- Mostre no console o nome no formato slug, e o resultado final. Use um console.log para cada formato.
*/
```

Então pensei em fazer uma função, será que fez sentido?

```
	console.log( '\nNome convertido à partir de um slug:' );
	
	var fullName = 'rafael-lima-de-souza';

	var newName = '';

	function removeSlug( name ) {

		var name = name.split('-');

		name.forEach( function( item, index ) {

			newName += item.charAt(0).toUpperCase() + item.slice(1) + ' ';
		});

		return newName;
	}

	console.log( fullName );
	console.log( removeSlug(fullName) );
```

**Comment by fdaciuk** [comment]
Oi @ralsouza! Legal cara, faz todo o sentido sim :)
Só tem algumas observações, para deixar a função mais reutilizável:

- Use apenas o escopo da função para fazer a transformação do nome passado via argumento. Ao invés de declarar uma variável fora da função (`newName`) e reatribuir o valor dela dentro da função, crie ela dentro da função. Dessa forma, cada chamada da função cria uma nova variável para cada nome. Se deixar como você fez, a cada vez que você usar a função, a variável `newName`, que está fora da função, será sobrescrita sempre com o nome da última chamada da função :)

- Outro ponto importante é não criar uma variável com o mesmo nome de um parâmetro da função. Você já recebe um valor que é passado para o parâmetro `name`. E parâmetros já são variáveis, então não precisa redeclarar, entende? Prefira sempre criar uma nova variável com nome diferente do parâmetro, ao invés de reatribuir :)

Deu pra entender a ideia? :)

**Comment by ralsouza** [comment]
Oi @fdaciuk , tudo certo?
Entendi, seria isso?

```
console.log( '\nNome convertido à partir de um slug:' );
	
	var fullName = 'rafael-lima-de-souza';

	function removeSlug( name ) {

		var newName = '';

		var oldName = name.split('-');

		oldName.forEach( function( item, index ) {

			newName += item.charAt(0).toUpperCase() + item.slice(1) + ' ';
		});

		return newName;
	}
```

**Comment by fdaciuk** [comment]
Isso aí @ralsouza! :D 

Qualquer coisa, só avisar :)
