### ISSUE TITLE
Falha no audio da aula 20 video #117 a partir dos 1:55

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-javascript-ninja#789]
Opa fernando aqui no meu a aula fica muda dos 1:55 ate os 6 minutos mais ou menos quando se muda a explifação pra if e for.

**Comment by fdaciuk** [comment]
Fala @brunotortelli! Na lista de aulas, tem um e-mail com a explicação do que foi falado nesse tempo que falhou o áudio =)
