### ISSUE TITLE
Erro, fim de arquivo inesperado!

### ISSUE THREAD

**Issue by brufelix** [da2k/curso-javascript-ninja#7897]
Não conseguir entender porque está acontecendo esse erro, sendo que consigo converter e acessar o valor contido no arquivo, e também queria saber porque as instruções dentro do __IF__ estão sendo executadas duas vezes!?

_ERRO:_ __Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous>__

__MAS LOGO EM SEGUIDA NO CONSOLE MOSTRA O VALOR CONTIDO NO ARQUIVO__

_CONTEÚDO DO ARQUIVO:_ __{ "name":"Bruno " }__
```
(function(win, doc){
    'use strict';

    var ajax = new XMLHttpRequest();

    ajax.open('GET','/data/data.json');
    ajax.send();

    function isRequestOk(){
        return ajax.readyState === 4 && ajax.status === 200;
    }

    ajax.addEventListener('readystatechange',function(){
        if (isRequestOk){
            var person = JSON.parse(ajax.responseText);
            console.log(person.name);
        }
    }, false);
})(window, document);
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @brufelix! Faltou você executar a função `isRequestOk` no if :)
Se não executar, o resultado sempre será `true`, e vai entrar nesse `if` antes da hora :)

**Comment by brufelix** [comment]
Ok, Obrigado!
