### ISSUE TITLE
[Duvida] Preciso baixar novamente o repositório, porém ele não vem com as branchs anteriores, o que devo fazer?

### ISSUE THREAD

**Issue by andersonweb** [da2k/curso-javascript-ninja#79]

**Comment by fdaciuk** [comment]
@andersonweb, para trazer todas as branches do seu repositório para o local, após clonar o repositório, execute o comando:

```sh
for remote in `git branch -r | grep -v master `; do git checkout --track $remote ; done
```

Depois disso, você precisa adicionar o `upstream`, baseado no repositório principal:

```sh
git remote add upstream git@github.com:da2k/curso-javascript-ninja.git
```

:smile:

**Comment by andersonweb** [comment]
@fdaciuk Poderia explicar o que cada comando faz? Obrigado!

**Comment by fdaciuk** [comment]
O primeiro comando faz um for por todas as branches que estão no seu repositório, e cria elas localmente com o conteúdo atualizado.

O segundo é pra adicionar o repositório principal como `upstream`, pra você poder atualizar os próximos desafios na sua master ;)

**Comment by andersonweb** [comment]
Show @fdaciuk ! Obrigado.

**Comment by fdaciuk** [comment]
:+1:
