### ISSUE TITLE
Sobre a utilização do "else"

### ISSUE THREAD

**Issue by diogorodrigues** [da2k/curso-javascript-ninja#790]
@fdaciuk ,blz?

Estava assistindo a correção do challenge-04 e vi que você não utilizou o else no método "carro.adicionarPessoas". 

Eu utilizei if, elseif e else na minha estrutura. Portanto, minha dúvida é: por questão se padrões de sintaxe, é interessante utilizar o else ou fazer tudo apenas com if quando for possível?

**Comment by fdaciuk** [comment]
Fala @diogorodrigues! Como está na aula 4 ainda, não precisa se preocupar muito com isso. Mas conforme for avançando, vou passando algumas boas práticas =)

Mas sim, sempre que possível, evite o `else`. O seu código fica mais simples se usar somente `if`.

Em alguns casos (raros), fica mais fácil a leitura com `else`, mas na maior parte do tempo, não usá-lo é melhor.

Melhor ainda se o `if` tiver apenas uma única regra dentro. O código fica mais simples de ler, e diminui o que chamamos de **complexidade ciclomática**. =)

**Comment by diogorodrigues** [comment]
Valeu!!
Suas dicas são ótimas, tenho aprendido bastante sobre essas questões de boas práticas. =D

**Comment by fdaciuk** [comment]
Show! \o/
Qualquer dúvida grita ae =)
