### ISSUE TITLE
Travamento na hora de codificar

### ISSUE THREAD

**Issue by ralsouza** [da2k/curso-javascript-ninja#7913]
Oi @fdaciuk, a minha dúvida não é tanto sobre o código em si. 

Hoje fiz o desafio 17 onde era necessário fazer uma função e em conjunto com uma expressão regular alterar o formato da data.

Na hora de codificar os dois últimos exercícios eu simplesmente travei, será que perdi algo importante e devo refazer o capítulo?

**Comment by fdaciuk** [comment]
Oi @ralsouza! Pode ser que você tenha perdido algo sim, mas a probabilidade maior é de que isso é  apenas uma dificuldade inicial, já que é a primeira vez que você precisa pensar nesse tipo de solução :)

Fique tranquilo que é normal. Acontece com todo mundo. 

Apenas continue praticando, e sempre que acontecer esse tipo de coisa, assista à correção da aula, e depois tente refazer o exercício sozinho. Faça isso algumas vezes, dando intervalo de dois ou três dias para cada resolução do mesmo desafio.

Isso vai "forçar" o seu cérebro a aprender aquela instrução, e o problema começa a ficar mais claro, facilitando assim a resolução de problemas parecidos no futuro :)

**Comment by ralsouza** [comment]
Oi @fdaciuk, baita dica!!!
Pode deixar que farei isso, muito obrigado!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
