### ISSUE TITLE
Porque essa função funcionou? 

### ISSUE THREAD

**Issue by ralsouza** [da2k/curso-javascript-ninja#7963]
@fdaciuk, estou trabalhando no desafio 18 sobre REGEX e tentei mudar um pouco a apresentação dos dados dos CPFs limpos. Mas não entendi como a função funcionou. kkk

Veja o comentário da última linha:
```
	console.log( 'Limpando CPFs:' );
	
	var cpf = ['049-214 3421-1','210.458.522-05','735 500 794 - 22','101.123-131x32'];

	function cleanCPF(item) {
		console.log( item.replace(/\D/g, '') );
	}

	cpf.forEach(cleanCPF); // Como foi possível invocar a função acima, sem usar os parênteses?
```

**Comment by fdaciuk** [comment]
Oi @ralsouza! Lembra que vimos a algumas aulas atrás que funções podem ser passadas por referência, assim como todo objeto em JavaScript?

E que se usarmos a função sem os parênteses, na verdade estamos passando a referência dessa função?

Então, é exatamente o que está acontecendo no seu código: o método `forEach` espera que uma função seja passada pra ele. Essa função será executada uma vez para cada item do array que estiver sendo iterado.

Mas quem executa a função é o método `forEach`, passando via argumento para essa função o item que está sendo iterado, certo?

Nesse caso, o que você fez é exatamente isso aqui:

```js
cpf.forEach(function cleanCPF (item) {
  console.log(item.replace(/\D/g, '');
});
```

Com a diferença que você simplesmente criou a função fora do forEach, e passou somente a referência dela para o `forEach` executar :)

Ficou claro? :)

**Comment by ralsouza** [comment]
Opa @fdaciuk, ficou muito claro sim!
Obrigado ;)

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :)
