### ISSUE TITLE
Pegar valor do input pelo id usando querySelector( )

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#8003]
Mestre! Estou com problemas pra pegar um valor de um input digitado pelo usuário. Esse input tá dentro de um form e tá com id.

@fdaciuk

**Comment by PauloTxJS** [comment]
```
<form action="/" method="get">
    <input type="text" id="numero" required placeholder="ex: 8589769876"/><br><br>
</form>

let numero = document.querySelector('#numero');
console.log(numero.value);
    
```

**Comment by fdaciuk** [comment]
Oi @PauloTxJS! Se você quer pegar o valor enquanto ele está sendo digitado, é preciso usar o evento `input`. Esse evento é disparado sempre que o valor de um input muda :)

**Comment by PauloTxJS** [comment]
Como é a sintaxe desse evento?

**Comment by PauloTxJS** [comment]
Valeu mestre, você é top demais... gostaria de dizer que consegui um estágio na área... graças ao que aprendi com você.

**Comment by PauloTxJS** [comment]
Mestre! Só mais umas dúvida aqui... Pode mandar o link na documentação do java script sobre esse evento input? Procurei mas não achei... Onde você viu essa sintaxe?... Só por curiosidade....procurei na documentação mas não achei.

**Comment by PauloTxJS** [comment]
Achei...kkkkkkk

**Comment by fdaciuk** [comment]
> gostaria de dizer que consegui um estágio na área... graças ao que aprendi com você.

Que legal cara, parabéns \o/

> Achei...kkkkkkk

haha! Boa :D 
Não sei se foi na MDN que você encontrou, mas lá é a mehor fonte que você vai achar para essas features. 

Tem também o [DevDocs](https://devdocs.io/), com documentação de várias ferramentas em um único lugar :)
