### ISSUE TITLE
Não ENTENDO - Array.isArray( ) 

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#8004]
Boa noite, dia, tarde senhor Fernando. Estou voltando a lhe incomodar. Veja bem isso...

![carbon](https://user-images.githubusercontent.com/19687110/73991064-cb35aa00-4929-11ea-94c5-63acd54c8cdd.png)

**Amarelo** - Quando ele fala passar entre "FRAMES" da mesma página, ele se refere a "window.frame"?
Ficou um pouco confuso para mim, ele fala que cada "web-page tem seu contexto global", seria a página toda, ou cada documento, tipo cada página dentro do site? Não entendi. Me ajuda ai.

**Azul** - cada um tem seu próprio Object, String, Number, Array, etc, certo?

**Vermelho** - a solução é dada para o Array, e para os outros, qual é a solução?

Me desculpe mais uma vez o incomodo. Agradeço a atenção desde já. Abraço.

@fdaciuk

**Comment by xfelipee** [comment]
Olá, bom dia, boa tarde boa noite.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

Fernando, eu estou em dúvida sobre essa propriedade __proto__ ela está depreciada, mas ainda aparece no console, e alguns conteúdos novos que eu vejo ainda usa ela. Na verdade, se eu não me engano ela foi implementada depois do do ES5. O senhor poderia me esclarecer?

Obrigado.

**Comment by fdaciuk** [comment]
Oi @xfelipee! Vamos lá:

> Amarelo - Quando ele fala passar entre "FRAMES" da mesma página, ele se refere a "window.frame"?
Ficou um pouco confuso para mim, ele fala que cada "web-page tem seu contexto global", seria a página toda, ou cada documento, tipo cada página dentro do site? Não entendi. Me ajuda ai.

Quando ele se refere a frames, são as tags `<frame>` e `<iframe>`, que podem renderizar tanto páginas externas (domínios diferentes) como páginas do mesmo domínio.

Cada "frame" teu seu próprio contexto, ou seja: cada página carregada vai tag `<frame>` ou `<iframe>`, independente do domínio.

---

> Azul - cada um tem seu próprio Object, String, Number, Array, etc, certo?

Isso mesmo, cada frame terá sua própria referência dos construtores padrão da linguagem.

---

> Vermelho - a solução é dada para o Array, e para os outros, qual é a solução?

Não sei te dizer ao certo se existe uma solução para outros tipos de dados, quando passados para frames diferentes (para usar no mesmo contexto, eu mostro no curso uma boa forma de fazer). Mas, pra ser sincero, esse tipo de situação é praticamente nula para aplicações web atuais. Normalmente você vai trabalhar sempre na mesma "instância" onde o interpretador do JS será executado pela primeira vez.

---

Sobre o `__proto__`: é outra feature que você nunca¹ vai precisar usar. Como no link que você mandou diz, existem outros dois métodos que você pode usar no lugar do `__proto__`.

Ele continua funcionando e aparecendo sim, pois a principal premissa dos navegadores web, e das pessoas que trabalham para incluir novas features na linguagem JavaScript é: **não quebre a web**.

Se o `__proto__` foi implementado um dia, e pode estar sendo usado em algum lugar, ele não deve ser removido, pois vai quebrar os sites que o usam. Não significa que você deva usar :)

---

Acho que é isso! Qualquer dúvida, só avisar :)

---

¹ sei que **nunca** é relativo, mas hoje em dia não vejo nenhum caso de uso onde você realmente precisaria usar isso.

**Comment by xfelipee** [comment]
vlw! abc

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
