### ISSUE TITLE
Dúvida referente ao enunciado do desafio da semana 14.

### ISSUE THREAD

**Issue by MateusDanieel** [da2k/curso-javascript-ninja#8022]
Oi professor, tudo jóia?

Estou com uma dúvida, referente a esse exercício, segue o enunciado:

```
/*
    Verifique se existem em algum índice de numberObjects um objeto ìgual a
    { number: 2 }. Se houver, mostre no console:
    - "Existe um objeto { number: 2 } em numberObjects!"
    Senão, mostre a frase:
    - "Não existe um objeto { number: 2 } em numberObjects :("
    Consegue prever o resultado? Deixe uma mensagem no console tentando explicar
    o que acontece ;)
*/
```

Eu creio que a intenção era fazer utilizando `indexOf()`, correto? Porém, o `indexOf()` aparentemente não funciona direito quando o item do array é um objeto, sabe me dizer pq isso ocorre?

E uma outra dúvida é sobre o final do enunciado, no trecho "Consegue prever o resultado? Deixe uma mensagem no console tentando explicar o que acontece ;)", não entendi o que quis dizer com 'prever o resultado', poderia me dar uma luz? Abração!

@fdaciuk

**Comment by fdaciuk** [comment]
O @MateusDanieel! A ideia é que você use sim o `indexOf`, e analise o resultado.
Qual das duas mensagens vai aparecer? 

E sobre prever o resultado: você saberia dizer o porquê apareceu uma mensagem e não a outra? 

É um exercício pra relembrar algo muito importante, mas que já vimos em aulas anteriores :)

Se não conseguir explicar o que acontece, não tem problema! Na correção desse desafio eu explico :)

Se após assistir à correção ficar alguma dúvida, pode voltar a comentar aqui que eu te ajudo, beleza? :)

**Comment by MateusDanieel** [comment]
Perfeito professor, obrigado! :D

**Comment by fdaciuk** [comment]
Vou fechar a issue, mas se você ainda tiver dúvidas, só voltar a comentar aqui que eu vou te ajudando :)
