### ISSUE TITLE
[AULA 4] Operadores de igualdade / relacionais

### ISSUE THREAD

**Issue by ebraimcarvalho** [da2k/curso-javascript-ninja#8029]
No slide 29, a definição de ```!==``` está: "Diferente, mas do mesmo tipo".
Acredito ser um erro de digitação pois na documentação do Mozilla está definido assim: "O operador desigualdade estrita retorna verdadeiro se os operandos não são iguais **e / ou não são do mesmo tipo.**"

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ebraimcarvalho! Acredito que falhei na comunicação nessa parte. A digitação está correta, mas o que eu tentei expressar foi exatamente o que você apontou: os dois valores serão testados, mas o tipo também será comparado, não somente o valor =)

**Comment by fdaciuk** [comment]
Oi @ebraimcarvalho! Vou fechar a issue, mas se você ainda tiver qualquer dúvida, só avisar que a gente reabre, ok? :)
