### ISSUE TITLE
Dúvida sobre regex

### ISSUE THREAD

**Issue by PauloTxJS** [da2k/curso-javascript-ninja#8037]
Mestre! Como eu faço pra escapar o caractere 'espaço'?

@fdaciuk

**Comment by PauloTxJS** [comment]
Já resolvi
```\ ```

**Comment by fdaciuk** [comment]
Isso mesmo @PauloTxJS! Mas, na verdade, o espaço não precisa ser escapado. Você pode usar ele de forma literal, ou com o `\s` :)

**Comment by PauloTxJS** [comment]
Sim... o  '\s', tinha esquecido dele. Valeu mestre.

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
