### ISSUE TITLE
[AULA 17] Dúvida referente ao último exercício.

### ISSUE THREAD

**Issue by MateusDanieel** [da2k/curso-javascript-ninja#8038]
Professor, fiquei com uma dúvida referente ao último desafio da aula 17, segue o código:

```
function replaceDate(regex, day, month, year) {
        return day + '/' + getMonthNumber(month) + '/' + year;
    }

    console.log( text.replace(regexDate, replaceDate) );
```

Minhas dúvidas são:
- Sei que o primeiro parametro passado na função de alguma forma ativava a variável `regexDate` que fizemos mais acima, mas não consegui entender de que forma isso funciona.
- Também não entendi o pq de chamar a função sem invoca-la com parenteses.

Abraços!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MateusDanieel! Vamos lá :)

Sobre a primeira dúvida: a variável `regexDate` teve um valor atribuído a ela: uma regex, certo? Logo, podemos usar essa variável para representar aquele valor que foi atribuído a ela.

Seria basicamente o mesmo que passar a regex direto para o método. Os dois exemplos abaixo são equivalentes:

Primeiro, usando a variável:

```js
var regexDate = /(\d\d) de (junho|julho) de (\d\d\d\d)/;
console.log(text.replace(regexDate, replaceDate));
```
E aqui, passando a regex direto para o método `replace`:

```js
console.log(text.replace(/(\d\d) de (junho|julho) de (\d\d\d\d)/, replaceDate));
```

Deu pra entender? :)

---

Sobre a segunda dúvida, eu respondi [aqui](https://github.com/da2k/curso-javascript-ninja/issues/3601#issuecomment-368173000). Dá uma olhada se isso te ajuda. Se ainda não ficou claro, só avisar que eu tento explicar de outra forma, ok? :)
