### ISSUE TITLE
Challenge-29 - ajax dando erro :(

### ISSUE THREAD

**Issue by prmlimajr** [da2k/curso-javascript-ninja#8046]
Estava tudo funcionando bem até que após alguma alteração eu não consigo mais pegar os dados do JSON e exibir. 
```
companyInfo: function companyInfo(){
            var ajax = new XMLHttpRequest()
            ajax.open('GET', 'company.json', true)
            ajax.send()
            ajax.addEventListener('readystatechange', this.getCompanyInfo, false)
        },

        getCompanyInfo: function getCompanyInfo(){
            if(!app.isReady.call(this))
                return

            var data = JSON.parse(this.responseText)
            var companyName = DOM('[data-js="nomeDaLoja"]')
            var companyPhone = DOM('[data-js="telefoneDaLoja"]')
            companyName.textContent = data.name
            companyPhone.textContent = data.phone
        },
```
Link para o meu repositório: https://github.com/prmlimajr/curso-javascript-ninja/blob/challenge-29/challenge-29/challenge-29.js

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @prmlimajr! Seu código está certo :)
Só faltou usar o `.get()` [aqui nessas duas linhas](https://github.com/prmlimajr/curso-javascript-ninja/blob/challenge-29/challenge-29/challenge-29.js#L91-L92). 

Lembra que precisamos dele quando queremos a referência do elemento do DOM, pra manipularmos manualmente? :)

**Comment by fdaciuk** [comment]
Oi @prmlimajr! Vou fechar a issue, mas se você ainda tiver qualquer dúvida, só avisar que a gente reabre, ok? :)
