### ISSUE TITLE
Aula 2. Error no SSH

### ISSUE THREAD

**Issue by Vicdeabreu** [da2k/curso-javascript-ninja#8051]
Boa tarde, profesor. 

Não tó conseguindo fazer o proceso do SSH no terminal. Não acho o link do SSH e não consigo fazer o proceso para subir o challenge 2. Preciso de ajuda. 

Muito obrigado.

**Comment by fdaciuk** [comment]
Oi @Vicdeabreu! Tem duas formas de resolver: a mais simples é usar o link com HTTPS para clonar. Dessa forma, você só vai precisar entrar com seu usuário e senha do GitHub pra conseguir clonar.

A outra forma é criando uma chave SSH, e configurando essa chave na sua conta do GitHub. Para fazer isso, é só seguir esses tutoriais do próprio GitHub, com base no seu sistema operacional:
https://help.github.com/articles/connecting-to-github-with-ssh/

---

OBS.: Não apague a menção ao meu usuário que aparece no texto quando você cria uma nova issue (`@fdaciuk`), senão eu não recebo notificação da sua dúvida, ok? :)

**Comment by fdaciuk** [comment]
Oi @Vicdeabreu! Vou fechar a issue, mas se você ainda tiver qualquer dúvida, só avisar que a gente reabre, ok? :)
