### ISSUE TITLE
EU NÃO ENTENDO! - Object.getOwnPropertyNames()

### ISSUE THREAD

**Issue by xfelipee** [da2k/curso-javascript-ninja#8067]
![InkedScreenshot_2020-02-27 Working with objects_LI](https://user-images.githubusercontent.com/19687110/75506696-931c0700-59bd-11ea-9550-f80eb5c7b313.jpg)

Olá Fernando, eu estou com essa dúvida. Isso está correto? Ele se contradiz no que diz respeito ao método getOwnPropertyNames()!  

Poderia me explicar?

PS: Cara eu posso tirar dúvidas com você mesmo tendo terminado o curso? Na verdade eu estou refazendo o curso. Caso queira eu posso pagar algo a mais, não sei. Agradeço mais uma vez sua atenção.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xfelipee! Sendo bem sincero, também não entendi o que quiseram mostrar ali no exemplo haha :D 

Mas parece estar errado sim: se não existia o método antes do ES5, como é possível usar esse método para criar uma implementação que funcionaria como um _polyfill_?

Enfim, de qualquer forma, isso não vai afetar seu código de hoje em dia :)

---

Claro, pode tirar dúvidas sim. Uma vez aluno, sempre aluno :)

Fique à vontade para perguntar sempre que precisar de ajuda :)

**Comment by xfelipee** [comment]
vlw.
