### ISSUE TITLE
Dificuldade em criar request

### ISSUE THREAD

**Issue by JungleLivre** [da2k/curso-javascript-ninja#8081]
Bom dia, apos eu editar a challenge nao aparece a opção **fdacius;challenge-01**
ja está respondido, ja criei uma nova fork tudo certinho conforme você ensinou no video, mas estou tendo dificuldade, em enviar a request.
alguma sugestão ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JungleLivre! Não se preocupe em enviar o Pull Request se estiver com dificuldades. Apenas tente resolver os desafios na sua máquina, pois agora você já consegue acompanhar a resolução de cada um sempre no início da próxima aula :)

O importante é tentar resolver, para praticar, e ver se você conseguiu absorver o conhecimento passado, ok? :)

E qualquer dúvida, fique à vontade para perguntar :)
