### ISSUE TITLE
Início do curso

### ISSUE THREAD

**Issue by campostalita** [da2k/curso-javascript-ninja#8114]
Olá, bom dia!!
Comprei o curso há algum tempo e estava sem tempo para fazer, agora iniciei e não achei o email que fala com as senhas e tal, poderia me enviar novamente?

Obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @campostalita! Tudo bem? :)
Você lembra em qual e-mail você estava recebendo as informações do curso? Passa ele aqui pra mim que eu te envio o novo acesso :)

**Comment by campostalita** [comment]
é no campos.talita@hotmail.com. Obrigada!

**Comment by fdaciuk** [comment]
Oi @campostalita! Eu dei uma olhada aqui, e percebi que o seu e-mail não está cadastrado da época que eu enviava e-mails. Então fui olhar na Udemy, e vi que o seu cadastro já está lá :)

Então você só precisa acessar a sua conta da Udemy, que lá você vai ter acesso ao curso, ok? :)

**Comment by fdaciuk** [comment]
Oi @campostalita! Vou fechar a issue, mas se você ainda tiver qualquer dúvida, só avisar que a gente reabre, ok? :)
