### ISSUE TITLE
challenge 20

### ISSUE THREAD

**Issue by sistemawebpro** [da2k/curso-javascript-ninja#814]
daciuk uma duvida, porque a utilização nos inícios de variáveis do $ para identificar valores referentes a campos dos formulários? é uma regra?

**Comment by fdaciuk** [comment]
Opa @sistemawebpro! Não é uma regra não =)
É apenas uma convenção em JS, quando você quer referenciar elementos do DOM xD
Eu acho que comentei isso em alguma aula, não? Não tenho certeza se falei xD

**Comment by sistemawebpro** [comment]
blz, outra duvida vc ia comentar sobre as utilização dos datas atributos como melhor opção, sobre o uso de ids e class mas não chegou a comentar, ou ao menos ainda não cheguei na aula, poderia me explicar?

**Comment by fdaciuk** [comment]
Eu falei, mas um poucos mais adiante xD
É mais questão de separação das coisas mesmo.. ID é ruim porque gera uma variável global, classes são usadas no CSS, então faz todo sentido usar data attributes para o JS =)

**Comment by fdaciuk** [comment]
Ficou claro essa parte @sistemawebpro? Qualquer dúvida, pode reabrir a issue! =)
