### ISSUE TITLE
O que esperar do curso em 2020?

### ISSUE THREAD

**Issue by jackmakiyama** [da2k/curso-javascript-ninja#8181]
Olá, estou iniciando o curso essa semana e gostaria de entender se este veio recebendo atualizações e ainda é uma boa entrada para 2020.

Tenho um bom domínio de PHP e estou com a intenção de entender melhor o mundo do JS para uma possível megração de ecosistema.

No início do curso tive a impressão que ele está de acordo com a data de lançamento da época, mas hoje, ele continua válido? Principalmente pra quem tem interesse profissional e moderno? 

Obrigadooo o/

**Comment by Leodma** [comment]
Oi Jack, eu também iniciei o curso faz pouco tempo, já fiz outros cursos de Javascript mas sentia que me faltava uma base mais sólida sobre o funcionamento da linguagem, pois eram tratados muito superficialmente, e esse curso te dá essa base. Mesmo que a linguagem já tenha evoluído esse curso vai te ajudar a entender como o Javascript funciona. Estou achando muito útil e assimilando muitos conceitos que antes não conseguia entender.

**Comment by fdaciuk** [comment]
Oi @jackmakiyama! 

Pode ficar super tranquilo, pois o curso vai te dar uma ótima base da linguagem JavaScript :)

Não pretendo atualizar o curso para novas versões, pois ES5 é - e sempre será - a base da linguagem. Todas as features novas que vieram desde 2015 até então (e as que continuarão vindo) terão sempre como base o ES5, já que todas as novas features em JS devem ser retrocompatíveis.

Em breve teremos outros cursos, mostrando as novidades da linguagem, mas esse curso vai ser base para os cursos novos, devido a importância de conhecer a base da linguagem :)

---

Obs.: desculpe a demora na resposta, só vi sua mensagem agora :)
Quando abrir issue aqui, pode me marcar (com `@fdaciuk`) que eu vou receber notificação da issue e respondo o quanto antes, ok? :)

E fique à vontade para perguntar sempre que tiver dúvidas :)
