### ISSUE TITLE
PROTEÇÃO FORMULÁRIO  

### ISSUE THREAD

**Issue by Srubens** [da2k/curso-javascript-ninja#8186]
```
<div class="form">
    <form name="contact" data-js="contact-form" method="post" data-netlify="true">
	    <div class="form-row">
	      <div class="form-group col-lg-6">
	        <input type="text" name="name" class="form-control" id="name" placeholder="Seu nome" data-rule="minlen:4" data-msg="Please enter at least 4 chars" required />
	      </div>
	      <div class="form-group col-lg-6">
	        <input type="email" class="form-control" name="email" id="email" placeholder="Seu email" data-rule="email" data-msg="Please enter a valid email" required />
	      </div>
	    </div>
	    <div class="form-group">
	      <input type="text" class="form-control" name="titulo" id="subject" placeholder="Titulo" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" required />
	    </div>
	    <div class="form-group">
	      <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Mensagem"required ></textarea>
	    </div>
	    <div class="text-left"><button type="submit" title="Enviar">Enviar</button></div>
	</form>
</div>
 $('[data-js="contact-form"]').submit(function(e){
        e.preventDefault();
        
        let contactForm = $(this);
        let redirect = "https://www.agenciadallas.com.br";
        
        $.post(contactForm.attr("action"), contactForm.serialize()).then(function () {
            alert(`Obrigado por entrar em contato ${inputName.value}!\nEntraremos em contato em breve!`);

            $(location).attr('href', redirect);
        });

    }); 
```

Fala @fdaciuk  tudo bem? Meu nome é Rubens, queria saber se você tem algum video explicando sobre requisição de formulário com o javascript, como posso colocar uma proteção no script além do required no html.
Eu tinha criado antes funções e codições para que o usuario não passasse se ele deixasse os campos vazios ou se colocasse algo de errado, so que quando colocava tudo correto ele ainda mostrava a mensagem de erro
Se você usa ou ja usou o netlify. Ou se você pode me explicar sobre, desde ja obrigado! 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Srubens! Mais para o finalzinho do curso eu mostro sim como fazer requests HTTP :)
Sobre o formulário, a ideia de "proteger" campos com `required` no navegador é apenas para facilitar a experiência do usuário. Não leve isso como segurança, pois pode ser facilmente burlável. É só você inspecionar o elemento e remover o required :)

Por isso, a segurança de uma aplicação deve sempre ser pensada do lado do servidor. Tudo o que você fizer no lado do cliente deve ser apenas para facilitar a usabilidade do usuário final :)

**Comment by Srubens** [comment]
ok obrigado!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
