### ISSUE TITLE
Laços e Repetições

### ISSUE THREAD

**Issue by Thaigon** [da2k/curso-javascript-ninja#8229]
Bom dia Professor

Eu estou no momento na AULA #11 e resolve buscar alguns exercícios para fazer.
Se possível, você poderia me ajuda nessa resolução, não quero a resposta. rs

```
/*
Se listarmos todos os números naturais abaixo de 10
que são múltiplos de 3 ou 5, obtemos 3, 5, 6 e 9.

A soma desses múltiplos é 23.

Conclua a solução para que ela retorne a soma de todos
os múltiplos de 3 ou 5 abaixo do número passado.

Nota: Se o número for múltiplo de 3 e 5, conte-o apenas uma vez.
*/

function solution(number){
    while(1 <= number){
        number % 3 === 0 || number % 5 === 0 ? console.log(number) : 'false';
        number--;
    }
    return;
}

console.log(solution(9));

```

Eu cheguei até esse ponto. Como posso recuperar a lista e fazer a soma de todos os números.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Thaigon! Você pode fazer por passos, e ir armazenando os valores já computados em variáveis, ou ainda criando funções, onde cada uma faz uma coisa, e no final você vai executando as funções para obter os resultados que precisa :)

Exemplo: você criar uma função que recebe um array de números, e retorna um array filtrado, só com os múltiplos de 3. Pode fazer uma outra função, igual a essa, mas que retorna os múltiplos de 5.

Depois você pode criar um array, concatenando o resultado dessas duas funções. Nesse array você vai ter todos os múltiplos de 3 e 5.

Então, você pode fazer uma última iteração nesse array, somando todos os valores, e atribuindo o resultado a uma variável que vai receber o valor final :)

Deu pra entender mais ou menos a ideia? O ponto aqui é tentar fazer as coisas aos poucos, quebrar o problema em partes menores e ir resolvendo aos poucos, para que no final, você faça a junção de tudo e resolva o problema proposto :)

**Comment by Thaigon** [comment]
Obrigado professor.

Vou tentar fazer aqui. 

Posso te mandar quando tiver algo, para você poder analisar?

**Comment by fdaciuk** [comment]
Claro, só mandar :)

**Comment by Thaigon** [comment]
Boa noite professor.

Finalmente creio q conseguir, pelo menos não deu erro. rsrs

`(function(){
/*
Se listarmos todos os números naturais abaixo de 10
que são múltiplos de 3 ou 5, obtemos 3, 5, 6 e 9.

A soma desses múltiplos é 23.

Conclua a solução para que ela retorne a soma de todos
os múltiplos de 3 ou 5 abaixo do número passado.

Nota: Se o número for múltiplo de 3 e 5, conte-o apenas uma vez.
*/

var numberList = 10;
var z = 5;
var x = 3;
var soma = 0;


function solution(numberList){
    i = 0;
    while(i < numberList){
        i % 3 === 0 || i % 5 === 0 ? console.log(i) : ' ';
        i++;
    }
    for( i = 0 ; i < numberList ; i++){
        if(i % x === 0 || i % z === 0 ){
            soma+=i;
        }
    }
}

console.log('Números mútiplos de 3 e 5, abaixo de ' + numberList);
console.log(solution(numberList));
console.log('A soma desses múltiplos é ' + soma);

})();
`

**Comment by fdaciuk** [comment]
Muito bom @Thaigon! :clap: :clap:
