### ISSUE TITLE
String vazia retornando true

### ISSUE THREAD

**Issue by rafaelvianna** [da2k/curso-javascript-ninja#828]
Fala @fdaciuk, beleza?
Cara, to com uma dúvida aqui.
Nas aulas da semana 4, vc explica valores Truthy e Falsy, quando realizo o seguinte teste: !!""
ele retorna false. Como o esperado, Já que strings vazias retornam false.
Porém, se eu realizar o mesmo teste dando um espaço entre as aspas, ele retorna true.

!! "" = false
!! " " = true

Porque isso acontece? O js identifica espaço vazio como preenchimento?

**Comment by fdaciuk** [comment]
Isso mesmo @rafaelvianna! O espaço é um caractere, então ele é lido sim =)

**Comment by rafaelvianna** [comment]
Obrigado @fdaciuk ;)
