### ISSUE TITLE
Exercícios complementares

### ISSUE THREAD

**Issue by NicolasMatheus** [da2k/curso-javascript-ninja#8293]
Oi, tudo bom?
Tem algum site ou link que tenha mais exercícios/desafios, para poder praticar ainda mais o JS?
Antes de dar inicio ao JS no browser, eu gostaria de ficar bem mais familiarizado com a linguagem. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @NicolasMatheus! Eu te recomendaria seguir com o curso, pois ainda vamos ver bastantes coisas relacionadas à linguagem, só que agora interangindo um pouco mais com alguns elementos em tela :)

Após finalizar o curso, aí eu recomendo você partir para outras fontes de estudo, que vão te ajudar a entender melhor o que você já aprendeu, ou ainda te ensinar coisas novas :)

Coloque foco total em apenas uma fonte de estudos por vez, e você vai ver que você vai conseguir evoluir muito mais rápido :)

**Comment by fdaciuk** [comment]
@NicolasMatheus vou fechar a issue, mas se você ainda tiver dúvidas, só avisar :)
