### ISSUE TITLE
Challenge-26

### ISSUE THREAD

**Issue by matheus161** [da2k/curso-javascript-ninja#8367]
@fdaciuk
Olá professor, Bom dia! Tudo bem? Continuo sem entender a necessidade da biblioteca que foi feita no challenge-26. Fiquei bem perdido assistindo os vídeos e na hora da correção eu não entendi muito bem.

```
function DOM(elements){
  this.element = document.querySelectorAll(elements)
;}
```
Sobre essa function, ela pega todos os elementos da minha HTML? (a, parágrafos, titles e etc).

**Comment by fdaciuk** [comment]
Oi @matheus161! A ideia é abastrair para facilitar a criação de novos objetos, quando precisarmos manipular DOM.

Ao invés de selecionarmos todas as divs usando:

```js
var $divs = document.querySelectorAll('div');
```

Com a lib DOM, podemos fazer assim:

```js
var $divs = new DOM('div');
```

E, usando uma função construtora, podemos criar métodos usando o `prototype`, para abstrair os métodos padrão que usaríamos da API DOM :)

Por exemplo: imagine que precisamos selecionar todas as `div` e todos os `span` do nosso HTML. Se precisarmos colocar um evento de `click` em todos esses elementos, usando a API DOM padrão, teríamos que fazer um `forEach` para cada um, para iterar pelos elementos, e então aplicar o evento:

```js
var $divs = document.querySelectorAll('div')
var $spans = document.querySelectorAll('span')

$divs.forEach(function ($div) {
  $div.addEventListener('click', function (e) {
    // faz alguma coisa quando clicar em uma <div>
  }, false);
});

$spans.forEach(function ($span) {
  $span.addEventListener('click', function (e) {
    // faz alguma coisa quando clicar em um <span>
  }, false);
});
```

Agora, se criarmos um método na nossa lib DOM que abstrair esse método `addEventListener, e já faz o `forEach`, olha só como ficaria:

```js
function DOM (elements) {
  this.elements = document.querySelectorAll(elements);
}

DOM.prototype.on = function (event, listener) {
  this.elements.forEach(function (element) {
    element.addEventListener(event, listener, false);
  }, false);
};
```

Acima, criamos a função construtora `DOM`, que vai receber o seletor de elementos (o mesmo que usaríamos com `querySelectorAll`). E criamos o método `on`, que vai receber qual evento vai ser atribuído a todos os elementos, e uma função de `listener`, que será a função passada para o evento. A mesma função que passamos logo após o nome do evento `click`, no método `addEventListener`.

Lá no começo eu mostrei como ficaria para selecionar todas as `div` e `span` do nosso HTML usando a API DOM padrão. Agora olhe como fica o código usando nossa lib:

```js
var $divs = new DOM('div');
var $spans = new DOM('span');

$divs.on('click', function (e) {
  // faz alguma coisa quando clicar em uma <div>
});

$spans.on('click', function (e) {
  // faz alguma coisa quando clicar em um <span>
})
```

Percebe que, usando essa abastração, nosso código final fica muito mais simples e legível? Esse é o objetivo de criar uma função construtora de objetos :)

**Comment by matheus161** [comment]
Muito obrigado pela atenção professor, de fato o código fica bem mais legível e enxuto.

**Comment by fdaciuk** [comment]
Legal, que bom que ficou claro :)
Qualquer coisa, só avisar :)
