### ISSUE TITLE
[Challenge 10] IIFE

### ISSUE THREAD

**Issue by LilianTobace** [da2k/curso-javascript-ninja#8369]
Com a aula e ajuda de algumas outras fonte ficou bem claro que a utilização da IIFE é para ela ser executada assim que eu defini-la. Mas quando devo usa-la? E qual a diferente de definir uma função imediada:  `function( ) { }( );`  e inciar meu código com `$(document).ready(function(){ });` ?
Qual seria a diferença de usar um e outro sabendo que ambos serão executados assim que eu rodar meu código?

**Comment by fdaciuk** [comment]
Oi @LilianTobace! A ideia de usar IIFE é para que nosso código não fique exposto no escopo global.

Como funções têm escopo próprio, ao envolver qualquer arquivo JS usado no browser com uma IIFE, nós garantimos que aquele código vai ser visto só ali dentro daquela função, nunca fora dela.

Então, sempre que você for escrever JavaScript para usar no browser, o ideal é envolver cada arquivo .js com uma IIFE :)

Mais pra frente nós iremos ver mais a fundo sobre a ideia de escopos local e global, então acredito que isso vai ficar mais claro :)

**Sobre a diferença de usar uma IIFE e o `$(document).ready(function () {});` do jQuery:**

Na verdade, são coisas diferentes: a ideia do `$(document).ready()` é esperar até que todo o HTML seja lido pelo browser, e seja parseado no objeto que chamamos de **DOM**,e só então o código JavaScript usado dentro da função passada para o método `ready` deverá ser executado.

Já a IIFE vai ser executada assim que ela for avaliada, independente se todo o DOM já foi carregado ou não.

Vamos ver isso mais pra frente também, sobre porquê de fazer isso, vantagens, desvantagens, e, inclusive, como fazer o que o `.ready` faz usando a própria API DOM, sem o jQuery :)

---

Obs.: desculpe a demora na resposta, só vi sua mensagem agora :)
Quando abrir issue aqui, pode me marcar (com `@fdaciuk`) que eu vou receber notificação da issue e respondo o quanto antes, ok? :)

E fique à vontade para perguntar sempre que tiver dúvidas :)

**Comment by LilianTobace** [comment]
Muito obrigada Fernando, e sem problemas com a demora haha 
Mas agora estou mais pra frente do curso que deu pra entender melhor sobre o DOM e facilitou entender a diferença de ambos, eu estava confusa com a função da IIFE mas agora ficou mais claro. Obrigada!

**Comment by fdaciuk** [comment]
Perfeito :)
Qualquer dúvida, fique à vontade para perguntar :D
