### ISSUE TITLE
challenge-01- Erro para enviar.

### ISSUE THREAD

**Issue by daiannecaetano** [da2k/curso-javascript-ninja#8403]
@fdaciuk

**Comment by daiannecaetano** [comment]
Bom dia Professor, não estou conseguindo enviar para você challenge-01 eu fiz a publicação na minha branch, mais no momento da comparação igual você faz no video não está funcionando. Tem como me ajuda.?

**Comment by fdaciuk** [comment]
Oi @daiannecaetano! Claro, ajudo sim :)
Dá uma olhadinha se [essa resposta](https://github.com/da2k/curso-javascript-ninja/issues/7633#issuecomment-549067355) te ajuda =)

De qualquer forma, não é obrigatório o envio dos desafios. Você pode tentar resolver os desafios no seu computador, e acompanhar a correção sempre no início da próxima aula, ok?

E sempre que tiver dúvidas, fique à vontade para perguntar :)

**Comment by daiannecaetano** [comment]
Só pra questão de informações 
link onde eu conseguir resolver o meu problema.
https://www.youtube.com/watch?v=CGTsIz5t0eY

**Comment by fdaciuk** [comment]
Legal @daiannecaetano! Que bom que conseguiu resolver :)
Qualquer dúvida, só avisar :)
