### ISSUE TITLE
Challenge-29

### ISSUE THREAD

**Issue by matheus161** [da2k/curso-javascript-ninja#8414]
@fdaciuk
Boa tarde professor! Gostaria de esclarecer duas dúvidas.
A primeira é sobre a necessidade de utilizar o this.(alguma coisa), eu poderia utilizá-lo de outra forma? Segue a parte do código a qual me refiro 

```
 function app(){
    return{
      init: function(){
        console.log('app init');
        this.companyInfo(); //ISSO AQUI NÃO ENTENDI
      },
      
      companyInfo: function companyInfo(){
        var ajax = new XMLHttpRequest();
        ajax.open('GET', '/company.json', true);
        ajax.send();
        ajax.addEventListener('onreadystatechange', this.getCompanyInfo, false);
      } ,

      getCompanyInfo: function getCompanyInfo(){
        console.log(this);
      }
    };
  }

  app().init();
```

--------------------------------------------------------------------------------------------------------------
A segunda dúvida é um problema que estou passando, desde o challenge-28, até então não sei como proceder. 
Ao tentar criar um ajax, como no código acima, aparece o seguinte error no console. 

![image](https://user-images.githubusercontent.com/63413370/81845858-8ec8aa00-9527-11ea-9d70-8d29eacb5276.png)

"Access to XMLHttpRequest at 'file:///C:/company.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https."

Eu não consegui de forma alguma revolver isso, no challenge 28, vi e revi as aulas, pensando que poderia ser um problema entre o computador e o teclado, mas pelo visto ainda não descobri o que pode estar acontecendo. Desde de já muito obrigado pela atenção!

**Comment by fdaciuk** [comment]
Oi @matheus161! Vamos lá!

Sobre o uso do `this`: você poderia mudar a forma de usar os métodos: ao invés de usar uma função `app`, retornando um objeto, você poderia ter funções simples: `init`, `companyInfo`, etc., para esse caso sem problemas.

Aí não precisaria do `this`. Se quiser manter essa estrutura, o objeto teria que ter um nome para que você consiga chamá-lo pelo nome ao invés de usar o `this`. Algo como:

```js
function app () {
  const methods = {
    init: function () {
      // aqui, ao invés de usar o `this`, agora você consegue usar `methods.companyInfo()`.
    },

    companyInfo: function () {
      //...
    },
  };

  return methods;
}
```

Deu pra entender a ideia? :)

---

Sobre a segunda dúvida: você não vai conseguir fazer requests se não estiver usando o protocolo HTTP. Por isso, na aula eu comentei sobre usar algum servidor que já esteja instalado na sua máquina (apache, nginx), talvez até usar o servidor do Python, como mostrado na aula.

Se você não tiver nenhuma dessas opções, te recomendo uma bem simples: você já tem o node.js instalado na sua máquina? Se sim, deve ter o `npm` também. Rode no seu terminal esse comando para saber qual versão do npm você tem instalada:

```
npm -v
```

Se o resultado ver uma versão maior que 5, você pode usar o `npx` para subir um servidor sem instalar dependência nenhuma: via terminal, acesse o diretório onde está o seu projeto, e rode o comando:

```
npx serve
```

Isso vai subir um servidor na porta 5000 da sua máquina, e você poderá acessar sua aplicação via:

```
localhost:5000
```

Me deixe saber se funcionou :)

**Comment by matheus161** [comment]
Boa tarde, ainda continuo com esse problema professor! 

![image](https://user-images.githubusercontent.com/63413370/81961232-78365780-95e8-11ea-873b-ae4d1c2bebb0.png)

![image](https://user-images.githubusercontent.com/63413370/81961253-7ff5fc00-95e8-11ea-86a5-53fc4ab30253.png)

![image](https://user-images.githubusercontent.com/63413370/81961312-956b2600-95e8-11ea-83ea-0264adae3ec9.png)
(Testei com o challenge 28, o código está igual ao que o senhor fez em vídeo). Tive algumas dificuldades para pensar na minha solução e tive que recorrigi-lo todo, baseado na sua aula de correção. Mas ainda não consigo rodar.

**Comment by fdaciuk** [comment]
Legal, agora já deu outro erro :)
Esse é porque teve uma mudança recente na API, e ela só funcoina com `https`. Então só trocar o `http` por `https` na chamada da API que deve funcionar :)

**Comment by matheus161** [comment]
Professor muito obrigado pela ajuda, mas ainda me encontro com esse error aqui. Todavia, vou tentar refazer do zero para ver onde pode ter algo errado. Obrigado pela ajuda e desculpe por qualquer inconveniência. 

![image](https://user-images.githubusercontent.com/63413370/81963815-05c77680-95ec-11ea-89e3-29d997d2d726.png)

**Comment by fdaciuk** [comment]
Oi @matheus161! Acabei de olhar aqui, e o dev mudou o site e o domínio: agora é esse aqui:
https://apicep.com/api-de-consulta/

:)

**Comment by fdaciuk** [comment]
Oi @matheus161! Vou fechar a issue, mas se você tiver qualquer problema, só avisar, ok? :)
