### ISSUE TITLE
Sobre a Errata da aula #11

### ISSUE THREAD

**Issue by baltazarparra** [da2k/curso-javascript-ninja#844]
@fdaciuk você disse: 

_"O && deveria ser usado, mas na verdade o correto é usar o ||, pois, se qualquer um dos dois argumentos não for número, a função deve retornar false."_

Mas no caso, se usarmos o ||, ele não vai avaliar como true, se qualquer uma das duas forem válidas?
Por exemplo, se o primeiro numero for válido, ele nem vai chegar a testar o segundo, não é?

**Comment by fdaciuk** [comment]
Exatamente.. essa é a ideia, pois, se entrar no `if`, significa que algum dos valores não é número. Ou seja: se o primeiro já não for número, ele cai no `if`, retornando `false` =)

**Comment by fdaciuk** [comment]
Ficou claro @baltazarparra? =)
Qualquer coisa pode reabrir a issue, ok? =)
