### ISSUE TITLE
Challenge-24

### ISSUE THREAD

**Issue by LilianTobace** [da2k/curso-javascript-ninja#8451]
Olá Fernando, estou com uma dúvida no desafio 24, vi que durante sua explicação do desafio em uma parte do código você instanciou uma função com o operador "new" criando um objeto, como no código a seguir:

`function getRegexOperations(){
    return new RegExp('\\d+[' + operation().join('') + ']?', 'g');
 }`

Porém quando eu fiz o desafio, minha função ficou bem parecida com a sua mas sem o "new" e ele funcionou mesmo assim. Já que ele funcionou sem o "new" qual seria a necessidade de ter criado este objeto?

Agradeço desde já.

**Comment by fdaciuk** [comment]
Oi @LilianTobace! No caso do `RegExp`, segundo a especificação da liguagem, você pode usar ele como construtor de um novo objeto (usando `new`), ou só como função (como você fez).

Para essa função específica, o resultado é o mesmo, porque a especificação prevê isso, então você pode usar como quiser.

Mas o ideal é sempre usar o `new` para construtores, para evitar efeitos colaterais indesejados: nem toda função construtora vai detectar que você não usou o `new`, e você pode ter resultados inesperados, como dois objetos compartilhando a mesma referência :)

**Comment by fdaciuk** [comment]
Oi @LilianTobace! Vou fechar a issue, mas se você tiver qualquer problema, só avisar, ok? :)
E sempre que abrir issue, pode me marcar (com `@fdaciuk`), que eu recebo notificação e respondo mais rápido :D
