### ISSUE TITLE
Desafio da semana #2

### ISSUE THREAD

**Issue by alvimalessandro** [da2k/curso-javascript-ninja#8537]
Fernando,
Não consigo fazer o Git clone para dar continuidade ao Desafio da semana# 2. Instalei o GIT, fiz o fork no Github, copie o endereço ssh.  Copiei A URL do SSH mas quando vou ponho para rodar o Git Clone no Node.JS aparece a mensagem Uncught SyntaxError: Unexpect identifier     

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @alvimalessandro! Esse erro aparece quando você tenta fazer o `git clone`? Consegue mandar um print pra eu dar uma olhada no erro copleto?

**Comment by brjoaof** [comment]
tem que rodar o git clone pelo prompt e não pelo node. Pelo menos aqui comigo funciona assim +)

**Comment by fdaciuk** [comment]
Ah, faz sentido @brjoaof! Se o @alvimalessandro tentou rodar o `git clone` dentro do Node.js, é pra dar esse erro mesmo :)

@alvimalessandro, se foi esse o problema, pressione `Ctrl + D` para sair do REPL do Node.js e voltar para o terminal, que é onde você deveria executar o comando do git :)

De qualquer forma, se tiver dificuldades com git, não se preocupe em enviar os desafios por aqui, ok? Apenas tente resolver na sua máquina que já está ótimo :)

Se ficar com dúvidas, acompanhe a solução do desafio sempre no início da aula posterior, e se ainda assim ficar alguma dúvida, pode perguntar aqui, ok? Estou aqui pra te ajudar no que for preciso :)

**Comment by fdaciuk** [comment]
Oi @alvimalessandro! Vou fechar a issue, mas se você tiver qualquer problema, só avisar, ok? :)
