### ISSUE TITLE
Dúvida - Lógica dos exercícios

### ISSUE THREAD

**Issue by mariosout** [da2k/curso-javascript-ninja#857]
Olá Daciuk tudo bom? 

É, eu sei que os exercícios são para focarmos em aprender as arte manhas do JavaScript e chegar ao nivel ninja. Mas por exemplo caso em algum exercício eu faça exatamente o que você pediu mas na correção você faça algo mil vezes mais simples é melhor. É valido mandar o PR com a minha resposta certo?

**Comment by fdaciuk** [comment]
Fala @mariosout! Com certeza =)
Nem sempre a solução que eu apresentar será a melhor. Será apenas a opção que eu escolhi no momento para resolver. 

Claro que eu vou tentar procurar o melhor caminho, mas nem sempre vai ser =)

Se você resolver diferente, e ficar com dúvida de porquê as duas funcionam, ou não entender da forma como eu fiz, ou ainda tenha qualquer dúvida com relação à correção, não hesite em perguntar!

O foco dos desfios é que você consiga colocar em prática o que está aprendendo, então esse é o momento em que surgirão dúvidas, pois é quando você coloca a mão na massa xD

Se a sua solução ficar diferente, mas você usar somente o que foi visto em aula até o momento daquele desafio, quando eu corrigir vou dar como válido. No máximo, apontar o que poderia ser feito de forma melhor, ou até aprender algo, pois eu poderia ter resolvido de forma diferente xD

Essa troca de conhecimento sempre haverá, então não deixe de perguntar se as dúvidas surgirem, ok? =)

**Comment by mariosout** [comment]
Valeu cara!
