### ISSUE TITLE
Dúvida exercício #18

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-javascript-ninja#861]
Na última questão desse challenge, não consegui entender uma pequena parte. 
Exercício:
```
/*
  Vamos complicar um pouco agora :D

  Crie uma expressão regular que faça o match com um texto existente dentro de
  uma tag HTML. O texto deve ser capturado e substituído por:
  'O texto dentro da tag "[NOME DA TAG]" é "[TEXTO]"'

  Use a marcação abaixo para fazer o replace:
  "<h1>Título da página</h1><p>Este é um parágrafo</p><footer>Rodapé</footer>"

  A marcação deve permanecer como está, somente o texto deve ser substituído.
  No replace, utilize quebras de linha para deixar uma tag por linha.

  O resultado deve ser esse:
  <h1>O texto dentro da tag "h1" é "Título da página"</h1>
  <p>O texto dentro da tag "p" é "Este é um parágrafo"</p>
  <footer>O texto dentro da tag "footer" é "Rodapé"</footer>

  Uma dica: faça o match aos poucos. Para facilitar o teste, use o site
  https://regex101.com/#javascript e verifique se as capturas estão
  corretas, para depois aplicar no código ;)
  */
```

A regex utilizada para capturar o que ele pede é essa aqui:
``` /<(\w+)>([^<]+)(<\/\w+>)/g ```
Não entendi, a segunda captura. Porque devemos negar o `<` dentro de um lista?

**Comment by andersoonweb** [comment]
Consegui entender assistindo as aulas. Só em corrija se eu estiver equivocado.
O `^` fora de uma lista, ele corresponde ao início da string. E dentro de uma lista, ele nega um elemento dentro da string.

**Comment by fdaciuk** [comment]
Exatamente isso @andersoonweb =)

O parte `[^<]]+`, significa: case com qualquer caractere, **menos** com o `<` =)

Só me marca na issue da próxima vez, senão eu demoro pra ver xD

**Comment by andersoonweb** [comment]
Beleza! :smile:
