### ISSUE TITLE
[aula 2]

### ISSUE THREAD

**Issue by ianca18** [da2k/curso-javascript-ninja#8612]
ola boa tarde não estou conseguindo baixa meus arquivos para fazer as Challenge 2#

**Comment by ederusena** [comment]
oque em especifico vc nao ta conseguindo fazer?

**Comment by ianca18** [comment]
conseguir já obrigada

**Comment by fdaciuk** [comment]
Oi @ianca18! Desculpe a demora na resposta, não vi sua issue! Quando abrir issue, pode sempre me marcar (com `@fdaciuk`) pra eu receber a notificação da sua dúvida, ok? :)

Fique à vontade para perguntar sempre que tiver dúvidas :)
