### ISSUE TITLE
onde encontra o gabarito das questoes?

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8613]
aonde encontra o gabarito dos Desafio Semana #1 e os demais

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @terceirolho! Por enquanto, apenas nos vídeos das aulas (sempre no início da aula posterior ao desafio). Mas estou trabalhando para colocar todos os desafios resolvidos [nessa branch](https://github.com/da2k/curso-javascript-ninja/tree/desafios-resolvidos). Vai demorar um pouco pra terminar, mas todos estarão lá logo menos :)
