### ISSUE TITLE
aula 13 sobre repositórios e github

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8617]
Olá Professor. na aula 13 sobre repositorios e github, com o git já instalado, vc pede pra ir no terminal. mas  vc nao mostra como ir no terminal. que terminal é esse?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @terceirolho! É o mesmo que eu mostro na primeira aula :)

**Comment by terceirolho** [comment]
qual mesmo? eu vejo que vc abre uma tela preta pra colar o SSH git@github.com:terceirolho/curso-javascript-ninja.git
eu tentei digitar git clone isso no node. mas nao consegui, o que fazer?

**Comment by fdaciuk** [comment]
Não é dentro do node, é no terminal direto. Se você entrou com o comando `node` e está tentando rodar o clone, vai dar um erro :)

Para sair do node, pressione `Ctrl + D`, ou `Ctrl + C` duas vezes para voltar para o prompt do terminal :)

De qualquer forma, se você já fez isso uma vez, não precisa fazer de novo tá? Pode fazer o clone uma única vez :)

**Comment by terceirolho** [comment]
Bom dia Fernando! Eu não estou compreendendo o que vc esta dizendo.
O que é terminal direto? Prompt de Comando que vc fala? Eu escrevo o que vc fala pra escrever '' git clone '' + SSH e nao funciona. Eu não consigo abrir o que vc mostra no video em meu Github eu gostaria que me explicasse, pois seguindo o passo do video nao consegui.

**Comment by fdaciuk** [comment]
@terceirolho você conseguiu a fazer os passos dos primeiros vídeos? Onde eu mostro como abrir um terminal, e fazer o clone do repositório?

Pelo que estou entendendo, você já está na aula 13, mas está tendo problemas com o terminal só agora, é isso mesmo?

Consegue me mostrar uns prints do erro pra eu ver como você está tentando fazer?

**Comment by terceirolho** [comment]
eu consegui! 
eu dei continuidade nas aulas porque eu to de ferias da faculdade e nao posso parar, ai eu dei sequencia... como eu faço pra te mandar os prints?

**Comment by terceirolho** [comment]
![eu fiz o fork pra challenge-01 e parece que todos os exercicios esta com fork](https://user-images.githubusercontent.com/64038338/85922002-a1d4d680-b856-11ea-925d-1ff3a79814a7.png)

**Comment by terceirolho** [comment]
![so que em branch nao aparece  somente challenge-01](https://user-images.githubusercontent.com/64038338/85922007-b0bb8900-b856-11ea-8c62-308f9148da80.png)

**Comment by terceirolho** [comment]
![nao consegui fazer isso](https://user-images.githubusercontent.com/64038338/85922018-c29d2c00-b856-11ea-94ac-26fb1e115572.png)

**Comment by terceirolho** [comment]
sobre as imagens:

1.eu fiz o fork pra challenge-01 e parece que todos os exercicios esta com fork
2.so que em branch nao aparece. somente challenge-01
3. nao consegui fazer isso

**Comment by fdaciuk** [comment]
Entendi seu problema: você não tem o git instalado no seu computador. 

Mas sem problemas, vamos usar uma solução mais simples: ao invés de usar o git, acesse o seu repositório no GitHub, deixe a branch "master" selecionada, e clique no botão verde "Clone".

No popup que aparecer, vai ter uma opção "Download ZIP". Clicando nesse botão, você vai baixar um arquivo `.zip` com todos os desafios. Você só vai precisar descompactar esse arquivo e pronto!

Pode fazer os desafios só no seu computador mesmo, não se preocupe em mandar Pull Request. Isso era necessário antes do curso estar na Udemy, para geração do certificado.

Apenas tente resolver os desafios no seu computador mesmo, e qualquer dúvida, fique à vontade para perguntar que vou te ajudando, ok? :)

**Comment by terceirolho** [comment]
Entendi, mas olhe.... eu já tenho ele aqui em documentos. so não consigo abrir no github. eu tenho github 

![image](https://user-images.githubusercontent.com/64038338/86124739-fb850d00-bab1-11ea-8452-7a7cce06d1d0.png)

**Comment by terceirolho** [comment]
E eu to com dúvida também. Porque na branch que criei challenge-1 e challenge-2 aparece todos os demais exercícios, e qual o sentido de criar uma pra cada exercício?

**Comment by fdaciuk** [comment]
Oi @terceirolho! A ideia de criar branches separadas é para ter as resoluções de cada desafio em uma branch. Mas assim.. eu só sugeri dessa forma pois antes do curso estar na Udemy, eu gerava o certificado de participação do curso através dos PRs. Como agora não precisa fazer isso, você pode criar uma branch só para as resoluções e resolver tudo nela, sem problema algum, ok? :)

Sobre não estar conseguindo usar o git e GitHub: o problema, pelo seu print do terminal, é que parece que você não tem o git instalado na sua máquina. Como você está usando windows, esse processo pode ser um pouco chatinho de fazer, mas nada impossível :)

Minha recomendação: se você estiver usando o windows 10, instale o WSL2, para que você tenha acesso ao terminal do Linux dentro do windows. Assim, todos os comandos que você executaria em um terminal Linux, você vai conseguir rodar no windows também :)

À partir do WSL, você pode instalar o git, node, etc, de forma muito mais simples :)

Qualquer dúvida ou dificuldade, me avise que eu vou te ajudando, ok? :)

**Comment by terceirolho** [comment]
mas eu tenho o github instalado professor!
![image](https://user-images.githubusercontent.com/64038338/86512082-339f8f00-bdd5-11ea-9d26-aa9f6f0238d3.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Você está confundindo os softwares :)

O GitHub é a plataforma onde ficam os seus repositórios. Ele tem uma aplicativo desktop, que é esse que você tem instalado. Até aí tudo bem.

Mas quando você tenta usar pela linha de comando, você precisa do Git. O Git é o software que faz o gerenciamento de versões do seu projeto.

São dois softwares diferentes, ok? :)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
