### ISSUE TITLE
DÚVIDA FUNCTION ANONYMOUS

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8630]
Olá Professor. gostaria de saber porque deu isso. Function anonymous

![image](https://user-images.githubusercontent.com/64038338/85923307-5f17fc00-b860-11ea-8454-1454faa94b3e.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @terceirolho! Isso acontece porque a função foi criada sem dar um nome a ela. Veja que você criou a função assim:

```js
valor.ganhei = function () {
  ...
}
```

Para que apareça o nome da função, após a palavra chave `function` você dá o mesmo nome da propriedade do objeto (no seu caso, `ganhei`:

```js
valor.ganhei = function ganhei () {
  ...
}
```

**Comment by fdaciuk** [comment]
Oi @terceirolho! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
