### ISSUE TITLE
dúvida exercício 3

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8651]
Minha dúvida é porque não parece o valor quando chamo o caminhouQuantosMetros e aparece NaN 
![image](https://user-images.githubusercontent.com/64038338/86480408-53c34580-bd24-11ea-89d0-c24d62de95a2.png)

@fdaciuk

**Comment by terceirolho** [comment]
professor  mais uma duvida, 

![image](https://user-images.githubusercontent.com/64038338/86492220-c55ebc00-bd43-11ea-8f28-35f2fc1ceebc.png)


meu codigo esta imprimindo ''Olá, eu sou o YU CHAN, tenhp 30 undefined, 1.7, meu peso é 60 e, só hoje, eu já caminhei 60 undefined'' 

PORQUE????

**Comment by Matheusiaromo** [comment]
Você não atribuiu valor a idadeAnos e metrosCaminhados


Logo se a idade e os metros não forem 1, eles ficarao como undefined

**Comment by Matheusiaromo** [comment]
![image](https://user-images.githubusercontent.com/67007761/86494449-91879480-bd4b-11ea-87eb-5b2afaedc86c.png)

**Comment by terceirolho** [comment]
> if (**idade.anos** === **1**){
> **idadeAnos** = "ano "
> }
> tá. mas se nao for === 1? se nao for igual a 1, ela vai ter o valor que tu declarou (**var idadeAnos;**) e isso retorna **undefined** porque voce nao definiu nenhum valor pra ela.

ah ta, agora entendi, valeu demais

**Comment by fdaciuk** [comment]
Oi @terceirolho! Sobre a sua primeira dúvida:

> Minha dúvida é porque não parece o valor quando chamo o caminhouQuantosMetros e aparece NaN

Isso acontece exatamente pelo motivo que o @Matheusiaromo comentou: no objeto, você declarou a propriedade como `caminhouQuantosMetros`, e passou o valor zero. Até aí tudo bem.

Mas na função `andar`, você usou `pessoa.CaminhouQuantosMetros` (com o `C` maiúsculo). Como essa propriedade não existia no objeto `pessoa`, ela foi criada no momento em que você definiu ela na função `andar`.

E como ela não tinha valor inicial, seu valor incial ficou definido como `undefined`.

Quando você tenta fazer uma soma de um número com `undefined`, você vai ver esse `NaN`, que significa _Not a Number_, ou que o resultado não é um número :)

---

Sobre a sua segunda dúvida:

> meu codigo esta imprimindo ''Olá, eu sou o YU CHAN, tenho 30 undefined, 1.7, meu peso é 60 e, só hoje, eu já caminhei 60 undefined!''
> PORQUE????

Isso acontece porque você não definiu um valor inicial para as variáveis `idadeAnos` e `metrosCaminhados`. Logo, elas recebem por padrão o valor `undefined`.

Você só faz a modificação desses valores dentro dos `if`s, mas como o seu código não entra em nenhum dos `if`s, o valor dessas variáveis continua `undefined`, até chegar no final da função.

Você precisa definir um valor inicial para essas variáveis (usando a versão "plural", já que você usa o `if` para definir o "singular").

Deu pra entender o problema? :)

**Comment by terceirolho** [comment]
acho que sim. e quanto ao sexo, feminino e masculino ? eu tentei fazer com que saisse o 'a' e não 'o' e nao consegui professor. brigado desde já pela ajuda

**Comment by fdaciuk** [comment]
Oi @terceirolho! Você chegou a definir a propriedade `sexo` no objeto `pessoa`? Provavelmente é isso. Como a definição padrão é `o`, ele não entra no seu `if`, quando você testa o valor de `pessoa.sexo` pela string `"Feminino"` :)

**Comment by terceirolho** [comment]
eu declarei var pessoa = {nome: 'YU', sobrenome: 'CHAN', sexo: 'feminino', idade: 30, altura: 1.70, peso: 60, andando: false, caminhouQuantosMetros: 0};

**Comment by fdaciuk** [comment]
Certo, o problema então é que você definiu a string com `f` minusculo, e testou no `if` com `F` maiúsculo. 
Letras maiúsculas e minúsculas são caracteres diferentes dentro de uma string :)

**Comment by terceirolho** [comment]
ah sim. faz sentido!

**Comment by fdaciuk** [comment]
Qualquer dúvida avisa ae :D
