### ISSUE TITLE
DÚVIDA AULA 24 - ESCOPO DE VARIÁVEIS E FUNÇÕES

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8671]
![image](https://user-images.githubusercontent.com/64038338/86919549-cbb3b600-c0fe-11ea-91fd-6ff186ede29b.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @terceirolho! Na primeira chamada da função `letras`, você passou `1` como argumento, para o parâmetro `a`. Por isso retornou `1`. Essa variável `a` é local, ela só existe dentro da função.

Por isso, na segunda chamada, quando você executou a função sem argumentos, o retorno é `undefined`, já que você não passou nenhum valor :)

Lembra que vimos que funções têm escopo próprio? Qualquer variável definida dentro de uma função só vai existir lá. Então, para que sua função `letras` sempre retorne algum valor diferente de `undefined`, você precisa passar algo no primeiro argumento sempre que executá-la :)

Ficou claro? :)

**Comment by terceirolho** [comment]
mas eu passei letras(1,2) no argumento, deveria aparecer 1 ao chamar letras() não?
como neste exemplo . depois que eu passo o valor retorna um valor
![image](https://user-images.githubusercontent.com/64038338/86922454-0c153300-c103-11ea-94d4-ec52bfd96d53.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Legal, acho que entendi sua dúvida. Vou tentar explicar de outra forma, me diz se assim fica mais claro, ok? Vamos lá :)

Quando você cria uma função, e espera que argumentos sejam passados para fazer alguma computação dentro da função, aqueles argumentos são sempre locais, e o valor desses argumentos "morre" junto com a execução da função. Vamos ao exemplo da função de soma. O código abaixo cria uma função que espera que dois números sejam passados via argumento, e retorna a soma dos dois números:

```js
function soma (x, y) {
  return x + y;
}
```

Bem simples, nada demais. Se executarmos a função sem passar argumentos, os parâmetros `x` e `y`, dentro da função, irão receber `undefined`:

```js
soma(); // NaN
```

O resultado é `NaN`, pois a operação o JS vai tentar fazer é `undefined + undefined`. Como estamos tentando fazer uma operação numérica com um tipo de dado que não é número (no caso, `undefined`), então o resutlado é `NaN`, ou seja: não é um número!

Agora, se eu chamar a função, passando dois números, eu consigo ver o resultado da soma dos mesmos:

```js
soma(1, 2); // 3
```

À partir daqui é onde acho que está sua dúvida: esse valor `3` apareceu, pois foi resultado da chamada da função `soma`, passando dois argumentos (`1` e `2`).

Se você fizer uma nova chamada da função, dessa vez, sem passar argumentos, o resultado vai ser igual ao primeiro `NaN`:

```js
soma(); // NaN
```

Ou seja: a função é reaproveitável. Sempre que você quiser que o retorno da função seja `3`, você precisa passar os argumentos necessários para ela fazer a soma **no momento em que você passa os argumentos**.

Pra você entender: por baixo dos panos, o que acontece quando você executa a função `soma(1, 2)` é:
- primeiro o JS vai verificar se existe uma variável com o nome de `soma` no escopo em que você chamou a função;
- se essa variável existir, o JS vai verificar se essa variável é uma função;
- se sim, então ele vai executar a função, passando os dois argumentos;
- ao passar os argumentos, ele vai para dentro da função e faz o que tem que ser feito lá dentro:
  - dentro da função, é esperado um valor para o parâmetro `x` e um valor para o parâmetro `y`;
  - ao receber esses valores, será feita a soma dos mesmos;
  - ao terminar a soma, não há mais nada para fazer na função, e o resultado é retornado;
  - quando a função retorna o valor, o JS não precisa mais desse valor, nem das variáveis `x` e `y`, que só existem dentro da função, então ele "descarta" as variáveis, já que elas só devem existir no escopo (dentro) da função.

Por isso, na próxima chamada de `soma()`, o retorno é `NaN`, não `3` como você pensou :)

Deu pra entender como as coisas funcionam? :)

**Comment by terceirolho** [comment]
AAAAAAAaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa entendi agora, nossa brigadx

por a função letras retornar a
qualquer coisa que eu passar vai dar apenas o 1, pois o 1 representa o a
como eu passei letras(1,2);

entao ele so retorna quando tem valor atribuído

**Comment by fdaciuk** [comment]
Exatamente isso :)
Que bom que ficou claro! Qualquer coisa, só avisar :D
