### ISSUE TITLE
DÚVIDA DESAFIO 4

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8672]
Gostaria de saber o porque seria necessário utilizar a função obterCor, pois toda vez que eu chamo a variável cor do objeto carro. eu tenho a mesma resposta.
![image](https://user-images.githubusercontent.com/64038338/86929081-cf9a0500-c10b-11ea-9f20-aab975b48f14.png)

@fdaciuk

**Comment by terceirolho** [comment]
outra dúvida é essa daqui
![image](https://user-images.githubusercontent.com/64038338/86930375-54395300-c10d-11ea-8457-522292047a3b.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! :D  

> Gostaria de saber o porque seria necessário utilizar a função obterCor, pois toda vez que eu chamo a variável cor do objeto carro. eu tenho a mesma resposta.

Apenas pra você entender que isso é possível. Em alguns momentos, quando estivermos trabalhando com objetos, vamos dar preferência ao uso dos métodos, ao invés de modificar diretamente o valor de propriedades :)

Mais pra frente no curso isso deve ficar mais claro :)

---

> outra dúvida é essa daqui

Você chegou a rodar o código todo no console? Se faltar alguma parte dele, o resultado final pode não ser o esperado mesmo :)

**Comment by ianca18** [comment]
Ola, quando você enviar mensagem
 Assim é para mim ? As vezes não entendo ou devo responde

Em qui, 9 de jul de 2020 08:59, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Oi @ianca18! Sim, quando eu marcar seu nome de usuário é pra você :)
Pode responder por e-mail mesmo, ou entrar no GitHub e responder por lá, pra eu saber se você entendeu, ou se ficou alguma dúvida, ok? :)

**Comment by ianca18** [comment]
Neste caso chamar a propriedade ou o método tem o mesmo resultado mas você
geralmente métodos podem ser criado para algo mais complexo como por
exemplo somar ou calcular algum dado de algumas das propriedades

Em qua, 8 de jul de 2020 11:14, terceirolho <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
É exatamente essa a ideia @ianca18! :)

**Comment by terceirolho** [comment]
ah sim entendi, eu fiz denovo até conseguir fazer que imprimisse

**Comment by fdaciuk** [comment]
Perfeito @terceirolho! Qualquer dúvida, só avisar :)
