### ISSUE TITLE
Git Clone - Desafio 2

### ISSUE THREAD

**Issue by helcioogomes** [da2k/curso-javascript-ninja#8677]
Não estou conseguindo clonar o git dá permissão negada

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @helcioogomes! Quando você clicar no botão de "Clone", escolha a opção "HTTPS", que vai ser mais fácil clonar :)
Aí só vai precisar entrar com seu usuário e senha do GitHub, e pronto :)
Qualquer dúvida, só avisar!

**Comment by fdaciuk** [comment]
Oi @helcioogomes! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
