### ISSUE TITLE
Duvida Desafio 2

### ISSUE THREAD

**Issue by helcioogomes** [da2k/curso-javascript-ninja#8678]
Não estou conseguindo clonar o git dá permissão negada

**Comment by fdaciuk** [comment]
Oi @helcioogomes! Ao fazer o clone, você pode escolher a opção HTTPS, que vai dar certo :)
Me deixe saber se conseguiu :)

**Comment by fdaciuk** [comment]
Oi @helcioogomes! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
