### ISSUE TITLE
NÃO CONSIGO ACESSAR CHALLENGE 5

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8682]
Socorro não consegui acessar o challenge 5 criei pull request mas ai quando é pra adicionar a branch nao aparece nada
![image](https://user-images.githubusercontent.com/64038338/87164964-d6f21780-c29f-11ea-8824-faf8c3a0310b.png)

@fdaciuk

**Comment by terceirolho** [comment]
eu consegui agora tinha que colocar no challenge 01

**Comment by fdaciuk** [comment]
Conseguiu resolver @terceirolho?

**Comment by terceirolho** [comment]
sim. mas to confusa ainda. eu preciso muito entender essas coisas. mas nao tive esclarecimento ate o momento do curso. eu to com aquele problema de nao acessar pelo comando Git 

baixei o Git como disse, executei como mostra no tutorial. mas nao funcionou. entrou  loop infinito de y

**Comment by terceirolho** [comment]
![image](https://user-images.githubusercontent.com/64038338/87307620-50804480-c4f0-11ea-881d-679df6beac0b.png)

**Comment by terceirolho** [comment]
colei o meu SSH lá no comando e apareceu '' 
Clonando em 'curso-javascript-ninja' ...
A autenticidade do host 'github.com (18.231.5.6)' não pode ser estabelecida.
A impressão digital da chave RSA é SHA256: nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Tem certeza de que deseja continuar a conexão (sim / não / [impressão digital])?

eu disse yes
entrou o loop infinito de y

![image](https://user-images.githubusercontent.com/64038338/87307666-655cd800-c4f0-11ea-9712-b1edc906ed71.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Como você está usando windows, minha recomendação é que você faça duas coisas:
- A primeira é instalar o WSL2. Se não souber como fazer isso, tem [esse curso aqui](https://www.youtube.com/watch?v=YcR8pKvjx44&list=PLlAbYrWSYTiOpefWtd6uvwgKT1R-94Zfd) do meu amigo Willian Justen, que vai mostrar o passo-a-passo de como fazer.

- A segunda coisa é seguir esse tutorial aqui para criar uma chave SSH no seu PC e subir para o GitHub:
https://docs.github.com/pt/github/authenticating-to-github/connecting-to-github-with-ssh

Siga cada um dos links na ordem. Após fazer todos os passos, você deve conseguir clonar o repositório via linha de comando usando SSH :)

Me deixe saber se deu certo :)

**Comment by terceirolho** [comment]
Oieee bom dia. então eu vi o video do seu amigo. so que o jeito que ele mostra no video não esta dando certo. eu nao consigo encontrar windows inside nas minhas configurações. já fiz o meu cadastro. não aparece pra mim dar continuidade  (https://www.youtube.com/watch?v=f4_lTRR1jtw&list=PLlAbYrWSYTiOpefWtd6uvwgKT1R-94Zfd&index=2) 2min 50

**Comment by terceirolho** [comment]
![image](https://user-images.githubusercontent.com/64038338/87427560-5ab94600-c5b7-11ea-978d-666a5a1a51b0.png)
eu entro ai e nao aparece nada também

**Comment by fdaciuk** [comment]
Oi @terceirolho! Acredito que o WSL2 já está disponível, sem a necessidade do cadastro no insider. Segue por [essa página aqui](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index) que você deve conseguir :)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)

**Comment by terceirolho** [comment]
oie. olha eu nao to conseguindo eu to ficando louca
porque nao ta dando certooooo eu n sei mais o que fazer, isso me atrasou tudo. eu to sem fazer seu curso. minhas ferias vao acabar e eu no vou conseguir terminar, porque quando minhas aulas voltarem o bixo vai pegar. eu nao sei mais

**Comment by terceirolho** [comment]
![image](https://user-images.githubusercontent.com/64038338/87938545-2210e500-ca6d-11ea-931d-a11a48041125.png)

**Comment by terceirolho** [comment]
nao ta dando pra fazer essa primeira parte
![image](https://user-images.githubusercontent.com/64038338/87938591-31902e00-ca6d-11ea-89b5-6d02968c9296.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! O que eu te recomendaria nesse caso é: ignore o Git e GitHub por enquanto, e resolva os desafios apenas no seu computador. O Git / GitHub não deveriam impedir de você conseguir seguir com o curso, pois tendo os desafios em mãos, você consegue resolvê-los localmente (no seu PC).

Dessa forma você consegue seguir com o curso sem ficar travada :)
