### ISSUE TITLE
DÚVIDA 

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8754]
Professor eu to confusa. serio. tipo eu faço as coisas aqui e tal as vezes funciona, mas eu nem sei o que eu to fazendo ai eu fico fuçando e ai eu vi uma coisa falando que eu tenho 4 branch. eu queria ter controle do que eu to fazendo. mas eu não sei o que eu to fazendo aqui no github.

tipo isso daqui, não entendi
![image](https://user-images.githubusercontent.com/64038338/88328912-83e87d80-ccff-11ea-9da2-530e4f713e8c.png)

to perdida nem sei o que te perguntar

@fdaciuk

**Comment by terceirolho** [comment]
eu tenho apenas essas challenge
sendo que eu to na 5 e eu nem sei como eu cheguei nela

![image](https://user-images.githubusercontent.com/64038338/88329015-b2feef00-ccff-11ea-8104-2043dd5b3726.png)

**Comment by terceirolho** [comment]
e eu nem sei se voce ta vendo os exercicios ou não

**Comment by fdaciuk** [comment]
Oi @terceirolho! Eu acho que você tá indo pelo lado mais complicado. Como eu tinha falado em outra issue, o GitHub não é tão importante nesse início: apenas resolva os desafios na sua máquina, e compare o que você fez com a solução apresentada sempre no início da próxima aula :) 

Como o curso já está todo gravado, todos os desafios já estão disponíveis no GitHub, e as resoluções sempre no início das aulas, não há mais a necessidade de eu verificar os exercícios um a um :)

Mas você deve perguntar aqui sempre que tiver dúvidas, ou estiver com dificuldade de entender algum assunto, ok? :)

Mas minha recomendação é: faça da forma mais fácil primeiro: resolva os desafios **só na sua máquina**, para que você consiga focar seus estudos **no JavaScript**.

Depois, quando você estiver com um pouco mais de tempo ocioso, aí eu recomendo estudar Git e GitHub, beleza? :)

**Comment by terceirolho** [comment]
ok.
