### ISSUE TITLE
DÚVIDA CHALLENGE 5

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8756]
![image](https://user-images.githubusercontent.com/64038338/88334577-5fdd6a00-cd08-11ea-94a3-e3db7008f4f1.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @terceirolho! Vamos lá :)

Veja que, onde você marcou em vermelho, você criou a função `myFunction` retornando apenas `objeto`, que é o valor que ela recebe? Por isso ele exibe o objeto todo. Olha a diferença da `myFunction` na área vermelha, e a `myFunction` criada lá em cima, na área verde :)

Conseguiu compreender o que aconteceu?

**Comment by terceirolho** [comment]
para que saia individualmente tenho que colocar  2 variáveis e retornar conforme o colocado no verde?

**Comment by fdaciuk** [comment]
Isso mesmo! Quando você define uma função, é **você quem diz o que ela deve fazer!**

Na parte verde, você definiu uma função chamada `myFunction`, que espera dois argumentos: um array e um índice.
E, ao receber esses dois valores, a função vai retornar o valor do array que está naquele índice passado.

Já na segunda definição, você disse que `myFunction` vai receber um argumento qualquer, e vai somente retornar esse argumento. Então se você passasse `1`, ela te retornaria `1`. Se você passasse um objeto vazio, ela retornaria esse mesmo objeto vazio:

```js
console.log(myFunction(1)) // 1
console.log(myFunction({})) // {}
console.log(myFunction([1, 2, 3])) // [1, 2, 3]
```
 
Conseguiu compreender? :)

**Comment by terceirolho** [comment]
ok. obrigado

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
