### ISSUE TITLE
DÚVIDA CHALLENGE 6

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8760]
PORQUE DEU ERRO?
![image](https://user-images.githubusercontent.com/64038338/88392084-c9ee2180-cd91-11ea-9b35-302529caa071.png)

@fdaciuk

**Comment by terceirolho** [comment]
não é porque eu coloquei + team[position -1] porque ja alterei e continua o mesmo

**Comment by terceirolho** [comment]
e eu declarei var team = ['coelho', 'dogs', 'cats', 'tigre', 'loser'];

**Comment by fdaciuk** [comment]
Oi @terceirolho! É que você usou o operador `>` (que é binário, ou seja, espera dois valores), com apenas um valor.

Eu sei que, olhando à primeira vista, pode parecer que isso funcionaria:

_quero testar se a posição é menor que 1 e maior que 5_: `posicao < 1 || > 5`.

Mas o problema é como eu comentei acima: os operadores de comparação são binários, ou seja, eles esperam sempre um valor à direita dele, e um valor à esquerda.

Então o erro no seu código, é que faltou adicionar o parâmetro `posicao` na comparação com `> 5`. O código dentro do `if` deveria ser:

```
if (posicao < 1 || posicao > 5) {
```

Percebeu a diferença? :)

**Comment by terceirolho** [comment]
aaaaa sim. entendy

**Comment by terceirolho** [comment]
e tenho outra dúvida:
![image](https://user-images.githubusercontent.com/64038338/88394866-85b15000-cd96-11ea-9a1a-472b92abbb71.png)


ta dando erro, porque? ta igual o teu que tu fez

**Comment by terceirolho** [comment]
consegui achar o problema, tinha que converter os valores hexa em string.
mas quando vou executar, aparece assim:
![image](https://user-images.githubusercontent.com/64038338/88398904-69b0ad00-cd9c-11ea-977f-c287b605065d.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Confere como você criou a função. Pode ser que, na hora de transformar os valores em string, você pode ter mudado alguma outra coisa :) 

Qualquer coisa, cola aqui também o print da versão final da função e as chamadas do console pra gente ver :)

**Comment by terceirolho** [comment]
ok

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
