### ISSUE TITLE
DUVIDA CHALLENGE 7

### ISSUE THREAD

**Issue by terceirolho** [da2k/curso-javascript-ninja#8775]
![image](https://user-images.githubusercontent.com/64038338/89038665-29f74180-d317-11ea-9314-c4ce50a633a9.png)

Porque nessa parte é [5] sendo que o segundo item do array é  somente [1]

@fdaciuk

**Comment by terceirolho** [comment]
![image](https://user-images.githubusercontent.com/64038338/89039064-d507fb00-d317-11ea-9cd2-2861b6950f02.png)

**Comment by terceirolho** [comment]
outra duvida: porque ta saindo o 21, sendo que ele nao é par e o comando ta pra imprimir apenas os pares
![image](https://user-images.githubusercontent.com/64038338/89041484-d3d8cd00-d31b-11ea-98b0-ba790bc789be.png)

**Comment by fdaciuk** [comment]
Oi @terceirolho! Vamos lá :)

### _Porque nessa parte é [5] sendo que o segundo item do array é somente [1]_

A primeira parte do desafio pede que você crie um array com 5 itens, certo? Então aqui temos os índices de 0 a 4 (já que temos  5 itens no array).

Depois é pedido para criar uma função que adiciona itens no array, e então, o próximo passo é criar um outro array, e adicionar ao primeiro.

Esse outro array, ao ser adicionado ao primeiro, vai ser o sexto item no primeiro array, logo, índice 5.

Por isso, para conseguir acessar informações desse segundo array, à partir do primeiro, usamos o índice `5` do primeiro array (sexto item), que é a posição desse segundo array :)

Deu pra entender até aqui? :)

### _outra duvida: porque ta saindo o 21, sendo que ele nao é par e o comando ta pra imprimir apenas os pares_

Para responder a essa segunda dúvida, podemos fazer o que chamamos de "teste de mesa". Esse teste é basicamente colocar no papel todos os valores das variáveis que estão sendo usadas no nosso código, até que ele termine de executar. 

Vamos fazer juntos? Acompanha comigo aqui:

- A variável `contador` inicia com valor `10`;
- Usamos o `while`, que vai executar todo o seu bloco de código gerado pelas chaves (chamamos de **iterar**), até que contador seja menor ou igual a `20`;
- Iniciamos a 1ª iteração:
  - temos uma condição que verifica se o valor atual de `contador`, dividido por `2` tem resto zero.
    - Se a condição for verdadeira:
      - Exibe o valor de `contador` no console e então acrescenta `1` ao valor do contador;
      - Passa para próxima linha, onde incrementa `+1` ao valor do contador.
    - Se a condição for falsa:
      - Não faz nada (só retorna uma string vazia que não vai pra lugar nenhum);
      - Passa para próxima linha, onde incrementa `+1` ao valor do contador.
  - se o valor de `contador` ainda for menor ou igual a `20`, continua o loop, passando para a próxima iteração.

Vamos colocar isso em uma tabela para ficar fácil de visualizar tudo o que está acontecendo:

Iterações   | valor de `contador` | deve continuar iterando? `contador <= 20` |  resultado da condição `contador % 2 === 0`  | valor exibido no console | novo valor (incrementado dentro do console) | novo valor (incrementado na segunda linha) |
-------------- | ------------------------: | :--------------------------------------------------------: | :-----------------------------------------------------------: | -------------------------------: | -----------------------------------------------------------: | ------------------------------------------------------------: |
1ª iteração | 10                           | sim                                                                 | `true`                                                                 | 10                                   | 11                                                                     | 12                                                                      |
2ª iteração | 12                           | sim                                                                 | `true`                                                                 | 12                                   | 13                                                                     | 14                                                                      |
3ª iteração | 14                           | sim                                                                 | `true`                                                                 | 14                                   | 15                                                                     | 16                                                                      |
4ª iteração | 16                           | sim                                                                 | `true`                                                                 | 16                                   | 17                                                                     | 18                                                                      |
5ª iteração | 18                           | sim                                                                 | `true`                                                                 | 18                                   | 19                                                                     | 20                                                                      |
6ª iteração | 20                           | sim                                                                 | `true`                                                                 | 20                                   | 21                                                                     | 22                                                                      |
7ª iteração | 22                           | não                                                                 | x                                                                       | x                                     | x                                                                        | x                                                                        |

Perceba que a iteração só exibe no console até o valor `20`. Então esse `21` não está vindo do seu `while`, a lógica está certa :) 

_De onde ele vem então?_

Quando você roda um código direto no console, ele vai te retornar o valor da última expressão passada. Nesse caso, a única expressão que retorna algum valor é a atribuição para `contador`, que retorna o valor passado para ele.
O navegador então exibe o último valor que ele tinha acesso de `contador` antes de acabar a iteração, por isso mostra `21`. Ao final da iteração, ainda acontece um pós-incremento, para que `contador` receba `21 + 1`. Então se você rodar chamar só o nome da variável `contador`, deve ver o valor final dele atualizado `22` :)

Pode ser um pouco complexo de entender ao rodar um código direto no console do navegador, por isso eu sempre peço para que você crie um arquivo e execute o código à partir desse arquivo, já que o console serve somente para testes rápidos :)

Com o teste de mesa, só quis te mostrar como você mesma consegue testar seu próprio código, pra entender o que está acontecendo :)

Ficou claro? :)

**Comment by terceirolho** [comment]
ok entendi eu acho, mas eu to preocupada com o repositorio git D:

**Comment by terceirolho** [comment]
outra pergunta, onde consigo ver as outras issues que abri?

**Comment by fdaciuk** [comment]
Oi @terceirolho! É só você clicar na aba _Issues_ aqui do repositório :) 
Você vai ver, no cabeçalho da tabela de issues, um filtro com o nome _Author_.

Clique ali e digite seu nome de usuário: `terceirolho`, e dê enter.

Ao fazer isso, vai aparecer todas as issues criadas por você, separadas por _Open_ e _Closed_. Aí é só clicar nesses links para ver as que ainda estão abertas (se houver alguma) e as que já foram fechadas :)
