### ISSUE TITLE
aula 10 [ Wrapper Objects ]

### ISSUE THREAD

**Issue by diogorodrigues** [da2k/curso-javascript-ninja#882]
@fdaciuk Não entendi a diferença, no modo prático, em se usar construtores e conversores.
Pois, no final, var idade = new Number( '28' ); e var idade = Number( '28' ); não dá no mesmo?

**Comment by fdaciuk** [comment]
Fala @diogorodrigues =)

Na aula 12 isso deve ficar um pouco mais claro. Mas o que acontece é o seguinte: objetos são passados por referência. Valores literais não. O que isso significa?

Olha esse exemplo:

```js
var objeto1 = {};
var objeto2 = {};
console.log(objeto1 === objeto2) // false
```

Porque o resultado da comparação é `false`, se eu tenho dois objetos "iguais"?

O que acontece com objetos em JavaScript, é que, quando um objeto é criado, ele fica armazenado em um espaço de memória. Criar objetos usando `{}` e `new Object()` dá no mesmo (apesar do primeiro modo ser mais rápido).

A questão principal é: sempre que você cria um objeto, e atribui ele a uma variável, como fizemos acima, o que acontece na verdade é:

- o objeto é criado em memória;
- uma **referência** a esse objeto é passado para a variável.

Ou seja: a variável passa a **apontar** para aquele espaço de memória em que o objeto foi criado. No nosso exemplo, criamos dois objetos diferentes, que foram criados em espaços de memória diferentes (quando eu falo **memória**, quero dizer a memória do seu computador mesmo =)).

Agora, se você fizer isso aqui:

```js
var objeto1 = {};
var objeto2 = objeto1;
console.log(objeto2 === objeto1) // true

objeto2.propriedade = 1;
console.log(objeto1) // { propriedade: 1 }
```

Veja que criamos um único objeto, e atribuímos a duas variáveis. O resultado do primeiro `console.log` é `true`, pois as duas variáveis são **ponteiros** do mesmo objeto. Elas **apontam** para o mesmo objeto.

A prova disso é o exemplo logo abaixo: ao criar uma propriedade em `objeto2`, se você der um `console.log` em `objeto1`, a propriedade também estará lá! Essa propriedade não está duplicada. O que acontece é que, como as duas variáveis apontam para o mesmo lugar, se eu mudar o objeto a partir de qualquer uma das variáveis, a alteração será refletida em qualquer variável que esteja apontando para esse mesmo objeto.

Deu pra entender até aqui? =)

---

Valores primitivos não são objetos. São o que chamamos de **valores literais**. E esses valores não têm um lugar específico em memória. Eles só são armazenados quando você atribui eles a alguma variável. Por isso, se você faz o mesmo exemplo de testar valores literais, o resultado é diferente:

```js
var numero = 28;
var numero2 = 28;
console.log(numero === numero2); // true
```

---

Agora sim, respondendo a sua pergunta: quando você usa `new Number('28')`, por exemplo, um objeto é criado em memória. Faça o teste:

```js
var numeroObjeto = new Number('28');
var numeroLiteral = 28;
console.log(numeroObjeto === numeroLiteral); // false
```

`numeroObjeto` é um objeto. `numeroLiteral` é um literal. Quando você usa `Number`, `String`, etc., sem o `new`, então o JavaScript somente **converte** o valor, sem criar um novo objeto:

```js
var numeroWrapper = Number('28');
var numeroLiteral = 28;
console.log(numeroWrapper === numeroLiteral); // true
```

Ficou mais claro? =)

**Comment by fdaciuk** [comment]
@diogorodrigues, conseguiu entender essa parte? =)

**Comment by tiagocedrim** [comment]
Resposta iradíssima @fdaciuk

**Comment by LFeh** [comment]
Bela resposta. Entendi perfeitamente agora ;)

**Comment by fdaciuk** [comment]
@diogorodrigues, vou fechar essa issue, se ainda ficou alguma dúvida, me avisa que eu abro novamente, ok? =)

**Comment by cristofersousa** [comment]
bah isso é um baita artigo top da galáxia! 👏
