### ISSUE TITLE
Cloud9 IDE e GIT

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-javascript-ninja#885]
Bom dia @fdaciuk !

Poderia me ajudar nessa questão de clonar o repositório do git?
Faz uns dois meses que parei o curso porque troquei de emprego, e como estou chegando bem cedo, vou continuar o curso usando o ambiente Cloud9 (https://c9.io), pois ai posso fazer no trabalho e depois em casa.

Eu já clonei o meu repositório do curso, mas só tem a branch master. Como faço para baixar as outras branchs que eu já fiz dos exercicios anteriores?

Depois, eu gostaria de deixar atualizada a minha pasta do curso no meu notebook, como eu faria para deixar atualizado lá também (branchs e arquivos)?

Valeu Fernando!

**Comment by fdaciuk** [comment]
Opa! Bom dia @gustavom =)

Você precisa fazer essa atualização manualmente, uma a uma. Se estiver usando Linux (ou algum terminal que tenha suporte para bash), você pode seguir as instruções [dessa issue](https://github.com/da2k/curso-javascript-ninja/issues/79), que basicamente faz o que você faria manualmente, mas em um loop, usando shell script =)

**Comment by gustavom** [comment]
Valeu @fdaciuk !

Eu fiz a atualização das branches uma a uma agora pouco, antes de ver a sua resposta.

O que eu fiz no cloud9 seguindo a issue indicada foi rodar o comando :
`git remote add upstream git@github.com:da2k/curso-javascript-ninja.git`

O comando do 'for', eu posso rodar ele sempre? Por exemplo, faço duas ou três aulas no ambiente linux  online, e quero atualizar o meu macbook, rodo ele certo?

`for remote in `git branch -r | grep -v master `; do git checkout --track $remote ; done`

**Comment by fdaciuk** [comment]
Sim, isso deve funcionar corretamente =)
