### ISSUE TITLE
Duvidas Com o Git .

### ISSUE THREAD

**Issue by lucasbicskei** [da2k/curso-javascript-ninja#8922]
@fdaciuk

Olá professor Fernando , sou novato em programação , consegui executar o  primeiro e o segundo desafio ,
mas estou com dificuldades para usar com o Git compartilhar os documentos , pode me ajudar ? lucasbicskei@gmail.com

**Comment by fdaciuk** [comment]
Oi @lucasbicskei! Não precisa subir no GitHub se estiver com dificuldades. Apenas resolva os desafios no seu computador, e acompanhe as correções no início das aulas posteriores.

Se tiver qualquer dúvida, fique à vontade para perguntar, ok? Estou aqui pra te ajudar :)

**Comment by fdaciuk** [comment]
Oi @lucasbicskei! Vou fechar a issue, mas se você ainda tiver dificuldades, só avisar :)
