### ISSUE TITLE
Como posso fazer algo igual esse modelo?

### ISSUE THREAD

**Issue by natgoncalves** [da2k/curso-javascript-ninja#8925]
Olá. Gostaria de uma ajuda com um site que estou fazendo.Não consegui descrever direito pra pesquisar algo na internet e nem entender muito bem como foi feito, já que o modelo que estou querendo seguir é um tema do Wordpress e tem tanta coisa que fico confusa, rs.

Eu preciso fazer um box como esse de Orçamento, logo acima dessa parte: https://www.doutorreparo.com/#contato
Onde tem perguntas e de acordo com o que você clica acontece uma transição e aí aparecem novas perguntas, até trazer de fato o orçamento de acordo com o que escolheu, tudo dentro do mesmo box.

Existe algum plugin ou algo do Bootstrap que possa me ajudar? É muito complexo de fazer?

Agradeço desde já a ajuda.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @natgoncalves! Não sei se existe algo pronto pra fazer isso, mas não tem muito segredo: você pode usar CSS ou JavaScript para fazer o efeito acontecer após o clique.

Com CSS, você pode usar, por exemplo, o `rotate3d`:
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d

Para JS, existem várias bibliotecas de animação. A mais conhecida é a GSAP: 
https://greensock.com/

Espero que isso te dê um norte pra você conseguir fazer o que precisa :)

**Comment by natgoncalves** [comment]
Olá Fernando, dei uma olhada. Mas acho que antes de eu pensar na animação em si, estou tentando pensar em como fazer funcionar a lógica aqui. Estava imaginando fazer um else if, porque preciso de 4 condições. Vou tentar explicar.

Tenho esse código html aqui:

`
<div class="box">

<div class="salvar-arquivos">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">Você possui arquivos para <span class="ft-medium">Salvar?</span></p>

	<div class="row">
		<div class="col item">
			<a class="apagar">
				<span class="icon rounded-circle">
					<img src="images/icons/deletar.svg" alt="Pode apagar tudo" title="Pode apagar tudo" class="img-fluid">
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Pode apagar tudo</p>
			</a>
		</div>
		<div class="col item">
			<a class="salvar">
				<span class="icon rounded-circle">
					<img src="images/icons/salvar.svg" alt="Preciso salvar arquivos!" title="Preciso salvar arquivos!" class="img-fluid">
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Preciso salvar arquivos!</p>
			</a>
		</div>
	</div>
</div>


<div class="softwares display">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">Você utiliza softwares profissionais, como PS, CDR, AI?</p>

	<div class="row">
		<div class="col item">
			<a class="nao-uso-softwares">
				<span class="icon resposta rounded-circle d-flex align-items-center justify-content-center ft-dark-blue">
					NÃO
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Não sei do que você está falando</p>
			</a>
		</div>
		<div class="col item">
			<a class="uso-softwares">
				<span class="icon resposta rounded-circle d-flex align-items-center justify-content-center ft-dark-blue">
					SIM
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Sim eu uso softwares profissionais</p>
			</a>
		</div>
	</div>
</div>


<div class="opcao1-orcamento display">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">O valor da formatação será de:<br/>
		<span class="ft-bold">R$120 a R$150</span>
	</p>

	<div class="row d-flex justify-content-center mb-4">
		<div class="col-md-10">
			<a href="#contato" class="btn btn-lg btn-block btn-cta btn-dark-blue bg-dark-blue ft-bold scrollSuave" role="button">
				QUERO AGENDAR AGORA
			</a>
		</div>
	</div>

	<p class="text-center ft-white">Os softwares necessários deverão ser <u>informados no agendamento.</u></p>

	<p class="text-center ft-white">Fatores como desempenho do equipamento e a velocidade de conexão da sua internet, poderão interferir no preço final.</p>
</div>


<div class="opcao2-orcamento display">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">O valor da formatação será de:<br/>
		<span class="ft-bold">R$100 a R$120</span>
	</p>

	<div class="row d-flex justify-content-center mb-4">
		<div class="col-md-10">
			<a href="#contato" class="btn btn-lg btn-block btn-cta btn-dark-blue bg-dark-blue ft-bold scrollSuave" role="button">
				QUERO AGENDAR AGORA
			</a>
		</div>
	</div>

	<p class="text-center ft-white">Fatores como desempenho do equipamento e a velocidade de conexão da sua internet, poderão interferir no preço final.</p>
</div>


<div class="opcao3-orcamento display">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">O valor da formatação será de:<br/>
		<span class="ft-bold">R$80 a R$90</span>
	</p>

	<div class="row d-flex justify-content-center mb-4">
		<div class="col-md-10">
			<a href="#contato" class="btn btn-lg btn-block btn-cta btn-dark-blue bg-dark-blue ft-bold scrollSuave" role="button">
				QUERO AGENDAR AGORA
			</a>
		</div>
	</div>

	<p class="text-center ft-white">Fatores como desempenho do equipamento e a velocidade de conexão da sua internet, poderão interferir no preço final.</p>
</div>
</div>
`

O que preciso é o seguinte:

- Se o usuário clicar em .salvar e depois em .uso-softwares, deverá mostrar a div .opcao1-orcamento;
- Se o usuário clicar em .salvar e depois em .nao-uso-softwares, deverá mostrar a div .opcao2-orcamento;
- Se o usuário clicar em .apagar e depois em .uso-softwares, deverá mostrar a div .opcao1-orcamento;
- Se o usuário clicar em .apagar e depois em .nao-uso-softwares, deverá mostrar a div .opcao3-orcamento;

Ou seja, dependendo de qual link ele clicar (que eu deixei cada um com uma class), deverá aparecer determinada div com o valor do orçamento. Até então eu tinha conseguido fazer usando jQuery, com onClick para clicar no link e aparecer tal div e sumir a div atual, usando `display: block;` e `display: none;`, porém percebi que precisaria de algo a mais, seguindo essas condições acima, como posso iniciar isso, usando javascript ou jQuery?

**Comment by natgoncalves** [comment]
Fernando, consegui fazer o que eu queria, porém não sei se é a melhor forma. Como posso melhorar isso?

```
$(".salvar").click(function(){
    $('.salvar-arquivos').css("display", "none");
    $('.softwares').css("display", "block");

    $(".nao-uso-softwares").click(function(){
        $('.softwares').css("display", "none");
        $('.opcao2-orcamento').css("display", "block");
    });
});

$(".apagar").click(function(){
    $('.salvar-arquivos').css("display", "none");
    $('.softwares').css("display", "block");

    $(".nao-uso-softwares").click(function(){
        $('.softwares').css("display", "none");
        $('.opcao3-orcamento').css("display", "block");
    });
});

$(".uso-softwares").click(function(){
    $('.softwares').css("display", "none");
    $('.opcao1-orcamento').css("display", "block");
});
```

**Comment by fdaciuk** [comment]
Oi @natgoncalves! Não é muito legal colocar eventos dentro de outros eventos, a menos que seja algo muito específico. No seu caso, não precisa :) 

O que você pode fazer é: 
1. **crie uma variável que recebe um array vazio.** 
Esse array vai ser alterado para receber as opções selecionadas

2. **crie os eventos um abaixo do outro, sem colocar eventos dentro de eventos como no seu exemplo acima**
Assim você consegue criar apenas dois listeners de evento, ao invés de vários com código repetido como você fez. A ideia também é: ao clicar em uma opção, essa opção será adicionada ao array, e então você exibe as próximas opções até finalizar e você conseguir exibir o resultado final.

Um exemplo de como ficaria:

```js
const opcoes = []

$('.salvar', '.apagar').on('click', function () {
  // salvar qual valor foi clicado no array "opcoes"
  // abrir a próxima tela
})

$('.uso-software', '.nao-uso-software').on('click', function () {
  // salvar qual valor foi clicado no array "opcoes"
  // abrir a tela de orçamento com base no valor do array
})
```

3. **Para o resultado final:**
Nessa etapa, você vai analisar os valores que estão dentro do array `opcoes` para exibir o orçamento que você precisa.

Deu pra entender a ideia? :)

**Comment by natgoncalves** [comment]
Então, eu consegui fazer dessa forma aqui pra ele abrir a próxima tela e salvar a class do link clicado no array:

```javascript
var opções = []

$('.salvar').on('click', function () {
  opcoes.push( $(this).attr('class') );

  $('.salvar-arquivos').css("display", "none");
  $('.softwares').css("display", "block");
});
```

Porem nada funciona se eu passo as duas opções no evento, como você me mostrou `$('.salvar', '.apagar').on('click', function () {` e essa é minha dificuldade primeiro, por isso acabei repetindo código =/
Porque no caso, se eu clico em .salvar OU .apagar, vai acontecer o que coloquei na função, ou seja, some a div atual (.salvar-arquivos) e aparece a próxima (.softwares).

**Comment by fdaciuk** [comment]
Certo.. faz tempo que não uso o jQuery, e acabei não testando o código, só jogando o que seria uma ideia :)

Mas fiz um exemplo funcional, veja se faz sentido para o que você precisa:
https://codesandbox.io/s/kind-elgamal-7ofrl?file=/src/index.js

Dá uma olhada nos arquivos `inde.js` e `index.html` pra ver o código :)

**Comment by fdaciuk** [comment]
Daria pra fazer facilmente sem jQuery também, se quiser:
https://codesandbox.io/s/hardcore-grass-mp69x?file=/src/index.js

**Comment by natgoncalves** [comment]
Fiz desse jeito com o jQuery mesmo, pq depois ia colocar um fade entre as transições.
Só que uma dúvida. No resultado, o array está trazendo as classes que estão dentro da div e não a classe da div em si. Por exemplo, se eu clico em .salvar e depois em .uso-softwares, ele está trazendo todas as classes de elementos dentro dessas divs e não a classe da div em si (.salvar e .uso-softwares apenas).
E também não sei como fazer pra mostrar uma das 3 opções de orçamento, que são 3 divs separadas, já que pra aparecer depende das duas opções que o usuário clicou anteriormente..

**Comment by fdaciuk** [comment]
@natgoncalves dá uma olhada no meu código: lá tem o exemplo de como vai ser adicionada a classe só do elemento clicado :) 

Depois, para aparecer as opções de orçamento, você só precisa verificar as combinações das classes no array :)

**Comment by natgoncalves** [comment]
Então, entendi o seu exemplo, porém sua div está vazia, só tem o texto 'Salvar':

`<button class="salvar">Salvar</button>`

A minha tem mais conteúdo:

```html
<button class="salvar">
  <span class="icon rounded-circle">
  <img src="images/icons/salvar.svg" alt="Preciso salvar arquivos!" title="Preciso salvar arquivos!" class="img-fluid">
  </span>
  <p class="texto-resposta text-center ft-white ft-regular">Preciso salvar arquivos!</p>
</button>
```
Então quando traz o resultado, ele não traz a class .salvar, mas as classes .icon .rounded-circle etc..

**Comment by fdaciuk** [comment]
Não entendi o que você quer fazer.. no meu exemplo, eu adiciono a classe `salvar` no array. Se o evento estiver no seu botão de salvar, e o código for como eu fiz, ele vai salvar do mesmo jeito :)

Não é isso que vc quer fazer?

**Comment by natgoncalves** [comment]
Sim, entendi o seu exemplo, e é isso mesmo que preciso, porém no meu código, quando implementei, ele tá trazendo outro resultado, porque dentro do meu botão tem uma imagem e um parágrafo, com outras classes, então ele está trazendo não a classe .salvar, mas sim outras classes que ele encontra dentro, entende?

Vou colocar meu html aqui novamente:

```html
<div class="salvar-arquivos">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">Você possui arquivos para <span class="ft-medium">Salvar?</span></p>

	<div class="row">
		<div class="col item">
			<button class="apagar">
				<span class="icon rounded-circle">
				<img src="images/icons/deletar.svg" alt="Pode apagar tudo" title="Pode apagar tudo" class="img-fluid">
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Pode apagar tudo</p>
			</button>
		</div>

		<div class="col item">
			<button class="salvar">
				<span class="icon rounded-circle">
				<img src="images/icons/salvar.svg" alt="Preciso salvar arquivos!" title="Preciso salvar arquivos!" class="img-fluid">
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Preciso salvar arquivos!</p>
			</button>
		</div>
	</div>
</div>

<div class="softwares">
	<p class="titulo text-center ft-white ft-bold">Orçamento</p>
	<p class="pergunta text-center ft-white">Você utiliza softwares profissionais, como PS, CDR, AI?</p>

	<div class="row">
		<div class="col item">
			<button class="nao-uso-softwares">
				<span class="icon resposta rounded-circle d-flex align-items-center justify-content-center ft-dark-blue">
				NÃO
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Não sei do que você está falando</p>
			</button>
		</div>
		
		<div class="col item">
			<button class="uso-softwares">
				<span class="icon resposta rounded-circle d-flex align-items-center justify-content-center ft-dark-blue">
				SIM
				</span>
				<p class="texto-resposta text-center ft-white ft-regular">Sim eu uso softwares profissionais</p>
			</button>
		</div>
	</div>
</div>
```

E aqui como está meu js:

```javascript
	const arquivosOpcoes = [".salvar", ".apagar"];
	const softwaresOpcoes = [".uso-softwares", ".nao-uso-softwares"];

	const $salvarArquivos = $(".salvar-arquivos");
	const $softwares = $(".softwares");
	const $resultado = $(".resultado");
	const opcoes = [];

	$softwares.style.display = "none";
	$resultado.style.display = "none";

	arquivosOpcoes.forEach((buttonClass) => {
	  $(buttonClass).addEventListener(
	    "click",
	    (e) => {
	      opcoes.push(e.target.className);
	      $softwares.style.display = "block";
	      $salvarArquivos.style.display = "none";
	    },
	    false
	  );
	});

	softwaresOpcoes.forEach((buttonClass) => {
	  $(buttonClass).addEventListener(
	    "click",
	    (e) => {
	      opcoes.push(e.target.className);
	      $softwares.style.display = "none";
	      $resultado.style.display = "block";

	      $resultado.append(opcoes.join(", "));
	    },
	    false
	  );
	});

	function $(element) {
	  return document.querySelector(element);
	}
```

Isso é o que aparece no meu resultado do array:
`img-fluid, icon resposta rounded-circle d-flex align-items-center justify-content-center ft-dark-blue
`

**Comment by fdaciuk** [comment]
Ah, agora entendi o problema :)
Isso acontece porque o `e.target` aponta para o elemento clicado. Como o evento foi colocado no `button`, mas existem outras tags dentro, o clique dispara também para essas outras tags.

Para passar a classe somente do elemento onde o evento foi adicionado, use `e.currentTarget` no lugar de `e.target` que deve resolver :)

**Comment by natgoncalves** [comment]
Agora deu certo! rs
Só uma última dúvida, na questão de mostrar os valores do orçamento de acordo com a opção selecionada.

Não sei o que está errado nas condições que coloquei, mas uma está dando errado, que é a última. Ou seja, quando clico em .apagar e .nao-uso-softwares está abrindo a .opcao2-orcamento e não a .opcao3-orcamento, o que está errado?
Meu código está assim:

```javascript
        const arquivosOpcoes = [".salvar", ".apagar"];
	const softwaresOpcoes = [".uso-softwares", ".nao-uso-softwares"];

	const $salvarArquivos = $(".salvar-arquivos");
	const $softwares = $(".softwares");
	const $resultado = $(".resultado");
	const opcoes = [];

	const $orcamentoOpcao1 = $(".opcao1-orcamento");
	const $orcamentoOpcao2 = $(".opcao2-orcamento");
	const $orcamentoOpcao3 = $(".opcao3-orcamento");

	$softwares.style.display = "none";
	$resultado.style.display = "none";

	arquivosOpcoes.forEach((buttonClass) => {
	  $(buttonClass).addEventListener(
	    "click",
	    (e) => {
	      opcoes.push(e.currentTarget.className);
	      $softwares.style.display = "block";
	      $salvarArquivos.style.display = "none";
	    },
	    false
	  );
	});

	softwaresOpcoes.forEach((buttonClass) => {
	  $(buttonClass).addEventListener(
	    "click",
	    (e) => {
	      opcoes.push(e.currentTarget.className);
	      $softwares.style.display = "none";
	      $resultado.style.display = "block";

	      $resultado.append(opcoes.join(", "));

	      	if (opcoes.indexOf('salvar' && 'uso-softwares') > -1) {
		        $orcamentoOpcao1.style.display = "block";
		    } else if (opcoes.indexOf('salvar' && 'nao-uso-softwares') > -1) {
		        $orcamentoOpcao2.style.display = "block";
		    } else if (opcoes.indexOf('apagar' && 'uso-softwares') > -1) {
		        $orcamentoOpcao1.style.display = "block";
		    } else if (opcoes.indexOf('apagar' && 'nao-uso-softwares') > -1) {
		        $orcamentoOpcao3.style.display = "block";
		    }

	    },
	    false
	  );
	});

	function $(element) {
	  return document.querySelector(element);
	}
```

**Comment by fdaciuk** [comment]
Desse jeito não vai funcionar pq vc passou uma expressão de curto circuito para o `indexOf`.. acho que uma solução simples seria usar um objeto para fazer um `de / para` à partir do valor de opções, e verificar se o resultado bate. Se bater, você exibe o resultado que você quer. Ficaria algo assim:

https://codesandbox.io/s/duvida-natgoncalves-19yf1?file=/src/index.js

**Comment by natgoncalves** [comment]
Ahh entendi, agora funcionou perfeitamente. Muuuuito obrigada por toda a paciência e ajuda!

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer coisa, só avisar :)
