### ISSUE TITLE
[Aula #01] Dúvidas sobre arrays e objetos

### ISSUE THREAD

**Issue by gabriel-vieira14** [da2k/curso-javascript-ninja#8952]
Podemos colocar um array como propriedade de um objeto?
```
var pessoa = {}
pessoa.nome = []
nome[0] = "Gabriel";
nome[1] = "GB";
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gb1456v! Pode sim! Mas para setar novos itens nesse array, você precisa usar a sintaxe completa, chamando o objeto, o ponto, o nome do array, e só então o índice.

No caso do seu exemplo:

```js
var pessoa = {};
pessoa.nome = [];
pessoa.nome[0] = 'Gabriel';
pessoa.nome[1] = 'GB';
```

Aí acessando `pessoa.nome` você vai ver um array com os itens: `['Gabriel', 'GB']` :)

**Comment by gabriel-vieira14** [comment]
E teria alguma diferença prática usar um ou outro?

**Comment by fdaciuk** [comment]
Não entendi muito bem a dúvida. Um ou outro o que?

**Comment by gabriel-vieira14** [comment]
> Não entendi muito bem a dúvida. Um ou outro o que?

No caso usar um array ou um objeto.. pra mim em essência parecem ser a mesma coisa.. Não entendi muito bem a diferença entre eles... Por isso minha pergunta;;

**Comment by fdaciuk** [comment]
Ah sim! Objetos e arrays servem para propósitos diferentes.. mais pra frente nós ainda vamos falar bastante sobre eles, mas basicamente é assim:

- objetos servem para quando você tem um tipo de dado "chave / valor", e não precisa de uma ordem;
- arrays só têm valores, o que seriam as "chaves" são os índices numerados. Arrays são ordenados por padrão;
- um objeto pode ter uma chave, onde o seu valor é um array (como no exemplo da sua dúvida);
- arrays podem conter objetos, se você precisar representar, por exemplo, uma lista de itens com chave / valor de forma ordenada :)

Basicamente são essas as diferenças! Mas como eu disse, mais pra frente você vai ver mais a fundo sobre essas duas estruturas de dados do JS :)

Fique sempre muito à vontade para perguntar sempre que tiver dúvidas :)
