### ISSUE TITLE
Aula 25

### ISSUE THREAD

**Issue by clarabatt** [da2k/curso-javascript-ninja#897]
Fala @fdaciuk , voltei com tudo agora :sunglasses: 
Fiquei com uma dúvida na aula sobre eventos.

Porque se passarmos a função anônima como parâmetro para `removeEventListener` não funciona?
Por que temos que extrair a função?

**Comment by fdaciuk** [comment]
@clarabatt show hein! :dancer: :dancer: =)

Vamos lá: lembra que objetos são passados por referência? A cada objeto que você cria, ele ocupa um espaço na memória. E sempre que você reatribui alguma variável que está apontando para um objeto, para uma nova variável, agora as duas variáveis apontam para o mesmo objeto, fazendo com que, ao modificar o objeto usando uma variável, ao tentar acessar a outra variável, o objeto também foi alterado, pois é o mesmo? Lembra disso?

```js
var a = {};
var b = {};
console.log(a === b); // false

var c = {};
var d = c;
console.log(d === c); // true
```

Agora, voltando lá na primeira aula, quando falamos sobre tipos de dados: temos 5 tipos de dados em JS que chamamos de "tipos primitivos", que são imutáveis, que são:
- number, string, boolean, null e undefined.

Todos os outros dados são **objetos**. Objeto do tipo `object`, objeto do tipo `array`, objeto do tipo `function`.

Ou seja: todo objeto é passado por referência.

No caso das funções, é exatamente a mesma coisa. Quando você usa uma função de callback para adicionar um listener de evento, ela ocupa um espaço de memória. Para que você possa remover alguma função específica de um listener, você tem que passar a referência dela para o `removeEventListener`, e não criar uma nova função. Exemplo:

```js
$button.addEventListener('click', function () {
  console.log('clicou no botão');
}, false);
```

Veja que foi passada uma função anônima para o `addEventListener`. A única forma de executar essa função específica é clicando no botão. Agora, se fizermos assim:

```js
function handleClick () {
  console.log('clicou no botão! (ou não)');
}

$button.addEventListener('click', handleClick, false);
// ...
$button.removeEventListener('click', handleClick, false);

console.log(handleClick()); // 'clicou no botão! (ou não)
```

Veja que nós podemos usar essa função como quisermos: podemos atrelar a um evento, podemos chamá-la diretamente, etc. Porque quando essa função foi criada, nós demos um nome para ela, para que possamos usá-la no futuro.

Esse nome vai fazer referência ao espaço de memória que essa função (ou objeto do tipo função) está ocupando.

Se você usar atribuir essa função a outras variáveis (sem executá-la), você tem o mesmo efeito, pois todas as variáveis vão apontar para a mesma função (mesmo objeto que ocupa um espaço de memória específico):

```js
function handleClick () {
  console.log('clicou no botão! (ou não)');
}

var addClickListener = handleClick;
var removeClickListener = handleClick;

$button.addEventListener('click', addClickListener, false);
// ...
$button.removeEventListener('click', removeClickListener, false);

console.log(handleClick()); // 'clicou no botão! (ou não)
```

Ficou claro? =)

**Comment by clarabatt** [comment]
sim sim :+1:  :smile:

**Comment by fdaciuk** [comment]
:+1:
