### ISSUE TITLE
Não estou conseguindo ter uma chave ssh publica, eu faço os passos mas da tudo errado

### ISSUE THREAD

**Issue by marlonferreiraninja** [da2k/curso-javascript-ninja#8993]
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marlonferreiraninja! Não é preciso uma chave SSH para ter acesso ao seu repositório do GitHub. Você pode só clicar naquele botão verde - "Code" - e escolher a opção HTTPS.

Ou ainda pode baixar um ZIP do repositório (nesse mesmo botão), para tentar resolver os desafios no seu computador mesmo :)

Não é necessário enviar Pull Requests dos desafios. Apenas tente resolver no seu PC que já está ótimo, ok? :)

**Comment by fdaciuk** [comment]
Oi @marlonferreiraninja! Vou fechar a issue, mas se você ainda tiver dúvidas, só comentar aqui que eu te ajudo, ok? :)
