### ISSUE TITLE
[Aula 04]  - Duvida sobre diminuir o numero de Pessoas

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9027]
Oi Fernando, 

Eu fiquei com dúvida na parte de Diminuir o numeros de pessoas. 
To tentando entender como que o fato de adicionar a validação de ```&&totalPessoas > = carro.assentos```, faz com que o código diminuia o número de pessoas sendo que não esta sendo escrito comando para de fato diminuir. 
Tipo carro.quantidadePessoas -= numeroPessoas.

Estou falando explicitamente sobre este trecho aqui:
``` if(carro.quantidadesPessoas === carro.assentos && totalPessoas >= carro.assentos) {
return "O carro já está lotado!"
```

Eu vou colocar aqui como eu havia feito para você entender meu raciocínio. Eu criei um método separado para Diminuir.
Coloquei, muitos else if, mas esta funcionando.

```
carro.adicionarPessoas  = function(y) {

    var pessoas = 'pessoas';    
    var assentosSobrando = carro.assentos - carro.quantidadesPessoas;
    if(assentosSobrando === 1) { pessoas = 'pessoa'}

    if(assentosSobrando == 0){
        return 'O carro já está lotado ! Já temos'+ ' '+ carro.quantidadesPessoas + ' '+ 'pessoas no carro !'
    } else if 
        (assentosSobrando <=5 && y === assentosSobrando  ) {
            carro.quantidadesPessoas += y; 
        
    return 'Já temos'+ ' '+ carro.quantidadesPessoas + ' '+ 'pessoas no carro !'

        } else if
            (assentosSobrando <=5 && y < assentosSobrando){
                carro.quantidadesPessoas += y; 
        
        return 'Já temos'+ ' '+ carro.quantidadesPessoas + ' '+ 'pessoas no carro !'


        }  else if (assentosSobrando <=5 && y > assentosSobrando){

            return 'Só cabem mais' + ' '  + assentosSobrando + ' ' + pessoas + '!'
        } else if 

            (assentosSobrando ===1 ) 
        
            return 'Só cabem mais' + ' ' + assentosSobrando + ' ' + pessoas + '!'
            
        }
    

    
carro.diminuirPessoas = function(z) {

    var pessoas = 'pessoas';
    carro.quantidadesPessoas -= z;

    if (carro.quantidadesPessoas === 1) { 
        pessoas = 'pessoa';
    }
console.log(pessoas)
    return 'Tem' + ' ' + carro.quantidadesPessoas + ' ' + pessoas + ' ' + 'no carro!'
}




```

@fdaciuk

**Comment by Gilmara-Git** [comment]
Novamente o trecho que estou dizendo ( Não ficou gravado acima) 

```if(carro.quantidadesPessoas === carro.assentos && totalPessoas >= carro.assentos) {
return "O carro já está lotado!"}```

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Na verdade não é esse trecho de código que faz a redução, e sim a chamada de `carro.adicionarPessoas`, passando um valor negativo para a função :)

Ao fazer isso, no momento de "somar" a quantidade de pessoas já no carro com a quantidade passada como argumento para a função, ao passar um valor negativo nós fazemos a subtração. É matemática básica, olha só:

```
10 + 2 // 12
10 + -2 // 8
```

Lembra nas aulas de matemática básica que, quando temos dois sinais de adição e/ou substração juntos, nós usamos a regra:
- dois sinais iguais (tanto de soma como de substração), nós efetuamos uma soma;
- com dois sinais diferentes (soma e subtração), nós efeturamos a subtração.

É essa regra que faz com que seja possível reduzir pessoas do carro sem mudar muito a lógica da nossa função :)

Ficou mais claro? :)

**Comment by Gilmara-Git** [comment]
Oi Fernando, 

Com a matemática básica entendi sim, ficou mais claro. 
É que eu não tinha pensado que se forçar mais uma validação faria diminuir pessoas. Agora acho que entendi melhor a validação abaixo.

Vou explicar com minhas palavras, me corrija se estiver incorreta, por favor.
Pimeiramente é verificado se o carro está CHEIO. E a segunda opção o código valida também se o totalPessoas (ou seja as pessoas dentro do carro  + as pessas que querem entrar no carro) é >=carro.assentos . 
Se as duas opções acontecerem, o código permite retirar, mas não adicionar pessoas. 
 
carro.quantidadesPessoas === carro.assentos && totalPessoas >= carro.assentos)


Obrigada, 
Abraços,
Gilmara

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! É quase isso! Vamos lá:

> Pimeiramente é verificado se o carro está CHEIO. E a segunda opção o código valida também se o totalPessoas (ou seja as pessoas dentro do carro + as pessas que querem entrar no carro) é >=carro.assentos .

Até aqui é isso mesmo :) 

> Se as duas opções acontecerem, o código permite retirar, mas não adicionar pessoas.
Não exatamente. Se as duas expressões forem verdadeiras (retornarem `true`), então o código dentro do bloco do `if` será executado, ou seja: se as duas expressões forem verdadeiras, o código para ali, já que temos um `return` com uma mensagem avisando que o carro já está cheio!

Se qualquer uma das expressões retornar `false`, então o bloco do `if` **não será executado**, e passamos para o próximo trecho do código, onde fazemos a verificação para garantir que não sejam adicionadas mais pessoas do que as que cabem ainda no carro :)

Passando por essas validações, se nenhum bloco `if` for executado, então nós chegamos na última etapa do nosso código, onde é feita a adição (ou remoção) de pessoas no carro:

```js
carro.quantidadePessoas += numeroPessoas;
```

É essa linha que adiciona ou remove pessoas do carro! 

Conseguiu pegar? :)

**Comment by Gilmara-Git** [comment]
Fernando, Desculpa a demora em responder. Estou fazendo um bootcamp em paralelo. 
Eu vou voltar neste desafio, olhar novamente if, por if para entender o passo a passo de sua explicação.
Assim, que fizer isso lhe dou um feedback. 
Muito obrigada
Gilmara

**Comment by fdaciuk** [comment]
Sem problemas @Gilmara-Git! Vou fechar a issue por enquanto, mas se você precisar de qualquer ajuda ainda sobre esse assunto, só comentar aqui que eu vou te ajudando, ok? :)
