### ISSUE TITLE
ajuda

### ISSUE THREAD

**Issue by jromarioss** [da2k/curso-javascript-ninja#9031]
me ajuda depois que eu fiz os exercícios, e vou para o próximo passo como no vídeo, não aparece a opção compare full request...

**Comment by fdaciuk** [comment]
OI @jromarioss! Se estiver com dificuldades nessa parte, não precisa fazer, ok? O importante é que você consiga resolver os desafios no seu computador mesmo!

Se quiser baixar todos os desafios de uma só vez, só acesse o link do repositório e clique no botão verde escrito "Code", como mostrado na imagem abaixo:

![Screenshot from 2020-10-28 15-03-54](https://user-images.githubusercontent.com/487669/97477919-fdab8b00-192e-11eb-9620-24494ff97e99.png)

---

Ao clicar nesse botão, você vai ver um link "Download ZIP". Clique nele para baixar todos os desafios :)

**Comment by fdaciuk** [comment]
Detalhe importante: sempre que abrir uma nova issue, me marque para que eu receba a notificação da sua pergunta, ok? 

Para me marcar, é só escrever `@fdaciuk` :)

**Comment by fdaciuk** [comment]
Oi @jromarioss! Vou fechar a issue, mas se você ainda tiver dúvidas, só comentar aqui que eu te ajudo, ok? :)
