### ISSUE TITLE
[Ajuda aula 2 desafio]

### ISSUE THREAD

**Issue by jromarioss** [da2k/curso-javascript-ninja#9038]
não consigo achar a opção do url  nao da certo....

**Comment by Olliv3r** [comment]
Ta falando da url que precisa clonar o repositório?

**Comment by Olliv3r** [comment]
eu precisei adicionar uma chave ssh pra  minha conta github, pra poder clonar o repositório por ssh.

**Comment by fdaciuk** [comment]
Oi @jromarioss! Te respondi na issue #9031 :)
