### ISSUE TITLE
[Duvidas de Pull Request]

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9049]
Oi Fernando, 

Uma pergunta sobre Pull request. 
A medida que termino um Challenge e assito a correção, eu faço aquele process de git add . , pelo branch referente ao Challenge, faço o commit e git push --set-upstream origin nomeBranch.

Acabei de fazer um push do desafio 06.

 A partir dai, eu to com dúvidas para realizar os Pull requests, pois ao tentar fazer um Pull request, estão mostrando mudanças em mais de um arquivo. 
Vou tentar mostrar com imagens para facilitar o entendimento:
![compaing_changes](https://user-images.githubusercontent.com/66445234/97734756-fc559c00-1aaf-11eb-9a45-74a6f8524475.png)
![branches_curso_javaScript_ninja](https://user-images.githubusercontent.com/66445234/97734759-fc559c00-1aaf-11eb-90af-3cd15b9fd20f.png)
![challenge06](https://user-images.githubusercontent.com/66445234/97735259-79811100-1ab0-11eb-88ea-02f119829ff4.png)
![challenge05](https://user-images.githubusercontent.com/66445234/97735260-79811100-1ab0-11eb-865a-9d86b9ceca73.png)
![challenge04](https://user-images.githubusercontent.com/66445234/97735263-79811100-1ab0-11eb-9834-5e72bc7c3d27.png)

Obrigada,
Gilmara

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Isso acontece pois você está criando a nova branch com base na branch onde um desafio já foi resolvido.

Por exemplo: a branch `master` é a branch que está "vazia", sem nenhum desafio resolvido.

À partir dela, você deve ter criado a branch `challenge-02`. Resolveu o desafio 2, fez o commit e o push.

Até aí tudo bem. O problema acontece na hora de criar a branch `challenge-03`: o correto seria **voltar para a branch master** e então criar a branch 3 à partir dela, que está sem desafios resolvidos.

Mas você deve estar criando a branch `challenge-03` à partir da `challenge-02`, que já tem o desafio resolvido.

Por isso aparecem mais arquivos modificados ao fazer o Pull Request contra a master, que não tem desafios resolvidos :)

Ficou claro? :)

**Comment by Gilmara-Git** [comment]
Oi Fernando, desculpa a demora em responder. 
Estou fazendo um bootcamp em paralelo e acabei ficando aguarrada em um Desafio do bootcamp. 
Era isso mesmo que eu estava fazendo, criando uma nova branch a partir da branch que eu estava em vez de voltar para a Master e criar a nova branch.
E agora, como faço para consertar ? Tem jeito ? 

Aguardo, 
Obrigada
Gilmara

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Tem algumas formas de ajustar, mas não precisa se preocupar em enviar os PRs, ok? Se quiser só resolver na sua máquina, sem enviar o PR, fique à vontade :)

Se ainda assim quiser resolver, me avise que eu te dou alguns caminhos :)
