### ISSUE TITLE
Como ativar ou gerar código html de um array

### ISSUE THREAD

**Issue by GleristonCastro** [da2k/curso-javascript-ninja#9063]
Olá amigos e professor Fernando!

eu estou gostando bastante do curso mas tenho uma dúvida, até o presente momento estamos apenas aprendendo como usar o console, mas eu tenho uma dúvida... tenho o seguinte array

```js

function tipoTelefone(){
    tipos = [
        {cp: 'Celular Pessoal'},
        {cc: 'Celular Comercial'},
        {fr: 'Fixo Residencial'},
        {fc: 'Fixo Comercial'},
        {ap: 'Apenas Whatsapp'}
    ];
    return tipos
}
console.log(tipoTelefone());
console.log(tipos[0].cp);
 
```

Ao invés de mostrar no console.log eu queria criar com os dados do array e seu objeto um select html

```html

<select name="tipoTelefones">
 <option value="**">**</option>
 <option value="**">**</option>
 <option value="**">**</option>
</select>

```
Só que não tenho a mínima ideia de como colocar os dados do array, só pensei que teremos que usar algum laço de repetição até os dados do array acabarem

onde tem ** do option value queria colocar o valor do índice, ou se tiverem alguma sugestão melhor fico grato.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @GleristonCastro! A ideia das primeiras aulas do curso é que você tenha um contato maior com a linguagem mesmo, então fazemos tudo ali, e quando precisamos visualizar algum valor, usamos apenas o `console` para ver o que está acontecendo :)

À patir da aula 15 eu começo a mostrar como lidar com a API DOM. Aí você via começar a ver exatamente isso que você precisa, pode ficar tranquilo :)

**Comment by GleristonCastro** [comment]
Há, ok obrigado! é que estava praticando e pensando como fazer! vou continuar com a sessão 6 agora! Obrigado Fernando!

**Comment by fdaciuk** [comment]
Sem problemas meu caro! Logo você vai chegar lá :D
E qualquer dúvida, fique à vontade para perguntar :D
