### ISSUE TITLE
[Sobre Pull Request]

### ISSUE THREAD

**Issue by vladimiremi** [da2k/curso-javascript-ninja#9068]
Olá professor Fernando! Gostaria de saber porque alguns dos meus Pull Request foram Closed. Seria alguma correção sua com relação ao meu desafio enviado? Se for, eu não consigo visualizar.

![image](https://user-images.githubusercontent.com/41305527/98111336-34c5f300-1e7f-11eb-8b4f-efeffba89c05.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @vladimiremi! Eu fecho os PRs apenas para organizar o repositório :)
Eu não corrijo mais manualmente os PRs, pois o curso todo já está gravado, e todas as soluções dos desafios estão sempre no início da próxima aula, você pode sempre acompanhar por lá :) 

Mas sempre que tiver dúvidas, pode abrir issue que eu vou te ajudando, ok? :)
