### ISSUE TITLE
Aula 21

### ISSUE THREAD

**Issue by baltazarparra** [da2k/curso-javascript-ninja#908]
Cara, sobre o projeto da aula 21,

Fiz de uma forma diferente do que foi mostrado na correção, e não entendi algumas decisões,
tipo, porque colocar a função fora do evento? e porque não usar um counter++ no value.

[Official Timer](https://gist.github.com/baltazarparra/6601f426e3b0a076cb136404360d56b3)

[Meu Timer](https://gist.github.com/baltazarparra/c48f1b980d820d8259f18bfbc3923934)

@fdaciuk

**Comment by fdaciuk** [comment]
Opa! Vamos lá =)

Sobre usar o `counter` e ir incrementando ele: não vejo problemas em fazer isso, **desde que** você mantenha o estado da sua aplicação bem definido. No exemplo que eu mostrei, nós usamos o valor do próprio input para incrementar. Isso faz com que o valor incrementado seja sempre baseado no valor anterior desse input.

Usando um estado separado (variável `counter`), se em algum outro lugar da sua aplicação essa variável for alterada, o timer não vai incrementar coretamente, causando o que chamamos de _side effect_, ou efeito colateral. Obviamente o exemplo é bastante simples, mas a ideia é já pensar nesses pontos com aplicações menores, que poderão ser aplicados facilmente em aplicações maiores.

O segundo ponto, sobre a função: perceba que você criou duas funções: 
- uma para o listener de evento;
- uma para ser usada no setTimeout.

Nesse caso, não há necessidade de deixar duas funções em memória, você consegue fazer a lógica apenas com uma.

Tem alguns outros pontos em questão de performance, que você verá nas próximas aulas. Mas nesse caso, você poderia usar a função diretamente no `addEventListener`, como fez no seu exemplo, e deixar ela nomeada, para chamar a mesma no `setTimeout`.

Ficou mais claro? =)

**Comment by baltazarparra** [comment]
@fdaciuk Perfeito, muito obrigado =]

**Comment by fdaciuk** [comment]
:+1:
