### ISSUE TITLE
[Aula 2] - Revisão do desafio 1 - Operador pós-incremento

### ISSUE THREAD

**Issue by willianribeiro** [da2k/curso-javascript-ninja#912]
@fdaciuk, fiquei com uma dúvida assistindo a revisão do desafio 1.

Você dá o seguinte exemplo:
```
1. var soma;
2. soma = 24;
3. soma = soma++;          // Após esta instrução a soma é igual a 24;
```

Pelo que eu entendi você explica o seguinte: Na linha 3 a variável `soma` é atribuída a própria variável `soma`.

Ok, isso porque é pós-incremento, faz muito sentido! Mas depois de fazer essa atribuição o JavaScript deveria fazer o incremento de +1 a variável `soma`, e ele não faz! .-.

Diferente do segundo exemplo que você dá, que são variáveis diferentes:

```
var um = 1;
var dois = um++;           // Após esta instrução um === 2 e dois === 1
```

Perceba que neste último exemplo o JavaScript faz o pós-incremento à variável `um` após a atribuição! Diferente do primeiro exemplo que não faz o pós-incremento à variável `soma`, é como se o pós-incremento fosse "perdido".

Não consegui entender o porquê do comportamento diferente nos dois exemplos ):

**Comment by fdaciuk** [comment]
Fala @willianribeiro! Bom, vamos lá. O que acontece é o seguinte:

O operador de atribuição tem prioridade baixa, ou seja: dentro da sentença em que o operador de atribuição existir, a atribuição será a última coisa a ser executada.

Então, a instrução à **direita** do operador `=` é executada primeiro, para só depois esse valor de resultado ser atribuído à variável.

O que acontece com o operador `++` é que ele tem o que chamamos de _side effect_, ou **efeito colateral**. Ele, além de somar `1` no valor atual, ele ainda atribui o valor á variável utilizada.

No caso do exemplo:

```js
var soma;
soma = 24;
soma = soma++;
soma; // 24
```

O valor de soma continua sendo `24`, pois o operador `++` atua **primeiro no valor** da variável, e só então faz (ou tenta fazer) a atribuição.

Nesse caso, como o operador é de **pós-incremento** (chamado depois da variável), antes de incrementar a variável `soma`, ele vai permitir a atribuição. Então, antes de qualquer coisa, é feito `soma = soma`.

Após essa primeira atribuição, é que o operador de **pós-incremento** vai agir. Ele incrementa o valor de `soma`, mas não consegue atribuir, pois uma atribuição já foi feita, e ele já perdeu a referência daquela variável anterior, causando esse "bug".

Como o valor incrementado não é atribuído a ninguém, você não consegue acessá-lo de nenhuma forma.

Deu pra entender melhor? =)

Você ainda verá alguns outros exemplos para esses casos de efeitos colaterais mais pra frente, e acredito que tudo vai ficar mais claro =)

**Comment by willianribeiro** [comment]
Hmmmmm entendi! Caramba, muito interessante isso. 

Obrigado pelo esclarecimento, abração!
