### ISSUE TITLE
Clonar seu próprio projeto em uma máquina diferente

### ISSUE THREAD

**Issue by ValdirCezar** [da2k/curso-javascript-ninja#9169]
Olá, pessoal!

Estou iniciando os estudo com Git e GitHub e tenho uma dúvida que não consegui encontrar na documentação ou em fóruns.

1 -> Eu tenho 2 computadores, o pessoal e o de trabalho.
2 -> Iniciei um projeto no GitHub  com a máquina pessoal usando GitBash.
3 -> Na máquina de trabalho eu baixei o projeto que criei no GitHub usando a outra máquina.
4 -> Fiz algumas alterações no projeto e quero atualizar no GitHub .

Resumindo: Eu quero baixar meu próprio projeto do GitHub em outra máquina e salvar a atualização realizada.

Podem me ajudar?
vlw!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ValdirCezar! Vi que você fechou a issue.. conseguiu resolver?
