### ISSUE TITLE
[Dúvida] 

### ISSUE THREAD

**Issue by raqcalazans** [da2k/curso-javascript-ninja#9201]
Olá! Estou tendo um problema com meus pull requests, os challenges estão indo todos juntos e não somente o challenge que eu commitei. Você pode me ajudar, por favor?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @raqcalazans! Dá uma olhada [nessa resposta aqui](https://github.com/da2k/curso-javascript-ninja/issues/9049#issuecomment-719713063) que eu expliquei porque isso acontece :)

Se ainda tiver dúvidas, só comentar aqui que eu vou te ajudando, beleza? :)

**Comment by fdaciuk** [comment]
Oi @raqcalazans! Vou fechar a issue, mas se você ainda tiver qualquer dúvida com relação a esse assunto, só comentar aqui que vou te ajudando, beleza? :)
