### ISSUE TITLE
[Dúvida]

### ISSUE THREAD

**Issue by Carecsnay** [da2k/curso-javascript-ninja#9235]
### O que pode ser @fdaciuk ?

```js
    carro.addPessoas = function( numPessoas ) {
        var totPessoas = carro.quantidadePessoas + numPessoas
        if ( carro.quantidadePessoas === carro.assentos ) {
            return 'O carro já está lotado!';
        }

        if ( totPessoas > carro.assentos ) {
            var pessoasRestantes = carro.assentos - carro.quantidadePessoas
            var pluralOuSingular = pessoasRestantes === 1 ? ' pessoa' : ' pessoas';
            return 'Só cabem mais '  + pessoasRestantes + pluralOuSingular + ' no carro!';
        }

        carro.quantidadePessoas += numPessoas;
        return 'Já temos ' + totPessoas + pluralOuSingular + ' no carro!'
        };
    carro.quantidadePessoas = 0 //zerar o valor primeiro
    carro.addPessoas(1); //fazer os testes
```

**Comment by Carecsnay** [comment]
Desafio 04 
/*
Crie um método que irá adicionar pessoas no carro. Esse método terá as
seguintes características:
- Ele deverá receber por parâmetro o número de pessoas entrarão no carro. Esse
número não precisa encher o carro, você poderá acrescentar as pessoas aos
poucos.
- O método deve retornar a frase: "Já temos [X] pessoas no carro!"
- Se o carro já estiver cheio, com todos os assentos já preenchidos, o método
deve retornar a frase: "O carro já está lotado!"
- Se ainda houverem lugares no carro, mas a quantidade de pessoas passadas por
parâmetro for ultrapassar o limite de assentos do carro, então você deve
mostrar quantos assentos ainda podem ser ocupados, com a frase:
"Só cabem mais [QUANTIDADE_DE_PESSOAS_QUE_CABEM] pessoas!"
- Se couber somente mais uma pessoa, mostrar a palavra "pessoa" no retorno
citado acima, no lugar de "pessoas".
*/
✔
    carro.addPessoas = function( numPessoas ) {
        var totPessoas = carro.quantidadePessoas + numPessoas
        if ( carro.quantidadePessoas === carro.assentos ) {
            return 'O carro já está lotado!';
        }

        if ( totPessoas > carro.assentos ) {
            var pessoasRestantes = carro.assentos - carro.quantidadePessoas
            var pluralOuSingular = pessoasRestantes === 1 ? ' pessoa' : ' pessoas';
            return 'Só cabem mais '  + pessoasRestantes + pluralOuSingular + ' no carro!';
        }

        carro.quantidadePessoas += numPessoas;
        return 'Já temos ' + totPessoas + pluralOuSingular + ' no carro!'
        };
    carro.quantidadePessoas = 0 //zerar o valor primeiro
    carro.addPessoas(1); //fazer os testes

**Comment by fdaciuk** [comment]
Oi @Carecsnay! O problema é que você está criando a variável dentro do `if`. Se, ao executar a função, não passar naquele `if`, a variável não vai ser criada, e ela vai ter o valor `undefined` :)

**Comment by Carecsnay** [comment]
Resolvido!! 

Muuuuito obg :)

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)

**Comment by Carecsnay** [comment]
![image](https://user-images.githubusercontent.com/53373326/102720092-ea82bf00-42d0-11eb-9029-0306d391d343.png)
```
var pluralOuSingularA = pessoasRestantes === 1 ? ' cabe' : ' cabem';

```

fiz um bônus professor, para ter na palavra cabe/cabem

**Comment by fdaciuk** [comment]
Muito bom 👏🏾 👏🏾
