### ISSUE TITLE
Não sei usar o git hub!

### ISSUE THREAD

**Issue by humb-farias** [da2k/curso-javascript-ninja#9253]
Oi cara, td certinho?
mano eu de verdade não entendi como fazer pra conectar (eu acho q se fala assim) o meu node.js com o navegador. não sei puxar um desafio do Github direto do meu console no Node.js. Eu tô na semana 7 e até agora tô fazendo todos os meus estudos e exercícios usando o console do meu navegador (Opera). Tô preocupado que mais pra frente isso vá me impedir de progredir no curso. 

Acho que o que eu não entendi é como atualizar meu repositório. Assuntos da aula #6, #7 e #13.
C pode me ajudar?!

Vlw cara abração!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @humb-farias! Não se preocupe com isso! Git não é um requisito do curso, por isso eu mostro por cima o básico, apenas pra você conseguir tentar enviar os Pull Requests, mas **não é obrigatório** :) 

Só resolvendo os desafios no console do seu navegador (ou pelo node.js) já está ótimo, você vai conseguir seguir assim sem problemas :)

Se mais pra frente você perceber que está te fazendo falta, aí sim você pode estudar Git e GitHub, mas nada obrigatório por agora :)

É um aprendizado importante? Com certeza! Mas estude sem pressa: foque no JS primeiro, depois você pode estudar Git e GitHub, ok?

E sempre que tiver qualquer dificuldade, não hesite em perguntar: estou aqui pra te ajudar :)

**Comment by humb-farias** [comment]
Massa então mano :))
brigadão e feliz natal!

**Comment by fdaciuk** [comment]
Nada! Conte comigo para o que precisar! Feliz natal, boas festas :D
