### ISSUE TITLE
Não consigo entender meu codigo!

### ISSUE THREAD

**Issue by RickShimizu** [da2k/curso-javascript-ninja#9322]
```js
 function book(nomeDoLivro) {

            var shelf = {

                'POKEMONZUKAN': {
                    quantiaDePag: 300,
                    autor: 'SATOSHI-TAJIRI',
                    editora: 'TOUEI'
                },

                'DIGIMONZUKAN': {
                    quantiaDePag: 400,
                    autor: 'AKI-YOSHI-HONGO',
                    editora: 'TOUEI'
                },

                'RAGNAROK': {
                    quantiaDePag: 100,
                    autor: 'Lee Myung-Jin',
                    editora: 'TOUEI'
                }

            }
            if (nomeDoLivro) {
                return shelf[nomeDoLivro];
            } else {
                return shelf;
            }

        }
```

bem.. minha duvida é a seguine.. como eu declarei uma:

```js
function book(nomeDoLivro){

}
```

o correto de eu digitar no console do chrome seria "book(nomeDoLivro);" e assim ele filtrar pelo parâmetro
mas acontece que não está acontecendo isso, quando coloco "book(nomeDoLivro);" no console ele me retorna um

 ERRO: VM2598:1 Uncaught ReferenceError: RAGNAROK is not defined
 at <anonymous>:1:6

Porém quando coloco o comando "book().nomeDoLivro" ele simplesmente funciona   / c ¬ .¬ \  .
o correto da sintaxe não seria "book(nomeDoLivro).algumAtributo" ou  simplesmente book(nomeDoLivro)?
se alguém poder me explicar agradeço muito! GRATO!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RickShimizu! Vamos lá :)

Veja o que o erro diz: 

```
Uncaught ReferenceError: RAGNAROK is not defined
```

Veja que o erro diz que `RAGNOROK` não foi definido, certo? Por que isso acontece? Esse erro acontece quando tentamos usar um nome de variável que ainda não foi definido. Digite no seu console:

```
RAGNAROK
```

E você vai ver o mesmo erro :)

Logo, isso significa que, quando você está chamando a função `book`, e passando o argumento `RAGNAROK`, ao invés de passar esse argumento como uma string (envolvido por aspas), você está passando só o nome sem as aspas. Dessa forma, o JS vai entender que você está tentando fazer referência a algum nome de variável chamada `RAGNAROK`, que na verdade não existe :)

Se você usar `book('RAGNAROK')` (perceba as aspas ao redor de `RAGNAROK`) vai funcionar como esperado!

---

Sobre sua outra dúvida: _por que então chamando `book().RAGNAROK` funciona?_

Veja o a lógica de retorno da sua função `book`:

```js
if (nomeDoLivro) {
    return shelf[nomeDoLivro];
} else {
    return shelf;
}
```

Ou seja: se o argumento `nomeDoLivro` foi passado, você vai retornar a propriedade do objeto `shelf` que tem o nome passado via argumento.

Caso contrário, você retorna o objeto todo!

E no objeto, você tem as 3 propriedades que são os nomes dos livros: `POKEMONZUKAN`, `DIGIMONZUKAN` e  `RAGNAROK`.

Então, se você chamar a função `book()` sem argumentos, ela vai te retornar um objeto. Como esse objeto têm propriedades que podem ser acessadas com a sintaxe de ponto, já que os nomes das propriedades têm caracteres válidos pra isso, você consegue usar esse formato para pegar qualquer um dos livros que a função vai retornar!

```js
book().POKEMONZUKAN;
book().DIGIMONZUKAN;
book().RAGNAROK;
```

Os 3 irão funcionar corretamente :)

Deu pra entender agora o que está acontecendo?

**Comment by RickShimizu** [comment]
entendi perfeitamente muito obrigado pela explicação!

**Comment by fdaciuk** [comment]
Nada! Qualquer dúvida, só avisar :)
