### ISSUE TITLE
Problema de interpretação - challenger 06

### ISSUE THREAD

**Issue by RickShimizu** [da2k/curso-javascript-ninja#9324]
Bom dia!, gostaria de entender melhor o anunciado será que poderia me explicar pfv?, me desculpe qualquer coisa o anunciado é o seguinte: 

"Escolha 4 times do campeonato selecionado e mostre a posição dele, usando a
função acima. Entre esses 4, adicione 1 que não esteja entre os 5 primeiros.

No meu caso os 5 times que escolhi são os seguintes:
são paulo, palmeiras, corinthians, quarani.

no anunciado está como "Escolha 4 times do campeonato selecionado e mostre a posição dele", acredito que seria "deles" neste caso tudo esta o conforme.. 
o problema começa na parte " Entre esses 4, adicione 1 que não esteja entre os 5 primeiros.", esse "5 primeiros"
são os 5 times que escolhi certo?, se for o caso eu preciso adicionar 1 time que não esteja no meu array de 5 "slot" ? é isso?
 

@fdaciuk

**Comment by RickShimizu** [comment]
olha, me desculpe se estou sendo chato por corrigir o enunciado mas, me considero muito burro, por isso necessito ler varias vezes o enunciado, ent acabo sendo mt dependente o enunciado. agradeço desde já.

**Comment by fdaciuk** [comment]
Oi @RickShimizu! Não precisa se desculpar por nada não! Pergunte sempre que tiver dúvidas :D 

Vamos lá :)

> o problema começa na parte " Entre esses 4, adicione 1 que não esteja entre os 5 primeiros.", esse "5 primeiros"
são os 5 times que escolhi certo?, se for o caso eu preciso adicionar 1 time que não esteja no meu array de 5 "slot" ? é isso?

A ideia do exercício é usar a função que você criou à partir do enunciado anterior. Essa função vai receber via argumento uma posição à partir de um número, e vai retornar o time que está nessa posição passada, certo?

O que você precisa fazer é escolher 4 posições diferentes: 3 deles serão de qualquer um dos 5 times que você selecionou, e uma delas será uma posição que não vai bater com nenhum time do array, para que seja exibida a mensagem de que "Não temos a informação do time que está nessa posição."

Ficou mais claro? :)

**Comment by RickShimizu** [comment]
okay, agora entendi! mt obrigado !

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :)
