### ISSUE TITLE
Dúvida GIT - mesclar commits

### ISSUE THREAD

**Issue by diegosfc100** [da2k/curso-javascript-ninja#9329]
Fala Fernando, blz ? Cara, já estou no 4desafio e gostando muito do curso, sei que não necessário mais fazer pullrequest deles, mas ando mexendo bastante no git pra ir pegando as manhas, ouvi dizer que tem como mesclar commits feitos no passado fazendo com que se tornem apenas um, queria fazer isso com alguns commits meus mas não estou conseguindo, pesquisei e vi que isso é feito pelo comando git rebase, mas não estou conseguindo selecionar os commits certos para mesclar. Consegue me ajudar nessa parte ?
Valeeu

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @diegosfc100! Legal que está curtindo o curso :)

Sobre o git, não recomendo você fazer rebase se não souber exatamente o que está fazendo, pois você pode perder informações importantes, já que o rebase modifica o histórico original do git.

Se ainda assim quiser fazer, é até bem simples, só que você precisa fazer todos os passos até o fim, ou abortar se decidir não fazer mais o rebase, ok? Vou mostrar os comandos logo abaixo :)

A primeira coisa a se fazer é descobrir quais commits você quer "juntar" em um único. Para isso, você precisa rodar:

```
git log
```

Que vai te trazer uma lista de commits. Veja que cada commit tem uma hash (o identificador gigante ao lado da palavra `commit`, na primeira linha do commit).

Você precisa primeiro selecionar essa hash do commit logo antes de onde você quer começar a juntar. Exemplo: tenho um arquivo `file.txt`, que tem 4 linhas, cada linha com um número. Para cada linha adicionada, foi feito um novo commit. O resultado do `git log` seria algo assim:

```gitattributes
commit bdfbc25c387a906c9ce081010bd81a78f09329a4 (HEAD -> main)
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:59:48 2021 -0300

    4

commit 3de52d30f49eece98a3924b7f8d919b9b2ef9ad2
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:59:36 2021 -0300

    3

commit ad475a861c5ee36d381e87850de396f8c0d92cd4
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:59:28 2021 -0300

    2

commit f4005f3e16942c5fa6688805880574ec9639ffa0
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:59:20 2021 -0300

    1

commit a75dff6d0e26cb5b1fe68f7cc99793d615be2eb2
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:58:04 2021 -0300

    Create file
```

Se eu quiser juntar os commits que estão numerados de 1 a 4, eu tenho que selecionar a hash do commit anterior (no caso, a hash do commit `Create file`, que foi o primeiro commit). A hash é `a75dff6d0e26cb5b1fe68f7cc99793d615be2eb2`.

Então eu executo o comando abaixo, passando como último argumento essa hash:

```
git rebase -i a75dff6d0e26cb5b1fe68f7cc99793d615be2eb2
```

Ao fazer isso, você vai ver a lista de commits para editar, e nessa lista, as instruções do que você precisa fazer:

```gitattributes
pick f4005f3 1
pick ad475a8 2
pick 3de52d3 3
pick bdfbc25 4

# Rebase a75dff6..bdfbc25 onto a75dff6 (4 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
```

Como eu quero juntar todos os commits (1, 2, 3, 4) no commit 1, eu vou deixar a primeira linha como `pick` (mensagem de commit que vai se manter) e as outras linhas (2, 3 e 4) vou trocar o `pick` por `squash`:

```gitattributes
pick f4005f3 1
squash ad475a8 2
squash 3de52d3 3
squash bdfbc25 4
```

Quando você salvar, vai ser pedido uma mensagem para esse commit que vai ficar, A sugestão que o `git` te dá é para deixar as mensagens de todos os commits anteriores, mas as mensagens serão unidas em um único commit:

```gitattributes
# This is a combination of 4 commits.
# This is the 1st commit message:

1

# This is the commit message #2:

2

# This is the commit message #3:

3

# This is the commit message #4:

4

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Fri Feb 5 19:59:20 2021 -0300
#
# interactive rebase in progress; onto a75dff6
# Last commands done (4 commands done):
#    squash 3de52d3 3
#    squash bdfbc25 4
# No commands remaining.
# You are currently rebasing branch 'main' on 'a75dff6'.
#
# Changes to be committed:
#	modified:   file.txt
#
```

 Você pode apagar e escrever o que quiser:

```gitattributes
# This is a combination of 4 commits.
# This is the 1st commit message:

NOVA MENSAGEM DE COMMIT

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Fri Feb 5 19:59:20 2021 -0300
#
# interactive rebase in progress; onto a75dff6
# Last commands done (4 commands done):
#    squash 3de52d3 3
#    squash bdfbc25 4
# No commands remaining.
# You are currently rebasing branch 'main' on 'a75dff6'.
#
# Changes to be committed:
#	modified:   file.txt
#
```

Pronto! Agora os commits 1, 2, 3 e 4 estarão unidos. Ao rodar `git log` você vai ver apenas o primeiro commit, e esse último com a nova mensagem:

```gitattributes
commit c33d52c08dc19cd05846adb0721ab1ca35a1063f (HEAD -> main)
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:59:20 2021 -0300

    NOVA MENSAGEM DE COMMIT

commit a75dff6d0e26cb5b1fe68f7cc99793d615be2eb2
Author: Fernando Daciuk <email@gmail.com>
Date:   Fri Feb 5 19:58:04 2021 -0300

    Create file
```

## Mas reiteirando: tome cuidado pois esse comando é destrutivo, e você NÃO PODERÁ voltar atrás, ok?

Espero que ajude :)

**Comment by diegosfc100** [comment]
Então, entendi sua explicação, porém a minha dúvida é a seguinte, os commits que eu quero mesclar foram feitos há alguns dias, então existem commits antes e depois deles, eu não estou conseguindo selecionar esse intervalo, quando eu coloco o hash do commits anterior ao último que eu quero mesclar, ele me mostra desse último até o mais recente que eu comitei hoje.

**Comment by fdaciuk** [comment]
Certo, o que você quer fazer então é um `cherry-pick`. É um pouco mais chatinho de se fazer, mas você consegue selecionar commits específicos e colocar em uma branch separada para trabalhar com eles. Depois de fazer o cherry-pick, você pode fazer o stash para juntar os commits que vão estar mais próximos :)

**Comment by diegosfc100** [comment]
Valeu Prof, irei tentar fazer desse jeito, Obrigado

**Comment by fdaciuk** [comment]
Show :)
Qualquer dúvida, só avisar :)
