### ISSUE TITLE
Dúvida no uso de Module Pattern

### ISSUE THREAD

**Issue by rafamaxber** [da2k/curso-javascript-ninja#933]
Fala @fdaciuk , então, eu finalmente cheguei ao desafio 31 só que acabei fazendo o desafio utilizando prototype assim:
```javascript
  function app() {
    function Catalog() {
      this.vehicleList = [];
    };
    Catalog.prototype.addVehicle = function( item ) {
      return this.vehicleList.push( item );
    };
    //[...]
   var catalog = new Catalog();
}
app();
```

E na resolução você seguiu com Revelling Module Pattern, e como sigo seu blog e já seguia antes mesmo de fazer o curso comecei a estudar e usar um esquema bem parecido(igual) com o que você ensina  [nesse post](http://blog.da2k.com.br/2015/02/13/escalando-javascript-no-browser/), mas preferi fazer utilizando prototype porque eu queria treinar mesmo, pois aprendi realmente a utilizar em seu curso :smile: mas ai me ocorreu essa duvida de quando utilizar um forma ou outra...a conclusão que cheguei é que para bibliotecas onde praticamente todos os métodos serão reutilizados como na lib DOM que fizemos no curso é legal utilizar com prototype já para projetos e sistemas maiores é melhor utilizar a abordagem do que você fez em seu post...correto ??
- A forma como fiz o exercício mostrado acima esta no caminho certo ?

E desde já muito obrigado, o curso é incrível.
Abraços.

**Comment by fdaciuk** [comment]
Fala @rafamaxber! Primeiramente, obrigado pelo feedback, e me deixa muito feliz em saber que o curso está te ajudando :dancer: :dancer: :sparkles: 

Com relação a sua dúvida: o caminho é mais ou menos esse mesmo =)

Tipo, são tipos de arquiteturas que você pode usar na sua aplicação. Usar orientação a objetos com prototype faz mais sentido se você vai fazer uma lib, para que ela possa ser extendida no futuro, tipo o jQuery.

Você cria a lib básica, e permite a criação de plugins, que extendem a funcionalidade da lib usando o prototype.

Mas para criar aplicações, você também pode usar, se achar que isso fará sentido pra você, ou apenas para treinar, como fez no seu exemplo xD

Com o prototype ou RMP, você segue um formato mais orientado a objetos. Mas você também pode criar uma estrutura mais "funcional", baseado somente em funções, composição, etc.

O JS é multiparadigma, e ter essa liberdade de escolha é bem interessante, desde que você saiba o resultado do que está fazendo =)

Resumindo: não tem certo ou errado. Se você achar que faz sentido instanciar objetos, usando prototype, faça isso. Se achar mais legível usar revealing module pattern, use-o.

Esse é o momento de experimentar mesmo ;D

Espero ter respondido sua dúvida! 

Qualquer coisa grita ae =)

**Comment by rafamaxber** [comment]
obrigadão :+1:
