### ISSUE TITLE
[Aula 24] Remover zero à esquerda.

### ISSUE THREAD

**Issue by uitalorss** [da2k/curso-javascript-ninja#9346]
Fernando, boa noite.

Gostaria de tirar uma dúvida, consegui finalizar os exercícios da calculadora das aulas 23 e 24, porém queria tirar a dúvida de como remover o zero à esquerda após começar a digitação dos números. Já tentei algumas alternativas e não consegui.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @UitalloRss! É bem simples na verdade: pense nos eventos sempre como uma "intenção", e não a ação de fato.
Vou explicar melhor: quando você adiciona um listener de evento do tipo `input` em um campo de texto, por exemplo, cada tecla que você pressiona ainda não está adicionando o valor no campo de texto.

Ao pressionar o tecla, o evento é disparado, e dentro da função que é listener do evento, você pode fazer as verificações necessárias antes de, de fato, adicionar o valor no campo.

Levando isso em consideração, o que você tem que fazer é: quando uma tecla for pressionada, antes de atualizar o valor do campo, você verifica se o primeiro caractere do campo, recebido através do evento, é igual a zero. 

Se for, você simplesmente ignora o primeiro caractere e atribui ao campo todo o restante do valor. Tem várias formas de se fazer isso que já vimos no curso. Vou deixar duas dicas aqui pra você tentar resolver: `slice` ou `replace`, já que o valor de um campo de texto é sempre uma _string_ :)

Deu pra entender a ideia? Tentei explicar sem mostrar exemplos pra não dar a solução por aqui e deixar você tentar resolver sozinho :)

Mas se ainda assim você tentar e não conseguir resolver, me chama aqui de novo que eu mostro um exemplo prático de como fazer, ok? :)

**Comment by uitalorss** [comment]
Boa noite, Fernando. Vou implementar o que você falou e comento aqui, caso consiga ou não.

Muito Obrigado pelo retorno.

**Comment by fdaciuk** [comment]
Perfeito meu caro! Fico aguardando sua resposta :)

**Comment by UitalloRss** [comment]
Boa noite Fernando, desculpe a demora, acabei adoecendo e só agora pude resolver essa issue.

Eu tentei com o slice, no console eu conseguia remover, mas ao exibir no input saía normal. 
Acabei conseguindo com o código abaixo.

`  function handleClick(){
    if($telaCalculadora.value[0] === '0'){
        $telaCalculadora.value = '';
    }
    $telaCalculadora.value += this.value;
  }
`

Aceito dicas de como remover usando slice e o replace, porque realmente quebrei a cabeça e não consegui. :D

**Comment by UitalloRss** [comment]
Boa noite Fernando, desculpe a demora, acabei adoecendo e só agora pude resolver essa issue.

Eu tentei com o slice, no console eu conseguia remover, mas ao exibir no input saía normal.
Acabei conseguindo com o código abaixo.
`
  function handleClick(){
    if($telaCalculadora.value[0] === '0'){
        $telaCalculadora.value = '';
    }
    $telaCalculadora.value += this.value;
  }
`

Aceito dicas de como remover usando slice e o replace, porque realmente quebrei a cabeça e não consegui. 🗡️

**Comment by uitalorss** [comment]
Boa noite Fernando, desculpe a demora, acabei adoecendo e só agora pude resolver essa issue.

Eu tentei com o slice, no console eu conseguia remover, mas ao exibir no input saía normal.
Acabei conseguindo com o código abaixo.
`function handleClick(){
if($telaCalculadora.value[0] === '0'){
$telaCalculadora.value = '';
}
$telaCalculadora.value += this.value;
}`
Aceito dicas de como remover usando slice e o replace, porque realmente quebrei a cabeça e não consegui. :)

**Comment by fdaciuk** [comment]
Oi @UitalloRss! Da forma  que você fez vai funcionar tranquilamente, pode seguir assim sem problemas :)

A única coisa que eu trocaria seria o `this`, já que ele é muito volátil no JS. Use o objeto de evento que você recebe no seu listener para pegar o valor do campo:

```js
function handleClick (e) {
  // substitua o this.value por e.target.value :)
}
```

Usar o `slice` ou `replace` seria apenas uma variação do que você já conseguiu fazer. Na verdade, seria um pouco mais complexo, porque o exemplo da calculadora usa botões para definir os valores do campo. Quando eu te respondi, eu acabei levando em consideração a edição direto no input, então pode ignorar e seguir com a sua versão que vai rolar bem :)

**Comment by uitalorss** [comment]
Vou testar aqui. Muito obrigado pela atenção. 

Vou abrir outra issue porque deu outro problema em outro challenge. kkk

**Comment by fdaciuk** [comment]
hahah! Massa :)
