### ISSUE TITLE
Dúvida em Trusty e False

### ISSUE THREAD

**Issue by grodrigues** [da2k/curso-javascript-ninja#935]
@fdaciuk  Gostaria de mais exemplo sobre trusty e Fals

**Comment by fdaciuk** [comment]
Qual foi a sua dúvida com relação a esse assunto @grodrigues?

**Comment by grodrigues** [comment]
Em qual situação, eu vou utilizar Truthy e Falsy ?

**Comment by fdaciuk** [comment]
Em muitas! Nas próximas aulas nós vamos ver vários exemplos onde isso é útil. Um exemplo bem claro do uso de _truthy_ ou _falsy_, é quando você quer verificar se uma variável tem algum valor por exemplo:

```js
var someValue = null;

if (someValue) {
 // faça algo
}
```

No exemplo acima, eu usei a estrutura condicional `if`, que transforma o resutado da expressão passada pra ele em um valor booleano (`true` ou `false`).

No caso, eu não precisaria verificar se o valor da variável é diferente de `null`, ou `undefined`, ou ainda uma string em branco. Somente passando o nome da variável, o seu valor será convertido no correspondente booleano (se já não for um booleano). No caso, como `null` é um valor do tipo _falsy_, ou seja, convertendo-o para booleano ele será `false`, o código dentro do `if` não será executado =)

Nós vamos ver muito sobre isso no decorrer do curso, não se preocupe. Só tenha a certeza que entendeu bem o conceito =)

Ficou claro?

**Comment by grodrigues** [comment]
é forma de testar algo que não seja boleano em uma expressão Boleana ?

**Comment by grodrigues** [comment]
Mas entende sim

**Comment by grodrigues** [comment]
Se eu soubesse disso antes...

**Comment by fdaciuk** [comment]
É isso =)
_truthy_ são valores que, ao se converter para o seu equivalente booleano, retornam `true`. E _falsy_, é o contrário: retornam `false`. =)

**Comment by grodrigues** [comment]
Valeu Daciuk

**Comment by fdaciuk** [comment]
:+1:
