### ISSUE TITLE
Os desafios ainda são corrigidos?

### ISSUE THREAD

**Issue by quirogadev** [da2k/curso-javascript-ninja#9394]
Comecei o curso essa semana, não sei se ainda tá rolando correção e tal, já que o curso é finalizado. Outra dúvida, comprei também o curso git e github ninja, posso fazer ao mesmo tempo ou é melhor terminar o javascript primeiro?
Aproveitando o espaço, qual fonte o Daciuk usa no editor? kkk

**Comment by pauloteixeira01** [comment]
Cara! Eu recomendo que você faça o curso de git e github primeiro.  Quanto ao editor, recomendo o uso do VSCODE.

**Comment by fdaciuk** [comment]
Oi @quirogadev! Desculpe a demora, não recebi a notificação da sua dúvida :)
Sempre que abrir issue aqui, pode me marcar com `@fdaciuk`, que eu recebo a notificação pra te responder, ok? :)

Mas pode seguir a dica do @pauloteixeira01: comece pelo curso de Git e GitHub, que é menor, depois pode seguir com o curso de JS :)

Não estou mais corrigindo os desafios pois sempre no início da próxima aula já está gravada a correção do desafio da aula anterior, ok? Mas sempre que tiver dúvidas, fique muito à vontade para perguntar, estou aqui pra te ajudar no que for preciso :)

Sobre a fonte, provavelmente eu estava usando a `Consolas`. Hoje eu uso a `Cascadia` :)
