### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by uitalorss** [da2k/curso-javascript-ninja#9411]
Fernando, boa noite.

Eu tenho uma dúvida com relação ao IIFE. Com o Ecmascript 6 e a chegada das declarações let e const, Ainda tem utilidade envolver todo o código em uma IIFE, visto que se torna melhor o uso no escopo local e global com as novas declarações?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @UitalloRss! Na verdade, a entrada das novas formas de declarar variáveis (com `let` e `const`) não afetam o escopo geral da aplicação. Se você criar uma variável com `let` ou `const` no escopo global, essas variáveis continuam sendo globais, assim como se estivesse declarando com `var`.

`let` e `const` apenas adicionam escopo de bloco para as declarações (e não fazem hoisting como o `var`): se você dceclarar variáveis dentro de blocos `if`, `for` ou `while`, por exemplo, essas variáveis só vão existir dentro desses blocos. Se elas forem declaradas dentro de uma função, mas fora de um bloco, o escopo das variáveis é de função. E se a declaração for feita fora de qualquer função, no escopo global, então as variáveis poderão ser acessadas de qualquer lugar da aplicação, globamente :)

O que muda o uso da IIFE é apenas os ES Modules: usando ES Modules, cada arquivo `.js` se torna um módulo, e cada módulo tem apenas escopo local, nada "vaza" para o escopo global. E módulos sempre serão estritos por padrão (sem a necessidade de usar `'use strict'` no início do arquivo, pois isso já está implícito em um módulo).

Aí sim você não precisa de IIFE :)

Hoje em dia, ainda não são todos os navegadores que dão suporte à ES Modules, então é importante sim continuar usando IIFE ao usar JS puro no frontend :)
