### ISSUE TITLE
Dificuldade com o Git

### ISSUE THREAD

**Issue by marcelzanatta** [da2k/curso-javascript-ninja#9444]
Olá, eu comprei o curso faz tempão, tentar fazer mas não consegui por dificuldade com o git, agora que estou tentando novamente ainda não consegui trabalhar com terminal do git, então fui fazendo tudo via web, mas agora que estou no challenge-05, complicou mais ainda!!! Preciso de um suporte, as coisas não parecem clara, pra começar que terminal é esse que você utiliza? 

Do Node.js ou do git CMD? 
![image](https://user-images.githubusercontent.com/35149853/114241563-b86c9a00-995f-11eb-9631-fce923cc28aa.png)

O meu terminar do Node.js nao exibe nada, pq
![image](https://user-images.githubusercontent.com/35149853/114241750-1600e680-9960-11eb-9bdc-8798ef42131a.png)

Voltei para a aula 2 e tentei refazer tudo com o git, mas não consifgo clonar o repositorio via SSH deu esse erro ( mas utilizei o Git CMD ), nem sei se esse é o software!!
![image](https://user-images.githubusercontent.com/35149853/114241893-5496a100-9960-11eb-9df0-a619e648e6ca.png)

Eu estou animado com o curso,  e dessa vez preciso ir até o final. Preciso de ajuda por favor!!

Att,

Marcel

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marcelzanatta! O terminal que eu uso é do Linux. No windows, você pode ter um terminal com as mesmas características instalando o WSL2 :)

Mas não precisa se preocupar tanto com isso, tem maneiras mais fáceis de resolver seu problema. Vou te ajudar com isso, vamos lá!

Primeiro, não se preda ao git. Você pode baixar o repositório todo do curso como um `.zip` e simplesmente descompactá-lo na sua máquina para fazer os desafios.

Não precisa também mandar os pull requests, só resolvendo na sua máquina já está suficiente. O importante é praticar!

Para baixar como zip, você só precisar acessar a página do repositório [nesse link](https://github.com/da2k/curso-javascript-ninja), clicar no botão verde "Code" e clicar em "Download ZIP". Pronto!

Para usar o terminal, você pode usar o editor VS Code, que já vem com um terminal embutido, que você pode rodar comandos como eu mostrei nas aulas. 

Não tem segredo, mas se você tiver qualquer dificuldade, fique à vontade para entrar em contato que eu vou te ajudando, beleza? :)

**Comment by marcelzanatta** [comment]
Fernando!! Muito obrigado, estou usando os VScode e fazendo os 'pullrequest' via web rss!! Eu nem espera um retorno seu tão rápido, muito obrigado, assim foi possível continuar os estudos no fds.

Abraço

**Comment by fdaciuk** [comment]
Ah, show! Qualquer dúvida, fique à vontade para perguntar :)
Estou sempre de olho aqui nas issues e nas perguntas lá na Udemy :)
