### ISSUE TITLE
[Aula 4] Desafio 4

### ISSUE THREAD

**Issue by eduardotrandafilov** [da2k/curso-javascript-ninja#9445]
@fdaciuk  

Olá ! Estou com uma dúvida sobre patterns em projeto, em específico no exercício que envolve o método carro.adicionarPessoas() 

Na questão " Tire 4 pessoas do carro" seria recomendado criar um novo método retirarPessoas() ao invés de reutilizar o mesmo de adicionar ou depende da complexidade do método a ser implementado. Ou seja, nesse caso do exercício como a operação de retirar seria simples , valeria a pena manter apenas o método já implementado de adição ?

É isso ! Até mais !

**Comment by fdaciuk** [comment]
Oi @eduardotrandafilov! As primeiras aulas do curso servem como apresentação da linguagem. Não se prenda a patterns nesse momento: procure entender primeiro o que é possível ou não fazer com a linguagem. Depois de entender a linguagem, você consegue aplicar boas práticas.

Sem saber o que são "más práticas", não é possível aplicar "boas práticas", concorda?

Então esqueça boas práticas e patterns nesse momento, e foque em entender como a linguagem funciona, ok?

Mais pra frente no curso, quando já tivermos boa parte do conteúdo da linguagem bem estabelecido, aí vamos entrar em mais detalhes de como fazer as coisas da melhor forma, ok? Por enquanto, foque em **fazer**, independente se é a melhor forma ou não :)

**Comment by eduardotrandafilov** [comment]
Opa...tranquilo! vou seguir esse caminho seu  @fdaciuk sem dúvida! Percebi mesmo que o tempo gasto entre os dois estudos boas praticas (muito extenso) e conhecer nova stack js me consumiu boas horas ! Isso aí , vou focar no js ninja para consolidar melhor o aprendizado.

vlw!! :+1:

**Comment by fdaciuk** [comment]
Boa! É isso aí mesmo: um passo de cada vez! Quando você perceber, já estará longe :D
