### ISSUE TITLE
Utilização de ternario ':'

### ISSUE THREAD

**Issue by marcelzanatta** [da2k/curso-javascript-ninja#9449]
Olá Fernando!!! È possível utilizar a condição com ternário sem o operador ou ":" ?

ex. 

```cor === 'azul' ? corHex = 0xFFFF```

tentei de várias formas e não consegui, então resolvi usar o "if" mesmo.

Obrigado

@fdaciuk

**Comment by marcelzanatta** [comment]
```cor === 'azul' ? corHex = 0xFFFF : '' ;```  // Achei a resposta no próximo vídeo. 

thank's

**Comment by fdaciuk** [comment]
Oi @marcelzanatta! Examente: não é possível usar apenas uma parte do ternário.. como ele espera uma expressão condicional, e te retorna uma nova expressão, sendo a condição inicial verdadeira ou falsa, é obrigatório sempre as duas partes :)

Mas não use o ternário para substituir o `if`: se você não precisa necessariamente de uma expressão após testar a condição, por exemplo, o `if` seria mais indicado, já que ele não retorna nada, apenas executa o bloco de código se a expressão condicional for verdadeira :)
