### ISSUE TITLE
Dúvida - Filas encadeadas

### ISSUE THREAD

**Issue by O-Programador** [da2k/curso-javascript-ninja#9484]
Não estou conseguindo resolver esse exercicio, alguem poderia me dar um help usando FILAS ENCADEADAS --- FILAS ENCADEADAS, escrever um programa que leia numeros e que  permita o usuãrio saber quantos numeros PARES e quantos numeros IMPARES eciste na lista, o programa devera ter a opção de inserir, excluir toda a lista, excluir  elemento da lista e motrar todos os elementos da lista contando quentos são PARES  e quentos são IMPARES

**Comment by fdaciuk** [comment]
Oi @O-Programador! Para resolver esse exercício em JavaScript é preciso ter uma boa base da linguagem. Em que ponto do curso você está? Talvez o que você precisa é seguir com os estudos, para ter o conhecimento necessário para resolver esse problema :)

**Comment by fdaciuk** [comment]
Oi @O-Programador! Vou fechar a issue, mas se você ainda estiver com problemas, só avisar que eu te ajudo, ok? :D
