### ISSUE TITLE
Dúvida - Fila encadeada circular

### ISSUE THREAD

**Issue by O-Programador** [da2k/curso-javascript-ninja#9485]
USANDO FILA ENCADEADA CIRCULAR -- Usando FILA ENCADEADA CIRCULAR Construa um programa que insere nomes em  uma fila circular e imprime a cada inserção, a fila completa, o “primeiro” e o  “último” elemento da fila. E, permitir também, a exclusão de um nome em uma fila  circular, permitir tambem, excluir a lista inteira

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @O-Programador! Qual a sua dúvida? :)

**Comment by O-Programador** [comment]
Travei nesse exercicio que o professor passou na faculdade, se puder me
ajudar respondendo ele.
Ainda estou aprendendo Java

Em qui., 22 de abr. de 2021 às 14:13, Fernando Daciuk <
***@***.***> escreveu:

**Comment by fdaciuk** [comment]
Oi @O-Programador! Eu respondi na outra issue que você abriu, mas vou repetir aqui:

Para resolver esse exercício em JavaScript é preciso ter uma boa base da linguagem. Em que ponto do curso você está? Talvez o que você precisa é seguir com os estudos, para ter o conhecimento necessário para resolver esse problema :)

**Comment by fdaciuk** [comment]
Oi @O-Programador! Vou fechar a issue, mas se você ainda estiver com problemas, só avisar que eu te ajudo, ok? :D
