### ISSUE TITLE
Dúvida - LISTAS SIMPLES ENCADEADAS NAO ORDENADAS

### ISSUE THREAD

**Issue by O-Programador** [da2k/curso-javascript-ninja#9486]
Usando LISTAS SIMPLES ENCADEADAS NAO ORDENADAS. Contrua um aplicacao  que leia vãrios numeros permitindo a insercao no inicio ou no final da lista, o  programa deve permitir a listagem dos numeros informados, exclusao de todos os  itens da lista, excluir um elemtno da lista (do inicio ou do final da lista) e por fim,  mostrar qual foi o maior valor e o menor valor informado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @O-Programador! Qual a sua dúvida? :)

**Comment by fdaciuk** [comment]
Oi @O-Programador ! Seguindo a resposta das outras issues que você abriu:
Para resolver esse exercício em JavaScript é preciso ter uma boa base da linguagem. Em que ponto do curso você está? Talvez o que você precisa é seguir com os estudos, para ter o conhecimento necessário para resolver esse problema :)

**Comment by fdaciuk** [comment]
Oi @O-Programador! Vou fechar a issue, mas se você ainda estiver com problemas, só avisar que eu te ajudo, ok? :D
