### ISSUE TITLE
Dúvida de aprendizado e outros

### ISSUE THREAD

**Issue by GleristonCastro** [da2k/curso-javascript-ninja#9487]
Fernando @fdaciuk boa noite,

Eu comprei o curso na udemy em torno de outubro ou novembro do ano passado e estou gostando muito. Passei um tempo sem fazer o curso (por motivos pessoais), e comecei tudo de novo novamente, do zero!, e passei por (quase) todas as etapas do curso.

O que fiz foi assistir todas as aulas, anotar quase tudo, inclusive fiz meio como uma apostila do seu curso, que até imprimi, acho que não é possível anexar arquivo aqui para você, mas não vem o caso agora.

A questão é como lhe falei acima, fiz todo o curso, assistir todos os vídeos e agora estou começando a fazer todos os exercícios, tem certas vezes que não lembro bem, e recorro a minha apostila que fiz, mais rápido até do que procurar nos vídeos. Mas como disse, estou fazer os exercícios e estou me saindo muito bem, digamos que 90% consigo fazer sozinho e 10% das vezes faço uma colinha na apostila.

Se não me engano fiz a issue até challenger 04 ou 05 não lembro... já estou no 09, não estranhe se fazer o submit de vários exercícios seguidos.

Sobre a correção (dos vídeos) só após fazer o submit de cada desafio que irei assistir os vídeos das correções.

Então minha dúvida não tem haver com algum código (por enquanto) e sim explicar como fiz meu processo de aprendizado diferenciado. E que estarei postando a resolução dos desafios sequenciados.

Agora uma dúvida pensando no futuro como programador...

Eu penso em breve desenvolver uma aplicação na qual quero fazer tudo meio que AJAX, zero refresh como é por exemplo o GMAIL, estou fazendo o curso de javascript ninja para depois fazer seu curso de react (inclusive já comprei), quero ficar ninja nos dois. Mas a dúvida se para fazer o projeto que falei, com estes dois cursos será suficiente?

Uma outra dúvida é se existe um fórum, um grupo (aberto) com seus alunos ou ex-alunos que possamos trocar ideia. Entrei no telegram é um grupo fechado. Talvez tenha algum aluno seu que fez algum grupo ou afim?

Outra dúvida que tenho é sobre segurança dos códigos, tanto javascript como react etc... pois como falei penso em fazer uma aplicação e já me preocupo com a segurança, você me indica algum curso ou já fez vídeos com essa abordagem?

E uma última dúvida por enquanto prometo :) , como posso criptografar um código javascript? Pois penso que se algum dia o código for vazado da minha aplicação ele se torne incapaz de ser reutilizado, seria meio que o CORE do sistema. 

Bem é isso, eu queria mandar tudo isso por e-mail, mas não achei seu e-mail, ou pelo menos não percebi. Mas é isso, obrigado por passar seus conhecimentos e nos falamos em breve, abraço.

**Comment by fdaciuk** [comment]
Oi @GleristonCastro! Que legal cara, fico feliz em saber que está conseguindo evoluir :D 
Vamos às dúvidas:

> Eu penso em breve desenvolver uma aplicação na qual quero fazer tudo meio que AJAX, zero refresh como é por exemplo o GMAIL, estou fazendo o curso de javascript ninja para depois fazer seu curso de react (inclusive já comprei), quero ficar ninja nos dois. Mas a dúvida se para fazer o projeto que falei, com estes dois cursos será suficiente?

Com o curso de JS você já deve conseguir fazer isso. No curso de React você vai aprender a fazer isso, mas usando React haha :D 

---

> Uma outra dúvida é se existe um fórum, um grupo (aberto) com seus alunos ou ex-alunos que possamos trocar ideia. Entrei no telegram é um grupo fechado. Talvez tenha algum aluno seu que fez algum grupo ou afim?

Sim, tem um discord para os alunos do curso! Me manda uma mensagem lá pela Udemy que eu te passo o link :)

---

> Outra dúvida que tenho é sobre segurança dos códigos, tanto javascript como react etc... pois como falei penso em fazer uma aplicação e já me preocupo com a segurança, você me indica algum curso ou já fez vídeos com essa abordagem?

Basicamente tudo o que fica do lado do cilente (navegador, no caso da web) é público. Então toda informação "sensível" do seu projeto deveria ficar no backend, não no frontend. No curso de React eu abordo alguns detalhes de como criar um sistema serverless, usando o Firebase, que é um serviço que te entrega o necessário para ter segurança no backend, sem necessariamente precisar escrever um backend próprio :)

---

> E uma última dúvida por enquanto prometo :) , como posso criptografar um código javascript? Pois penso que se algum dia o código for vazado da minha aplicação ele se torne incapaz de ser reutilizado, seria meio que o CORE do sistema.

Essa entra exatamente no mesmo ponto da resposta anterior: código frontend pode ser minificado, e pode até passar por um processo de encriptação, mas tudo o que renderiza no navegador é facilmente decriptável. Não vale a pena o esforço, pois só vai deixar sua aplicação mais lenta. O importante é tentar deixar código sensível sempre no backend, aí você não terá problemas, ok? :)

---

Respondi suas dúvidas? Fique sempre à vontade para perguntar quando precisar, ok? :)

**Comment by fdaciuk** [comment]
Oi @GleristonCastro! Vou fechar a issue, mas se você ainda estiver com problemas, só avisar que eu te ajudo, ok? :D
