### ISSUE TITLE
Challenge-13 

### ISSUE THREAD

**Issue by felipprodrigues** [da2k/curso-javascript-ninja#9544]
```js
--------- Felipe ---------
var map = [];
newBrasil.map(function( item, index ){
  map.push({
    id: index + 1,
    estado: item.estado + ' pertence ao Brasil.'
  })
})
--------- Daciuk ---------
var map = newBrasil.map(function(item, index){
   return {
    id: item.id + 1,
    estado: item.estado + ' pertence ao Brasil'
  }
})
```

Daciuk, na resolução dos exercícios do challenge-13 você usa o segundo bloco de código para incluir + 1 ao index de cada estado e, em seguida, adiciona uma string à propriedade estado. Minha dúvida é em relação ao primeiro bloco de código, no caso, eu obtive o mesmo resultado porém com o método push, já que declarei a variável `map` separadamente. 

Embora o meu bloco de código resulte no mesmo output que o seu, tenho dúvidas quanto ao raciocínio que usei. Seria essa uma abordagem errada ou somente mais verbosa e talvez complicada?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @felipprodrigues! Apesar do resultado ser o mesmo, a abordagem está errada sim, mas "errada" falando de forma semântica.
A ideia do uso do `map` é para transformar valores: a função passada para o `map` recebe um valor como input (via argumento) e retorna uma transformação para esse valor.

No caso do método `.map`, por ele ser um método de array, ele vai sempre iterar o array e executar a função uma vez para cada item dentro do array.

E ao final dessa iteração, o método `.map` vai te retornar um novo array. Então, semanticamente falando, não faz sentido criar um novo array primeiro, e usar o `.map` só para iterar o array, fazendo `push` para o array anteriormente criado, se o pŕoprio método já te retorna o novo array que você precisa!

Se quiser só iterar o array, você já tem outras estruturas imperativas para isso, como o `for`, `while` e o próprio método `.forEach`.

Os métodos declarativos (`map`, `filter`, `reduce`, `every`, `some`, etc), vão iterar pelo array também, assim como o `.forEach`, o `for`, o `while`.. a diferença é que esses métodos servem para coisas específicas:

Você precisa de um novo array, do mesmo tamanho original, mas quer transformar cada item do array? Use o `.map`.
Precisa filtrar alguns itens do array com base em uma condição? Use o `.filter`.
Precisa verificar se todos os itens do array "casam" com alguma condição? Use o `every`.

E assim por diante. Cada método tem sua responsabilidade, por isso é importante saber o que cada um faz, e usar o método correto, no momento correto. Na dúvida, use um `.forEach`, que vai iterar de forma imperativa mesmo, e olhe para o resultado. Muitas vezes, olhando para o resultado final, a gente consegue ver melhor qual método caberia melhor para o resultado que esperamos =)

Deu pra entender a ideia? =)

**Comment by felipprodrigues** [comment]
@fdaciuk Deu pra entender sim! 

Uma última coisa que acabei notando agora, enquanto lia seu comentário, é o fato de você ter declarado `id: item.id + 1`. Não seria mais conveniente utilizar diretamente o parâmetro index e adicionar + 1 ( `id: index + 1` ) como eu fiz no meu exemplo? Ou isso também seria uma forma incorreta de declarar o valor do objeto em questão?

**Comment by fdaciuk** [comment]
Oi @felipprodrigues! No caso do `index`, vai depender do objetivo. No caso do desafio, o objetivo era adicionar `1` ao `ID` do item iterado, não adicionar 1 ao index do elemento do array. O ID poderia ser qualquer outra sequência de números, diferente do `index`, e isso poderia trazer resultados inconsistentes =)

**Comment by felipprodrigues** [comment]
@fdaciuk Muito bem explicado! Obrigado por esclarecer esses pontos

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar =)
