### ISSUE TITLE
Dificuldade GIT

### ISSUE THREAD

**Issue by alexcamposwd** [da2k/curso-javascript-ninja#9569]
Fernando, boa tarde

Estou com dificuldade para compartilhar meus desafios no GIT, sigo todo o processo mais alumas coisas estão diferentes, por exemplo: depois de commit direto no meu branch, eu clico no link  from da2k/curso-javascript-ninja ai tudo é diferente e não tem as opções que vocês passa. Teria outra forma ?
Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @AlexCamposBR! Não precisa enviar os desafios aqui no GitHub. Pode apenas resolver na sua máquina que já está ótimo. O importante é praticar :D

**Comment by yurinevesdev** [comment]
Tive o mesmo problema do alexcamposwd, mas como já foi respondido vou só praticar!

**Comment by fdaciuk** [comment]
Boa @yurineves1994! Qualquer dúvida, só perguntar :D
