### ISSUE TITLE
Dúvida - A  quantidade de vezes que o elemento aparece na sequência de números.

### ISSUE THREAD

**Issue by talysonmaia** [da2k/curso-javascript-ninja#9572]
Olá, eu sou novo aqui. Estou com uma dúvida em um exercício que não consigo resolver de forma alguma. A questão pede a quantidade de vezes que o elemento aparece na sequência de números.

Entrada e Saída
Entrada:
1ª linha: Os valores de X e N, onde X é o número que corresponde ao Ultron e N a quantidade de elementos da sequência de números.
2ª linha: Os elementos da sequência de números.
Saída:
A quantidade de vezes que o elemento aparece na sequência de números.

Exemplo: 
>>
0 4
0 0 1 0
<<
3

(É pra eu tentar fazer sem o uso de vetores)

Meu código: 
#include <stdio.h>

int main () {
    
    int X, N, cont = 0;
    scanf("%d", &X);
    scanf("%d", &N);
    for(int i = 0 ; i <= N ; i++) {
         if(i == X) {
                cont = cont + i; 
            }
        
        
    }
        printf("%d", cont);
}

**Comment by tcanhetti** [comment]
Fala @talysonmaia , blz? Esse repositório é para o curso de Javascript, esse teu código é em C, talvez é melhor abrir essa issue em algum repositório de C( ++, #). Aqui vai ser difícil vc ser respondido por falta de conhecimento especifico da galera aqui do curso, a não ser que o Fernando tenha o conhecimento e te responda.
Boa sorte ai, abç.

**Comment by fdaciuk** [comment]
Oi @talysonmaia! Infelizmente não tenho conhecimento em C pra te ajudar nessa.. vai ser mais fácil fazer como o @tcanhetti comentou, e postar a sua dúvida em alguma comunidade de C =)

**Comment by talysonmaia** [comment]
Olá, eu não sei mexer muito no github, sou iniciante. Fiz essa pergunta em um lugar errado mesmo, peço perdão. Muito obrigado pelas dicas.

**Comment by fdaciuk** [comment]
Sem problemas meu caro! No que pudermos ajudar, só avisar =)
