### ISSUE TITLE
Challenge 27 - Dúvida sobre Refatoração dos métodos de Array  

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9585]
Oi Fernando, 
Tudo bem ?

Estou tentando refatorar a parte de métodos de Arrays da 'Challenge 27' e me deparei com uma certa dificuldade.
Eu já tentei algumas formas, mas acabo voltando com a função ```js  getArrayPrototype()```, conforme o primeiro código abaixo :

Eu acabaria chamando ela em todos os métodos(forEach, map, filter...etc)  somente para receber o Array.prototype, que não vejo sentido .

```js

    DOM.prototype.get = function get() {
      return this.element;
    };

 
      DOM.prototype.forEach = function forEach() {
        return getArrayPrototype().forEach.apply(this.element, arguments);
      };

      function getArrayPrototype() {
        return Array.prototype;
      }

    
```

Vou exemplificar aqui com o forEach(), o que tinha pensado em fazer e se puder me dar uma luz se algo parecido seria possível, eu agradeço:

A principio queria passar tudo para a funcao 'getArrayPrototype' e criar uma maneira de mudar somente os métodos.
Porém, me dei conta de que 'this.element' e 'arguments' precisam ficar na função principal. 

Dai tentei assim:
```js
 DOM.prototype.forEach = function forEach() {
        return getArrayPrototype('forEach').apply(this.element, arguments);
      };

      function getArrayPrototype(method) {
        return `Array.prototype.${method}`
      }
```

Mas dá este erro:

```
Uncaught TypeError: getArrayPrototype(...).apply is not a function
    at DOM.forEach (challenge-27.js:62)
 ```

Não sei se esta linha de raciocínio está correta.

Poderia me dar uma luz ?
Obrigada
Gilmara

@fdaciuk

**Comment by Gilmara-Git** [comment]
Fernando, bom dia 

Veja se o que tentando codar tem sentido, please:

Estou passando por parametro a função forEach, o element(node que tem as âncoras), e o arguments para a função ```getArrayPrototype()```.
Ao debugar, quando eu passo o mouse nas variávies``` $method}`,${element} e ${arg}```, dentro da ```getArrayPrototype```
  ```return `Array.prototype.${method}.apply(${element}, ${args})` ```; é mostrado a informação de 'method' igual a 'forEach', 'element' igual ao 'Node' que tem 3  'a', e o 'arg', que, traz somente 1 argumento (função que representa a chamada do forEach  -   ``$a.forEach(function (link) {
      console.log(link.firstChild.nodeValue);
    });``

```js 
 DOM.prototype.forEach = function forEach() {
        let element = this.element;
        let args = arguments
        let test = getArrayPrototype(forEach, element, args);

        return (test);
        // return getArrayPrototype('forEach').apply(this.element, arguments);
      };

      function getArrayPrototype(func, element, args) {
        let method = func.name;
        // let { args, element } = func;
        // console.log(func.args, func.element)
        return `Array.prototype.${method}.apply(${element}, ${args})`;
      }
`
```

Eu vi que o retorno da função ```getArrayPrototype(forEach, element, args)``` está trazendo ```test = "Array.prototype.forEach.apply([object NodeList], [object Arguments])", forEach = ƒ forEach(), element = NodeList(3) [a, a, a] ```e não entendi porque.

Eu vi que dentro da ```DOM.prototype.forEach```  são mostrados 3 arguments   e dentro da ```getArrayPrototype``` é mostrado somente 1 argument

Eu devo deixar o this.element e o arguments, dentro da função  DOM.prototype.forEach  ?

Espero tem conseguido passar minha dúvida.
Obrigada, 

Gilmara

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Você está fazendo quase tudo certo. O problema é o retorno da função `getArrayPrototype`: perceba que você está retornando um array, não a referência de um método:

```js
function getArrayPrototype(method) {
  return `Array.prototype.${method}`
}
```

Essa sintaxe que você usou não faz parte do ES5 mostrado no curso, ela é uma feature nova para concatenar strings. Ao usar a crase para representar a string, você consegue interpolar variáveis dentro da string usando `${suaVariavel}`, onde essa variável será avaliada, e o valor da variável será concatenado à string.

Então o que você está fazendo é o mesmo que fazer:

```js
return 'Array.prototype.' + method
```

Veja que isso nada mais é do que uma string. E se estamos lidando com strings, nós não temos o método `.apply`, que só pode ser usado com funções =)

Para funcionar, a sintaxe que que você procura é a de passar valores dinâmicos como string para serem usados como propriedades de um objeto. E essa sintaxe é a sintaxe de colchetes! Lembra que vimos isso lá no começo do curso? =)

Basicamente o que você quer fazer é algo assim:

```js
return Array.prototype[method]
```

Que quando você passar o método `forEach` via string, por exemplo, você vai ter

```js
return Array.prototype['forEach'] // agora sim você terá acesso ao método `forEach` =)
```

Deu pra entender a ideia? =)

**Comment by Gilmara-Git** [comment]
Oi Fernando, entendi sim, me salvou..rsrs,  obrigada pela atenção! 
Eu não tinha pensado em usar os colchetes e fiquei tentando algumas alternativas. 
Eu estava com a idéia em minha cabeça de que era para usar os colchetes quando visse ou me deparesse com um objeto assim:

```js
let carro  = {  
  portas: 2,
  assentos: 5,
  'cor': 'branco'
}
console.log(carro['cor']) // branco
console.log(carro['assentos']) // 5 
```

Com a sua explicação, consegui fazer de duas formas:

1 - Assim passando o nome do método manualmente

```js 
DOM.prototype.map = function map() {
        return getArrayPrototype(['map'], this.element, arguments);
      };
```

```js  
function getArrayPrototype(method, element, args) {
        return Array.prototype[method].apply(element, args);
      }
```

2 - Pegando o nome do metodo e  passando nos colchetes:  

```js 
DOM.prototype.map = function getMethodNameAndExecute(func){
        let method = func.name;
        return getArrayPrototype([method], this.element, arguments);
      };
```

Para conseguir pegar o nome do método,  na chamada do ```map```, eu nomei a função dentro do parâmetro de '''map'''.
   ```js 
let dataJs = $a.map(function map(element) {
      return element.getAttribute("data-js");
    });
```

OBS:
Eu tentei fazer como abaixo para ter a funcao ```getMethodNameAndExecute``` escrita somente  1 vez ,
 e só fazer a chamada quando precisar, mas dai fala que 'func' , que estou passando no parametro é undefined
``` js
DOM.prototype.forEach = getMethodNameAndExecute(func);

      function getMethodNameAndExecute(func){
        let method = func.name;
        return getArrayPrototype([method], this.element, arguments);

      };
```
Tem algum jeito de fazer isso  ?

**Comment by fdaciuk** [comment]
Então, o uso dos cholchetes serve para qualquer tipo de objeto.. levando com consideração que o `.prototype` é um objeto, você também pode usar a sintaxe de colchetes para buscar métodos dinamicamente sem problemas =)


> Para conseguir pegar o nome do método, na chamada do map, eu nomei a função dentro do parâmetro de '''map'''.

Não recomendo fazer dessa forma, pois meio que você precisa garantir que a pessoa que vai usar a lib DOM tenha que obrigatoriamente passar uma função nomeada, sendo que deveria funcionar corretamente se for passada uma função anônima.

A primeira forma seria a "mais recomendada".

Mas levando em consideração que a implementação desses métodos tem somente 1 linha de código, acho que não faz muito sentido tentar abstrair tanto.. ainda que pareça repetição de código, no final fica muito mais legível e clara a sua intenção, se usar o `Array.prototype` direto no método do DOM que você está criando =)

> Eu tentei fazer como abaixo para ter a funcao getMethodNameAndExecute escrita somente 1 vez ,
e só fazer a chamada quando precisar, mas dai fala que 'func' , que estou passando no parametro é undefined

Apenas para fins didáticos, dá pra fazer algo nesse sentido sim: é importante primeiro entender como o escopo está sendo resolvido pelo interpretador do JS.

Perceba que você está executando a função `getMethodNameAndExecute`, e atribuindo o retorno dela para o seu `DOM.prototype.forEach`. Ao executar a função, você está expondo o conteúdo no corpo dela ao escopo do momento em que ela está sendo executada.

E nesse escopo (criação do método `DOM.prototype.forEach`), você não tem acesso ao `this` de dentro do `DOM`. Você só tem esse acesso quando **cria uma função e atribui para o `DOM.prototype.forEach`**.

Perceba a diferença de atribuir **uma função** (estamos falando da referência da função), e de atribuir o **retorno de uma função** (que acontece quando vc executa a função).

Para ter acesso ao `this`, a função `getMethodNameAndExecute` deveria **retornar uma nova função**, e essa função é que vai ser passada para o `DOM.prototype.forEach`. Aí sim, dentro dessa função você vai ter acesso ao `this` no escopo correto =)

E é essa função retornada que vai ser a função usada quando você executar o `.forEach`, depois de construir um objeto com o construtor `DOM`.

Seria algo assim:

```js
function getMethodNameAndExecute (method) {
  return function funcaoInterna () { // só nomeei para representar no próximo exemplo
    return Array.prototype[method].apply(this.element, arguments)
  }
}
```

Que aí, quando você executar a função:

```js
DOM.prototype.forEach = getMethodNameAndExecute('forEach')
```

Ao executar `getMethodNameAndExecute`, o retorno dela é que será passado para `DOM.prototype.forEach`, ou seja: a função `funcaoInterna` criada no exemplo anterior =)

Ficou mais claro? =)

**Comment by Gilmara-Git** [comment]
1 - Sobre o uso dos colchetes, ficou claro agora. 
Não tinha me atentado que podemos usa-los para qualquer tipo de objeto e nem tinha pensado no fato de que '.prototype' é um objeto. 

"_Mas levando em consideração que a implementação desses métodos tem somente 1 linha de código, acho que não faz muito sentido tentar abstrair tanto.. ainda que pareça repetição de código, no final fica muito mais legível e clara a sua intenção, se usar o Array.prototype direto no método do DOM que você está criando_ "

2 - Se for analisar bem, faz muito sentido o que você está falando, até mesmo porque   estou repetindo a função getArrayPrototype()  em todos os metodos abaixo de qualquer jeito:

```js 
DOM.prototype.forEach
DOM.prototype.map
DOM.prototype.filter
DOM.prototype.reduce
DOM.prototype.reduceRight
DOM.prototype.every
DOM.prototype.some
```


Ex:
```js
 DOM.prototype.filter = function filter() {
        return getArrayPrototype(['filter'] , this.element, arguments);
      };
```

```js  
Vou deixar  como vc recomendou em todos eles:
DOM.prototype.filter = function filter() {
        return Array.prototype.filter.apply(this.element, arguments);
      };
```


_Para ter acesso ao this, a função getMethodNameAndExecute deveria retornar uma nova função, e essa função é que vai ser passada para o DOM.prototype.forEach._

_Aí sim, dentro dessa função você vai ter acesso ao this no escopo correto =)_

_E é essa função retornada que vai ser a função usada quando você executar o .forEach, depois de construir um objeto com o construtor DOM._
_Seria algo assim:_

```js

function getMethodNameAndExecute (method) {
  return function funcaoInterna () { // só nomeei para representar no próximo exemplo
    return Array.prototype[method].apply(this.element, arguments)
  }
}
```


Consegui fazer esta ideia somente para entender na prática.

```js
 DOM.prototype.forEach = getMethodNameAndExecute("forEach");

      function getMethodNameAndExecute(method) {

        return function execute() {
          return Array.prototype[method].apply(this.element, arguments);
        };
      }
```

Então esta função interna é um callback, correto ?

**Comment by fdaciuk** [comment]
> Então esta função interna é um callback, correto ?

Não necessariamente.. o que a gente costuma chamar de _callback_ são funções que normalmente usamos para fazer inversão de responsabilidades. Por exemplo: todos esses métodos de array (`.map`, `.filter`, `.forEach`) iteram pelo array, exatamente como você faria com um `for` normal.

A diferença é que cada um deles faz alguma coisa à partir de uma função recebida por argumento: 
- o `.map` usa essa função para transformar cada um dos itens do array;
- o `.filter` usa a função como um predicado (função que retorna um booleano) para saber se o item iterado deve ou não estar contido no novo array;
- o `.forEach` só itera pelo array, e executa a função para cada um dos itens, não fazendo nada além disso (exatamente como o `for`).

Essa função que você passa via argumento para esses métodos é o que chamamos de _callback_, pois o método recebe **a referência da função** e, internamente, executa ela =)

Essa função passada também é responsável por dizer como o método deve validar os dados. Por isso dizemos que isso é uma "inversão de responsabilidade": o método itera pelo array e faz o que tem que fazer, mas quem diz o "como" fazer é responsabilidade dessa função que você passa via argumento =)

Mas a estrutura dessa função `getMethodNameAndExecute`: se chama _Higher Order Function_ (ou função de alta ordem, ou ordem superior, se for traduzir) =)

Funções de alta ordem podem:
- ou retornar uma função;
- ou receber uma função via argumento;
- ou os dois =)

Os próprios métodos `.map`, `.filter`, `.forEach`, etc., são funções de alta ordem, pois todas elas recebem uma função via argumento =)

Mas são apenas nomenclaturas. O importante é entender o porquê nós fazemos esse tipo de coisa. Se isso ficou claro, é o que importa :D

---

Apenas duas dicas adicionais: a primeira é sobre o código que você estava fazendo, com a função `getArrayPrototype`: você estava passando um array como primeiro argumento, com uma string com o nome do método dentro. Não precisa, pode passar só a string mesmo, pois esse argumento será usado dinamicamente quando você chamar o `Array.prototype[method]`.

Como o JS tem tipagem fraca, ele não vai reclamar se você passar um array como estava fazendo: ele automaticamente "entende" que o array tem somente 1 item, e "remove" o array, passando somente o item ali para o `Array.prototype`. Mas só pra vc saber que não precisa passar um array, ok? =)

E a outra coisa é sobre o GitHub: sempre que você precisar escrever código, tem duas formas de fazer: 
- com 3 crases antes e depois do código, como você estava fazendo, para blocos de código, 
- e com 1 crase antes e depois do código, para marcar o código inline.

Só importante dizer que, ao usar 3 crases para criar blocos de código, é preciso deixar as 3 crases em uma linha sozinhas. Se você deixar o código junto das 3 crases, tanto no começo quanto no final, o GitHub se perde na hora de fazer o _highlight_ do código =)

Só dizendo isso pq eu editei suas mensagens pra ajustar isso, ok? :D 

Mas é isso! Se ficou alguma dúvida ainda, me avise que eu te ajudo! :D

**Comment by Gilmara-Git** [comment]
Muito obrigada pelas explicacões Fernando.
Deu para ficar claro, 'callback', 'Higher Order Function' (eu nem conhecia este termo).

Também entendi que não é preciso passar um 'array' como primeiro parâmetro na função `getArrayPrototype`, fiz o teste aqui. 
Legal saber que o JS remove o 'array', quando ele vê que tem somente um item no mesmo.

Quanto ao Github, obrigada por corrigir, eu estava apanhando para formatar o texto...rsr

Valeu, grande abraço
Gilmara

**Comment by fdaciuk** [comment]
Show @Gilmara-Git! Que bom que ficou tudo claro! :D 

Qualquer dúvida, conte comigo :D
