### ISSUE TITLE
Challenge 05 - Duvida no exercicio

### ISSUE THREAD

**Issue by raffaelmiranda** [da2k/curso-javascript-ninja#9589]
Professor fique com duvida na interpretação do que estava pedindo, tive que recorrer o exercício resolvido. Seria esse ponto:

> /*
> Crie uma função chamada `book`, que recebe um parâmetro, que será o nome do
> livro. Dentro dessa função, declare uma variável que recebe um objeto com as
> seguintes características:
> - esse objeto irá receber 3 propriedades, que serão nomes de livros;
> - cada uma dessas propriedades será um novo objeto, que terá outras 3
> propriedades:
>     - `quantidadePaginas` - Number (quantidade de páginas)
>     - `autor` - String
>     - `editora` - String
> - A função deve retornar o objeto referente ao livro passado por parâmetro.
> - Se o parâmetro não for passado, a função deve retornar o objeto com todos
> os livros.
> */

````
function book (bookName) {
  var allBooks = {
    'Segredos do Ninja Javascript': {
      quantidadeDePaginas: 488,
      autor: 'John Resig & Bear Bibeault',
      editora: 'Novatec'
    },
    'Introdução ao HTML5': {
      quantidadeDePaginas: 225,
      autor: 'Bruce Lawson & Remy Sharp',
      editora: 'Alta Books'
    },
    'Smashing CSS': {
      quantidadeDePaginas: 283,
      autor: 'Erick A. Meyer',
      editora: 'Bookman'
    }
  };

  return !bookName ? allBooks : allBooks[bookName];
}
````

>  Dentro dessa função, declare uma variável que recebe um objeto com as
> seguintes características

esse objeto não seria uma array e cada posição do array seria objeto do tipo livro? Fiquei bem confuso no entendimento do enunciado

`allBooks[bookName]`

Outra perguntga é: o que fica mais fácil para você, abrir um issue aqui no github ou abrir um pergunta no forum da aula lá na Udemy?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @raffaelmiranda! Vamos lá!

Primeiramente sobre a sua dúvida de onde postar dúvidas: fique à vontade para postar aqui lá pela Udemy, ok? Eu monitoro os dois lugares. Só se for postar alguma dúvida aqui, não esqueça de me marcar com `@fdaciuk`. No mais, pode escolher onde você achar melhor =)

---

> esse objeto não seria uma array e cada posição do array seria objeto do tipo livro? Fiquei bem confuso no entendimento do enunciado

Se você assistir à correção da aula, talvez fique mais fácil de entender, mas algumas aulas atrás nós falamos sobre como "pegar" propriedades de objetos de forma dinâmica, que seria exatamente usando a sintaxe de colchetes, e passando uma string com o nome da chave do objeto que queremos, lembra disso?

Dá uma olhada nesse exemplo:

```js
var person = {
  name: 'Maria',
  age: 23
}
```

Se eu quiser pegar o valor da propriedade `name` do objeto `person` acima, eu posso fazer de duas formas: com a sintaxe de ponto:

```js
person.name // "Maria"
```

Ou com a sintaxe de colchetes:

```js
person['name'] // "Maria"
```

As duas formas funcionam! Mas perceba que, usando a segunda forma, nós precisamos apenas passar uma string como nome da chave. Isso nos abre algumas possibilidades. Pense nesse objeto `allBooks`:

```js
var allBooks = {
  'Segredos do Ninja Javascript': {
    quantidadeDePaginas: 488,
    autor: 'John Resig & Bear Bibeault',
    editora: 'Novatec'
  },
  'Introdução ao HTML5': {
    quantidadeDePaginas: 225,
    autor: 'Bruce Lawson & Remy Sharp',
    editora: 'Alta Books'
  },
  'Smashing CSS': {
    quantidadeDePaginas: 283,
    autor: 'Erick A. Meyer',
    editora: 'Bookman'
  }
};
```

As chaves desse objeto não são válidos se forem usados como nomes de variáveis (pois contém espaços), logo não podemos usar a sintaxe de ponto para pegar nenhuma dessas chaves, temos sempre que usar a sintaxe de colchetes. Se eu quiser pegar o objeto referente ao livro `'Segredos do Ninja Javascript'`, eu preciso fazer isso:

```js
console.log(allBooks['Segredos do Ninja Javascript'])
```

Isso vai exibir no console o objeto:

```js
{
  quantidadeDePaginas: 488,
  autor: 'John Resig & Bear Bibeault',
  editora: 'Novatec'
}
```

Concorda? Pois é o valor da chave `'Segredos do Ninja Javascript'`.

A outra possibilidade que o uso dos colchetes nos abre é de que podemos usar valores dinâmicos para encontrar o valor da chave: como só precisamos passar uma string qualquer, podemos atribuir uma string à uma variável, e então usar essa variável para buscar o valor do livro que queremos. Então, o exemplo anterior funciona exatamente igual se fizermos dessa forma:

```js
var selectedBook = 'Segredos do Ninja Javascript';
console.log(allBooks[selectedBook]);
```

Perceba como colocamos a string com o nome do livro em uma variável, e usamos a variável  para obter exatamente o mesmo resultado anterior!

E essa variável pode ser também um argumento de uma função (como usado no desafio), já que, ao executar a função, nós passamos uma string via argumento.

Se a chave for encontrada no objeto, a nossa função vai retornar o valor dessa chave. Senão, o objeto com todos os livros será retornado!

Deu pra entender? =)

**Comment by raffaelmiranda** [comment]
entendi sim

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
