### ISSUE TITLE
Metodo Some

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-javascript-ninja#9596]
Olá, tudo bom? Estou com dúvidas em relação ao metodo some, espero que me ajude

Tenho feito alguns testes e fiz esse aqui e por algum motivo está retornando false no console do navegador

```
var numeros = [1, 2, 3, 4, 5]
var outrosnumeros = [5, 6, 7, 8]
numeros.some(function(numero){ numero === outrosnumeros})
```

Sabe me dizer porque está retornando false? O some, deveria procurar se alguns deles é válido e retornar true, certo?

Obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marisbispo! Faltou o `return` dentro da função =)
Sem ele, a função sempre vai retornar `undefined`. E `undefined`, transformado em booleano, sempre retorna `false` =)

Retornando a expressão de comparação já vai trazer o resultado correto :D

**Comment by marisbispo** [comment]
Olá, @fdaciuk! Obrigada pela resposta!

Mas aqui no meu console, volta false mesmo passando o return. No node também! Segue o codigo: 

```
var numeros = [1, 2, 3, 4, 5];
var outrosnumeros = [5, 6, 7, 8];
numeros.some(function(numero){ return numero === outrosnumeros});
```

**Comment by fdaciuk** [comment]
Boa, agora o problema é outro, não tinha reparado que vc estava tentando comparar o valor com um array =)

Para exemplificar, olha o que está acontecendo no seu código: o `some` vai iterar pelo array, e vai te executar a função ali passada, uma vez para cada item dentro do array.

Então na primeira execução da função, o argumento `numero` vai receber `1`, certo?
Aí a sua comparação está sendo isso aqui:

```js
numero === outrosnumeros
```

Que seria o mesmo que:

```js
1 === [5, 6, 7, 8]
```

Um número nunca vai ser igual a um array, por isso sempre retorna `false` =)

Provavelmente o que você quer fazer é verificar se o argumento `numero` existe no array `outrosnumeros`, certo?

Tem algumas formas de fazer isso, mas você pode fazer isso usando um outro `some`:

```js
numeros.some(function (numero) {
  var esseNumeroExisteNoArrayOutrosNumeros = outrosnumeros.some(function (outronumero) {
    return numero === outronumero
  })
  
  return esseNumeroExisteNoArrayOutrosNumeros
})
```

Criei a variável ali só para fins didáticos. Você poderia retornar direto o segundo `some`:

```js
numeros.some(function (numero) {
  return outrosnumeros.some(function (outronumero) {
    return numero === outronumero
  })
})
```

Se a gente fizer um teste de mesa com o código, olha o que está acontecendo agora:

- O primeiro `some` vai iterar pelo array `numeros` e executar a função uma vez para cada número;
- Dentro do primeiro `some`, nós iteramos o array `outrosnumeros` para conseguir fazer a comparação do `numero`, que é resultado da primeira iteração do array `numeros`, com todos os números no array `outrosnumeros`;

Para conseguir compreender bem o código e entender o que ele faz, é importante começar debugando de fora pra dentro.

Na segunda vez que usamos o `some`, o que acontece é o seguinte:
- Iteramos pelo array `outrosnumeros`. A primeira chamada da função vai receber no argumento `outronumero` o valor `5`;
- Veja que estamos ainda na primeira chamada do primeiro `some`, então `numero` vale `1`;
- Comparamos o `numero` (1) com o primeiro item de `outrosnumeros` (5). isso retorna `false`;
- O segundo `some` só vai retornar tudo quando algum retorno for `true`, então ele continua iterando. 
- Próximo valor de `outronumero`: `6`;
- Comparamos `1` com `6` e o resultado continua `false`;
- Próxima interação, `outronumero` vai receber o próximo item do array, no caso o `7`;
- Comparamos `1` com `7` e o retorno é `false`.
- E assim por diante, até o array `outrosnumeros` ser completamente iterado e retornar `false`.
- Quando ele retorna, o valor `false` é passado como retorno do primeiro `some`, que agora vai para a sua segunda iteração.
- Agora o valor de `numero` é `2`, pois é o próximo da lista no array `numeros`.
- E começamos de novo a segunda iteração do `some` em `outrosnumeros`: ou seja: tudo vai acontecer de novo, só que agora vai ser comparado todos os valores de `outrosnumeros` com o número `2`.
- Se isso retornar `false`, o primeiro `some` vai iterar o próximo item, no caso `3`.

E assim por diante, até que algum número igual seja encontrado, o segundo `some` retorne `true`, fazendo o primeiro `some` também retornar `true` e finalizar a iteração =)

No caso do seu exemplo, o caso `true` só vai acontecer na última iteração do `numeros.some`, comparando com a primeira iteração do `outrosnumeros.some` =)

Deu pra entender melhor? =)

**Comment by marisbispo** [comment]
Poxa, muito obrigada mesmo @fdaciuk! Fez total sentido agora!

**Comment by fdaciuk** [comment]
Massa @marisbispo! Qualquer dúvida, só avisar =)
