### ISSUE TITLE
Section 29 - Aula 177 - Resposta API - Blocked by flood

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9625]
Oi Fernando, 

Uma dúvida quanto a resposta da API.
Eu notei que "as vezes" mesmo ao inserir um Cep correto, não retorna informações, mas não apresenta erro.

Debugando vi que a resposta da API estava vindo "Blocked by Flood"

```js
function parseData() {
    let result;
    try {
      result = JSON.parse(ajax.responseText);
    } catch (e) {
      result;
    }
    debugger
    return result;
  }
```

Retorno:

`result = {status: 400, ok: false, message: "Blocked by flood", statusText: "bad_request"`

Na hora eu nem pensei em chamar a url direto, mas eu estava usando o mesmo Cep mostrado nos vídeos, e outros Ceps  válidos.
https://ws.apicep.com/cep/89201010.json

Agora, como o problema não acontece, o retorno vem normal:

```status: 200, ok: true, code: "89201-010", state: "SC", city: "Joinville", …}
address: "Rua Abdon Batista"
city: "Joinville"
code: "89201-010"
district: "Centro"
ok: true
state: "SC"
status: 200
statusText: "ok"
```

O que causa isso ? 
A princípio pensei que pudesse ser o browser, mas troquei o browser e continuou a mesmo comportamento. 

 
*Acredito que isso pode ser que houve muitas requisicoes para a API naquele momento.*
Seria algo deste tipo ?

Obrigada, 
Gilmara

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! É exatamente isso! O servidor entende que houveram muitas requisições seguidas partindo do seu IP, aí ele bloqueia por um tempo, mas depois as requisições são liberadas novamente =)

**Comment by Gilmara-Git** [comment]
Ahh, Entendido Fernando!
Obrigada e bom fim de semana!
Gilmara

**Comment by fdaciuk** [comment]
Show! Bom fim de semana pra vc também :D 
Qualquer dúvida só avisar :D
