### ISSUE TITLE
Dúvida de commit no desafio 30

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9649]
Fernando, bom dia.

Eu criei meu repositório, criei a branch 'challenge-30'.
Enviei as alterações para o github, mas não estou conseguindo criar um Pull Request
Eu clico em 'Compare and Pull Request' e não me dá a opcão de criar, somente comparar.

Fala que não tem nada para comparar, mesmo que ele reconhece que as branches são diferentes. 
There isn't anything to compare
master and challenge-30 are entirely different commit histories

``https://github.com/Gilmara-Git/cars4sales/compare/challenge-30?expand=1``

Para ver o meu código, tem que ir na branch 'challenge-30'

Pode ser que eu tenho feito algo errado, mas não estou conseguindo identificar o que foi.
Quando isso acontece tem alguma maneira de resolver ? 

Obrigada.
Gilmara

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Pela mensagem do GitHub, ele está dizendo que as duas branches são completamente diferentes.. isso pode acontecer por dois motivos: ou você fez alguma alteração no histórico do git (usando rebase, por exemplo), ou então criou a branch `challenge-30` usando `--orphan`, que faz com que a nova branch seja criada com um histórico completamente novo.

Você fez alguma dessas duas coisas?

Se não fez, o que eu te recomendo fazer é: 
- No GitHub, delete a branch `challenge-30`;
- no seu PC, dentro da branch `challenge-30`, renomeie ela para qualquer outra coisa, por exemplo: `git branch -m ch30`;
- copie os arquivos dessa branch para um outro lugar, fora do diretório atual do seu projeto;
- no seu computador, acesse a branch `master` (`git checkout master`), e crie uma nova `challenge-30` com base nessa `master`: `git checkout -b challenge-30`;
- Agora só cole todo o conteúdo que você copiou anteriormente da branch `ch30` para dentro dessa, faça o commit e envie para o GitHub.

Fazendo isso, você deve conseguir comparar as alterações da `master` com a `challenge-30`, pois agora a `challenge-30` foi criada com base na `master` =)

Me deixe saber se deu certo :D

**Comment by Gilmara-Git** [comment]
Oi Fernando, 
Eu não fiz `rebase` nem `--orphan`

Ainda não sei utilizar estes comandos, apesar de já ter escutado um pouco sobre `rebase`.
Talvez a maneira que clonei o projeto que causou isso.

Fiz assim: 
Criei o repo/projeto no GitHub.
Não consegui clonar com SSH porque não tenho chave SSH ainda.
Então eu fiz o download do projeto.
Abri o projeto e criei a challenge-30
Trabalhei na challenge-30 e fiz o commit, o push e me deparei com este problema.
Dai, segui suas intruções e aconteceu o mesmo problema.

Então decidi deletar o repositorio, criar outro.
Resumindo, consegui enviar fazer o pull request. 

Agora veio outra dúvida, de entendimento do enunciado do exercício.

Quando vc diz: 
**Envie um pull request da branch `challenge-30` para a `master` e cole aqui
nesse arquivo, dentro do `console.log`, o link para o pull request no seu
projeto.**

Isso quer dizer que não é para fazer merge ?

É só colocar o link to pull request no console ?
https://github.com/Gilmara-Git/cars4sale/pull/1

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Entendi, é por isso então. Quando você baixa um repositório, ele não traz junto o histórico do git (diretório `.git`), por isso deu esse problema na hora de tentar fazer o merge :)

Sobre a sua dúvida com relação a fazer ou não o merge: a ideia é você fazer dois pull requests:
- Um pull request você vai fazer no seu próprio projeto, com as alterações do desafio atual (após o PR, pode fazer o merge sim);
- O segundo pull request é aqui no repositório do curso, onde você vai apenas editar o console.log que está no arquivo `challenge-30.js`, colocando ali o link do pull request que você abriu contra o seu próprio projeto =)

Ficou claro? =)

**Comment by Gilmara-Git** [comment]
Oi @fdaciuk, 

Ficou claro, sim.
Obrigada pelo esclarecimento!

Abraços,
Gilmara

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D
