### ISSUE TITLE
Challenge 32 - Dúvida sobre recarregar página

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9665]
Bom dia Fernando, 

Eu notei que após fazer o POST, e em seguida o GET para trazer os carros atualizados do servidor, o Frontend, mostra os carros que já estavam em tela e adiciona o último cadastrado.

Ex:
Se tiver dois carros ( Um fusca e um BMW) e eu adiciono um Ferrari está sendo mostrado assim:

Fusca
BMW
Fusca
BMW
Ferrari

Se recarregar a página, os dados são mostrados corretamente:
Fusca
BMW
Ferrari

Debuguei e verifiquei os dados vem corretamente do Backend. 
Tentei aplicar uma lógica no Fronted para resolver isso, mas não consegui.

Daí fiz a página recarregar com setTimeout. Eu chamo a função que faz o GET e recarrego a página.
```js
setTimeout(function(){
                   app.allCars();
                   window.location.href='http://127.0.0.1:5501/index.html'
                 }, 100)
```

Pesquisando nas issues fechadas, vi que alguém usou:
```js
window.location.reload();
```
Testei e senti que esta solução é mais performática, mais transparente para o usúario.
Enfim, esta é a maneira mais apropriadade de resolvir isso ?

P.S:  Eu acabei criando outro repositório no GitHub, pois novamente não consegui fazer o merge com a master, no caso merge da branch 32 com a master. 
Você vai notar isso no link do pull request que enviei na challenge-32.

Obrigada
Gilmara 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! É mais simples que isso: ao invés de fazer reload na tela, você pode simplesmente remover todas as linhas da tabela, e adicionar novamente com os dados que você recebe no GET .. assim não precisa recarregar a tela, e a tabela vai estar sempre atualizada :D

**Comment by Gilmara-Git** [comment]
Oi Fernando, 

Eu até tinha tentando fazer algo parecido. 
Tipo  retirar as `<td>`  de `<tr>`  e colocar de volta. Tentei com `tbody` também.

Tentei agora retirar as linhas, que são as `<tr>`  do fragment, e colocar novamente, mas no Frontend continua duplicando o que já tem,  e adiciona o último carro. 

A parte do cógido que me refiro está no final da função abaixo.
Talvez eu esteja fazendo da forma incorreta.

```js
 displayCars: function displayCars(cars) {
        let $fragment = document.createDocumentFragment();
        let $trowChildren;
        cars.forEach(function (car) {
          let $trow = document.createElement("tr");
          let $tdImage = document.createElement("td");
          $tdImage.className = "image";
          let $image = app.getImage(car.image);

          let $tdMakeModel = document.createElement("td");
          let $tdYear = document.createElement("td");
          let $tdPlate = document.createElement("td");
          let $tdColor = document.createElement("td");
          let $tdDelete = document.createElement("td");

          $tdDelete.addEventListener("click", app.deleteCar, false);

          $tdImage.appendChild($image);
          $tdMakeModel.textContent = car.makeModel;
          $tdYear.textContent = car.year;
          $tdPlate.textContent = car.plate;
          $tdColor.textContent = car.color;
          $tdDelete.appendChild(app.getDeleteIcon());

          $trowChildren = app.addTableData($trow, [
            $tdImage,
            $tdMakeModel,
            $tdYear,
            $tdPlate,
            $tdColor,
            $tdDelete,
          ]);

          $fragment.appendChild($trowChildren);
        });
        
        $fragment.removeChild($trowChildren);
        $fragment.appendChild($trowChildren);
        return $fragment;
      },
```

Link do repositório:
https://github.com/Gilmara-Git/_cars4Sales/blob/master/scripts/main.js

Obrigada 
Gilmara

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! O ponto que eu tinha comentado seria sobre fazer uma atualização [nessa linha](https://github.com/Gilmara-Git/_cars4Sales/blob/master/scripts/main.js#L63).

Ao invés de usar o `window.location.reload()`, você poderia simplesmente pegar o `$tbody`, e usar o `innerHTML` passando uma string vazia antes de fazer a chamada do `app.allCars()`.

Como a tag `<tbody>` vai sempre estar na tela, você pode declarar a variável que pega essa tag lá no início do arquivo, para não precisar redeclarar a variável quando for usar ela de novo, e usar `$tbody.innerHTML = ''` antes de chamar `app.allCars()`. Fazendo isso, você limpa todo o `tbody` antes de preencher ele com os dados que virão do seu request `GET` no servidor =)

Deu pra entender a ideia? =)

**Comment by Gilmara-Git** [comment]
Ahh, entendi e já testei. 
Ficou ótimo agora. 
Eu estava incomodada com isso Fernando.
Obrigada mais um vez pela atenção e ajuda!

Abraços, 
Gilmara

**Comment by fdaciuk** [comment]
Sem problemas @Gilmara-Git! Qualquer dúvida, só avisar :D
