### ISSUE TITLE
Dúvida sobre certificado do curso e sobre 'slack'

### ISSUE THREAD

**Issue by Gilmara-Git** [da2k/curso-javascript-ninja#9680]
Oi @fdaciuk , 

Primeiramente, gostaria de agradecer pelo excelente curso, didática e apoio de sempre!
Quero só te contar um pouquinho de como cheguei em teu curso.
Durante boa parte do início da pandemia, fiz um bootcamp para iniciantes e  senti que precisava aprender javascript, pois me tomava muito tempo para entender o JS.
Uma amiga (Ilda Neta)  me recomedou seu curso e fui intercalando as atividades do curso, com tralhalho e outras aplicações que estava desenvolvendo em paralelo. Hoje me sinto muito mais confiante  e preparada para seguir adiante. 
Sei que dúvidas sempre surgirão e saber que posso contar com o conteúdo do curso e com você é muito gratificante.
As 'issues' abertas também ajudam muito (eu tive um problema para gerar o arquivo de caminho do "source map" e encontrei a solução em uma das issues abertas anteriomente) .

Primeira pergunta:
Lendo as issues, vi tem um grupo do slack.
Se o grupo ainda existir gostaria de participar.
Meu email é : `**@**`

Segunda pergunta:
Eu gerei meu certificado e notei que tem um espaço em branco no meio.
Lembro que na aula final você mencionou algo das atividades que enviamos. 
Por um acaso o certificado deveria mostar alguma percentagem de conclusão das atividades ?
Ou seria da forma como abaixo mesmo ?

![image](https://user-images.githubusercontent.com/66445234/131046046-b14b4b73-679f-4010-ac4d-2b86578a7412.png)

https://github.com/da2k/curso-javascript-ninja/issues/5624

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Gilmara-Git! Sensacional sua história! Com certeza pode contar comigo sempre que precisar sim \o/

Não temos mais o Slack, pois migramos para um servidor no Discord. Vou te mandar o link do convite via mensagem privada lá pela Udemy, ok? =)

Sobre o certificado: como o curso foi criado antes da Udemy, eu gerava o certificado à partir dos Pull Requests enviados pelos alunos. Agora é a Udemy que gera o certificado, então esse espaço em branco é normal, esse é o layout novo deles para o certificado =)

Parabéns por concluir o curso! Conte comigo sempre que precisar :D

**Comment by Gilmara-Git** [comment]
Oi @fdaciuk ,

Beleza, eu espero seu convite lá  na Udemy.
Valeu por esclarecer sobre o certificado!
É uma ótima sensação terminar,  e ter todo este conteúdo disponível para revisões é uma tranquilidade!
Mais um vez parabéns pelo curso.
Obrigada
Gilmara
