### ISSUE TITLE
problema autenticando github usando 'push' dentro do terminal

### ISSUE THREAD

**Issue by 2swamped4u** [da2k/curso-javascript-ninja#9681]
Oi Fernando, tudo bom?

Ta sendo dificil criar o branch de 'challenge-02' dentro do terminal seguindo os comandos do video (minuto 09:10) sobre desafio da semana 02. Tirei uns screenshots para voce ver: 
 
![github_problema](https://user-images.githubusercontent.com/69281697/131125768-0a0ed314-2b9d-4073-ae0d-db4513c94dd6.png)
![Screenshot from 2021-08-27 09-22-09](https://user-images.githubusercontent.com/69281697/131126716-de429814-8980-44cf-9197-8327a2fba2ab.png)

Tambem ja autorizei a authenticacao de dois fatores, mas ainda ta dando problema dentro da terminal para criar esse branch, depois de colocar os meus credencias. Voce sugere que eu so criasse o branch dentro do github e continuar assim mesmo? 

Muito obrigado pelo seu tempo.

Javier Sanchez (2swamped4u)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @2swamped4u! Parece que o GitHub não suporta mais a autenticação com senha, quando você clona um repositório usando HTTPS. Eu realmente estava por fora disso, mas para resolver é bem simples (principalmente porque você está no Linux):

Se você ainda não tem uma chave SSH, crie uma com o comando:

```
ssh-keygen -t rsa -b 4096 -C "SEU_EMAIL_DO_GITHUB"
```

Do comando acima, subsitua o `SEU_EMAIL_DO_GITHUB` pelo seu email cadastrado no GitHub.

Você pode criar uma senha para a chave se quiser, mas como é apenas para usar local, não vejo necessidade, então pode só ir confirmando os passos com ENTER.

Feito isso, copie o conteúdo do arquivo `~/.ssh/id_rsa.pub` (**muito importante pegar do arquivo que termina com .pub**) e então coloque essa chave na sua conta do GitHub. O passo-a-passo de como fazer está [nesse link]9https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).

Finalizada a etapa acima, você só precisa verificar a sua conexão com o GitHub. Rode o seguinte comando no seu terminal:

```
ssh -T git@github.com
```

Esse comando deve te dar uma mensagem de boas vindas. Se isso acontecer, você estará corretamente conectado ao GitHub \o/

Aí você pode clonar o repositório usando `SSH` mesmo, que vai funcionar sem problemas =)

Se tiver qualquer dificuldade, me avise que vou te ajudando, ok? =)
