### ISSUE TITLE
Desafio 01 - Pull

### ISSUE THREAD

**Issue by leandrofsp** [da2k/curso-javascript-ninja#969]
Fiz o commit do challenge-01 e depois fui para o repo do curso e não me apareceu a opção de pull request. como devo proceder?  Abs

**Comment by fdaciuk** [comment]
Fala @leandrofsp, tudo certo? =)

As vezes demora um pouco pra aparecer na página principal do curso. Tente acessar [essa url](https://github.com/da2k/curso-javascript-ninja) pra ver se aparece a opção de enviar o pull request.

Se ainda assim não funcionar, pode fazer direto [por aqui.](https://github.com/da2k/curso-javascript-ninja/compare/master...leandrofsp:challenge-01?expand=1)

Qualquer dúvida me avise =)

**Comment by leandrofsp** [comment]
Parece que pelo outro modo foi.

Obrigado pelo pronto atendimento.
abs.

**Comment by fdaciuk** [comment]
Nada =)
Precisar de algo grita ae :grin:
