### ISSUE TITLE
Aula 02 - Dúvida no desafio da semana.

### ISSUE THREAD

**Issue by leandrofsp** [da2k/curso-javascript-ninja#973]
No exercicio abaixo é para ser feito apenas com o conteúdo das aulas 01 e 02 ou vai mais alem? pq estou quebrando um pouco a cabeça pra resolver rs

Poderia da alguma luz?

valeu.

/*
Crie uma função com as seguintes características:
1. A função deve receber 3 argumentos.
2. Se somente um argumento for passado, retorne o valor do argumento.
3. Se dois argumentos forem passados, retorne a soma dos dois argumentos.
4. Se todos os argumentos forem passados, retorne a soma do primeiro com o segundo, e o resultado, dividido pelo terceiro.
5. Se nenhum argumento for passado, retorne o valor booleano `false`.
6. E ainda, se nenhuma das condições acima forem atendidas, retorne `null`.
*/

**Comment by fdaciuk** [comment]
Opa @leandrofsp! Isso mesmo, os desafios devem ser resolvidos apenas com o conteúdo das aulas já passadas =)

Tudo o que pede no desafio nós já vimos, mas nem sempre exatamente igual está pedindo no exercício. Por isso se chama **desafio** hehe xD

Mas vou dar uma dica: para verificar se algum argumento existe, você pode testar se ele é igual a `undefined` =)

Se ainda assim não conseguir resolver, envie o pull request com o desafio até onde você conseguiu e comente nele o que ficou complicado de entender que eu vou te ajudando e dando dicas, para que você possa finalizá-lo, ok? =)

**Comment by leandrofsp** [comment]
Entendi.

è isso mesmo desafio kkk, é que não tava achando um norte, mas com a dica vou tentar novamente.

vlw.
abs.

**Comment by fdaciuk** [comment]
haha! Normal, relaxa =)
Qualquer dúvida me avise =)
