### ISSUE TITLE
Pull Request Challenge-01

### ISSUE THREAD

**Issue by alessandroapolinario** [da2k/curso-javascript-ninja#9734]
Bom dia, Professor.
Eu terminei os exercícios do Challenge-01 e em seguida eu fiz o commit na branch Challenge-01, conforme demonstrado no seu vídeo. No entanto, quando eu mudei para o seu repositório para fazer o Pull Request, eu não consigo visualizar o meu commit. Já fiz 4 commits do meu repositório e quando eu acesso o seu repositório eu não consigo fazer o pull request.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @alessandroapolinario! O seu PR já foi feito, ele está aqui:
https://github.com/da2k/curso-javascript-ninja/pull/9735

=)
