### ISSUE TITLE
Bug Challenge-04 Adicionando número de pessoas 

### ISSUE THREAD

**Issue by gabriel-elesbao** [da2k/curso-javascript-ninja#9736]
```js
carro.adicionarPassageiros = function(pessoas){
  let totalPessoas = carro.quantidadePessoas + pessoas

  if(carro.quantidadePessoas === carro.assentos){

     return "O carro já está lotado!"
  }

    carro.quantidadePessoas += pessoas
    return `Já temos ${totalPessoas} pessoas no carro!`

}


carro.adicionarPassageiros(1)
carro.adicionarPassageiros(1)

console.log(carro.adicionarPassageiros(4))

```
Está exatamente  como criada em Aula, porém, notei um bug, ao chamar dessa forma acima, a saída continua somando
```
Já temos 6 pessoas no carro!

```
Era pra ele dar a mensagem que está lotado, porém, se for adicionando aos poucos, como na aula, tudo ocorre certo, por exemplo.
```js
carro.adicionarPassageiros(2)
carro.adicionarPassageiros(1)
carro.adicionarPassageiros(2)

console.log(carro.adicionarPassageiros(1))
```
Ai ele dá a mensagem certa, que está lotado, porque isso ocorre ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gabriel-elesbao! A solução mostrada na aula é [essa aqui](https://github.com/da2k/curso-javascript-ninja/tree/desafios-resolvidos/challenge-04). Tem algumas verificações a mais que nesse seu código, por isso o seu não está trazendo o resultado como esperado =)
