### ISSUE TITLE
problema com o clone do repositorio

### ISSUE THREAD

**Issue by jeffonis** [da2k/curso-javascript-ninja#9753]
boa noite prof, eu fui realizar a aula 13 do curso de javascript, mas quando fui fazer o clone do repositorio, ele ficou com esse erro
![image](https://user-images.githubusercontent.com/62406460/139150350-007f6b29-1d6a-4c06-869d-05fa5717ca39.png)

o senhor saberia dizer qual é o problema?
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jeffonis! Você chegou a fazer a configuração da chave SSH no seu sistema, e subiu essa chave no GitHub?

**Comment by rodinogueira** [comment]
git clone https://github.com/da2k/curso-javascript-ninja.git
clone com https.
o comando para listar o diretorio no linux é ls. Use ls para listar no MINGW64

**Comment by jeffonis** [comment]
> Oi @jeffonis! Você chegou a fazer a configuração da chave SSH no seu sistema, e subiu essa chave no GitHub?

 então, como faço essa configuração?

**Comment by rodinogueira** [comment]
https://docs.github.com/pt/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Faça assim !

**Comment by fdaciuk** [comment]
Obrigado pela ajuda @41RDG6BR! Se tiver alguma dificuldade para seguir o tutorial para o seu sistema @jeffonis, me deixe saber =)

**Comment by jeffonis** [comment]
obrigado @41RDG6BR consegui seguir o tutorial, mas agora tive outro problema @fdaciuk (segue imagem abaixo)
![image](https://user-images.githubusercontent.com/62406460/139326770-28178a50-2419-465e-8663-6aaddd2fab22.png)
não sei o que pode ter acontecido :/

**Comment by fdaciuk** [comment]
O problema é o mesmo @jeffonis! Como você está usando seu origin com `https`, use o upstream com `https` também.. se usar com `git@github...` vc precisa ter a chave SSH configurada =)

**Comment by jeffonis** [comment]
@fdaciuk aaa sim, entendi
consigo fazer essa alteração do upstream?

**Comment by jeffonis** [comment]
@fdaciuk agora consegui alterar ambos, mas continua o erro, eu ja havia feito essa chave ssh
então terei que faze-la novamente?

![image](https://user-images.githubusercontent.com/62406460/139329363-f93d0860-6f33-41da-82da-55d2cc51fdc7.png)

**Comment by jeffonis** [comment]
@fdaciuk com os dois https foi, posso seguir assim?

![image](https://user-images.githubusercontent.com/62406460/139329720-21dccb5f-1dc2-4b2d-a15e-43a498951cde.png)

**Comment by fdaciuk** [comment]
É isso aí! Ou você deixa os dois com `git@github...` e configura o SSH, ou deixa como `https` pra não precisar configurar o SSH =)

Mas pode deixar assim sim =)

**Comment by jeffonis** [comment]
outra duvida tambem @fdaciuk 
na videoaula, o sr mostra só o challenge dois na pesquisa dos arquivos, mas aqui ta mostrando todos, teria algo errado ? 

![image](https://user-images.githubusercontent.com/62406460/139330263-5ef67a3e-2821-432e-873b-fb416c66eb26.png)

**Comment by fdaciuk** [comment]
Está certinho! É que enquanto eu estava gravando o curso, os desafios ainda não estavam completos. Agora já tem todos os desafios no repositório, então tá tudo certo :D

**Comment by jeffonis** [comment]
@fdaciuk  muito obrigado pela atenção <3

**Comment by fdaciuk** [comment]
Tamo junto! Qualquer coisa, só avisar! :D
