### ISSUE TITLE
Dúvida a respeito no exercício 03 do challenge-22

### ISSUE THREAD

**Issue by sou-gabriel** [da2k/curso-javascript-ninja#9757]
Oi Daciuk, tudo bom?

Estava realizando o challenge-22 e não entendi muito bem como o reduce estava iterando sobre o array, sendo mais específico, achei muito confuso executar a instrução: ```Array.prototype.reduce.call```, a partir daí, decidi recriar o método ```reduce``` do zero para tentar entender melhor o problema e cheguei na seguinte solução:

```js
Array.prototype.reduce = function reduce (reducingFunction, initialValue) {
  var accumulator = initialValue
  
  this.forEach(function (item) {
    accumulator = reducingFunction(accumulator, item)
  })

  return accumulator
}
```

A resolução que eu vi em aula foi algo parecido com isto:
```js
  function sum () {
    console.log(arguments)

    return Array.prototype.reduce.call(
      arguments,
      function (accumulator, item) {
        console.log(accumulator, item, this)
        return Number(accumulator) + Number(item)
      },
      0      
    )
  }
```
Agora vem a dúvida: Daciuk, no momento que você invocou o método ```call``` no código acima você especificou que ```arguments``` será o valor do this dentro do ```reduce```, então nativamente o método reduce pega esse valor do ```this``` e itera sobre ele até reduzí-lo a um único valor, e com isso a implementação do ```reduce``` que fiz ali encima seria maaaaaais ou menos o que ocorre por baixo dos panos quando eu uso o ```reduce``` nativo da linguagem?

Me perdoe se não ficou muito claro.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @sou-gabriel! É exatamente isso meu caro, mandou bem :D
