### ISSUE TITLE
contar letras

### ISSUE THREAD

**Issue by maduschw** [da2k/curso-javascript-ninja#9775]
eu não consegui fazer oq a função pede , como eu poderia melhorar ele pra fazer oq é pedido na questão pfv.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @maduschw! Consegue me dizer qual exercício de qual aula você está tendo dificuldades?

**Comment by fdaciuk** [comment]
@maduschw vou fechar a issue, mas se você ainda tiver dúvidas, fique à vontade para perguntar :)
