### ISSUE TITLE
Video 92 - Objeto arguments

### ISSUE THREAD

**Issue by alexandre1202** [da2k/curso-javascript-ninja#9782]
Oi Fernando.

Por favor, o que estou fazendo de errado para não conseguir imprimir o `arguments[0]`, tal como no seu exemplo?

Meu código:

```
(function() {
    function MyFunctionArguments(name, address, age) {
        this.name = name;
        this.address = address;
        this.age = age;
    
        this.addAge = function addAge() {
            console.log('arguments', arguments);
            console.log('arguments[0]: ', arguments[0]);
            this.age += arguments[2];
            return this;
        };
    }
    var myFunctionArguments = new MyFunctionArguments('Pedro', 'Av Paulista 2000', 77);   
    myFunctionArguments.addAge();
})()

```

Console no Node:
![Screen Shot 2021-12-27 at 19 23 04](https://user-images.githubusercontent.com/8005205/147510914-90eeb349-fc31-465a-bcf7-864cafdbb845.png)

Console no navegador:
![Screen Shot 2021-12-27 at 19 24 57](https://user-images.githubusercontent.com/8005205/147510986-ac15ce91-d48e-41b4-8963-4ed0a7739b94.png)

@fdaciuk

**Comment by Alexandre1202** [comment]
Desculpa... pode ignorar

Vi que o problema era a linha abaixo:
`myFunctionArguments.addAge();`

o correto é 
`myFunctionArguments.addAge;`

obviamente pois eu preciso chamar a property que chama a função addAge(). Até porque ela não é visivel fora do escopo de MyFunctionARguments()....

**Comment by fdaciuk** [comment]
Opa! Você não passou nenhum argumento para a função `addAge` :)

**Comment by alexandre1202** [comment]
Fiquei com duvida no seu exemplo no video 93. 

Ficou claro que é o seu exemplo está fazendo um encadeamento de chamadas de uma função que retorno um objeto e depois você chamou uma função (getAge()) dessa função que foi retornada pela primeira função.
A função addAge() não recebe parâmetro então como pode funcionar o seu :
`fernando.addAge(2).getAge();
`

**Comment by alexandre1202** [comment]
> Opa! Você não passou nenhum argumento para a função `addAge` :)

Sim mas essa função não tem parâmetro. certo?

**Comment by fdaciuk** [comment]
A `addAge` tem.. a `getAge` que não :)

**Comment by alexandre1202** [comment]
Ajustei aqui passando o parâmetro na chamada da função 
    `myFunctionArguments.addAge(2);`
e agora entendi...

então mesmo que na assinatura da função addAge() não tem um parâmetro, como podemos ver aqui:
![Screen Shot 2021-12-27 at 20 22 38](https://user-images.githubusercontent.com/8005205/147513271-018da29b-9072-4bac-8aff-b0f90c5fb008.png)

mas se passarmos o parâmetro então ele identifica que foi passado um parâmetro... 

certo?

**Comment by fdaciuk** [comment]
Isso mesmo @Alexandre1202! O `arguments` é um objeto especial que só existe dentro de funções.. e através desse objeto, você tem acesso à todos os argumentos passados para a função, ainda que na assinatura da função você não espere nenhum argumento :)

**Comment by alexandre1202** [comment]
Olá Fernando @fdaciuk 

Excelente!  a explicação do `arguments` ficou bem legal. Muito obrigado
Cara... eu trabalho com desenvolvimento em Java, Spring e frameworks populares (Apache Commons, HIbernate, Jackson, MapStruct, etc) e sempre tive vontade de aprender outra linguagem.
Estou empolgado com JS e dedicando bastante tempo nesse curso porque sei que é a base para trabalhar com NodeJS, ExpressJS, Krakenjs e Typhon.
Agradeço muito se puder compartilhar se é verdade que você está fazendo um curso de NodeJS.

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Que massa que está curtindo o curso :D 
Tenho pretensão de fazer um curso de Node.js, mas não vou conseguir separar tempo hábil para fazer isso tão cedo.

Por esse motivo, eu estou fazendo [lives na Twitch](https://twitch.tv/fdaciuk) diariamente, das 7h às 8h30 da manhã, falando sobre vários assuntos, mas principalmente sobre JavaScript, TypeScript, Node.js e React, que são assuntos que domino, além de estudar coisas novas ao vivo, como Elixir, Svelte,  Remix, etc =)

Inclusive, eu mostrei como criar uma API completa com Node.js + TypeScript usando o paradigma de programação funcional, organizando a arquitetura da aplicação com o pattern "Ports & Adapters" (também conhecido como "Arquitetura Hexagonal").

Os vídeos das lives estão no meu canal do YouTube, [nessa playlist](https://www.youtube.com/playlist?list=PLr4c053wuXU_2sufpBUxu3bLRBbyWt4lX) =)
