### ISSUE TITLE
Video 153 - Mais eventos por elemento

### ISSUE THREAD

**Issue by alexandre1202** [da2k/curso-javascript-ninja#9784]
Oi Fernando.

Agradeço se por favor, você complementar se realmente o motivo de utilizarmos o '[data-js="elemento"]'  é realmente devido a algumas implicações de referenciarmos um id do elemento HTML, de dentro de um código JavaScript?
Estou inseguro na minha lembrança.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! É exatamente por isso! Vamos deixar o uso de IDs apenas para campos de formulário, e para criação de âncoras, por questões de acessibilidade. Ao manipular DOM sem frameworks, vamos sempre usar `data-*` =)
