### ISSUE TITLE
challenge-02 

### ISSUE THREAD

**Issue by eiericksilva** [da2k/curso-javascript-ninja#9796]
Pode me explicar por que o código só lê o IF ?

mesmo enviando os 3 parâmetros ele não faz o cálculo.

![Sem título](https://user-images.githubusercontent.com/93824705/148125834-e3046322-d594-4519-b83e-438535f8706f.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @eiericksilva! O cálculo está sendo feito, ele apenas não está sendo exibido, pois você simplesmente chamou a função, mas não fez nada com o resultado :D 

Se você executar a função, passando o resultado para a o método `log` de `console`, assim como você fez na segunda chamada, o resultado será exibido no console :)

**Comment by eiericksilva** [comment]
Obrigado! 
Armazenei numa variável o resultado da função e chamei essa variável no console. Funcionou certinho!

**Comment by fdaciuk** [comment]
Também funciona! Qualquer dúvida, só avisar :D
