### ISSUE TITLE
VIDEO 28 - Revisão da semana 4# parte 3 

### ISSUE THREAD

**Issue by pabloh25** [da2k/curso-javascript-ninja#9827]
```js
if (carro.quantidadePessoas === carro.assentos && totalPessoas >= carro.assentos) {
    return 'O carro já está lotado!';
  }

```

Fernando, não entendi como que através da verificação no código mencionado a cima ele aceita o valor (-4) e remove pessoas de dentro do carro ? seria mas correto criar um novo método pra isso ? digo esse por que sou novo em programação e queria entender melhor como isso funciona.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pabloh25! Na verdade, essa verificação não remove pessoas do carro, ela simplesmente garante que, se o número total de pessoas passadas (quantidade recebida via argumento da função, somando com a quantidade de pessoas que já estão no carro) for maior que a quantidade de assentos no carro; e todos os assentos já estiverem preenchidos, aí ele vai travar nessa mensagem do `return`.

O que remove as pessoas é a expressão após o próximo `if`:

```js
carro.quantidadePessoas += numeroPessoas;
```

Como o número de pessoas é um valor negativo, se houverem 5 pessoas no carro, e você passar `-4` via argumento da função, o cálculo será `5 + (-4). Quando você tem dois sinais diferentes juntos (positivo e negativo), o que fica é o negativo. Então o resultado vai ser o valor de `5 - 4 = 1`.

Ou seja: `carro.quantidadePessoas`, que era `5`, vai receber `1` =)

Se for pensar na forma "correta" de fazer as coisas, com certeza escreveríamos uma nova função. Mas o objetivo das primeiras aulas e dos primeiros desafios não é escrever código correto, e sim aprender sobre a linguagem e praticar algoritmos de lógica dentro da programação.

Em aulas futuras vamos falar de melhores práticas, mas não é esse o momento. 

Por isso, curta o aprendizado, e pratique bastante. É assim que você vai dominar a linguagem :D 

E sempre que tiver dúvidas, fique muito à vontade para perguntar, ok? =)

**Comment by pabloh25** [comment]
Show, obrigado pelo retorno. 

Agora entendi que por conta da declaração ele faz esse processo de positivo com negativo, ficou mais claro, sim sim eu entendi que o intuito e aprender e praticar conforme as aulas, é que ficou aquela pulga atrás da orelha de como isso funcionava.


```
carro.quantidadePessoas += numeroPessoas;
```

**Comment by fdaciuk** [comment]
Boa @pabloh25! Qualquer dúvida, só avisar :D
