### ISSUE TITLE
[Challenge-13] Sobre os métodos every e some

### ISSUE THREAD

**Issue by diogorodrigues** [da2k/curso-javascript-ninja#985]
Olá @fdaciuk !
Estou abrindo essa issue apenas para dizer que hoje implementei esses métodos em um projeto que estou desenvolvendo. A satisfação foi muito grande. Valeu!!

Abs!!

**Comment by fdaciuk** [comment]
haha! Que legal @diogorodrigues! Parabéns! :dancer: :dancer: :sparkles:
