### ISSUE TITLE
COMPARE & PULL REQUEST - ENVIAR DESAFIO

### ISSUE THREAD

**Issue by EduardoGuedes27** [da2k/curso-javascript-ninja#9861]
Ola Boa noite, sou o Eduardo Guedes e estou na primeira aula. 

estou tendo dificulde em enviar o arquivo como mostradodo no video **'7. Desafio da semana #01'** na primeira aula
no minuto **6.37** voce fala para clicar no botão **COMPARE & PULL REQUEST** porem na versão atual do GitHub eu não estou encontrando esta função. 

![image](https://user-images.githubusercontent.com/102256817/159824342-1ac99fd1-9ae8-4d94-aaa3-98a258b5dea2.png)

@fdaciuk

**Comment by EduardoGuedes27** [comment]
localizei a função... agradeço

**Comment by fdaciuk** [comment]
Oi @EduardoGuedes27! Que bom que deu certo :D 

Os Pull Requests não são mais obrigatórios, mas você pode fazer se quiser, ok? O importante é resolver os desafios no seu PC, pois é a prática que importa!

Qualquer dúvida, só avisar :D
