### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by decotaca** [da2k/curso-javascript-ninja#9896]
Professor quando eu tento fazer o procedimento de git clone, aparece essa msg abaixo.

Cloning into 'curso-javascript-ninja'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

- Minha dúvida é, como faço para resolver isso?
*primeira vez que estou usando o github, desculpa ai se estou fazendo errado para enviar a pergunta.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @decotaca! Não precisa pedir desculpas não, está certinho o uso :D 

Sobre a criação do repositório, não precisa se preocupar em clonar o repositório e enviar os pull requests: o importante é você consegue resolver os desafios, ainda que só na sua máquina mesmo, ok?

Pra fazer isso sem precisar clonar o repositório, você só precisa ir até a página inicial do repositório, clicar no botão verde "Code", e então clicar em "Download ZIP".

Fazendo isso, você vai baixar um zip com todos os desafios do repositório pra você resolver, ok? :D 

Me deixe saber se deu tudo certo! E qualquer dúvida, fique sempre muito à vontade para perguntar :D

**Comment by fdaciuk** [comment]
@decotaca vou fechar a issue, mas se você ainda tiver dúvidas, fique à vontade para perguntar :)
