### ISSUE TITLE
Função books

### ISSUE THREAD

**Issue by pabloh25** [da2k/curso-javascript-ninja#9908]
Professor, fiquei com uma duvida, na verdade acho que entra em boas praticas, eu coloquei o nome dos livros como o nome em si do objeto e declarei as props, porem fazendo a revisão do exercício que tem uma das atividades de declarar o nome do livro, me deparei que não conseguia converter o nome em string, fazendo a revisão do exercício vi que tem como declarar como string, como isso é possivel ? gerou essa duvida ate pq nas aulas não me atentei se tem ou não algo que fala 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pabloh25! Ali foi um exemplo pra mostrar que as chaves de um objeto são sempre strings! Ainda que você escreva as chaves de um objeto sem as aspas, o interpretador da linguagem sempre vai entender as chaves como strings, por isso é possível colocar, entre aspas, caracteres que são inválidos como identificadores para variáveis de funções :)

Era essa a sua dúvida?

**Comment by pabloh25** [comment]
> Oi @pabloh25! Ali foi um exemplo pra mostrar que as chaves de um objeto são sempre strings! Ainda que você escreva as chaves de um objeto sem as aspas, o interpretador da linguagem sempre vai entender as chaves como strings, por isso é possível colocar, entre aspas, caracteres que são inválidos como identificadores para variáveis de funções :)
> 
> Era essa a sua dúvida?

Isso era essa a duvida, muito obrigado pelo retorno.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D
