### ISSUE TITLE
Aula 187. DOM - innerHTML - Problemas de segurança

### ISSUE THREAD

**Issue by pgstudies22** [da2k/curso-javascript-ninja#9916]
Olá @fdaciuk!

Recentemente, vi [uma live](https://youtu.be/Sez1wYdTVWQ?t=3393) em que vc menciona que no Front-end, não há segurança. E que segurança deve ser garantida no Back-end.

Isso significa que, por exemplo, usar `textContent` ao invés de `innerHTML`/`insertAdjacentHTML` e usar uma lib de sanitização como a DOMPurify no Front-end é perda de tempo?

A propósito, suas lives são monstras professor. Muito obrigado pela tonelada de conhecimento valioso que vc compartilha 🙏🏻

**Comment by fdaciuk** [comment]
Oi @pgstudies22! Não é perda de tempo não! O que eu quis dizer com "não há segurança no frontend", é que tudo ali é público, então você deveria cuidar ao usar alguma informação que pode ser privada em seu projeto frontend!

Sobre o uso do `textContent`, DOMPurify, etc., você deveria usar sim, não é perda de tempo não! O uso dessas ferramentas é para tratar código que veio de alguma fonte que pode não ser confiável: não foi você que escreveu o código, ele veio de algum lugar de forma dinâmica, e você precisa renderizar esse conteúdo na tela para o usuário.

Para garantir que nenhum código malicioso será executado quando sua aplicação rodar, usar o DOMPurify, e evitar usar diretamente um `innerHTML` são boas práticas que ajudam sim a manter sua aplicação mais segura :)

Que bom que está curtindo as lives \o/

**Comment by pgstudies22** [comment]
Show professor. Ficou mais claro agora, então vou fechar a issue.

Muito obrigado pela resposta =)
