### ISSUE TITLE
MDN x w3schools

### ISSUE THREAD

**Issue by pgstudies22** [da2k/curso-javascript-ninja#9924]
Olá @fdaciuk, tudo em paz? =)

Gostaria de uma opinião...

Qual é o problema do `w3schools` que vejo o pessoal criticar tanto?

Tipo, vejo que pra quem está iniciando na área, ele tem uma aderência melhor do que o MDN, por exemplo...

Vc acha que uma plataforma pode substituir a outra no começo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pgstudies22! Tudo certo meu caro! :D 

O w3schools foi problemático há alguns anos atrás, pois, apesar de ser muito didático, eles ensinavam muitas coisas erradas lá.

Na época foi criado [um manifesto](https://www.w3fools.com/) para as pessoas não usarem mais o w3schools, e ele acabou ficando com essa má fama desde então, apesar de hoje em dia já estar muito melhor.

Então hoje em dia não vejo problemas estudar por ele, mas como eu não acompanho muito o que acontece por lá, minha recomendação para estudos de JS é sempre a MDN, pois essa é praticamente a documentação oficial do JavaScript, já que é mantida pela própria comunidade :)

**Comment by pgstudies22** [comment]
Oloco! Agora ficou bem claro qual foi a parada do w3schools hahah.

Curto o MDN tb. É a fonte da verdade xD

Acho que o que pega no MDN pra quem está iniciando são 2 coisas:

1. Links com termos desconhecidos nos parágrafos. 

Isso faz com que haja uma "tentação" de sair clicando e cada link. Um labirinto de links, hahah. Só no primeiro parágrafo da pág. de const, há links para as págs object e array. Mas talvez, quem esteja pesquisando sobre const ainda não saiba o que são objetos e arrays (e talvez ainda não seja o momento de saber...).

![image](https://user-images.githubusercontent.com/107188587/180665057-e09e893f-6870-4ad5-b6f0-f908b8b31275.png)

---

Pra agravar um pouco mais a situação, inseriram um try/catch no demo:

---

![image](https://user-images.githubusercontent.com/107188587/180665212-ecb33e31-80f8-4a87-a223-5184233c451e.png)

---

2. Syntax

Um iniciante não tem a menor ideia do que significam os colchetes e vírgulas nos blocos de syntax. E em nenhum lugar perto dele há instruções explicando o que esses caracteres significam....

---

![image](https://user-images.githubusercontent.com/107188587/180665236-b5644cc6-87a7-422a-9b0c-f59b93e707e8.png)

---

Por isso, talvez o ideal pra quem está começando seja focar nos guides, né?

@fdaciuk

**Comment by fdaciuk** [comment]
> Por isso, talvez o ideal pra quem está começando seja focar nos guides, né?

Exatamente, para isso servem os guias! As outras áreas são páginas de consulta mesmo: pra quando você já conhece um pouco da linguagem, e está com dúvida de algo específico, ou quer aprender algo novo, mas já tem uma base, um pré-conhecimento da linguagem :)

Documentação dificilmente vai ser o lugar para uma pessoa iniciando do completo zero. Esse perfil de pessoas precisa de um guia para saber por onde seguir. Esse foi o objetivo principal quando eu criei esse curso :)

**Comment by pgstudies22** [comment]
Faz total sentido! =D

Muito obrigado Daciuk. Vou tomar a liberdade de fechar a issue pq ficou bem claro =)

**Comment by fdaciuk** [comment]
Perfeito @pgstudies22! Qualquer dúvida, fique à vontade para perguntar :D
