### ISSUE TITLE
Programa com URLs

### ISSUE THREAD

**Issue by pgstudies22** [da2k/curso-javascript-ninja#9953]
Olá @fdaciuk, tudo bem? 

Quero criar um programa que a cada vez que recebe um valor no input, pegue uma URL qualquer, concatene esse valor recebido, em seguida abra em outra página.

Se a página com essa URL modificada já estiver aberta ou já existir, só troque de guia pra ela. Se não, abra uma guia nova. 

Eu consegui criar a função para isso acontecer da primeira vez, mas sempre que o valor do input muda ou é o mesmo, ela sempre abre uma nova guia. Segue abaixo meu código:

```html
<form>
  <input name="input" type="text" />
</form>
```

```javascript
const form = document.querySelector('form')

form.addEventListener('submit', event => {
  event.preventDefault()
  const inputvalue = event.target.input.value

  window.open(`https://google.com/${inputvalue}`, '_blank')
})
```

Poderia me me dar um help?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pgstudies22! Se eu entendi bem o que vc quer fazer, não rola fazer isso, porque o seu JS só tem acesso à aba em que o seu código está rodando. Não tem como você ter acesso às outras abas abertas no navegador :)

**Comment by pgstudies22** [comment]
Entendi... Pelo que pesquisei, por motivos de segurança, não é tão simples saber se alguma página específica está aberta no navegador do usuário.

Vi que talvez é possível implementar uma extensão para o navegador que faça isso..

Com uma extensão, eu teria acesso ao `windows.getAll()`:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/getAll

Mas claro, precisaria da permissão do usuário para ter acesso a esse tipo de informação.

Fora que implementar extensões é bem chatinho xD

Mas é isso, obrigado @fdaciuk, dúvida sanada. Pode fechar a issue, se quiser =)
