### ISSUE TITLE
Como limitar a quantidade de vezes que bato em determinados endpoints

### ISSUE THREAD

**Issue by pgstudies22** [da2k/curso-javascript-ninja#9964]
Olá @fdaciuk, tudo bem?

Estou desenvolvendo uma aplicação que preciso limitar a quantidade de vezes que bato em determinados endpoints de uma API, porém nao estou conseguindo fazer isso direto.

A estrutura dela é o seguinte... front end onde o cliente pode solicitar os dados que precisa chama uma api minha passando tudo que precisa e este meu backend em node chama as APIs que preciso limitar a quantidade de chamadas por minuto...

Talvez com axios possa resolver, na parte de [timeout](https://axios-http.com/docs/config_defaults)...

Só que pra saber disso percebi que preciso entender outra coisa...

Por exemplo, se duas pessoas fizerem uma requisação ao mesmo tempo para a minha api, elas serão executadas em paralelo ou uma depois da outra?

Se for em paralelo eu confirgurar o timeout acaba que nao vai resolver, pq amabas vao esperar ao mesmo tempo e bate na api que tenho que limitar ao mesmo tempo kkk

Preciso entender tbm se a cada chamada da api todas as variaveis são recriadas...

Poderia me dar um help?

**Comment by fdaciuk** [comment]
Oi @pgstudies22! O que você precisa, na verdade, é de um cache! Provavelmente você quer fazer isso pois está batendo muitas vezes no banco de dados, e isso está deixando os requests lentos, é isso?

Se for esse o caso, requests do tipo GET você consegue cachear facilmente: como são apenas buscas de dados, você pode colocar um banco Redis na frente e fazer o seguinte: quando acontecer um request, você bate no seu banco, pega os dados e salva no Redis.

Na próxima requisição, você verifica primeiro se existem dados no Redis antes de bater no banco. Se houver, vc retorna os dados do Redis, que estão cacheados.

Isso vai reduzir consideravelmente as suas chamadas ao banco de dados, e vai deixar as respostas muito mais rápidas, pois o Redis trabalha com dados estáticos :)

É importante também levar em consideração quanto tempo os dados deveriam ficar no cache, com base no tempo em que esses dados são atualizados no seu banco, pra você mostrar para o seu usuário final, sempre que possível, o dado mais recente.

Infelizmente esse não é um assunto que dá pra falar por completo em apenas uma resposta, mas acho que isso já te dá um caminho pra você começar a buscar uma solução para o seu problema =)

**Comment by pgstudies22** [comment]
Massa d+, acho que já as ideias estão começando a clarear =)

O cache do headers na hora de fazer o fetch também é pra esse tipo de situação?

@fdaciuk

**Comment by fdaciuk** [comment]
> O cache do headers na hora de fazer o fetch também é pra esse tipo de situação?

De qual cache de header vc está falando? O cache-control?

**Comment by pgstudies22** [comment]
O que o MDN informa [neste link](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options):

![photo_2022-08-25_23-42-34](https://user-images.githubusercontent.com/107188587/186805346-eca69ece-4df6-4bd9-9fa1-1f4480d940b3.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Ah, ok. Esse é um pouco diferente: basicamente ele serve para definir como o browser vai lidar com o cache para essa request. Aqui tem a doc dessa propriedade:
https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by pgstudies22** [comment]
> ### Aqui tem a doc dessa propriedade:

Pelo que eu entendi, ele faz uma requisição para o servidor SE não tiver em "fresh" que seria um "tempo de vida" ou "idade máxima" setado no navegador para depois verificar no no servidor se houve mudança e aí de fato trazer os dados. 

Meio que isso é o padrão da função fetch, então em teoria, se entendi certo, o que eu teria que fazer sobre o cache já resolveria com a função nativa do JS, não? 

Eu nunca vi exemplo de alguém usando esse tipo de abordagem com fetch, por isso a pergunta...

@fdaciuk

**Comment by fdaciuk** [comment]
> Meio que isso é o padrão da função fetch, então em teoria, se entendi certo, o que eu teria que fazer sobre o cache já resolveria com a função nativa do JS, não?

Mais ou menos.. esse cache é à nível de request. Se o seu servidor não enviar de volta um header sobre o tempo de expiração desse cache, o request será feito de forma completa de qualquer forma.

Então você precisa fazer o cache do lado do backend de qualquer jeito =)

**Comment by pgstudies22** [comment]
Saquei @fdaciuk , muito obrigado! 

Tem uma issue de outra pessoa aberta, mas seu @ não foi marcado, então acho que vc não viu.

Vou abrir uma issue no Repo do React Ninja pq tem haver com o Firebase. 

Novamente, muito obrigado pela força. Vc tem me ajudado bastante! =)

**Comment by fdaciuk** [comment]
> Tem uma issue de outra pessoa aberta, mas seu @ não foi marcado, então acho que vc não viu.

Vou ver, obrigado por avisar!

> Vou abrir uma issue no Repo do React Ninja pq tem haver com o Firebase.

> Novamente, muito obrigado pela força. Vc tem me ajudado bastante! =)

Sempre às ordens meu jovem! Conte comigo para o que precisar :D
