### ISSUE TITLE
Assossiação de classe java objetos

### ISSUE THREAD

**Issue by C0381** [da2k/curso-javascript-ninja#9970]
Eu Não estou conseguindo associar as classes* para o metodo main.  eu queRO associar com outras classes* 
eu nao estou conseguindo resolver 

Residencia, Porta,  veiculo, cargo, Função.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

package associacaoExpandidoFunc;

public class Funcionario {
  private String matricula;
  private String nome;
  private Residencia residencia;
    private Cargo cargo;
    private Veiculo veiculo;

  
    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Residencia getResidencia() {
        return residencia;
    }

    public void setResidencia(Residencia residencia) {
        this.residencia = residencia;
    }

    public Cargo getCargo() {
        return cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }

    public Funcionario(String matricula, String nome, Residencia residencia, Cargo cargo, Veiculo veiculo){
        this.matricula=matricula;
        this.nome = nome;
        this.residencia = residencia;
        this.cargo = cargo;
        this.veiculo = veiculo;
    }
      @Override
    public String toString(){
        return"\nMatricula:" +getMatricula()+
                "\nNome:" +getNome()+
                "\nInformações da Residencia:" +getResidencia()+
                "\nEntrar com o Cargo:" +getCargo()+
                "\nInformações do Veículo:" +getVeiculo();
    }
    
}
++++++++++++++++++++++++++++++++++
package associacaoExpandidoFunc;

public class Residencia {
    private String endereco;
    private Porta porta;

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    
    public Residencia(String endereco, Porta porta){
        this.endereco=endereco;
        this.porta=porta;
    }
    
    
    
    public String toString(){
        return"\nEndereço:" +getEndereco()+
                "\nInformações da Porta:" +getPorta();
        
    }

    public Porta getPorta() {
        return porta;
    }

    public void setPorta(Porta porta) {
        this.porta = porta;
    }
  
}
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
no metodo main esta dando erro

package associacaoExpandidoFunc;

public class TestaAssociacaoExpadidoFunc {

    
    public static void main(String[] args) {
       Funcionario F = new Funcionario("12345", "Maria", 
                     new Residencia(""), 
                     new Cargo("", 2000.00), 
                     new Veiculo(""));
       
       
       
       
        System.out.println(F);
    }
    
}

**Comment by fdaciuk** [comment]
Oi @C0381! Esse repositório é específico para tirar dúvidas sobre o conteúdo do curso JavaScript Ninja, ok? =)
